### ISSUE TITLE
Furniture usage

### ISSUE THREAD

**Issue by adamkad1** [DFHack/dfhack#1000]
Trying to eat on a seat only only works (can put item into reaction) when its in inv, not in hands, and it puts it into "hauling" but then the timer is stuck at -1, like plant gathering
Trying to sleep in bed will be interrupted because dangerous -unconscious (this kinda makes sense... or does it?) after pressing "." (and "," too mayby?)

**Comment by adamkad1** [comment]
Seems like the bed thing is just related to races that dont need to sleep.  And another thing, bookcases cant be built even though they can be made

**Comment by lethosor** [comment]
Is this even a DFHack bug?

**Comment by warmist** [comment]
I think this is about advfort?

**Comment by lethosor** [comment]
Needs more details for us to reproduce - let us know if the issue is still occurring.

**Comment by adamkad1** [comment]
Heavens above, i havent played dwarf fortress for like 5 years or so... good to know someone is still taking care of this though
