### ISSUE TITLE
0.43.05-alpha1 libdfhack.so symbol lookup error (x64)

### ISSUE THREAD

**Issue by qwertyuiop924** [DFHack/dfhack#1008]
when I run dfhack, I get this error:

`./libs/Dwarf_Fortress: symbol lookup error: ./hack/libdfhack.so: undefined symbol: _ZNK6google8protobuf11MessageLite25InitializationErrorStringEv`

I am running ArchLinux, with a 64bit version of both Dwarf Fortress and DFHack, both installed by hand from latest, not from the AUR or from the official repos. I don't have any other relevant information, AFAIK, but if you want to know any other system info, I would be glad to provide it.

**Comment by lethosor** [comment]
It looks like DFHack can't find a protobuf symbol. Can you check that libprotobuf-lite is present in the hack folder in your DF folder, and that libdfhack is linking to it?

**Comment by qwertyuiop924** [comment]
libprotobuf-lite is within the hack folder. However, according to ldd, libdfhack is linking to the system libprotobuf-lite in /usr/lib. I changed the line 62 of ./dfhack from

`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"./hack/libs":"./hack"`

to

`export LD_LIBRARY_PATH="./hack/libs":"./hack":$LD_LIBRARY_PATH`

Which fixed the problem. I would recommend considering changing this upstream, as it will probably save a lot of people a lot of confusion (for instance, this would stop dfhack from binding to the system liblua or libruby), and is probably a sensible default. However, I don't know enough about DFHack to say for sure, and it's ultimately your decision.

**Comment by lethosor** [comment]
Apparently that dates back to https://github.com/DFHack/dfhack/commit/0808c9c0abac980bf14258a7a1390b6d2ad5fd34#diff-83a88bce58b3e1d41a25bf06cadd51acR38, so changing it is probably fine. (There are some other more recent changes that allow things like LD_PRELOAD to be customized, but I'm pretty sure this doesn't affect that.)

**Comment by qwertyuiop924** [comment]
thanks!
