### ISSUE TITLE
Linking against system tinyxml seems to cause immediate segfault on 0.43.05-alpha1

### ISSUE THREAD

**Issue by TC01** [DFHack/dfhack#1009]
I went to upgrade my packages to the 0.43.05 alpha and found that, while things compiled, attempting to launch dfhack immediately segfaulted:

```
$ dfhack
Sound devices available:
OpenAL Soft
Picking OpenAL Soft. If your desired device was missing, make sure you have the appropriate 32-bit libraries installed. If you wanted a different device, configure ~/.openalrc appropriately.
Perfect OpenAL context attributes GET
Loading bindings from data/init/interface.txt
New window size: 640x300
Font size: 8x12
Resizing grid to 80x25
Resizing font to 8x12

Resetting textures
/home/bjr/.dwarffortress/dfhack: line 66: 13880 Segmentation fault      (core dumped) setarch i386 -R env LD_PRELOAD="$PRELOAD_LIB" ./libs/Dwarf_Fortress "$@"
```

After some trial and error I eventually traced the problem to me setting -DEXTERNAL_TINYXML in the build process. Disabling that flag and using the included tinyxml sources seemed to have solved the issue.

This is obviously a low-priority issue but I figured I should file a bug. Poking briefly around the source tree it's not immediately clear to me what's changed to cause this. What version of tinyxml does dfhack bundle?

**Comment by lethosor** [comment]
```cpp
const int TIXML_MAJOR_VERSION = 2;
const int TIXML_MINOR_VERSION = 5;
const int TIXML_PATCH_VERSION = 3;
```
This appears to be https://sourceforge.net/projects/tinyxml/, which is the original TinyXML (I think), *not* TinyXML2.

I don't imagine we depend heavily on a specific version of TinyXML, so upgrading shouldn't be too bad if that would help.

**Comment by lethosor** [comment]
I wouldn't expect this to be the case, but is it possible that DFHack is still using its own TinyXML headers? I don't know why that wouldn't show up before 0.43.05, though, unless your system TinyXML isn't the same architecture as DFHack and CMake is switching things up on you.

**Comment by TC01** [comment]
Hm, I suppose it's possible that the wrong headers are being picked up, but yeah, I'm not sure why that wouldn't have been an issue before this. I did double-check to make sure the 64-bit tinyxml is being detected properly by cmake: ```TinyXML_LIBRARY:FILEPATH=/usr/lib64/libtinyxml.so``` is definitely getting set.

(I should probably have mentioned this was with 64-bit DF + DH in the initial report, my bad).

The last version of the original tinyxml looks to have been 2.6.2 back in 2011; that's what's packaged in Fedora. Given that tinyxml2 is now a thing I'd guess this is likely to be the last release for the foreseeable future. In which case it might make sense to upgrade in dfhack anyway?

I can attempt building the dfhack tree with (bundled) tinyxml 2.6.2 sources and see if that changes anything.

**Comment by TC01** [comment]
Hm... building dfhack against a bundled copy of tinyxml 2.6.2 seems to work just fine, but building with -DEXTERNAL_TINYXML still causes a crash (on 64-bit) even when building by hand and not using RPM.

I also tested running ```rm depends/tinyxml/*.cpp depends/tinyxml/*.h``` before the build to ensure we weren't accidentally linking against the bundled tinyxml and it didn't fix the issue either.

**Comment by lethosor** [comment]
Which compiler are you using?

**Comment by TC01** [comment]
gcc 6.3.1, which I realize is much newer than the recommended compiler (but that's the current version of gcc on Fedora-- I'm also using it to build dwarffortress's libgraphics.so, and that appears to be working alright).

I can test an older gcc and see if that works any better.

**Comment by lethosor** [comment]
I mainly wanted to make sure it wasn't clang or something.
One possibility is the string ABI incompatibility. Maybe try compiling with `-D_GLIBCXX_USE_CXX11_ABI=0`? I would expect any issues related to that to result in linker errors, though.

**Comment by abbradar** [comment]
I can confirm that this this bug is fixed by using `-D_GLIBCXX_USE_CXX11_ABI=0`.

**Comment by lethosor** [comment]
Thanks! That does appear to be in https://github.com/svenstaro/dwarf_fortress_unfuck/blob/d6a4ee67e7b41bec1caa87548640643db35a6080/CMakeLists.txt#L6, so that could explain why libgraphics was working.

**Comment by TC01** [comment]
> I can confirm that this this bug is fixed by using -D_GLIBCXX_USE_CXX11_ABI=0.

It seems like this is already set by default when building with gcc 5.0 or above in dfhack? [See here](https://github.com/DFHack/dfhack/blob/master/CMakeLists.txt#L24).

Is there somewhere else I need to set this flag?

@abbradar: what version of gcc did you use to build dfhack with -DEXTERNAL_TINYXML and have things work?

**Comment by lethosor** [comment]
I'm talking about compiling tinyxml with that flag.

**Comment by TC01** [comment]
Oh! Yeah, that makes sense. I can now also confirm that that works.

Good to know, although that's not really an option for Fedora packaging. Seems like until Toady updates to gcc > 5.0 (assuming this ever happens) I'll just keep the bundled copy of tinyxml around.

What I will do is send in a PR to update the bundled sources to the latest (final) tinyxml release, as I mentioned above.

**Comment by lethosor** [comment]
I think DFHack is doing as much as it can to detect GCC 5+ itself, so I'm going to close this. Thanks for #1033, though!
