### ISSUE TITLE
stockpiles fails to serialize furniture stockpiles

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#1013]
After ec222c0 (#964), trying to save the furniture stockpile in [this fort](http://dffd.bay12games.com/file.php?id=10161) results in the following error:

```
serialization failed: protobuf exception: CHECK failed: !coded_out.HadError(): 
```

This occurs on both 32 and 64-bit OS X.

cc @Ramblurr. I'll try to investigate this, but let me know if you have any ideas.

**Comment by lethosor** [comment]
Could be related to #779.

**Comment by Ramblurr** [comment]
Will look into this!

**Comment by lethosor** [comment]
Enabling the "furniture/siege ammo" category in 0.47.04-r2 (Linux) and attempting to save now gives a different error:
```
serialization failed: protobuf exception: CHECK failed: (bytes_produced_by_serialization) == (byte_size_before_serialization): Byte size calculation and serialization were inconsistent.  This may indicate a bug in protocol buffers or it may be caused by concurrent modification of the message.
```
The "sheets" category appears to be ignored entirely.

**Comment by lethosor** [comment]
Commenting out this line appears to fix the issue: https://github.com/DFHack/dfhack/blob/0.47.04-r2/plugins/stockpiles/StockpileSerializer.cpp#L831

**Comment by Ramblurr** [comment]
Thanks @lethosor !
