### ISSUE TITLE
exportlegends plus crash (0.43.05)

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#1017]
Reported on the forums: http://www.bay12forums.com/smf/index.php?topic=139553.msg7262531#msg7262531

http://dffd.bay12games.com/file.php?id=12556

**Comment by ebrayton** [comment]
exportlegends had a similar crash for me on Linux 64-bit (Debian-based) in alpha 4. It seems to have been in the maps part, though. Should I post my save and details here or open a new issue?

**Comment by lethosor** [comment]
Is it possible that it's related to #958? Does it crash if you don't use the script? Even better, does it crash if you export all of the maps without DFHack? (I think there are only 10-20, but if there are more than I'm remembering, don't feel a need to export all of them manually.)

**Comment by ebrayton** [comment]
Hmm, it could be possible. I'd have to have a bit more time to dig into that thread and try out what's in there to be sure, but it doesn't crash if I export all the maps individually. I just went through all of them and exported one by one and it was fine. Then I moved those .bmps into another folder and tried with dfhack and got this:
```
[DFHack]# exportlegends maps
    Exporting:  Standard biome+site map map
[DFHack]# Segmentation fault
```

**Comment by ebrayton** [comment]
A newly-generated world does the same thing. Here's the original save: http://dffd.bay12games.com/file.php?id=12683

**Comment by sparkybear** [comment]
@ebrayton when you're running the export, open a task manager/resource monitor and just verify how much memory DF is using compared to what your total available is. Your system is going to be reserving memory for other things, and may still be limiting the amount of memory DF can use so it's probably worth checking out regardless of being on x64 and linux.

**Comment by ebrayton** [comment]
@sparkybear Thanks. I just tried it with the system monitor open. Before I run exportlegends it shows about 1.6GB in use. `exportlegends maps` fails as above almost instantaneously and I don't see any spike (or even blip) in memory usage. I do only have 4GB total in this old machine, though.

`exportlegends all` gives varying errors once it gets to generally the same area. That is, toward the beginning of the export maps section.

Let me know if there's anything else I should try or if it's probably just my system.

**Comment by sparkybear** [comment]
That's your problem. You are running out of memory on your machine.

**Comment by lethosor** [comment]
Forgot to ask earlier - is there anything at the bottom of stderr.log?

Since this is on 64-bit Linux, I think it's unlikely that you're running out of memory. Even if you run out of physical memory, DF should start swapping instead of crashing (unless you run out of swap space too).

**Comment by sparkybear** [comment]
He's only running 4GB total on his machine.

**Comment by sparkybear** [comment]
Sorry, hit reply too early. TheOS will reserve about 2GB for critical
functions and then allow the rest to be allocated to whatever needs it. It
should do that intelligently and should take advantage of the swap
partition as you mentioned. Regardless of the architecture, the OS is still
reserving most of the memory available on the system and can't allocate a
larger address space for DF with that limitation. DF could also have issues
of not being able to read and write to the swap space quickly enough to
work around the limitation of the system.

**Comment by lethosor** [comment]
Yes, but DF shouldn't crash unless the OS runs out of memory *and* swap space. In that case, there might be something that shows up in stderr.log. @ebrayton, have you seen anything there?

**Comment by ebrayton** [comment]
Just to clarify, because I realize that I might've been unclear: 1.6 GB total was in use by the system and DF once in legends mode.

Also, when I do `exportlegends all`, the total usage increases as it goes along, from 1.6 GB up to 75% of what I have, and then when it gets to the `maps` portion, it dies. So, given that it's fine using more memory for other aspects, it's suspect that it'd die so suddenly when I just do `maps`.

@lethosor There is nothing remarkable at the bottom of stderr.log. The last 5 lines are:

```
Invoking: gui/load-screen enable
<vtable-address name='viewscreen_movieplayerst' value='0x7ffff6db9670'/>
Invoking: gui/prerelease-warning
loaded map in prerelease build
Invoking: exportlegends maps
```

---

I don't know if this is helpful or just a red herring, but when I do `all`, it goes fine until this point (I added `keys` and `screen` print statements to the gui.lua):
```
<viewscreen_legendsst: 0x7fff848ded30>
1                      	 = 238
<viewscreen_legendsst: 0x7fff848ded30>
1                      	 = 28
<viewscreen_legendsst: 0x7fff848ded30>
1                      	 = 6
<viewscreen_legendsst: 0x7fff848ded30>
1                      	 = 240
    Exporting:  Standard biome+site map map
<viewscreen_export_graphical_mapst: 0x7fff17055a40>
1                      	 = 1
[DFHack]# The futex facility returned an unexpected error code.Aborted
```

**Comment by lethosor** [comment]
I haven't been able to reproduce this. Let me know if it's still occurring in 0.43.05-beta2 or newer.

**Comment by lethosor** [comment]
Okay, I'm getting a crash in 0.43.05-r1 with exportlegends. I think I know what the problem is (the map export screen _closes_ after exporting one map now, so any attempt to access that screen later crashes). I'll try to fix it, but that part of the script is not very clear, so the fix may involve rewriting it.

**Comment by lethosor** [comment]
That seems to be the case in 0.43.03 too, though. I can't imagine why it would work in 0.43.03 at all, but maybe it's possible.

**Comment by lethosor** [comment]
Also, the layout for viewscreen_export_graphical_mapst is wrong:
```xml
        <int32_t name='rgb_buffer' comment='pointer to allocated buffer'/>
```
(int32_t? Really?)

**Comment by lethosor** [comment]
It looks like the only problem was `rgb_buffer`'s type. Fixing that means that moving the list cursor doesn't mess with in_export or (maybe) numtiles_map_height, which also fixed a crash I ran into when trying to export one map in DF after setting sel_idx.

**Comment by lethosor** [comment]
DFHack/df-structures@67f9e61
