### ISSUE TITLE
getplants duplicates cutting/gathering orders if run multiple times

### ISSUE THREAD

**Issue by PatrikLundell** [DFHack/dfhack#1018]
The plugin designates the specified plants for gathering every time the command is executed. However, the designations are converted into jobs and it appears the designations are then reset, so when the command is executed again a while later it will designate all the plants for gathering again, resulting in new jobs targeting the same tiles.
To avoid this, getplants would have to iterate over the df.global.world.job_list to find duplicates and refrain from designating those tiles again.

I found this when using a lua script based on getplants' logic to spare one of each kind of booze supporting fruit tree on my embark, running the script whenever I thought a bit too many new trees had popped up (and with a wood cutter doing other things mostly), and then saw my wood cutter cut a tree, walk away, return with a tree cutting order to the empty tile, walk away...
I've verified that "getplants CASHEW" repeated a few times with DF running in between resulted in multiple tree cutting orders for the same set of 3 tiles (the number of cashews I happened to have at the time). While I only tested with trees, I assume the logic is the same with shrubs.

**Comment by ab9rf** [comment]
This is closely related to the problem in #1014 and has to do with how Toady changed the way map designations are handled, somewhere in 0.40.x. Prior to 0.40.x, map designations persisted and map-related jobs (digging, tree cutting, etc) were spawned when a dwarf with the relevant labor enabled went looking for a job. Sometime after 0.34.11, Toady changed this: on unpause, map designations that become set while the game is paused are immediately cleared and converted into job postings. Setting new ones after that will be converted again into more job postings. The in-game map renderer checks the job posting queue when it determines if a map square should be shown as "designated".

The jobs are not posted to df.global.world.job_list initially; they're posted instead to df.global.world.job_postings. They get moved to the job list when a dwarf is actually assigned to the posting.

Getplants (and also autochop and likely many other plugins) are still relying on the map designations; anything that does so will probably behave unreliably. Anything that wants to _query_ map designations probably needs now to also scan both the job posting list and the job list for pending jobs. If Toady has a lookaside accelerator for this, I'm not aware of it.

**Comment by PatrikLundell** [comment]
Thanks for the background info. Interesting that the jobs appear in the job_list first. It definitely seems you need to scan both job lists and the map (in case the command is rerun while still paused). Interestingly enough, though, my modified script correctly blocked duplicating commands by scanning the job_list (only), even though I've only got a single wood cutter. I'm not saying the description is wrong, merely suggest that it might be a little more convoluted than a straight active assignment (such as some kind of validation having been performed. In the case of wood cutting, the cutter would need to "see" all legal cutting orders to select which one to tackle next). Regardless, checking both lists seems like the sound thing to do.

**Comment by ab9rf** [comment]
I'm not clear on when jobs from from the posting list to the job list. My research (related to bring labormanager up to speed on 43.03) is that jobs will appear on the posting list immediately, and will move to the job list if there is a unit that might possibly do them. 

There's a similar behavior with respect to hauling jobs now; before, they only appeared on the job list when a unit was actually assigned; now, they appear when a unit is available to whom they might be assigned. But if there are no unit with the requisite labor enabled, they appear not to get spawned.

Someone probably needs to dig through DF itself to understand exactly what happens when the core routines controlled by the "process_dig" and "process_jobs" global flags are called.

**Comment by PatrikLundell** [comment]
That description would explain what I've seen. Thanks.

**Comment by ab9rf** [comment]
I wouldn't close this just yet. We probably should add some utility routines to the DFHack core to deal with this issue, since this is an issue that arises across multiple plugins.

**Comment by PatrikLundell** [comment]
Oops!
I thought "Close and comment" meant close the window and issue a comment...

A utility would be useful if a sufficiently general way of searching for matches can be found. If exact matches is all that's required it might be easy, but if it should take partial matches and other types of clashes into consideration it might be messy. Then that utility would still need to be called from each plugin.

**Comment by lethosor** [comment]
This should be fixed in the next release, along with similar autochop issues.
