### ISSUE TITLE
autogems should be able to exclude rock crystal

### ISSUE THREAD

**Issue by TV4Fun** [DFHack/dfhack#1027]
I've noticed that autogems, when enabled, creates jobs to cut rock crystal. I would prefer to make the rock crystal into crystal glass rather than cutting it. Is there a way to disable this?

**Comment by ab9rf** [comment]
This is not a terribly onerous addition, but before I essay it, are there situations in which a player might want to exclude other gems? Adding a single additional control to allow excluding rock crystal (or, actually, gems that have the "[CRYSTAL_GLASSABLE]" raw tag) would be much easier than setting up a UI to allow the player to arbitrarily control which gems are autocut.

**Comment by eswald** [comment]
Currently, there's no interface to disable particular gem types, but autogems does respect stockpile links.  If each jeweler's workshop has at least one gem stockpile set to give to it, and none of those stockpiles accept rock crystal, then autogems will stop creating jobs to cut rock crystal.  (Except perhaps for rough gems already on that stockpile, until they get moved elsewhere.)

**Comment by lethosor** [comment]
> Adding a single additional control to allow excluding rock crystal (or, actually, gems that have the "[CRYSTAL_GLASSABLE]" raw tag) would be much easier than setting up a UI to allow the player to arbitrarily control which gems are autocut.

Too late, I'm afraid:

![](http://i.imgur.com/qwvck64.png)

The "rock crystal" option does check for CRYSTAL_GLASSABLE - thanks for that suggestion, by the way.

**Comment by lethosor** [comment]
Nope. That's why this hasn't been closed yet. I didn't get around to supporting this in the plugin itself yet (the UI is just a script) or figuring out how to save the restrictions.

**Comment by lethosor** [comment]
Merged, appears to be working
