### ISSUE TITLE
misery status

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#1037]
Currently doesn't compile due to thought-related changes in 0.40.

#1011

**Comment by expwnent** [comment]
I'm fine with it being deleted. I don't think many people used it, and if it's going to be redone it'll pretty much have to be redone from scratch anyway.

**Comment by lethosor** [comment]
The main issue appears to be the removal of `status.recent_events`. I was thinking of investigating how add-thought.lua works and trying to apply that to misery, but if that's too hard, getting rid of the existing misery.cpp is fine with me too.

**Comment by lethosor** [comment]
It seems to be working:

![image](https://cloud.githubusercontent.com/assets/3719547/21076713/b8cf91e8-bf00-11e6-8ab8-562cee644175.png)
![image](https://cloud.githubusercontent.com/assets/3719547/21076513/540018e6-befb-11e6-835a-115656c2b64f.png)
![image](https://cloud.githubusercontent.com/assets/3719547/21076709/a7248a84-bf00-11e6-8b03-15bc8a9b7fae.png)
![image](https://cloud.githubusercontent.com/assets/3719547/21076724/e953444a-bf00-11e6-8065-cbe4864d95cb.png)

 Stress takes some time to kick in, followed by other interesting effects:

![image](https://cloud.githubusercontent.com/assets/3719547/21076704/707658dc-bf00-11e6-8f16-f4fff1b23a95.png)

**Comment by expwnent** [comment]
Cool, thanks!

**Comment by Tachytaenius** [comment]
Was just looking at this plugin in my v47 install to see if I could challenge myself a bit since everyone is permanently super happy in many of my forts... and I must say, the screenshots are quite funny. Is "3:276" a cat??
