### ISSUE TITLE
Manipulator crash - assign profession when none defined

### ISSUE THREAD

**Issue by quietust** [DFHack/dfhack#1040]
1. Start Dwarf Fortress such that Manipulator has no custom professions defined (i.e. the "professions" subdirectory is empty or nonexistent)
2. Load a fortress and open Manipulator
3. Press "p" to apply a profession - the screen will say "No saved provessions"
4. Press Enter.

Offending code: https://github.com/DFHack/dfhack/blob/master/plugins/manipulator.cpp#L1013

**Comment by lethosor** [comment]
Looks like it was unintentionally introduced in 198571dca316f6ede36bb6e16fd868f1e155a09b
