### ISSUE TITLE
Error from stockflow

### ISSUE THREAD

**Issue by ab9rf** [DFHack/dfhack#1044]
After saving and reloading a fort in which stockflow had been in use, got the following error some time after unpausing:

```
C:\Users\Kelly\df_43_05_win\hack\lua\plugins\stockflow.lua:1097: Cannot write field manager_order.amount_left: integer expected.
stack traceback:
        [C]: in metamethod '__newindex'
        C:\Users\Kelly\df_43_05_win\hack\lua\plugins\stockflow.lua:1097: in function 'plugins.stockflow.create_orders'
        C:\Users\Kelly\df_43_05_win\hack\lua\plugins\stockflow.lua:91: in function 'plugins.stockflow.finish_bookkeeping'
```
Doesn't crash, but the expected jobs are not added. The message recurs each time the bookkeeper updates stock records.

Stockflow was working prior to the save/reload.

DF 0.43.05, Win64, dfhack 0.43.05-alpha3. Save available upon request.

**Comment by ab9rf** [comment]
Update: on a newly created fort, this error occurred when I first used stockflow, even though that fort has never been saved and reloaded. It's possible that in my first fort, I had not actually used stockflow before the save/load.

**Comment by ab9rf** [comment]
Additional information: debugging has determined that "amount" is a floating point value at line 1097; the type mismatch is what causes the exception.

**Comment by lethosor** [comment]
Lua 5.3 has a separate integer type (internally, at least), but we upgraded to 5.3 before the first 0.43.05 release.
