### ISSUE TITLE
stocks: single-stockpile inventory (q-i) shows more than just the inventory of that stockpile

### ISSUE THREAD

**Issue by ab9rf** [DFHack/dfhack#1045]
The stockpile-specific inventory (q-i) provided by stocks appears to show the entire fort inventory, not merely the inventory of the requested stockpile.

DF 0.43.05, Win64, DFHack 0.43.05-alpha3

**Comment by lethosor** [comment]
@ab9rf I'm having trouble reproducing this in 0.43.05-beta1. Do you have a save where it happens (and does it still occur)?

**Comment by ab9rf** [comment]
I haven't been able to reproduce it since either, and I'm no longer sure which save it was that had this. Feel free to close as "cannot reproduce". There might still be a bug, but I can't find it and if there is it requires "obscure circumstances" to make happen.

**Comment by lethosor** [comment]
Feel free to reopen if it happens again.
