### ISSUE TITLE
Access violations inside ruby cause a whole-app quit

### ISSUE THREAD

**Issue by ab9rf** [DFHack/dfhack#1048]
Memory accesses from inside Ruby script code that cause an access violation cause an appquit rather than an appcrash. This means that something is catching them and choosing to exit the entire app instead of allowing the exception to reach the top of the stack (which would cause the runtime to cause a crash and allow a JIT debugger to launch). If we can catch them and exit, why can't we catch them and resume?

Memory accesses that cause access violations from inside ruby should therefore be caught and the ruby executive reset.  The Lua interpreter, if I'm not mistaken, already does this.

**Comment by lethosor** [comment]
The Lua interpreter doesn't do this. It can catch any C++ exception, but (currently) not signals.

**Comment by lethosor** [comment]
I'm getting a normal segfault on OS X. When BenLubar and I were researching 4dff21897650e97aadd217bc1510a27d2a4780ba, we ran into [this function](https://github.com/ruby/ruby/blob/97819765a6530004d2dc42bc175dc497cb22a34b/thread_win32.c#L738-L745) in libruby, as well as [this](https://github.com/ruby/ruby/blob/9d09240d9e329bbe5a8168dd850f5bb3549fbaa9/eval_intern.h#L95), which imply that there's some sort of custom Windows-specific segfault handling in libruby. I'm not sure that's something we should interfere with.

**Comment by bitassassin** [comment]
Heyo,

These access violations are occurring at init on my machine. If I remove the file libruby.dll, I can play the game. Otherwise, debugging shows a first and last chance exception for an 0x0 access violation. The violation occurs pretty much instantly after ruby is loaded, and quits. There isn't any reference to the failure in any logging either.

If the idea stated here was implemented, I'd at least be able to get more insight into the cause.

**Comment by lethosor** [comment]
That's not what this issue is about. It's about buggy Ruby scripts (e.g. ones that dereference invalid DF objects) catching the segfault signal somehow.

Some details about your system would help. What Windows version? What DFHack version and build (32/64-bit)? Did you replace libruby.dll?

**Comment by bitassassin** [comment]
Apologies for misunderstanding.

Windows 10 Pro 64-bit v.1709 build 16299.431
DFHack build 0.44.10-r1-0-g8cb5e7fa (From PeridexisErrant's 0.44.10-r03 pack)
libruby: 2.0.0p648 (x64-mingw32)

Libruby is as packaged initially, last line in stderr.log before quit:
loaded plugin reveal; DFHack build 0.44.10-r1-0-g8cb5e7fa

Removing libruby.dll sidesteps the whole thing.

**Comment by lethosor** [comment]
You know, it's possible that the ruby segfault handler is installed before the crash, which would kind of make it the same issue. Can you try getting rid of all `.rb` files in hack/scripts and see what that does?

In any case, libruby.dll is not built by us (we just provide it), so there's really nothing we can do about issues with it. We have a pretty big Windows 10 user base, so I'm not sure why this would be the first time hearing about an issue like this.

**Comment by bitassassin** [comment]
Seems to occur with or without the .rb files.

It's weird to me too, as it nearly guarantees that the fault lies in my setup.

**Comment by bitassassin** [comment]
Ah, sorry to be a bother. Seems a windows reinstall fixed it. I had fudged something somewhere.
