### ISSUE TITLE
Infinite loop in stockflow

### ISSUE THREAD

**Issue by ab9rf** [DFHack/dfhack#1051]
I'm not sure what conditions prompted this, but while investigating a hung DF process, I determined that the hang was caused by a fairly tight loop while evaluating Lua code called from stockflow. The C++ call stack indicates that the entry point was the `start_bookkeeping` method.

I don't know enough about the innards of the Lua interpreter to be able to tell what it's doing beyond this.

**Comment by lethosor** [comment]
If it's a loop in Lua, `dfhack-run kill-lua` should stop it, by the way.

**Comment by ab9rf** [comment]
closing as stale
