### ISSUE TITLE
Autobutcher in Linux 64bit DF Hack alpha3 not working.

### ISSUE THREAD

**Issue by Castaras** [DFHack/dfhack#1053]
Pressing shift and B in the animal menu causes the following error to appear in the DF Hack console.
```

...Dwarf Fortress/df_linux/hack/scripts/gui/autobutcher.lua:163: attempt to call a nil value (field 'autobutcher_getSettings')

stack traceback:

	...Dwarf Fortress/df_linux/hack/scripts/gui/autobutcher.lua:163: in method 'initListChoices'

	...Dwarf Fortress/df_linux/hack/scripts/gui/autobutcher.lua:97: in local 'fun'

	./hack/lua/class.lua:98: in upvalue 'invoke_after_rec'

	./hack/lua/class.lua:127: in global 'WatchList'

	...Dwarf Fortress/df_linux/hack/scripts/gui/autobutcher.lua:662: in local 'script_code'

	./hack/lua/dfhack.lua:562: in function 'dfhack.run_script_with_env'

	(...tail calls...)
```

Using Ubuntu Mate, 64bit version X(can't remember exact name), with 64bit DFHack 43.05alpha3.

**Comment by ab9rf** [comment]
It should be noted that this is solely a bug in the autobutcher Lua GUI script. The autobutcher plugin itself works just fine.

**Comment by lethosor** [comment]
What's the status of the `zone` plugin? (Run `plug zone`)

gui/autobutcher uses the zone plugin under the hood, and that plugin could have failed to load due to a couple missing globals on 64-bit Linux.

**Comment by ab9rf** [comment]
Additional information: the autobutcher gui works in Windows 64 bit, which is additional evidence for @lethosor's conclusion that this is due to missing globals on 64-bit Linux.

**Comment by lethosor** [comment]
If you run `load zone`, you should get a list of the specific ones `zone` needs that are missing.

**Comment by Castaras** [comment]
Plugin zone is missing required globals: ui_building_assign_type, ui_building_assign_is_marked, ui_building_assign_units, ui_building_assign_items

**Comment by lethosor** [comment]
Works for me after d18beb8.
