### ISSUE TITLE
Planning Mode build jobs problem

### ISSUE THREAD

**Issue by aesguitar** [DFHack/dfhack#1058]
In a few different worlds so far, anytime I use planning mode to build things (beds, chairs, doors, etc...), the job immediately shows up as suspended and the items are never built. I'm using the default options in planning mode. Manually trying to unsuspend the jobs or using "unsuspend" and "resume" all do nothing, however manually building the items via the normal mechanic works. I tried getting it to work both before and after having the necessary items available. I'm using the current release version of dfhack with workflow disabled.

**Comment by lethosor** [comment]
What is the "current release version"? 0.43.03-r1? 0.43.05-alpha4?

**Comment by aesguitar** [comment]
0.43.03-r1

**Comment by aesguitar** [comment]
![untitled picture](https://cloud.githubusercontent.com/assets/6676966/22037849/ee1dea6e-dcc6-11e6-9a23-6e012f5b69ea.png)

**Comment by lethosor** [comment]
It's normal for them to show up as suspended, but they should be unsuspended and built eventually by buildingplan. Do you have dwarves with the necessary labors available?

**Comment by aesguitar** [comment]
Ok, derp on my end I guess... It had sat there for a few minutes with no action on the chairs and then they were built. -_-

 In a previous save, I had several dwarves with just furniture hauling enabled with beds, doors, etc available and they just sat idle for a couple seasons before I manually did the jobs.
