### ISSUE TITLE
liquids/tiletypes prevent DF from closing

### ISSUE THREAD

**Issue by epsilon-phase** [DFHack/dfhack#1066]
If the liquids prompt is left open and you attempt to close the game, the game refuses to close until you quite liquids.

I haven't tried it with any of the other commands with their own prompts.

This really isn't too much of a serious problem, it's easy to get out of, but I'd like to see it fixed.

**Comment by lethosor** [comment]
I think tiletypes has a similar issue.

**Comment by lethosor** [comment]
@jaked122 What platform(s) are you seeing this issue on? I'm getting it on OS X, and presumably Linux too, but haven't checked Windows.

**Comment by jaked122** [comment]
I'm on Linux 64 bit.

I don't recall if I saw this behavior on Windows when I used it

**Comment by expwnent** [comment]
I vaguely remember getting it on Windows a long time ago.

**Comment by lethosor** [comment]
The issue appears to be some thread waiting for the plugin to unload, so I don't think it's platform-specific. You can also produce this issue by running `unload tiletypes` from command-prompt or with dfhack-run while tiletypes is running.

**Comment by lethosor** [comment]
Fixed in #1304
