### ISSUE TITLE
Crash when building walls

### ISSUE THREAD

**Issue by FruitsPunchSamuraiOG** [DFHack/dfhack#1067]
When i go to build a wall with box select the game crashes and says:

`./dfhack: line 66:  8812 Segmentation fault      (core dumped) setarch i386 -R env LD_PRELOAD="$PRELOAD_LIB" ./libs/Dwarf_Fortress "$@"
`

It crashes immediately after selecting what materials to build with.

**Comment by lethosor** [comment]
Is this on 64-bit Linux. If so, it's already been fixed in #1059 (that fix will be in the next build, hopefully soon).

**Comment by FruitsPunchSamuraiOG** [comment]
Yeah it is x64 sorry about that, didnt see that issue posted
