### ISSUE TITLE
crash when zooming all the way out in linux. 

### ISSUE THREAD

**Issue by se5a** [DFHack/dfhack#1072]
Since the terminal output is pretty big I've put it in a gist: 
https://gist.github.com/se5a/d1458eb992d952692fb0294bb9d038c3

I'm using: 
DF 43.05 with 
mephs tileset: http://www.bay12forums.com/smf/index.php?topic=161047.0
hikops TWBT from here: https://github.com/mifki/df-twbt/issues/52

running linux mint x64.

steps:
0: start DF using dfhack
1: start/load a fort. 
2: zoom all the way out with the mouse wheel. 
3: crash. 
 
running DF without DFhack does not cause the crash. 
any info I've left out?

**Comment by lethosor** [comment]
What if you don't use TwbT?

**Comment by se5a** [comment]
Ah yes looks like its a TwbT bug. if I change to [PRINT_MODE:2D] I don't get the crash.
I'll move this over to TwbT.
