### ISSUE TITLE
[Build] Incorrect ELF class for stonesense and diggingInvaders in 64-bit Linux build

### ISSUE THREAD

**Issue by Ekdohibs** [DFHack/dfhack#1075]
In the official 64-bit Linux build (0.43.05-beta1), the files for the stonesense and diggingInvaders plugins are of class ELF32, instead of ELF64 like all others, preventing these plugins from being loaded.

**Comment by lethosor** [comment]
Neither of those plugins were included in 0.43.05-beta1. My guess is that you copied them over from an older (32-bit) DFHack version.

**Comment by Ekdohibs** [comment]
Hmmm, it must be that then, since I installed an incorrect version at first, thanks!
