### ISSUE TITLE
stonesense overlay crashes DF if TWBT is enabled

### ISSUE THREAD

**Issue by PeridexisErrant** [DFHack/dfhack#1078]
It would be nice to make this not crash, possibly just by checking the print mode and bailing out with an error message.

**Comment by lethosor** [comment]
The issue is that the print mode is indistinguishable from STANDARD in-game, although I suppose reading init.txt would work. I'd rather check if the plugin is enabled, but I don't think that would work, since TwbT doesn't use the normal plugin enable/disable API.

**Comment by warmist** [comment]
There is a renderer header that has special value. We could check that. Though not sure if it would not be out-of-bounds if the renderer is not TWBT. See here https://github.com/mifki/df-twbt/blob/master/renderer_twbt.h#L65

**Comment by lethosor** [comment]
Yeah, I'm concerned about that potentially breaking if TwbT isn't enabled. It might be possible to get the renderer's class name using DFHack - doReadClassName() tends to produce somewhat-mangled names for non-DF classes (e.g. `ack21dfhack_lua_viewscreenE`), but it should at least contain `renderer_cool` somewhere.

**Comment by warmist** [comment]
Could it be that https://github.com/DFHack/dfhack/blob/98893793bd19d359b75771279d694bff7dd34ede/library/Process-windows.cpp#L349 this skips the .dfh part instead in that case? Ofc. it depends on mangling but we could have some sort of read full classname thing.

**Comment by lethosor** [comment]
No, on *nix it skips non-lowercase letters: https://github.com/DFHack/dfhack/blob/98893793bd19d359b75771279d694bff7dd34ede/library/Process-darwin.cpp#L124
I think doReadClassName's result should *contain* `renderer_cool`, at least, so that could be enough.

**Comment by warmist** [comment]
Heh, that "FIXME BAD" above though :D

**Comment by lethosor** [comment]
@PeridexisErrant does it work with PRINT_MODE:STANDARD?

**Comment by PeridexisErrant** [comment]
Hmm, looks like we have a variety of interactions depending on the print mode.  I also seem to have had something depend on whether `ssense overlay` is invoked before or after loading a fort, but have not been able to replicate that.

- `PRINT_MODE:2D` - works as expected.

- `PRINT_MODE:STANDARD` and `PRINT_MODE:TWBT_LEGACY` seem to be equivalent.  DF does not crash, but no location changes are displayed in the viewport - the view is stuck wherever ssense was invoked, and only the hover from mousequery and z-level indicators indicate that the viewport is moving.

- In `PRINT_MODE:TWBT`, `ssense overlay` makes DF crash when a fort is loaded (if invoked from the starting menu), or immediately if invoked with a fort loaded.

**Comment by lethosor** [comment]
Well, since STANDARD and TWBT/TWBT_LEGACY are all broken, the easiest option is to disable STANDARD, which has the effect of disabling all three of those.
