### ISSUE TITLE
"prefchange help" should be a nondestructive operation

### ISSUE THREAD

**Issue by escondida** [DFHack/dfhack#1080]
Curious about the script and its options, I ran "prefchange help", which changed the preferences of every dwarf in the fort rather than printing usage information as expected.

**Comment by lethosor** [comment]
It looks like that should do nothing at all, actually: https://github.com/DFHack/scripts/blob/95dbacdab21ce24dbc25aacc8173d370b099bce9/prefchange.lua#L351
Only recognized options should do anything. Did you notice any changes to your dwarves' preferences? I'll add support for `help`, anyway.

**Comment by escondida** [comment]
Yeah, every dwarf liked weapons, armor, steel, iron, and plump helmets after that; it explicitly went through every dwarf, announcing that their preferences were changed.

Thanks (-:

**Comment by lethosor** [comment]
Huh, it doesn't do that for me (and gives no output). What DFHack version are you using? Can you run `type prefchange` and tell me what it says?

**Comment by lethosor** [comment]
@escondida are you using any mods?

**Comment by lethosor** [comment]
I added a "help" option, but I strongly suspect you're using a third-party version of this script, so my change won't help unless you can track down whoever's distributing that version of prefchange.lua and get them to fix it too.

**Comment by escondida** [comment]
Hey, lethosor. I missed your earlier question, sorry. Thanks for implementing help anyway, but here are the belated answers:

It's the one shipped with dfhack as of 0.34.11-r5-2813-g098481c6 (19th April '17, branch "develop", full commit hash 098481c60d2cd55c26b85dff8380aa55a381e52e)

"type prefchange" ⇒ prefchange is a Lua script: /home/ivy/local/games/data/native/dwarffortress/hack/scripts/prefchange.lua

(~/.../dwarffortress is where df is, naturally).

**Comment by escondida** [comment]
And I didn't specify it above, but it's definitely the official dfhack repository (https://github.com/DFHack/dfhack.git); I've never even added another remote.

**Comment by lethosor** [comment]
What's the md5 of prefchange.lua?

**Comment by escondida** [comment]
md5:
9b382259750583a7241a33b13bbdf228	prefchange.lua

sha256:
dd472c98e53986457820111aa7673cd390b94d29d72518595aa60fb49a0756ff  prefchange.lua

**Comment by lethosor** [comment]
That looks right. I have no clue what the issue could be, because "help" looks like it should have been doing nothing, and it's doing nothing on my end before my changes. That is the same DFHack installation you were using before, right? Is the issue still occurring?

**Comment by escondida** [comment]
Bizarrely, I can't seem to reproduce it. I wish I'd kept a transcript of that session, because I distinctly remember staring at what I'd typed, staring at the output, and immediately coming here to report it.
