### ISSUE TITLE
had an issue with revflood

### ISSUE THREAD

**Issue by Amostubal** [DFHack/dfhack#1081]
Today was running test forts for various modifications I made this week... I cam across an interesting thing.  generally I just abandon and then reembark on the same location with a new race.  well sometimes areas that have previously been seen will refuse to reveal, so I use revflood.   Well this is the first time I was doing this on an abandoned world generated fort (I usually just pick a suitable area to test everything I want to test and dig a quick hole in the ground, speed test, and quit...).

well I'm not sure if its because world generated stairs are different from normal made stairs, but revflood would reveal the entire floor up to a stairway, then refuse to reveal the floor below.  I just went to the stair dropped (or rose) a Z and revflood again to get the next floor, but I've not had it do that to me before.  It was as if revflood doesn't see the stairway as a open passage way.

anyways, I just wanted to drop the note here.  I've had revflood reveal through stairs with no problem before, this is the first time I had it refuse to show through a stairwell, wondered if anyone else had such an issue?

**Comment by lethosor** [comment]
This sounds like #874. Can you see if those stairs are constructed? They should flash green "C"s if you press `d-n`, unlike dug stairs.

**Comment by Amostubal** [comment]
sorry for not getting back to you on this, been rather busy this last 8 days here.... I checked around in all my saves and I believe I've lost that map somewhere.... so Since I'm running some tests tonight on another issue that cropped up, I'll do an embark on a reclaim and see if I can get a similar issue and get back to you on that.  I would say right now, I don't think so... but I really dind't try to d-n anything on those levels, I just temp fixed it by ramping through from floor to floor.

**Comment by Amostubal** [comment]
And you are right... they are constructed stairwells... well thats really annoying... wish we could fix that.  I'm not as up on that bit of coding though to start looking into it right now... now must figure out what's going on in 2 other "masterwork" scripts...
