### ISSUE TITLE
Stonesense dylib version clash

### ISSUE THREAD

**Issue by Simons-Mith** [DFHack/dfhack#1083]
loading plugin stonesense
dlopen(/Applications/Games/Dwarf Fortress/hack/plugins/stonesense.plug.dylib, 6): Library not loaded: /usr/local/opt/freetype/lib/libfreetype.6.dylib
  Referenced from: /Applications/Games/Dwarf Fortress/hack/libs/liballegro_ttf.5.2.2.dylib
  Reason: Incompatible library version: liballegro_ttf.5.2.dylib requires version 20.0.0 or later, but libfreetype.6.dylib provides version 19.0.0
Can't load plugin stonesense

Above is from the stderr log file. Mac OS 10.9.5, dfhack 43.05.beta2

Sorry for terseness, captured error above and wanted to record it asap. Will try to followup with more info tomorrow.

**Comment by lethosor** [comment]
Try this (unzip it and move the .dylib into hack/libs)
[libfreetype.6.dylib.zip](https://github.com/DFHack/dfhack/files/969361/libfreetype.6.dylib.zip)

**Comment by Simons-Mith** [comment]
That's caused the error to change. So, progress, I think. It still can't load Stonesense, but now the log says

loading plugin stonesense
dlopen(/Applications/Games/Dwarf Fortress/hack/plugins/stonesense.plug.dylib, 6): Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
  Referenced from: /Applications/Games/Dwarf Fortress/hack/libs/libfreetype.6.dylib
  Reason: image not found
Can't load plugin stonesense

I don't mind downloading and installing libpng but I'm dubious about it being necessary. I'd have thought this machine ought to have sufficient png support already. So I'll leave things alone until you've have more chance to investigate. And I'll try not to do anything unilaterally that might muddy the waters.

**Comment by lethosor** [comment]
Yeah, that sounds like progress. I'm trying to recompile freetype without PNG support, to see if that works.

**Comment by lethosor** [comment]
Try this one:
[libfreetype.6.dylib.zip](https://github.com/DFHack/dfhack/files/971203/libfreetype.6.dylib.zip)

**Comment by Simons-Mith** [comment]
That's fixed it. I can stonesense now. Thank you.

**Comment by lethosor** [comment]
Cool. It seems to work for me (it doesn't break Stonesense any more, at least), so I'll include it in the next release.

**Comment by Simons-Mith** [comment]
Now that I can run Stonesense, I think these are probably separate issues, but I'll mention them here too:

None of the Stonesense keys appear to work, nor does the scrollwheel. I can navigate by mouse by left and right-clicking (how I'd generally use it), but I've just noticed I can't change z-levels.

Also, DF+Stonesense isn't quitting cleanly.

Will log these separately.

**Comment by lethosor** [comment]
Yeah, the input issue is reported in the Stonesense repo: https://github.com/DFHack/stonesense/issues/32

Not sure about the issue when quitting - what print mode are you using?

**Comment by Simons-Mith** [comment]
I was using Stonesense as a separate window. I don't use it as my main UI. I have NOT activated that 2D view setting (can't remember what it's called precisely).

**Comment by lethosor** [comment]
Overlay?

**Comment by Simons-Mith** [comment]
Yes, that. :-)

**Comment by lethosor** [comment]
This should be fixed in the next release.
