### ISSUE TITLE
DF + Stonesense not quitting cleanly

### ISSUE THREAD

**Issue by Simons-Mith** [DFHack/dfhack#1084]
(This is with the fresh dylib version  as supplied today to fix issue 1083)

What I do:

run dfhack
load fortress (created in 43.05), which starts out paused.
Run 'ssense' or 'stonesense' from dfhack command line

stonesense window comes up correctly centred on wherever in the fortress the cursor was set.

admire fortress

close Stonesense window.

Save game.

Select Quit from dwarf Fortress main menu

Dwarf Fortress still has the Stonesense icon, and it won't shut down until Force Quit.
At that point DF is forcibly removed and the dfhack terminal window reports this:

Stonesense launched
Using allegro version 5.2.2 r1
Stonesense shutdown.
Clearing all animal hospitals
[DFHack]# /Applications/Games/Dwarf Fortress/dfhack: line 15:  2031 Killed: 9               DYLD_INSERT_LIBRARIES=./hack/libdfhack.dylib ./dwarfort.exe "$@"

logout

[Process completed]

**Comment by lethosor** [comment]
This should probably be reported at https://github.com/DFHack/stonesense instead.

**Comment by Simons-Mith** [comment]
I was using Stonesense as a separate window. I don't use it as my main UI. I have NOT activated that 2D view setting (can't remember what it's called precisely)

[Thx, i'll report there too.]

**Comment by lethosor** [comment]
It's probably best to just have it there.
