### ISSUE TITLE
script <filename>

### ISSUE THREAD

**Issue by Amostubal** [DFHack/dfhack#1090]
Okay was playing around with odd and new commands I hadn't played with before and I came across this one in a description while hunting for a way to split up onLoad.init based on race through a call to another script...

well after much play time with the command I found it targets the main dwarffortress folder and that folder only.  considering that onLoad.init is usually in the raw folder.  This seems odd behavior,  I actually had to use script raw\<filename> just to get it to target files outside of dwarf fortress... Shouldn't any call to look for scripts to be run as init files,, be looking through the same folders in the same order that it does for init files:
1.The main DF directory
2.data/save/world/raw, where world is the current save, and
3.data/save/world/raw/objects

or is there a special way to call this to make it select the current world save?

**Comment by lethosor** [comment]
It's intended to run arbitrary files, not init files specifically, so I would expect it to treat paths as relative. It predates onLoad.init files, anyway (and those were originally just in the main DF folder). I doubt anyone is relying on the current behavior, though, so it's probably fine to change.

**Comment by lethosor** [comment]
Never mind, these scripts don't really keep track of their own directory. I suppose your suggestion would be more feasible to implement.

**Comment by Amostubal** [comment]
Well I see where it is located at, I just don't have that level of programming to write or test it... I really need to get back to learning C++... I've not even looked into the language since 2000... or longer.  Got to find a compiler etc... at least now the documentation is everywhere and I bet I can get a compiler easily (the last time I had one, it was on collection of CDs...).
