### ISSUE TITLE
autobutcher: ignore units with fertile eggs

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#1092]
Discussed [here](http://www.bay12forums.com/smf/index.php?topic=139553.msg7453545#msg7453545) on the forums.
I wasn't able to find anything in zone.cpp that looked like it dealt with pregnancy, but checking on pregnancy information may be faster than checking all buildings/eggs on the map, and it could apply to other pregnant units as well.

**Comment by dawnmist** [comment]
I _suspect_ that all that would be required here is to add a check for pregnancy_genes when collecting the units for PushProtectedUnits.

i.e. add `|| unit->pregnancy_genes` to the condition at https://github.com/DFHack/dfhack/blob/195db1bad9697f75672838127ad435112ee72491/plugins/zone.cpp#L3069-L3076

**Comment by ab9rf** [comment]
checking `unit->pregnancy_timer` is enough to detect if a unit is pregnant. egglayers are considered "pregnant" while brooding
