### ISSUE TITLE
exportlegends maps executes the first option for each map

### ISSUE THREAD

**Issue by juanminm** [DFHack/dfhack#1095]
When you open a world in Legends using normal methods or `open-legends` command, and you execute either `exportlegends maps` or `exportlegends all`, only the "-detailed.bmp" file gets exported over and over even if exportlegends says it is exporting the other ones.

This seems to affect at least since version 0.43.05-beta1, 0.43.03 worked correctly.

**Comment by lethosor** [comment]
This might be related to #1017.

**Comment by lethosor** [comment]
DFHack/df-structures@67f9e61 should have fixed this.

**Comment by juanminm** [comment]
I finally used the new version and can confirm it does work now! Thanks!
