### ISSUE TITLE
labormanager will reserve dwarfs to do tasks in parts of the fortress they can't reach

### ISSUE THREAD

**Issue by ab9rf** [DFHack/dfhack#1102]
Should probably try to use the pathing components (in map_block.path_tag to divide the fort into reachability segments and run the labor assignment algorithm once for each connected component that has at least one dwarf in it

**Comment by warmist** [comment]
Remember that those can change. I.e. unlocking door should recompute the path_tags

**Comment by ab9rf** [comment]
closing as stale
