### ISSUE TITLE
masspit.rb script causes crash

### ISSUE THREAD

**Issue by indivisible** [DFHack/dfhack#1110]
Using "masspit <zone number>" and then opening the zone's information screen (iP), or having a dwarf try to perform the job will crash DF. Tested on win 10, 64 bit DF 43.05 with dfhack 0.43.05-r1-0-g2396392b
 (latest LNP.)

Nothing relevant in the outputs.

Would a save file help?

**Comment by lethosor** [comment]
This may be related to #1107 
Try making this change to hack/ruby/ruby-autogen-defs.rb: https://github.com/DFHack/dfhack/commit/65382473f7a1cf9bf3ea6ce74ecc5078735324b6

**Comment by indivisible** [comment]
Uh, that might have to wait a day, I have no build env set up for dfhack at the moment.

**Comment by lethosor** [comment]
No, make the change to that file in your DFHack installation (it's not compiled, and I gave the path in your installation, which is different from its path in this repo).

**Comment by indivisible** [comment]
Right, that seems to fix it, thanks!

**Comment by lethosor** [comment]
Cool! It looks like that issue also affects `create-items` and `fix/loyaltycascade` (in addition to `levers` and `masspit`). There's some extra work to do for r2 still, but hopefully it'll be ready soon.
