### ISSUE TITLE
Mousequery: mouse pointer icon does not recognize non-ASCII graphics sets

### ISSUE THREAD

**Issue by MagboneD** [DFHack/dfhack#1113]
Windows7x64 Intel Corei7 32GB NVIDIA Quadro4000M
See attached .mp4 videos demonstrating the issue. 

When using mousequery with the standard ASCII tileset, the in-game mouse pointer will correctly correspond to the position of the System mouse pointer (see attched _Mousequery working.mp4_). 

When using TWBT graphics sets (in this case, Phoebus 16px, the mousequery pointer remains locked to the ASCII  resolution, which causes the pointer position to be incorrect and the box-select function of Auotmaterial to fail (see attached _mousequery fail.mp4_)

[Mousequery working.zip](https://github.com/DFHack/dfhack/files/1083255/Mousequery.working.zip)

**Comment by quietust** [comment]
I think you'll find that the problem is not the fact that the graphics set is non-ASCII, but the fact that TWBT **overrides** the tileset dimensions for the playfield and makes them different from what you've actually configured - if you use Phoebus 16px _without_ TWBT, it should work just fine.

**Comment by lethosor** [comment]
Exactly. Also, try using the modified mousequery plugin that TWBT distributes. An older version of a pack made by PeridexisErrant didn't include that plugin, which may be the cause of the issue you're having too. (A version he released today does include TWBT's mousequery, so you could try upgrading your pack too if you're using it.)

**Comment by MagboneD** [comment]
You are correct! Thanks!
