### ISSUE TITLE
repeat-utils functions can't cancel themselves

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#1122]
This was pointed out by [Atkana](http://www.bay12forums.com/smf/index.php?topic=164123.msg7497491#msg7497491) on the forums:

> ```lua
> local blah = 1
> local id = "foo"
> local repeatUtil = require 'repeat-util'
> 
> local function doStuff()
>     print("Blah: " .. blah)
>     blah = blah +1
>     print("Blah is now " .. blah)
>     if blah > 10 then
>         print("Blah is more than 10. Stopping.")
>         print("Has supposedly cancelled = " .. tostring(repeatUtil.cancel(id)))
>     end
> end
> 
> repeatUtil.scheduleEvery(id,50,"frames",doStuff)
> ```

This doesn't work because repeat-utils schedules the next call of doStuff() *after* doStuff() returns, regardless of what doStuff() does. Scheduling it before doStuff() could result in error message spam, but tracking calls to cancel() and avoiding rescheduling doStuff() if it cancelled itself could work.

**Comment by expwnent** [comment]
Yup, that's bad. Should be a simple fix. I'll try to fix it today.

**Comment by lethosor** [comment]
Fixed in #1131
