### ISSUE TITLE
The DFHack console can get its colors confused.

### ISSUE THREAD

**Issue by PatrikLundell** [DFHack/dfhack#1123]
I suspect the DFHack console thread has an unsafe handover between the command executed and DFHack's own prompt.
A couple of small scripts used to produce odd results (at least on my system):
```lua
function y ()
  for i = 1, 1000 do
  dfhack.printerr ("Do I bleed?")
  end
  dfhack.println ("What?")
--  error ("Not really...")
--  dfhack.println ("What?")
--  dfhack.println ("What?")
end

y ()
```
and
```lua
function z ()
  dfhack.color (COLOR_BLUE)
  dfhack.println ("What color is this?")
end

z ()
```
Each test is run on a freshly started DF (with an associated DFHack terminal). Script output were as expected unless noted.
- Running y causes the DFHack prompt to become red (actually light red), and if I run z after that I then get a blue prompt. Typing garbage (in blue) resulted in a red error message and a red prompt.
- Running z followed by y caused the final standard color output line from y to become blue followed by a blue prompt.

**Comment by lethosor** [comment]
The prompt color is weird. I haven't seen the prompt change color before, although I haven't tested it on Windows.
Here's the result of running y(), then z():
![image](https://user-images.githubusercontent.com/3719547/27736910-271a383a-5d74-11e7-87cf-693b301891db.png)

As for z() followed by y(), that looks intentional - when printerr() returns, it's supposed to restore the color of the console before it was called, not reset the color. See [here](https://github.com/DFHack/dfhack/blob/7b3efeafc9d8a8b6856a826755473236321958dc/library/ColorText.cpp#L126).

**Comment by PatrikLundell** [comment]
Sloppy reporting on my part. I should have mentioned that I'm using Windows 10.1 (and I'm also behind on DFHack, at alpha-2, 32 bit).

Well, the second result isn't what I would have expected, but testing it shows that this is the way it works without prior corruption as well.

However, I would have expected the DFHack prompt invocation to provide each script with a "standard environment" where e.g. the color setting for the next script would be returned to the standard one as part of the invoker's finalization regardless of how sloppy the previous script was.

**Comment by lethosor** [comment]
I suppose it could reset the color when invoking a command. That wouldn't help with some timeouts and other things, but it could avoid some issues.

**Comment by lethosor** [comment]
It does look like printerr() is resetting the color correctly when it wasn't set before (i.e. it's calling color(COLOR_RESET) instead of color(COLOR_WHITE) or something like that). My guess is that the colored prompt has something to do with the Windows console. Essentially, these two are the same, as long as the console wasn't colored before:
```lua
dfhack.printerr("foo")
-- and
prev = dfhack.color(COLOR_LIGHTRED)
print("foo")
dfhack.color(prev)
```

**Comment by PatrikLundell** [comment]
I agree it's probably not the printerr that's the culprit, but rather the console/script interaction. Since one script can influence a subsequent one with the prompt in between being unaffected (normally) there ought to be two color settings in operation in parallel: one for the console and one for scripts. The DFHack console competes with the error output (a lot of DFHack console prompts flashing by to be replaced by the next error output and a new prompt could be seen when using errors generation during rendering, but the script above writes too fast for me to see anything), so the DFHack console probably triggers the writing of a new prompt as soon as a script output action is finished, the next script output action then overwrites the prompt and triggers the display of a new prompt. However, if the console thread is sluggish the next script thread output may appear before the console one is finished, possibly resulting in the console color command to being written to the wrong pen state object (because the critical region isn't protected properly). Since it appears to happen on Windows only, it can be a bug in the console itself, or it can be Windows specific integration code (or something present for other OS' as well, but happening too infrequently to be detected due to OS timing).
A lot of speculation...

**Comment by lethosor** [comment]
> there ought to be two color settings in operation in parallel: one for the console and one for scripts.

What? Don't (most) scripts use the console? Any that don't wouldn't meaningfully be able to set output colors in any case.

I haven't looked into the console code much, especially on Windows, and it's pretty ancient. However, there's really just a single variable keeping track of what color the console output currently is. The actual color is supposed to get reset for prompts, as I understand it (I *think* color_ostream handles calls to dfhack.color(), which then get fed to the console, and the console then handles resetting the color for the prompt itself, but I could be wrong about that).

Do you see the same issue if you build a 1000+-line message, then use dfhack.printerr() to send it to the console all at once?

**Comment by PatrikLundell** [comment]
If script 1 sets the color to blue prints something and finishes, and the DFHack console prints a white prompt, while script 2's output becomes blue again without any color definition in the script there must be two color settings at play. So what I meant with one color for the console, I meant for the console's own output (the prompt). I know the console has another one as well, since if you try to execute garbage you get it in red. Of course, both the prompt and the error message outputs can be hard coded with what I called the script one being cashed while the console performs its own output, but then it shouldn't be possible to corrupt the prompt.
I'll be back with an update when I've tried 1000 line barfs.

**Comment by lethosor** [comment]
> there must be two color settings at play

What I was saying is that the console resets the color for the prompt. It also changes its color whenever it's told to by the color_ostream that controls it. As far as I know, there is only one color setting, which is held in the color_ostream instance. The color_ostream feeds each chunk of text to the console along with its color.

Anyway, it looks like the console resets its color every time before redisplaying the prompt on all platforms, so I'm not sure what's going on here. Maybe try something shorter too, if you can (say 500 lines, or a large number that's small enough that you can scroll back all the way to the command you ran).

**Comment by PatrikLundell** [comment]
Yes, it did corrupt the prompt, which I wouldn't have expected.
`function Blue ()
  local l = "A junk line\n"

  for i = 0, 12 do
    l = l .. l
  end
  
  dfhack.printerr (l)
end

Blue ()`

(The name is selected to confuse the enemy..) This script resulted in a whole bunch of "A junk line" lines followed by a blank line and the DFHack prompt in corrupted red. I've only run it one. Hitting return on the console can result in the prompt returning to the normal color, but running z causes both the output and the prompt to turn blue. Hitting return once cause the prompt to return to normal again, another return resulted in a second normal prompt, but executing z again resulted in a blue prompt and hitting return again there resulted in the DFHack error message in blue followed by a normal prompt.
Somehow, there is a corruption happening that causes subsequent prompts to take on whatever color the script sets, but this color can be reset temporarily by hitting return again.

I changed the script above to iterate from 2 to 8. I than ran it without problems a few times (3-4? without starting a fresh console in between) and then finally got a corruption. Scrolling up showed that the prompt above was still the standard color, which I guess is what you wanted that test to check?

I did get a new idea: I output 1000 lines of "A junk line\n" using dfhack.println () and then ran a script that simply produced a single dfhack.printerr line, and the prompt turned red. This indicates you can get entanglement corruption just from normal output, without specifying any colors at all. When you do specify the color the entanglement manifests itself.

**Comment by PatrikLundell** [comment]
Another minor experiment: Changing the script that output a single error line to follow that line with a dfhack.prinln() one caused the color to return to normal (but the corruption is still present, waiting for an opportunity to show itself). This indicates that the color restoration done by printerr doesn't get effected unless there is another line of output (as in my code you commented upon where I did this manually just because of this failure of a change to take effect).

**Comment by PatrikLundell** [comment]
Hm, so the console seems to output <RESET COLOR><CR>{DFHack]#<Script_Color> ?
Would some of the symptoms go away if it was <CR><RESET COLOR> instead?

**Comment by lethosor** [comment]
There's not really any corruption here. The only issue is the prompt not being a consistent color. 

If anything, I would expect reversing the sequences to make the issue worse. However, this is dealing with a low-level Windows API, so who knows. What Windows version are you using, by the way?

**Comment by PatrikLundell** [comment]
Windows 10.1, auto updating as per the small soft one's whims...

**Comment by lethosor** [comment]
I managed to test this on Windows. Is it the *Lua* prompt changing color? I'm seeing that happening, but not the main DFHack prompt.

**Comment by PatrikLundell** [comment]
I'm not sure what a Lua prompt is, but assume you'd get one if you ran a command to turn the console into a Lua interpreter?
The prompt I refer to is the "[DFHack]# one appearing when you start DF (and the console) up, which is also the one I run scripts from.

**Comment by lethosor** [comment]
I'm referring to the "[lua]# " prompt you get when you run the `lua` command. I thought that's where you were running your functions from.

Anyway, I was able to reproduce this on Windows 10. Not sure if it applies to older versions or not.

**Comment by PatrikLundell** [comment]
I assume this also means you've essentially ruled out it affecting other OS'?
And thank you for spending all this time on a rather minor issue!

**Comment by lethosor** [comment]
On non-Windows platforms, DFHack uses whatever terminal it was launched from. Most of those are pretty decent and don't have issues like this (I'm sure you could find one that did, but it wouldn't be standards-compliant).

Unfortunately, I know very little about the Windows console API (the majority of that knowledge is what I picked up by skimming Console-windows.cpp earlier today), so I have no idea if this is an issue on our end or with Windows. Sure, it is a minor issue, but it's kind of annoying.

Just wondering - were you having this issue with color()/print()/color() before?

**Comment by PatrikLundell** [comment]
With "before" I assume you mean with an earlier Windows version? I'm not sure as I don't remember when I upgraded the Windows version, and I haven't messed with Lua scripts for that long (showbiomes is my first attempt larger than a page and the first post of that thread claims it was posted September 29 last year).
I have no recollection if the issue suddenly appearing, though: it's been a long standing annoyance.

**Comment by lethosor** [comment]
Oh, okay. You pointed this out when I pointed out printerr() and qerror(), so I wasn't sure if the issue was specific to those functions or not.

**Comment by ab9rf** [comment]
FYI, dfhack console on Windows has done this for as long as I can recall (at least 3 years), on both Windows 7 and Windows 10.

**Comment by PatrikLundell** [comment]
I've made some headway on the issue, but I'm not sure it's good enough.
According to this page [https://docs.microsoft.com/en-us/windows/console/writeconsoleoutputcharacter](url)
"The attribute values at the positions written to are not changed.", which matches what I've seen, i.e. the console behaves somewhat like a DFHack pen array (but with much worse control). However, just replacing usage of that function with the pair
`            SetConsoleCursorPosition(console_out, pos);
            WriteConsoleA(console_out, str, len - 1, &count, NULL);
`
doesn't work properly either, because that function apparently advances the cursor, causing the window to scroll down when the line is blanked out. My best work around is to create a special blanking function that uses WriteConsoleA up to the last character and then blanks the last one with WriteConsoleOutputCharacterA.
The results seems to be that the color contamination of the DFHack prompt is blocked, but the DFHack help text when typing garbage still takes on the "script assigned" color.

**Comment by PatrikLundell** [comment]
The following change gets rid of the color contamination caused by the "err" script:
In Console-windows.cpp function output, replace the call to "WriteConsoleOutputCharacterA" with
`            CONSOLE_SCREEN_BUFFER_INFO inf = { 0 };
            GetConsoleScreenBufferInfo(console_out, &inf);
            SetConsoleCursorPosition(console_out, pos);
            WriteConsoleA(console_out, str, len, &count, NULL);`

and I haven't been able to reproduce the original color confusion/bleeding with that code in place, but I am able to do it with the original code, so I suspect the random point at which contamination happens is caused by a race condition determining whether the output of the DFHack prompt ends up on a "new" line or reusing the line from the previous output.

The change causes characters placed into the screen buffer to always use the currently defined attributes, rather than keep the attributes that happened to be present at those locations.

I suspect that if dfhack were to support console background colors (I couldn't find this with a quick look), the clearline function would have to be updated to replace attributes, as you could keep the wrong background color otherwise.

And, while changing the file, remove the semicolon from the end of "#define MAX_CONSOLE_LINES 999;" as that makes MAX_CONSOLE_LINES useless as a constant where you don't actually want a semicolon at the end of it [such as trying to calculate how far away from the end of the buffer you are] (or, if you do want to keep it, remove the redundant semicolon after the usage of MAX_CONSOLE_LINES).
