### ISSUE TITLE
Most of DFHack's stderr gets sent to "stderr.txt" on Windows

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#1124]
I've seen a few reports of this in various places, but didn't think it was possible because absolutely *nothing* in DFHack contains the string "stderr.txt". I got it to happen with a clean install of 0.43.05-r1 on Windows 10, though.

Specifically, stderr.log contains the following:
```
FirstCall()
Initized HOOKS!
```
and stderr.txt contains everything else, starting with:
```
DFHack build: 0.43.05-r1-65-gcc0220f0
```

It would be good to fix this, because there's no reason DFHack should be logging to that file and it makes troubleshooting harder.

**Comment by lethosor** [comment]
A string dump of Win64 0.43.05 contains these strings:
```
/stdout.txt
/stderr.txt
```
It would probably be possible to call freopen() again in Core::Init(), since DF appears to be opening these files before Core::Init() is called.

**Comment by expwnent** [comment]
I had always assumed this was intended behavior, so that logging could be done without spamming the console.

**Comment by lethosor** [comment]
This is separate from the console. DFHack is logging to *.log files, and DF logs to *.txt files on Windows by default (which may be new). It looks like I forgot to update the issue to mention that, sorry.

**Comment by expwnent** [comment]
Oh, my mistake.

**Comment by ab9rf** [comment]
DF logs to stderr.txt on Windows because there's no "console" for vanilla DF on windows; it runs as a pure GUI app. Without the redirects, there'd be no log _at all_.

Redirecting the logs might make it "hard" to submit the logs when reporting a DF bug, but since Toady is not obliged to accept bug reports from reporters who are running DFHack anyway, that's a moot point, and having them redirected to the DFHack log might make taking those bug reports via DFHack easier.

**Comment by lethosor** [comment]
Right, that's probably why Toady added it. However, it was added fairly recently (between 0.40.24 and 0.43.05, probably on the newer end, since I don't remember reports of stderr.txt containing DFHack stuff before 0.43.05), and before that, DFHack always logged to stderr.log. I also added messages to the txt files before switching to the log files in that commit, which should hopefully make it obvious if someone does send Toady one.

**Comment by ab9rf** [comment]
I doubt Toady explicitly "decided" to do this; rather, it's an optional behavior of SDL on Windows, and presumably Toady changed SDL options (intentionally or not) when he migrated to VS2015.

See http://sdl.beuc.net/sdl.wiki/FAQ_Console for more on where stdout.txt and stderr.txt come from.

**Comment by lethosor** [comment]
Oh, that would make sense. It looks like that's controlled by the `NO_STDIO_REDIRECT` flag in main/win32/SDL_win32_main.c in SDL (1.2.15). I thought Toady added it for diagnostics, but he could have just removed that flag unintentionally. (The behavior changed in *both* builds of 0.43.05, so it's probably from when he recompiled SDL.)

**Comment by BenLubar** [comment]
Since we replace SDL completely on Windows, can we compile a version that doesn't redirect stdio and distribute that as SDLReal instead of the version Toady distributes?

**Comment by lethosor** [comment]
Sure, but that would be extra effort for something that's mostly fixed. (It's still possible for some of DF's output to get sent to the *.txt files, but that typically isn't something we care about).
