### ISSUE TITLE
gui.widgets List and Label don't like specification of right frame parameter (gui.lua is guilty)

### ISSUE THREAD

**Issue by PatrikLundell** [DFHack/dfhack#1125]
I have the weird issue that Lists and Labels that have their 'r' frame parameters specified get cut (List) or not presented at all (Label) if they cross the middle of the Panel they're placed on (always the full DF screen in my case, with DF itself being windowed). Omitting the 'r' parameter to let it auto size works, but when an 'r' is added to yield the same width they don't want to cooperate. Resizing the DF window so a List crosses gradually less of the middle causes the List to grow on the left side (up to the middle), while a Label suddenly appears when the whole frame ends up on the left side. Shrinking the DF window has the opposite effects. Zooming has the same effect as resizing. It can be noted that I've left the 'b' parameter out in both cases. A possible requirement to specify the 'b' parameter is not an issue for the Label in my case, as that tends to be fixed, but I want my Lists to be able to make use of all the vertical space available.

Neither of these issues are huge problems as they can be worked around, but they're definitely odd.

I'm somewhat outdated by using DFHack alpha-2, but I believe the gui.widgets file hasn't changed since then. The OS is Windows 10.1.

**Comment by PatrikLundell** [comment]
As far as I can see, the error lies in gui.lua:compute_frame_rect() and the same logical flaw occurs with the vertical logic. The lines
`local sw = wavail - (spec.l or 0) - (spec.r or 0)
local sh = havail - (spec.t or 0) - (spec.b or 0) `
essentially remove the left/top boundary twice: first as itself and then as part of the right/bottom one, when both are specified, and you actually want the specified width when specified, and the part to the left when only the right boundary is specified (and the corresponding logic for the vertical case).
I believe the two lines should be replace by:
`       local sw
	if spec.r then
	  sw = spec.r - (spec.l or 0) + 1
	else
	  sw = wavail - (spec.l or 0)
	end
	
	local sh
	if spec.b then
	  sh = spec.b - (spec.t or 0) + 1
	else
	  sh = havail - (spec.t or 0)
	end`
I've tried it with a brief test of my bugged case, and it seems to work correctly there, although I haven't tried boundary cases, just resizing the DF window. Since my case has issues with the horizontal logic only, that's what I've tested.

**Comment by lethosor** [comment]
You need three backticks for multi-line code blocks.

And as long as it doesn't break existing scripts, that change is fine with me.

**Comment by PatrikLundell** [comment]
It definitely shouldn't break existing code that lack r and b parameters respectively, since you end up in the second branch where I've removed what then resolves to  '- 0'.
Provided that the parameter is actually used as width the top branch is correct, which seems to be the case as the code is read through a number of times. I can't say I'm completely comfortable with my understanding of the gap/alignment stuff, but I can't see anything wrong with it: it looks OK.

**Comment by PatrikLundell** [comment]
It DOES "break" gui/gm-editor. A list displaying an enum showed only the first character, and an edit box for an integer displayed incorrectly. I've found I've made the mistake of defining what's essentially edit boxes to have exactly the dimensions of the data to fit into it, but the prompt adds an extra character: I assume gui/gm-editor has done the same. However, I'll check the script to verify, and take a look at the list issue as well.

**Comment by PatrikLundell** [comment]
Well, this is a mess...

I've found two errors in dialogs.lua:

In InputBox:preinit() there's a `frame = { l = 0, r = 0, h = 1 }`. Removing the "r = 0" constraint to a single character allows the box to work correctly.

In ListBox:init the "self:addviews" definition contains `frame = { l = 0, r = 0 }`. Removing the definition of a single character box by removing "r = 0" causes the listbox to display correctly.

Apart from being those instances gui/gm-editor uses, they're also the only ones I can find in that file. I've tested it by commenting out the lines and replaced them with copies without the definition of 'r', and gui/gm-editor seems to return to normal. ("Seems" as in all the problems I've seen have been removed, but there are advanced edit options I've never used).

It also means there is nothing wrong with gui/gm-editor, as it doesn't specify edit field sizes incorrectly (or, indeed, at all).

**Comment by PatrikLundell** [comment]
I've realized I've totally misunderstood the purpose and usage of the 'r' and 'b' frame parameters respectively. Thus, the only errors are me using the parameters as they are not indices but distances from the right and bottom edges, respectively.
