### ISSUE TITLE
Unknown reference 

### ISSUE THREAD

**Issue by robinhoodexe** [DFHack/dfhack#1127]
I am using DF 0.43.05 and latest dfhack on OS X 10.11.16. 

I have generated a 257x257 world with 10k history and a lot of sites. I can export the legends to XML from DF without problems (although the file is some 44 GB). 

However, when running `exportlegends info` from dfhack I get the following error:

    [DFHack]# exportlegends info
    Exporting:  World map/gen info
    Exporting:  Legends xml
    Exporting:  Extra legends_plus xml
    unknown reference	48	ABSTRACT_BUILDING
    unknown reference	48	ABSTRACT_BUILDING

Which goes on some 188 times until DF crashes.

I'd like to explore the legends with [LegendsBrowser](https://github.com/robertjanetzko/LegendsBrowser) which I believe needs the `legends_plus.xml` file (also because it threw an error when I tried to load the 44 GB XML).

**Comment by lethosor** [comment]
Is this 64-bit or 32-bit DF?
The message looks harmless. It's really just a warning about a certain reference not being exported because exportlegends doesn't know how to export it.

**Comment by robinhoodexe** [comment]
64 bit. 

Also, when running `exportlegends maps` DF crashes with the [following report](https://paste.installgentoo.com/view/8af0b0a0) from OS X and output from dfhack:

    [DFHack]# exportlegends maps
    Exporting:  Standard biome+site map map
    [DFHack]# /Users/philip/Downloads/df_osx/dfhack: line 15: 33875 Abort trap: 6
    DYLD_INSERT_LIBRARIES=./hack/libdfhack.dylib ./dwarfort.exe "$@"

**Comment by lethosor** [comment]
I think that's the same issue as #1095. I'm not sure what the original issue here is, though. What if you run "exportlegends custom"?

**Comment by robinhoodexe** [comment]
Running `exportlegends custom` gives:

    unknown reference	48	ABSTRACT_BUILDING

times a lot. I can't stop it and DF will probably crash at some point.

**Comment by quietust** [comment]
Just to make things clear, the "unknown reference" message should have absolutely **nothing** to do with any crashes you may be experiencing.

To get rid of that particular "unknown reference" message, edit exportlegends.lua and insert the following at line 421 (just before the final `else` statement):
`elseif refV:getType() == df.general_ref_type.ABSTRACT_BUILDING then -- TODO ABSTRACT_BUILDING`

**Comment by lethosor** [comment]
I applied Quietust's patch. While that change isn't in DFHack r2, the crash fixes are, so please test with r2 and see if the crash still occurs.
