### ISSUE TITLE
Unable to retrieve version information.

### ISSUE THREAD

**Issue by ihavesomepoblem** [DFHack/dfhack#1132]
I had trouble with dfhack ( can't load image data/art/mouse.png ), then i edited executable file DwarfFortress and replaced mouse.png to mouse.bmp.
And if i begin start dfhack it's stopped because md5sum isn't correct (because i edited executable file and md5sum was changed).
How i can disable this check?

**Comment by quietust** [comment]
You don't - you edit hack/symbols.xml and insert the updated md5sum.

Alternatively, you figure out why Dwarf Fortress was unable to load mouse.png - http://www.bay12games.com/dwarves/mantisbt/view.php?id=2688 would be a good place to start.

**Comment by ihavesomepoblem** [comment]
Thanks!
And one more question about stonesense.
Can i play in stonesense or i must be in game and stonesense is only visualizer?

**Comment by lethosor** [comment]
There's a experimental "stonesense overlay" command, which might be what you're referring to by playing "in stonesense". It doesn't work very well, though.
