### ISSUE TITLE
"Stuck in a tree" detection has a lot of false positives

### ISSUE THREAD

**Issue by TV4Fun** [DFHack/dfhack#1138]
Don't get me wrong, I love this feature, but I have had several warnings that someone was stuck in a tree when they had a stepladder beneath them and climbed out perfectly well a moment later. Maybe it needs to be a hair less sensitive.

**Comment by lethosor** [comment]
I'm going to need a safe for that. (You could also increase the delay in your init file and see if that helps.)

**Comment by TV4Fun** [comment]
Here is a save with an example http://dffd.bay12games.com/file.php?id=13019. Someone has just been reported stuck in a tree. The tree is at ground level, and he walks out a moment later.

**Comment by TV4Fun** [comment]
Here is a better example: http://dffd.bay12games.com/file.php?id=13021. Iton Olindosim was just reported as stuck in a tree even though he hasn't been there all that long, and there's a stepladder beneath the tree that he picks up almost immediately after the message.

**Comment by BenLubar** [comment]
Hmm, can dwarves climb down ANY stepladder? Could stockpile tricks be used to move a stepladder under a tree a dwarf is in, or does the dwarf need to have the stepladder equipped in some way?

**Comment by ab9rf** [comment]
I can confirm that the script is oversensitive; in my current "test" game the script fired, but on resume the dwarf named by the script climbed back down out of the tree and went his merry way less than a day (in-game) later.

**Comment by lethosor** [comment]
I'm just going to remove this script for now, since http://www.bay12games.com/dwarves/mantisbt/view.php?id=9252 was fixed.
