### ISSUE TITLE
Digging Invader plugins disabled from Dfhack during 64bit conversion

### ISSUE THREAD

**Issue by msnbcorp** [DFHack/dfhack#1145]
The plugin DiggingInvaders is still present in Dfhack but have been disabled without comments during the 64bit conversion. 
It should be re-enabled or reworked if it has 64bit bug (don't see anything that could have problem on 64bit in the code though)

**Comment by lethosor** [comment]
@pronvit this was changed in https://github.com/DFHack/dfhack/commit/8916aba3bf29f81a426485a779a623edd4b1be61

**Comment by pronvit** [comment]
Something probably didn't compile (although I don't see what it could be), so I disabled it temporarily and then no-one noticed. Sorry.

**Comment by lethosor** [comment]
No worries. I'm checking on it now (I was working on another DFHack project earlier, but I've put that on hold for now).

It's worth noting that it could be broken in-game too, though, even if it does compile.

**Comment by lethosor** [comment]
It looks like the only things breaking it are missing includes/namespaces. I have no idea how that only turned up when you tried compiling for Win64, since it shouldn't be specific to that. (People were using GCC 4.8+ well before the 64-bit changes, so it should've been breaking with that before too.)

**Comment by lethosor** [comment]
Not sure if that commit fixes it on Windows, but it does seem to at least build with GCC 4.8 now.

**Comment by ab9rf** [comment]
Win64 build fails over const invariance violations:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C3848	expression having type 'const PointComp' would lose some const-volatile qualifiers in order to call 'int32_t PointComp::operator ()(df::coord,df::coord)' (compiling source file C:\Users\Kelly\Documents\GitHub\dfhack\plugins\diggingInvaders\diggingInvaders.cpp)	diggingInvaders	C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xtree	1994	
Error	C3848	expression having type 'const PointComp' would lose some const-volatile qualifiers in order to call 'int32_t PointComp::operator ()(df::coord,df::coord)' (compiling source file C:\Users\Kelly\Documents\GitHub\dfhack\plugins\diggingInvaders\diggingInvaders.cpp)	diggingInvaders	C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xtree	1999	
Error	C3848	expression having type 'const PointComp' would lose some const-volatile qualifiers in order to call 'int32_t PointComp::operator ()(df::coord,df::coord)' (compiling source file C:\Users\Kelly\Documents\GitHub\dfhack\plugins\diggingInvaders\diggingInvaders.cpp)	diggingInvaders	C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xtree	2009	

```

**Comment by msnbcorp** [comment]
The operator simply need to be const : 
https://stackoverflow.com/questions/19816139/expression-having-type-const-comparevptrs-would-lose-some-const-volatile-quali

And in theory this has nothing to do with x64 ...

**Comment by lethosor** [comment]
I know. We had to switch compilers on Windows, so maybe the old one was tolerant of that somehow.

**Comment by msnbcorp** [comment]
Some compiler just made inteligent guessing and add the const to the operator if it is not called in another place of the program. gcc made this kind of thing in my memory.

But it should have to throw some warning, even on old compiler ...

**Comment by lethosor** [comment]
I know it *should* produce an error/warning, but it *didn't*. Not with GCC 4.x or MSVC 2010, at least. It's possible that the missing-include/namespace errors snuck in due to some header changes after diggingInvaders was disabled, but the diggingInvaders plugin itself hasn't had any significant changes since 2015.

Anyway, sorry about this getting forgotten. I only noticed that diggingInvaders was disabled recently myself. (I can hardly blame mifki for it, either - nobody wants to deal with a plugin spewing hundreds of errors when they're adding 64-bit support to the DFHack core.)

**Comment by msnbcorp** [comment]
No problem, just noticed that myself when i try to use it :p 
Did you know when a corrected release will be out ?

**Comment by lethosor** [comment]
@msnbcorp what platform are you on? This should be built, now, but I haven't checked it extensively. I could provide a build if you'd like to test it.

**Comment by expwnent** [comment]
I should also mention that this hasn't been updated for multi-tile trees / climbing, so it will likely get confused in some situations involving climbing. I think it'll work for "immediate" climbing but if they have to dig then climb then walk it'll think they can't do it.

**Comment by msnbcorp** [comment]
@lethosor I was speaking mostly about the Dfthread release given here : http://www.bay12forums.com/smf/index.php?topic=164123.0 which is tied to a "real" release on github.

I am on windows x64 but it's just to have everyone synchro ^^ 

@expwnent : Don't see exactly when it play a role ... with a quick look on the code it seems to use DF classic path algo to have the information of "dwarf reachable or not" in first place, so whatever the signal is, it's should begin good imho. After that the only pathing problem solved by the system is the "how to reach the dwarf" . If climbing does not count it should simply dig to a place where there is no climbing to join the dwarf no ?
I don't see a situation in real fortress where the problem occurs ... imho

**Comment by expwnent** [comment]
It is possible that they will prefer digging over climbing sometimes. The code is mostly Dijkstra's algorithm with a complicated cost function.

**Comment by msnbcorp** [comment]
Of course but the result is the same to make difficulties for the players :p 
It is in fact slightly better that ennemies don't follow exactly what the player intend to be ^^

**Comment by expwnent** [comment]
My goal in writing it was to make it so you can't just wall yourself in. I tried to make it so they dig as little as possible, because you can't undig what they dig and it would suck if they ruined your beautiful fort design when they could have just taken a longer route in.

**Comment by msnbcorp** [comment]
Well, it's the game when you search for difficulties no ? You can de-dig by building wall in hole so it's not a great problem. If players don't want to have big holes well, they must design pretty simple routes to the forts. It is pretty rare to have a fort when you have to use the climbing to join the meeting hall :p 

However, you do what you want, if you want to minimize it i guess that it is quite easy to include the climbing in the cost function ... I guess :p
