### ISSUE TITLE
Ruby scripts can't be run if the DF folder contains an apostrophe

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#1146]
Could apply to other special characters too.

This was introduced by the fix for #1099 and could probably be patched temporarily by stripping the DF path from script search paths.

**Comment by OwnageIsMagic** [comment]
Will it also fix when DF dir name is not latin?

**Comment by lethosor** [comment]
This patch might help with that, if it was working in 0.43.05-r1 and earlier for you.

**Comment by OwnageIsMagic** [comment]
actually not
![image](https://user-images.githubusercontent.com/10534634/29492193-348220e8-857c-11e7-9ddc-5fc0edb4cbcc.png)

**Comment by lethosor** [comment]
That looks like a separate issue to me, actually. Did r1 work for you?

**Comment by OwnageIsMagic** [comment]
it also cause troubles to lua too
![image](https://user-images.githubusercontent.com/10534634/29492245-704280da-857e-11e7-9faa-3ef7927624d8.png)
last time I used dfhack was DFv42.05 and it worked flawlessly in any folder

**Comment by OwnageIsMagic** [comment]
@lethosor should I open another issue for this?

**Comment by lethosor** [comment]
The siren issue is different and doesn't have anything to do with your script path. Is that script broken in 0.43.05?

**Comment by OwnageIsMagic** [comment]
lol
I just randomly picked `.lua` script to test if it works
but it really broken
![image](https://user-images.githubusercontent.com/10534634/29494979-2452a5f2-85be-11e7-9481-6cb6929cabfa.png)
did you notice strange path delimeters in last trace line?

**Comment by lethosor** [comment]
Forward slashes there are normal, if that's what you mean. The siren issue should be reported separately, but it's not related to the path issue.
