### ISSUE TITLE
create-unit works wrong in arena mode

### ISSUE THREAD

**Issue by warmist** [DFHack/dfhack#1149]
Create-unit script fails to set correct unit race if filter is not empty in arena create-unit screen also if you leave the pointer in wrong location.

**Comment by lethosor** [comment]
Is this still an issue? There have been some fixes to create-unit like https://github.com/DFHack/scripts/pull/52 (although I don't think that one specifically fixes this).

**Comment by warmist** [comment]
Seems fixed
