### ISSUE TITLE
Floating Point Exception Crashing Game

### ISSUE THREAD

**Issue by thorlucas** [DFHack/dfhack#1152]
I keep getting the game crashing at random times. 

[DFHack]# /Applications/df_osx/dfhack: line 15:  1074 Floating point exception: 8   DYLD_INSERT_LIBRARIES=./hack/libdfhack.dylib ./dwarfort.exe "$@"

It's very annoying because it doesn't save my game.

**Comment by quietust** [comment]
Which DFHack plugins and scripts are you using? If you disable everything, does the problem go away?

**Comment by lethosor** [comment]
Please reopen if the problem persists.
