### ISSUE TITLE
instant shutdown upon using create-item script

### ISSUE THREAD

**Issue by kjak0110** [DFHack/dfhack#1153]

**Comment by kjak0110** [comment]
i was wondering if this is my fault and if i can do anything about it

**Comment by lethosor** [comment]
What exact command are you running? "create-item" is not a valid command. Also, this is a *crash*, not an "instant shutdown".

**Comment by lethosor** [comment]
Closing due to lack of information. If you can provide the exact command(s) that crashed, let us know.
