### ISSUE TITLE
labormanager error with horn figurines

### ISSUE THREAD

**Issue by moozaad** [DFHack/dfhack#1162]
LABORMANAGER: Cannot deduce labor for make crafts job (not bone)
LABORMANAGER: Game paused so you can investigate the above message.

> ...: Needs unrotten horn body part

The wiki says to report these errors, so I hope this helps!

**Comment by moozaad** [comment]
Correction, looks like it was Pearl ring triggering it.

**Comment by ab9rf** [comment]
Does anybody offhand know what labor is used for carving horn figurines or pearl rings?
