### ISSUE TITLE
LaborManager issue

### ISSUE THREAD

**Issue by guska84** [DFHack/dfhack#1166]
As requested in the documentation, I'm opening an issue after experienceing a LaborManager pause. 

Vanilla DF 0.43.05-r2 with PyLNP (Automatic Job Assignments, Multilevel View, Other Automation plugins and Performance Tweaks all turned on in the DFHack menu)

LABORMANAGER: Cannot deduce labor for make crafts job (not bone)
LABORMANAGER: Game paused so you can investigate the above message. Use 'labormanager pause-on-error no' to disable autopausing.

**Comment by guska84** [comment]
Apologies, look like this is a duplicate of

https://github.com/DFHack/dfhack/issues/1162

I also had a black pearl job suspend due to lack of materials.

**Comment by ab9rf** [comment]
Duplicate of #1162.
