### ISSUE TITLE
object:delete() crashes on 64bit for invalid reference

### ISSUE THREAD

**Issue by warmist** [DFHack/dfhack#1170]
It's supposed to return false as per docs: [Doc link](https://dfhack.readthedocs.io/en/stable/docs/Lua%20API.html#typed-object-references)
Probably this place: [Source link](https://github.com/DFHack/dfhack/blob/master/library/LuaWrapper.cpp#L936)
Forum thread: [Forum thread](http://www.bay12forums.com/smf/index.php?topic=164123.msg7575122#msg7575122)

**Comment by lethosor** [comment]
I don't think this is fixable. It's basically just a wrapper around the delete operator, and that'll crash if you try to use it on something that wasn't heap-allocated. I don't think the Lua API can distinguish between objects that can be freed with delete and ones that can't.

I'm pretty sure a destructor that's "not available" refers to one we haven't found, e.g. for a virtual class, rather than a destructor that'll crash if it's called.

**Comment by warmist** [comment]
Then docs must be updated. Also strange that 32bit does not crash.

**Comment by PatrikLundell** [comment]
I don't know anything about the internals, so my questions might be rather uninformed, but I would have thought the destructor called should be for the stl-vector that the XML representation identifies, rather than the naked pointer visible for it through things like gui/gm-editor and printall (and assuming the stl-vectors set up by DF itself are actually allocated from the heap, the destructor crashes 64 bit for heap allocated data as well)?

**Comment by warmist** [comment]
I don't think there is a way to differentiate pointer from reference. However i've not look very deeply at this.

**Comment by lethosor** [comment]
> I don't think there is a way to differentiate pointer from reference.

I'm pretty sure there is not.

Something like `df.unit:new().social_activities:delete()` is always invalid, as it would be in C++. There's no way for DFHack to tell whether you're deleting something that you actually allocated with new() or something else (and in this case, both unit and unit.social_activities are on the heap). Granted, that doesn't *guarantee* that DF will crash if you try it, and it *seems* to not crash on 32-bit Windows or OS X, but that doesn't make it any less undefined.

**Comment by PatrikLundell** [comment]
This: `dfhack.println (unit.social_activities._type)` prints "vector<int32_t>", which indicates the script "understands" the element is a vector object. So, what does `unit.social_activities:delete()` do? It seems this extracts the pointer to the vector part of the object from within the std::vector object header (or whatever you'd call the part of the object embedded in the "struct") and sends it for standard naked pointer destruction, which doesn't make much sense. The most logical thing would be to call the destructor for a vector object (which, as far as I understand, returns the array part pointed to to the heap, as well as destroying any objects in the vector (if applicable). It ought to set the pointer inside the header part of the object itself to null in order not to leave any dangling references, but it can't really destroy the header itself in any meaningful way, although it could be marked as being illegal to use).

The above does not mean there have to be a reasonably feasible way to distinguish between a reference inside an object header and a naked pointer at the point the meaning of :delete() is evaluated, though.

**Comment by lethosor** [comment]
> It seems this extracts the pointer to the vector part of the object from within the std::vector object header (or whatever you'd call the part of the object embedded in the "struct") and sends it for standard naked pointer destruction, which doesn't make much sense.

In C++, it's the same as
```c++
df::unit *u = new df::unit;
delete &(u->social_activities);
```
This is not safe.

The Lua API docs talk about "refs" briefly. Essentially, every Lua wrapper around a C++ object is a pointer plus some type information. It's impossible to tell whether this pointer points to a vector allocated with `df.new('int-vector')` or a vector that's part of a dynamically-allocated object. `delete()` uses C++'s `delete` operator under the hood, which only works with things directly allocated with `new`, not things contained in another object allocated with `new`.

Destroying a vector that's part of another object is only safe when also destroying that object. Even if you called the vector's destructor and set the pointer in the Lua ref to null, the containing object would still exist and contain a vector in an inconsistent state.

> it would be consistent with the documentation

The documentation for `delete()` says:

> Destroys the object with the C++ delete operator. If destructor is not available, returns false.

"not available" means that we know there's a destructor but we don't know how to call it (for example, a destructor in a subclass of a virtual class that we haven't located). We definitely know how to call the destructor for a vector, so a vector's destructor is always available, even if calling it would crash.

**Comment by PatrikLundell** [comment]
Well, trying to use a C delete on an element of a struct by passing the address of the element when the element is found not to be a naked pointer is definitely not safe, and I doubt it makes sense in any context. It would be slightly less unsafe if it did something like "delete(u->social_activities.vector_data_pointer)" (which I thought it did).
The part about "destructor not found" in the documentation makes no sense if the C++ delete operation is called regardless of what the destructor is (unless it's a really obscure way of saying it won't actually crash if you do it on discrete non objects such as integers and floats).
"delete" calls the destructor of the object the pointer points to if there is a destructor for it, according to a web search, but delete is not the destructor for a for an std::vector (I assume that would be ~std::vector). "delete" is the destructor for a pointer to an std::vector.

I agree "df.new('ptr-vector'):delete())" is safe, but I disagree that it makes sense, as it doesn't achieve anything useful, and you're not calling it on the vector but on a pointer to the vector.

**Comment by warmist** [comment]
I feel like this went off the rails somewhat. I.e. @PatrikLundell you have difference of opinion of how it should work and slight misunderstanding what is possible.

My original feeling is that it only needs documentation change so it would clarify what "destructor is not available" means.

Also df.new('ptr-vector'):delete() achieve something useful. It allocates and deletes a vector. Of course this is itself useless but imagine that there is some computation happening in between. E.g. `local a=df.new('ptr-vector); some_df_vmethod_needing_vector(a); a:delete()` (there is a more error safe way of doing this but the argument is the same as it does the same under the hood).

**Comment by PatrikLundell** [comment]
If the documentation said it invokes the C++ delete operation and should be used only on things created with new (no mentioning of destructors or indications of being safe to call in any other circumstances) it would describe how I think it is intended to work and the scope where it is safe to use it (provided my understanding of it isn't too off).
