### ISSUE TITLE
manipulator enhancement

### ISSUE THREAD

**Issue by strainer** [DFHack/dfhack#1176]
I want to manage dwarf labors but I spend much too long puzzling over the dwarf descriptions to decide what labors they will be best at and progress best with. The manipulator could background color each labor as good/ok/bad depending on the dwarfs attributes which are relevant to each labor. This would change dwarf labor assignment for new immigrants into a pleasant little visual game, instead of the current difficult puzzle.

It might not be very difficult to add. The manipulator columns already handle a different background color for the non-job columns. The labor grid display seems to be made around here `manipulator.cpp:1985` where it already has access to each dwarfs stats including emotions and attributes.

**Comment by strainer** [comment]
I've got this working now its great. Ill send a pull request when I figure out how to best tidy my cpp code up.

**Comment by quietust** [comment]
If you're going to add this, be sure to add a way to turn it off (or, ideally, a way to turn it *on*), because some people might not want the extra clutter.

**Comment by strainer** [comment]
Right, that's not to difficult. I think its going to look ok and be popular though ...

**Comment by strainer** [comment]
This is quite done now. The view shows a dwarf attribute grid in the column space for 'professions' etc. It shows what attributes are affected by selected job, and it colors all jobs in three levels by how they are affected by the dwarves individual attributes. 

Here are two screenshots: https://imgur.com/a4rnjdy

The edit is all to manipulator.cpp in branch develop of my fork here: https://github.com/strainer/dfhack

Ill ask for pull in a while.
