### ISSUE TITLE
Invalid material_category value for imported manager order

### ISSUE THREAD

**Issue by nornagon** [DFHack/dfhack#1177]
I tried to import the following order JSON and got the error:

```
Invalid material_category value for imported manager order: [
        "cloth"
]
```

The command I ran was `orders import test`.

DFHack build: `0.43.05-r2-0-g48a61420`

<details>
<summary>
test.json
</summary>

```json
[
	{
		"amount_left" : 2,
		"amount_total" : 2,
		"frequency" : "Daily",
		"id" : 22,
		"is_active" : false,
		"is_validated" : false,
		"item_conditions" : 
		[
			{
				"condition" : "AtLeast",
				"flags" : 
				[
					"plant"
				],
				"item_type" : "CLOTH",
				"value" : 5
			},
			{
				"condition" : "AtMost",
				"flags" : 
				[
					"empty"
				],
				"item_type" : "BOX",
				"value" : 10
			},
			{
				"condition" : "AtLeast",
				"flags" : 
				[
					"empty",
					"bag"
				],
				"item_type" : "BOX",
				"value" : 10
			}
		],
		"job" : "ConstructChest",
		"material_category" : 
		[
			"cloth"
		]
	}
]
```

</details>

**Comment by BenLubar** [comment]
Hmm, I can't see why cloth wouldn't work for that function:

https://github.com/DFHack/df-structures/blob/666f4c7f5fc578240d2a2ab2aa097bfc5c60d6ad/df.jobs.xml#L5

**Comment by nornagon** [comment]
Me either! I also got the same error with "wood", so I assume there's
something deeper that's wrong.

**Comment by lethosor** [comment]
Are you importing in a different fort?

**Comment by nornagon** [comment]
Nope, export and import in the same fort (didn't even close the game)

**Comment by BenLubar** [comment]
If you remove
```
,
		"material_category" : 
		[
			"cloth"
		]
```

do you get an error about item condition flags? If so, the `json_array_to_bitfield` function is broken in some subtle way I can't find just by looking at its code.

**Comment by nornagon** [comment]
Yep, I did get that error when I removed the material category.

**Comment by BenLubar** [comment]
🤦‍♂️ it never handled the first flag in the array. #1178 should fix that.

**Comment by nornagon** [comment]
Nice! Looking forward to the next release :)
