### ISSUE TITLE
Some item management ideas

### ISSUE THREAD

**Issue by peterix** [DFHack/dfhack#119]
Source: http://www.bay12forums.com/smf/index.php?topic=95087.0

- [x] Let's not forget (I noticed this by accident), workshops that have whatever material used to build (base material, let's say) it are also marked for dumping (the material used to make them, not the shop itself). It'll still show up on the list as assigned to dump.

  I wonder if a DFHack tool can be made to un-designate such flags on workshop base materials, but not affect the rest of the dump designations assigned. Minimize confusion. 

- [x] Also another interesting program regarding this: I wonder if it's possible to make a DFBookkeeper program (that uses DFHack) so you have more direct control over (or from) the bookkeeping job (or as a separate interface outside of DF; good for copy-pasting info, descriptions, value, weight, etc.), so to say (Appraising the fort value and such could also be implemented, in case you lack an appraiser, but are curious of those values. Where it really shines could be seeing the item values themselves in table format (with optional details as easy to look at by rolling over them or a separate window that hold that info it it; similar interface as DFBookkeeper). Kinda like an interface to do similar to the stocks screen, but you get more details, like what Z-level whatever materials are on if expanded, if they're material used in a workshop or construction, and the obvious mass-dump/forbid option.

  Chances are this info is hard to reach/hard-coded and can't be done. Still, it could be interesting to try out/explore. Heck, you could possibly change the items themselves through these programs. I dunno.

- [x] I wonder if it's also possible to also make a DFHack-based program that can also be more specific with stockpil(es/ing), or be a quicker interface than the in-game interface. I mean, if you're really particular about it. Just choose the stockpile name in a list (provided you recognize it), and adjust it's values, even change the name of the stockpile as well (I guess). Then again, I'm just coming up with ways to make lazier ways through playing the game now. :|

Essentially, my ideas sound more like adaptations of DwarfTherapist or Dwarf Foreman if anything.

**Comment by PeridexisErrant** [comment]
>Let's not forget (I noticed this by accident), workshops that have whatever material used to build (base material, let's say) it are also marked for dumping (the material used to make them, not the shop itself). It'll still show up on the list as assigned to dump.

>I wonder if a DFHack tool can be made to un-designate such flags on workshop base materials, but not affect the rest of the dump designations assigned. Minimize confusion.

Done, see `scripts/undump-buildings.lua`

>Also another interesting program regarding this: I wonder if it's possible to make a DFBookkeeper program (that uses DFHack) so you have more direct control over (or from) the bookkeeping job (or as a separate interface outside of DF; good for copy-pasting info, descriptions, value, weight, etc.), so to say (Appraising the fort value and such could also be implemented, in case you lack an appraiser, but are curious of those values. Where it really shines could be seeing the item values themselves in table format (with optional details as easy to look at by rolling over them or a separate window that hold that info it it; similar interface as DFBookkeeper). Kinda like an interface to do similar to the stocks screen, but you get more details, like what Z-level whatever materials are on if expanded, if they're material used in a workshop or construction, and the obvious mass-dump/forbid option.

Most of these functions are provided by Falconne's enhanced `stocks` plugin.

>I wonder if it's also possible to also make a DFHack-based program that can also be more specific with stockpil(es/ing), or be a quicker interface than the in-game interface. I mean, if you're really particular about it. Just choose the stockpile name in a list (provided you recognize it), and adjust it's values, even change the name of the stockpile as well (I guess). Then again, I'm just coming up with ways to make lazier ways through playing the game now. :|

This sounds pretty much like the `stocksettings` plugin to me.

With the major ideas implemented, I think it's time to close this issue before it turns four years old!

**Comment by lethosor** [comment]
Sure. I'm not really sure about the first part of the second point, but the rest are definitely implemented. (I reformatted it as a bulleted list for easier tracking later if we decide otherwise.)
