### ISSUE TITLE
gui/gm-editor: Print type together with enum value selection

### ISSUE THREAD

**Issue by PatrikLundell** [DFHack/dfhack#1193]
To make it easier to user gui/gm-editor to identify which types enum elements belong to I suggest that the change value dialog box should display the type in the box header by replacing line 298 with
"local ret,idx,choice=guiScript.showListPrompt("Choose "..tostring(enum):sub(8,#tostring (enum)-1) .. " item:",nil,3,list,nil,true)"
For most types the element type is shown instead of the element value (as you need to descend into these types to see their contents), but enums (and integer types) show the field data directly without displaying the type. I don't think the particular integer types are of interest in most cases (although it might be possible and desirable to do the corresponding modification to that dialog while at it), but enum types often are.
The change above has been tested briefly and worked as intended during that test.

**Comment by lethosor** [comment]
Nice idea. It can get rather long, though: 
![image](https://user-images.githubusercontent.com/3719547/34067546-fb597f82-e1f6-11e7-9b6a-cbd12292c91b.png)
I'll see if there's a better way to get the enum type name, but it looks ok.

**Comment by PatrikLundell** [comment]
The long name is a side effect of using inline type definitions (which I'm not keen on in the first place), and you get the same ungainly names if you need to address the type in a script. On the other hand, it's not as if the screen space is needed for anything else.
If you find a better way to get the enum name that's even better.
