### ISSUE TITLE
crash after enabling dwarfvet and when setting civ burrows Windows x64

### ISSUE THREAD

**Issue by tsaber** [DFHack/dfhack#1195]
Thanks for the work guys it's a pleasure to "orders import". It's crashing regularly for me but that's ok.
Neither the error nor the gamelog save anything about the crashes but they note something about this:

`Invoking: prospect
Invoking: command-prompt
UNKNOWN CLASS 'viewscreen_commandpromptst': vtable = 0x7fede5a89a8
Invoking: getplants -a
Invoking: digv
UNKNOWN CLASS 'viewscreen_unitlaborsst': vtable = 0x7fede02ff40
Invoking: zone assign all own
Invoking: zone set
Invoking: zone assign all own
Invoking: zone assign all own
Invoking: zone assign all own
Invoking: command-prompt
Invoking: quicksave

I'm going to try a fresh unpacked df and the linux version to verify

**Comment by lethosor** [comment]
None of that stuff in stderr.log is relevant, unless it crashes right when you run one of those commands (following `Invoking:`) - does it?

What if you don't enable dwarfvet?

**Comment by lethosor** [comment]
Might be #1227, but without more information, there isn't anything I can do. If this isn't fixed in 0.44.05-r1+, can you give more detail about what's going on?
