### ISSUE TITLE
createitem - Items disappear after unpausing the game (0.44.02-alpha1)

### ISSUE THREAD

**Issue by backlands** [DFHack/dfhack#1198]
I just started a new game and was testing out some of the DFHack tools and found that when I spawn items with the `createitem` command using `createitem BLOCKS INORGANIC:BAUXITE ##` the blocks instantly disappear after unpausing the game. I have the save and have uploaded it [here](https://drive.google.com/file/d/1wsWqNOd0Oh1OJLmkLpRfgvAd-mXSEn7C/view?usp=sharing).

I was using this with default settings in the PeridexisErrant DF Starter Pack. Let me know if you need more information from me!

**Comment by quietust** [comment]
On what platform are you playing? I just used that exact same command to create bauxite blocks in 0.44.02-alpha1 with Windows 32-bit and 64-bit and they both worked correctly.

**Comment by lethosor** [comment]
I'm thinking it's save-specific somehow. I'll test the save when I get a chance.

**Comment by backlands** [comment]
This was on Windows 10, 64-bit with latest updates installed. I can port the save over to a Mac or Linux system to test if you would like.

I believe that all I have running is TWBT and Multilevel View. I am also using the GemSet tileset but doubt that has any relation here. You can find a [gist of my PyLNP.json here](https://gist.github.com/backlands/9b1dc049053e6105c9a01a466143be5f) so you can replicate my setup, in case there is some setting in there causing the issue, not sure why it would but you never know!

**Comment by lethosor** [comment]
For the record, I've heard a few reports of this on the forums before. Can you try it with a citizen selected if you aren't doing that already?

**Comment by backlands** [comment]
That did it, it looks like if I am over a citizen either with the `v` or `k` selector tools the block remains. if I am off of a unit or a non-citizen unit the item created disappears after unpausing.

**Comment by lethosor** [comment]
Looks like it's teleporting to the position of a magma crab, which is world.units.active[0].

**Comment by lethosor** [comment]
Interestingly enough, this patch correctly selects the first citizen, but the item is still teleported to the location of units.active[0]. Selecting the same (first) citizen before running `createitem` does *not* teleport the item. Not sure what's going on here.

```diff
diff --git a/plugins/createitem.cpp b/plugins/createitem.cpp
index e65d1979..79971aa1 100644
--- a/plugins/createitem.cpp
+++ b/plugins/createitem.cpp
@@ -1,5 +1,7 @@
 // Create arbitrary items
 
+#include <algorithm>
+
 #include "Core.h"
 #include "Console.h"
 #include "Export.h"
@@ -11,6 +13,7 @@
 #include "modules/Gui.h"
 #include "modules/Items.h"
 #include "modules/Materials.h"
+#include "modules/Units.h"
 #include "modules/World.h"
 
 #include "DataDefs.h"
@@ -354,15 +357,25 @@ command_result df_createitem (color_ostream &out, vector <string> & parameters)
     df::unit *unit = Gui::getSelectedUnit(out, true);
     if (!unit)
     {
+        auto &active = world->units.active;
         if (*gametype == game_type::ADVENTURE_ARENA || World::isAdventureMode())
         {
             // Use the adventurer unit
-            unit = world->units.active[0];
+            unit = active[0];
         }
-        else if (!world->units.active.empty() && cursor->x >= 0)
+        else if (!active.empty() && cursor->x >= 0)
         {
+            auto iter = find_if(active.begin(), active.end(), Units::isCitizen);
+            if (iter != active.end()) {
+                unit = *iter;
+            }
+            else {
+                out.printerr("Could not find a citizen on the map. Please select a unit.\n");
+                return CR_FAILURE;
+            }
+            out.print("found unit %i\n", unit->id);
             // Use the first possible unit and the cursor position
-            unit = world->units.active[0];
+            unit = active[0];
             move_to_cursor = true;
         }
         else
```

**Comment by quietust** [comment]
The problem is most likely in the "move_to_cursor" logic - modifying the makeItem function to ensure that it only ever calls item->moveToGround() *once* (either adding "if (move_to_cursor) on_ground = false;" or by reversing the on_ground/move_to_cursor cases and using "else if") should fix the problem.

**Comment by lethosor** [comment]
Yeah, that fixed it. Thanks!
