### ISSUE TITLE
burial.lua error in 0.44.02-alpha1 (release)

### ISSUE THREAD

**Issue by justjohn2001** [DFHack/dfhack#1202]
I periodically receive the following error in the dfhack console.
```
...rter Pack\Dwarf Fortress 0.44.02/hack/scripts/burial.lua:22: Cannot read field building_slabst.burial_mode: not found.
stack traceback:
        [C]: in metamethod '__index'
        ...rter Pack\Dwarf Fortress 0.44.02/hack/scripts/burial.lua:22: in local 'script_code'
        ... Starter Pack\Dwarf Fortress 0.44.02\hack\lua\dfhack.lua:562: in function 'dfhack.run_script_with_env'
        (...tail calls...)
        [C]: in field 'runCommand'
        ... Starter Pack\Dwarf Fortress 0.44.02\hack\lua\dfhack.lua:580: in upvalue '_run_command'
        ... Starter Pack\Dwarf Fortress 0.44.02\hack\lua\dfhack.lua:595: in function 'dfhack.run_command'
        ...rter Pack\Dwarf Fortress 0.44.02/hack/scripts/repeat.lua:76: in upvalue 'func'
        ...ter Pack\Dwarf Fortress 0.44.02\hack\lua\repeat-util.lua:30: in function <...ter Pack\Dwarf Fortress 0.44.02\hack\lua\repeat-util.lua:29>
```

The world was imported from 043.05. Let me know what other details you need.

**Comment by quietust** [comment]
Only Coffins have a "burial_mode" field, not Slabs. Did that script work in previous versions of Dwarf Fortress?

**Comment by lethosor** [comment]
Looks like another result of #1196. Can you change COFFIN to WEAPON_RACK in hack/scripts/burial.lua and see if the issue goes away?

**Comment by quietust** [comment]
For the record, that bug also affects "autofarm.rb" and "gui/extended-status.lua",

**Comment by justjohn2001** [comment]
It goes away with that change.

**Comment by lethosor** [comment]
Cool, should be fixed in the next version then. (To clarify, that change to the script shouldn't be made in the next version.) Thanks for the report!
