### ISSUE TITLE
"Auto Gem" Order is placing Gem cutting jobs on the Fishery

### ISSUE THREAD

**Issue by FrostZer0** [DFHack/dfhack#1207]
When I change the orders to allow automatic gem cutting all of the gem cutting jobs are placed on my fishery.

Repro Rate: 
5/5 Worlds

Repro steps:
1. Extract Pack 44.02-r04
2. Launch PyLNP
3. Enable DFhack
4. Launch DF
5. Create a new world and proceed through Fortress setup until entering Gameplay
6. Mine until finding Gems
7. Build a Fishery
8. Press "O" > "W" > "g" to enable auto Gem cutting
9. Observe Gem cutting jobs appear on Fishery

Actual Result:
Gem Cutting jobs appear on the fishery building

Expected Results:
Gem Cutting jobs appear on Jewelers workshop

Environment:
I am using the PyLNP 44.02-r04 pack.

**Comment by lethosor** [comment]
Can you confirm that you're using DFHack 0.44.02-alpha1? This should be fixed in beta1.

**Comment by FrostZer0** [comment]
I am using Alpha1, I will upgrade to beta1 and give it a try! thanks!

**Comment by lethosor** [comment]
Also, anything newer (like 0.44.03-alpha1) should also work.
For reference, #1196 is the original issue.

**Comment by FrostZer0** [comment]
Confirmed beta1 fixed this issue! Closing issue as fixed. Thank you.
