### ISSUE TITLE
autolabor errors on pedestal placing jobs due to new job type

### ISSUE THREAD

**Issue by endofzero** [DFHack/dfhack#1208]
autolabor will start to throw errors if you set a display pedestal to have an object, like an artifact.

Display case may act the same.

Error:

Dwarf 14 "lor" has unknown job 240
Dwarf 26 "ustuth" has unknown job 240
Dwarf 45 "monom" has unknown job 240

**Comment by lethosor** [comment]
I think I've fixed this in autolabor, autohauler, and labormanager. Thanks for the report!
