### ISSUE TITLE
Error message while using 'exportlegends all'

### ISSUE THREAD

**Issue by robbyph** [DFHack/dfhack#1215]
nil
stack traceback:
        [C]: in function '_doSimulateInput'
        D:\Dwarf Fortress\Dwarf Fortress 0.43.03\hack\lua\gui.lua:52: in function 'simulateInput'
        ...ss\Dwarf Fortress 0.43.03/hack/scripts/exportlegends.lua:808: in function 'export_site_maps'
        ...ss\Dwarf Fortress 0.43.03/hack/scripts/exportlegends.lua:819: in function 'f'
        ...warf Fortress\Dwarf Fortress 0.43.03\hack\lua\dfhack.lua:562: in function <...warf Fortress\Dwarf Fortress 0.43.03\hack\lua\dfhack.lua:503>
        (...tail calls...)

**Comment by lethosor** [comment]
That's a weird traceback, but also a pretty old DF version. Can you try reproducing it with DFHack 0.44.05-alpha1? The save you're using should load in 0.44.05. Alternatively, if you upload the save, I could take a look at it.

**Comment by lethosor** [comment]
Given that you're using 0.43.03, this is probably the same issue as #1017/#1095. Please upgrade and reopen if the problem continues.
