### ISSUE TITLE
docs for embark-assistant

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#1226]
From #1159 

@PatrikLundell anything specific you'd like to use for this? Otherwise it will probably be pretty minimal (e.g. commands to run from the console) unless you add stuff to Plugins.rst.

**Comment by PatrikLundell** [comment]
No, the purpose is to have it invoked/exited actively rather than have it take over the control by default. That way it can be introduced fairly safely.

Things have happened since it was written, in particular the naming and identification of fields, so I'm not surprised some updates were needed.

**Comment by lethosor** [comment]
This was probably unclear since I wrote it quickly... anyway, ab9rf brought up the fact that there isn't any documentation in Plugins.rst, and I was going to put in a few lines but was wondering if there was anything you wanted to mention. I think it's fairly obvious how to use it, but a short description would be nice, as well as how to start it (running embark-assistant in the console works, but I'm not sure if there's another way).

**Comment by PatrikLundell** [comment]
I basically don't know about Plugins.rst, so I need to find out what it is, and I must have failed to understand ab9rf's comment (I'll look at it again).

The intended way to start is is from the console, and I'm not aware of any other way...

**Comment by lethosor** [comment]
Ok. Plugins.rst is the source file of https://dfhack.readthedocs.io/en/latest/docs/Plugins.html , and ab9rf's comment was on IRC earlier.

Short version: anything you want to say to describe the plugin? I can make something up if that's easier.

**Comment by lethosor** [comment]
I stole the blurb from embark-assistant.cpp; let me know if you want something else.

**Comment by PatrikLundell** [comment]
Thanks. I think that is as good as it will get for the time being.
If ar9bf's comment was made on IRC it would explain why I haven't seen it, as I don't use IRC...
