### ISSUE TITLE
deramp reliability issues

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#1228]
From IRC:

> \<zava> deramp sometimes works and sometimes does not. older designations are ignored and if it works it works once. Maybe that's a feature

Possibly related to #481

**Comment by lethosor** [comment]
Update: I was wrong, probably not the same as #481, although fixing it could also shed some light on occasional issues I've seen with the fix for #481:

> \<zava> it is. just use different priorities and then deramp. there's no output

**Comment by suokko** [comment]
Is it possible this would be related to designation to job handling reseting map_blick->designation when job is created? (bug #1229)

I will have a look.

**Comment by lethosor** [comment]
Yeah, it's probably similar to #481/#1229

**Comment by lethosor** [comment]
Fixed in #1317
