### ISSUE TITLE
64-bit Linux start_dwarf_count missing

### ISSUE THREAD

**Issue by sc3454998** [DFHack/dfhack#1239]
EDIT: This is on Debian 9

The value in symbols.xml for start_dwarf_count is either missing or wrong. When I run the command "startdwarf" I get the following

`E: RuntimeError: ./hack/scripts/startdwarf.rb:18: patch address not available
 ./hack/scripts/startdwarf.rb:18
 (eval):1:in "load"
 (eval):1
 (eval):1:in "catch"
 (eval):1'`

I'm no expert, but this seems to be due to the fact that start_dwarf_count is missing a value in the linux section of symbols.xml.

Is there any way to determine this value so I can manually fix the problem with symbols.xml?

**Comment by lethosor** [comment]
Yeah, that's missing because the script to find it doesn't work for the 64 bit Linux build, and nobody has managed to fix it yet. It's probably possible to find via disassembly.

You're also several versions behind, although more recent versions also have this issue.

**Comment by sc3454998** [comment]
Thanks, I think I'm several versions behind because I'm using the most recent version of the "Lazy Noobs Pack." I'll Do my best to find the correct offset via disassembly, but I thought I'd try my luck asking the DF experts first.

I am slightly worried that the DFHack developers don't seem to be supporting the project for linux, but I understand that Windows and MacOS are a priority.

**Comment by lethosor** [comment]
That's not true. DFHack was created specifically with improving utilities for Linux in mind, and we try to avoid anything that breaks certain platforms. All of our tests (admittedly not many) are run on Linux, and Linux makes up a larger than average percentage of our user base. This is just one offset out of several dozen that's missing, because it's harder to find than every other offset and isn't a priority on any OS.

**Comment by sc3454998** [comment]
Thank you for clearing up DFHack's policy regarding Linux. I'm sure you are careful to keep Linux in mind when you create these utilities that we are all grateful for. I still do not understand why Windows and MacOS have the correct offsets and Linux does not...

**Comment by lethosor** [comment]
64-bit Linux does not. 32-bit Linux does. Like I said, this is currently the **hardest offset to find**, because it isn't a global, and only **one** script uses it, so it's not a high priority to find if the automated scan doesn't work (which it doesn't for 64-bit Linux, although it's intended to).

**Comment by sc3454998** [comment]
Thanks. Sorry if I sounded critical, you guys are awesome

**Comment by jjyg** [comment]
The script to find this global is now fixed. You can add these addresses to hack/symbols.xml :
global-address name='start_dwarf_count' value='0xf42176'     (linux64, df 0.44.11)
global-address name='start_dwarf_count' value='0xf435d6'     (linux64, df 0.44.12)
