### ISSUE TITLE
Can't build current `develop`-Branch due to error in `world_raws.h`

### ISSUE THREAD

**Issue by nshcat** [DFHack/dfhack#1248]
Hello,
I've been trying to compile the current `develop` branch on my ArchLinux system. I'm using a pristine clone of this repository, without any personal changes. Nevertheless, when trying to perform the build I get the following error:

    /home/katharina/git/dfhack/library/modules/Materials.cpp: In member function ‘bool 
    DFHack::Materials::ReadDescriptorColors()’:
    /home/katharina/git/dfhack/library/modules/Materials.cpp:736:31: error: ‘struct df::world_raws’ has no 
    member named ‘descriptors’
          size_t size = world->raws.descriptors.colors.size();
                                    ^~~~~~~~~~~

I realize that the different descriptor tables were supposed to be merged into one sub-struct member called `descriptors`, and the current TWBT patches and changes in dfhack reflect that change. But for some reason, it is not present in `world_raws.h` for me.

I used the the following CMake parameters:
`cmake .. -DCMAKE_BUILD_TYPE=Release -DDFHACK_BUILD_ARCH=64 -DCMAKE_INSTALL_PREFIX=<path to my df installation>`

Thanks in advance for any help!

**Comment by nshcat** [comment]
Issue resolved it self. Submodules didn't update after branch switch even though I told git to do so.

**Comment by lethosor** [comment]
How did you tell git to do that (and when)?
