### ISSUE TITLE
SIGFPE while using DFHack

### ISSUE THREAD

**Issue by moonheart08** [DFHack/dfhack#1257]
./dfhack: line 68:  9732 Floating point exception(core dumped) setarch "$setarch_arch" -R env LD_PRELOAD="$PRELOAD_LIB" ./libs/Dwarf_Fortress "$@"

# Plugins in use
autolabor
setfps
prospect
autochop
tweak (Default configuration)
# Core file
Will upload the dump if requested.
# Save
The save is brand new, so I don't think(?) it was involved. Will upload on request.

This may or may not be a DFHack issue, so I opened a issue just in case.

I'm willing to help debug the issue, and already have tools (gdb, valgrind, etc) installed to help if needed.

**Comment by lethosor** [comment]
Is it reproducible? What build of DFHack are you using (and what GCC version was it built with)?

**Comment by moonheart08** [comment]
I'm using DFHack 0.44.09-r1 compiled with GCC 7

**Comment by lethosor** [comment]
The GCC 7 builds are pretty new. When did this crash happen? If it's not reproducible, there's not much we can do, but you can try disabling plugins or DFHack and see what happens, or try the GCC 4.8 build.

**Comment by moonheart08** [comment]
Also, for reference, it is probably in some patched data (DFHack)

    (gdb) bt
    #0  0x0000000000f6a659 in  ()
    #1  0x0000000001083435 in  ()
    #2  0x0000000000cde62e in  ()
    #3  0x0000000000cde85d in  ()
    #4  0x000000000073e7a2 in  ()
    #5  0x00007ffff69faeb2 in interfacest::loop() () at 
    /home/moony/Games/df_linux/libs/libgraphics.so
    #6  0x00000000009b63de in mainloop() ()
    #7  0x00007ffff69df1c5 in enablerst::async_loop() () at 
    /home/moony/Games/df_linux/libs/libgraphics.so
    #8  0x00007ffff69df4e0 in call_loop(void*) () at 
    /home/moony/Games/df_linux/libs/libgraphics.so
    #9  0x00007ffff6fe700b in  () at /usr/lib/libSDL-1.2.so.0
    #10 0x00007ffff702830a in  () at /usr/lib/libSDL-1.2.so.0
    #11 0x00007ffff546608c in start_thread () at /usr/lib/libpthread.so.0
    #12 0x00007ffff5debe7f in clone () at /usr/lib/libc.so.6

**Comment by lethosor** [comment]
None of those addresses look like DFHack to me. libgraphics.so is part of DF, and the stuff at the top is probably DF, given that the executable is loaded into memory at 0x400000 and extends to at least 0x2000000.

**Comment by moonheart08** [comment]
Oh, dur. I'm a derp. The lack of symbols confused me 
I'll look a little more into it.

**Comment by lethosor** [comment]
I'm pretty sure this is the [DF bug](http://www.bay12games.com/dwarves/mantisbt/view.php?id=10061) I mentioned. If you can only reproduce it with DFHack, though, feel free to reopen this.
