### ISSUE TITLE
DFHack console can execute removed Lua functions

### ISSUE THREAD

**Issue by PatrikLundell** [DFHack/dfhack#1260]
I don't where this issue originates. It might a a DFHack or Lua issue. If you have a script that calls a widgets.List callback function that doesn't exist the script fails with a rather unhelpful error message. However, if the function is there in the Lua script file, the script is executed and exited normally, then the Lua file is modified to remove the function and you execute the script again, the script will call the no longer existing function without issues, but if DF is exited and restarted, the script fails (as there's no cached copy of the removed function).

The following script illustrates the issue by performing the following steps:
- Run the script. It fails (as expected). This step is not strictly necessary.
- Edit the script to remove the comments in front of the Ui:MFP_Callback function and save the file.
- Run the script. It brings up a DFHack screen. Exit with <ESC>
- Edit the script to comment out the function again and save the file.
- Run the script. It does behave as if the function was still there.

I don't think it's an issue specific to widgets, and it might not even be restricted to callbacks.
(MFP = Minimal Faulty Program, by the way).
I'm on Windows 10.1, if  the OS is of importance, and I made and tested the MFP with DFHack 0.44.09-r1.

```
local gui = require 'gui'
local widgets = require 'gui.widgets'

function MFP ()
  Ui = defclass (Ui, gui.FramedScreen)
  Ui.ATTRS = {
    frame_style = gui.GREY_LINE_FRAME,
    frame_title = "MFP"
  }

  --============================================================
 
  function Ui:init ()
    self.stack = {}
    self.item_count = 0
    self.keys = {}
    local Main_Page = {}
    
    Main_Page.List =
      widgets.List {view_id = "MFP",
                    choices = {},
                    frame = {l = 1, t = 1, yalign = 0},
                    text_pen = COLOR_DARKGREY,
                    cursor_pen = COLOR_YELLOW,
                    inactive_pen = COLOR_GREY,
                    on_select = self:callback ("MFP_Callback")}
    local mainPage = widgets.Panel {
      subviews = {Main_Page.List}}
                
    local pages = widgets.Pages 
      {subviews = {mainPage},view_id = "pages",
                   }

    pages:setSelected (1)
    Focus = "Main"
      
    self:addviews {pages}
  end

  --==============================================================

--  function Ui:MFP_Callback (index, choice)
--  end
  
  --==============================================================

  function Ui:onInput (keys)
    if keys.LEAVESCREEN_ALL or
       keys.LEAVESCREEN then
        self:dismiss ()
    end
  end
  
  --==============================================================

  function Show_Viewer ()
    local screen = Ui {}
    persist_screen = screen
    screen:show ()
  end

  --============================================================

  Show_Viewer ()  
end

MFP ()```

**Comment by lethosor** [comment]
This is expected. You're passing Ui to defclass, so it copies all fields from the old Ui table first.

**Comment by PatrikLundell** [comment]
Thanks for the answer. In case someone else digs this up and is interested, the explanation led me to dig around and find a work around: add "Ui = {}" before the line calling defclass to make sure you're wiping any old garbage before (re)defining the class.
That part of the script comes from copying how gui/gm-editor does its UI, by the way.

**Comment by lethosor** [comment]
Or just `defclass(nil, parent)` would work (or maybe `defclass({}, parent)`).

**Comment by PatrikLundell** [comment]
Hm, yes. nil worked and is a much better alternative. I must have misread the defclass script, as I got the impression there was a check to reject nil.
