### ISSUE TITLE
Autogems should respect workshop profile

### ISSUE THREAD

**Issue by TV4Fun** [DFHack/dfhack#1263]
I have two jeweler's workshops. One I specifically want used for gem cutting, and the other I want used for gem setting. If you have a manager, you can set the type of job each workshop is used for in the workshop profile. Specifically, I can disable gem cutting for one workshop, and disable gem setting for the other workshop. Even doing this though, autogems will still send cut gem jobs to both workshops. It would be nice if autogems respected this setting, or if there were another way to tell it to only send jobs to specific workshops.

**Comment by lethosor** [comment]
Is this a new-ish feature? I don't remember being able to limit jobs before (only dwarves or skill levels). If it's new, we might not have enough information in df-structures to be able to do this yet.

**Comment by TV4Fun** [comment]
@lethosor yes, this was a new feature in 0.43.01, which added a lot of nice features to the manager interface, basically making Workflow obsolete. Do we have more information on this in df-structures yet? I was thinking it would be nice to write a tool to manage jobs in bulk and be able to save and load repeating jobs between fortresses if DFHack has enough information to do that.

**Comment by lethosor** [comment]
I think `workshop_profile` is what you'd be looking for, given that it has a field called `blocked_labors`, which we added in https://github.com/DFHack/df-structures/commit/c8095b66fc0e1135628a91db67e6715c0b8b8c5f
