### ISSUE TITLE
view-item-info.lua Loses info when repeatedly viewing the same item.

### ISSUE THREAD

**Issue by PatrikLundell** [DFHack/dfhack#1273]
If you view the same clothing item in the inventory of a dorf each viewing adds a blank line in between the item description and the properties, gradually pushing all of it below the bottom of the view.

The reason for this is that "get_custom_item_desc" fetches the description and then adds a blank line before returning the result. For some reason that added blank line gets included the next time that description is fetched, so it probably has somehow been added to the wrong item.

You may also consider squashing multiple items onto the same line, as I suspect there's a fair bit of info that's pushed below the bottom edge even at the first viewing.

**Comment by lethosor** [comment]
You realize you can scroll down with `+-*/`, right? The duplicate blank lines should be removed, but the information not visible on the first page is still possible to get to.

**Comment by lethosor** [comment]
> unless the blank line(s) end up in DF itself

I thought you were saying they did end up displayed - is that not the case?

**Comment by lethosor** [comment]
What string? The list that view-item-info modifies is a temporary list of strings that is freed when the screen closes. I think the item description itself (v) is generated on the fly as well, but view-item-info doesn't touch that.

**Comment by lethosor** [comment]
Ok, it looks like the issue here is that a new line gets added after the main description every time, regardless of the item being viewed (viewing the same item repeatedly does it too).
