### ISSUE TITLE
Max quality for planned buildings

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#1274]
Suggested by JezaGaia at http://www.bay12forums.com/smf/index.php?topic=164123.msg7757035#msg7757035

> I can select the min quality of items I want used but not the max, so say I want to keep my wasterwork quality beds for my nobles and furnish the other rooms with any other quality I haven't found a way for it.

**Comment by TotallyGatsby** [comment]
It seems like the ItemConstraint has a min_quality property. Would the approach here be to just add a max_quality property, and check/set it everywhere that min_quality is set in workflow.cpp?

If so, I can probably make an attempt at this.

**Comment by lethosor** [comment]
This is about buildingplan, so stuff is spread between plugins/buildingplan.cpp and buildingplan-lib.{h,cpp}. In addition to what you mentioned, you'll need to display it in the sidebar and save it somehow (it looks like config.ival(1) through config.ival(3) are used, so config.ival(4) should be ok).

**Comment by TotallyGatsby** [comment]
Ok, got the latest develop branch compiling. Lemme see what I can do.

**Comment by TotallyGatsby** [comment]
Is there precedence for how min/max should interact while cycling? 

Example:
Min is set to 'FinelyCrafted', and I cycle max past 'Artifact'. Should it:
a) Go to 'Ordinary' (the bottom value)
b) Go to 'FinelyCrafted' (the current minimum value)

I can see either being reasonable.

**Comment by lethosor** [comment]
I think DF has a quality selection in the workshop profile screen - you could look at that for ideas. I'm not sure if there's a good way to do this with just 2 keys instead of 4.

**Comment by TotallyGatsby** [comment]
Tossed up a (perhaps naive?) implementation. Your comment about 4 keys makes me wonder if I'm missing a quality of life change. (Were you thinking that you'd want to cycle up and down with two keys per entry? e.g. Q - increase minimum, q - decrease minimum, W - increase maximum, w - decrease maximum)

**Comment by lethosor** [comment]
If you think sticking with the two behaviors you listed is better, I think (b) is the more intuitive one, because you won't end up with combinations that exclude all items.

**Comment by TotallyGatsby** [comment]
Cool. I can take a pass on the interface. Lemme know if there's anything else in the PR you think needs to be touched up.

**Comment by TotallyGatsby** [comment]
The workshop manager lowers the min when the max goes lower than the min (and raises the max when the min goes above the max.) It uses four keys.  I'll match that behavior.

Would you prefer I keep min on Q? Or should I move it to match the workshop profile? (Which uses /* -+)

**Comment by lethosor** [comment]
I'd rather use some letter keys than scrolling keys, since those could potentially conflict with DF if the menu changes at all (and really wouldn't be used for scrolling in this case).
