### ISSUE TITLE
[0.44.10-beta1 x64] prospect causes crash

### ISSUE THREAD

**Issue by Tharn** [DFHack/dfhack#1276]
Using a savegame grandfathered in from 0.43.X (not sure if this is relevant or not), the game crashes immediately and without any error popup if I run `prospect hell all` or even just `prospect`.

The last line in stderr.log reads ``Invoking: prospect``

**Comment by lethosor** [comment]
I can't reproduce this with saves between 0.40 and 0.44. Can you upload your save somewhere?

**Comment by Tharn** [comment]
Here's the save: https://mega.nz/#!NXoz0aRL!rt0J7cg2OQFLejHyz1UIKElloMHql4duUEwcq0AWbao

**Comment by lethosor** [comment]
That helps a lot, thanks. I got output through the `>>> TOTAL = ` line, then a backtrace:
```
Thread 7 Crashed:
0   prospector.plug.dylib         	0x000000010df3b716 printVeins(DFHack::color_ostream&, std::map<short, matdata, std::less<short>, std::allocator<std::pair<short const, matdata> > >&, DFHack::Materials*, bool) + 230
1   prospector.plug.dylib         	0x000000010df3e9d5 prospector(DFHack::color_ostream&, std::vector<std::string, std::allocator<std::string> >&) + 7717
```
so this should help us figure out what's going on.

**Comment by lethosor** [comment]
There's something weird with vein materials on your map that I haven't figured out yet. I feel like this has come up before, but the closest thing I've found is a45438d17273988fd00cc79896578fc55fbb5b82, which is a fix for 3dveins but not the same cause.
Anyway, the crash should be replaced with a warning now. `prospect` and `prospect hell all` don't crash any more on your save. I'll create another issue for tracking down the vein weirdness, so please keep your save up if you can.
