### ISSUE TITLE
error messages sometimes assume that the user already knows exactly where they come from

### ISSUE THREAD

**Issue by db48x** [DFHack/dfhack#1282]
I've noticed that I occasionally get an error message like "This script requires a workshop job selected in the 'q' mode" in the DFHack console. I don't know what key I pressed to get this error, which makes tracking it down much harder. I'm using the default DFHack configuration, so I didn't even explicitly enable "this" script. A quick grep says that there are 22 files containing `this script` and `qerror` on the same line, so there are a number of error messages that should be fixed.

**Comment by warmist** [comment]
More info: `qerror` hides the trace of error log. Replacing it with `error` should help.

**Comment by db48x** [comment]
Stack traces are good for developers, not so good for ordinary users.

**Comment by db48x** [comment]
Ah, that's a good suggestion.

**Comment by lethosor** [comment]
We can probably prepend the current script name pretty easily (unix-style), but keep in mind that qerror doesn't necessarily have to be called from scripts.

**Comment by db48x** [comment]
Yes, but a user shouldn't have to care too much about the difference between a script and a plugin. The message source should be identifiable in either case.

**Comment by db48x** [comment]
Testing this is hard, since I don't know how I was triggering it in the first place.
