### ISSUE TITLE
Several plugins' daily events are delayed after save/load cycles

### ISSUE THREAD

**Issue by Tharn** [DFHack/dfhack#1286]
I set an Unlimited autochop setting to clean a burrow. Documentation says the script should activate every day, but it does not activate for me at all. Removing the burrow and doing it for the whole map does not work either.

I tried waiting a month, saving and loading the game, as well as erasing the ~8500 logs l had gathered and waiting.

Autochop does activate once if I go into `d-t-c` and hit Esc. I assume this setting is correct?

![untitled](https://user-images.githubusercontent.com/13466852/40430717-083261ac-5ea6-11e8-9cf5-dfff96a1c5af.png)

**Comment by lethosor** [comment]
> Autochop does activate once if I go into d-t-c and hit Esc

So does it work every time you enter and exit the settings screen, then, or just once?

**Comment by lethosor** [comment]
Is it possible that you've unloaded a world and loaded this one in the same DF session?

**Comment by lethosor** [comment]
Cool. This is actually a pretty widespread problem, affecting at least
* autochop
* autodump
* automelt
* autotrade
* buildingplan
* dwarfmonitor
* embark-tools
* fix-unit-occupancy
* fortplan
* mousequery
* stockflow
and possibly other plugins that my search didn't turn up (or scripts, although less likely)

**Comment by Madrawn** [comment]
Hi, I can confirm this. I was googling why planning mode stopped for me and I too did save and reload my game without quitting DF.

Quitting DF fixed it, but I had to place another planned cabinet before it and all the other planned stuff started to get placed.

DF: 0.44.10
DFhack: 0.44.10-r1

**Comment by lethosor** [comment]
> I had to place another planned cabinet before it and all the other planned stuff started to get placed

Did you unpause and let the game run for at least a day?

**Comment by Madrawn** [comment]
I believe so.
I'll try it out... 
Placed 5 planned beds... saved game... loaded game without quitting. 26th... 27th... 1st.. produced 4 more beds all in storage... nothing gets build.

Saving game again... closing DF... starting DF again.... loading game again... it's the 3rd all beds still planned... unpause... still 5 beds in storage... and it's the 6th and all beds got placed.

Ok probably didn't have beds ready to be placed the last time.

**Comment by lethosor** [comment]
Updates:
* autogems uses a different method but appears to also be affected.
* embark-tools just checks/stores mouse flags, which shouldn't be an issue.
* mousequery just stores enabler->clock, which is independent of save/load cycles
* workflow *looks* okay, but uses the same bad pattern and should be adjusted - the difference is that it actually resets its "last frame" counter in init_state(), which is called when a map is loaded, so it shouldn't be broken as-is.

Others not on the list above:
* siege-engine actually checks world->frame_counter correctly!
* `tweak pausing-fps-counter` is probably not affected, at least by this issue - it stores pause state (easily adjusted in-game) and some timing information from enabler.

**Comment by lethosor** [comment]
Autogems actually uses the same (safer) method to reset its counter as workflow, but I'll still change it.
