### ISSUE TITLE
[0.44.10-r1 x64] Stockpile 'i' function lists military worn inventory

### ISSUE THREAD

**Issue by Tharn** [DFHack/dfhack#1288]
I have a game with very specialized stockpiles. Browsing through them with DFHack's `i`nventory function will display ghost entries of stuff that isn't actually in the bins. My stockpiles for finished goods, wooden shields, bone weapons and the various armour and weapons segregated by metal quality will *all* include items worn in the current inventory of military units.

And these entries are not properly sorted by stockpile, i.e. the finished goods stockpile won't just list waterskins that have been taken from there but whole military inventories, including steel gear, quivers, waterskin contents and so forth. And it's the same with all other stockpiles.

Just noticed it now, but it's probably visible in the save I already uploaded. Subterran level 3 has finished goods stockpiles on the top row sorted by quality. Subterran level 12 has all the weapon and armour stockpiles. Easiest way to see this is to hide all stockpile filters except 'In Inventory'.

The weirdest example is `raw mussel [2]` found in the *furniture* inventory that has had large pots / food storage disabled for in-game *decades*. No idea how that listing got there, as there's not even a reason for military dwarves to interact with that stockpile.

**Comment by lethosor** [comment]
That's the save from #1276, yes? Is it confirmed in there?

**Comment by Tharn** [comment]
Yup, just checked it.

**Comment by lethosor** [comment]
Fixed in #1316
