### ISSUE TITLE
Broken script: "remove-stress all" fails when used with the "all" argument

### ISSUE THREAD

**Issue by AncalagonX** [DFHack/dfhack#1290]
**remove-stress** on _individual_ dwarves works fine and removes stress correctly. However, **remove-stress all** gives the below error and does not function:

```
[DFHack]# remove-stress all
...1\PERIDE~2.10-\Dwarf Fortress 0.44.10\hack\lua\utils.lua:607: error parsing arg 1: all
stack traceback:
        [C]: in function 'error'
        ...1\PERIDE~2.10-\Dwarf Fortress 0.44.10\hack\lua\utils.lua:607: in function 'utils.processArgs'
        ...0-\Dwarf Fortress 0.44.10/hack/scripts/remove-stress.lua:20: in local 'script_code'
        ...\PERIDE~2.10-\Dwarf Fortress 0.44.10\hack\lua\dfhack.lua:562: in function 'dfhack.run_script_with_env'
        (...tail calls...)
[DFHack]#
```
This has been like this for all the 0.44.10 DFHack alpha/beta/RCs. I never tried to use this command before 0.44.10, so I don't know how far back this problem first cropped up.

This has occurred for two fortresses on two different world gens now. Both of these fortress are using **Old Genesis mod for 0.44.10**. My forts also have several visitors of non-dwarf races milling around. Let me know if you need any other useful info.

**Comment by lethosor** [comment]
Already fixed in https://github.com/DFHack/scripts/commit/7b30d55e97f2859f48341bd1f889ef6b98b37d33
