### ISSUE TITLE
Suggestion: "remove-stress" should remove the temporary "Depression" from dwarves

### ISSUE THREAD

**Issue by AncalagonX** [DFHack/dfhack#1291]
**remove-stress** should remove the _temporary_ "Depression" status from dwarves who have fallen into it.

**remove-stress** currently operates correctly on haggard, stressed, normal, _and_ temporarily "Depressed" dwarves by setting their stress level to a very low value.

However, when used on the aforementioned temporarily "Depressed" dwarves, they remain in the "Depressed" state for quite some time before recovering, despite having had their stress correctly force-removed by this command.

What should happen is their "Depression" status should be removed. Thanks for your time and generosity spent on making DFHack better and better over the years.

**Comment by tswaugh** [comment]
Remove stress no longer seems to remove haggard correctly with the release of the Steam version.

**Comment by ab9rf** [comment]
> Remove stress no longer seems to remove haggard correctly with the release of the Steam version.

could you please raise this as a new issue instead of resurrecting one that's been closed for five years

**Comment by tswaugh** [comment]
I already did as https://github.com/DFHack/dfhack/issues/2954
