### ISSUE TITLE
Dwarfmonitor/manipulator stress thresholds are inaccurate

### ISSUE THREAD

**Issue by TV4Fun** [DFHack/dfhack#1292]
Since upgrading to 44.10, the happiness summary from dwarfmonitor appears to be inaccurate in my fortress. In 44.09, I had quite a few unhappy dwarves, though in 44.10, dwarfmonitor shows no one below the third highest happiness level. This despite several dwarves showing red down arrows, and others throwing tantrums and slipping into depression.

**Comment by lethosor** [comment]
It has rarely showed dwarves below the third level since around 0.42 (or maybe 0.40?). I suspect this is a longer-standing issue, unless it was listing dwarves below that level in 0.44.09.
Anyway, I'm pretty sure this is based on stress level. What does manipulator say? If they're not stressed, there's not a lot we can do about it.

**Comment by TV4Fun** [comment]
It was listing dwarves at much lower levels in 44.09. Manipulator says they are extremely stressed, haggard, questioning their life decisions, etc.

**Comment by lethosor** [comment]
Manipulator doesn't say those things... are you talking about the vanilla "v" screen, or maybe therapist?

**Comment by TV4Fun** [comment]
Sorry, I was talking about the "v" screen. To give a few examples, manipulator shows the stress of one very depressed dwarf at 100,000. It shows several others over 10,000, including one who recently threw a tantrum at 57,762.

**Comment by lethosor** [comment]
To be clear, that's red or yellow, not -100,000 (light green)?
What if you `reload dwarfmonitor`? It looks like it may be affected by #1286.

**Comment by TV4Fun** [comment]
The number 100,000 shows in yellow. The numbers less than that show in dark green. `reload dwarfmonitor` and re-enabling it left the happiness summary unchanged.

**Comment by lethosor** [comment]
> The numbers less than that show in dark green

Oh, so 57,762 is dark green? That implies that it's lower stress, at least according to the cutoffs that manipulator and dwarfmonitor use, which means that it'll also display in one of the happier categories in dwarfmonitor. If that's the case, either our cutoffs are wrong or something else is determining tantrums, which is harder to fix.

**Comment by lethosor** [comment]
This is probably the same as https://github.com/Dwarf-Therapist/Dwarf-Therapist/issues/98

**Comment by lethosor** [comment]
Fixed in 2dac3c53
