### ISSUE TITLE
ban-cooking broken since last update

### ISSUE THREAD

**Issue by tsaber** [DFHack/dfhack#1320]
Or is it just me ?
Here's the error:
E: NoMethodError: undefined method `&' for :Cook:Symbol
 ./hack/scripts/ban-cooking.rb:23
 ./hack/scripts/ban-cooking.rb:22:in `times'
 ./hack/scripts/ban-cooking.rb:22
 (eval):24:in `load'
 (eval):24
 (eval):24:in `catch'
 (eval):24

E: NoMethodError: undefined method `&' for :Cook:Symbol
 ./hack/scripts/ban-cooking.rb:23
 ./hack/scripts/ban-cooking.rb:22:in `times'
 ./hack/scripts/ban-cooking.rb:22
 (eval):1:in `load'
 (eval):1
 (eval):1:in `catch'
 (eval):1

 
I was using ban-cooking brew, tallow and booze

Regards, Zava
4.17.1-1-ARCH 64

**Comment by lethosor** [comment]
Duplicate of #1293
