### ISSUE TITLE
Cursecheck maybe broken for werebeasts 44.05? 

### ISSUE THREAD

**Issue by ianlintner** [DFHack/dfhack#1323]
I am on a mac but I saw the same thing on PC.

If anyone else has seen this. I am using the versions bundled with Lazy Newb Pack, but I think it has been in multiple versions possibly.

**Comment by lethosor** [comment]
We have made a few changes to cursecheck for DFHack 0.44.10-r2 and don't support 0.44.05 any more. Can you test with 0.44.10-r2?

**Comment by lethosor** [comment]
The save from http://www.bay12games.com/dwarves/mantisbt/view.php?id=10530 (http://dffd.bay12games.com/file.php?id=13428) appears to have a vampire, but neither I nor `cursecheck` could find it. Do you have a current save?

**Comment by ianlintner** [comment]
I just got a current build of the 44.11 alpha installed on my Mac with DFHack.

I started a .11 game. When/if I get to the generated werebeast attack I will save it out this weekend.

**Comment by ianlintner** [comment]
Can you generate a cursed creature or curse an existing creature with a dfhack script IDK?

**Comment by lethosor** [comment]
I suspect curses have changed somehow. If that's the case, an existing DFHack script to cause curses would be useless, because it would produce things different from curses produced by vanilla DF.

**Comment by ianlintner** [comment]
This is the first time I have looked at the dfhack code so take this comment with a grain of salt... is it possible that the curse_year or unk_4c bits aren't set anymore. That would make the most sense on my reading of curse check and units code... at least for werebeast.

**Comment by lethosor** [comment]
`curse_year` is my guess, although that would be strange. I've been trying to find a 0.44 save with a cursed unit - the one I found on Mantis didn't have a vampire that I could identify.

**Comment by lethosor** [comment]
Did this get fixed?
