### ISSUE TITLE
Console freezes on startup on Windows

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#1345]
http://www.bay12forums.com/smf/index.php?topic=164123.msg7801798#new

https://www.reddit.com/r/dwarffortress/comments/8wpotq/dfhack_04411beta1_released/e1xz4s4/

**Comment by Tharn** [comment]
Same here.. I don't know if it's a 'freeze' as the cursor is blinking, but I can't enter any commands.
![untitled](https://user-images.githubusercontent.com/13466852/42412903-b67bb258-8215-11e8-86f2-530af6ce62e0.png)

**Comment by lethosor** [comment]
The cursor is a system feature, so it blinking doesn't mean anything. It's interesting that you're getting output in the console, though. Are you able to enter text in the console (without necessarily running commands) at all?

**Comment by Tharn** [comment]
Nope, I can't enter text even right after starting DF. The cursor moves to the line right below [DFHack]#. The output also works properly when saving, loading and doing stuff. It just won't accept input.

**Comment by lethosor** [comment]
@suokko ideas on this one? Maybe some later changes from #1304 didn't get added to Console-windows.cpp?

**Comment by suokko** [comment]
Maybe the error check is incorrect at https://github.com/DFHack/dfhack/blob/develop/library/Console-windows.cpp#L288

**Comment by lethosor** [comment]
https://docs.microsoft.com/en-us/windows/console/readconsoleinput

> If the function fails, the return value is zero.
