### ISSUE TITLE
fatal: repository '../../open-source-parsers/jsoncpp.git' does not exist

### ISSUE THREAD

**Issue by PatrikLundell** [DFHack/dfhack#1361]
This message was received when trying to issue the command "git submodule update" after having pulled the develop dfhack branch to get it up to date.
I've seen the logic was changed 3 days ago (by BenLubar), but I'm unsure if it's a matter of my weak git-fu or something that's actually wrong. I haven't yet tried "nuke and redo from scratch"...
I'm on Windows 10.1, if it matters.

**Comment by lethosor** [comment]
Did you try "git submodule init" first?

**Comment by PatrikLundell** [comment]
No. I didn't know there was such a command. I guess this means the json stuff is a new sub repo, and update doesn't know about those (apart from that they should have existed).
However, it seems to work (and I assume nuking and cloning from scratch would indeed have worked).

**Comment by lethosor** [comment]
Yeah, "update" just updates submodule folders that already exist. "init" sets up new ones. Fortunately we don't add new submodules very often, but this is probably worth documenting anyway.

**Comment by PatrikLundell** [comment]
It probably doesn't hurt to document it in the documentation. It would be useful to add a note to the release notes as well: Something along the lines of "The DFHack internal support structure has been modified, resulting in the introduction of a new sub repo. Note that the 'git submodule init' command is required for existing DFHack clones to register the new sub repo."

**Comment by lethosor** [comment]
`git submodule update --init` actually was documented already, although it only mentioned changing branches. I added a note about needing to update submodules after pulling too. (`update --init` is equivalent to `init` followed by `update`.)
