### ISSUE TITLE
blueprint plugin doesn't recognize designations

### ISSUE THREAD

**Issue by tsaber** [DFHack/dfhack#1363]
These designations produce an empty blueprint:
![evidence 1a5c](https://user-images.githubusercontent.com/9378902/42728528-bb17e796-87ab-11e8-9656-1cc2235aa342.png)

**Comment by myk002** [comment]
I think this is an idea rather than a bug. Blueprint doesn't read designations. It reads tile shapes. Creating a dig blueprint only works after you did the area out.

Reading designations works be nice, though :-P
