### ISSUE TITLE
0.44.12-r1 dwarfvet animals being ignored by dwarfs

### ISSUE THREAD

**Issue by tsaber** [DFHack/dfhack#1371]
Early in its development dwarfs would ignore all injured non-dwarfs. 
I think that is the case again. The animals, even when not pastured, spam area inaccessible.

Reproduce. Easy, have a stupid doggo who thinks a kangaroo is a good match.

**Comment by lethosor** [comment]
The title says the animals are being ignored by dwarves, but "area inaccessible" means the animals can't path to somewhere. Are you sure the two are related? Is the animal hospital accessible? I think animals have to actually be there to get treated.
A save would probably help. Having a dog get attacked by a kangaroo isn't easy to reproduce.

**Comment by lethosor** [comment]
Oh, so it's more of a suggestion that dwarves should take wounded animals to the hospital (like the "recover wounded" jobs for dwarves)? I'm not sure how easy it would be to implement, but it does sound like it could be useful.

**Comment by tsaber** [comment]
it has already been a feature. it just stopped working like the blueprint issue i had reported I think.

It's not much work I reckon. I'll take a look at the script

**Comment by lethosor** [comment]
Save from IRC: https://drive.google.com/file/d/1GMo4AassuPG-aCs3dm9FzkWRsYWcH_s3/view

**Comment by warmist** [comment]
A minor note: this issue is already noted in the dwarvet source (if I understood it correctly): https://github.com/DFHack/dfhack/blob/master/plugins/dwarfvet.cpp#L636
I.e.: 

> If health->requires_recovery is set, the creature can't move under its own power and a Recover Wounded or Pen/Pasture job MUST be created by hand - TODO

This might not be too complicated but might be hard to track if it does not leave jobs hanging
