### ISSUE TITLE
Exportlegends info failing on legends_plus xml

### ISSUE THREAD

**Issue by goldenvixen** [DFHack/dfhack#1373]
Hey~ I looked at other threads on here, hoping that there would be a way to solve this problem, but it doesn't seem like anyone has my issue, despite some similiar issues in some of the bug reports here. I think I already have a suspicion on what it is, but it doesn't hurt to make sure. Whenever I attempt to exportlegends info on my world, I get this error:

```
Exporting: Extra legends_plus xml
        historical figure 10000/21035 (48%)
        historical figure 20000/21035 (95%)
...s\Dwarf Fortress 0.44.12/hack/scripts/export legends.lua:605: Cannot read field vector<caste_raw*>. 1: index out of bounds.
stack traceback:
            [C]: in metamethod '__index'
            ...ss\Dwarf Fortress 0.44.12/hack/scripts/exportlegends.lua:605: in global 'export_more_legends_xml'
            ...ss\Dwarf Fortress 0.44.12/hack/scripts/exportlegends.lua:776: in global 'export_legends_info'
            ...ss\Dwarf Fortress 0.44.12/hack/scripts/exportlegends.lua:829: in local 'script_code'
            ...warf Fortress\Dwarf Fortress 0.44.12\hack\lua\dfhack.lua:680: in function 'dfhack.run_script_with_env'
            (...tail calls...)
```

I tried reinstalling the game and dfhack all fresh. I thought maybe that the Lazy Newb Pack I downloaded was corrupted or something, so I tried downloading Dwarf Fortress and DF hack from the main websites, and that didn't work. I am not running this game vanilla so, I came to the conclusion that maybe it was one of the three mods I am using (not including the Meph graphics pack I use)? The mods I am using are Arctic Addition, Succubus Dungeon, and Dark Ages III War & Mythos. With just Arctic Addition and Succubus Dungeon, I was able to use exportlegends info just fine, but when I threw Dark Ages back in it, I ended up getting this error again. Is it possible that there are simply too many things creatures and other things in the Dark Ages mod pack and exportlegends info can't handle a Dwarf Fortress game with so many additions? I do not believe it is a mod compatability issue--I have edited the files in myself, going through each line in the raws to make sure I'm changing and adding things in correctly and I can play the game without any issues with these mods.

For those who want to check the game save, here is a link to download it: https://www.dropbox.com/s/634rwtdfl31soyc/region1.rar?dl=0

**Comment by goldenvixen** [comment]
I’m using the latest version, the 0.44.12-r1 version.

**Comment by goldenvixen** [comment]
Update! I got it to work finally. I went looking through the raws again and I spotted a few duplicates I must have typed in on accident. I got rid of the duplicates, wondering if the extra code was maybe mucking up the legends_plus xml. So for anyone who has the issue I had, check your raws!

**Comment by lethosor** [comment]
Yeah, here's the section from exportlegends.lua:
```lua
                elseif k == "caste" then
                    if v > -1 then
                        file:write("\t\t<caste>"..(df.global.world.raws.creatures.all[event.race].caste[v].caste_id):lower().."</caste>\n")
                    end
```
It already checks to make sure the caste isn't -1 (invalid) - if the caste ID is larger than that, but isn't a valid vector index, I'm inclined to say that it's due to the raw issue that you mentioned, and not something we should address in the script.
