### ISSUE TITLE
companion orders broken in 0.44.12

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#1374]
I'm unclear on details, but apparently they just don't work at all: https://www.reddit.com/r/dwarffortress/comments/90tru9/biweekly_df_questions_thread/e2zi4al/

**Comment by warmist** [comment]
~~It looks like something changed in df. IIRC you could set units path and it would happily go the target. I've had other method in my http server (set idle area and it's threshold) and it seems to works... somewhat, after few ticks it gets reset and companion walks back.~~

Found it in comments/help: 
> If companions are following they will move no more than 3 tiles from you.

So it's working as documented :)

I guess best case would be for someone to look into df disassembly to see if there is any way to work around that. Maybe by using some special path_goal or idle_area.type but last time i looked there was nothing.

However looking into this, i've changed the way it sets a path and fixed one other bug (with screen width not being divisible by two making this error out)

**Comment by warmist** [comment]
Looks like it's a misunderstanding:[here](https://www.reddit.com/r/dwarffortress/comments/90tru9/biweekly_df_questions_thread/e33b8vg) Maybe docs could be improved?
