### ISSUE TITLE
Move full-heal to modtools

### ISSUE THREAD

**Issue by warmist** [DFHack/dfhack#1375]
IMHO it's more useful as a mod tool, e.g. various scripts/interaction etc, could heal/revive your dwarves or enemies.

**Comment by lethosor** [comment]
No, people use it manually too.

**Comment by warmist** [comment]
I guess scripts can just call the full-heal script.

I just worry that it will need hundred of params (e.g. leave scars, all etc...).

**Comment by lethosor** [comment]
Module support from https://github.com/DFHack/scripts/pull/73 should make it easier for other scripts to use directly.

**Comment by warmist** [comment]
Ah nice, missed that one.
