### ISSUE TITLE
Proposal: Move biome type inference engine from embark-assistant to main library

### ISSUE THREAD

**Issue by ab9rf** [DFHack/dfhack#1392]
There is no straightforward way to determine the biome at a particular map tile square in fort mode, but it is possible. @ragundo worked out an inference algorithm for exportmaps in 2016: [see here](https://github.com/ragundo/exportmaps/blob/master/cpp/df_utils/biome_type.cpp). Ragundo's code was imported into dfhack as part of embark-assistant, at https://github.com/DFHack/dfhack/blob/master/plugins/embark-assistant/biome_type.cpp.

I would like to move the (fairly complex) logic in embark-assistant into one of the general library modules, probably Maps. In addition to being used by embark-assistant, I need this logic to make autofarm work correctly (at present, it does a crappy job of assigning seeds to above-ground farms because it can't tell what plants can be planted where). It's also used by df-ai. Rather than replicate the same code across multiple plugins, it makes more sense to move this generic function to a library.

Comments?

**Comment by lethosor** [comment]
Improving code reuse is good. I think the Maps module mostly deals with player-level maps (fort/adv mode), but I guess I can't really think of a better place for world-level map utilities.

**Comment by ragundo** [comment]
Je,Je
That code was a direct translation from IDA.

**Comment by lethosor** [comment]
Closing since it looks like #1394 addresses this fully. Please reopen if I'm mistaken.
