### ISSUE TITLE
fatal error: json/json.h: No such file or directory

### ISSUE THREAD

**Issue by ShimmerFairy** [DFHack/dfhack#1396]
Trying to compile dfhack, I get this problem:

````
[ 28%] Building CXX object library/CMakeFiles/dfhack.dir/RemoteClient.cpp.o
/foobar/dfhack/library/RemoteClient.cpp:58:10: fatal error: json/json.h: No such file or directory
 #include "json/json.h"
          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [library/CMakeFiles/dfhack.dir/build.make:4970: library/CMakeFiles/dfhack.dir/RemoteClient.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:803: library/CMakeFiles/dfhack.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
````

The json.h file clearly exists, in `depends/jsoncpp-sub/include/json/json.h`, and yet can't be found.

**Comment by lethosor** [comment]
The file exists in your local copy, right? Have you tried re-running CMake? If neither of those address the issue, the exact compiler command for RemoteClient.cpp would help (run `make VERBOSE=1` or `ninja -v`).

**Comment by ShimmerFairy** [comment]
This comes from a fresh run of cmake, since I had accidentally cleared out my build directory when updating the repository. Here's the precise command:

`
cd /mnt/d2/repos/git/dfhack/BUILD/library && /usr/bin/c++  -DBUILD_DFHACK_LIB -DDFHACK64 -DHAVE_CUCHAR -DLINUX_BUILD -DLUA_BUILD_AS_DLL -DPROTOBUF_USE_DLLS -D_GLIBCXX_USE_C99 -D_GLIBCXX_USE_CXX11_ABI=0 -D_LINUX -Ddfhack_EXPORTS -I/mnt/d2/repos/git/dfhack/depends/protobuf -I/mnt/d2/repos/git/dfhack/depends/lua/include -I/mnt/d2/repos/git/dfhack/depends/md5 -I/mnt/d2/repos/git/dfhack/depends/tthread -I/mnt/d2/repos/git/dfhack/depends/clsocket/src -I/mnt/d2/repos/git/dfhack/library/proto -I/mnt/d2/repos/git/dfhack/library/include  -fvisibility=hidden -mtune=generic -m64 -mno-avx -O3 -DNDEBUG -fPIC   -include Export.h -std=c++11 -o CMakeFiles/dfhack.dir/RemoteClient.cpp.o -c /mnt/d2/repos/git/dfhack/library/RemoteClient.cpp
`

**Comment by ShimmerFairy** [comment]
It turns out commit 2b79b4cce74a4e5ad728b9cd4d0d8042ef86ec05 may be to blame. When jsoncpp was changed to be a submodule, an include line in the top-level `CMakeLists.txt` was removed without being replaced. Adding it back in, modified for the change to submodule, allows dfhack to compile.

Here is the diff output for the change I made:

````
diff --git a/CMakeLists.txt b/CMakeLists.txt
index e05e5cf2..d618543d 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -370,6 +370,7 @@ find_package(ZLIB REQUIRED)
 include_directories(depends/protobuf)
 include_directories(depends/lua/include)
 include_directories(depends/md5)
+include_directories(depends/jsoncpp-sub/include)
 
 # Support linking against external tinyxml
 # If we find an external tinyxml, set the DFHACK_TINYXML variable to "tinyxml"

````

**Comment by lethosor** [comment]
I'm pretty sure that was removed intentionally, and at any rate, it's worked on Travis, Buildmaster, and for (most) individuals building it since then. What CMake version are you using?

**Comment by ShimmerFairy** [comment]
I currently have cmake 3.12.1 and I'm on gentoo. Interestingly, just in case it's relevant, the cmake package in portage has a `system-jsoncpp` USE flag, which in my case is enabled. I also have jsoncpp 1.8.4 installed via portage.

**Comment by lethosor** [comment]
Try not using your system jsoncpp, then

**Comment by ShimmerFairy** [comment]
I'm confused as to how that would affect things, though. That useflag just means that the compilation of cmake doesn't use the jsoncpp that's bundled with cmake's source. I'd be willing to try recompiling cmake with its bundled jsoncpp, but I don't see how that would affect a project using cmake.

**Comment by ShimmerFairy** [comment]
Well then, apparently it just works now, even with the system-jsoncpp version of cmake. Even going for a new, clean build directory won't trigger the compilation error anymore. I'll close this bug and hope it never comes back.
