### ISSUE TITLE
DFHACK 0.44.12-r1-0 32bit ver error (stocks, searchplugin not enable ) why not?

### ISSUE THREAD

**Issue by xmunchoi** [DFHack/dfhack#1397]
DFHack build: 0.44.12-r1-0-gc2a64b35
DF Version: v0.44.12 SDL win32

plugin search
plugin stocks
not enable.
PeridexisErrant 's Starter Pack 44.12 32bit Edition and
vanilla DF 0.44.12 SDL win32+DFHACK 0.44.12-r1-0 
The same situation occurs.

[stderr.log]
error code :
(https://github.com/DFHack/dfhack/files/2318292/stderr.log)
Invoking: enable search

VMethodInterposeLinkBase::apply(1): stocks_search_hook::feed: no vtable pointer: viewscreen_storesst

Could not enable plugin: search

Invoking: enable automaterial

Invoking: enable confirm dwarfmonitor mousequery autogems automelt autotrade buildingplan resume trackstop zone stocks autochop stockpiles

VMethodInterposeLinkBase::apply(1): stocks_hook::feed: no vtable pointer: viewscreen_storesst

Could not enable plugin: stocks

**Comment by lethosor** [comment]
This was reported on the forums and fixed in https://github.com/DFHack/df-structures/commit/11faf4afe03b8810fe3c681e0c1e660c0abd5afd, but I guess there wasn't a report here, so thanks for the report.

**Comment by lethosor** [comment]
Also, 

> PeridexisErrant 's Starter Pack 44.12 32bit Edition and

PE doesn't put up a 32-bit pack, and hasn't since 2016.

**Comment by xmunchoi** [comment]
think lethosor~ 
PeridexisErrant 's Starter Pack 44.12 64bit edition moding(Korean translation apply only 32bit ver. 64bit ver not translation) pack.

**Comment by lethosor** [comment]
Oh, so you replaced the 64-bit Dwarf Fortress with the 32-bit one? That makes sense if it helps with translation, but it's a good idea to say that it was something you changed.
