### ISSUE TITLE
Possible revflood bug in 44.12?

### ISSUE THREAD

**Issue by YaaZ** [DFHack/dfhack#1408]
I dug some ore and then closed all holes in walls, but when I use revflood, this area is still visible:
![image](https://user-images.githubusercontent.com/9004656/46368603-4ed1ed80-c689-11e8-8440-550046437ce8.png)
I tried to call reveal, then revfoget and then revflood to make sure it is working. So yes, it is working, but somehow not as expected, as this area remained visible. Some time ago I was doing same things with older versions of df and everything worked, so it is possibly a bug in newer versions.

**Comment by lethosor** [comment]
Are those floors? It's hard to tell from your tileset. Are you sure they're closed off? Assuming they're floors, does gui/pathable indicate that they can be pathed to?

**Comment by YaaZ** [comment]
Here is the screen without tileset:
![image](https://user-images.githubusercontent.com/9004656/46370288-e0dbf500-c68d-11e8-9842-7512a499686c.png)
And here is the pathable:
![image](https://user-images.githubusercontent.com/9004656/46370353-1254c080-c68e-11e8-9121-2f8fb3427c18.png)
So no, they are not pathable, but remains visible after revflood

**Comment by lethosor** [comment]
Are those constructed walls or smoothed natural walls walling off the veins? revflood might not handle constructions well.

**Comment by YaaZ** [comment]
Aw yes, these are constructed walls...
But if revflood has issues with constructed walls, is there any other way to unreveal this area?

**Comment by YaaZ** [comment]
Yes, I was using constructed walls and revflood worked with them. Cannot say exact version, maybe 44.09, or maybe even some 43.xx version. I liked using revflood to get rid of all ugly caves around my fortress :c

**Comment by lethosor** [comment]
Yeah, this behavior is intentional from https://github.com/DFHack/dfhack/issues/874#issuecomment-299705891 and https://github.com/DFHack/dfhack/commit/67e60fdaa1844fccda9dd39b6a2b348bc3e499c due to http://www.bay12games.com/dwarves/mantisbt/view.php?id=1871

You could probably use gui/liquids to create natural obsidian walls in those places.

**Comment by lethosor** [comment]
Going to say this isn't a bug per above, but let me know if there are still issues with natural walls or anything else.
