### ISSUE TITLE
Game crashes with dwarfvet and clean patient job

### ISSUE THREAD

**Issue by way-hu** [DFHack/dfhack#1417]
My game (windows x64, df 44.12, DFHack, revised mod) crashes about a second after a vet diagnosed a patient dog. I think that the crash is connected to a "Clean Patient" job being issued. My fort does not have empty buckets, and the crash disappears when I build a few buckets before trying to diagnose.

Might be connected to issue #1270 but I am not sure.

**Comment by lethosor** [comment]
Probably related to #1270. I don't think we fixed anything directly related to dwarfvet in 0.44.12-r2, but can you check with that version, and if it still crashes, upload a save?

**Comment by way-hu** [comment]
I've attached a save file. There's a wounded dog in the animal hospital area. Typing dwarfvet enable on the dfhack console would make the dog sleep at the topleft corner and the diagnostician goes there. As soon as the diagnostician leaves the dog the game crashes. 
[DVCrash.zip](https://github.com/DFHack/dfhack/files/2761174/DVCrash.zip)

**Comment by way-hu** [comment]
Witnessig more crashes I came to think that it is pretty much related to not having the proper items available in the fort. No bucket for cleaning, no thread for suturing, etc.
