### ISSUE TITLE
Typing too much into liquids causes DF crash.

### ISSUE THREAD

**Issue by keupo** [DFHack/dfhack#1425]
Open liquids in the dfhack terminal, type too much, and the game will crash.

Presumably related to [this](https://github.com/DFHack/dfhack/issues/1354), with [this fix.](https://github.com/DFHack/dfhack/pull/1355)

**Comment by lethosor** [comment]
This is not enough information for me to reproduce the issue. What platform are you using? What DFHack version (run "help" if you don't know)? How much, exactly, is "too much"?

**Comment by keupo** [comment]
I'm using a mac
DFHack version 0.44.12-r2 (release) on x86_64
The crash was also present in the last version, after the fix I linked to.
It happens when using a small terminal window with dfhack. Specifically when the liquids state description rolls over onto a new line like:

 [obsidian_floor:range(w333:h33
:z1):7:f+:s.:pf.]#

This would be the state after making a large area obsidian floor. If I now tried to switch to water, by tying w; the game will crash.

**Comment by lethosor** [comment]
OH, so the prompt is taking up two lines. I don't know if @suokko or I ever tested that - the default prompt is so short that a window smaller than that would be unreasonable.

Out of curiosity, do you remember how versions before 0.44.12 handled that? I don't think we've had any kind of multi-line support, so I'd expect it looked pretty bad.

**Comment by lethosor** [comment]
Should be fixed in that commit (in the next release).
