### ISSUE TITLE
ctd on 1x1 embark related to twbt unit_transparency

### ISSUE THREAD

**Issue by Sheepy-Gorilla** [DFHack/dfhack#1429]
When embarking on a 1x1, right after the embark intro text (so at the point the graphics are shown for the first time) the game immediately closes to desktop. There are no error notifications in the error log. (or is there a separate dfhack log? if so, please let me know!)

After some trial and error, I found this is related to the twbt unit transparency (in one of the OnLoad init files). The above error only occurs when it is set to 1. If set to 0, the embark works fine. Right after that I can save, restart the game with twbt unit_transparency 1 and the map loads without problem. So this only occurs on the embark itself.

**Comment by lethosor** [comment]
TWBT has a separate repo where you should report issues: https://github.com/mifki/df-twbt
