### ISSUE TITLE
Adventure mode "commands" full of null pointers

### ISSUE THREAD

**Issue by charliegreen** [DFHack/dfhack#1430]
Hello! This is my first time messing with writing dfhack scripts; please forgive any obvious mistakes I'm making.

I'm trying to modify the "get" menu in adventure mode to show the value and weight of items next to their names. I have a lua script that I'm calling, and it accesses `df.global.ui_advmode.commands`. I can see the normal options for igniting plants or making campfires, but any options for picking up items are just nil. The order and number of nils correspond to the menu I see in-game, though; for example, when standing somewhere where there's nothing to pick up, I don't see any nils.

Here's my code:
```lua
function getUpdate()
    print("Length of commands is: "..#df.global.ui_advmode.commands)
    for i, foo in ipairs(df.global.ui_advmode.commands) do
    	print(i, foo)
    end
end

getUpdate()
```

And here's some example output, standing over a large pile of items:
```
Length of commands is: 28
0	nil
1	nil
2	nil
3	nil
4	nil
5	nil
6	nil
7	nil
8	nil
9	nil
10	nil
11	nil
12	<adventure_environment_pickup_make_campfirest: 0x7fffab809e90>
13	<adventure_environment_pickup_make_campfirest: 0x7fffe02680a0>
14	<adventure_environment_pickup_make_campfirest: 0x7fffe0a95390>
15	<adventure_environment_pickup_make_campfirest: 0x7fffaae557d0>
16	<adventure_environment_pickup_make_campfirest: 0x7fffb24d1dc0>
17	<adventure_environment_pickup_make_campfirest: 0x7fffaba76720>
18	<adventure_environment_pickup_make_campfirest: 0x7fffb399d6b0>
19	<adventure_environment_pickup_make_campfirest: 0x7fffabc76210>
20	<adventure_environment_pickup_ignite_vegst: 0x7fffaae556f0>
21	<adventure_environment_pickup_ignite_vegst: 0x7fffb3932f70>
22	<adventure_environment_pickup_ignite_vegst: 0x7fffb3a86120>
23	<adventure_environment_pickup_ignite_vegst: 0x7fffe0b554f0>
24	<adventure_environment_pickup_ignite_vegst: 0x7fffe0b54d80>
25	<adventure_environment_pickup_ignite_vegst: 0x7fffe0a94ed0>
26	<adventure_environment_pickup_ignite_vegst: 0x7fffabecb440>
27	<adventure_environment_pickup_ignite_vegst: 0x7fffe0a98330>
```

Am I doing something wrong? Or is this the expected behavior? If it is, is there a different way I should be trying to accomplish my goal? Thanks!

**Comment by lethosor** [comment]
I'd say this is expected. DF is probably keeping the item pointers in another list somewhere - this sort of pattern isn't uncommon. I'm not sure where they would be off the top of my head, but probably in ui_advmode somewhere.

**Comment by charliegreen** [comment]
For future reference, this is how I solved this problem:
```lua
local player = df.global.world.units.active[0]
local pos = player.pos
local items={}
for k,v in pairs(df.global.world.items.all) do
    if v.flags.on_ground and v.pos.x==pos.x and v.pos.y==pos.y and v.pos.z==pos.z then
        table.insert(items,v)
    end
end
```
