### ISSUE TITLE
DF always crash when viewing Thoughts and Preferences, after pref-adjust & remove-stress -all

### ISSUE THREAD

**Issue by myxibrium** [DFHack/dfhack#1438]
I opened my game and ran pref-adjust and remove-stress -all. Then the game crashed when I open Thoughts and Preferences on a dwarf. So then I tried it again, saved the game, re-opened it, then ran the commands again. Same thing. The game crashes every time. I've looked in all the log files and there's nothing useful.

I'm using DFHack version 0.44.12-r2 (release) on x86_64
On PyLNP 0.13b

**Comment by lethosor** [comment]
Can you try just one of these to help narrow it down? That is, what happens if you load the game and only run one of these commands?

**Comment by myxibrium** [comment]
Unfortunately since I'm an idiot and saved over the game, it always crashes no matter what I do.

**Comment by lethosor** [comment]
My guess from http://www.bay12forums.com/smf/index.php?topic=164123.msg7961462#msg7961462 would be pref-adjust. I'll make sure it gets updated for the next release.

**Comment by myxibrium** [comment]
Thanks!

**Comment by myxibrium** [comment]
Funny story: I abandoned that fortress and started a new one. Then some dwarfs from the other fortress immigrated into the new one. Then I crashed the game again and lost a bunch of progress. Now I'm generating a new world. First world problems.

**Comment by lethosor** [comment]
A fix has been merged for 0.47.04-r2 - you can grab the fixed script here in the meantime: https://github.com/DFHack/scripts/blob/master/pref-adjust.lua
