### ISSUE TITLE
Noisy Gatekeeper on Catalina

### ISSUE THREAD

**Issue by tommy** [DFHack/dfhack#1465]
Running a fresh install of dwarf fortress with dfhack on macOS Catalina generates dozens of security warnings (Example: "libdfhack.1.0.0.dylib cannot be opened because the developer cannot be verified."), as each dylib file is checked for a developer signature. It is fiddly and time-consuming to allow each plugin via the mac Security settings and relaunch dfhack.

Removing the quarantine flag from all the downloaded files prevents these alerts. After copying the extracted dfhack files into the dwarf fortress installation directory, this can be done by running the following command (replacing `df_osx` with the appropriate directory name):

`find df_osx/ -print0 | xargs -0 xattr -d com.apple.quarantine`

It would of course be nice for these files to be signed so this workaround is not needed, but I'm not sure if that's on the horizon for this project. I'm happy to put up a PR to add this workaround to a readme or other documentation if that's desirable.

Thanks for all the hard work on this amazing project!

**Comment by lethosor** [comment]
Does this prevent DFHack from starting? Or do you just have to dismiss a bunch of warnings?
Does the `xattr` command require any sort of authentication, or is it something that the `dfhack` launcher script would run?
(I don't have Catalina to test on; I'd also be concerned about scanning through the entire DF folder on every launch, but maybe scanning `hack/plugins` and `hack/libs*` would be fast enough.)

**Comment by tommy** [comment]
The existing behavior on Catalina does prevent DFHack from starting initially. Specifically it requires: moving back and forth between DF and the Apple security settings to "Allow Anyway" every dylib and framework file, of which there are over a hundred. Each library generates two alerts (before and after using "Allow Anyway"), and DFHack must be restarted about 5 times (I'm guessing this relates to batches of libraries that are loaded independently).

That's a good idea about removing the quarantine flags in the startup script. The xattr tool does not require special permissions. I tested the following addition to the `dfhack` shell script, and was able to run DFHack while only needing to go to the Apple security settings once (to run the `dfhack` script itself), which I believe is the current behavior under Mojave.

```
find hack/lib* hack/plugins -print0 | xargs -0 xattr -d com.apple.quarantine
find libs -print0 | xargs -0 xattr -d com.apple.quarantine
xattr -d com.apple.quarantine dwarfort.exe
```

Of course, the files referenced in lines 2 and 3 are shipped with DF itself, so there may eventually be an upstream fix for those that DFHack could rely on.

**Comment by lethosor** [comment]
Well, that's nice and secure! It does make our job easier, though. I'll test it out / see if it breaks pre-Catalina, and add it for the next release.

**Comment by lethosor** [comment]
Hopefully f3d5a185ba7e1e857f24821d383278b1a5fc3ed7 does the trick; let me know if not.
