### ISSUE TITLE
labormanager should avoid sending dwarfs outside when it's raining

### ISSUE THREAD

**Issue by ab9rf** [DFHack/dfhack#1469]
Based on a conversation on the DF discord, it's been suggested to me that `labormanager` should try to avoid sending dwarfs outside when it's raining.

In addition, if we can figure out which personality facets and/or traits make a dwarf more or less susceptible to personality damage due to rain exposure, modulating the "go-outside" penalty by those facets/traits would be appropriate.

**Comment by PatrikLundell** [comment]
Before doing anything, I think there's a need to see if it's useful. If the time it takes to do anything outside is long enough to see multiple showers come and go it will just prevent dorfs from taking jobs that would bring them outside after the weather has cleared, while not preventing those sent outside from being rained upon after getting to the surface, it will only slow down the work rate.

**Comment by ab9rf** [comment]
stale
