### ISSUE TITLE
Embark-assistant should allow for searching for volcanos

### ISSUE THREAD

**Issue by ab9rf** [DFHack/dfhack#1471]
If possible, it would be nice if `embark-assistant` had an option for volcano (present/absent).

**Comment by clinodev** [comment]
It does already, doesn't it? 

Min Magma>Volcano

Admittedly I've never tried it, but the other Min Magma settings I've tried worked fine.

**Comment by ab9rf** [comment]
I totally missed that. Even after you pointed it out it still took me three passes down the list to see it.
