### ISSUE TITLE
autochop: autochop should not count logs that are underwater

### ISSUE THREAD

**Issue by ab9rf** [DFHack/dfhack#1473]
Autochop counts logs that cannot be collected because they are underwater and thus unreachable; autochop should not count for the purposes of its threshold controls logs that are underwater or otherwise unreachable.

It might be possible to use the `walkable` member of `map_block` for this purpose as this is usually zero for unreachable locations, but nonzero for reachable locations.

**Comment by HunterZ** [comment]
This would be extremely helpful. I've apparently got over 400 unreachable logs around my fortress, and my stockpiles are always empty.

Might be nice to only count stockpiled logs, except that could result in runaway chopping if lack of hauling is the problem?
