### ISSUE TITLE
digfort throws up error if number of lines is longer than number of squares along y axis

### ISSUE THREAD

**Issue by evanmoring** [DFHack/dfhack#1478]
If the number of lines in the .csv file is greater than the total number of squares along the y axis, digfort throws an error and doesn't designate anything. This causes problems if you are designating large areas across many z levels.

You can successfully designate large files if you comment out this code, but it probably causes other issues:

if x < 0 or y < 0 or x+max_x >= map.x_count or y+max_y >= map.y_count
    max_x = max_x + x + 1
    max_y = max_y + y + 1
    raise "Position would designate outside map limits. Selected limits are from (#{x+1}, #{y+1}) to (#{max_x},#{max_y})"

end

**Comment by lethosor** [comment]
Is this an issue? What are you expecting it to do instead?

**Comment by evanmoring** [comment]
Sorry, didn't make this clear. If your csv file designates 10 z levels, each with 10 y levels designated, digfort will throw the error if there are less than 100 units free on the y axis.

For example:

d,d,d 
d,d,d
d,d,d
#>
d,d,d
d,d,d
d,d,d

seems to trigger the error if you try to use it within 6 units of the lower wall. 

I can upload my save and csv file if you would like to test with them.

**Comment by lethosor** [comment]
Ah! Yes, that's a bug. I think https://github.com/DFHack/scripts/pull/95 fixed it, in fact - want to try with that? [Here's the raw script file](https://raw.githubusercontent.com/DFHack/scripts/master/digfort.rb).

**Comment by evanmoring** [comment]
That worked great, thanks for the help and sorry for wasting your time.

**Comment by lethosor** [comment]
No worries. We really should get these fixes out in a proper release soon.
