### ISSUE TITLE
getplants will mark plants for harvest that don't have usable growths

### ISSUE THREAD

**Issue by Rekov3D** [DFHack/dfhack#1479]
If you use getplants to designate shrubs for harvest, it will do so even if there is nothing currently there to harvest. This occurs when the only usable components of the plants are growths.

Steps to reproduce:
1: Embark on a site with bilberrys
2: getplants -s BILBERRY
3: The dwarves will go around 'harvesting' bilberries. The shrubs will be destroyed. No bilberry fruits are actually collected.

**Comment by lethosor** [comment]
I'm not entirely familiar with this, so to clarify - are the dwarves collecting growths (other than berries) or nothing at all? Does designating the bilberry bushes for gathering manually lead to the same result? If that's the case, I'm not sure if there's a way to tell in advance whether a plant will produce berries when harvested, but we can investigate.

**Comment by RekovPDX** [comment]
No. If you manually designate the bilberry bushes with d - p they aren't selected unless there is a fruit there to collect. Similarly if you put these plants in a gather zone, dwarves will not attempt to harvest them unless there's a fruit or whatever. 

From the wiki: 
> Edible or otherwise usable growths should have [STOCKPILE_PLANT_GROWTH] in their material definitions for proper stockpiling. This also lets them be collected from plant gathering and farming jobs. 

I don't really know if they are 'collecting' the leaf/flower growths to be honest. Nothing is produced out of it either way.

I'm roughly trying to repeat [what Patrik Lundell told me on the forum.](http://www.bay12forums.com/smf/index.php?topic=175283.0) His explanation might be more helpful.

**Comment by lethosor** [comment]
Aha, thanks for the forum link. So getplants is making designations that aren't even possible to make in vanilla, then. I'm not sure how complicated this is to address, but yeah, it's definitely a DFHack bug in that case.

**Comment by PatrikLundell** [comment]
I've thought a bit about the problem, and came up with a few complications that will have to be considered.
The Bilberry case is reasonably straightforward, as the basic plant can't be used for anything, and thus there's no vanilla reason to pick a Bilberry at that stage. However:
- If the "structure" part of the Bilberry plant actually is collected, it's ought to be possible to create custom reactions that could use it (like Papyrus doesn't have any usefulness flags associated with it [at least none have been identified], but has to be detected through its paper making reaction).
- The Strawberry trouble maker has an edible "structure" part, and so there is a reasonable reason to pick it before there are any berries on it, but most people would presumably want to skip the picking until the berries are available (starvation being an exception, I guess).
- I don't know if there's any (vanilla) shrub that has this behavior, but the Date Palm has both edible flower growths and edible fruit growths. As far as I've seen, it seems gathering of the flowers don't have the real world effect of blocking the later ability to pick the fruit (which is fortunate, as gathering zones have no controls that can be used to restrict the gathering), but I can't guarantee that this is a correct observation. If a shrub that sports both usable early time growths and usable late time growths you'd get into a tricky situation, however, as the picking of shrubs removes the shrub, and thus blocks the ability to get the late ripening growth.

It seems to me that the [STOCKPILE_PLANT_GROWTH] raw tag referenced above gets translated into the stockpile_growths and stockpile_growth_flags arrays in the raw structured inside DF. However, these arrays do not include the structural part of the plant, so the determination of whether to pick that part has to use other info.

**Comment by quietust** [comment]
Just located the code DF itself uses for checking if a plant is harvestable (and whether it will allow you to designate it), and it appears to use the following criteria:
* plant's defined BASIC_MAT is EDIBLE_RAW or EDIBLE_COOKD
* plant is flagged with THREAD, MILL, EXTRACT_VIAL, EXTRACT_BARREL, or STILL_VIAL
* plant's defined BASIC_MAT has at least one REACTION_PRODUCT or REACTION_CLASS
* at least one time-valid plant growth produces SEEDS items whose material is EDIBLE_RAW or EDIBLE_COOKED
* at least one time-valid plant growth produces PLANT_GROWTH objects whose material has flag 0x26 set (which used to be LEAF_MAT but appears to mean something else now)

**Comment by PatrikLundell** [comment]
I guess the best approach would be to apply the same rules DF uses and leave it up to the players to issue the command at the correct times if they want to get specific time limited parts (just as with the vanilla DF designations, it will lead to confusion for things like strawberries, but at least it's a standard confusion...).

**Comment by lethosor** [comment]
Aliases are not possible, but renaming it is easy. What isn't easy is ensuring that everything that used the old name is updated, but if the old name was wrong anyway, I'm fine with renaming it.

**Comment by PatrikLundell** [comment]
Well, just renaming the constant in the definition doesn't count as performing a renaming in my book: The task should involve locating and changing usages as well.

Something that bothers me with the implementation above is that it doesn't actually make use of the plant's growth state, which may or may not match how DF treats it, i.e. if a shrub is spawned, it assumes the appropriate time-of-year growths are present immediately as well. There's a "grow_counter" field in the individual plant, but I don't know if it is used for shrubs (it is for trees). If there is no actual dependency on the plant itself, it might be better to make the evaluation of whether it is ready for picking on the species level (there are a few hundred plants, but potentially thousands of shrubs on an embark).

**Comment by lethosor** [comment]
Looks like there are a couple occurrences in scripts: https://github.com/DFHack/scripts/search?utf8=%E2%9C%93&q=leaf_mat&type= (but I only see the definition in df-structures, and nothing in dfhack)

**Comment by quietust** [comment]
Your plant growth checks aren't quite right - the seed one shouldn't look at SEED_MAT or behavior.bits.has_seed, but should instead check the growth's item_type (and compare to SEEDS / PLANT_GROWTH) and then load the material specified by mat_type/mat_index (which might not even belong to that plant) to check the necessary flags.

It's probably best to iterate across the growths array _once_ (to avoid duplicating the time validity check), since that's what DF itself does.

**Comment by quietust** [comment]
Also, regarding LEAF_MAT, that's what it *used* to be called back in version 0.34.11 - Toady renamed it when he added plant growths in 0.40.

**Comment by PatrikLundell** [comment]
Thanks for the feedback, quietust.

I usually assume the need for a change of a name to be caused by DF changing the use, rather than the person originally naming it having made an error. That's why I try to use the term "obsolete" rather than "incorrect".

**Comment by PatrikLundell** [comment]
@quietust Does your ability to look at the DF code allow you to figure out where we might need to look for growths that can be picked/gathered? The plant raws provides the timing for when growths may be present, but after they're picked the plants they grew on still remain if the plants themselves (the structure part) are not useful (e.g. bitter melon), DF is clearly capable of displaying the fruit/nuts on trees, removing them from display as they're picked, and DF also refuses to designate already picked shrubs for picking, so the info is clearly there, somewhere.
I suspect the growths are stored in some unmapped structure, although it's obviously not possible to rule out a failure on my part to find something "hiding" in plain sight.

**Comment by quietust** [comment]
In version 0.47.04 on 64-bit Windows, the function for designating Shrub tiles for plant gathering is located at address 0x140DE87C0. My analysis above is based entirely on that function, but I omitted some details that I wasn't able to figure out at the time - specifically, how the game decides that growths are "time-valid".

The time validity is based on cur_year_tick plus/minus a *random* value (whose seed is based on the X and Y coordinates). I'm not exactly certain about the math involved, but that particular code is at 0x140DE89D1 if you want to try to analyze it in IDA or Ghidra.

There's another check I previously overlooked that involves records inside `world.world_data.object_data`, specifically the lists `unk_c0`/`unk_d0`/`unk_e0` (all int16, likely containing X/Y/Z coordinates) and `unk_f0`/`unk_100`/`unk_110` (all int32, with the 2nd being related to growth Density and the 3rd being a Year). These could very well be how it keeps track of which tiles have been harvested.

**Comment by PatrikLundell** [comment]
Thanks, quietust. I'll try to see if I can get anything useful out of the structures you've pointed out. object_data is currently a dark corner of the structures, so anything hiding there would be hard to find without this kind of hint.

I'll most likely not delve into code analysis, though, but it's definitely useful to know there is randomness involved (which is visible in game play, as you can see that trees in particular change different tiles at different times over a comparatively short period.

**Comment by quietust** [comment]
I've done a bit more digging into the code for the "random" time variance on each tile, and it seems to be based on the following formula: `variance = ((435522653 - (((Y_coord + 3) * X_coord + 5) * ((Y_coord + 7) * Y_coord * 400181475 + 289700012))) & 0x3FFFFFFF) % 2000`. As far as I can tell, the X and Y coordinates are relative to your entire embark, **not** the map_block in which the plants are located.

No, I don't know where any of those big numbers come from, but Ghidra managed to come up with the exact same equation so I'm pretty sure it's correct. That variance gets added to `cur_year_tick` (mod 403200), and the resulting timestamp is compared to the growth timing values to see if they're valid.
