### ISSUE TITLE
Look into custom linter configs (CodeFactor)

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#1483]
The current CodeFactor settings don't always seem to agree with this project: https://github.com/DFHack/dfhack/pull/1468#issuecomment-557340552 https://github.com/DFHack/dfhack/pull/1481#issuecomment-575204072

I logged into the dashboard and it looks like we can override the linter configs for various languages:
![image](https://user-images.githubusercontent.com/3719547/72660192-3c6fe600-3998-11ea-9443-f5d7a9d59e3a.png)

![image](https://user-images.githubusercontent.com/3719547/72660194-5dd0d200-3998-11ea-92b4-45cba6bdd696.png)

C++ links [here](https://github.com/google/styleguide/blob/6271f3f473ceb3a7fef99388a3040903b1a145f1/cpplint/cpplint.py#L156-L197), for reference.

We could probably adjust this to produce fewer warnings that aren't relevant to us.

**Comment by BenLubar** [comment]
I've told it to ignore complex methods and whitespace (it seems to have misdetected every single file as having multiple newlines at the end)

**Comment by lethosor** [comment]
How did you do that? Is it some setting on CodeFactor's end?

**Comment by BenLubar** [comment]
Confusingly, it's done from the error list page with an unlabeled crossed out eye icon
