### ISSUE TITLE
dfhack Segfaults with DF 0.47.01

### ISSUE THREAD

**Issue by jasonkena** [DFHack/dfhack#1487]
`./dfhack: line 21: 86077 Segmentation fault: 11  DYLD_INSERT_LIBRARIES=./hack/libdfhack.dylib ./dwarfort.exe "$@"` shows up regardless of whether 32 or 64 bit of the DFHack 0.44.12-r3 release, or when DFHack is compiled on OSX.

**Comment by warmist** [comment]
Maybe related to #949 which now i see is originally 2016 issue with a new comment :?

**Comment by lethosor** [comment]
Yeah, this isn't expected to work, but it also isn't supposed to segfault

**Comment by BenLubar** [comment]
Ran into the segfault by accidentally running Dwarf Fortress 0.44.12 with latest DFHack
