### ISSUE TITLE
dfhack crashes on win64 if I add DF 0.47.01

### ISSUE THREAD

**Issue by LordBSD** [DFHack/dfhack#1488]
Hi, title, DF starts fine but I want to use DFhack and the window closes if I add DFhack and try to run it. Event manager reports there was some issue with SDL.dll hope this helps. Good luck and thanks for your work.

**Comment by lethosor** [comment]
This is expected. DFHack doesn't work with 0.47 yet. It shouldn't crash, but let's keep discussion on that to #1487 if that's happening.
