### ISSUE TITLE
Crash on attempting to access nemesis flags, build #200210002 Win64

### ISSUE THREAD

**Issue by AtomicChicken** [DFHack/dfhack#1492]
Testing a couple of my scripts in 0.47.02 with build #200210002 for Win64. Running any of the following resulted in an instant crash:

bodyswap.lua
linger.lua
unretire-anyone.lua

Commenting out all references to nemesis.flags contents (`nemesis_record.flags.RETIRED_ADVENTURER` etc) prevents this from occurring, indicating that the problem appears to lie here.

**Comment by PatrikLundell** [comment]
Yes, the flags pointer seems to be misaligned. df-structures work underway to correct it.

**Comment by AtomicChicken** [comment]
Fixed following DFHack/df-structures/pull/347.
