### ISSUE TITLE
Exportlegends sites/all

### ISSUE THREAD

**Issue by ralpha** [DFHack/dfhack#1494]
Then using the `exportlegends all` command it fails while doing the export.
### Error message
```
~/df_linux/hack/scripts/exportlegends.lua:813: Cannot write field viewscreen_export_graphical_mapst.sel_idx: not found.
stack traceback:
	[C]: in metamethod '__newindex'
	~/df_linux/hack/scripts/exportlegends.lua:813: in function <~/df_linux/hack/scripts/exportlegends.lua:802>
```

### Code inspection
Opening the `exportlegends.lua` file it files in the function export_detailed_maps() (line 801-821):
```
function export_detailed_maps()
    script.start(function()
        for i = 1, #MAPS do
            local vs = dfhack.gui.getViewscreenByType(df.viewscreen_export_graphical_mapst, 0)
            if not vs then
                local legends_vs = dfhack.gui.getViewscreenByType(df.viewscreen_legendsst, 0)
                    or qerror("Could not find legends screen")
                gui.simulateInput(legends_vs, 'LEGENDS_EXPORT_DETAILED_MAP')
            end

            vs = dfhack.gui.getViewscreenByType(df.viewscreen_export_graphical_mapst, 0)
                or qerror("Could not find map export screen")
            -- FAIL ON NEXT LINE --
            vs.sel_idx = i - 1
            -- FAIL ON LINE ABOVE --
            print('    Exporting map: ' .. MAPS[i])
            gui.simulateInput(vs, 'SELECT')
            while dfhack.gui.getCurViewscreen() == vs do
                script.sleep(10, 'frames')
            end
        end
    end)
end
```
### Quick fix
I commented out line 813. So the old code was:
```
            vs = dfhack.gui.getViewscreenByType(df.viewscreen_export_graphical_mapst, 0)
                or qerror("Could not find map export screen")
            vs.sel_idx = i - 1
            print('    Exporting map: ' .. MAPS[i])
```
New code:

```
            vs = dfhack.gui.getViewscreenByType(df.viewscreen_export_graphical_mapst, 0)
                or qerror("Could not find map export screen")
            -- vs.sel_idx = i - 1
            print('    Exporting map: ' .. MAPS[i])
```
This fixed the problem for me and was able to export the maps after this.
This might have other implications but not familiar enough with this code to tell.
(Note: Numbering of export files looks fine, not problems found)

**Comment by lethosor** [comment]
What DFHack version and OS are you using?

**Comment by ralpha** [comment]
OS: Linux mint 19.1 (Linux - 4.15.0-58-generic - x86_64)
DFHack version: Current dev: commit e9a295c788df1b32dff350951759ec82decdb0d0
CC (compiler): cc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Build it using compile instructions on: https://dfhack.readthedocs.io/en/latest/docs/Compile.html
DF version: 0.47.02

So latest DFHack, lastest DF.
Both clean downloads (no mods or graphics or anything else)

**Comment by PatrikLundell** [comment]
If I understand it correctly, the problem line selects which map to export, i.e. line in the list, and does a human->C index tranlation (1-based -> 0-based). Your quick fix ought to result in all maps actually being the Standard biome+site map selection (as it's the default).

Comparing with 0.44.12, it seems the field sel_idx has gone missing and been replaced by anon_1 (probably by mistake). Changing which line is selected in the list changes the value of this field according. Thus, it seems to firstly be a df-structures issue (to clarify: it's not a matter of casting blame, but to forward a problem to its root).
