### ISSUE TITLE
Missing symbol for MapExtras::BiomeInfo::MAX_LAYERS

### ISSUE THREAD

**Issue by cvuchener** [DFHack/dfhack#1495]
Bad commit: 123de7fdf795d7962a0fd2ca347bca013e67080f

`constexpr` does not remove the need for a definition, the variable exists both at compile and run time. You need `inline constexpr` for that, but it is a C++17 feature (so I guess not acceptable here).

Using linux32 debug build:

    ./libs/Dwarf_Fortress: symbol lookup error: ./hack/libdfhack-debug.so: undefined symbol: _ZN9MapExtras9BiomeInfo10MAX_LAYERSE

Why was the definition inside a ifdef block? Is the definition causing issues on some setup?

**Comment by lethosor** [comment]
The ifdef is probably from when we were using Visual Studio 2010 on Windows. Was this a clean build? I don't know why nobody has encountered this before - BuildMaster builds seem to be working fine.

**Comment by cvuchener** [comment]
BuildMaster does release builds, right? I only had this issue with a 32 bits debug build. 64 bits debug or 32 bits release worked.

I am not sure what you call "clean", this was on my desktop computer with fedora 31 (gcc 9.2.1), not a vm.

**Comment by lethosor** [comment]
Oh, I guess that could be it, but I still don't really have a good explanation. Maybe MAX_LAYERS is only getting inlined on release builds?
If you're able to fix this properly, BuildMaster should tell you if release builds still build (although if this issue only comes up at runtime, that might not be enough).

**Comment by cvuchener** [comment]
> Oh, I guess that could be it, but I still don't really have a good explanation. Maybe MAX_LAYERS is only getting inlined on release builds?

I looked at the usage of MAX_LAYERS, and tried that:
```diff
--- a/library/modules/MapCache.cpp
+++ b/library/modules/MapCache.cpp
@@ -1231,7 +1231,7 @@ MapExtras::MapCache::MapCache()
 
         memset(biomes[i].layer_stone, -1, sizeof(biomes[i].layer_stone));
 
-        for (size_t j = 0; j < std::min<size_t>(BiomeInfo::MAX_LAYERS,layer_mats[i].size()); j++)
+        for (size_t j = 0; j < std::min<size_t>(size_t(BiomeInfo::MAX_LAYERS),layer_mats[i].size()); j++)
         {
             biomes[i].layer_stone[j] = layer_mats[i][j];

```

And it fixed the issue. My understanding, which can be wrong, is that std::min takes a lvalue reference so MAX_LAYERS need to be defined. If I cast MAX_LAYERS, the casted rvalue is created at compile time, and MAX_LAYERS no longer needs to be a defined.

In some setup, std::min may be inlined and optimized such that a lvalue is no longer needed.

Unless you want to be very careful to never use MAX_LAYERS as an lvalue, I think it is best to define it.
