### ISSUE TITLE
mac release fails with "dwarfort.exe: No such file or directory"

### ISSUE THREAD

**Issue by ror6ax** [DFHack/dfhack#1497]
```
./dfhack
./dfhack: line 21: ./dwarfort.exe: No such file or directory
```
Is this a packaging error or am I missing something?

**Comment by lethosor** [comment]
You have to install DFHack into an existing copy of DF (although on macOS and Linux, you can also install DF into an existing copy of DFHack); we don't redistribute DF with our builds. See https://docs.dfhack.org/en/stable/docs/Introduction.html#installing-dfhack for details.
