### ISSUE TITLE
segfault

### ISSUE THREAD

**Issue by LordBSD** [DFHack/dfhack#1500]
`mike@core ~/dwarf $ ./dfhack
Loading bindings from data/init/interface.txt
Resetting textures
./dfhack: line 83: 410784 Segmentation fault      (core dumped) setarch "$setarch_arch" -R env LD_PRELOAD="$PRELOAD_LIB" ./libs/Dwarf_Fortress "$@"

mike@core ~/dwarf $ 
`
Hi. This is what I am getting on my gentoo system. If I just run ./df the game runs fine but no dfhack obviously. Thanks for any help.

**Comment by lethosor** [comment]
We need more information to help with this - what DF and DFHack version are you using (including the build number if it's a nightly build)? 32-bit or 64-bit? (Looks like Linux from the output, but that's all I can tell.)

**Comment by LordBSD** [comment]
Yes of course and thanks for your quick reply. 
Its dwarf fortress 0.47.03 64bit  and DFHack 0.44.12-r3 64bit

**Comment by lethosor** [comment]
Interesting, that's been working for me. Is there anything in stderr.log? What distro are you using? You have the 64-bit version of DFHack too, right?

**Comment by LordBSD** [comment]
Hi yes 64 bit everything ill check the log now and this is gentoo linux multilib.

**Comment by LordBSD** [comment]
I had the wrong version of dfhack installed. This was my error. I am so sorry and thank you for your help.

**Comment by lethosor** [comment]
Ah. I think we fixed at least one case where DFHack would segfault when it didn't recognize the DF version, as opposed to giving the intended error message, but that fix won't be in older DFHack versions, of course.
