### ISSUE TITLE
immediate crash of dfhack, line 21: 15435 Segmentation fault

### ISSUE THREAD

**Issue by zntaylgit** [DFHack/dfhack#1502]
I have downloaded the correct version of dfhack for my 64bit mac. I am running catalina, I unzipped the package, took the contents of dhfack folder and copied them into the df_osx folder (this has worked for me previously). Clicking on the dfhack executable in the hopes of running legends mode gives me an immediate crash (4 threads) and this message in my terminal:

df_osx/dfhack: line 21: 15435 Segmentation fault: 11  DYLD_INSERT_LIBRARIES=./hack/libdfhack.dylib ./dwarfort.exe "$@"

Because I am running Catalina which generates an ungodly number of security warnings I performed the following fix:

find df_osx/ -print0 | xargs -0 xattr -d com.apple.quarantine

Suggested here: https://github.com/DFHack/dfhack/issues/1465

I am not a Legendary Mac User, Im just  a humble urist. Can anyone spot the problem and suggest what I need to do to fix this?

**Comment by lethosor** [comment]
What DFHack and DF version are you using?

**Comment by zntaylgit** [comment]
Im using the newest df release: 
       DWARF FORTRESS CLASSIC 0.47.03 (February 16, 2020)
and dfhack:
      dfhack-0.44.12-r3-OSX-64-gcc-7.4.0

**Comment by lethosor** [comment]
DFHack can't ever support a newer DF version than what's specified in its name (in this case, DFHack for 0.44.12 can't support anything newer than that, like 0.47.03). See #1500 and http://docs.dfhack.org/en/stable/docs/Introduction.html#installing-dfhack for more details.
