### ISSUE TITLE
dwarfvet too verbose?

### ISSUE THREAD

**Issue by pierredavidbelanger** [DFHack/dfhack#1504]
A plugin seems to be too verbose, I see this line a lot in the dfhack console:

```
Clearing all animal hospitals
```

I guess this line can be removed:
https://github.com/DFHack/dfhack/blob/546178bc56e6d70ae8a03d0801b1c0ab60ba39fe/plugins/dwarfvet.cpp#L417

**Comment by lethosor** [comment]
Yup, it really should only print that if the plugin is enabled (if at all).
