### ISSUE TITLE
No way to check all historical events related to a historical figure?

### ISSUE THREAD

**Issue by IndigoFenix** [DFHack/dfhack#1509]
I've been searching for ages but can't seem to find the place in DFHack's data structure that records the historical events that relate to a given histfig - essentially the events as they show up on their Legends screen.  (I'm trying to write a script that correlates personalities and values to involvement with particular events by taking a global census, in order to figure out how personalities and values impact worldgen). 
Is there any way of doing this or has it not been mapped yet?

**Comment by BenLubar** [comment]
There's a vmethod on history_event that can tell you if it's related. I'm pretty sure the game just goes through all the events that have ever happened in the world when generating that textviewer.

**Comment by IndigoFenix** [comment]
Really?
...That's a lot of events to go through every time a screen is opened...
What's the method, at any rate?

**Comment by BenLubar** [comment]
`getRelatedHistfigIDs` and `isRelatedToHistfigID` look like they're both useful for this

**Comment by lethosor** [comment]
I think that's probably the answer here; legends does take some time in larger worlds to scan events before it's ready to interact with.
