### ISSUE TITLE
Rebind `l` key bind for managing labors with manipulator

### ISSUE THREAD

**Issue by sooheon** [DFHack/dfhack#1510]
[manipulator](https://dfhack.readthedocs.io/en/stable/docs/Plugins.html#manipulator) is accessed with `l` from the units list. I've rebound all the navigation in DF with vi-keys, and this is the last remaining conflict. 

Where can this be rebound, and is it configurable in dfhack.init?

**Comment by lethosor** [comment]
It's DF's CUSTOM_L key. You can change that in DF's keybindings menu, but that will change all in-game DFHack keys that use that binding (as well as reactions, and maybe other things in DF). The specific key manipulator uses is unfortunately not possible to change at this time, but we've thought of making keys like that customizable.

**Comment by sooheon** [comment]
Thanks, that's good enough for now.

**Comment by sooheon** [comment]
For posterity: it was not the CUSTOM_L key, but the UNITVIEW_PRF_PROF key (used by df when you `v`iew a unit's. `p`refs.

**Comment by lethosor** [comment]
Whoops, forgot manipulator used that - most in-game DFHack shortcuts use the CUSTOM_ group of keys, but in this case there's an existing DF key that fits.

**Comment by sooheon** [comment]
Can you point me to where the l: Load/Save Settings for stockpiles is defined? Doesn't seem to be CUSTOM_L.

**Comment by lethosor** [comment]
It is: https://github.com/DFHack/dfhack/blob/82f082d7cbd6b823ab4c54d0dfbbf578f7fb1c4a/plugins/stockpiles/stockpiles.cpp#L386-L390

**Comment by sooheon** [comment]
Ah cool thanks. FYI I rebound it do Alt-l and it still shows up as `l` in the interface.

**Comment by lethosor** [comment]
Yeah, that's a bug: https://github.com/DFHack/dfhack/blob/82f082d7cbd6b823ab4c54d0dfbbf578f7fb1c4a/plugins/stockpiles/stockpiles.cpp#L424
It's hardcoding the "l" string - there's another overload of OutputHotkeyString that takes an interface_key instead, which would account for changing bindings.
