### ISSUE TITLE
modtools/create-unit crash

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#1519]
Reported on Reddit: https://www.reddit.com/r/dwarffortress/comments/fh8l10/comment/fkb5wom

**Comment by lethosor** [comment]
More info: 
build 200309001, win64: https://buildmaster.lubar.me/applications/3/builds/build?buildId=7282
diffs:
https://github.com/DFHack/dfhack/compare/DFHack:b984111...DFHack:3948608
https://github.com/DFHack/df-structures/compare/e2fafc...8ec203
https://github.com/DFHack/scripts/compare/a1ae6a...54cdfb (irrelevant)

**Comment by AtomicChicken** [comment]
Looking into this on Win64 build 200316004 in a freshly installed game with arena mode open, the following problem is immediately apparent:

```
[lua]# printall(df.global.world.arena_spawn)
race                     = <vector<int16_t>[1643313815]: 00007FF79B5ACED8>
caste                    = <vector<int16_t>[18446744073709192577]: 00007FF79B5ACEF0>
type                     = -1009051346
filter                   =
item_types               = <vector<world.T_arena_spawn.T_item_types*>[]: 00007FF79B5ACF30>
unk_vec1                 = <vector<void*>[0]: 00007FF79B5AD938>
unk_vec2                 = <vector<void*>[0]: 00007FF79B5AD950>
unk_vec3                 = <vector<void*>[0]: 00007FF79B5AD968>
equipment                = <world.T_arena_spawn.T_equipment: 00007FF79B5AD980>
side                     = 0
interaction              = 0
tame                     = 0
interactions             = <vector<interaction_effect*>[1484564269]: 00007FF79B5ADA38>
creature_cnt             = <vector<int32_t>[18446744073704830398]: 00007FF79B5ADA50>
unk_int1                 = -1027269448
```

**Comment by lethosor** [comment]
Shoot, that's not good. Any idea where the alignment issue is?

**Comment by AtomicChicken** [comment]
No idea, but `df.global.world.features` is also messed up, which probably explains #1516.

**Comment by lethosor** [comment]
Just realized your build was from March 16 - would you mind double-checking in a newer build and see if this still occurs on Win64? Thanks

**Comment by AtomicChicken** [comment]
The alignment issue has been resolved as of build 200325001.
`features magma` is working well, and preliminary tests with `modtools/create-unit` have not yielded crashes so far.

**Comment by thurin** [comment]
I checked this on current develop (4fde096) and it is working for me now.

**Comment by lethosor** [comment]
Nice! Going by AtomicChicken's build numbers, [this](https://github.com/DFHack/df-structures/compare/2f93b7188d37be889bb5dc83a758dd13b72d6353...500668a7490bae370d3b8ea040d53232cc342a46) is the XML diff, and I suspect https://github.com/DFHack/df-structures/commit/4bfdb764a0235177bae2d0cfedf0533d77924c6b fixed it. (The commit was from before March 16, but wasn't merged in until after.)
