### ISSUE TITLE
gui/advfort breaking due to renamed unit_action fields

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#1520]
Reported on Reddit: https://www.reddit.com/r/dwarffortress/comments/fflu1q/biweekly_df_questions_thread/fkcbzcg/?context=3
```
Cannot write field unit_action.T_data.job: not found.
stack traceback:
[C]: in ?
[C]: in ?
[C]: in ?
[C]: in method 'assign'
C:\DwarfFortress\df_47_04_win/hack/scripts/gui/advfort.lua:259: in global 'add_action'
C:\DwarfFortress\df_47_04_win/hack/scripts/gui/advfort.lua:286: in global 'addJobAction'
C:\DwarfFortress\df_47_04_win/hack/scripts/gui/advfort.lua:389: in function <C:\DwarfFortress\df_47_04_win/hack/scripts/gui/advfort.lua:361>
Cannot write field unit_action.T_data.job: not found.
stack traceback:
[C]: in ?
[C]: in ?
[C]: in ?
[C]: in method 'assign'
C:\DwarfFortress\df_47_04_win/hack/scripts/gui/advfort.lua:259: in global 'add_action'
C:\DwarfFortress\df_47_04_win/hack/scripts/gui/advfort.lua:286: in global 'addJobAction'
C:\DwarfFortress\df_47_04_win/hack/scripts/gui/advfort.lua:1035: in upvalue 'ContinueJob'
C:\DwarfFortress\df_47_04_win/hack/scripts/gui/advfort.lua:1831: in function <C:\DwarfFortress\df_47_04_win/hack/scripts/gui/advfort.lua:1797>
[C]: in ?

```

Build: b9841110, 64-bit

`job` was renamed to `Job`, breaking here: https://github.com/DFHack/scripts/blob/95a32a0f1709e17afd927f57675b81effbc42912/gui/advfort.lua#L283

Discussed on IRC - may be worth renaming these fields back to lowercase to minimize breakage in other scripts (and third-party tools)

**Comment by warmist** [comment]
fix: https://github.com/DFHack/scripts/pull/130

**Comment by warmist** [comment]
Also there is issue with this commit: https://github.com/DFHack/scripts/commit/a1ae6a095b626c2667519176a28a40d5214e6fb9

Because of how local/vs global functions work in lua it broke bunch of stuff very subtly.

**Comment by lethosor** [comment]
BenLubar added support for tagged unions using different names (i.e. capitalization in this case) for union items and the corresponding enum. I think that's probably the way to go to fix this (structures-side).
