### ISSUE TITLE
Labor Manager: Respect Custom Labors

### ISSUE THREAD

**Issue by missionz3r0** [DFHack/dfhack#1522]
Possibly related to

#1469 #1378 #1105 and #1102

I think it would be amazing if Labor Manager would respect custom labors in a fashion.

What I mean by this, is I would like it if I could tell Labor Manager that certain dwarves were off limits so that it would not assign jobs or re-arrange their jobs. So certain highly skilled dwarves can be kept right where I want them.

And on the flip side, I think the opposite would be beneficial as well. Set a certain custom profession to be the only profession that labor manager will work with.

And I believe this functionality could settle in nicely to allow the tool to play nice with Dwarf Therapist, which allows a fine degree of control of dwarf labors. However the downside of Dwarf Therapist is it requires a lot of micro-management at times.

If this this feature were added to Labor Manager, this would allow a person to use Dwarf Therapist to only handle exactly what they want while letting Labor Manager deal with every other labor.

This could honestly be expanded a bit more to include part of auto hauler in it as well. Where Labor Manager will ignore the dwarf accept when idle, where it will only provide them with hauling jobs that need doing.

I'm considering taking a stab at either adding this feature to Labor Manager, or making a new plugin that pulls from Labor Manager with some adjustments. But would like opinions from those who have worked on the project longer before diving in.

**Comment by lethosor** [comment]
Sounds like what #1400 intends to address to me, so I'd take a look at that if you're interested (@ab9rf knows far more about this than I do, though).

**Comment by ab9rf** [comment]
You can already exclude a specific dwarf from labormanager's assignment algorithm by assigning that dwarf to a burrows.

#1400 addresses this issue pretty much directly. @lethosor has an unresolved blocker on that pull request that needs to be addressed. I personally don't like the approach in #1400 that much but I don't have a clearly better idea at the moment, so I'm OK with it going forward provided that the issues that @lethosor identified are dealt with.

I do ask that you think carefully before you fork labormanager. We already have three labor managing plug-ins, all of which share a lot of common code and all of which are mutually incompatible. A fork would make that _four_ such plugins, and would add that much more maintenance headache whenever Toady changes the way the core game handles labors.

**Comment by missionz3r0** [comment]
While a burrow does work, it's also limiting and a clunky work around to making a dwarf be ignored by the manager.

Hrm, #1400 would solve it. But I feel like using a user defined role rather than alchemy as the marker. I'll hop over to that pull request for the discussion rather than extending this one further.
