### ISSUE TITLE
DFHack 0.47.03-beta1 Issues

### ISSUE THREAD

**Issue by rebrab404** [DFHack/dfhack#1523]
So, it says to leave any issues I have here. Hunters aren't taking their kills back to be butchered. They just stand there forever and I keep getting a message saying they can't find a path back. Also, lots of lag and almost crashing.

**Comment by lethosor** [comment]
Have you tried disabling DFHack temporarily to see if the issues persist in the same save?
On Windows, you can do this by performing the DLL swap under "uninstalling" here: https://docs.dfhack.org/en/stable/docs/Introduction.html#installing-dfhack

**Comment by rebrab404** [comment]
After turning off DFHack in the menu I'm not having the almost crashing/not responding issue as much anymore, but I just got another message claiming my hunter was canceling hauling a kill because he couldn't find a path.

**Comment by lethosor** [comment]
Are your hunters taking paths over bridges or through a river or something like that?
I'm not sure what would be causing lag, but you could try disabling plugins (`unload -all` is a way to force all of them off, except TWBT if you're using that).

**Comment by lethosor** [comment]
I'm pretty sure these issues are unrelated to DFHack (particularly the hunting-related issues, unless you're specifically doing something hunting-related with DFHack), but feel free to reopen this if it occurs in 0.47.04 or newer
