### ISSUE TITLE
Crash after trying to launch Stone Sense

### ISSUE THREAD

**Issue by SzybkiMotorek** [DFHack/dfhack#1524]
After starting the game, when type ssense in the console to launch it, both windows disappears after short loading. It happens in all versions of DF and DFhack.It is very frustrating, I spent half of a day trying to figure out why it is not working :(

Windows 10 64bit administrator permissions

**Comment by lethosor** [comment]
Which versions of DFHack have you tried? I suspect this may be the same as https://github.com/DFHack/stonesense/issues/68

**Comment by SzybkiMotorek** [comment]
on both df and dfhack 0.47.03 verisions and 0.44.12 also the same versions. I see this issue is probably the same as you mentioned. Both windows just disappear, no communicates, nothing

**Comment by lethosor** [comment]
Going to move this to the thread linked above.
