### ISSUE TITLE
Cannot go back to previous screen after editing unit personality with gui/gm-unit

### ISSUE THREAD

**Issue by marti404** [DFHack/dfhack#1525]
DFHack build: 0.47.04-alpha0-85-g65a7db44
on Win7 64

after editing a unit personality, pressing "Esc" to go back doesn't do anything. The dfHack console prints the following error:

`Invoking: gui/gm-unit
UNKNOWN CLASS 'dfhack_lua_viewscreen@DFHack': vtable = 0x7fedb035e68
C:\DWARF FORTRESS\DF4704/hack/scripts/modtools/set-need.lua:169: Cannot call field vector<unit_personality.T_needs*>.erase(): invalid index.
stack traceback:
	[C]: in method 'erase'
	C:\DWARF FORTRESS\DF4704/hack/scripts/modtools/set-need.lua:169: in global 'removeNeed'
	C:\DWARF FORTRESS\DF4704/hack/scripts/modtools/set-need.lua:157: in global 'addNeed'
	C:\DWARF FORTRESS\DF4704/hack/scripts/modtools/set-need.lua:392: in field 'rebuildNeeds'
	C:\DWARF FORTRESS\DF4704/hack/scripts/gui/gm-unit.lua:1399: in function <C:\DWARF FORTRESS\DF4704/hack/scripts/gui/gm-unit.lua:1398>
	[C]: in field 'on_activate'
	C:\DWARF FORTRESS\DF4704\hack\lua\gui\widgets.lua:334: in function 'gui.widgets.check_text_keys'
	(...tail calls...)
	C:\DWARF FORTRESS\DF4704\hack\lua\gui.lua:484: in function <C:\DWARF FORTRESS\DF4704\hack\lua\gui.lua:479>
	(...tail calls...)
	[C]: in ?`

**Comment by lethosor** [comment]
Thanks for the report! `devel/pop-screen` should get you out of a stuck screen (just don't run it too many times in a row or it'll quit DF)

**Comment by lethosor** [comment]
In hack/scripts/modtools/set-need.lua, can you try replacing all 3 occurrences of `needInstance == false` with `not needInstance`?
