### ISSUE TITLE
translation module translates some names as empty strings

### ISSUE THREAD

**Issue by BenLubar** [DFHack/dfhack#1528]
Seen for some deities, only `words[2]` was set to a nonnegative value. DFHack renders this as an empty string. Not sure what the game does, but it definitely doesn't render it as empty (or if it does, that's a second bug.)

**Comment by PatrikLundell** [comment]
My first approach would be to find the hist fig in the exported Legends XML, as you've got the id in that info (and my guess would be that it would be called whatever that second word is/translates to, but a check ought to show that).
