### ISSUE TITLE
Crash on Save

### ISSUE THREAD

**Issue by TwistedBlizzard** [DFHack/dfhack#1529]
The game occasionally crashes when it tries to do a seasonal save with DFHack 0.47.04-alpha0-109-gffe73028. I'm on macOS Mojave 10.14.6. The only thing I'd used DFHack for since loading the game previously is 'revflood' as the 'unreveal' command wasn't working after saving and loading with the map revealed.

When the crash happened, macOS produced a crash report which I've included.
[DFHackBugReport.txt](https://github.com/DFHack/dfhack/files/4411307/DFHackBugReport.txt)

**Comment by lethosor** [comment]
For our reference: it's a null pointer dereference, and here's the relevant backtrace:
```
Thread 1 Crashed:
0   dwarfort.exe                        0x0000000100d900e0 0x100000000 + 14221536
1   dwarfort.exe                        0x00000001006f89c2 0x100000000 + 7309762
2   dwarfort.exe                        0x0000000100e75be2 0x100000000 + 15162338
3   dwarfort.exe                        0x0000000100f2f286 0x100000000 + 15921798
4   dwarfort.exe                        0x0000000100718278 0x100000000 + 7438968
5   ???                                 0x00000001032f4cd0 vtable for std::basic_fstream<char, std::char_traits<char> > + 24
```

I *suspect* this is an issue in DF's serialization code (trying to write a null C string to a file, maybe?). Have you noticed the problem in other saves, or in other builds of DFHack?
If it's specific to just this save, uploading it to DFFD might help.

**Comment by lethosor** [comment]
@TwistedBlizzard have you been able to reproduce this? If so, does it reproduce in 0.47.04-beta1?

**Comment by TwistedBlizzard** [comment]
I'm still using the build I mentioned in my first post. I haven't come across the issue since, either with the original save or a new one (about 24 hours of total gameplay). I'll update to beta1 and keep an eye out!

**Comment by lethosor** [comment]
Sounds good. If you do end up getting to a state where it's reliably reproducible, I'd still recommend running without DFHack to see if it still crashes.

**Comment by lethosor** [comment]
I'm going to close this as I suspect it's a DF issue, but feel free to reopen if it reproduces and we can take a look at another crash report
