### ISSUE TITLE
exportlegends: questionable export of raw tokens

### ISSUE THREAD

**Issue by PatrikLundell** [DFHack/dfhack#1534]
History event exports of hf_does_interactionst and hf_learns_secretst export interaction raw strings, token and all, and does so using hard coded indices.

1. Does DF use a canonical order of tokens internally? If not, any user generated raws may result in the wrong token being exported.
2. Just dumping strings is quite ugly. If the raw strings are used, they ought to at least be stripped down to the contents.

For the hf_learns_secret case, it looks like the applicable string is available in in a directly usable form as
 ´´´
interactions[v].sources[0].name
´´´
although that relies on the assumption that there is a single source (or at least that the description is in the first one).

For the hf_does_interaction case, it looks like there's a corresponding approach would be
´´´
interactions[v].sources[0].hist_string_1 + interactions[v].sources[0].hist_string_2
´´´
resulting in " cursed to assume the form of a gila monster-like monster every full moon" (with a leading blank).

The reason I don't just make these changes and a PR is that I'm unsure if it would be that much safer than the current implementation, as it relies on the "sources" element to be of an appropriate derived type. Someone with a bit more knowledge of interactions might be able to provide advice.

It would e.g. be possible to check for the presence of a source element and that it's of the expected derived type and output an error message (but still provide a functioning XML file) if it's not. If that is done, it's still required to know the source derived types applicable to each case. Is it only _deityst for the hf_does_interaction case and _secretst and _experimentst for the hf_does_interaction case, and does it make sense to have more than one element in sources (and, if so, can they be of the same type, or should there be a search for the appropriate one[s])?

Edit: finding _experimentst, it's apparent that there can be 2 sources elements, although the first one is experimentst in the case seen (the second one being _attackst).

Edit2: And there is a case of the current approach failing with
´´´
<interaction_action>[IS_HIST_STRING_2:, passing on the sloth monster curse]</interaction_action>
<interaction_string>[I_TARGET:A:CREATURE]</interaction_string>
´´´
for interaction DEITY_CURSE_WEREBEAST_10_BITE, as the desired strings are 2 and 3 in that case.
using the single sources _attackst element's hist_string_1+2 would result in " bit, passing on the sloth monster curse"

Vampire curse would work, but spreading it uses the _ingestionst source derived type.

**Comment by lethosor** [comment]
I'm guessing backticks are hard to get to (or missing?) on your keyboard - you're using ´, but ` is what you want for code formatting. I'm not familiar with Scandinavian keyboard layouts, but from looking around, typing backticks seems like it can be system-specific. Still readable IMO, and thanks for tracking this down and fixing it!

**Comment by PatrikLundell** [comment]
There is a backtick on the keyboard which works like diacritical decorations, i.e. they're not displayed until the character to be decorated is pressed (like this "è"). For these code indicators I typically press the key 6 times, resulting in 3 pairs, and then split it in the middle to insert the code. I never have any other use for the key, though. Don't know why I used the wrong tick this time.
