### ISSUE TITLE
Scripts doc-build GitHub action is generating nested zips

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#1536]
Downloading docs.zip under "Artifacts" at https://github.com/DFHack/scripts/runs/559867231 gives a docs.zip file containing *another* docs.zip file. We're probably performing an extra unneeded zip step somewhere, since both files have the name we want.

**Comment by BenLubar** [comment]
if it's anything like BuildMaster, artifacts *are* zips, so we shouldn't be generating a zip at all

**Comment by lethosor** [comment]
Forgot I fixed this in https://github.com/DFHack/scripts/commit/8618cd0b0a17935fe07f329b249726cda61f5bdf
