### ISSUE TITLE
Autogems not working with linked stockpiles with bins

### ISSUE THREAD

**Issue by progger** [DFHack/dfhack#1546]
If jeweler's workshop linked to stockpile and rough gems in bins, jobs not created.
Issue in iterate stockpile items:
https://github.com/DFHack/dfhack/blob/0b926e2d150a208b8989204f0424e0cb2e2ac2bc/plugins/autogems.cpp#L163-L170
It checks bins, but not check bin content. I don't know how to fix it correctly.

**Comment by Nilsolm** [comment]
I've run into this issue as well at some point.

I think I may have solved it. There are some examples of how to check container content in some other plug-ins. A bit more testing, then I'll submit a PR.
