### ISSUE TITLE
Moving of files in Lua missing documentation

### ISSUE THREAD

**Issue by ralpha** [DFHack/dfhack#1555]
Moving files and folders is not documented in the docs: https://dfhack.readthedocs.io/en/stable/docs/Lua%20API.html#filesystem-module

It was a luck guess that the command `mvfile(src_file, dest_file)` exists and the parameters is has.

**Comment by lethosor** [comment]
> mvfile

The string "mvfile" doesn't appear anywhere in the DFHack codebase, so I'm pretty sure that's not one of our functions. How did you call it?

**Comment by ralpha** [comment]
Oh I got a small bug, moved directory and so exported files in that folder. 
`dfhack.filesystem.mvfile(src_file, dest_file)` just does not give any error message so though that that did it :P 
I'm working on https://github.com/DFHack/dfhack/issues/1416 for reference.

**Comment by lethosor** [comment]
That definitely doesn't work for me:
```
[lua]# ~dfhack.filesystem.mvfile
nil
[lua]# ~dfhack.filesystem.mvfile('a', 'b')
(interactive):1: attempt to call a nil value (field 'mvfile')
stack traceback:
	(interactive):1: in main chunk
	[C]: in function 'safecall'
	./hack/lua/dfhack.lua:519: in function 'dfhack.interpreter'
	../../code/dfhack/scripts/lua.lua:76: in local 'script_code'
	./hack/lua/dfhack.lua:680: in function 'dfhack.run_script_with_env'
	(...tail calls...)
```

In fact, the reason we didn't implement a move/rename function is because `os.rename()` in Lua already does that.

**Comment by ralpha** [comment]
Oh nevermind. Had I had it behind an if test to check if the file existed. And because I was in the wrong folder it never triggered the body of the if condition. So never failed.
Haha, at least my checks where working correctly :) 
(just tested, gives me error if I actually call it too)
