### ISSUE TITLE
exportlegends plus broken, again

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#1556]
http://www.bay12forums.com/smf/index.php?topic=126076.msg8132032#msg8132032
civ was renamed to entity_id

**Comment by ralpha** [comment]
I'll take a look at this

**Comment by ralpha** [comment]
It looks like this was already fixed in: https://github.com/DFHack/scripts/commit/09b64b0daa888b0d98934745b01a309fa7ea2b07 also shown in: http://www.bay12forums.com/smf/index.php?topic=126076.msg8132241#msg8132241

**Comment by lethosor** [comment]
Yeah, looks like a pack packaging issue to me: https://github.com/PeridexisErrant/starter-pack/commits/d44886e672a96a9650d6df6155d9c78296e532fe
PE probably included a patched exportlegends for 0.47.04-beta1 accidentally
