### ISSUE TITLE
df 47.04 : stonesense makes the game crash without error

### ISSUE THREAD

**Issue by jeancallisti** [DFHack/dfhack#1559]
**Versions**
- Dwarf fortress : 47.04 Windows 64 ( from https://www.bay12games.com/dwarves/df_47_04_win.zip )
- DFHack : 0.47.04-r1 Windows 64 (from https://github.com/DFHack/dfhack/releases/download/0.47.04-r1/dfhack-0.47.04-r1-Windows-64bit.zip )
- Windows 10 Pro 10.0.18363
- CPU: i7-9750H
- GPU : Nvidia Geforce GTX 1650

**Scenario :** 
- Unzip DF into a subfolder "_foo_" of the "Downloads" folder
- Unzip DFhack into a subfolder "_bar_" of the "Downloads" folder
- Copy all the files from _bar_ into _foo_
- Run Dwarf Fortress.exe
- DF starts normally, alongside the DFHack Window
- Start a new world (I picked pocket sized). Embark the dwarves straight away
- When the "real" game starts, go to the DFHack terminal and type "stonesense"
- The stonesense window briefly appears and starts loading resources (sprites or whatnot). It shows a text message in a sprite font telling you what it's currently loading

**Expected behaviour :** Stonesense finishes loading
**Observed (faulty behaviour) :** The Stonesense window closes almost immediately before you have time to read what's on screen. The DF and DHHack windows instantly crash and close too.

**Troubleshooting :** 

Last lines of gamelog.txt : 
> Loaded region1, Thur Num (The Universes of Wind) at coordinates (9,8)
Loaded the fortress Ritas‹ngiz (Owlceilings), colonized by the group F“kerfath (The Slippery Sacks) of the civilization Tulon Atham (The Roads of Focus).

Last lines of stderr.txt : 
> dfhack: redirecting stderr to stderr.log (again)

Last lines of stderr.log : 

> Invoking: stonesense
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: out-of-date sRGB profile with no signature
Client connection established.
Shutting down client connection.

**Comment by lethosor** [comment]
This sounds like the same issue as https://github.com/DFHack/stonesense/issues/68 to me, so I'd like to keep discussion there. I appreciate the detailed report, though!
