### ISSUE TITLE
Exportlegends info fails after exporting historical figures

### ISSUE THREAD

**Issue by eviscares** [DFHack/dfhack#1562]
Hi,

just tried my first legends export, and ran into this crash.
Error is repeatable and occurs every time I try to run it.
`[DFHack]# exportlegends info
    Exporting:  World map/gen info
    Exporting:  Legends xml
    Exporting:  Extra legends_plus xml
        historical figure 0/23804 (0%)
        historical figure 10000/23804 (42%)
        historical figure 20000/23804 (84%)
        historical figure 23803/23804 (100%)
...op\Dwarf Fortress 0.47.04/hack/scripts/exportlegends.lua:332: Cannot read field identity.civ: not found.
stack traceback:
        [C]: in metamethod '__index'
        ...op\Dwarf Fortress 0.47.04/hack/scripts/exportlegends.lua:332: in global 'export_more_legends_xml'
        ...op\Dwarf Fortress 0.47.04/hack/scripts/exportlegends.lua:956: in global 'export_legends_info'
        ...op\Dwarf Fortress 0.47.04/hack/scripts/exportlegends.lua:1009: in local 'script_code'
        ...pusch\Desktop\Dwarf Fortress 0.47.04\hack\lua\dfhack.lua:680: in function 'dfhack.run_script_with_env'
        (...tail calls...)`
Is this me being stupid, or is it an actual error?

For debug purposes:
OS: 10
DFHack Version: 0.47.04-r1

Kind regards

**Comment by thurin** [comment]
Are you using PeridexisErrant's Starter Pack 0.47.04-r04?

If so, that's a build issue in that version of the Pack and not a DFHack issue.  It was fixed in 0.47.04-r05.

**Comment by lethosor** [comment]
Yeah, the pack distributed an old version of that specific script that doesn't work with 0.47.04-r1.
