### ISSUE TITLE
Not a known DF version (docs unclear on installing/upgrading)

### ISSUE THREAD

**Issue by calebrader** [DFHack/dfhack#1568]
I followed the installation instructions in the readme and then started Dwarf Fortress 0.47.04 and got this error message 

---------------------------
DFHack error!
---------------------------
Not a known DF version.
DFHack will now deactivate.
Check file stderr.log for details

---------------------------
OK   
---------------------------

Log contains this information:

DFHack build: 0.47.04-r1-0-g6bdbf5b0
Identifying DF version.
Loading hack\symbols.xml ... OK
v0.47.03 SDL win32 (windows): PE: 0x5E4916E0
v0.47.03 SDL win64 (windows): PE: 0x5E491E82
v0.47.03 linux32 (linux): MD5: d64e00ffa0be385c2f94a40392d065e6
v0.47.03 linux64 (linux): MD5: 0f184a432dc8b09af70169537e8000b8
v0.47.03 osx32 (darwin): MD5: 99b655b646e355a115504d89fc5e15a9
v0.47.03 osx64 (darwin): MD5: cd5ef8c61e892f0fec8065353534aee7
Loaded 6 DF symbol tables.
Unable to retrieve version information.
PE timestamp: 0x5e5b1983

**Comment by lethosor** [comment]
> I followed the installation instructions in the readme (which amounts to a single line, "On Windows, SDL.dll is replaced" ---replace how? replaced by what? where? more detail PLEASE???)

The line you quoted is the one line *specific* to Windows - the line above also applies:
> Installing DFhack involves copying files from a release archive into your DF folder, so that: On Windows, SDL.dll is replaced

There's an SDL.dll in the zip, and it replaces the SDL.dll in the destination folder (so you'll know you did it right if you get a confirmation asking if you want to "replace SDL.dll", which you should confirm). I'm not sure exactly how to explain it better without explaining how to unzip a zip file in general, but I can try.

From your error message, it looks like you have installed DFHack 0.47.04-r1, except for the contents of the `hack` folder - specifically, `hack/symbols.xml` only contains data to support 0.47.03. You should probably remove your hack folder and install DFHack again. I checked the [official builds](https://github.com/DFHack/dfhack/releases) and the 64-bit Windows build of 0.47.04-r1 has the correct files - if you got DFHack from somewhere else, you might want to try it from here instead.

**Comment by calebrader** [comment]
Thanks. Here's a recommended change for clarity:

Installing DFhack involves copying all the files from the release into your DF folder. The installation is successful if the SDL.dll in your Dwarf Fortress root is replaced by SDL.dll from the DFHack release, along with several hundred more files.

I added "all the" which removes ambiguity about _which_ files and change "a release" to "the release".
I also added a line specifying which SDL.dll files are being mentioned, where they are located, and most importantly the other files which will be replaced during installation as the readme indicates only one.

**Comment by lethosor** [comment]
Ah, did you skip the hack folder because it already existed from an older installation? Historically we've recommended fresh installations (which would just involve replacing SDL.dll) instead of upgrading in-place. I think that recommendation might be due to DF sometimes breaking if you upgrade it in-place, but that is definitely something we could stand to document better (rather than just not mentioning it).

Anyway, did you get it working? Is there anything else you ran into? I'll probably keep this open until we've improved the docs here.

**Comment by calebrader** [comment]
Hey -- thanks for responding. Sorry I got irritable. I think I tried to
install several times before and didn't know what to do. I'm certain that's
why the DFHack directories were in there. I probably saw "do you want to
replace 970 files" and hit No every time which caused the install to fail.
I finally hit Yes today and got it working. Thanks again for responding

caleb

**Comment by lethosor** [comment]
I got around to the changes I wanted to make to these docs - you can find the latest version here: https://docs.dfhack.org/en/latest/docs/Installing.html
Suggestions are welcome, of course
