### ISSUE TITLE
exportlegends info issue

### ISSUE THREAD

**Issue by Evthestrike** [DFHack/dfhack#1575]
Any time I try to use exportlegends info this happens

    [DFHack]# exportlegends info
        Exporting:  World map/gen info
        Exporting:  Legends xml
        Exporting:  Extra legends_plus xml
            historical figure 0/13535 (0%)
            historical figure 10000/13535 (74%)
            historical figure 13534/13535 (100%)
    ...~1\Dwarf Fortress 0.47.04/hack/scripts/exportlegends.lua:332: Cannot read field identity.civ: not 
    found.
    stack traceback:
            [C]: in metamethod '__index'
            ...~1\Dwarf Fortress 0.47.04/hack/scripts/exportlegends.lua:332: in global 
    'export_more_legends_xml'
            ...~1\Dwarf Fortress 0.47.04/hack/scripts/exportlegends.lua:956: in global 'export_legends_info'
            ...~1\Dwarf Fortress 0.47.04/hack/scripts/exportlegends.lua:1009: in local 'script_code'
            ...UME~1\LNPDF~1\Dwarf Fortress 0.47.04\hack\lua\dfhack.lua:680: in function 
    'dfhack.run_script_with_env'
            (...tail calls...)

**Comment by lethosor** [comment]
Are you using a pack? If it's PeridexisErrant's 0.47.04-r04 pack, that distributed a broken version of the script, and you should upgrade (see http://www.bay12forums.com/smf/index.php?topic=126076.msg8132401#msg8132401 for details)

**Comment by Evthestrike** [comment]
I updated the pack and it fixed the problem. Thank you!

**Comment by lethosor** [comment]
Cool, thanks for reporting back!
