### ISSUE TITLE
0.2 DFPlex for windows does not listen to the secondary port, only [STATICPORT] listen works correctly, the second port for the actual game never works.

### ISSUE THREAD

**Issue by faycalki** [DFHack/dfhack#1579]
I get "connection error", I'm hosting on Windows 10 x64.

I used firefox and it worked for localhost, I also used google chrome which worked for none of them, and I used edge which worked for ocalhost
But over the internet it doesn't work, even though like I said I forwarded the ports, the page loads but it says "connecting" then just says retry.

After further investigation, it seems the windows build never "attaches" to the port 1234, even if you change that port to any other port, it never attaches to that specific port, by attach I mean it never "Listens" to that port.

Note that i port forwarded and everything correctly, and I double checked so it's not a firewall or port forward issue, the issue is for Windows, the application never attaches to the secondary port, which by default is 1234. the [STATICPORT] attaches correctly though, which is port 8000 by default.

Note that version 0.1 for DF 0.44 works correctly, but version 0.2 of DFPlex for 0.47.04-r1 does not work correctly, pertaining to the issues I listed above.

**Comment by lethosor** [comment]
dfplex is a third-party plugin, so https://github.com/white-rabbit-dfplex/dfplex is where you should report this (but I also suspect your [forum post](http://www.bay12forums.com/smf/index.php?topic=176070.msg8145654#msg8145654) will get visibility).
