### ISSUE TITLE
Units.isMilkable true for whole race if any caste is milkable

### ISSUE THREAD

**Issue by TymurGubayev** [DFHack/dfhack#1583]
The [Units.isMilkable](https://github.com/DFHack/dfhack/blob/2fc7fa7ac2e56bffa5775e33fc3a3a8cafd6f364/library/modules/Units.cpp#L660) looks like the following.

```c++
bool Units::isMilkable(df::unit* unit)
{
    CHECK_NULL_POINTER(unit);
    df::creature_raw *raw = world->raws.creatures.all[unit->race];
    for (auto caste = raw->caste.begin(); caste != raw->caste.end(); ++caste)
    {
        if((*caste)->flags.is_set(caste_raw_flags::MILKABLE))
            return true;
    }
    return false;
}
```

I.e. what it does is check if **any** caste of unit's race is milkable and if so returns `true`. I think it should only return `true` when the actual caste of the unit is milkable.

**Comment by ragundo** [comment]
Hmmm. Maybe there should be an overload of that method with a second parameter specifying the desired caste

**Comment by lethosor** [comment]
Since this is in the Units module, I'm inclined to agree that it's a bug. Making users pass in (unit, unit.caste) doesn't seem as logical to me. Maybe we could have a separate function that performs the current functionality given a creature raw ID or something similar.

**Comment by TymurGubayev** [comment]
I think only current usages are in [plugins/zone.cpp](https://github.com/DFHack/dfhack/blob/2fc7fa7ac2e56bffa5775e33fc3a3a8cafd6f364/plugins/zone.cpp#L1326) and in [scripts/workorder.lua](https://github.com/DFHack/scripts/blob/47d9b3c9390d21ecc49ddaba477b16071884ee87/workorder.lua#L664).

The `workorder`-script will definitely benefit if this function is changed; I'm no 100% sure about the `zone`-plugin, but probably too.
