### ISSUE TITLE
Question: How to communicate with DFHack using grpc?

### ISSUE THREAD

**Issue by CIB** [DFHack/dfhack#1584]
Hi. Sorry for using a github issue, but it seemed like the easiest way to communicate.

I'm experimenting with building a program that communicates with DFHack using node. I saw that grpc is currently being used for this purpose. For that, I used [this tutorial](https://grpc.io/docs/languages/node/basics/). Loading the .proto files worked fine, however from there I got stuck. The tutorial explains that to create a client, you have to "attach" to one of the service definitions in the proto file. But as far as I can tell, the proto files in DFHack don't define any services at all. Rather, all the function signatures seem to be only available as comments. How would I go about actually calling these functions from node grpc?

**Comment by ragundo** [comment]
Usually, you need to create a C++ DFHack plugin which process the data that you need to use in the input proto message and pack it to a proto out message.

Check [RemoteFortressReader ](https://github.com/DFHack/dfhack/blob/develop/plugins/remotefortressreader/remotefortressreader.cpp#L146) plugin as a example.

**Comment by lethosor** [comment]
We're using our own RPC protocol, actually, not gRPC. I don't think gRPC would work with DFHack out of the box, but maybe it's similar.

**Comment by CIB** [comment]
Ah, gotcha, thanks. I just googled "rpc protobuf", and so google's rpc protocol came up, hence the confusion. :)

Hm, so I guess I'd have to implement that protocol in node myself. I tried to find the implementation in armokvision, but couldn't. How difficult would it be to implement from scratch?

**Comment by lethosor** [comment]
https://github.com/RosaryMala/RemoteClientDF-Net is (at least most of) Armok Vision's RPC implementation. You're at least the second person this month to ask about DFHack's RPC protocol, and it is definitely in need of documentation. Ragundo (or RosaryMala) would know more about the protocol than myself at the moment.

**Comment by BenLubar** [comment]
I have a Go implementation of the RPC here: https://github.com/BenLubar/dfhackrpc

Since Dwarf Fortress currently only runs on x86, assuming little endian is pretty safe. A lot of code within Dwarf Fortress also passively assumes little endian.

**Comment by McArcady** [comment]
This JS client can connect to DFHack RPC services like RemoteFortressReader or IsoworldRemote:
[https://github.com/alexchandel/dfhack-remote](url)
The connection is not direct, but goes through a websockify proxy.

**Comment by lethosor** [comment]
Closing as this seems to have been addressed.

We also have a dedicated documentation page for DFHack's remote API now (open to additions): https://docs.dfhack.org/en/latest/docs/Remote.html
