### ISSUE TITLE
Confirm on conviction

### ISSUE THREAD

**Issue by FalcoGer** [DFHack/dfhack#1593]
I just wanted to interrogate someone, and then accidentally convicted them. Since there is no way to revert that "choice", I'd like conviction to be added to the confirm dialog, please.

**Comment by lethosor** [comment]
This turned out to be pretty straightforward:

![image](https://user-images.githubusercontent.com/3719547/85206118-c298ab80-b2ed-11ea-8ce0-a4f4d3160d8e.png)

Thanks for the suggestion!

**Comment by FalcoGer** [comment]
thank you
