### ISSUE TITLE
labormanager doesn't adduce correct build labor for custom furnaces

### ISSUE THREAD

**Issue by ab9rf** [DFHack/dfhack#1595]
I got a report via Discord of labormanager failing to allocate an architect to build a Masterwork "finishing forge". On research, I've determined that this is a custom furnace. Labormanager is not respecting the designated custom build labor when inferring the required build labor, which results in starving finishing forges (and likely other Masterwork custom furnaces) of the architect required.

**Comment by Tokeli** [comment]
Here's a save showing off the bug in Masterwork 1.31 https://dffd.bay12games.com/file.php?id=15118
