### ISSUE TITLE
Trade screen searches don't restore item counts properly

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#1602]
Reported by @FalcoGer on IRC
The issue is that the trade search classes (starting [here](https://github.com/DFHack/dfhack/blob/0.47.04-r1/plugins/search.cpp#L1217)) are only saving/restoring the ["items" and "selected" vectors](https://github.com/DFHack/df-structures/blob/0.47.04-r1/df.viewscreen.xml#L3149-L3154) - they need to handle the "count" vectors too. This will involve switching to search_multicolumn_modifiable, like the [kitchen search](https://github.com/DFHack/dfhack/blob/0.47.04-r1/plugins/search.cpp#L2126) or the [pets search](https://github.com/DFHack/dfhack/blob/0.47.04-r1/plugins/search.cpp#L770)

**Comment by GitOnUp** [comment]
Took a crack at this since it's labeled as a good first issue.  #1633

**Comment by lethosor** [comment]
Yep, glad the label worked!
