### ISSUE TITLE
Script to cause off-site histfig to die

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#1603]
For [this DF bug](https://www.bay12games.com/dwarves/mantisbt/view.php?id=11549) (more specifically, [this duplicate](https://www.bay12games.com/dwarves/mantisbt/view.php?id=11571)), PatrikLundell [identified a possible workaround](http://www.bay12forums.com/smf/index.php?topic=176846.msg8164415#msg8164415) that involves setting the death time to a time in the near future. This would probably be pretty easy to add as a `fix/` script. (It would be good to test on some of the other crashing saves too.)

**Comment by PatrikLundell** [comment]
The big problem here is to identify the trouble causing histfig. I don't know what method @quietust used to identify the histfig causing the issues, but for a script to really have any impact, you'd need to be able to identify the histfig to kill off.

**Comment by quietust** [comment]
The method I used was to attach to DF from within IDA and set a breakpoint just before the crash, such that one of the CPU registers contained a Unit pointer referring to the mother. Then I jumped to that memory location and Alt+Q'ed a Unit structure onto it so I could easily find all of the important fields (unit ID, histfig ID, and race).

It took a bunch of trial and error to find the ideal breakpoint location (0x140DDB52B for Win64, but you have to set it **before** attaching a debugger for the first time because the EXE gets rebased and all of the addresses change), and the breakpoint tripped multiple times before it got to the case where it crashed (so I had to write down about a dozen unit/histfig IDs before getting the right one).

**Comment by PatrikLundell** [comment]
Thanks for that explanation, which, unfortunately, was approximately what I expected, i.e. a manual process that can't be replicated by a script.
Atomic Chicken has found a couple of anon fields that may offer a better target for a script, though [(http://www.bay12forums.com/smf/index.php?topic=176846.0)]

**Comment by PatrikLundell** [comment]
```function x ()
  for i, hf in ipairs (df.global.world.history.figures) do
    if hf.info and
       hf.info.curse and
       hf.info.wounds and hf.info.wounds.anon_1 >= df.global.cur_year then
      hf.info.wounds.anon_1 = -1
      hf.info.wounds.anon_2 = -1
      dfhack.println ("Aborting pregnancy on cursed " .. dfhack.TranslateName (hf.name, true) .. "/" .. dfhack.TranslateName (hf.name, false))
    end
  end
end

x ()
```

seems to avoid the crash in the two saves I've tested. Note that I don't know if something will happen when the hf enters the embark and the unit (presumably with its pregnancy info unchanged) gets loaded. From that perspective killing the unit might be safer.

**Comment by lethosor** [comment]
Any thoughts on good names for the anon fields? From the thread, it sounds like they're probably pregnancy-specific, so maybe `pregnancy_year` and `pregnancy_tick`?

**Comment by PatrikLundell** [comment]
I'm somewhat hesitant when it comes to pregnancy_*, as that sound more like the time of initiation of the pregnancy than the time of giving birth (i.e. the end of it). "give_birth_*" is a bit awkward too, though.

**Comment by lethosor** [comment]
I think it would be more consistent with https://github.com/DFHack/df-structures/blob/76c3c0daa7e681b40913e83c2849e9c49e2e04ab/df.units.xml#L669, though (although that only has a single `pregnancy_timer` field, apparently).

**Comment by PatrikLundell** [comment]
"_timer" indicates a duration, and so is fine (the duration of the pregnancy). What about "pregnancy_timer_*" for year/tick?

**Comment by AtomicChicken** [comment]
If I remember correctly, pregnancy_timer decrements by 1 each tick, causing the unit to give birth when it reaches 0.

I'd go for something like "parturition_year", "parturition_tick" or "childbirth_year", "childbirth_tick" for the sake of clarity.

**Comment by PatrikLundell** [comment]
I'd prefer the latter pair, for the sake of clarity. Remember that many forumites aren't native English speakers (and I suspect a fair number of those that are may struggle with some "big words").
