### ISSUE TITLE
Can't make weapons with advfort

### ISSUE THREAD

**Issue by wolfboyft** [DFHack/dfhack#1604]
When pressing tab at the metalsmithing workstation, choose what to make -> weapons and ammunition (as well as siege eq. and armour!) are all empty.

**Comment by lethosor** [comment]
I spent some trying to reproduce this and couldn't get to a screen that would let me build a forge, or craft weapons or ammo. Can you provide some steps to reproduce this issue? Are you sure this isn't the vanilla DF building UI?
(Alternatively, @warmist almost certainly knows more about advfort than I do)

**Comment by lethosor** [comment]
Ok, I figured out how to build with advfort (the `?` help page is helpful). I am seeing options in all the categories you mentioned, though. What race is your adventurer? For example, animal men might not be able to make certain metal objects. (Also, is your world modded at all?)

**Comment by wolfboyft** [comment]
It's a modded caste of human (fwiw, 3 tailed female kitsune). Maybe crafting capabilities are set somewhere and mention male and female specifically instead of all? Hmm.

And I also have a mod called adventurer reactions that adds a couple of extra reactions like making stone axes and stuff.

I think the caste thing is a useful lead. I shall try it as a normal human or dwarf or whatever at once!

Thank ya

**Comment by wolfboyft** [comment]
In one world a human male had the options, in the object testing arena (same raws) another one didn't.

Plus I was unable to find anything relating to castes and forging capabilities.

I think it might be something to do with civilisations and the world(gen) itself.

**Comment by lethosor** [comment]
Yeah, maybe it also has something to do with the civilization (e.g. I think civs might not always have access to iron)

**Comment by wolfboyft** [comment]
Do you mean in terms of the raws themselves? Because when I did see it, I definitely was a human.
That was in a 550 (or was 250?) year old world

the other was a minimalist 2 years world w few civs but still.

**Comment by lethosor** [comment]
No, I mean a specific in-game civilization. The raws define what a civilization *could* have access to, but that can vary based on what happens during world generation. I'm a bit rusty on the details, but [here](https://dwarffortresswiki.org/index.php/DF2014:Trading#Dwarves) is a mention of this type of behavior from the wiki:

> If the trading civilization does not have access to iron, they can still bring steel (and steel goods) and pig iron bars, but will not bring iron products.

I'm unsure exactly what the details are, or whether advfort is intended to check what a civ has access to (@warmist?). If you still have the save, you could upload it for diagnosis.

**Comment by wolfboyft** [comment]
Here's the world where I can't: https://drive.google.com/file/d/1mMLzAt2-S-8D9KgRQoFsYu_5pmJOWJy0/view?usp=sharing

**Comment by wolfboyft** [comment]
And here's where I can, using a random adventurer and who's already standing on a (gui/hack-wish'd-in) MSforge: https://drive.google.com/file/d/1rloJCTS9eHi9V3weZA_WiXsEByaT4Ggd/view?usp=sharing

**Comment by wolfboyft** [comment]
Does it vary from site-to-site?

**Comment by wolfboyft** [comment]
Right, so with some experimenting, it seems that the civilisation an adventurer is a citizen of is what matters. That can change if you retire somewhere because when you unretire you will be a citizen of that place.

So maybe I just need to make a dummy civilisation that "has access" to all the things.
Problem is... I can't even find how to see civilisations in gm-editor.

**Comment by lethosor** [comment]
Civilizations are instances of `historical_entity` (although not all `historical_entity`s are civs). Adding a new one is probably pretty hard. It should be easier to give your current civ access to certain materials, although I'm not sure how to do this off the top of my head.

**Comment by warmist** [comment]
Advfort tries to be smart and setups the ui fields to be same as your adventurer. However that probably would cause issues for some adventurers...

I (or anyone wanting to fix this) probably needs to find a good "civ" and race to use in `setupFields` function. However currently i'm not how to best select it in general case (i.e. if using a lot of mods?)

**Comment by wolfboyft** [comment]
I mean, it's 100% a caste of human, just with different ears and a tail (or three).
It's definitely based on what can be made at the place your adventurer belongs to-- the civ-- where you unretire/start from.

**Comment by wolfboyft** [comment]
So yeah, been fiddling w/ it for a while-- you can make what a fortress with your civilisation can make.

**Comment by warmist** [comment]
I'm very sorry that i don't get to this... I think easiest quick fix would be to find a dwarf civ and set it in `setupFields`. That way you would not need to change your own civ but you would get access to all dwarven crafts.

**Comment by warmist** [comment]
Fixed this in [this pullreq](https://github.com/DFHack/scripts/pull/161)
