### ISSUE TITLE
Can't build a tool workshop with advfort

### ISSUE THREAD

**Issue by wolfboyft** [DFHack/dfhack#1605]
Selecting "tool" in the Select Building menu closes the menu and makes no change to the world.
Most of the other shops seem to work nicely...

**Comment by lethosor** [comment]
To clarify, this is under "workshops", right?

I'm getting this error in the console (generally, looking in the DFHack console for this information is useful):
```
./hack/lua/dfhack/buildings.lua:464: one of items, filters or abstract is required
stack traceback:
	[C]: in function 'error'
	./hack/lua/dfhack/buildings.lua:464: in function 'dfhack.buildings.constructBuilding'
	../../code/dfhack/scripts/gui/advfort.lua:650: in function <../../code/dfhack/scripts/gui/advfort.lua:631>
	[C]: in field 'on_select'
	./hack/lua/gui/buildings.lua:248: in method 'submitBuilding'
	./hack/lua/gui/buildings.lua:256: in function <./hack/lua/gui/buildings.lua:252>
	[C]: in field 'on_submit'
	./hack/lua/gui/widgets.lua:694: in field 'on_submit'
	./hack/lua/gui/widgets.lua:607: in method 'submit'
	./hack/lua/gui/widgets.lua:619: in method 'onInput'
	./hack/lua/gui.lua:484: in function <./hack/lua/gui.lua:479>
	(...tail calls...)
	./hack/lua/gui.lua:484: in method 'inputToSubviews'
	./hack/lua/gui/buildings.lua:271: in function <./hack/lua/gui/buildings.lua:260>
	[C]: in ?
```

Evidently either the dfhack.buildings module or advfort (or both?) doesn't support tools.

**Comment by warmist** [comment]
I think tool is a bit special because you need to specify which one to build when building it as opposed to how others can be constructed. Indeed that is what error is saying - and advfort does not have a way to this.

**Comment by wolfboyft** [comment]
Now that I've *played* fort mode... what the hell *is* a tool workshop??
Bookcases etc are already implemented (though they also do not work) outside of any choose-what-to-build submenus

**Comment by lethosor** [comment]
Maybe something like a display case or an altar would be a "tool"?

**Comment by warmist** [comment]
Okay so to make it clear for future generations: Advfort is very lazy (like me). Because of that it just makes a list of all workshops ( I forget from where). There must be a "tool workshop" that is internally used for "tool based workshops". That probably includes: altar, display case, cauldron (found in monster caves), and so on.

Fix should be: blacklist the generic type and special case add the specific ones.

**Comment by lethosor** [comment]
It's using BuildingDialog from library/lua/gui/buildings.lua. It looks like there is a flag that could be set to disable the tool workshop: https://github.com/DFHack/dfhack/blob/fb44b26b47eca729646e316efc22cfe2a138691e/library/lua/gui/buildings.lua#L33
