### ISSUE TITLE
Advfort "stud with gold" seems to not produce anything

### ISSUE THREAD

**Issue by wolfboyft** [DFHack/dfhack#1618]
Did "stud with gold" on an adamantine long sword and the result was nowhere to be found. Removed the smith shop too, nothing dropped, so yeah
Will also test with other things to verify, and also if other encrusting/studding/decorating things delete items too

**Comment by wolfboyft** [comment]
Encrusting with gems also deletes items. You can't encrust items with low quality (the sword was low quality) but it still deletes.

**Comment by Ozzatron** [comment]
Ran into this issue while playing a long running advfort save, after I noticed my steel pick was randomly obliterated.

I made a backup and decided to do some extensive testing of decorations with advfort, using the following items:
- A weapon: `≡steel battle-axe≡`
- An armor piece: `+bronze helm+`
- A finished good: `☼wolf bone scepter☼`
- A piece of furniture: `≡microcline armor stand≡`
- A stack of ammunition: `☼wolf bone bolts [5]☼`
- A leather bag: `≡longfin mako shark leather bag≡`
- A silk bag: `≡giant cave spider silk bag≡`
- A cut gem: `round green glass cabochons`
- A bar of metal: `gold bars`
- A stack of bones: `cougar mangled bone [16]`
- A bolt of cloth: `☼giant cave spider silk cloth☼`
- A piece of leather: `horse leather`

Results:
1. Encrusting any unstacked item with gems, regardless of the item or the `-a` or `-c` flags on advfort, deletes the item and the gems, but does provide experience. It does not matter which of the three encrusting jobs you pick, or whether the item you choose to encrust is the right type for that job.
2. Encrusting a stack of ammo with gems reduces the ammo count by one and deletes the gems, but does not decorate the remaining ammo.
3. Studding any unstacked item deletes both the item and the metal bar, with experience gain.
4. Studding a stack of ammo produces identical behavior to gem encrusting (you lose the metal and 1 ammo, but no decoration appears).
5. You cannot sew silk or leather images onto leather bags.
6. You can sew leather images onto silk bags without issue.
7. The `Sew leather image` command will also suggest you attempt to sew the image onto the bolt of cloth you are carrying. This will spend time and gain experience, but produce no effect (both the leather and the cloth are dropped at your feet).
8. You can sew silk images onto silk bags without issue.
9. Decorating anything with a stack of cougar bones deletes the item and reduces the stack of cougar bones by 1.
10. The `Decorate with bone` command will also suggest you attempt to use the bone bolts and the scepter in the decoration. Attempting to decorate the steel battle axe with the wolf bone scepter results, oddly enough, in a _wolf bone scepter decorated with steel._

Results 2, 4 and 10 seem peculiar, as if the decoration job is crossing the signals of which item is being decorated with which.

**Comment by Ozzatron** [comment]
Found out that `job.items` was not being filled in exactly the order of `job.job_items` by advfort. Adding a bit of insertion sort to `advfort_items.lua` so that they are always in the same order fixes issues 1, 2, 3, 4, 9, and 10.

However, all decorations thus produced are generic, for example "hanging rings of exceptionally worked green glass" instead of "encrusted with round green glass cabochons".
