### ISSUE TITLE
Can fastdwarf + timestream solve FPS death?

### ISSUE THREAD

**Issue by daedsidog** [DFHack/dfhack#1638]
For me, the problem with FPS death is that the dwarves take forever to do things and the world simulation becomes less interesting because it takes so much time for the seasons to progress. In early game, a play session could last 5 years, and many things could get done, but in late game you could spend an entire session in just one season with your dwarves testing your patience.

It seems to me that even in extremely low FPS, fastdwarf causes dwarves to behave about the same as their 100 FPS counterpart, if not a lot better.  Is it feasible to make a plugin which applies fastdwarf globally (ie to all the creatures on the map, not just citizens) while also speeding up the calendar **based on the ratio of 100 and the current FPS?**

You would still have GUI lag, slower world & environment checks, etc.

### Example:
100 FPS: No effect
50   FPS: Creatures and calendar would progress at x2 speed
25   FPS: x4 speed
Etc.

**Comment by lethosor** [comment]
fastdwarf intentionally limits itself to citizens: https://github.com/DFHack/dfhack/blob/8728056674c7249f1a15f80c62e3ded16507bb56/plugins/fastdwarf.cpp#L53-L55
Removing this check would probably make it apply to every creature on the map, although I'm not sure if wildlife (or creatures without a specific task/destination/action/etc.) would behave normally.

As for speeding up time, is there an existing "timestream" tool that does that? My concern would be that some important event could get skipped if the corresponding tick is skipped, but maybe just modifying the cur_year/cur_year_tick globals is safe.

**Comment by daedsidog** [comment]
I was thinking more in the vein of making this a dynamic thing based on your current FPS. If you have 100 FPS, nothing would change, but say you drop to 50, timestream would ramp up to 2x and fastdwarf would make dwarves only twice as fast as they are. That way you get that constant 100 FPS experience. 

Again, I'm not an expert in how fastdwarf works, so I don't know if this is feasible to even do.

**Comment by quietust** [comment]
If you wanted to make fastdwarf apply to all units on the map, you could instead use mode "2" which works by setting the `DEBUG_MEGAFAST` flag in Dwarf Fortress.

**Comment by daedsidog** [comment]
> If you wanted to make fastdwarf apply to all units on the map, you could instead use mode "2" which works by setting the `DEBUG_MEGAFAST` flag in Dwarf Fortress.

I played around with that enabled today. Even at 30-40 FPS, everyone is zooming about much faster than I could keep track of.

In my mind I wasn't thinking of fastdwarf, but a variation of it which doesn't work at full throttle at all times. A hacky example would be to turn it on and off in phases, or limit the FPS of the game to a certain sweet spot which would provide 100 FPS experience when the fastdwarf 2 is enabled.
