### ISSUE TITLE
turn down fortplan and digfort

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#1644]
The quickfort script is positioned to replace fortplan and digfort, but we should have a proper plan for deprecating and removing them so their current users aren't caught by surprise. Here is a possible plan (open for discussion and changes):

1) do nothing until quickfort has been "proven" for at least one release and no significant bugs are open against it
2) advertise that fortplan and digfort are deprecated:
- output a deprecation warning when they are run, pointing people to quickfort
- update their documentation with the deprecation warning and pointer to quickfort
- add a deprecation warning and pointer to quickfort to their source files
3) after a good amount of time (one year?), remove fortplan and digfort source but leave documentation stubs that announce what has happened and provide a pointer to quickfort
4) after more time (or maybe never), remove the documentation stubs for fortplan and digfort

edit: step 4 is not necessary. we have Removed.rst for this purpose

**Comment by lethosor** [comment]
As long as it's easy to switch to quickfort, this sounds great to me! From my (admittedly limited) testing, I'm pretty confident that this won't pose any major obstacles to digfort users. I'm unsure about fortplan, since I've never used it myself.

**Comment by myk002** [comment]
the transition should be relatively painless, though you're right that it should be documented.
- digfort and fortplan users will see the base path of their input files change from df_root to df_root/blueprints
- `digfort file` becomes `quickfort run file`
- `fortplan file` becomes `quickfort run file`
