### ISSUE TITLE
OSX - Dfhack launches but seams to not be working? 

### ISSUE THREAD

**Issue by Treah** [DFHack/dfhack#1649]
I am able to sucessfully launch the dfhack script but DF lauches with no indication that dfhack is running and also not getting a dfhack console? 

Not sure if something is not being setup correctly as I have no errors or anything in OSX just getting vanilla DF with no hack after launching hack?

**Comment by lethosor** [comment]
How are you launching DFHack? If you're not already, can you try running it with `./dfhack` from an existing terminal (after navigating to your DF folder)?

**Comment by Treah** [comment]
Yes I am launching it from an existing terminal using the ./dfhack

**Comment by lethosor** [comment]
Is there any output in the terminal after you start DFHack? Can you upload your stderr.log?

**Comment by Treah** [comment]
![Screen Shot 2020-09-16 at 10 58 45 AM](https://user-images.githubusercontent.com/12091471/93374870-2eff4a00-f80c-11ea-83a6-246a18020dce.png)
Here is what shows up when Launching. There is no stderr.log in the df folder where I am running hack from.

**Comment by lethosor** [comment]
The dfhack script uses bash regardless of what your system shell is. What DFHack version are you using? https://github.com/DFHack/dfhack/pull/1606 was intended to fix some Catalina issues and is part of 0.47.04-r2.
Could you also try running ./dfhack-run? It won't do anything, but I'm wondering if a gatekeeper error will come up.

**Comment by Treah** [comment]
I am running 0.47.04-r2 
When I run dfhack-run I get the below. 

`:> ./dfhack-run
Usage: dfhack-run <command> [args...]

Note: this command does not start DFHack; it is intended to connect
to a running DFHack instance. If you were trying to start DFHack, run
   ./dfhack
or see the documentation in hack/docs/index.html for more help.
:> `

**Comment by lethosor** [comment]
Ok, that's good. Can you post the contents of your `dfhack` script?

**Comment by Treah** [comment]
Sure I did not modify it from what I remember other then checking to make sure it did not contain any ^M at every line end like the soundsense one has that makes it not work. 

```
#!/bin/sh
PWD=`dirname "${0}"`
cd "${PWD}"
#thanks to Iriel for figuring this out
OSREV=`uname -r | cut -d. -f1`
if [ "$OSREV" -ge 11 ] ; then
	export DYLD_LIBRARY_PATH="./hack:./libs:./hack/libs"
	export DYLD_FRAMEWORK_PATH="./hack:./libs:./hack/libs"
else
	export DYLD_FALLBACK_LIBRARY_PATH="./hack:./libs:./hack/libs"
	export DYLD_FALLBACK_FRAMEWORK_PATH="./hack:./libs:./hack/libs"
fi

# attempt to remove quarantine flag: https://github.com/DFHack/dfhack/issues/1465
if ! test -f hack/quarantine-removed; then
    find hack/ libs/ dwarfort.exe \( -name '*.dylib' -or -name '*.framework' -or -name '*.exe' \) -print0 | xargs -0 xattr -d com.apple.quarantine 2>&1 | grep -iv 'no such xattr'
    echo "quarantine flag removed on $(date); remove this file to re-run" > hack/quarantine-removed
fi

if [ ! -t 0 ]; then
    stty() {
        return
    }
fi

old_tty_settings=$(stty -g)
DYLD_INSERT_LIBRARIES=./hack/libdfhack.dylib ./dwarfort.exe "$@"
stty "$old_tty_settings"
tput sgr0
echo ""
```

**Comment by Treah** [comment]
LOL disregard this.... My AV was blocking this because it interacts with memory in another application so it thought it was some kind of virus. I will need to mark it as OK to do this. Sorry for leading anyone down a rabbit hole.

**Comment by lethosor** [comment]
Interesting. DFHack actually doesn't interact with memory in *another* application (it runs in the same process as DF), but the technique it uses to inject itself into DF (DYLD_INSERT_LIBRARIES in the dfhack script) could conceivably be used by malware. I'm not sure how any third-party antivirus software could prevent it from working, but the OS could probably prevent it, and that would keep DFHack from being able to initialize, which would match the behavior you saw.
(Hopefully that's helpful if you need to disable a specific AV feature if whitelisting DFHack isn't enough)
