### ISSUE TITLE
Integrate quickfort docs into main docs

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#1653]
I'm planning to move the user-facing quickfort docs into Sphinx so that they end up on https://docs.dfhack.org/ and in the bundled docs in release builds. Opening an issue mainly for tracking.

A couple questions for @myk002:
* The main page I've found is https://github.com/DFHack/dfhack/blob/develop/data/blueprints/README.md - are there others that should also be moved over?
* That page links to a couple files on GitHub (e.g. aliases-common.txt), which makes me wonder - are there any links *to* this page on GitHub that would need to be updated (so they don't 404 when README.md is removed)?

As a side note, I'd like to find a way to either bundle files like aliases-common.txt with the docs or link to the corresponding version on GitHub for versioned builds like https://docs.dfhack.org/en/0.44.12-r1/. Somewhat lower-priority, though.

**Comment by myk002** [comment]
1) no, README.md is the only doc file that isn't already integrated with
sphinx
2) there are links to README.md in the quickfort help text in
quickfort.lua, the forums, and in some private messages/emails I've sent.
Most don't link to the file directly, but rather the blueprints/ directory
on GitHub. I'd suggest leaving a stub README.md that points to the new doc
location.

**Comment by lethosor** [comment]
Ah, forgot about help text, thanks. I'm not entirely sure what the best solution there is - I would prefer to use Sphinx `ref`s, which would work for local builds of the docs, but those come at the cost of removing the URLs from the help text itself. I suppose I could keep them in a comment or something.

**Comment by myk002** [comment]
what is the current status on this? I have a few more features to document, plus the dreamfort case study. Should I add them to the existing README.md or wait for the RST?

**Comment by lethosor** [comment]
I haven't gotten to it yet, but I can now (ish). I'll let you know if that changes / when I'm done.

**Comment by lethosor** [comment]
Things are coming along on this branch: https://github.com/lethosor/dfhack/tree/quickfort-docs-rst
My main remaining task is to check for broken formatting or links (fortunately, pandoc seems to have done a good job converting these!). Once that's done, I'll move on to updating the scripts repo as needed.

If you happen to have time and are able to build the docs locally, a second set of eyes on this would certainly be appreciated (but I'll also make a PR when I think I'm done).

**Comment by myk002** [comment]
I'm remote from my workstation, but I built the docs and viewed them in a text browser (lynx). They look great! I like how the links are set. The only thing I saw was that toc depth was set to 2, but the generated toc was complete. Not really a problem, but something isn't working as intended. I'd be fine with a full toc.

**Comment by lethosor** [comment]
Hm, here's a screenshot of what I see. Is this the TOC you're talking about? What sphinx + docutils version are you using? I have 3.1.2 and 0.16, respectively (although I think only docutils matters in this case.) I'm open to bumping up the depth here; this was just to match the original TOC in the markdown version.

![image](https://user-images.githubusercontent.com/3719547/94979271-d5776a80-04ef-11eb-8520-e60d07c38d86.png)

As for the examples, it looks to me like the theme we're using has a bit more padding on the sides of code blocks than GitHub does, but the text itself is unaffected (highlight for reference). It's consistent with other pages (and callout blocks), but not too hard to override with some custom CSS.

![image](https://user-images.githubusercontent.com/3719547/94979408-6ea68100-04f0-11eb-8441-afdbeccc0618.png)

**Comment by myk002** [comment]
sphinx-3.2.1 and docutils-0.16 here's the toc html:

`<ul>
<li><a class="reference internal" href="#">Quickfort User Guide</a><ul>
<li><a class="reference internal" href="#features">Features</a></li>
<li><a class="reference internal" href="#editing-blueprints">Editing Blueprints</a><ul>
<li><a class="reference internal" href="#area-expansion-syntax">Area expansion syntax</a></li>
<li><a class="reference internal" href="#automatic-area-expansion">Automatic area expansion</a></li>
<li><a class="reference internal" href="#multilevel-blueprints">Multilevel blueprints</a></li>
<li><a class="reference internal" href="#dig-priorities">Dig priorities</a></li>
<li><a class="reference internal" href="#marker-mode">Marker mode</a></li>
<li><a class="reference internal" href="#stockpiles-and-zones">Stockpiles and zones</a></li>
<li><a class="reference internal" href="#minecart-tracks">Minecart tracks</a><ul>
<li><a class="reference internal" href="#constructed-tracks">Constructed tracks</a></li>
<li><a class="reference internal" href="#carved-tracks">Carved tracks</a></li>
</ul>
</li>
<li><a class="reference internal" href="#modeline-markers">Modeline markers</a><ul>
<li><a class="reference internal" href="#blueprint-labels">Blueprint labels</a></li>
<li><a class="reference internal" href="#start-positions">Start positions</a></li>
<li><a class="reference internal" href="#hiding-blueprints">Hiding blueprints</a></li>
<li><a class="reference internal" href="#messages">Messages</a></li>
</ul>
</li>
<li><a class="reference internal" href="#packaging-a-set-of-blueprints">Packaging a set of blueprints</a></li>
<li><a class="reference internal" href="#meta-blueprints">Meta blueprints</a></li>
</ul>
</li>
<li><a class="reference internal" href="#buildingplan-integration">Buildingplan integration</a></li>
<li><a class="reference internal" href="#generating-manager-orders">Generating manager orders</a></li>
<li><a class="reference internal" href="#tips-and-tricks">Tips and tricks</a></li>
<li><a class="reference internal" href="#caveats-and-limitations">Caveats and limitations</a></li>
<li><a class="reference internal" href="#links">Links</a></li>
</ul>
</li>
</ul>`

**Comment by lethosor** [comment]
Oh, are you talking about the table of contents in the sidebar? The `:depth: 2` is for the one in the body of the page, right above the "Features" heading. I'm not sure if the sidebar depth is possible to control, actually (at least on a per-page basis)

**Comment by myk002** [comment]
ah, silliness. yes. you're right. looking at it in chrome, the toc is depth 2. everything looks good. thank you very much for converting the doc! will you be removing the text from README.md in this PR too?

**Comment by myk002** [comment]
Though if there already is an autogenerated toc in the margin, maybe we don't need another one inline in the text?

**Comment by lethosor** [comment]
Yeah, I'll deal with the readme and the script docs. PR should be up fairly soon.
There's a bit of a convention to have in-page TOCs, e.g. on https://docs.dfhack.org/en/stable/docs/Lua%20API.html and https://docs.dfhack.org/en/stable/docs/Core.html, so I think it's ok to have it on this page too (even if it does mirror the sidebar more than on some other pages)
