### ISSUE TITLE
Windows: console closes DF when closed

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#1679]
A Discord user mentioned that closing the DFHack console on Windows will quit the game without saving. I'm fairly certain that this is not intentional (it doesn't match behavior on other platforms), and it may actually be a crash that is silenced by #1048.
Opening an issue to track since I don't have a proper Windows dev environment to debug this.

**Comment by quietust** [comment]
DFHack explicitly disables the Close button on its Console window (using code that reportedly worked as far back as Windows 2000), and I've confirmed that that logic works correctly on both both Windows 10 build 19041 and Windows 8.1.

However, this method doesn't seem to prevent you from closing the window from the Preview window that appears when hovering over its taskbar icon.

The following StackOverflow post suggests that preventing this may be impossible:
https://stackoverflow.com/questions/11959643/

**Comment by lethosor** [comment]
Good to know, thanks. UristMcRilo provided the following screenshot, which does appear to be what you're describing (that or the alt-tab screen):

![image](https://user-images.githubusercontent.com/3719547/96519641-73cb3600-123b-11eb-99f0-e2d633d3a9d7.png)

Probably nothing to do here, then.
