### ISSUE TITLE
DFHack v 0.47.04-r2 DwarfVet Rest Area Inaccessible

### ISSUE THREAD

**Issue by Woozle44** [DFHack/dfhack#1681]
No crash but when I enable DwarfVet my animals spam the announcements with "Rest area inaccessible". Using dwarfvet report confirms that the hospital is the zone I have designated as Hospital+Animal Training and it is in the correct location. The animals that it identifies as patients can all walk and can access the hospital. Additionally when I get one of those patients in the hospital (pasturing then removing the pasture so it doesn't interfere), they still spam rest area inaccessible.

**Comment by Nilsolm** [comment]
As per http://www.bay12forums.com/smf/index.php?topic=164123.msg8206358#msg8206358, the issue cannot be replicated with the latest DFHack 0.47.04-r3.  Were you using an earlier version maybe?

**Comment by Moth-Tolias** [comment]
> As per http://www.bay12forums.com/smf/index.php?topic=164123.msg8206358#msg8206358, the issue cannot be replicated with the latest DFHack 0.47.04-r3. Were you using an earlier version maybe?

issue title does specify -r2. i reckon this can be closed.

**Comment by lethosor** [comment]
I would like to confirm whether this is still an issue in r3, because there have not been any changes made directly to dwarfvet since 0.47.03-beta1

**Comment by Krougal** [comment]
This is still an issue in 0.47.05

**Comment by lethosor** [comment]
What version of DFHack are you using (run "help")? I believe there were changes between 0.47.05-r1 and r2.

**Comment by Krougal** [comment]
DFHack version 0.47.05-r2 (development build 0.47.05-r2-158-g10db894d) on x86_64 [build ID: 210821003]
(I pulled latest changes myself)

**Comment by Krougal** [comment]
Seeing it on r3 still. Inaccessible area. My geese start pecking at each other and get minor injuries and then can't go to the hospital and so start spamming.

**Comment by lethosor** [comment]
Dwarfvet hasn't changed since 0.47.05-r2, so that makes sense. Are there any extra setup steps, or are you able to reproduce this on a fresh embark (followed by `enable dwarfvet`)?

**Comment by Krougal** [comment]
This embark was from r2 but being as it crashes frequently since the update I am about to start a new one. I had several fresh embarks on r2 as I did a lot of testing for Dreamfort these last few weeks. Obviously need to build a hospital and get some wounded animals but yeah, it's pretty consistent.

**Comment by lethosor** [comment]
> Obviously need to build a hospital and get some wounded animals but yeah, it's pretty consistent.

Do you have a save handy? Getting to that state might not be easy.

**Comment by Krougal** [comment]
Ok, I'm there now on a fresh save.
https://dffd.bay12games.com/file.php?id=15658
