### ISSUE TITLE
[buildingplan][automaterial] Fix confusing UX interaction on construction placement screens

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#1688]
Filing this as a formal issue so it blocks -r4. I think the current state qualifies as "broken". I didn't catch this earlier since I was testing with 1x1 buildings, where the issue doesn't manifest.

Currently, if planning mode is enabled, buildingplan takes precedence and places a single tile of the construction on {Enter}, regardless of desired size or what settings are set for automaterial (e.g. box select). I think the solution here is:
- for automaterial-managed constructions, let automat handle placement (that is, buildingplan doesn't intercept the {Enter} key
- if planning mode is enabled, automaterial will
  - not show the "Auto Mat-select", "Reselect Type", or "Open Placement" options
  - construct the buildings with filters instead of showing its material selection screen
  - route the building back through buildingplan to let it select materials according to its filter

if buildingplan is enabled and automat is not, we stil have to handle the case where the requested size is > 1x1

**Comment by lethosor** [comment]
Do you have the ability to add issues to projects (in this repo or in scripts)? Not sure how triage permissions affect those.

automaterial has a lot of features that are only somewhat related to its original purpose (selecting construction materials automatically) - if it makes things easier, I would be fine with moving parts of it to buildingplan (but that may also be harder than it's worth - e.g. box-select might integrate with auto-material-selection in a way that I'm not familiar with...)

Regarding https://github.com/DFHack/dfhack/pull/1676#issuecomment-716983902, inter-plugin communication with Lua still makes sense to me. If we were implementing these plugins from scratch, I would probably try to either provide a core API (if there's an approach that even makes sense here) that they could use in some way to avoid conflicts with each other, or just combine all of these features in one plugin, but I think your current plan is definitely easier given the current implementation.

**Comment by myk002** [comment]
I can add PRs to projects in scripts, but not issues or PRs in dfhack.

They definitely overlap in
- placing a bunch of similar constructions quickly
- allowing constructions to be freely designated where the ui won't let you (though automaterial is more strict on constraints than buildingplan is. Automaterial requires that what you're designating is connected to something that will eventually be built)

But I think there is room for both automaterial and buildingplan. Automaterial is about efficiently using what you have. Buildingplan is about specifying what you want eventually.

When they're both enabled, though, the only automaterial features that make sense are box select and hollow. I think it's fine to let that functionality live in automaterial and not move it to buildingplan, though, so automaterial can still provide the feature when buildingplan is not enabled.

What does the develop only tag mean?
