### ISSUE TITLE
[question] How does one detect whether a building name is being edited?

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#1695]
I found a small issue with the new buildingplan code. Actually, the issue was there with the old code too, but now it applies to more buildings. I don't think this needs to block -r4, but I'd like to fix it eventually.

The issue is that buildingplan eats the 's' key on the query screen for planned buildings so the user can't manually unsuspend them prematurely (there are ways to get around this safeguard, but that's a different issue). However, a side effect of this is that users also can't use the 's' key when setting a custom building name.

If the player wants to use an 's' character in a custom name for a planned building, the workaround is to wait until the building is built (and therefore no longer registered with buildingplan), then give it a name.

We could fix this by only intercepting keys if the building is not currently being named, but I don't see where the state for that is kept. There is an `editing_customname` field for `viewscreen_new_regionst.h`, but that does not seem related. Do you have any advice on where this boolean might be stored, and if there is no boolean, how we might detect this state?

I guess we have a fallback of manually detecting {Ctrl}n to turn "editing mode" on and {Enter} to turn it off, but I'd rather go with detecting game state directly if possible.

**Comment by lethosor** [comment]
Good question - the ability to rename buildings in DF is newer than buildingplan.

I would generally check `ui_*` globals for things like this, particularly `ui_sidebar_menus`. In this case,  `ui_sidebar_menus.barracks.in_rename` appears to be the flag used. It's not exactly intuitive, I will admit - pretty much everything in that compound is squad-related, so I suspect Toady is reusing an unrelated flag, but it's entirely possible that he uses something more accurate than `barracks` (which we named). Perhaps this could be extracted into a library function (GUI module?).

**Comment by myk002** [comment]
many thanks! I'll spin up a PR

**Comment by myk002** [comment]
while adding Lua documentation for my "new" Gui function, I discovered Gui::inRenameBuilding() : p Looks like this PR is down to a one-line change.
