### ISSUE TITLE
Buildingplan can't match metal bars as construction materials

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#1699]
See initial investigation in #1689

The issue is that if you try to build something that requires a building_material item, buildingplan never chooses a metal bar, even when it should. For example, if you try to build a track stop in buildingplan and set the material filter to 'metal', it will never choose an iron bar, even if that is the only building material available.

There are two separate bugs that need to be fixed. The first is in [Materials.cpp:516](https://github.com/DFHack/dfhack/blob/develop/library/modules/Materials.cpp#L516) in
`void MaterialInfo::getMatchBits(df::job_item_flags2 &ok, df::job_item_flags2 &mask)`:

`TEST(non_economic, !inorganic || !(ui && vector_get(ui->economic_stone, index)));`

It looks like iron bars should get "non_economic" set.

The second bug is that buildingplan's ItemFilter itself fails to match an iron bar as a valid metal material. I haven't tracked down the root cause for that one yet.

**Comment by myk002** [comment]
so my first though at an approach to this is keeping state in the MaterialInfo about the item type and checking for BAR in the TEST line:
`TEST(non_economic, isOrganic() || (isBoulder() && !isEconomic()) || isBar());`

I'm not a fan of adding state, but I'm not seeing any other obvious route forward here.

**Comment by lethosor** [comment]
I guess I'm not really sure what that `TEST` line is doing - it's setting the `non_economic` flag to a value depending on the material, but what is checking that?

`ui->economic_stone` should only contain stones/ores. My understanding is that metals, while inorganic, are not ores, so I'm not sure why this particular check would have an impact for metals. I'd also be reluctant to add an `isBar()` check since it seems to me like it _should_ only catch bars made of stones/ores, not the metals (but again, I'm not really sure how this works).

**Comment by myk002** [comment]
sorry, I should have explained better. here's the chain:

1. the failing line is [isSuitableMaterial() in buildingplan](https://github.com/DFHack/dfhack/blob/develop/plugins/buildingplan-planner.cpp#L827)
1. which initializes a [MaterialInfo in Job.cpp](https://github.com/DFHack/dfhack/blob/develop/library/modules/Job.cpp#L619)
1. which calculates which flags need to match the job_item spec [in Items.cpp](https://github.com/DFHack/dfhack/blob/develop/library/modules/Items.cpp#L305)
1. which takes us to [getMatchBits() in Materials.cpp](https://github.com/DFHack/dfhack/blob/develop/library/modules/Materials.cpp#L516)

The TEST lines synthesize a job_item flag set for a specified material. Our iron bar gets a flags2 with only `fire_safe` and `magma_safe` set. We know iron bars show up as an option if we build a construction manually, so if the filters in buildings.lua are correct, then iron bars (or, rather, bars in general) *should* get the non_economic flag, even if they are made of an "economic" material like iron.

I put together a PR that shows what I have in mind. I'll attach it in a sec.

**Comment by lethosor** [comment]
Thanks, that helps. It does look like `ui.economic_stone` contains all inorganics, despite only stones being visible in the z-Stone menu, and elements corresponding to at least IRON and GOLD (indices 0 and 1 in my world) are set to `1`. Will follow up in #1700.
