### ISSUE TITLE
Windows 10 error 0xc000007b

### ISSUE THREAD

**Issue by Lo118** [DFHack/dfhack#1707]
like the titel says im not able to open dwarf fortress. i just giving me a error message.

**Comment by lethosor** [comment]
Are you using DFHack? If so, which version did you install?

**Comment by Lo118** [comment]
the newest one. version 0.47.04-3r-windows-64bit

**Comment by lethosor** [comment]
Are you running 32-bit or 64-bit DF?

**Comment by Lo118** [comment]
how can i see that?

**Comment by lethosor** [comment]
What link did you use to download DF?

Inspecting Dwarf Fortress.exe might also provide some information.

**Comment by Lo118** [comment]
32 bit... well then i have to install the 32 bit version of df chaets to?

**Comment by Lo118** [comment]
works thanks

**Comment by lethosor** [comment]
Yeah, they need to match - https://docs.dfhack.org/en/stable/docs/Installing.html covers this and other details. Glad it's working now!
