### ISSUE TITLE
reveal: revflood does not hide walled-off areas

### ISSUE THREAD

**Issue by Nilsolm** [DFHack/dfhack#1719]
I am not sure if this is intended behaviour or not, but the documentation seems to imply that revflood can do that:

> revflood: Hide everything, then reveal tiles with a path to the cursor (useful to make walled-off rooms vanish)

I tested this in multiple saves, but it doesn't appear to work.

DFHack version 0.47.04-r3 (development build 0.47.04-r3-160-gc28bbe26) on x86_64

**Comment by quietust** [comment]
This behavior is intentional, in order to avoid DF bug [#1871](https://www.bay12games.com/dwarves/mantisbt/view.php?id=1871).

**Comment by Nilsolm** [comment]
I see, thanks. I suppose the documentation needs to be adjusted then.

**Comment by lethosor** [comment]
Yeah, the docs here aren't quite correct. Looks like the original wording dates back to a8ab59542. `help revflood` prints the following, which is different but could also be similarly misleading.

> revflood: Hide all, and reveal tiles reachable from the cursor.
Usage:
This command hides the whole map. Then, starting from the cursor,
reveals all accessible tiles. Allows repairing parma-revealed maps.

Open to suggestions, but I should be able to get to this later today
