### ISSUE TITLE
workflow: type_mill: not found.

### ISSUE THREAD

**Issue by calibhaan** [DFHack/dfhack#1722]
I create a Millstone Workshop, I create "mill plants" job, I choose Dimple Cup Plant to mill.
In workflow Constraint I would add a constraint. But I can't, I have an error:
...ant\Dwarf Fortress 0.47.04\hack\lua\plugins\workflow.lua:216: Cannot read field plant_raw.T_material_defs.type_mill: not found.
stack traceback:
        [C]: in metamethod '__index'
        ...ant\Dwarf Fortress 0.47.04\hack\lua\plugins\workflow.lua:216: in local 'handler'
        ...ant\Dwarf Fortress 0.47.04\hack\lua\plugins\workflow.lua:233: in upvalue 'enum_job_outputs'
        ...ant\Dwarf Fortress 0.47.04\hack\lua\plugins\workflow.lua:253: in function 'plugins.workflow.listJobOutputs'
        ...ant\Dwarf Fortress 0.47.04/hack/scripts/gui/workflow.lua:1020: in function <...ant\Dwarf Fortress 0.47.04/hack/scripts/gui/workflow.lua:1019>
        [C]: in field 'on_activate'
        ...IsErrant\Dwarf Fortress 0.47.04\hack\lua\gui\widgets.lua:334: in function 'gui.widgets.check_text_keys'
        (...tail calls...)
        ...\PeridesIsErrant\Dwarf Fortress 0.47.04\hack\lua\gui.lua:484: in function <...\PeridesIsErrant\Dwarf Fortress 0.47.04\hack\lua\gui.lua:479>
        (...tail calls...)
        ...ant\Dwarf Fortress 0.47.04/hack/scripts/gui/workflow.lua:1076: in function <...ant\Dwarf Fortress 0.47.04/hack/scripts/gui/workflow.lua:1070>
        [C]: in ?

It's when I do "Shift +A".
If I create a "advanced Constraint" I can create a dimple cup constraint But how to link it whis the job?

**Comment by quietust** [comment]
In commit 7dfea1f1d4e453b97d5529785701db46360596ce (just before 0.47.04-r1), `plant_raw.material_defs.type_mill` was replaced with `plant_raw.material_defs.type[df.plant_material_def.mill]`.

**Comment by lethosor** [comment]
Good catch - files in `plugins/lua`tend to get missed when breaking changes happen. Definitely worth fixing for the next release. Seems to be the only file still affected by that structures change, in any case.

**Comment by lethosor** [comment]
@calibhaan could you give some more detailed steps to reproduce this issue?

I have built a mill and have dimple cups available, but when I press `alt-w` followed by `A` on a "mill plants" job, I get this screen:
![image](https://user-images.githubusercontent.com/3719547/101722157-9fb6ab00-3a77-11eb-98ab-20837e186095.png)
I have been unable to reproduce your error with any options in this screen, or by pressing `shift-enter` from here and creating a "dimple cup plant" constraint with `p`.

(I *think* I see how to fix your error, although it's a bit complicated, so I'm trying to verify whether the fix actually works in your case.)

**Comment by lethosor** [comment]
I was able to reproduce in a different way, by creating a "mill plants" job, using `gui/workshop-job` to specify a specific plant as the first reagent, then running `:lua require('plugins.workflow').listJobOutputs(job)`. Working on a fix.
