### ISSUE TITLE
deathcause throwing error on animal corpses and body parts

### ISSUE THREAD

**Issue by qeveren** [DFHack/dfhack#1726]
Any time I use deathcause on an animal corpse or body part it returns the following error:

```
E: NoMethodError: undefined method `killer_tg' for #<DFHack::Incident:0x0002f6a5907678>
 hack/scripts/deathcause.rb:31:in `display_death_unit'
 hack/scripts/deathcause.rb:62:in `<top (required)>'
 eval:2:in `load'
 eval:2:in `block in <main>'
 eval:2:in `catch'
 eval:2:in `<main>'
```

Each error differs only in the Incident ID.  The error also seems to occur for any unit (animal or sentient) killed with the **exterminate** command.

**Comment by quietust** [comment]
Commit dfhack/df-structures@55d2da77374bab9f751f1e15d705cc3d174c375a renamed the `killer` field to `criminal`, so this script can't find it anymore (apparently, Ruby has some special logic where `[field]_tg` tries to find `[field]` and automatically resolve its ref-target).

**Comment by qeveren** [comment]
> Try editing deathcause.rb and replacing "killer_tg" with "criminal_tg".

Yup, that works!

**Comment by lethosor** [comment]
All right, I'll go ahead with that fix. Thanks for checking!
