### ISSUE TITLE
Log init file names when processing

### ISSUE THREAD

**Issue by TymurGubayev** [DFHack/dfhack#1776]
dfhack configuration is composed of multiple different init files. It is not always easy to say, which is used and in what order, especially if using something like Lazy Newb Pack. I think it would make all our lives just a tiny bit easier if dfhack would output what file exactly is it currently processing.

It is actually possible to do it on the user-side, like following.

```
lua print('onMapLoad_AwesomeInit.init - begin')

# do stuff

lua print('onMapLoad_AwesomeInit.init - end')
```

But this approach has the downside, the user would have to maintain the logging.

**Comment by lethosor** [comment]
This might be something that could be logged to stderr.log, since command invocations are already logged there.
