### ISSUE TITLE
color-schemes register fails when given a directory path

### ISSUE THREAD

**Issue by RedDeadElite** [DFHack/dfhack#1786]
color-schemes register will fail when given a directory path, but not when given a file path.
For example:
`color-schemes register /data/init/colors/colors.txt` will succeed.
`color-schemes register /data/init/colors/` will fail.

It gives the following error:
...-fortress/0.47.04_mine/df/hack/scripts/color-schemes.lua:119: attempt to perform arithmetic on a nil value (local 'e')
stack traceback:
	...-fortress/0.47.04_mine/df/hack/scripts/color-schemes.lua:119: in upvalue 'listdir'
	...-fortress/0.47.04_mine/df/hack/scripts/color-schemes.lua:352: in upvalue 'register_dir'
	...-fortress/0.47.04_mine/df/hack/scripts/color-schemes.lua:375: in global 'register'
	...-fortress/0.47.04_mine/df/hack/scripts/color-schemes.lua:871: in method '_action'
	...-fortress/0.47.04_mine/df/hack/scripts/color-schemes.lua:785: in function <...-fortress/0.47.04_mine/df/hack/scripts/color-schemes.lua:772>
	(...tail calls...)
	...-fortress/0.47.04_mine/df/hack/scripts/color-schemes.lua:818: in method 'parse'
	...-fortress/0.47.04_mine/df/hack/scripts/color-schemes.lua:894: in local 'script_code'
	./hack/lua/dfhack.lua:680: in function 'dfhack.run_script_with_env'
	(...tail calls...)

**Comment by lethosor** [comment]
What happens if you leave off the leading `/`? Typically that makes it an absolute path, but I'm not sure how this particular script handles that.

**Comment by RedDeadElite** [comment]
Hmm. Giving variable `local e` (line 118) the length of DF's root directory (`string.len(ROOT)`) seems to have fixed it.

**Comment by lethosor** [comment]
What OS are you using?

**Comment by RedDeadElite** [comment]
> What OS are you using?

Ubuntu 18.04.5

To answer your other question: leaving out the leading `/` gives the same error.

**Comment by lethosor** [comment]
I can't reproduce this (Ubuntu 20.10) with any of these:
```
color-schemes register /dfhack-config/
color-schemes register /dfhack-config
color-schemes register dfhack-config
```

What DFHack version are you using? Does your installation path contain any symlinks? Is DF installed under your home folder or somewhere else?

**Comment by RedDeadElite** [comment]
>     * Does your installation path contain any special (non-ASCII) characters?

I changed the hyphen in a folder name in the installation path to an underscore and that seems to have fixed the issue.
I renamed 'dwarf-fortress' to 'dwarf_fortress'.

As for your other points:

- 0.47.04-r3
I also tried a fresh install of DF with corresponding DFHack 0.47.05-r1.
- Yes, it was installed under '/home/user/Games/dwarf-fortress/0.47.04_mine/df/'
- No symlinks

**Comment by lethosor** [comment]
Oh! Hyphens have a special meaning in lua patterns (roughly equivalent to `*?` in perl-style regexes, I believe). We probably just want a raw string comparison there instead of match(). Thanks!

**Comment by lethosor** [comment]
This version of the script should fix the issue: https://github.com/DFHack/scripts/blob/83e88c73d7a51063489aaa72094928db9619aca2/color-schemes.lua (let me know if not)

**Comment by RedDeadElite** [comment]
> This version of the script should fix the issue: https://github.com/DFHack/scripts/blob/83e88c73d7a51063489aaa72094928db9619aca2/color-schemes.lua (let me know if not)

It works; thank you!
