### ISSUE TITLE
No documentation for dfhack.run_command

### ISSUE THREAD

**Issue by gaberau** [DFHack/dfhack#1800]
Searching for the documentation for the dfhack.run_command Lua function reveals nothing, as seen here https://docs.dfhack.org/en/stable/search.html?q=dfhack.run_command%28%29&check_keywords=yes&area=default. The changelogs states that documentation has been created, but nothing exists.

**Comment by lethosor** [comment]
It's on https://docs.dfhack.org/en/stable/docs/Lua%20API.html and the search you linked brings up that page ("DFHack Lua API") for me.

**Comment by gaberau** [comment]
Yep, you are totally right. I must have completely missed it. I apologize for wasting your time.
