### ISSUE TITLE
gui/liquids displays "water" when the cursor is over magma/lava

### ISSUE THREAD

**Issue by Bumber64** [DFHack/dfhack#1808]
gui/liquids displays an indicator that "water" is present on the selected tile, even when the fluid is magma or lava. It should instead display "magma" or "lava" where appropriate. Magma is considered "lava" when the tile's "subterranean" flag is false.

**Comment by lethosor** [comment]
This looks like it should already be handled here, so this could be a possible structures issue: https://github.com/DFHack/scripts/blob/8200539a851623bfc8a049390633a5fa3cc55b84/gui/liquids.lua#L133-L140

**Comment by myk002** [comment]
the new gui/liquids doesn't display existing liquid since it's already displayed by the vanilla "mousequery" area
