### ISSUE TITLE
Ability to automatically re-designate tiles cancelled due to warm or damp stone

### ISSUE THREAD

**Issue by Bumber64** [DFHack/dfhack#1812]
If possible, develop a plugin that automatically re-designates tiles cancelled due to warm or damp stone. Hopefully it's possible to intercept the cancellation before it wipes info about the designation type.

**Comment by lethosor** [comment]
Thanks for this - I'm surprised that it doesn't seem to be on here already. From what I remember, the announcement is fairly easy to detect, but happens after the designation is cleared. Restoring designations isn't too hard, but tracking them to allow that might be slow.

**Comment by BenLubar** [comment]
You might have to parse the announcement to get the job type, but it should have the coordinate in the `report` struct.

**Comment by myk002** [comment]
An idea we were throwing around on discord: detect when a dig job is nearly complete and pre-unhide adjacent tiles. This would avoid the announcement and undesignation

**Comment by Bumber64** [comment]
Implemented by #4403
