### ISSUE TITLE
`enable dwarfvet` doesn't work

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#1825]
When dwarfvet is disabled, `enable dwarfvet` does not set up the tick handler that `dwarfvet enable` sets up here: https://github.com/DFHack/dfhack/blob/9d723dc2566803d563e40629413c9321a4992647/plugins/dwarfvet.cpp#L797-L799

**Comment by myk002** [comment]
Fixed in https://github.com/DFHack/dfhack/pull/3589
