### ISSUE TITLE
More info on petitions screen

### ISSUE THREAD

**Issue by Bumber64** [DFHack/dfhack#1834]
More information about those petitioning for residency. Info on active guildhall/temple agreements.

The Steam update might fix this, but I'm suggesting this just in case.

**Comment by Bumber64** [comment]
Is this fully implemented as of 0.47.05-r6?

**Comment by myk002** [comment]
I believe it is.

**Comment by lethosor** [comment]
https://github.com/DFHack/scripts/pull/398 ?

**Comment by myk002** [comment]
And DFHack/scripts#391 and DFHack/scripts#323
