### ISSUE TITLE
warn-starving.lua: Add option to ignore the insane

### ISSUE THREAD

**Issue by Bumber64** [DFHack/dfhack#1836]
Simply add an option to ignore the insane to the warn-starving script. There's generally not much that can be done about them, so the warnings aren't useful to most players.

**Comment by quietust** [comment]
Is there ever a reason to _not_ exclude insane dwarves? If not, it would be simpler to just unconditionally ignore them.

**Comment by Bumber64** [comment]
Somebody might want to save them using a different script or something.

**Comment by lethosor** [comment]
Looks like a duplicate of #1809
