### ISSUE TITLE
reloading a plugin does not reload associated lua code

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#1845]
While working on the blueprint plugin, I made modifications to `plugins/lua/blueprint.lua`. I ran `ninja install` to install the modified lua code and ran `reload blueprint`. I expected that the new lua code would be used the next time I ran `blueprint`, but it was not. A workaround is to restart dfhack, which isn't terrible, but it does slow down development compared to what a quick `reload blueprint` should be able to do.

Inside of `Plugin::unload()` in `PluginManager.cpp`, `reset_lua()` is called, but it does not appear to allow the lua code to reload.
https://github.com/DFHack/dfhack/blob/develop/library/PluginManager.cpp#L428

**Comment by lethosor** [comment]
FYI: `reload("plugins.blueprint")` from Lua should work (not great, but it's faster than restarting DF)

**Comment by myk002** [comment]
that does help. especially when it's just the lua that I need reloaded. thanks for the tip!

**Comment by myk002** [comment]
Is this as easy as invoking `:lua reload('plugins.%s')` from the `reload` built-in code?

**Comment by warmist** [comment]
we should add `package.loaded[<package_name>]=nil` to reset_lua code (or somewhere nearby)

**Comment by lethosor** [comment]
Yeah, I would rather try `reload()` than clearing the table if `reload()` is able to keep state.

**Comment by myk002** [comment]
ok, i'm fine with making reloading the lua state a separate step.

**Comment by lethosor** [comment]
Hm? I just meant that if we add Lua logic to the `reload` command, I would prefer that that logic be `reload()` as opposed to `package.loaded[x]=nil`.

**Comment by myk002** [comment]
I understood [Warmist's comment](#issuecomment-1328209289) to mean that we intentionally do not reload the lua side when we reload a plugin in an attempt to save lua-side state.

**Comment by lethosor** [comment]
I took it to mean we don't _clear_ the state, which `package.loaded[x]=nil` does. I don't know if `reload()` also clears the state. From looking at the current implementation, I don't think it does, but I should probably test it:

https://github.com/DFHack/dfhack/blob/7625dc132ea4d0b0a83c2ee2fcbef9336373d6a9/library/lua/dfhack.lua#L128-L137
