### ISSUE TITLE
autofarm is not enabled on restart

### ISSUE THREAD

**Issue by aljohnston112** [DFHack/dfhack#1874]

**Comment by lethosor** [comment]
Could you be more specific? What commands are you running? What do you mean by "on restart" (unloading a save or restarting DF entirely)?

**Comment by lethosor** [comment]
This could still use more details, but I suspect enabling autofarm in an [init file](https://docs.dfhack.org/en/stable/docs/Core.html#init-files) would do the trick.

**Comment by ab9rf** [comment]
`autofarm` does not store any of its configuration state persistently. You have to reenable it (and reconfigure it, if you change any of its settings) after loading a save. I recommend using an init file.

**Comment by myk002** [comment]
Here is an example of how to use an init file to keep `autofarm` running across reloads:
https://github.com/DFHack/dfhack/blob/develop/data/examples/init/onMapLoad_dreamfort.init#L28
