### ISSUE TITLE
Advfort: Starting a reaction at a workshop while not on the centre tile makes the job timer start at -1

### ISSUE THREAD

**Issue by wolfboyft** [DFHack/dfhack#1880]
Starting a reaction at a workshop while not on the centre tile (or more likely the workshop's specific work-here spot (custom workshops and all that)) makes the job timer start at -1, so you need to step time to start the job.

**Comment by warmist** [comment]
This is an interesting bug.

IIRC the -1 is "correct". I.e. advfort sets it to -1 for df to fill out the correct value when starting a job. However it probably fails to start the job as player is in a wrong spot. I'll investigate further...

**Comment by warmist** [comment]
probably fixed in https://github.com/DFHack/scripts/pull/298
