### ISSUE TITLE
Move string.split() to core library

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#1888]
`string.split()` is currently [added to the `string` global](https://github.com/DFHack/scripts/blob/13fbb5a84d59d43bf68ce190726192484d52e00a/gui/load-screen.lua#L105) by `gui/load-screen`.  This affects any Lua code run after this script is run. There are several scripts that rely on this function being defined, and possibly more that are out of our control:
* https://github.com/DFHack/scripts/blob/c453a53bce292caea2e608ac86942dae4d92e73f/color-schemes.lua#L644
* https://github.com/DFHack/scripts/blob/c453a53bce292caea2e608ac86942dae4d92e73f/gui/settings-manager.lua#L35

Since this script is run in `dfhack.init-example`, this is not an issue in many cases. However, it did break Buildmaster in #1791 (after the test image was updated?) since that test environment uses an empty `dfhack.init` and does not run `gui/load-screen` at all, leaving `string.split()` undefined.

`gui/load-screen`'s implementation of `split()` fails to handle some edge cases, so I would recommend using the one defined in [utils.lua](https://github.com/DFHack/dfhack/blob/0297a5b1b8ea5492c99cbd214b37dcfd97f16bbe/library/lua/utils.lua#L485) instead (possibly replacing `split_string()` with a stub calling `string.split()`).

Another useful improvement would be to expose the `plain` argument of `string.find()`, e.g. as `string.split(str, sep, plain)`. `utils.split_string()` always interprets the separator as a pattern, which requires escaping characters like `.` in the separator (and this is the _only_ separator used in gui/load-screen, incidentally).

Inspired by #1885

**Comment by myk002** [comment]
I should note that an alternative to supporting the `plain` parameter is just to require that all callers escape magic characters. in-tree, this only affects `gui/load-screen`. From the original comment, I take it that supporting the `plain` param is preferred, but I just wanted to make sure the options were documented.

**Comment by lethosor** [comment]
At a high level, I'm not too concerned about breaking compatibility, since `split()` isn't a standard library function or one that we've documented. If the only breakage necessary is internal to `gui/load-screen`, that's even better, because its implementation of split() is very error-prone. It's hard to know for sure what external tools this might affect, but I _suspect_ most uses of split() don't intend to use a pattern as a delimeter. I would say that a changelog entry is sufficient.

I think the plan looks good! I was about to say that (1) could be pushed directly, but you beat me to it with https://github.com/DFHack/scripts/pull/305. (2) can be tested locally if you remove `gui/load-screen` from dfhack.init. Otherwise I think this all makes sense. Thanks for putting in the thought to make this happen!

**Comment by myk002** [comment]
Thanks! Expect a few PRs in short order (I can push DFHack/scripts#305). We'll also need to make sure the scripts submodule is updated between (3) and (4) so the tree is never in a broken state.

**Comment by lethosor** [comment]
FYI, I took care of enabling the test in https://github.com/DFHack/dfhack/commit/da3b522061ab8abdb2e6b730ebb453df43b13c8c
