### ISSUE TITLE
Tests should run with an empty dfhack.init

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#1895]
This would avoid issues such as #1888 

One possible counterargument: running `dfhack.init-example` in CI can help catch issues with tools included in it, and users are likely to see these issues if CI doesn't catch them. Should we have a test that runs `dfhack.init-example`? There isn't really any "undo" functionality for init scripts, so we might need to run it in a standalone DF session, and we don't really have support for that at the moment (although it would be possible).

**Comment by myk002** [comment]
this is a good idea -- run two test actions, one with the default init scripts and one with all config commented out.
