### ISSUE TITLE
Trouble building source due to JSON files not being loaded

### ISSUE THREAD

**Issue by aljohnston112** [DFHack/dfhack#1899]
I am trying to run generate-MSVC-all.bat.

I have installed Visual Studio 2017 with "Desktop development with C++" including "Just-In-Time debugger", "VC++ 2017 version v14.16 latest v141 tools", "C++ profiling tools", "Windows 10 SDK (10.0.17763.0)", "Visual C++ tools for CMake", "Visual C++ ATL for x86 and x64", "Test Adapter for Boost.Test", "Test Adapter for Google Test", "Windows XP support for C++", and "VC++ 2015.3 v14.00 (v140) toolset for desktop". 

The output I get when running the batch file and the CMakeOutput.log I get are attached
[CMakeOutput.log](https://github.com/DFHack/dfhack/files/6766150/CMakeOutput.log)
[cmdOutput.txt](https://github.com/DFHack/dfhack/files/6766151/cmdOutput.txt)

**Comment by aljohnston112** [comment]
I ended up pasting files from http://sapling.stanford.edu/~manolis/flecsi/src/CMake/Templates/MSBuild/FlagTables/ to the right directory

**Comment by lethosor** [comment]
These files are installed by CMake - it's not anything we can change on the DFHack side, as far as I can tell. Perhaps reinstalling CMake would help?

**Comment by aljohnston112** [comment]
CMake.portable appears to have been the issue

**Comment by myk002** [comment]
closing solved issue
