### ISSUE TITLE
Fruits are not detected in autofarm. 

### ISSUE THREAD

**Issue by Quoose** [DFHack/dfhack#1902]
I'm running dfhack-0.47.05-r1-Windows-64bit and I have found that farm plot fruits are not being detected by autofarm and just get farmed unlimited. Specifically in my example: Bilberries, Blueberries, Raspberries and Grapes. Strawberries seem to work. 

I remember also encoutering this problem running Linux, however cannot say now what version I was running.

**Comment by ab9rf** [comment]
Both bilberries and raspberries have the `[GROWTH_HAS_SEED]` and `[GROWTH_DROPS_OFF]` tags, but strawberries instead have `[GROWTH_DROPS_OFF_NO_CLOUD]`. I'm sure this is somehow relevant, but I don't know how. There are several other differences in the raws between strawberries (which have been in DF a long time) and these other fruits (which are much newer).

Sorting this out is going to require spending some time digging through the internal datastructures to figure out why bilberries and raspberries (and the others mentioned above) aren't being identified as "plantable plants" by the `find_plantable_plants` function in `autofarm.cpp`. There's a bunch of possible reasons and I don't which is the cause at this point.

**Comment by ab9rf** [comment]
On researching this further I'm increasingly confused by the comment that they're "farmed unlimited". `autofarm` ought not to schedule planting of a seed that it doesn't recognize as the seed of a plantable plant. Are you saying that it *is* scheduling raspberries or bilberries into fields, and simply not cutting them off when their products go over threshold? Or is it not managing those farm fields at all (which it shouldn't do at all: if `autofarm` finds no plantable seeds it sets all farms to fallow).

A save exhibiting the behavior in question would be extremely valuable to my investigation.

**Comment by ab9rf** [comment]
I now have a working theory. The threshold counts, used to determine when to stop planting something, are done by enumerating `world->items.other[df::items_other_id::PLANT]`. My guess (although I haven't actually fired up a world and gyrated through long enough to test this) is that while harvested strawberries are on this item list, harvested bilberries/raspberries/grapes are not; they're instead most likely on `world->items.other[df::items_other_id::PLANT_GROWTH]`.

I can fix this either by using a different item list (such as `df::items_other_id::ANY_GOOD_FOOD`) that has both `PLANT` and `PLANT_GROWTH` on it, or simply by walking both `PLANT` and `PLANT_GROWTH`. Of course, some plants have more than one growth, and so this may have "unexpected" side effects.

**Comment by ab9rf** [comment]
I have confirmed that edible raspberry fruits are, in fact, plant growths, and not plants, and that's why it doesn't count them for determining when thresholds are reached. The solution is going to be to scan both the plant and plant growth subvectors.

Pull request will be forthcoming soon.

**Comment by Quoose** [comment]
Sorry. Yes. It does

> 
> 
> On researching this further I'm increasingly confused by the comment that they're "farmed unlimited". `autofarm` ought not to schedule planting of a seed that it doesn't recognize as the seed of a plantable plant. Are you saying that it _is_ scheduling raspberries or bilberries into fields, and simply not cutting them off when their products go over threshold? Or is it not managing those farm fields at all (which it shouldn't do at all: if `autofarm` finds no plantable seeds it sets all farms to fallow).
> 
> A save exhibiting the behavior in question would be extremely valuable to my investigation.

Yes. The fruits such as bilberry, grape and raspberry are being planted however the count that detects how many there are stays as zero.

**Comment by ab9rf** [comment]
> Is this save still relevant to your investigation considering there is now a pull request?
> I had assumed it was stock behaviour.

At this time, I'm satisfied that I've identified the issue and a resolution.
