### ISSUE TITLE
Feature request: allow specifying material in the tailor plugin

### ISSUE THREAD

**Issue by TymurGubayev** [DFHack/dfhack#1911]
I'd like to have tailor enabled since I find it nice, but I don't want it to use leather.

**Comment by ab9rf** [comment]
The default order is silk, cloth, yarn, leather. I had in mind to make this end-user configurable (as well as the hold-aside limit of ten) but never got around to it.

It's not a terribly hard change to make. I'll give it some serious thought.

**Comment by ab9rf** [comment]
The PR referenced above allows you to set the list of materials to use. With this change, if you don't want it to use leather, the command `tailor materials silk cloth yarn` (or whatever other order you like) and it will only use those materials.

Please note that the current version doesn't persist this setting in the save; you'll have to reset it whenever you reload. I suggest putting your preferred setting in your dfhack init file.
