### ISSUE TITLE
quickfort/blueprint isn't working with custom stockpile

### ISSUE THREAD

**Issue by arzyu** [DFHack/dfhack#1931]
Hi, I have a 3x3 stockpile with custom settings (with animal+food enabled). When using the `blueprint` command, it generated `test-place.csv` with contents:

```
#place
`,`,`,#
`,`,`,#
`,`,`,#
```
But it didn't work when applying by quickfort.

I noticed that quickfort/blueprint is still under development. So is this function not implemented yet?

Here are my steps:
```
[DFHack]# blueprint 3 3 test place
Generated blueprint file(s):
  blueprints/test-place.csv
[DFHack]# quickfort list
reading quickfort configuration from "dfhack-config/quickfort/quickfort.txt"
1) test-place.csv (place)
  138 library blueprints not shown (use `quickfort list --library` to see them)
[DFHack]# quickfort run -v 1
boundary map (after edge detection):
boundary map (after chunking):
boundary map (after expansion):
run test-place.csv successfully completed
  Keystrokes sent: 0
  Stockpiles designated: 0
```

**Comment by myk002** [comment]
The blueprint plugin doesn't handle multi-type stockpiles yet (see https://github.com/DFHack/dfhack/issues/1842 for the implementation plan), but if you create the blueprint manually, quickfort can create multi-type stockpiles just fine. The blueprint should look something like this:
```
#place
af(3x3)
```

**Comment by arzyu** [comment]
Thanks for replying so quickly. I will write the blueprint manually.
