### ISSUE TITLE
"seedwatch all" doesn't watch all seed types

### ISSUE THREAD

**Issue by ab9rf** [DFHack/dfhack#1941]
`seedwatch all` only covers the seed types that are in `seedwatch`'s hardcoded abbreviation list (whether or not they're in the game). Arguably, this command should match all plants in the game that have seeds, whether or not `seedwatch` has an abbreviation for them.

In addition, the automatic enabling/disabling of cooking plants based on seed supply only works for plants on the hardcoded abbreviation list.

**Comment by Krougal** [comment]
These are the "legacy" plants is why.  It was never updated to include the new ones.
+1

**Comment by myk002** [comment]
@ab9rf this seems very related to the autofarm code. Could I possibly assign this one to you?

**Comment by ab9rf** [comment]
I'd be likely to rewrite it entirely if assigned to me, but that might not be a bad idea anyway. I'll grab it for now.

**Comment by myk002** [comment]
Thanks!
