### ISSUE TITLE
unknown job 242 spam in dfhack window

### ISSUE THREAD

**Issue by henkmet** [DFHack/dfhack#1994]
My captain of the guard is interrogating and this seems to cause 'unknown job 242' spam repeatedly. Did the job number change?
I'm using dfhack-twbt 0.47.05-10 from archlinux aur

**Comment by lethosor** [comment]
What DFHack version is that? You can run "help" in the DFHack console to check

**Comment by henkmet** [comment]
That's 0.47.05-r1

**Comment by quietust** [comment]
Job types 241-243 were identified back in May 2020 in DFHack/df-structures@0231cce29e6014367c0af122aed4f7ba21292b2b (and applied to DFHack in 947d0db182832c931e26b30eb13daba94219a1cc), so that _should_ have been present since DFHack 0.47.0**4**-r2

**Comment by quietust** [comment]
It appears that while LaborManager was updated to recognize jobs 241-243, AutoHauler and AutoLabor were never updated accordingly. They use pretty much the exact same code (it looks like one of them was copy/pasted to the others at some point), so fixing it should be straightforward.

**Comment by myk002** [comment]
Seems related to #1601

**Comment by myk002** [comment]
Fix will be to add "OTHER" three times to the end of the big array in autolabor.cpp

**Comment by ab9rf** [comment]
Working on this now. Will also fix autohauler because it has the same issue. I've been putting off refactoring this smelly mass of duplicated code because DF 2022 will almost certainly make these three plugins obsolete
