### ISSUE TITLE
Mention Arch Linux packages in README

### ISSUE THREAD

**Issue by Daenyth** [DFHack/dfhack#20]
For Arch Linux users, dfhack is packaged in the [AUR](http://archlinux-gaming.org/issues/88), and has binaries available in the [Arch-Games project](http://archlinux-gaming.org)

**Comment by lethosor** [comment]
Not quite sure why this got closed originally (GitHub evidently lost track of who closed it), but since the AUR package is still around (!), I added it to the installation page of the docs.
