### ISSUE TITLE
Firestarter script not working

### ISSUE THREAD

**Issue by Paaaad** [DFHack/dfhack#2001]
Entry "firestarter" returns error:

> Cannot write field fire.temp_unk2: not found.
stack traceback:
        [C]: in ?
        [C]: in ?
        [C]: in method 'insert'
        ...wner\Downloads\df_47_05_win/hack/scripts/firestarter.lua:18: in local 'script_code'
        C:\Users\Owner\Downloads\df_47_05_win\hack\lua\dfhack.lua:775: in function 'dfhack.run_script_with_env'
        (...tail calls...)

Version is 0.47.05-r3

**Comment by myk002** [comment]
It looks like some fields have been identified since this script was written. See https://github.com/DFHack/df-structures/blob/b1637f68e920dcb4a68a1e727a5ea5bf193b131f/df.world.xml#L539

**Comment by lethosor** [comment]
This change should fix it: https://github.com/DFHack/scripts/pull/352/files

@Paaaad let me know if it works for you

**Comment by Paaaad** [comment]
Fire started with no error messages at all. Looks like those changes did the trick. @lethosor
