### ISSUE TITLE
Tailor plugin crashes the game

### ISSUE THREAD

**Issue by HunterZ** [DFHack/dfhack#2006]
Using PeridexisErrant's Starter Pack 0.47.05-r06, which comes with DFHack version 0.47.05-r3 (release) on x86_64 and Dwarf Fortress 0.47.05 x64.

I enabled the tailor plugin, but it seemed to never do anything.

I then tried increasing bookkeeper accuracy (`n` then highlight bookkeeper then `s`) from the lowest setting to any higher setting, and the game consistently crashes within a few minutes.

Attaching a debugger indicates that the tailor plugin caused an out of range exception:
![image](https://user-images.githubusercontent.com/108939/152652918-26e58bdd-0c1a-430e-8b60-affee9771436.png)

**Comment by myk002** [comment]
The tailor plugin will normally not do anything until clothing starts to wear out and there aren't enough extra clothes lying around, so it might be expected to do nothing, depending on the conditions of your fort. The crash, however, needs investigation.

**Comment by myk002** [comment]
Could you possibly upload your savegame? It would help in reproducing the problem.

**Comment by HunterZ** [comment]
Need details on how I'd go about doing that, but honestly my game has progressed so far beyond that point that my current save may not be any help either. It would probably be better for me to start a new world and try to replicate it again.

**Comment by myk002** [comment]
You can upload savegames to https://dffd.bay12games.com/category.php?id=20
Any cloud storage provider (e.g Google Drive) would work too, as long as you give the file public download permissions. Compress the data/save/region1 folder and upload it.

**Comment by myk002** [comment]
@HunterZ could you reopen this bug if you see this again?
