### ISSUE TITLE
`stocks show` search doesn't match if searched term is in the ellipsised part

### ISSUE THREAD

**Issue by rubybrowncoat** [DFHack/dfhack#2015]
Searching items with long names don't match when the part I'm searching isn't being displayed on the screen.

For example and clarity, I have several `bone hand-cannon shot` items from various animals and creatures and if I'm searching for `bone hand` the screen shows the thousands of them I actually have but if I'm searching for `shot` or `bone shot` it only shows the few lucky enough to have short animal prefixes (like `pig`) because they actually fit the screen without getting shortened with the ellipsis.

I'm not sure if this is a known limitation or a bug, so I'm mentioning it just in case.

**Comment by myk002** [comment]
Potential fix: add full label (before it is truncated by the call to `pad_string()`) to the keywords string. This should allow the `ListColumn` search implementation to find the tokens in the truncated part
