### ISSUE TITLE
Files in raw/init.d/ won't run in arena mode

### ISSUE THREAD

**Issue by wolfboyft** [DFHack/dfhack#2039]
(also, why is it called init.d?)

**Comment by myk002** [comment]
The "init" means "run on initialization" and the ".d" means "directory". On Unix systems, the /etc/init.d directory is where all the system service startup scripts are located.

In general, a directory that ends in ".d" has the semantics of "the files in this directory each have a different owner but anything that is in this directory will get detected and used".

**Comment by wolfboyft** [comment]
Okay, makes sense. Also, bug label? Since I don't have the perms.

**Comment by warmist** [comment]
same thing #1266

**Comment by lethosor** [comment]
Yep. Duplicate of #1266
