### ISSUE TITLE
allow dfhack.item.moveToGround to affect building clutter

### ISSUE THREAD

**Issue by Tachytaenius** [DFHack/dfhack#2040]
This is because the function detachItem which needs to return true for moveToGround will return false when an item has anbuilding holder general ref.
Also, do all specific refs really need to prevent detachItem...? It seems prohibitive (at the very least is giving me modding troubles lol (but if there's a good reason then I'll of course just work around it))

**Comment by myk002** [comment]
It's likely that specific refs just weren't sufficiently understood by the author and are unhandled. It might be possible to implement, though. Is there a reference somewhere for how specific refs work and what the implications would be for removing (or ignoring) them in this function?

**Comment by Bumber64** [comment]
Can be closed due to #4319
