### ISSUE TITLE
Revflood removes tree-chopping designations

### ISSUE THREAD

**Issue by wolfboyft** [DFHack/dfhack#2047]

**Comment by myk002** [comment]
Does it remove all dig designations, or just trees?

**Comment by wolfboyft** [comment]
Channels on the surface too. I believe it's the lit flag, probably.

**Comment by myk002** [comment]
I could not reproduce this. I tried designating trees for chopping and surface tiles for channeling. then I ran `revflood`. the channels and trees stayed designated. what am I doing differently?

**Comment by myk002** [comment]
Closing as not reproducible -- please reopen if you have a savegame that can reproduce this.
