### ISSUE TITLE
add-spatter plugin crashes the game on OSX

### ISSUE THREAD

**Issue by fricy** [DFHack/dfhack#205]
When loading an existing savegame or generating a new game with raws that use the add-spatter plugin the game crashes. After deleting the plugin the crash disappears. Vanilla does not crash.
Tested with Masterwork mod v.3d and DfHack r3 Darwin - compiled on 2013. 03. 15 running on OSX 10.7.5.

Crashlog: http://pastebin.com/Ppnz7z49

**Comment by lethosor** [comment]
Can you provide a series of steps that reproduces this? I certainly haven't seen this when creating new worlds, so I'm unsure how to make the problem occur.

**Comment by lethosor** [comment]
I'm suddenly getting an add-spatter crash with http://dffd.bay12games.com/file.php?id=9468 or http://dffd.bay12games.com/file.php?id=9469 in DFHack 0.40.24-r2 (the save has never had problems in earlier versions and doesn't appear to use any SPATTER_ADD reactions).

**Comment by lethosor** [comment]
It seems to apply to any save, actually.

**Comment by fricy** [comment]
Fix confirmed with 34.11-r5 and Masterwork 6.2 raws. Thx!
