### ISSUE TITLE
Planning Mode Crash

### ISSUE THREAD

**Issue by iHoosy** [DFHack/dfhack#2078]
Hi - git newbie here so apologies in advance if there are any faux pas.

I've only been playing for a couple of days but I've had two crashes when using planning mode, one was placing up/down stairs and the other was placing a door.

The game didn't freeze or hang, it just closed. Playing on v 0.47.05 from the PyLNP.

**Comment by myk002** [comment]
Is the crash repeatable? Does it always crash when you do something specific?

**Comment by iHoosy** [comment]
> It's not consistent, though both times the game closed (Not crashed, just close to desktop), it was when I was placing things on the same Z level, though I believe that's just coincidence as it's where i've been building. I had no filters set on material, and both times it happened it was as I hit enter.

The first time it happened I had only used the planner to queue 2 things, both of them up/down stairs. The game closed as I hit enter on the 2nd stair, though when I was doing the doors on a separate occasion, it closed after 6 or so planned builds.

The only changes to the LNP launcher are enabling Vettlingr 32x, and changing the resolution size. Though I stretch the game to fit my window.

**Comment by myk002** [comment]
Could you possibly compress your game save (the `data/save/region1` directory) and upload it to [dffd](https://dffd.bay12games.com/category.php?id=20) or some other cloud storage and post the link here? I might need your setup in order to reproduce the crash.

**Comment by myk002** [comment]
I see there may be crashes related to the tileset (e.g. https://www.reddit.com/r/dwarffortress/comments/dcd5mz/vettligr_october_update/f29ahba?utm_medium=android_app&utm_source=share&context=3). If you use a different tileset, do you still see crashes?

**Comment by iHoosy** [comment]
Hi, sorry I haven't had much time to play since making the post, and I still don't have my email activation from that map uploading website. I'll try a different tileset and see how it goes, the next time I play. 

This is the log from the last time it crashed, only 2 lines in it but it may indicate an issue with the tileset:
"Running PyLNP 0.14a (OS: win, Compiled: True)
INFO: Read installed graphics (Vettlingr) from log"

Thanks for looking into this.

**Comment by lethosor** [comment]
If it does still occur with a different tileset, we would need a save to diagnose further. Those two lines don't indicate any problems - they just tell you what tileset you're using.

**Comment by myk002** [comment]
@iHoosy Please reopen this bug if/when this happens again.
