### ISSUE TITLE
Add cprobe capabilities to cursecheck

### ISSUE THREAD

**Issue by GuilhermeAbraham** [DFHack/dfhack#2087]
Hi,

I was using cursecheck and got the name of the cursed create, but still can't find it, so I through it would be great to have some of the cprobe capabilities on that plugin so I could get the creature ID and teleport it under my cursor.

I was checking the code and both plugins loop trough all creatures, so what I am suggesting is adding 1 more parameter on cursecheck to print that line I extracted from probe:
`out.print("Creature %d, race %d (%x), civ %d (%x)\n", unit->id, unit->race, unit->race, unit->civ_id, unit->civ_id);`

You think this would be possible? Do you see any problem with it?
If you need contribution on the coding, I am available, but would need a few directions on any info on how to contribute.

Thanks in advance.

**Comment by lethosor** [comment]
I think that would be fine. We probably don't need the hexadecimal versions of the IDs (`%x`) for cursecheck, so it could be shortened a bit.

We'd be happy to take a PR for this. You can set up a fork and push from your local machine, or make the change in a fork in GitHub's web-based editor. We have some documentation on contributing here: https://docs.dfhack.org/en/latest/docs/Contributing.html
