### ISSUE TITLE
Quickfort can't place constructions over natural ramps

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#2116]
From TrufflePump on IRC via softmoth on discord:

[20:48] <TrufflePump> I'm using dfhack and quickfort. I'm trying to build a ramp over a dug ramp. The same a building a floor over a dug floor. I can do it in game but not via QF.

analysis from myk002:

This looks like faulty "is_valid_tile" logic in scripts/internal/quickfort/build.lua.

**Comment by myk002** [comment]
We can fix this by moving the RAMP clause from `is_valid_tile_machine` to `is_valid_tile_has_space` IF all of the following building types can be built over natural ramps:

- bridges
- water wheels
- horizontal axels
- supports

**Comment by quietust** [comment]
Ramps can only intersect with Bridges if they would be visible while the bridge is Raised/Retracted (i.e. they cannot be beneath the anchor point of a Drawbridge.

They cannot intersect with Water Wheels, Axles, or Supports at all.

**Comment by myk002** [comment]
Ack. I'll fix the logic for constructions and bridges, leaving water wheels, horizontal axles, and supports as they are.
