### ISSUE TITLE
User init files build on defaults instead of overwriting them

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#2120]
I wonder about our current guidance to copy the `dfhack.init-example` file to `dfhack.init` and make changes. Should we instead be creating a standard default baseline that is overwritten on upgrade (e.g. `hack/data/init/dfhack.init`) and instruct people to create their personal files in addition to (as opposed to the current "instead of") the defaults?

This would go for `onLoad.init` and `onMapLoad.init` too.  The defaults would set up the "baseline DFHack experience" and users would augment.

On the other hand, if we set something up in the baseline files and users don't want it, there is no way to turn some things off. For example, once `fix/blood-del` runs, there is no undoing what it did.

**Comment by wolfboyft** [comment]
I'm all for the change. RE commenting things out from dfhack.init, we could leave that as is for those few cases and have a message on update that says what minor things you should do to maintain your directory?

**Comment by wolfboyft** [comment]
What if user inits were run at the start of dfhack.init and variables could be set within the user script to disable dfhack.init things from happening?

**Comment by lethosor** [comment]
One benefit of a "baseline" init file is that it can be upgraded relatively easily, without people having to manually merge changes they've made to dfhack.init and changes we've made.

As for a way to disable the defaults, maybe we could continue providing a `dfhack.init-example` that simply invokes the defaults with `script`. That would still give people the usual "configure DFHack by creating a config file" prompt, default to our defaults, and make it relatively easy to opt out.

I am hesitant to introduce features where one init file can modify the behavior of another (e.g. through variables), mostly due to complexity. Those files are pretty simple right now.

**Comment by myk002** [comment]
Ok, how's this for a plan (directory and file names are totally up for debate):
- default implementations of `dfhack.init`, `onLoad.init`, and `onMapLoad.init` go in `hack/init/defaults/` and get copied to the DF dir on startup (just like how `dfhack-config/defaults/` files get copied to `dfhack-config/` at startup).
- These files contain documentation and one or two lines that invoke files that live in `hack/init/`. For example, the default `onLoad.init` file explains when the file is run and how to add your own commands, and contains the line `script hack/init/onLoad.base.init`
- we have control over the "base" scripts, so they can proxy arbitrary complexity, like conditional actions or invoking other scripts if we want to split config up into small chunks. That way the top level config will never (for some approximation of "never") need to be manually updated by the user after version upgrades.

One could argue that the top-level config files and their defaults belong in `dfhack-config/`, but I fear the location of `dfhack.init` is too well established to change. Moreover, these files need to be super discoverable, and having top level configs in the top level directory is industry standard.

**Comment by wolfboyft** [comment]
Pulling them out of the DLL mess would be good IMO

**Comment by myk002** [comment]
in order to not require any init file editing if the user doesn't need to, perhaps we should remove the warning about no `dfhack.init` and just use `dfhack.init-example` if the real init file doesn't exist. the new `gui/assistant` could be all the configuration a large percentage of our users ever need.

**Comment by myk002** [comment]
and then maybe we should rename `dfhack.init-example` to `dfhack.init-default`
