### ISSUE TITLE
MenuOverlay doesn't restore sidebar mode

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#2123]
As discussed in DFHack/scripts#377

There was a subtle behavioral change introduced here: previously, the script could be invoked from either the Default or LookAround modes, and would preserve the mode that was selected before. Now it always enters LookAround (k), ~~and exits back to Default when it's done~~.

I don't think it really matters, but again, I am curious - is there an existing way to change sidebar modes only if the pre-selected mode isn't one of multiple valid options?

I do worry that it might complicate the logic too much, and I don't see a compelling argument for it unless it is easy.

@myk002 myk002 8 hours ago
I'll look into this. The intended behavior is to restore the previous mode if it is supported by enterSidebarMode(). It should only be "restoring" Default if the topmost screen is a DFHack window or if the starting mode is unsupported

**Comment by lethosor** [comment]
I described that poorly. The `devel/block-borders` script supports panning around both with and without a cursor (toggleable with `k`) and was designed to start out in either Default or LookAround, with the assumption that the user started in the mode that they wanted. Let's try with a table:

### Before

| Initial mode  | Mode after invoking script | Mode after exiting script |
| ------------- | ------------- | --------------- |
| Default  | **Default**  | Default |
| LookAround  | LookAround  | LookAround |
| other | error | N/A |

### After

| Initial mode  | Mode after invoking script | Mode after exiting script |
| ------------- | ------------- | --------------- |
| Default  | **LookAround**  | Default |
| LookAround  | LookAround  | LookAround |
| other | LookAround | other (same) |

The change in behavior between the bolded cells is what I'm referring to.

**Comment by myk002** [comment]
Ah, I see
Yes, very fixable.
