### ISSUE TITLE
Update forks to latest releases

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#2131]
For each fork:
- merge upstream into our master branch
- rebase our changes on top of latest release
- test locally, make any other required changes
- force push to the dfhack branch in our fork
- update submodules in DFHack/dfhack
- ensure CI passes

Updates:
- libexpat: update from 2.2.9 to 2.4.8
- libxslxio: update from 0.2.29 to 0.2.32
- libzip: update from 1.7.3 to 1.8.0
- jsoncpp: update from 1.9.3 to 1.9.5
  - we don't have a dfhack branch for this, or any local changes. Should we make one? It could get an option renaming treatment like libxlsxio got.

Not sure what to do with the other forks:
- isoworld: we're both ahead and behind on this one. It might be worth creating a dfhack branch to separate our changes out
- df-luacheck, exportmaps, DF2MC, Runesmith: are these still active? Should they be integrated into the main build? Archived?

**Comment by myk002** [comment]
Also add missing submodules to https://github.com/DFHack/dfhack/blob/develop/ci/update-submodules.manifest

**Comment by lethosor** [comment]
I would like us to make a `dfhack` branch for jsoncpp, at least to disable the version banner it prints in CMake if nothing else. Might as well upgrade while we're at it. Thanks for tracking these down!

Just to clarify, are you updating our forks to tags corresponding to those versions, or the upstream repos' main branches? I'd prefer the former for stability, unless we have a need for specific patches or the upstream project doesn't tag/make releases.

I personally am not worried about the repos you mentioned at the end. df-luacheck is probably the most up-to-date of all of them, but is not used. I would say we should transfer ownership of isoworld to the DFHack org, if we want to do anything with it, unless @RosaryMala objects.

**Comment by myk002** [comment]
Master to HEAD, dfhack to tag + our changes. The specific flow I had in mind (tell me if there's a better way):
1. Click "fetch upstream" when on our master branch
2. git clone our repo, checkout dfhack
3. git rebase tagname
4. commit any further fixes
5. git push --force
6. pull changes in dfhack clone, test. further fixes can be done in situ

Steps 2-5 probably could be done directly in the dfhack submodule checkouts, but I've found it a bit tricky to do branch work in there.

**Comment by myk002** [comment]
tags did not come for free. I had to set upstream as a remote, fetch them, and push them to our repo.

libexpat done

**Comment by myk002** [comment]
xlsxio done

**Comment by myk002** [comment]
libzip done

**Comment by myk002** [comment]
@lethosor I apparently don't have permissions to the [jsoncpp repo](https://github.com/DFHack/jsoncpp). Could you give permissions to core and/or developers?

**Comment by myk002** [comment]
created dfhack branch for jsoncpp, updated `ci/update-submodules.manifest` to read from the new dfhack branch. after that's merged, I'll fetch upstream, update the dfhack branch, and patch out some warnings/banner headers

**Comment by ab9rf** [comment]
I've had a pending PR for jsoncpp for over a year to deal with a build issue on Windows.

**Comment by myk002** [comment]
Thanks! I'll incorporate those commits when I do the jsoncpp upgrade
