### ISSUE TITLE
Get fortress mode tests running in ci

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#2132]
Need to add a prepared fortress save to the df image used by CI. There is a save ready [here](https://drive.google.com/file/d/1XvYngl-DFONiZ9SD9OC4B2Ooecu8rPFz/view?usp=drivesdk) but we need to get it into the image.

IIRC, the plan of record is to add the compressed save file to the dfhack-bin repo, clone it as part of the build action, and decompress it into place.

Then we can remove the `mode` restriction in run_tests.py so fortress tests are run.

Edit: the save can be added to the df cache by modifying https://github.com/DFHack/dfhack/blob/develop/ci/download-df.sh

Do we want to download the binary with wget or clone/pull the dfhack-bin repo?

**Comment by myk002** [comment]
It looks like we could get tests running in the scripts repo by copying a significant chuck of https://github.com/DFHack/dfhack/blob/develop/.github/workflows/build.yml to https://github.com/DFHack/scripts/blob/master/.github/workflows/build.yml

Is there a better way to do this?

**Comment by lethosor** [comment]
> Do we want to download the binary with wget or clone/pull the dfhack-bin repo?

I think it shouldn't go in the repo - the point of the repo is to allow downloading individual binary assets without needing to download others or older versions at the same time (which a typical `git clone` would include). CMake downloads assets with 
a wrapper around its built-in `download_file()`, for reference. As for where the save should go, I suppose we could add it as an asset to whatever the latest release is with some non-platform-specific prefix (`test-`?). I'm also happy to mirror it on files.dfhack.org.

**Comment by myk002** [comment]
makes sense. It's keyed off a DF version, not a DFHack release, so maybe files.dfhack.org would work best.

**Comment by lethosor** [comment]
Yeah, the versioning scheme there is not the best. I intended for it to mean "assets created when this DF version was current" because they change so infrequently, but it wouldn't work if we needed to update assets more than once per DF release. Adding assets can be done any time, but replacing them is the only thing that requires a new release in dfhack-bin. So I'd be fine adding a (small-ish) save to the last release there as well.

**Comment by myk002** [comment]
> but replacing them is the only thing that requires a new release in dfhack-bin

Could you expand on this part a little bit? By "a new release in dfhack-bin" are you referring tot he [dfhack-bin repo](https://github.com/DFHack/dfhack-bin)? Isn't that repo...mostly empty?

To level-set, this is my current understanding of the plan:

The goal: run fortress-mode unit tests as part of the GitHub test action

- We make the [test save](https://drive.google.com/file/d/1XvYngl-DFONiZ9SD9OC4B2Ooecu8rPFz/view?usp=drivesdk) available as https://files.dfhack.org/DF/0.47.05/test_save.tgz
- we modify [download-df.sh](https://github.com/DFHack/dfhack/blob/develop/ci/download-df.sh) to download the test save (with wget) and extract it in the df `data/save` dir
- we modify [run-tests.py](https://github.com/DFHack/dfhack/blob/develop/ci/run-tests.py) to remove the `--mode` restriction in the `test` command so all modes are run

Open questions:
- How can we update the save file if we need to?
  - Option 1:
    - overwrite https://files.dfhack.org/DF/0.47.05/test_save.tgz with the new version
    - `download-df.sh` re-downloads the file for every run.
  - Option 2:
    - overwrite https://files.dfhack.org/DF/0.47.05/test_save.tgz with the new version
    - cache the file in the df cache (that `download-df.sh` already uses for the df game tarball)
    - create a new action that we can manually run that clears the file from the cache
    - `download-df.sh` downloads the updated test save on the next run
- Do we need to automatically provide the save to users for use in running tests locally?
  - Is this why you brought up CMake's `download_file()`? I hadn't really considered this use case. If devs want to run the tests locally, I figured they could use their own fort save. They can also choose to download the test save from files.dfhack.org and install it manually. Do we need to make this automated?

**Comment by myk002** [comment]
@lethosor I have a PR ready for this, but it does depend on the file being available somewhere. I can point it to google drive for now, but it would be better if we were pulling from somewhere owned by DFHack. I think it might be slightly less maintenance to put the file on files.dfhack.org since we'll need to update it for the next df release, and the dfhack-bin repo hasn't needed another release for many df releases, but it would if it contained the test save. It's totally your call, though.
