### ISSUE TITLE
Adopt isoworld repo into DFHack org

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#2136]
Should DFHack take ownership of the isoworld repo? @RosaryMala WDYT?

ref: #2131

**Comment by RosaryMala** [comment]
Not a bad idea. I haven't been maintaining this at all.

**Comment by myk002** [comment]
This is the process as I understand it (@RosaryMala please correct me if I'm wrong):
1. Ensure code in DFHack/isoworld master branch is fully up to date with upstream
2. Send a message to GitHub support to disconnect the DFHack/isoworld fork from upstream
3. RosemaryMala/isoworld should be removed and recreated as a fork of DFHack/isoworld

**Comment by lethosor** [comment]
I think GitHub support can do #2 and #3 at the same time (i.e. change which repo in the network is the "base"), if requested by RosaryMala. At least, I believe that's what happened with https://github.com/angavrilov/df-structures

**Comment by myk002** [comment]
I merged from upstream. We're a few commits ahead at this point, but nothing behind. @RosaryMala, could you contact support to make the switch?

**Comment by myk002** [comment]
It looks like this is done. Thanks @RosaryMala ! It still doesn't build, but I split that out into #2151
