### ISSUE TITLE
Expat requires CMake >=3.17 on platform "APPLE"

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#2140]
Didn't see this when I tested the fork upgrade. @BenLubar  Is it possible to upgrade our cmake version in the apple buildmaster environment?

Error seen in https://buildmaster.lubar.me/executions/execution-in-progress?executionId=1425293

Cmake download page has updated binaries for osx 10.10 and up. Would that be compatible with our env? https://cmake.org/download/

**Comment by lethosor** [comment]
This was introduced in f00c5857f9c0f9ff3f550d7f35a921c4ae7eadad. Is this a feature we need? If not, we might be able to patch out this block.

**Comment by lethosor** [comment]
From https://github.com/libexpat/libexpat/issues/55, it sounds like this only applies to shared libraries, and we're only using a static lib.

(I'm not opposed to bumping the version of CMake we use in Buildmaster, but I'm not sure I want to bump our minimum version quite that high for everyone yet.)

**Comment by myk002** [comment]
Yeah, if the problem doesn't affect us, the path of least resistance would be to just `if(0)` around the error
