### ISSUE TITLE
EventManager should use and send `shared_ptr` instead of pointers where it makes sense

### ISSUE THREAD

**Issue by cppcooper** [DFHack/dfhack#2150]
It would be really nice in my opinion to have `Job::cloneJobStruct` utilize smart pointers, particularly `std::shared_ptr` which could enable #2107 for example to simplify some procedures, and actually optimize memory utilization. In the "Refactors EventManager.." pull request I've taken to cloning jobs in 3 of the manager functions, twice in one. This sort of change would allow me to share the clones I make between the job manager functions, and allow the shared_ptr to clean itself up when I drop all references from my containers.

**Comment by myk002** [comment]
Anything sent to Lua would have to use bare pointers, I think, but there's no reason why the C++ interface can't be more intelligent. I think this is a good idea.

**Comment by lethosor** [comment]
IMO the caller should create a shared_ptr if it needs one. `workflow` re-adds jobs from `cloneJobStruct()` to DF's global job list, so those should not be managed by a smart pointer.

Does `job2 = shared_ptr<df::job*>(cloneJobStruct(job))` not work for your use-case?

**Comment by cppcooper** [comment]
Yea, I suppose I can just create the managed object inside the initialize function, and think of a mechanism by which to share with the others. It just requires manual clean up, despite using a managed object. So at that point why bother with the managed object, I can't see a reason to. I figured the managed object could simplify some things not just for me.

**Comment by lethosor** [comment]
I think you're right that `deleteJobStruct()` is what you need to use to delete. `shared_ptr` has an optional `Deleter` template argument that I think you could use. Not entirely sure if it would take a function or if you have to wrap it in a class/functor, though.

**Comment by cppcooper** [comment]
> `shared_ptr` has an optional `Deleter` template argument that I think you could use

Oh ok, I'll take a look at that.

**Comment by cppcooper** [comment]
While I still think it'd be nice to generate auto-managed resources when generating resources, I think the suggestion can be put to rest at least until I work may way over to workflow to understand what's going on there.

**Comment by cppcooper** [comment]
So I'm working on #2111 at the moment, and just made some containers for jobs received by the job events. I decided to store the job id's instead of the pointers, because I have no control over their life cycles. So I think sending shared pointers is very much a good idea, as it allows plugins to just use the pointers however they see fit without needing to worry. So perhaps it isn't useful to integrate directly into the cloning procedure, but somewhere in the process to avoid duplicating and make it easy for plugins to keep data laying around for Purposes:tm:
