### ISSUE TITLE
Manager: give a warning/confirmation before a Work Order is removed

### ISSUE THREAD

**Issue by joeljpa** [DFHack/dfhack#2155]
Per title. 

Using 0.47.05-r5. 

While I've seen this UI great improvement done to remove uniforms (for example), I was surprised it wasn't there for removing a Work Order at the Manager screen. Kind of new using this awesome mod which makes our lives so much easier so hope I'm not missing something.

**Comment by myk002** [comment]
+1 on this. 'r' is just too easy to hit. I'm not sure how hard the key is to intercept, but the functionality would fit into the `confirm` plugin.

**Comment by myk002** [comment]
There are times when you need to remove a bunch of orders, though. Perhaps there should be a "pause confirmation for 5 minutes" option when the prompt comes up.

**Comment by lethosor** [comment]
There's a pretty straightforward way to disable, but re-enabling at the moment requires pulling up the settings screen or using the console.

Maybe "pause until this screen is closed" could be a reasonable option, since most bulk workflows like you suggested would keep the same screen open.

**Comment by softmoth** [comment]
I remap it to capital R, it solves the problem well for me.

**Comment by myk002** [comment]
That's a really good idea. I might do that too (maybe in addition to the confirmation prompt requested here)

**Comment by joeljpa** [comment]
I remove orders often also and can't imagine the confirmation being that much of a hurdle for the player.  I think it's worth the minor inconvenience versus accidentally removing a Work Order and having no clue what I just removed from my list of ~10 unrelated Work Orders (true story).
