### ISSUE TITLE
Rewrite refreshSidebar() to not send keystrokes to DF

### ISSUE THREAD

**Issue by Bumber64** [DFHack/dfhack#2172]
``Gui::refreshSidebar()`` currently works by sending keystrokes to DF's UI to move up/down z-levels. We should do this more directly, if possible.

The Lua API documentation says this function:
``Refreshes the fortress mode sidebar. This can be useful when making changes to the map, for example, because DF only updates the sidebar when the cursor position changes.``

One of the things DF does in its internal code for scrolling and recentering is:
```
ui_sidebar_menus->minimap.need_render = true;
ui_sidebar_menus->minimap.need_scan = true;
```

Is there more needed?

**Comment by lethosor** [comment]
Yes, more is needed. I specifically remember that this was a successful way to refresh the `k` sidebar.

Is there a reason feeding keys to DF isn't adequate? There shouldn't be any delay from it.

**Comment by myk002** [comment]
If there is a refresh we can invoke directly, that's arguably better than sending keystrokes. However, any replacement would have to do the refresh inline, without waiting for a tick, so the new sidebar could be interacted with immediately. Many of our scripts depend on this behavior.

**Comment by lethosor** [comment]
That's a good point, so any sort of "update on next tick" flag like `need_render` wouldn't be adequate for all clients.

There are really only three possibly-relevant viewscreen methods that could be updating the sidebar content: logic(), feed(), and render(). If Myk has scripts in mind that rely on the sidebar to be updated instantly, and those scripts work reliably, then based on the current implementation of refreshSidebar(), feed() is almost certainly where the sidebar-updating logic lives. Unless feed() is calling some other more-specific vmethod that updates the sidebar, our two main options would be to call a non-virtual method or to reimplement DF's sidebar-updating logic (both of which are rarely worth the trouble).
