### ISSUE TITLE
build-now leaves wall constructions that flash red in remove construction mode

### ISSUE THREAD

**Issue by wolfboyft** [DFHack/dfhack#2174]
To reproduce: make a wall of normal wall constructions, then designate another layer on top and build-now.
Presumably this is because the previous top-of-wall constructions weren't removed?

**Comment by wolfboyft** [comment]
Working on a fix right now

**Comment by myk002** [comment]
I think your guess is spot on. If you need any help with the fix, just ask!

**Comment by lethosor** [comment]
What does DF flashing red actually mean? Is it indicative of a problem?

**Comment by wolfboyft** [comment]
I meant, like, when you go to designate remove construction, the construction tiles flash red instead of green. Also sorry, back working on it again. Worried that my formatting may not be in-style btw so let me know when I open the PR.

**Comment by wolfboyft** [comment]
I go through and make it delete the first construction on the tile it sees, and it just leaves "floor", a "green-type" construction when it should be "red-type". Guess I'm doing something badly wrong. Maybe it's not deleted but inserted in front of/behind the floor one...?

**Comment by wolfboyft** [comment]
Also build-now on a single wall seems to have mixed up the no_build_item flag? A proper wall has it false on both its wall and floor above, but build-now'd ones seem to have it true for the wall.

**Comment by myk002** [comment]
it wouldn't crash df, but it's likely to cause build-now'd constructions to behave differently from naturally built ones. it's a bug, but not a dangerous one.

Feel free to start a PR any time. I'd like to do some testing with your changes to make sure I understand what's going on.

**Comment by wolfboyft** [comment]
The red means you can't remove the construction because it's the "virtual floor" on top of a wall.

**Comment by wolfboyft** [comment]
Okay, set up a PR in the scripts repo.

**Comment by wolfboyft** [comment]
The PR's closed, so

**Comment by wolfboyft** [comment]
Unless we were supposed to keep the task open for the get_original_tiletype business, I should've asked first

**Comment by myk002** [comment]
No that's ok, and we should have attached three PR to this bug so it got closed automatically. You can write something like "Fixes DFHack/dfhack#2174" in the PR description to link it automatically.
