### ISSUE TITLE
EventManager and Eventful UNIT_NEW_ACTIVE is broken

### ISSUE THREAD

**Issue by warmist** [DFHack/dfhack#2189]
The event triggers for all units all the time as the (local static) activeUnits is not updated to have "seen" ids. Also local static does not work here as it needs to be cleared on map unload and etc.

https://github.com/DFHack/dfhack/blob/develop/library/modules/EventManager.cpp#L595

**Comment by warmist** [comment]
Also it could be looking at next unit id change to find if any new unit is created and only then check for updates in the unit list. (Also check with binary search as we know it's sorted?).

**Comment by myk002** [comment]
@cppcooper

**Comment by myk002** [comment]
Also Lua is still seeing this event as NEW_UNIT_ACTIVE. I thought we fixed that, but I guess not.

**Comment by cppcooper** [comment]
yep, he's right. that shouldn't have gotten through review lol
just need an
```cpp
activeUnits.emplace(id);
```
on line 603

**Comment by cppcooper** [comment]
I can implement this, but honestly it'd probably happen faster if yall did it yourselves. Whoever feels like it. I probably won't touch it for a while.. but we'll see maybe I think that now and at 9pm I'll be all `hmm, I need something to do`

**Comment by cppcooper** [comment]
> Also Lua is still seeing this event as NEW_UNIT_ACTIVE

Where do you see that? This is what I see:
![image](https://user-images.githubusercontent.com/7276349/172507628-9fbb90f4-4ee0-415b-991a-5fe2b76cbbca.png)

**Comment by myk002** [comment]
> > Also Lua is still seeing this event as NEW_UNIT_ACTIVE
> 
> Where do you see that? 

I think the culprit is here: https://github.com/DFHack/dfhack/blob/40a6fcdd9928d482e409801078d365b41de4e5c5/plugins/lua/eventful.lua#L157

**Comment by warmist** [comment]
IMHO we can use the rewised (see https://github.com/DFHack/dfhack/issues/2190 and probably this: https://github.com/DFHack/dfhack/pull/2107) which fixes this bug in the process.

**Comment by cppcooper** [comment]
> > > Also Lua is still seeing this event as NEW_UNIT_ACTIVE
> > 
> > 
> > Where do you see that?
> 
> I think the culprit is here:
> 
> https://github.com/DFHack/dfhack/blob/40a6fcdd9928d482e409801078d365b41de4e5c5/plugins/lua/eventful.lua#L157

Ah, I see.



> IMHO we can use the rewised (see #2190 and probably this: #2107) which fixes this bug in the process.

I've got some down time right now, I'm gonna see if I can make a quick patch PR.

**Comment by cppcooper** [comment]
I've made the edits I think we wanted. Short PR, review at leisure. Haven't added a changelog entry yet
