### ISSUE TITLE
Don't spam DF downloads part 2

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#2195]
The os updates in #2191 trigger an issue in our download-df.sh. namely: the receipt file we use to detect changes is useless.

The specific issue is that the md5 binary in the updated os images produces different output for the same input. The md5 hash is the same, but the newer version of md5 adds the string "MD5" to the beginning of the output. This causes the `receipt` check that compares against the cached md5 output to fail on os images that contain a different md5 binary from the one that initialized the cache. Therefore, regardless of who initialized the cache, half of our builds will needlessly redownload DF and the test save.

Now that we understand more about how GitHub caches work, we can do better.

Right now, we key the cache on the df version and the md5sum of the download-df.sh script. The download-df.sh script then does a check against it's own md5sum to see if there are any changes that might require redownloading. Now that we know that caches are write-once, we can:

1. Keep download-df.sh the same and add the os version to the key
Or
2. Rewrite download-df.sh to only download the files if they don't exist in the cache (the new cache case) and get rid of the receipt

I like option 2 better because it is less wasteful.

**Comment by lethosor** [comment]
Sounds to me like we can resolve this more quickly by passing better flags to md5, or switching to a different hash implementation.

**Comment by myk002** [comment]
Any fix would involve modifying download-df.sh. removing the receipt is not a difficult change

**Comment by lethosor** [comment]
Looks like this is due to `openssl` upgrading from 1.1.1 in Focal to 3.0.2 in Jammy. Guess that's a breaking change. I thought I picked this at the time over `md5sum` because it _was_ more stable across platforms... sigh.

I'm fine with (2). FWIW, this script dates back to before we were using Github Actions, and caching on Travis behaved differently.
