### ISSUE TITLE
the registerReaction function of the eventful module is broken

### ISSUE THREAD

**Issue by quarque2** [DFHack/dfhack#2202]
If you use the registerReaction(reaction_name,callback) to modify a reaction, it seems that the callback function does not receive the 7th argument (call_native).
Without the call_native parameter you can't disable the standard behaviour of a reaction.

Can be reproduced with the following example script, that should make brewing require water:

~~~
-- Forces brewing in a still to require water
local eventful = require 'plugins.eventful'
local utils = require 'utils'
function usewater(reaction,reaction_product,unit,input_items,input_reagents,output_items,call_native)
	local building = dfhack.buildings.findAtTile(unit.pos)
	local pos = {}
	pos.x1 = building.x1
	pos.x2 = building.x2
	pos.y1 = building.y1
	pos.y2 = building.y2
	pos.z = building.z
	for x = pos.x1-1, pos.x2+1, 1 do
		for y = pos.y1-1, pos.y2+1, 1 do
			baseBlock = dfhack.maps.ensureTileBlock(x,y,pos.z)
			liquidBlock = dfhack.maps.ensureTileBlock(x,y,pos.z-1)
			if liquidBlock.designation[x%16][y%16].flow_size > 0 and liquidBlock.designation[x%16][y%16].liquid_type == false then
				liquidBlock.designation[x%16][y%16].flow_size = liquidBlock.designation[x%16][y%16].flow_size - 1
				call_native.value=true
				return
			end
		end
	end
	dfhack.gui.showZoomAnnouncement(df.announcement_type.CANCEL_JOB, unit.pos, dfhack.TranslateName(unit.name).." cancels "..reaction.name..": Needs water." , COLOR_RED, true)
	call_native.value=false
	-- Force the job to fail.  Create no Products; do not provide any experience points in the associated Skill.  
	-- Note: the failed job WILL consume the normal set of Reagents.
	dfhack.job.setJobCooldown(building, unit, 5) -- Prevent the worker from immediately re-attempting the failed Job.
	return
end

dfhack.onStateChange.loadUseLiquid = function(code)
	if code==SC_MAP_LOADED then
		for i,reaction in ipairs(df.global.world.raws.reactions.reactions) do
			if string.startswith(reaction.code,'BREW_DRINK') then
				eventful.registerReaction(reaction.code,usewater)
				print('reaction should now require water: ')
				print(reaction.code)
			end
		end
	elseif code==SC_MAP_UNLOADED then
	end
end

if dfhack.isMapLoaded() then dfhack.onStateChange.loadUseLiquid(SC_MAP_LOADED) end
~~~

**Comment by myk002** [comment]
It appears that there are two callbacks, onReactionCompleting, which passes call_native, and onReactionComplete, which does not (because by the time that event fires, the native callback has already been called). It might be a documentation issue.

Code ref:
https://github.com/DFHack/dfhack/blob/develop/plugins/eventful.cpp#L355-L366

**Comment by quarque2** [comment]
Does this mean I can use the onReactionCompleting function instead of registerReaction to get my script to work? That would be great. :-)

**Comment by myk002** [comment]
That's my read on it.

**Comment by quarque2** [comment]
Ah, I think I see now. 

There is an example in the documentation that shows how this is intended to work:

~~~
b=require "plugins.eventful"

b.registerReaction("LUA_HOOK_LAY_BOMB",function(reaction,unit,in_items,in_reag,out_items,call_native)
  local pos=copyall(unit.pos)
  -- spawn dragonbreath after 100 ticks
  dfhack.timeout(100,"ticks",function() dfhack.maps.spawnFlow(pos,6,0,0,50000) end)
  --do not call real item creation code
  call_native.value=false
end)
~~~

I can tell there has been some change in those functions between 2014 and 2017, because the second expected parameter (reaction_product) is missing in this example and it is also missing in some scripts from 2014. I noticed someone else reporting this bug on the forum in 2017.

The registerReaction function should probably bind your custom callback function to the onCompleting event of the given reaction. The advantage of this function is that it does not require the reaction to start with LUA_HOOK_, so you can use it to change an existing reaction. With the onCompleting function you are forced to add a new custom reaction to the raws.

**Comment by warmist** [comment]
The comment above is exactly right. The callback was split to be more obvious about the use however the library lua file was not changed to reflect that.
