### ISSUE TITLE
Documentation for windows builds

### ISSUE THREAD

**Issue by cppcooper** [DFHack/dfhack#2205]
So [take a look](https://docs.dfhack.org/en/stable/docs/Compile.html#windows), that's the beginning of the windows build documentation section. Wouldn't it be nice if we had a table of contents? Perhaps a FAQ section and other improvements?

Perhaps we should separate the documentation of platform dependent builds to different files and keep very short sections in [this file](https://github.com/DFHack/dfhack/blob/develop/docs/Compile.rst) for each platform, which then link to their respective files.
@lethosor I think you were leaning this way

@myk002 @ab9rf thoughts?

**Comment by cppcooper** [comment]
So.. aside from the headings using an arbitrary order of a set of accepted heading underlines the rst's support localized content tables a la
```
.. contents:: Contents
  :local:
  :depth: 6
```

So separate files aren't necessary it seems. I'm going to take a crack at restructuring the windows help for the sake of clarity and simplicity.

**Comment by myk002** [comment]
Sounds good. Thanks!
