### ISSUE TITLE
Find out what people need most from DFHack

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#2217]
After basic reverse engineering to re-establish our hooks  I expect we'll need to validate all DFHack functionality for the steam release. Covering everything before we do a release is a huge task. It would be very useful if we knew what users need most so we could prioritize accordingly. Then we can do smaller incremental releases.

I'm thinking about creating a survey the we can post on Reddit, the forums, and anywhere else DF players congregate. The survey can be hosted on Google forms, and the results can get automatically written to a spreadsheet for analysis.

The big question is, then, what questions should we ask? We have a practical limit to how many questions we ask because if we ask too many, then people won't finish the survey. Maybe limit ourselves to 5 questions?

The idea is to discover what classes of users are using DFHack, where a class is defined by the set of DFHack tools they are using. The remaining questions should focus on discovering the needs of the users in that class.

**Comment by myk002** [comment]
Potential questions:
- which DFHack services do you use? (checkboxes for all plugins and scripts, maybe broken down by category, maybe bundled into groups)
- what is the one command/screen/service from DFHack that you rely on most?
- which mods do you use that require DFHack?
- what do you wish DFHack would do better?

**Comment by wolfboyft** [comment]
"Do you find it easy to get into script/plugin development?"

**Comment by cppcooper** [comment]
Automation faculties for me. And scripts to help manage dwarves/animals

**Comment by cppcooper** [comment]
I'd just dig into what you want to know, which is how users are using dfhack.
1. What describes best your purpose for using dfhack? cheating, management, ui improvements, automation (we want to be able to visualize how users are distributed along a wide range of uses, so add/remove to the list as needed)
2. What plugins do you appreciate or use the most?
3. Which 5 (or less) scripts do you need the most?

I think it boils down to just a few general questions. If we're talking a survey, we'll want to aggregate the data so we can see what things stand out. And for what its worth, I think automation and management of dwarves(stats) and animals are the most useful aspects of dfhack.

**Comment by lethosor** [comment]
> That first question depends on a taxonomy for DFHack scripts/plugins. I'll see if I can come up with something. If it's good enough, we might be able to reuse the taxonomy to restructure our documentation.

"Tools" is how we've summarized it in the project description at https://github.com/DFHack/dfhack for a while.

**Comment by myk002** [comment]
Taxonomy spreadsheet here: https://docs.google.com/spreadsheets/d/1hiDlo8M_bB_1jE-5HRs2RrrA_VZ4cRu9VXaTctX_nwk

I didn't categorize modtools/ or devel/ since they're (ostensibly) not user-facing. They can get documented as categories of their own.

The next step is to create the survey, using the new taxonomy to name groups of tools do we have only a few checkboxes instead of 350+

**Comment by myk002** [comment]
> I'd just dig into what you want to know, which is how users are using dfhack.
> 
> 1. What describes best your purpose for using dfhack? cheating, management, ui improvements, automation

I think you might be right. We don't need to list every tool, and even the category names I came up with aren't very useful for this (though I hope they'll still be useful for improving our documentation)

**Comment by myk002** [comment]
In-progress form here: https://docs.google.com/forms/d/e/1FAIpQLSfXMmRZNi1Fyb5fOsa2W5RC_MTeu9IGucC-PRDLzkn_0r51Lw/viewform?usp=sf_link

**Comment by cppcooper** [comment]
> > I'd just dig into what you want to know, which is how users are using dfhack.
> > 
> > 1. What describes best your purpose for using dfhack? cheating, management, ui improvements, automation
> 
> I think you're right. We don't need to list every tool, and even the category names I came up with aren't very useful for this (though I hope they'll still be useful for improving our documentation)

Well, here is a list I just made up. I think it covers much of the use cases I see dfhack as being for.

* cheat
* quality of life
* automate and manage
* simplify the mundane
* bug fixes
* ui improvements
* new mechanics
* information gathering/analysis

**Comment by myk002** [comment]
@cppcooper could you try taking the survey to see if the organization of the questions works? Feel free to submit real answers. It all goes to a spreadsheet

**Comment by cppcooper** [comment]
> @cppcooper could you try taking the survey

I had difficulty answering the "I use DFHack to:". I found the section a bit too complicated. I'd look at the idea of the response eg. "Add new mechanics" and then the scripts/plugins it lists and I'd immediately be in conflict. (for me it was with: automate, information for decisions , manage stock, change x/y/z, recover) So I'd look at these and think, oh yea that's me.. Then the scripts and think, ok maybe not.. I wonder what scripts they(myk) considers part of this use.

So in that singular way, the responses feel like they're enforcing a Use to Script mapping. Which maybe is what we want, but it gets tricky for the user trying to choose responses if you're not sure what kind of script DFHack considers your particular script unless explicitly listed.

In terms of designing a survey, we want to make responses easy and natural to choose. So all the mentally taxing stuff should be on the surveyor side of things. Otherwise, we might end up in a situation where the responder part way through says to themselves you know what it doesn't really matter and just leaves or gives half baked responses. In other words, the users should only need to think about how they use dfhack and match that with simple responses, or add their response as "other" with a text box.

In short, we should divorce the responses from their related scripts/plugins [or do the opposite and accept scripts/plugins as responses].. Our asking about which parts they use most allows us the chance to cross reference their idea about how they use dfhack with actual scripts/plugins.

> In terms of designing a survey, we want to make responses easy and natural to choose.
To go back for a quick second, even the questions should be short and sweet. So for Q4 I'd write:

What do you wish DFHack would do better? (eg. documentation, script X should also do Y, integrate more things with the GUI, etc.)

Shorten the examples, group them together and make them second-class compared to the question.

As someone with a bit of an information processing problem, simple stuff like this matter more than we can immediately realize.

I feel like a such a hypocrite hah.. Here I am espousing short, simple, and quick response options.. and I've written a huge response about responses.

**Comment by myk002** [comment]
> I feel like a such a hypocrite hah.. Here I am espousing short, simple, and quick response options.. and I've written a huge response about responses.

You should see some of the posts in the quickfort thread sometime... ldog and I got in pretty deep.

Good feedback. Thank you! I updated the survey. Could you take another look?

**Comment by myk002** [comment]
> What is LDOG?

see, for example, http://www.bay12forums.com/smf/index.php?topic=176889.345

> To be better I think we gotta nail down the breakdown of uses and their order.

I was actually planning on randomizing the order to avoid "select the first option" syndrome

I'll add the Other option.

"Change the map/dwarves/resources to what I want" means "edit stuff to casually cheat, like to make the game easier overall", but I'm being careful not to use the word "cheat" since it can be seen as judgmental. I do want to differentiate this type of cheating from the "cheat myself out bad planning/unwinnable situation" option.

**Comment by myk002** [comment]
Good point. Changed to "modify"

**Comment by myk002** [comment]
The reddit post is live!
https://www.reddit.com/r/dwarffortress/comments/vhr2c3/help_dfhack_get_ready_for_the_dwarf_fortress/?utm_source=share&utm_medium=web2x&context=3

**Comment by myk002** [comment]
Forum post is live here: http://www.bay12forums.com/smf/index.php?topic=180020.new#new

Post text:
```
When a new DF release comes out, DFHack devs need to spend time adapting to code and behavior changes. This means that we have to go through all our tools and make sure they still work! We need your help figuring out which are the most important DFHack tools to look at first when the Steam release comes out.

If you can, please help us by writing down the DFHack tools you depend on most in this (very short) survey: https://docs.google.com/forms/d/e/1FAIpQLSfXMmRZNi1Fyb5fOsa2W5RC_MTeu9IGucC-PRDLzkn_0r51Lw/viewform

This is the same survey we posted to Reddit, so if you've already submitted something from there, thank you! and no need to submit again from here.

Feel free to comment in this thread, but please fill out the survey form too! Those are the responses that we're looking at.
```

**Comment by myk002** [comment]
After a huge amount of database query calculation, we have the graph of tool affinity to user type:
![image](https://user-images.githubusercontent.com/977482/175366416-d9834f74-6108-4002-9556-e6e868a420d8.png)
In other words, there is no clear association of tool to user type. Users may say they prioritize different things, but they all use the same tools.

**Comment by myk002** [comment]
The "more than 10 explicit mentions club" (as of 2022-06-23):
![image](https://user-images.githubusercontent.com/977482/175374146-a7098e6a-2e04-4083-ade7-6ed1cac04e43.png)

**Comment by myk002** [comment]
What users want most from DFHack:
![image](https://user-images.githubusercontent.com/977482/175436277-09541e5b-da5a-4aaf-9661-0c51be7b7c92.png)

**Comment by myk002** [comment]
Top feature requests (only new requests; about a third of "feature requests" are for existing features that were not discoverable enough):
![image](https://user-images.githubusercontent.com/977482/175473884-3790a551-fc74-4efa-9a41-120f0ffeb6bb.png)

**Comment by myk002** [comment]
I'll update this report if there are significant changes, but here are the results and analysis so far:

Overall, there were 457 responses. This is more than enough to get some real, statistically significant results. Thank you all for your responses! It really means a lot to us!

### Q1: "I Play:"
457 responses.
![image](https://user-images.githubusercontent.com/977482/175720065-3d1520f2-14b6-46ab-b897-057678bbbd8c.png)

#### Q1 analysis
**Almost everybody (98.2%) plays fort mode.** About a quarter of respondents also play adventure mode. A small percentage play with mods, and most are small personal mods the players themselves have created. Only Squamous's mods (The Long Night, Fall from Grace, etc.) and Masterwork have more than one respondent playing them.

DFHack tools that are useful for fort mode will have the most impact, but adventure mode has a significant presence. Tools specifically for adventure mode will still be appreciated and used, but that is not where the devs should focus.

Mods may not have a huge presence right now, but that might change drastically once DF supports Steam Workshop and mods can be distributed via Steam. Watch this space!

### Q2: "I use DFHack to:"
454 responses.
![image](https://user-images.githubusercontent.com/977482/175720413-953170ac-d92d-4aa9-9a5a-343a5c97240b.png)

#### Q2 analysis
The **top categories all have to do with productivity, toil reduction, and access to information**. This is where people are most keenly aware of DFHack's benefits.

These categories are closely followed by bug fixing. Bugfixing happens in the background and is mostly invisible. I was surprised that there were this many people who were aware enough of the bugfixes that they selected for this option, though I suspect if people knew the extent of DFHack's bugfixing, the number would be even higher.

Every aspect of DFHack has a significant number of users that care about it, though.

### Q3: "What are the DFHack tools that you rely on most?"
280 responses. Only tools that got 10 or more mentions are included on the graph. There is a very long list of tools (300+) that did not get mentioned by name. We will be using the rankings here (along with the rankings in Q2 above) to prioritize our work in getting tools ready for the Steam release.

Note that these are plugin/script names, not command names. For example, many people wrote `digv` as the tool they use, but it was consolidated in this graph with the other `dig` plugin commands. Also, many people seemed uncertain about what to call the `manipulator` plugin. Many just called it "Dwarf Therapist" or "that DT screen" or "labor spreadsheet". These were all consolidated into the `manipulator` category, even the ones that were clearly referring the the *real* external (non-DFHack) tool named Dwarf Therapist, with the rationale being that "a tool that does labor assignment is important to our users".

![image](https://user-images.githubusercontent.com/977482/175722031-3df5f6d6-ad1d-43db-8d89-36a5e1bc9afa.png)

#### Q3 analysis
This is a poll of perception, not actual records of usage, so we must remember that these are not necessarily the most *valuable* tools, but rather the most *valued* tools. All the tools listed here are definitely high-value, but the list is not guaranteed to be exhaustive.

That being said, the most valued tools seem to fall into a few categories

- **Automation:** (autobutcher, autochop, autofarm, autolabor, autonestbox, buildingplan, workflow)
- **Information:** (embark-assistant, manipulator, reveal, prospect, search, showmood, stocks)
- **Aesthetics:** (autodump, clean)
- **Wizardry:** (createitem, exterminate, fastdwarf, liquids)
- **Fortress design:** (dig, quickfort)
- **Utility:** (exportlegends, gui/gm-editor, quicksave)

### Q4: "What do you wish DFHack would do better?"
171 responses. This is the "user pain points" section. The responses here indicate where DFHack users are feeling frustration.
![image](https://user-images.githubusercontent.com/977482/175749791-a7a9a46b-af89-4410-9244-814a52aa68cf.png)

#### Q4 analysis
The results could not be more clear. DFHack has a lot of great, useful features, but users are frustrated with not being able to find them and not being able to use them. There is a large call to make DFHack more accessible from the Dwarf Fortress game screen (the GUI). DFHack should be heavily concentrating developer effort to fix these usability issues.

### Q5: "If you could write your own DFHack feature, what would it be?"
147 responses. Here are the areas where users think DFHack could make an impact if we were to develop a new feature. I made up tool names to combine similar ideas from multiple users, which I will explain more below. Only ideas that appeared more than once are included in the charts below.
![image](https://user-images.githubusercontent.com/977482/175750013-06a2ca88-d9f9-4dc7-8e3a-846ea6fe220a.png)
Now, you may recognize some of the "feature requests" in that chart. Many users were just not aware that DFHack already includes the tool they were requesting. In fact, about 1 in 3 feature requests were for features or tools that already exist in DFHack. Another vote for the "Discoverability" pain point.
Here is the chart with only requests for features that don't already exist in DFHack:
![image](https://user-images.githubusercontent.com/977482/175750191-4f5c9af3-793a-412d-93a1-9681389f85d2.png)
Again, these are made-up names that I used to embody the spirit of the ideas I was combining from the responses. Here's what they mean:

- military
- force-siege
- impregnate
- track-designer
- fix/missingsquad
- assign-pets
- max-wave
- fortminder
- gui/assistant
- filter-reports
- religion

#### Q5 analysis

**Comment by lethosor** [comment]
I might add to your list at the end: catsplosion can already handle non-cats. Not quite sure if it handles dwarves, and I'm pretty sure it doesn't handle individuals, so there's still some room for new features there.

**Comment by myk002** [comment]
I can add that info to the `impregnate` feature request explanation. Yeah, `catsplosion` handles any animal type, but not dwarves (and also not specific units)

**Comment by myk002** [comment]
Report has been posted to:
- [reddit](https://www.reddit.com/r/dwarffortress/comments/vlwsi7/the_dfhack_survey_results_are_in/?utm_medium=android_app&utm_source=share)
- [DF forums]()
- [DFHack forum thread]()
