### ISSUE TITLE
Convert starvingdead from ruby to lua

### ISSUE THREAD

**Issue by quarque2** [DFHack/dfhack#2229]
See #2081. This issue is for the subtask of converting the starvingdead script.

As discussed in Discord, I would like to suggest a small change in the way in functions, as well. Instead of removing an undead after a fixed time of 6 months, remove it after its physical attributes fall below a certain threshold. That way, stronger undead persist for longer.

**Comment by myk002** [comment]
Your suggested improvements sound good!

**Comment by myk002** [comment]
@quarque2  do you have time to implement this? We're intending to turn Ruby down with the next DFHack release.

**Comment by vallode** [comment]
The script was ported in https://github.com/DFHack/scripts/pull/537, since the script now offers variable decay rates and death thresholds I think it's enough for now. No need to rewrite the logic.
