### ISSUE TITLE
Factor out fastdwarf movement timers into API

### ISSUE THREAD

**Issue by wolfboyft** [DFHack/dfhack#2244]
The fastdwarf movement timer modification code could really benefit modders if it were in its own API.

Fastdwarf breaks for every action type it works on so I can assume a unit won't have multiple move actions at a time, making the API's getter(s) simpler.

I think the API should have: getMoveStatus, which'd return movement timer, timer start and action type (or getMoveTimer, getMoveTimerStart, and getMoveActionType if multiple return can't be supported), and setMoveTimer, addMoveTimer (taking negatives (also maybe addMoveTimerCapped (capped to move timer start))), and multiplyMoveTimer (with flooring for integers. Maybe also multiplyMoveTimerCapped).

**Comment by wolfboyft** [comment]
```cpp
int Units::addActionTimer(df::unit* unit, int amount, int affectedActionType, bool notCappedToTimerInit)
{
    CHECK_NULL_POINTER(unit);
    // Loop over all actions, if an action is of the right type, add to the timer accordingly
    // Don't forget to ignore attack timers of 0, like in fastdwarf
}

int Units::addActionTimerCategory(df::unit* unit, int amount, int affectedActionTypes, bool notCappedToTimerInit)
{
    CHECK_NULL_POINTER(unit);
    // Loop over all actions, if an action's type is in the category, add to the timer accordingly
    // Don't forget to ignore attack timers of 0, like in fastdwarf
}

int Units::multiplyActionTimer(df::unit* unit, float amount, int affectedActionType, bool notCappedToTimerInit)
{
    CHECK_NULL_POINTER(unit);
    // Loop over all actions, if an action is of the right type, multiply the timer accordingly
    // Don't forget to ignore attack timers of 0, like in fastdwarf
}

int Units::multiplyActionTimerCategory(df::unit* unit, float amount, int affectedActionTypes, bool notCappedToTimerInit)
{
    CHECK_NULL_POINTER(unit);
    // Loop over all actions, if an action's type is in the category, mutliply the timer accordingly
    // Don't forget to ignore attack timers of 0, like in fastdwarf
}
```
Current iteration of the API (want me to split those long lines?)
I just had a thought, what if you wanted to only work on action timers that are at init? Should we have a bool for controlling that? It's a believable use case, subtracting a bonus x from the time or splitting it in half but letting it run when it's not at start.

Also I'll make a PR to change the modding API's "use" of this API when this API is done.

**Comment by wolfboyft** [comment]
The idea would just be a `bool ignoreTickedTimers` addition to the function signature. But now that I think about it, what if you add to the timer and bump it back up to start again? Should we care about that case?
Also I think subtract would be better than add. Current API:

```cpp
int Units::subtractActionTimer(df::unit* unit, int amount, int affectedActionType, bool notCappedToTimerInit,
                               bool ignoreTickedTimers)
{
    CHECK_NULL_POINTER(unit);
    // Loop over all actions, if an action is of the right type and either ignoreTickedTimers is false
    // or the timer is at init, operate on the timer according to amount, not letting it go below 1
    // Don't forget to ignore attack timers of 0, like in fastdwarf
}

int Units::subtractActionTimerCategory(df::unit* unit, int amount, int affectedActionTypes, bool notCappedToTimerInit,
                                       bool ignoreTickedTimers)
{
    CHECK_NULL_POINTER(unit);
    // Like subtractActionTimer but for a category of action timers, "all" being a category
}

int Units::multiplyActionTimer(df::unit* unit, float amount, int affectedActionType, bool notCappedToTimerInit,
                               bool ignoreTickedTimers)
{
    CHECK_NULL_POINTER(unit);
    
}

int Units::multiplyActionTimerCategory(df::unit* unit, float amount, int affectedActionTypes, bool notCappedToTimerInit,
                                       bool ignoreTickedTimers)
{
    CHECK_NULL_POINTER(unit);
    
}

```

**Comment by myk002** [comment]
`affectedActionTypes` is a mask, right? What's the definition of the mask? Will there be category masks? How are they defined?

if you find yourself adding more `bool`s to the end of a function signature, maybe consider a bitmask for flags as well.

do we have need of a get API?

for use cases where we only want to make a modification once when timer==init, does it make sense for the caller to track that, or can the API reasonably handle it? The case where the caller increases the timer past init might be a good reason for why the caller would have to track whether modifications have been done to this unit's action before.

**Comment by wolfboyft** [comment]
`affectedActionTypes` is an entry in an enum in this iteration, sorry, I must've not been clear.
I think 2 bools is fine but if there are more then yeah, though I am averse to using a bitmask for that.
A get API? Yeah, one that only works on single action types, sounds good.
I think we need the API to handle it because it works on multiple types and you would have a hard time excluding types if their getters returned == init. Unless we really *should* use a bitmask for the affected types.
