### ISSUE TITLE
rename enableable plugins whose name is close to but not equal to their commands

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#2249]
Offshoot from #2228 

to reduce help page proliferation.

prospector -> prospect
burrows -> burrow
cleaners -> clean

**Comment by lethosor** [comment]
How does this affect the number of help pages? I would think there would be one page per plugin either way.

**Comment by myk002** [comment]
it's one page per help entry, and if a plugin name differs from the commands it provides, there will be an extra page for the plugin

**Comment by lethosor** [comment]
Hm, I thought we were going with a page per plugin. In a lot of cases (ok, maybe not all), the commands that a single plugin implements are closely related: `clean`/`spotclean`, `reveal`/`unreveal`/`revflood`. Keeping them consolidated into one page _could_ reduce duplication, somewhat.

**Comment by Moth-Tolias** [comment]
one page per plugin would probably be preferable, if it's an option.

**Comment by myk002** [comment]
The current architecture uses one rst file in `docs/tools/` to house:

- the tags/categories for the command
- the keybindings for the command
- the short description (taken from the first sentence of the help text)
- the full help text (the entire .rst file that includes all of the above)

Putting all commands provided by a plugin on a single page certainly makes organizational sense. Adding keybindings for all the commands at the top in one section is not difficult. Getting tags and short descriptions out per command might be a little more tricky, though.

Well, there is a fallback for the short descriptions. I've been removing the "usage" text from the PluginCommand initializers, but I've been keeping the short descriptions so helpdb has the text to fall back on in case the rendered text isn't available. I can get the short descriptions from there. The first sentence of the rst file can then become the short description for the plugin itself, but only used in `ls` if the plugin name differs from the command name.

This does mean that the same tags will be used for all commands in the plugin. We'll see if that makes sense. If it doesn't we can likely come up with some syntax to allow for different commands in the same rst file to have different tags.

**Comment by myk002** [comment]
Yes, this is possible. I just need to add another layer of indirection in helpdb. The API shouldn't change, but the help file structure can get simplified.

**Comment by myk002** [comment]
Whereas combining plugin docs into one page is tractable for the helpdb, the HTML help will no longer have a way to index by command. The vision there was to cross link commands by tag. The current implementation enabled this by making each file a link target. Now that will no longer be true, potentially making the HTML help less useful. We haven't fully designed the sphinx help, so maybe this won't turn out to be a problem, but it's something to keep in mind.

For example, with each command on its own page, sphinx could produce an index of commands and their short help. With the plugin commands combined on one page, at most sphinx will include the plugin name in the index, which is not as useful. There is no digv,, only dig. There is no prospect, only prospector. What do you think? Is this trade-off worth it? Is there a good way to get plugin commands back in the index and associated with their tags?

**Comment by myk002** [comment]
I think I came up with a possible solution. Here's my line of thinking, and maybe you can tell me if it makes sense or if there's a better way to get command-level granularity back into the HTML docs. (Or maybe it was obvious and it just took me a while to see it...)

In order to generate a command index, sphinx needs to know what the commands are. It no longer has the map of one file per command, so we need another method. Directives come to mind. Could there be a way to mark each command with a directive like
```:dfhack-command:`commandname` ```
And gather the set of commands while sphinx processes the docs? Afaict, no. Sphinx doesn't work that way. Directives are a way to *inject* information, not *extract* it. But wait, we can **pre-parse** out the directives from conf.py and build an index that way! Hold on a sec, at the top of every file that contains commands, we *already* have the `:dfhack-keybind:` directive that lists exactly the command names! So all that really needs to change is that we build our index from the text in the keybind directives instead of the file names.

With this method, we can additionally differentiate between plugin names and plugin commands, which is a strict improvement over the previous organization. We now have enough information to generate:

- list of plugins (and link to their docs)
- list of commands per plugin (and link to the plugin docs)
- list of commands per tag (with the restriction that all commands for a plugin must have the same tags, unless we get fancy (but no need for that yet))

However we lose the ability to generate command indices with short descriptions since we no longer have an obvious place to retrieve the short descriptions from (before, this was extracted from the first sentence of the per-command doc file). Ideas to solve this? Is there a need for more special syntax that we can parse out?

Let me write a little summary of the changes required to move all docs related to a single plugin into a single file:
- help file structure
  - before:
    - one file named for the plugin with information on what happens when you enable the plugin
    - one file per command that the plugin provides
    - each command doc file contains tags and a keybinding directive for the command
    - if the name of the plugin is shared with a command that the plugin provides, they share a doc file with information on both enabling and running
  - after:
    - single doc file with the plugin's name with docs for enabling and running provided commands
    - at the top of the single file, there are keybinding directives for all commands documented in the file
    - all commands are associated with the same tags
  - same:
    - if a command has no keybinding, the keybinding directive for that command expands to the empty string
    - total documented information does not change
    - no individual doc file for plugins that are not enablable and provide no commands (i.e. plugins that only provide a Lua API). These plugins are documented in `Lua API.rst`
- short descriptions
  - before:
    - extracted from the first sentence of the individual command doc
  - after:
    - in helpdb, the short description for plugin commands (used in `ls`, `hotkeys`, etc.) will come from the PluginCommand constructor
    - in the HTML docs the short description (planned to be used in the generated indices) for plugin commands will come from ? We need to figure this out.
  - same:
    - for scripts and plugins themselves, short descriptions will continue to come from the first sentence for both helpdb and the HTML docs

**Comment by myk002** [comment]
While we figure this out, I'll make changes to helpdb to support either organizational structure. At the very least, it will allow me to combine pages for builtin aliases.

**Comment by myk002** [comment]
Thought - how hard would it be to lex the short descriptions out of the plugin source files? Then helpdb and the generated docs would be guaranteed to be using the same strings for the plugin commands.

**Comment by lethosor** [comment]
> Afaict, no. Sphinx doesn't work that way. Directives are a way to _inject_ information, not _extract_ it. But wait, we can **pre-parse** out the directives from conf.py and build an index that way!

It should be possible to build an index based on the contents of directives. Or maybe something other than directives, if those don't work.

I don't want to encourage writing a custom parser for something that Sphinx already parses.

**Comment by lethosor** [comment]
https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#index-generating-markup seems like it could be useful.

**Comment by myk002** [comment]
I'll play with `index` a bit and see what output it produces. I'm also a little unclear on *where* this index is output, but an experimental diff should tell me pretty quickly. Thanks for the pointer!

**Comment by myk002** [comment]
Hrm, either I'm using it wrong or this is not what we think it is. Adding `.. index:: ls` to the `ls` page results in zero change to the text rendering (i.e. there is no index being generated anywhere), and the only change to the html output is
```
$ diff -r /tmp/html html
diff -r /tmp/html/docs/tools/ls.html html/docs/tools/ls.html
85c85
< <p>Usage:</p>
---
> <p id="index-0">Usage:</p>
```

so it seems to add a link target, but does not produce anything that we would call an "index".

**Comment by lethosor** [comment]
I think it should be generating a separate index page, like https://www.sphinx-doc.org/en/master/genindex.html

I will investigate

**Comment by myk002** [comment]
I think this is the culprit: https://github.com/DFHack/dfhack/blob/6e89f89b3f1600156c5638d9cc9755b11ec42eb5/conf.py#L371
