### ISSUE TITLE
digType designating below certain Z Levels

### ISSUE THREAD

**Issue by AstraAmbrosius** [DFHack/dfhack#2266]
Instead of manually having to remove designations from digType it would be convenient if at all possible to be able to designate all of one type of tile below a certain Z level.

**Comment by myk002** [comment]
Should be very doable. The z coord [here](https://github.com/DFHack/dfhack/blob/5b54f91d81f8931bb765a4a1712b2a18dd857d8f/plugins/dig.cpp#L1511) just needs to be configurable.

It might be nice if all tools that take a map bounds could use a common interface. Blueprint, for example, has a more flexible boundary selection that we could build on.
