### ISSUE TITLE
Idea: more informative quickcommand gui 

### ISSUE THREAD

**Issue by NotRexButCaesar** [DFHack/dfhack#2268]
![CFA937BB-9883-42C2-8D48-3FCD4119BA0C](https://user-images.githubusercontent.com/68972888/185804414-a7809d24-b493-4ec1-89d1-c9ed11a93ef3.png)

Shown above are four different commands: one to reveal, one to hide, one to replace a stone wall & one to remove it.  Because the gui only shows the basic command, there is no way to differentiate the different commands other than by editing them or memorising.

According to members of the Discord, this might benefit from the EditField widgit, which could show parameters for the command.

**Comment by myk002** [comment]
It is possible that this functionality should be integrated into the hotkeys rollover menu so quick commands appear in that list. Full commandlines can appear in the description textbox
