### ISSUE TITLE
Changes to `argparse` causing errors

### ISSUE THREAD

**Issue by Atkana** [DFHack/dfhack#2279]
I [had a report](http://www.bay12forums.com/smf/index.php?topic=179679.msg8405497#msg8405497) from a user of [one of my mods](https://dffd.bay12games.com/file.php?id=15871), and upon inspection it looks like it's due to some edit to `argparse` since `0.47.05-r4`. I've not really looked into what the exact problem is because I don't have the time at the moment, but you can review the error logs / see for yourself. It looks like the error is caused by my usage of `dfhack.run_script`, which as far as I can tell is properly formatted, so the problem might also affect any other scripts that also utilise that function:
```
dfhack.run_script("modtools/transform-unit", table.unpack({
		"-unit", unit.id,
		"-race", race_token,
		"-caste", caste_token,
		"-duration", "forever",
		"-keepInventory"
	}))
```

I've tried both the version of `argparse` shipped with `0.47.05-r6` as well as the most up to date version from the github repo, and both yield the same error.

**Comment by myk002** [comment]
I think the issue here is that `run_script` expects its arguments to be strings, and here some of them are numbers. There's no reason we need to be so strict at the API level, though. `run_script` should probably tostring all its args.

**Comment by myk002** [comment]
I note that the docs for `run_script` don't explicitly say that all args should be strings, but the example does indicate numbers should be stringified.

**Comment by myk002** [comment]
Looking at the history of argparse, the breakage likely occurred when I replaced
`string.sub(arg,1,1) == '-'`
With
`arg:startswith('-')`

Both assume the input is a string. The old code just apparently failed silently.

**Comment by lethosor** [comment]
FYI: that `table.unpack()` call is redundant. You can replace `dfhack.run_script(table.unpack("a", "b"))` with just `dfhack.run_script("a", "b")`. (table.unpack is most useful when you have a variable number of arguments.)
