### ISSUE TITLE
exportlegends UI revamp

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#2292]
The UI appears to freeze for a long time while `exportlegends` is doing its thing. It should show an onscreen progress bar so the user doesn't have to worry if something has hung.

**Comment by lethosor** [comment]
Any particular stages of exportlegends you have in mind? Some call out to DF, and DF performs blocking operations where we can't easily inject a progress bar. Our own "custom" data export should be possible to add progress info to, though.

**Comment by myk002** [comment]
I think it's during our custom stages that the UI appears frozen. The DF-controlled export stages do show UI activity. If we only show a progress bar for the custom export, that will probably be sufficient.
