### ISSUE TITLE
ensure foo.init runs before foo.*.init

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#2324]

**Comment by myk002** [comment]
I'm not sure what I remembered seeing that prompted me to file this bug, but it doesn't appear to be true.

**Comment by lethosor** [comment]
Here's what I'm seeing on f5d100d28c8e40dc6aff739cc2c414e49444a408:

```
Loading script: dfhack-config/init/dfhack.a.init
Loading script: dfhack-config/init/dfhack.foo.init
Loading script: dfhack-config/init/dfhack.init
Loading script: dfhack-config/init/dfhack.z.init
```
so I think it is still sorting alphabetically. Not sure it's an issue, though.

**Comment by myk002** [comment]
ok, that's a problem then. the "plain" init file should always go first for consistency.
