### ISSUE TITLE
Move dfhack-owned files out of dfhack-config/

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#2326]
like the default files.

what about the library files for professions, orders, and (soon) the control panel?

**Comment by lethosor** [comment]
I thought the library files lived under hack/?

**Comment by myk002** [comment]
I believe after discussion we decided to put them in `dfhack-config/foo/library` so users could remove them if they wanted to. I'm not sure that's a strong enough reason to keep them there, though.

**Comment by myk002** [comment]
in fact, let's remove dfhack-config/ from the release archive entirely and create it on demand so users can upgrade DFHack without fear of losing their stored data. E.g. on OSX using Archive Manager, extracting the DFHack installation will *replace* the dfhack-config/ directory, not just overwrite the contents of it.

**Comment by lethosor** [comment]
Sounds good to me
