### ISSUE TITLE
Sometimes when attempting placing a building designation for a building (for which you haven't got any stock of) out of planning mode you will see "Item      Dist Num" and pressing enter will crash

### ISSUE THREAD

**Issue by wolfboyft** [DFHack/dfhack#2358]
To replicate, maybe: use k to select a position to place a building, then without moving the cursor press b, select the type to build, press enter and see if it comes up with that state.

**Comment by myk002** [comment]
so this is when buildingplan is *not* enabled for the building type, right?

**Comment by wolfboyft** [comment]
Yeah, when you haven't used P.

**Comment by myk002** [comment]
Is this a DFHack bug or a DF bug? If buildingplan isn't involved, what part of DFHack *is* involved?

**Comment by wolfboyft** [comment]
Ack, I think it's because it usually happens *around* buildingplan and my brain took a shortcut. Do you have any advice as to how I might be able to diagnose it when I am in that state? Maybe launch my game with gdb every time and when I next see it, intentionally crash and get a backtrace?

**Comment by lethosor** [comment]
Intentionally inducing a crash will give you a backtrace of whatever the game was doing at that instant, which probably won't point to the bug.

**Comment by wolfboyft** [comment]
Perhaps there is some gui/gm-editor diagnostics to do.
