### ISSUE TITLE
Channel-Safely plugin features and implementation

### ISSUE THREAD

**Issue by cppcooper** [DFHack/dfhack#2363]
> Ugh.. I had written a whole train of thought on my phone but didn't submit it and now it's gone. Let me see what I can reconstruct.
> 
> A lot of this will be duplicating what you already have, but let me see if I can form a chain of reasoning.
> 
>     1. digging a channel is unsafe if it is likely to cause a dwarf to fall and get injured
> 
>     2. a dwarf can only fall if there is empty space under the tile that is being channeled and a dwarf is on top of the tile when it is channeled
> 
>     3. situations where a dwarf will be on top of the channeled tile:
>        a) dwarf is channeling that tile and can only approach that tile from above OR was already standing on that tile when they took the job to dig it
>        b) two channel designations are adjacent and a dwarf is standing on one designated tile while digging the other
>        c) dwarf is pathing through the tile on the way to somewhere else
> 
>     4. digging a channel is also undesirable (though not necessarily unsafe to any dwarves) if after digging the channel other designated tiles are no longer reachable
> 
> 
> So, potential algorithm.
> 
>     1. find groups of connected channeling designations (a "project)
> 
>     2. put all designations in the project in marker mode that have project tiles directly above them (so when those tiles are channeled we don't have new empty space to contend with)
> 
>     3. for unmarkered tiles that are over open space, marker them all, then unmarker a tile whose removal would not make any adjacent tile unreachable AND whose approach path does not involve a dwarf coming straight down at it. You can probably do more than one of these tiles at a time, but we'd have to think carefully about how.
> 
> 
> also, we can set all passable tiles that are being channeled as a restricted traffic area to minimize other dwarves passing through at a bad time
> 
> test cases:
> 
>     * channeling 10 z-levels straight down through rock should work. the tiles should be channeled strictly top to bottom, even if the tiles on middle levels are accessible to other miners
> 
>     * channeling a 10x10 floor area over magma should slowly dig out the tiles one by one until they are all clear
> 
>     * channeling 3 z-levels straight down through the ceiling of a cavern should stop at the last tile before the ceiling of the cavern is breached (since the path to that tile is straight down). The dwarf will become stuck.
> 
> 
> how to calculate a path? df has a cache you can use, but how to test changes to that pathing? This I don't know.
> 
> if calculating pathing is unfeasible, then the safety of channeling over open space is probably not detectable. However, if we give up the use case of channeling out passable tiles (e.g. the 10x10 floor over magma example above) then we don't need to worry about other units since no injuries are possible if we always channel from the top down. Then all we need to do is wait until the only remaining tiles in a project are unsafe (and presumably in marker mode) and no units are occupying those tiles (e.g. designated floors, stairs, etc.) and then unmarker them and call `dig-now` on those tiles.
> 
> ah, we _do_ need to worry about pathability of project tiles even when only the top-most project tile in a column is not in marker mode. consider a 3x3 area accessible from the top and channeling straight down for 10 z-levels. a dwarf can channel out the top 2 layers and dig a hole straight down for a while. that dwarf can't get back up to channel the tiles above them and other dwarves can't get down to get the remaining tiles at the higher z-levels. would it make sense to marker all tiles in a project that aren't at the maximum z-level of the project? that would force a z-level to be "cleared" before dwarves are allowed to start on the next level down. There are esoteric designs that would defeat this check like this:
> 
> ```
> d h   h j
>   h   h x
>   d d d u
> ```
> 
> where the "spire" on the right won't be accessible until the spire on the left is completely dug out. maybe we still need to respect pathability. however, for this we can use the df pathing functions since we're addressing the current map, not a hypothetical future map.

-@myk002 

> > 2. ...on top of the tile when
> 
> This made me think of an easy partial solution whereby when a job is started the plugin spawns a tick event, probably a customized lambda, to check if the job's tile is occupied by a dwarf until the event handler for ticks is unregistered when the completed job event fires. During a tick event, when the job tile is occupied we pause the job somehow.. or cancel and requeue it(?).
> 
> I think then we could ignore pathing entirely.
> 
> > 2. put all designations in the project in marker mode that have project tiles directly above them (so when those tiles are channeled we don't have new empty space to contend with)
> > 3. for unmarkered tiles that are over open space, marker them all, then unmarker a tile whose removal would not make any adjacent tile unreachable AND whose approach path does not involve a dwarf coming straight down at it. You can probably do more than one of these tiles at a time, but we'd have to think carefully about how.
> 
> I think this would be a change from what I have (or did have, at least), but I think it would be a welcome one.
> 
> What I think it currently does is effectively wait until the top-most overlapping layer of designations are finished to enable any overlapping groups' tiles from below them. And changing that, I don't think I'd need to worry about groups.. but I dunno maybe it's better to wait for the group to finish to ensure paths above aren't ruined.. but then we've maybe made digging pits more difficult to complete due to project lifespan and the size of the hole. I can foresee trapped dwarves potentially, who must dig to escape.. might just be a fun! addition to keep?

-@cppcooper 

Just thought I'd post where we left off

**Comment by cppcooper** [comment]
> would it make sense to marker all tiles in a project that aren't at the maximum z-level of the project? that would force a z-level to be "cleared" before dwarves are allowed to start on the next level down.

This is the primary mechanism for ensuring safety at the moment. I check whether two groups, that are z-adjacent, are also overlapping with any tiles. I do this with the following function, it seemed like the best insurance policy.
```cpp
inline bool has_groups_above(const ChannelGroups &groups, const Group &group) {
    // for each designation in the group
    for (auto &key_value : group) {
        auto &tile_pos = key_value.first;
        //auto &block = key_value.second;
        // check if we could potentially fall
        if (!is_safe_to_dig_down(tile_pos)) {
            return false;
        }
        df::coord above(tile_pos);
        above.z++;
        // check whether there is a non-empty group above any of the tiles in `group`
        if (groups.count(above)) {
            if (!groups.find(above)->empty()) {
                return true;
            }
        }
        // check if there is an untracked designation
        if (has_channel_designation(above)) {
            ChannelManager::Get().build_groups();
            return true;
        }
    }
    // if there are no incomplete groups above this group, then this group is ready
    return false;
}
```

NOTE: just because a job in a group is completed doesn't mean it won't take part in the above check. The groups would need to be recalculated for this to happen, which I've tried to avoid.

> also, we can set all passable tiles that are being channeled as a restricted traffic area to minimize other dwarves passing through at a bad time

Great idea.

> if calculating pathing is unfeasible

I think it is, it may be useful in one very specific case: checking if insta-dig is the only way to dig an active designation.

For other reasons I don't think it is necessary, like your example

> where the "spire" on the right won't be accessible until the spire on the left is completely dug out

I consider falling to be the only unsafe outcome. So, this doesn't sound like a safety issue, it sounds like a planning issue.

**Comment by myk002** [comment]
I agree that a simple solution is probably best to start with. I've seen requests for this kind of functionality on Reddit so we'll get requests if people want specific improvements.

Most channel projects are likely to be relatively simple up and down. We can start with that case.

**Comment by cppcooper** [comment]
> I've seen requests for this kind of functionality on Reddit

Well, if we want to get a working plugin merged.. I do believe this [commit](https://github.com/DFHack/dfhack/pull/1879/commits/935b3761b0b406e18db01221a24568c941433996) has the last verified working state.

I'll still work on upgrades, but if a simple working solution is wanted.. I had it working a while ago.

**Comment by cppcooper** [comment]
In terms of the upgrades.. here is what I'm thinking right now.

```
 Enable plugin:
 -> build groups
 -> manage designations

 Unpause event:
 -> build groups
 -> manage designations

 Job started event:
 -> validate job type (channel)
 -> check pathing:
    -> Can: add job/worker to tracking
    -> Can: set tile to restricted
    -> Cannot: remove worker
    -> Cannot: insta-dig & delete job
    -> Cannot: set designation to Marker Mode (no insta-digging)

 OnUpdate:
 -> check worker location:
    -> CanFall: check if a fall would be safe:
        -> Safe: do nothing
        -> Unsafe: remove worker
        -> Unsafe: insta-dig & delete job (presumes the job is only accessible from directly on the tile)
        -> Unsafe: set designation to Marker Mode (no insta-digging)
 -> check tile occupancy:
    -> HasUnit: check if a fall would be safe:
        -> Safe: do nothing, let them fall
        -> Unsafe: remove worker for 1 tick (test if this "pauses" or cancels the job)
        -> Unsafe: Add feature to teleport unit?

 Job completed event:
 -> validate job type (channel)
 -> verify completion:
    -> IsOpenSpace: mark done
    -> IsOpenSpace: manage tile below
    -> NotOpenSpace: check for designation
        -> HasDesignation: do nothing
        -> NoDesignation: mark done (erases from group)
        -> NoDesignation: manage tile below
```
