### ISSUE TITLE
DFHack docs SEO

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#2368]
Google searches for DFHack tools rarely take people to useful pages. Look into robots.txt and other techniques to help web crawlers grok our docs

https://docs.readthedocs.io/en/stable/guides/technical-docs-seo-guide.html

**Comment by myk002** [comment]
also see https://search.google.com/search-console/welcome for how google currently indexes the site, but it requires verification of DNS name, which only @lethosor can do

**Comment by myk002** [comment]
ReadTheDocs has the option to make a version "Hidden", which will hide the version's docs in the generated robots.txt. However, it will also hide the version's docs in the flyout menu on the docs site (where you'd choose whether you are looking at "stable" docs or some specific version's docs). I think we still want to make old docs visible there.

therefore, I think the solution is to create a custom robots.txt file. There are instructions on how to do that here: https://docs.readthedocs.io/en/stable/guides/technical-docs-seo-guide.html#use-a-robots-txt-file

**Comment by lethosor** [comment]
I submitted our sitemap just now at the Google search console:
![image](https://user-images.githubusercontent.com/3719547/202933662-824f207d-18c6-4ad1-9414-f8b2eb18731a.png)

It wasn't listing anything before, so I'm not sure if that sitemap was being used.

**Comment by myk002** [comment]
our sitemap.xml file *is* listed in our current autogenerated robots.txt, but that doesn't mean it was ever successfully used. Hopefully registering it will help here.
