### ISSUE TITLE
"forbid unreachable" tool

### ISSUE THREAD

**Issue by ab9rf** [DFHack/dfhack#2421]
In relation to #2418, #2417, and #1473, I wrote a quick and dirty ruby script some years ago that will forbid any unreachable items. Anyone who wants to reimplement it in lua is welcome to do so. It appears below (it's very short).

``` ruby
DFHack.world.items.all.each { |item|
    if not item.flags.in_inventory then
        pos = item.pos
        mb = DFHack::map_block_at(pos)
        mt = DFHack::map_tile_at(pos)
        if (mb and mt) then
            w = mb.walkable[mt.dx][mt.dy]
            if w == 0 then
                item.flags.forbid = true
            end
        end
    end
}
```

**Comment by myk002** [comment]
This check would be very useful inside `unforbid`. It could avoid unforbidding unreachable items unless a flag is passed
