### ISSUE TITLE
Autochop should not designate inaccessible trees

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#2424]
This includes trees on isolated islands and trees whose roots are underwater.

**Comment by ab9rf** [comment]
This one shouldn't be too hard

**Comment by myk002** [comment]
Would this work? for all adjacent tiles, if any are isPathable() from any citizen with woodcutting, then tree is choppable?

pathability is cached, so this *shouldn't* be too expensive, I think.

**Comment by ab9rf** [comment]
i was going to use walkability tags, but that's essentially the same test
