### ISSUE TITLE
Distribute DFHack on Steam

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#2428]
DFHack should be as easy to keep updated as the base game. We should find a way to distribute DFHack releases on steam to complement the "manual" download from our GitHub page.

Option 1: self publish
This keeps everything under our control, but is also the most process-heavy, costly ($100), and least tied to Dwarf Fortress and Kitfox, which means that it won't show up as a recommended download on the official Dwarf Fortress page. However, those who download DFHack this way *will* get automatic updates.

Self publishing will install DFHack in a directory separate from DF. SKSE loads itself via the steam overlay, or if the player has disabled the steam overlay, SKSE can be started from skse_loader.exe in the SKSE directory. We can likely do something similar.

Option 2: become an official DLC
The developer will be listed as DFHack Team and the publisher will be Kitfox. DFHack will be listed on the main game page as additional content.

A significant plus for this and the next option is that mods can register a dependency on DFHack and DFHack can get automatically recommended/installed when a player installs a mod that uses DFHack.

Still investigating this, especially around how to handle staggered updates (i.e. what happens when DF is updated and there's no version of DFHack for that version yet?)

Option 3: be a steam workshop mod
Still investigating this

**Comment by warmist** [comment]
Option 3 imho would be best if possible by the system. It might need us to change our file system and ask today to do something strange (e.g. check if sdl.dll is subfolder and try loading that first)

**Comment by Moth-Tolias** [comment]
option 2 sounds ideal. official endorsement would be nice

**Comment by ab9rf** [comment]
option 3 requires explicit support in the application to load the DLL, which we are not likely to get as it would require Toady's explicit cooperation

option 2 requires explicit cooperation from kitfox to list dfhack as a DLC and will leave us at kitfox's mercy regarding what dfhack is allowed to do and when updates can be published. we would also have to be ready to publish updates whenever kitfox requires it

option 1 is the only one that leaves us free to put whatever _we_ want into dfhack, and to update when we are able and willing to do so

**Comment by silverwing235** [comment]
Hey there. I pretty much always did back Option 1 in the event of this, myself.

**Comment by Moth-Tolias** [comment]
> option 2 requires explicit cooperation from kitfox to list dfhack as a DLC and will leave us at kitfox's mercy regarding what dfhack is allowed to do and when updates can be published. we would also have to be ready to publish updates whenever kitfox requires it

if steam dlc is required to be compatible with the latest version, then it probably wouldn't be a good fit for dfhack considering it's all volunteer work. i don't suppose kitfox would much enjoy combing over it for raise-mermaid-bone-value.lua either, so option 2 looks much less attractive.

> option 3 requires explicit support in the application to load the DLL, which we are not likely to get as it would require Toady's explicit cooperation
> 
> option 1 is the only one that leaves us free to put whatever _we_ want into dfhack, and to update when we are able and willing to do so

i was under the impression that toady [and by extension, kitfox] was in the habit of cooperating when it comes to dfhack. is this not the case? also, wouldn't option 1 still be affected by valve bundling sdl?

**Comment by myk002** [comment]
They are potentially cooperative for option 3, but it might take a while.

I think it might be best to start with option 1 and move to option 3 if/when it becomes feasible.

**Comment by ab9rf** [comment]
i actually think that we can get toady to throw in hooks for nearly anythign as long as we explain precisely what we want and it's not too hard for him to implement. it's not like he's trying to obstruct what we do

**Comment by papercrane1001** [comment]
If you don't mind a newcomers suggestion, you could use the steam workshop method the same way this group has:
https://steamcommunity.com/sharedfiles/filedetails/?id=1847679158

To summarize, have the steam workshop mod be virtually useless, but contains a link to github for installation of the actual program.

**Comment by myk002** [comment]
That's not a bad idea. In our case, we could even distribute *most* of DFHack as a steam workshop mod and just require a separate download for a loader/launcher (which would not need to be updated on every version)

**Comment by MartinX3** [comment]
Nice!
Will there be an announcement after it became available in the workshop?

**Comment by myk002** [comment]
It won't be on the workshop -- it has to be a separate steam app -- but there will definitely be an announcement. Still a bit of work to do before anything goes live. Maybe a month or so.
