### ISSUE TITLE
improve df_import_structures

### ISSUE THREAD

**Issue by ab9rf** [DFHack/dfhack#2482]
This is actually an issue in the df_misc repository, but I'm putting it over here since "wanderers" are more likely to come here than to df_misc and I'm kinda hoping to recruit a ~~victim~~volunteer to work on this project.

We currently have a [script](https://github.com/DFHack/df_misc/blob/master/import_df_structures.java) (in Java, run within Ghidra) that parses the output of our structures definition files (in XML) and converts that to structure definitions inside ghidra. it currently does this "all at once" which means it tries to overwrite (and usually fails) any existing definitions.

What we'd like to do is have a version that can (a) be run to update only one, or some subset, of datatypes or (b) compare the datatype derived from the structure definition files with the datatype already in ghidra, and give the user the option to update the datatype in ghidra or not. Probably the easiest change to make is to add a dropdown or text entry field for "type to replace" and then only replace that type.

Another "nice to have" would be something that goes in the opposite direction: given a ghidra data type, generate the structure definition update. that's a lot harder.

At the moment when we find something that needs to be updated in structures, we have to manually update both the structures in ghidra and the structures in the structures repo. it would be nice if we could single-source that, or at least provide some means of cross-checking that the parallel updates match.

Even fixing the importer so it can be run more than once without going *brrrt* would be an improvement, since otherwise we have to blow away the entire analysis repo, reload, and start over, and a full auto-analysis of DF takes a lot of time plus we lose any analysis that's in the repo or have to tediously copy it over to the new one.

**Comment by Akiira** [comment]
I have spent some time reviewing the script and Ghidra api. I would like to replicate the expected work environment so I can actually test changes I make to the script. What is needed to do this? I have Ghidra installed but am not familiar with it. I assume I need to have it read in the dwarf fortress binary?

**Comment by ab9rf** [comment]
yes, you will need to load the dwarf fortress binary into ghidra

- you will need an appropriate copy of df-structures
- - for 50.0x use the most recent version of ab9rf/df-structures or quiestust/df-structures, whichever is newer (we will merge our working versions into dfhack/df-structures once we're done with the first phase analysis)
- - for 47.05 use the master branch of dfhack/df-structures
- locally clone whichever of these repos is appropriate to your use case
- in the df-structure clone you have chosen, run `perl codegen.pl`; this will generate the `codegen.out.xml` you need for the import process
- put a copy of the java script in one of ghidra's script directories (on windows, `%USERHOME%\ghidra_scripts` works, for other environments I imagine it's somewhere similar; script directories are configurable within ghidra)
- launch ghidra and create a workspace
- import the df binary you wish to analyze into ghidra
- do _not_ allow ghidra to auto-analyze the imported program
- open the script manager from the program listing screen
- find the `df_import_structures` script in category `DFHack` 
- - if it's not there, it's because the folder you have it in is not known to ghidra as a script directory, either move it to one of ghidra's script directories or add the folder it's in as a script directory in ghidra
- run the script
- the script will ask for the path to `codegen.out.xml` and `symbols.xml`. `codegen.out.xml` is in the `codegen` subfolder of the df-structures repo, and `symbols.xml` is in the top level of that same repo
- - if you use a version of df that we haven't analyzed, you'll get some unpleasant errors, otherwise the script will just start running. output goes to the ghidra console which can be a little hard to notice

if you have questions catch me on discord
(and yes, we should probably document this)

**Comment by paxman101** [comment]
> I have spent some time reviewing the script and Ghidra api. I would like to replicate the expected work environment so I can actually test changes I make to the script. What is needed to do this? I have Ghidra installed but am not familiar with it. I assume I need to have it read in the dwarf fortress binary?

Consider looking over https://github.com/DFHack/df_misc/pull/20 once you get an environment up. I believe it fixes the underlying issue that causes errors when running the script on existing data, but there is still improvements to be made wrt letting the user choose what gets overwritten and other features mentioned in this issue.
