### ISSUE TITLE
Game crashed when using create_items

### ISSUE THREAD

**Issue by alirezahemiten** [DFHack/dfhack#2488]
Game crashed when using create_items plants MUSHROOM_HELMET_PLUMP or any other plants through new GUI

**Comment by myk002** [comment]
oh, it's a ruby script : p
this script will be turned down or migrated to Lua before the next release. in the meantime, consider `gui/create-item --multi`

**Comment by myk002** [comment]
We did find the conflict for this, if you need a short-term fix for this issue. Ruby scripts cannot run at the same time as a lua script. Disabling the overlay (`disable overlay`) will avoid this conflict.
