### ISSUE TITLE
df_import_structures should import comments from df-structures into ghidra

### ISSUE THREAD

**Issue by ab9rf** [DFHack/dfhack#2489]
if there is a comment in df-structures for a field, put that in the comments in the ghidra type def'n
in addition, if df-structures specifies an init-value, append that to the comment (enclosed appropriately)

**Comment by lethosor** [comment]
Assuming this is the same as https://github.com/DFHack/df_misc/issues/19 and therefore resolved by https://github.com/DFHack/df_misc/pull/23
