### ISSUE TITLE
Add a label to gui/launcher for what the command list means

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#2503]
add a label at the top that says "autocomplete" when it's the "complete what I've typed so far" list and "related tools" when it's the related list

**Comment by vallode** [comment]
It's a tough spot to put a proper label. Something like this could work:

![image](https://user-images.githubusercontent.com/18506096/214448947-07f345d1-8e36-4a5a-a35d-8af045a67fbf.png)

`All scripts`, `Autocomplete`, `Similar scripts` are three possible states?

**Comment by myk002** [comment]
That sounds brilliant. Would you like to add it?
