### ISSUE TITLE
timestream causes dwarves to not pick up work

### ISSUE THREAD

**Issue by TSM-EVO** [DFHack/dfhack#2611]
using `timestream --rate 2` seems to work okay but using `timestream --units --fps 500` stops dwarves from doing work like cutting stone blocks or brewing

```
> timestream --units --fps 500

timestream: Time running dynamically to simulate 500 FPS.
timestream: Unit simulation is on.
```
I'm having trouble reproducing this consistently, sometimes jobs will carry on. I'm also getting game crashes on a big fort with this enabled, setting the --rate to a high value seems to affect this. Is there a way to debug this plugin further?

**Comment by myk002** [comment]
Note that 500 is a *lot*. Does it work better with 100?

**Comment by TSM-EVO** [comment]
> Note that 500 is a _lot_. Does it work better with 100?

When I set it to 100 it doesn't seem to cause issues but it also doesn't seem to have much effect, maybe my big fort isn't heavy enough to notice a difference.

**Comment by myk002** [comment]
fixed by not skipping important ticks
