### ISSUE TITLE
tailor doesn't queue up new tailoring tasks.

### ISSUE THREAD

**Issue by TSM-EVO** [DFHack/dfhack#2618]
I have tailor enabled, all settings enabled in a fort with everything needed to make new clothes. 

I get the confiscation message in console:
`Confiscating and dumping a worn item:   [16602] pig tail shoe (wear level 2), owner `Beech' Olinrag
....`

but no work orders are created. I checked this by forbidding my clothiers workshops and using `orders clear`. No new orders are created after the confiscation.

**Comment by TSM-EVO** [comment]
Update:

**Comment by TSM-EVO** [comment]
Update; new version of `tailor`  and DFHack -
`DFHack version 50.05-alpha1 (development build 50.05-alpha1-22-g298736d9) on x86_64 [build ID: 230120000]`

I've created a save w/no mods. There's dwarves with worn clothing and dwarves missing clothing (For example, "Threetoe" or "Elboron"). 

Save File, full folder: https://file.io/t7hbulFGTn3R

How to reproduce "issues"

Load save, hit F3 to see tailoring industry section. Check Stocks (lots of cloth, silk and yarn), check orders (empty). enable `fastdwarf 1 1` to make it faster to do the jobs if you like.

`enable tailor`. Let it run, at this point the dwarves have already dumped their worn clothes in the dumping pile at F3, tailor won't confiscate more items it seems. 

Now, do an `unforbid all` and watch the dump at F3, dorfs will come pick up items, which will be dropped again when `tailor` does another check. You can let the save run for a little while, a migrant wave comes and dumps their threadbare stuff as well, but no new ones get queued and a bunch of dorfs run around a bit naked. I also used dwarf therapist to see the number of naked body parts. 

The documentation says:

> Whenever the bookkeeper updates stockpile records, this plugin will scan the fort. If there are fresh cloths available, dwarves who are wearing tattered clothing will have their rags confiscated (in the same manner as the [cleanowned](https://docs.dfhack.org/en/stable/docs/tools/cleanowned.html#cleanowned) tool) so that they’ll reequip with replacement clothes.

In this save, if there are fresh clothes, dwarves will pick them up without any message. To see this, try making a pair of socks and watching the log. You'll see a dwarf come get the new socks without any confiscation happening. If a bunch of new dwarves show up with worn clothes, it'll mass confiscate. 



> If there are not enough clothes available, manager orders will be generated to manufacture some more. tailor will intelligently create orders using raw materials that you have on hand in the fort. For example, if you have lots of silk, but no cloth, then tailor will order only silk clothing to be made.

This part is currently not happening. Do the cycle of unforbid all -> enable tailor -> dwarves dump worn items but no new ones get queued up.

**Comment by TSM-EVO** [comment]
Can I leave an idea here as well:


It seems that `tailor` doesn't confiscate `x` small x (worn) worn clothes, only `X` big X (threadbare) clothes. 

Once it's able to create work orders, it would be really helpful if it would check for small x worn clothes and create work orders to create items.

**Comment by ab9rf** [comment]
loaded the provided save, bumped tailor debug logging to max, forced a scan with `tailor test`
```
tailor: MakeArmor times 89 of size 6000 ordered
tailor: MakeShoes times 93 of size 6000 ordered
tailor: MakePants times 83 of size 6000 ordered
tailor: ordering 41 tunics
tailor: material silk skipped due to lack of reserves, 2 available
tailor: added order #241 for 41 cloth tunics, sized for dwarves
tailor: ordering 133 dresses
tailor: material silk skipped due to lack of reserves, 2 available
tailor: order reduced from 133 to 67 to protect reserves of cloth
tailor: added order #242 for 67 cloth dresses, sized for dwarves
tailor: added order #243 for 66 yarn dresses, sized for dwarves
tailor: ordering 165 trousers
tailor: material silk skipped due to lack of reserves, 2 available
tailor: material cloth skipped due to lack of reserves, 10 available
tailor: order reduced from 165 to 48 to protect reserves of yarn
tailor: added order #244 for 48 yarn trousers, sized for dwarves
tailor: order reduced from 117 to 113 to protect reserves of leather
tailor: added order #245 for 113 leather trousers, sized for dwarves
tailor: ordering 172 gloves
tailor: material silk skipped due to lack of reserves, 2 available
tailor: material cloth skipped due to lack of reserves, 10 available
tailor: material yarn skipped due to lack of reserves, 10 available
tailor: material leather skipped due to lack of reserves, 10 available
tailor: ordering 178 shoes
tailor: material silk skipped due to lack of reserves, 2 available
tailor: material cloth skipped due to lack of reserves, 10 available
tailor: material yarn skipped due to lack of reserves, 10 available
tailor: material leather skipped due to lack of reserves, 10 available
tailor: ordering 267 socks
tailor: material silk skipped due to lack of reserves, 2 available
tailor: material cloth skipped due to lack of reserves, 10 available
tailor: material yarn skipped due to lack of reserves, 10 available
tailor: material leather skipped due to lack of reserves, 10 available
```
![image](https://user-images.githubusercontent.com/1445859/213791991-597fe2b4-4a42-4d6b-9861-554df41a59b2.png)

looks to be working as designed to me

the plugin is not counting the silk as available because it is not dyed; tailor only used dyed cloth even if the "use any cloth" standing order is selected; i will change this in the next release

**Comment by TSM-EVO** [comment]
I just downloaded the latest build and deleted my /hack/ folder.  `DFHack version 50.05-alpha1 (development build 50.05-alpha1-51-gac483ed1) on x86_64 [build ID: 230120010]`

Re-loaded the save, and new tailor jobs got queued. 
```
[DFHack]# tailor test
tailor: added order #242 for 41 cloth tunics, sized for dwarves
tailor: added order #243 for 72 cloth dresses, sized for dwarves
tailor: added order #244 for 61 yarn dresses, sized for dwarves
tailor: added order #245 for 53 yarn trousers, sized for dwarves
tailor: added order #246 for 112 leather trousers, sized for dwarves
tailor: added order #247 for 1 leather glove, sized for dwarves
```


I would say it's working now, I guess it just wasn't working in build 230120000 or prior? Or maybe my /hack folder had something that was preventing it from working. Either way, probably good to close this issue now.
