### ISSUE TITLE
"changelayer" command broken!

### ISSUE THREAD

**Issue by Yigitcan57** [DFHack/dfhack#2625]
I tried changing some layers to limestone, that worked perfectly but I cant use limestone at all. I can see limestone boulders at stocks list but I cant place/build/cract anything from it. Here is a screenshot.

https://imgur.com/a/tU6uJVT

**Comment by lethosor** [comment]
I suspect this might be DF's economic stone handling. Try changing limestone from economic to non-economic (not sure which menu off the top of my head - possibly stocks?)

**Comment by Yigitcan57** [comment]
> I suspect this might be DF's economic stone handling. Try changing limestone from economic to non-economic (not sure which menu off the top of my head - possibly stocks?)

I tested it and you are right. When I change it with mudstone it worked. However I dont know how to change limestone to non economic + If i do that limestones no longer be used for steel and quicklime production isnt it?

**Comment by Yigitcan57** [comment]
> I suspect this might be DF's economic stone handling. Try changing limestone from economic to non-economic (not sure which menu off the top of my head - possibly stocks?)

Oh you are right. I tested it with mudstone and it works. Its from labor-stone use menu. Its normally checked in vanilla thats why I confused. Thanks you very much.

Guess I cant delete the post. Sorry for that

**Comment by lethosor** [comment]
It depends on the stone type. This feature is intended to keep dwarves from building with valuable materials, e.g. ores, by default, but you can change it.
