### ISSUE TITLE
Quickstart says to first run "orders import library/basic" despite file not only not existing, but directory as a whole

### ISSUE THREAD

**Issue by themaster567** [DFHack/dfhack#2630]
There is no dfhack-config/orders directory, and thus no files to run. A cursory look using github's search seems to suggest the files don't exist in this git at all.

**Comment by ab9rf** [comment]
they're in `hack/data/orders` of the release build zip file

**Comment by lethosor** [comment]
Have you launched DFHack yet? That should create the dfhack-config directory, at least.

If this doesn't help, please specify your DFHack version.

**Comment by ab9rf** [comment]
my guess here is that `orders` only checks `dfhack-config/orders` for its datafiles, and does not fall back to checking `hack/data/orders` as a fallback

**Comment by myk002** [comment]
We specifically just moved library files out of dfhack-config/ so the files in there are all owned by the user. If the orders directory is empty, only library files are listed. I take it that in this case if the orders directory doesn't even exist then library files are not accessible?

**Comment by ab9rf** [comment]
the plugin is set up to check `dfhack-config` and `hack/dfhack-config-defaults` but there is nothing in `hack/dfhack-config-defaults` for it to use, instead the standard library is in `hack/data` which it does not know to look in

either the plugin needs to look in `hack/data` or the standard library needs to be moved to `hack/dfhack-config-defaults`

**Comment by myk002** [comment]
Report with Reddit with some details:

I exported a work order list from what I already had and it created an 'orders' folder in my dfhack-config folder with only my Test.json file in it. I moved over the basic, furnace etc. json files over to that orders folder and tried importing it again but didn't work. Then tried importing my Test.json file and it said 

Output from command run from gui/launcher:

\> orders import library/Test

Cannot find orders file: dfhack-config/orders/library/Test.json

Hopefully this helps, not sure what info would be most useful for you.

**Comment by themaster567** [comment]
> they're in `hack/data/orders` of the release build zip file

Good to know, at least I can fix it manually.

> Have you launched DFHack yet? That should create the dfhack-config directory, at least.
> 
> If this doesn't help, please specify your DFHack version.

I launched it and ran through testing each command on a fresh fort, and noticed that no files mentioned for the order command were valid. I'm using the latest version that came out yesterday.

**Comment by Amadeus99** [comment]
If you move the orders to "<Dwarf Fortress directory>/dfhack-config/orders", then you can use "orders import basic" to load the basic.json.  Using "library" doesn't work because there is no library folder under orders.
