### ISSUE TITLE
Script pulling civilization diplomacy data doesn't actually return data.

### ISSUE THREAD

**Issue by blaxout1213** [DFHack/dfhack#2631]
The script below has different outputs from a nightly build (0.47.05-r8-406-g39f79305) than from the 50.05-alpha1 build, which results in the script not working at all on the new alpha build

This was tasted on a save that is at war with its parent civilization. I'll post the outputs below

![dfhacknightly](https://user-images.githubusercontent.com/5104534/213027181-8a5e3bf8-8ebe-4fa5-aef4-ecc1aec69602.png)

![dfhackalpha1](https://user-images.githubusercontent.com/5104534/213027216-4cd3af47-3098-459e-8f9c-98c8b4cbdfd7.png)

As the output shows, Alpha-1 for 50.05, for whatever reason, has no data whatsoever, and obviously the script doesnt do anything then. The save was reloaded specifically for this demonstration. I may also be dumb, and may be missing something. Im new to this, and just want to get caravans and migrant waves again, even when my civilization keeps trying to kill itself.

Also side note, having a script to fix civil wars included would be very very nice <3.

```-- Force peace with hostile parent civilization
--[====[

fix/civil-war
=============
Reset diplomacy relationship of parent civilization to end a civil war.

]====]

local civ = df.historical_entity.find(df.global.plotinfo.civ_id)

for k,v in pairs(civ.relations.diplomacy) do
	print(v.relation)
    if v.group_id == civ.id and v.relation > 0 then
        v.relation = 0
        print("Civil war removed")
    end
end

**Comment by ab9rf** [comment]
this is probably due to an alignment problem in `historical_entity` that we discovered this evening chasing a different problem
