### ISSUE TITLE
quickfort/blueprint doesn't allow for material selection, acting always like "Use closest material"

### ISSUE THREAD

**Issue by omgpointless** [DFHack/dfhack#2632]
When using a /construct blueprint, i.e. build walls for a room instead of digging them out, the constructed walls behave as if you had selected "Use closest material" during build.

As far as I can see there is no way to change this or select material.

To make the /construct fully usable some form of material selection should be implemented so that the user can implement the blueprint and have it using the same resources on the whole build. As it stands, it's close to unusable in that mode.

Thanks for all your work, this thing is amazing.

**Comment by myk002** [comment]
Material selection is part of buildingplan, which quickfort relies on to attach items to buildings. This issue should be solved once buildingplan is fully functional.
