### ISSUE TITLE
Suggestion (Steam Edition): Ability to save and load mod order when creating a new world

### ISSUE THREAD

**Issue by wgoff194** [DFHack/dfhack#2633]
I have been having fun playing the game and messing around with the various mods on the Steam Workshop! As you know, when you try a new mod you have to create a new world. At this point load order is not saved between sessions and can be tedious to re-setup every time.

Example: If a certain mod has to go before another mod or even before or replacing vanilla game files. 

Is it possible to have this be saved and loaded via DFHack?

**Comment by lethosor** [comment]
Are mods steam-specific, or can Itch/Classic builds load them as well?

**Comment by wgoff194** [comment]
> Are mods steam-specific, or can Itch/Classic builds load them as well?

To be honest I've never tried the non-steam version. The steam version has a gui for setting load order for workshop mods when generating a map. A number of these mods look like they were created on the same basis as the original game by just overwriting base data and settings for the game
.

**Comment by ab9rf** [comment]
iirc, classic and itch editions can load mods from the user's local mod repository. integration with the steam workshop is available only with the steam edition

**Comment by myk002** [comment]
This functionality is now offered via `gui/mod-manager`
