### ISSUE TITLE
Copying onMapLoad_dreamfort.init to init folder crashes game once emarked

### ISSUE THREAD

**Issue by themaster567** [DFHack/dfhack#2636]
Tested it pretty simply by just copying the file out of the example directory and into the init folder. Game crashes once it begins loading the map when it is present, game doesn't when not.

I ran each command one by one and determined that lines 33 through 41 (enabling automelt, tailor, and autonestbox) may be the culprit, as DFHack doesn't recognize any of them as they presumably have not been ported yet.

**Comment by lethosor** [comment]
Enabling a nonexistent plugin won't crash the game, especially not later - it will only print an error.

When does the game crash? When loading, when doing something specific later, etc?

**Comment by themaster567** [comment]
It crashes the very instant it starts loading the map, before it even has a chance to begin autosaving on embark.

**Comment by ab9rf** [comment]
confirmed, this is due to a structure misalignment in `historical_entity` which we just found and are working on a fix

**Comment by themaster567** [comment]
"repeat -name warn-starving -time 10 -timeUnits days -command [ warn-starving ]" from the file crashed the game when I ran it on this fort. I'm pretty sure I've successfully run it before. I'm assuming this is related to aforementioned misalignment?

**Comment by myk002** [comment]
Likely, yes, but we'll need more testing after the next release. It's unfortunate that I can't reproduce any of these crashes on Linux.
