### ISSUE TITLE
`ban-cooking` is too noisy

### ISSUE THREAD

**Issue by ab9rf** [DFHack/dfhack#2642]
`ban-cooking` generates hundreds of lines of output for fairly routine invocations, obliterating any other messages that might be in the console and generally being annoying, especially when called as from automation

i therefore suggest that the tool should not list _each_ item banned if there are more than about 10 or so, instead just reporting a count

**Comment by Moth-Tolias** [comment]
could a --verbose flag be useful?

**Comment by myk002** [comment]
yes, that sounds like a good idea. wanna write it?

**Comment by Moth-Tolias** [comment]
testing on v50 isn't possible currently as we only own the itch version - are there any changes that would prevent ban-cooking as it currently exists from working on v47? if not we would be happy to give this a shot.

**Comment by Moth-Tolias** [comment]
got interested and tried it anyway lol. still untested though
