### ISSUE TITLE
Suggestion: Bring back up, down, up-down stairs somehow

### ISSUE THREAD

**Issue by robindegen** [DFHack/dfhack#2644]
The new "intuitive" stairbuilding works for most cases but in some cases I found it to be quite a pain to make it do exactly what I want. Is it possible for dfhack to bring back the old stairs somehow; maybe next to the existing system?

**Comment by myk002** [comment]
yeah, I've been trying to think how to best present that functionality. You can do it now with `quickfort`, since it applies designations tile by tile, but that's not as convenient as it should be. Perhaps a stand-alone tool: `gui/stairmaster`

**Comment by robindegen** [comment]
Thanks I'll look into quickfort. A separate ui to properly designate them would be great though yes.

**Comment by Kiloku** [comment]
As a workaround, I managed to use tiletypes to change a tile to the specific type of stairs I needed. But of course, that's not the same as having the dwarves properly build it.

**Comment by myk002** [comment]
This should be solved with the updated `buildingplan` (still in development)
mockup screenshot:
![image](https://user-images.githubusercontent.com/977482/218404527-e52ef107-b360-4a79-ac17-8f2e3a787c3a.png)
