### ISSUE TITLE
dig-now interacts strangely with reveal

### ISSUE THREAD

**Issue by ab9rf** [DFHack/dfhack#2653]
dig-now appears to only dig tiles that are not adjacent to open space if used while the map is (or, possibly, has previously been) revealed

it is also possible that this is due to some tiles having had their dig designations removed because dig jobs had been assigned

**Comment by cppcooper** [comment]
Do we have a solid idea of how/when the designations have jobs created for them to replace the map designations? I know from experience that it isn't when a dwarf is given a designation to perform but [at least sometimes] beforehand.

I can also say that my experience with dig-now not doing what you'd expect was in fact verifiable to be a result of those designations being on the job list. I basically always use `reveal` when I'm in planning mode for my forts. While I was able to explain my experience with dig-now and reveal, I cannot rule out there being an additional edge-case present here.

Not digging designations that have a job associated to it is what issue #2471 reports on. So if other possibilities can be ruled out I imagine we can close this.

**Comment by ab9rf** [comment]
agreed this is probably a dup of #2471, closed as duplicate
