### ISSUE TITLE
DFHack 50.05-alpha1 - Fastdwarf teleport not working

### ISSUE THREAD

**Issue by robindegen** [DFHack/dfhack#2660]
Running fastdwarf 1 1 prints the confirmation that teleporting is enabled, but the dwarves don't actually teleport. They do move faster however. Tested with the steam version.

**Comment by JezaGaia** [comment]
Seems that the bug not global as it works perfectly in my game.
I have a mod from the workshop that already gives the dwarfs speed so I tried fastdwarf 0 1 and they started teleporting, I even tried fastdwarf 1 1 for science and they are faster too.
Didn't try it out in "vanilla "tough as the release came midgame and I didn't make a specific world to try it out.

**Comment by robindegen** [comment]
My game is vanilla. I can make a video about it if needed. Let me know if you need more information or if i should try certain things.

**Comment by lethosor** [comment]
@JezaGaia what DFHack version are you using?

**Comment by lethosor** [comment]
@robindegen to confirm, what does `fastdwarf 0 1` do for you?

And can you verify that `help` prints `DFHack 50.05-alpha1`, with no additional information in the version number?

**Comment by robindegen** [comment]
```
DFHack is ready. Have a nice day!
DFHack version 50.05-alpha1 (release) on x86_64
```

I recorded a video. I tried both again, and in neither cases do they teleport. With 1 1 they just move faster; thats it.

https://www.youtube.com/watch?v=3Zkm-DavidA

**Comment by lethosor** [comment]
@robindegen does the issue persist in alpha2 or later?

@wolfboyft any idea if https://github.com/DFHack/dfhack/pull/2374 could be related?

**Comment by robindegen** [comment]
@lethosor From what I can see a lot of things work since I'm seeing them blink around now; however hauling doesn't. For hauling they will still just move regularly (or fast with fastdwarf 1 1) and never teleport.

**Comment by wolfboyft** [comment]
So just to clarify: when they are currently holding an item and moving with it, they move quickly, but otherwise they teleport? hat about when they are in a hauling job but haven't picked up the item yet?

**Comment by robindegen** [comment]
@wolfboyft I have to look in greater detail when exactly it works and when it doesn't when I have some time. I will get back to you about that.

**Comment by wolfboyft** [comment]
Can confirm they teleport for hauling with `fastdwarf 0 1` and `fastdwarf 1 1` in 47.

**Comment by lethosor** [comment]
Could also be a DF behavior change in v50

**Comment by myk002** [comment]
yeah, I'm pretty sure everything was working as intended in 0.47

**Comment by robindegen** [comment]
I can confirm that teleportation does not work if they're using a wheelbarrow. It doesn't seem to matter if it is empty or not; if they have one; they will not teleport. It doesn't matter when the command was entered; the wheelbarrow causes them to never tp.

It looks like teleporting does work if they're just carrying it in alpha2, but i have to look deeper if this is in all cases.

**Comment by lethosor** [comment]
Do you know if the wheelbarrow limitation was also present in 0.47?

The teleport feature works by teleporting dwarves to their "destination position", which is determined by DF. In a typical case where dwarves are walking, this is their final destination. When they're pushing a wheelbarrow, it's possible that DF is setting their destination tile to the next step along their path, and if that's the case, fastdwarf simply doesn't have the information it needs to teleport those dwarves.

You can visualize a unit's full path using `devel/unit-path` to check this, although I think it only works in 0.47 at the moment.

**Comment by Caotical** [comment]
the above still remains in 50.09-r4 but if I leave the teleport options running for too long I'll invariably end up with multiple teleporters stuck in random unexplored unmined locations, unable to move. with me only discovering their captivity due to the starving/dehydrated warning.
