### ISSUE TITLE
DFHack window system behavior spec

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#2666]
Copying summary from discord until we can formalize it a bit:

I would summarize it as
- problems with ZScreens accepting plain letter keys:
    - some screens should allow map movement with wasdce, similar to old sidebars
    - minimized ZScreens should allow all input to pass through to DF, aside from their unminimize key (hang on, isn't this the case already?)
- problems with ZScreens accepting modified keys:
    - they conflict with some of our keybindings that have no context
- problems with adding contexts to keybindings:
    - this will prevent keybindings from firing e.g. when ZScreens are open on top of dwarfmodest, even if the user wants them to fire
I might have missed a couple things
it's possible we could resolve some of the keybinding issues by introducing more flexibility to the context matcher
e.g. give dfhack_viewscreen an isOverlay() vmethod that allows screens to say "pretend I'm actually my parent screen"
myk002 — Today at 6:30 PM
There's nothing special now about minimized ZScreen windows. they just don't tend to have many hotkeys on them
Lethosor — Today at 6:31 PM
we might actually be close to that with dfhack_viewscreen::getFocusString(), but it does automatically prepend a dfhack/lua/ prefix for lua viewscreens, in some way I haven't been able to track down yet
yeah, but IMO, Ctrl-K = autodump should work if you have minimized gui/autochop open
if you have maximized gui/autochop open, on the other hand, maybe Ctrl-K shouldn't work

I guess another useful thing to consider is the types of screens we're dealing with:
- full-screen (rare, but easy and consistent with how things used to work)
    - similar, just with different render(): dialogs that don't allow interaction with screens below them (gui/launcher?)
- screens that appear over the map but provide no (or minimal: alt-m) interaction (e.g. minimized gui/autochop)
- screens where the user can interact heavily with them and the map at the same time (e.g. blueprint, maximized gui/autochop?)
in particular, the second case (minimal interaction) is one where keybindings could conceivably have different semantics

**Comment by myk002** [comment]
Let me see if I can represent the needs of the GUI tools I think I understand in spreadsheet form so we can look for patterns:
https://docs.google.com/spreadsheets/d/1hiDlo8M_bB_1jE-5HRs2RrrA_VZ4cRu9VXaTctX_nwk/edit#gid=215906712

**Comment by myk002** [comment]
Thoughts:

- Some tools will want to pause the game while they have focus. We should add an indicator to the window title bar if the tool is preventing the game from being unpaused.
- Most tools should be able to be defocused and sent into the background, which would prevent them from handling keyboard and mouse input (unless they were clicked on (focused and raised) or rclicked on (closed) directly). Defocused windows will have focus string passthrough, focused windows will be represented in the focus string. With this mechanic, the hotkey conflict complications we were talking about would just go away. I think if we implement "click somewhere else to defocus" then we could completely remove the pinning mechanism for an overall reduction in interface complexity.
- Every tool should allow the map to be dragged with the middle mouse button unless they have a specific reason not to. this should not defocus the window.
- No window will pass keyboard events through while they have focus. We may want to make an exception for spacebar to unpause if the window does not force pausing and does not otherwise handle the spacebar.

**Comment by lethosor** [comment]
IMO, gui/launcher should pause, because commands are likely to include characters (space) that conflict with the pause hotkey.

**Comment by myk002** [comment]
yeah, that's now the default, and will be configurable with the upcoming `gui/control-panel` (or a short lua command from the docs). players can also click on the pause/play buttons as normal too.

**Comment by lethosor** [comment]
My 2¢, unrelated to the issue at hand, is that it would be nice if such commands could have a CLI of sorts (possibly `gui/control-panel set-foo bar`) as opposed to a Lua snippet. Not sure which you were referring to.

**Comment by myk002** [comment]
The Lua snippets are in Lua API.rst. e.g.

```
The speed of scroll events when the mouse button is held down is controlled by two global variables:

SCROLL_INITIAL_DELAY_MS
The delay before the second scroll event.

SCROLL_DELAY_MS
The delay between further scroll events.

The defaults are 300 and 20, respectively, but they can be overridden by the user in their dfhack-config/init/dfhack.init file, for example:

:lua require('gui.widgets').SCROLL_DELAY_MS = 100
```

**Comment by myk002** [comment]
But yes, this needs a CLI. I think maybe a new `control-panel` script would be better for the CLI than `gui/control-panel`, to better mirror the usual CLI/GUI split, but I can be convinced otherwise.
