### ISSUE TITLE
autochop is_valid_item caught something useful

### ISSUE THREAD

**Issue by jeffreyguilmot** [DFHack/dfhack#2668]
Idk anything about github or what exactly I need to tell you guys so here is a copy paste of the entire dfhack terminal window:

DFHack is ready. Have a nice day!
DFHack version 50.05-alpha1 (release) on x86_64
Type in '?' or 'help' for general help, 'ls' to see all commands.

This is an alpha build of DFHack. Some structures are likely
to be incorrect, resulting in crashes or save corruption
Make backups of your saves often!

REMINDER: Please report any issues you encounter while
using this DFHack build on GitHub (github.com/dfhack/dfhack/issues)
or the Bay12 forums (dfhack.org/bay12).

Loading script: dfhack-config/init/default.onLoad.init
Loading script: hack/init/onLoad.default.init
Loading script: dfhack-config/init/onLoad.init
Loading script: dfhack-config/init/default.onMapLoad.init
Loading script: hack/init/onMapLoad.default.init
Loading script: dfhack-config/init/onMapLoad.init
autochop is_valid_item actually caught something useful!! Please tell the DFHack team.
invalid alias in #aliases section: "{startnobles}{startorders}{startburrows}{startmilitary}{starthotkeys}"
executing via gui/quickfort: quickfort run library/dreamfort.csv -n /help
[DFHack]#

**Comment by myk002** [comment]
Thanks! this will be fixed in the release that will go out later today or tomorrow.
