### ISSUE TITLE
getNoblePositions is broken

### ISSUE THREAD

**Issue by agsedov** [DFHack/dfhack#2676]
```
for _, unit in ipairs(df.global.world.units.active) do
  positions = dfhack.units.getNoblePositions(unit)
  if(positions == nil) then
    print("Not a noble")
  else
    print("Noble")
  end
end
```
Tested on older fort: nobody got listed as a noble

Tested on fresh embark: game crashed.

**Comment by ab9rf** [comment]
which version/build of dfhack

**Comment by agsedov** [comment]
> which version/build of dfhack

dfhack50.05-alpha1

Steam Play Proton 5.0-10 (Linux)

Just tested, fixed in dfhack50.05-alpha2 though. 👍
