### ISSUE TITLE
Request: Add an option to pause the game when opening gui/launcher

### ISSUE THREAD

**Issue by leftbones** [DFHack/dfhack#2683]
I just noticed today the game doesn't pause when I open gui/launcher, since it was a large window I just assumed the game paused like it does when any other window that takes up most of the screen opens. Maybe a naive assumption, but still.

It would be nice to have an option for this! Bonus points if the minimal launcher doesn't pause the game.

**Comment by myk002** [comment]
This was added, but keeping this issue open until we have an in-game control panel to make it more accessible
