### ISSUE TITLE
autobutcher state is not saved

### ISSUE THREAD

**Issue by Thyrem** [DFHack/dfhack#2695]
Autobutcher reverts to disabled state and empty watchlist after reload.
Reproduced with DFHack 50.05-alpha1 & DFHack 50.05-alpha2.

Steps:
enable autobutcher, and set it up and confirm that animals are actually set to be slaughtered
Then save and reload.

**Comment by myk002** [comment]
Did you happen to have your game saved to a timeline or "manual" save? Vanilla has a bug right now where it saves those to incorrect directory names, so DFHack's persistent data can't know where to save itself. If you stick to a single timeline and autosaves, this isn't a problem.

**Comment by Thyrem** [comment]
Ah, I was unaware of that vanilla bug.
I was using manual save for testing out commands. 
I Retried using it on a world that only had autsaves and autobutcher persisted fine.
Thanks.
