### ISSUE TITLE
Request: Hotkey to open gui/quickcmd

### ISSUE THREAD

**Issue by leftbones** [DFHack/dfhack#2697]
Quick Command is an amazing plugin, in concept. It's still somewhat slow to have to open the launcher and type it in and then find your command, it'd be nice to able to have a hotkey (ctrl+shift+q perhaps?) to launch it instantly.

**Comment by myk002** [comment]
You got it: Ctrl-Shift-A

according to https://defkey.com/what-means/ctrl-shift-a it's not likely to conflict with any system hotkeys

**Comment by leftbones** [comment]
> 

Excellent! Thank you!

**Comment by myk002** [comment]
(ctrl-shift-q is already `quickfort`)
