### ISSUE TITLE
Ruby 1.9 - require an ".so" file crashes (need to init stack?)

### ISSUE THREAD

**Issue by benhell** [DFHack/dfhack#271]
While running on Windows, I noticed that requiring any of the .so files that typically exist in a Ruby installation (e.g., 'win32ole') causes dfhack to crash, hang, or the embedded ruby interpreter to throw a variety of low-level errors.

Digging into ruby.cpp in dfhack, I noticed that RUBY_INIT_STACK is not called.  See http://stackoverflow.com/questions/6585610/why-does-this-code-not-work-on-ruby-1-9-but-works-on-ruby-1-8.  Apparently RUBY_INIT_STACK is a requirement when initializing an embedded version of at least Ruby 1.9 (not sure what is required for Ruby 2.0+).  Without it, I believe that certain features of the interpreter just blow up.

I tested this (without recompiling DFHack) by creating an intermediate libruby DLL that exposed all of the Ruby DLL symbols that DFHack uses, but overrode ruby_sysinit to initially call RUBY_INIT_STACK.  I did this and ran a smoke test -- no longer crashes the interpreter, and thus far it has been stable.

I realize that DFHack accesses the ruby DLL directly through its exported symbols and not by actually loading the ruby.h header file, which means you can't use the RUBY_INIT_STACK directly.  It appears to be a fairly simple macro though, so you might be able to import and call the one function it calls directly.  See ruby.h in any distribution of ruby.

Thanks,
-Ben

**Comment by lethosor** [comment]
Is this an issue in recent versions of DFHack?

**Comment by PeridexisErrant** [comment]
If this is still an issue - and that seems unlikely, with Ruby2 and months without an update - is it really a DFHack problem if some things don't work with unsupported programs or versions?  If it is, I'd request Python support back; if not it's time to close this issue.

**Comment by lethosor** [comment]
We still use ruby 1.8, so nothing about this issue should have changed. I'm not sure which ruby libraries, if any, are distributed as binaries - I haven't seen DFHack distribute any, and DFHack scripts shouldn't be using anything platform-specific like win32ole.

I'm not entirely sure what you mean about python support, but that's hardly relevant to this issue - DFHack python support only existed when DFHack was out-of-process, back in 2009 or so.

**Comment by jimbofreedman** [comment]
@benhell I have been dealing with the same issue at the moment - if you still have it lying around would you be willing to send your shim DLL over and save me a bit of time?

**Comment by lethosor** [comment]
Hang on - you're using ruby 1.9 as well? Is there something that requires compiled ruby 1.9 libraries that doesn't work with 1.8?

**Comment by jimbofreedman** [comment]
I'm trying to use some gems that only work from ruby 1.9. I'm currently bootstrapping building dfhack from source (something I was going to do eventually).

One of them requires loading stringio.so which doesn't seem to work currently in dfhack (my test script works find from the command line)

**Comment by jimbofreedman** [comment]
(this led me here and also describes what I'm trying to do)
http://stackoverflow.com/questions/31940971/loading-external-dlls-e-g-stringio-so-in-embedded-ruby-interpreter?noredirect=1#comment51804056_31940971

**Comment by benhell** [comment]
Happy to share the code and dll. I was able to do quite a lot with ruby 1.9
and df34.11 once the shim was in place. I don't have access to it right now
(at work), but I'll try to post it somewhere late tonight or tomorrow.

I'm trying to use some gems that only work from ruby 1.9. I'm currently
bootstrapping building dfhack from source (something I was going to do
eventually).

One of them requires loading stringio.so which doesn't seem to work
currently in dfhack (my test script works find from the command line)

—
Reply to this email directly or view it on GitHub
<https://github.com/DFHack/dfhack/issues/271#issuecomment-129996250>.

**Comment by lethosor** [comment]
@jimbofreedman: ruby isn't compiled with DFHack, so recompiling DFHack won't help - it just dynamically loads the ruby library at runtime.

**Comment by jimbofreedman** [comment]
No but my current tack (only just heard from @benhell ) is to rebuild that plugin and add RUBY_INIT_STACK where it belongs for 1.9

**Comment by benhell** [comment]
Maybe you have a gem path or other path issue in ruby? The command line
interpreter usually sets those paths, but the embedded ruby interpreter may
not. If you're trying to use 1.9 and it can't find stringio, then you may
have path problems. If it can find stringio but crashes, then it is a shim
issue.  Just a thought.

I agree that rebuilding dfhack won't help since dfhack just dynamically
loads the ruby dll. That's why the shim workaround actually works.

(Regardless, you'll need a shim or your require statement will probably
crash.)

**Comment by benhell** [comment]
Whoops, have to disagree with myself. You can rebuild the plugin with the
stack init included, it's just a hassle.

**Comment by jimbofreedman** [comment]
I thought it might be a path issue but when I move stringio.so somewhere else, the error changes to "cannot load such file", which suggests it isn't being found.

Re: your second message yes that's my plan, but my long-term intentions probably involve building dfhack anyway so I thought I might as well.

It's not been a fun hour or two with trying LibXML on Windows etc. - seriously considering moving over my Linux machine even though it doesn't have all the power for actually playing the game...

**Comment by Azolo** [comment]
Hey, so sorry to sound naive here, but looking around the source trying to help out I could only find where Windows Ruby is linking against `MSVC` Ruby. I don't know how exactly `dfhack` was compiled, but that could cause problems with RubyInstaller (`mingw`) Ruby.

**Comment by lethosor** [comment]
Mind pointing me to that?
Anyway, if you're not familiar with DFHack, the Ruby libraries are pre-compiled (stored [here](https://github.com/DFHack/dfhack/tree/master/plugins/ruby)), and DFHack needs to be compiled with MSVC 2010 on Windows to be binary-compatible with DF. I don't know who originally compiled the Windows library (@jjyg?), but I suspect it was compiled with the same compiler.

**Comment by lethosor** [comment]
Oh, do you mean that RubyInstaller's libraries (stringio, etc.) might not work with DFHack?

**Comment by Azolo** [comment]
Right, I'm not sure but I do know that that could cause loads of problems. Loading a `mingw` dll from a `msvc` that is.

Of course, I feel seriously inadequate when situations like these come up because **I don't know** how or why just that it's something to look for when loading these kinds of things. But that could be why just dropping a RubyInstaller DLL in as a replacement doesn't work.

**Comment by jimbofreedman** [comment]
The DLL is loaded at run-time - I would have thought as long as the symbols match, and the code fulfills contracts, there won't be a problem.

**Comment by Azolo** [comment]
I mean, I don't know for sure. But if I remember correctly they both export their functions a bit differently. I tried to look into this when I took over RubyInstaller maintenance, but I seriously found myself stuck at not knowing enough about compiler toolchain internals.

You could always download a [RubyInstaller 1.8.7 release][1] and try it though, just see what happens?
Download the `7z` and grab the `dll` out of it.

[1]: https://bintray.com/oneclick/rubyinstaller/rubyinstaller/1.8.7-p330/view#files

**Comment by lethosor** [comment]
As I understand it, the main issue with MSVC binary compatibility is STL classes. Ruby is largely written in C, so I wouldn't expect as many MSVC compatibility issues, but there could be other incompatibilities between MSVC and mingw.

**Comment by benhell** [comment]
I used the Ruby 1.9 dll (taken from the Ruby Installer which was built with mingw) together with the shim dll (compiled with the DevKit for that version of Ruby) successfully.  The exported DLL functions appear to be binary-compatible with one another, and once you're inside the Ruby interpreter, it largely keeps to itself except for the interactions with DFHack-imported DF objects.  However, access to those objects is defined in a close-to-the-metal manner (generally in terms of pointer offsets, if my memory is right) which appeared to work with 1.9.  That said, it's been awhile since I did this, so I may have forgotten something.  

I think the following code can be compiled from a command prompt after running devkitvars.bat from the ruby DevKit.  Of course, change "/dev/Ruby193-p327" to wherever you installed Ruby (c:\Ruby is not uncommon).  Then sub out the ruby dll in the DFHack folder for the shim and make sure the Ruby Installer version of Ruby is on the path when you run DFHack.

 https://gist.github.com/benhell/cca9884ffe7f34b067a1

I also have the compiled DLL, but I don't think that I can post it here (and you shouldn't trust random binaries anyway).  Please let me know if you encounter any difficulties.

**Comment by jimbofreedman** [comment]
![image](https://cloud.githubusercontent.com/assets/7499526/9228873/613a6d94-4112-11e5-9015-93cdf6a5f3be.png)

I've built my own dfhack ruby plugin linked against the ruby-2.1.4 on my system (also uses <ruby.h> etc.). I haven't exactly stress-tested it yet but it loads and I can use gems I've installed.

Is there any interest in this? My use case is a bit niche - can't see much point in upgrading for the sake of it.

**Comment by jjyg** [comment]
@benhell, what does your shim do that the dfhack plugin doesn't ? ruby_init_stack() is in dfhack since the original bug report (more than 1year ago) : see https://github.com/DFHack/dfhack/blob/master/plugins/ruby/ruby.cpp#L411

The dfhack plugin code is written so that any ruby dll binary could be dropped in-place instead of the one shipped with dfhack, as long as a minimal binary compatibility with ruby1.8 is preserved. The only ABI dependencies on the ruby dll are listed in the plugin, lines 288-320.

Afaik the ABI should be compatible with all ruby, except latest ruby2 compiled with the USE_FLONUM macro. In this case the binary value of Qnil and Qtrue changes so that may break a few things in dfhack, and i think the rb_float_new export is replaced by rb_flot_new_in_heap, so that may prevent the dfhack plugin to load at all (it refuses to load if it can't find all the expected symbols in the ruby dll).

**Comment by benhell** [comment]
If init_stack is included now, then my shim shouldn't be needed.
