### ISSUE TITLE
Update the confirm plugin

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#2710]
Saving discussion from discord:

Robob27 — Yesterday at 9:12 PM
quick question, is confirm.lua disabled because we need some changes in game to be implemented for it to work, or just hasn't been worked on yet? 
myk002 — Yesterday at 9:12 PM
It's dependent on context, and we haven't put our context code back together yet
We call it "focus strings"
Identifying which part of the UI is the "focus"
Robob27 — Yesterday at 9:13 PM
okay sweet, ty!
myk002 — Yesterday at 9:14 PM
I just started looking at it again, prototyping it with the orders overlay I just wrote
Robob27 — Yesterday at 9:14 PM
i was curious because i had a friend probably quit playing for some time after losing like 10 minutes after an accidental right click in a trader screen last night so i'm trying to find a way to fix things so he'll come back lol
so i appreciate the info, glad to hear it's not disabled because it seems impossible or somethin' like that
myk002 — Yesterday at 9:16 PM
Vote for it on the poll to bump its priority
Robob27 — Yesterday at 9:16 PM
will do, also gonna take a look myself to see if i can figure any of it out. doubt i would before y'all get it sorted but we'll see, i'm committed haha
myk002 — Yesterday at 9:17 PM
I can give you an overview, if you like
Robob27 — Yesterday at 9:17 PM
i would love/super appreciate that
myk002 — Yesterday at 9:18 PM
Ok, so DF makes use of gui contexts called viewscreens
The main fort mode map is called viewscreen_dwarfmodest
(the st suffix stands for structure)
In the previous version, almost everything you could do put a new viewscreen on the stack
Only the top viewscreen gets input and renders unless it explicitly calls its parent
So in the previous version, you'd do something, like open the trade screen, a new viewscreen would be pushed on the stack, and that would be your interface
When you exit the viewscreen, it would get popped and you'd be back at dwarfmodest
Confirm worked by attaching to a specific viewscreen and intercepting the input stream
When a key corresponding to a known dangerous action was seen, the key was intercepted and a confirmation prompt was presented to the player
If the player confirms, the key would be re-injected in the input feed and the viewscreen would interpret it
Got that?
Robob27 — Yesterday at 9:23 PM
Yeeee tyvm
myk002 — Yesterday at 9:23 PM
Ok, so the new version of DF is different
There's generally only one viewscreen. Dwarfmodest.
Instead of a stack of viewscreens, you have a panel that displays different interfaces based on the mode
Confirm has to switch its interception logic from being based on viewscreens to being based on UI mode
That's generally 1 to 1, and not terrible
The next part is how to intercept input. If there are hotkeys for an action, we'd intercept them same as before
Ozzatron — Yesterday at 9:26 PM
confirm is definitely possible in the new UI it just requires some code path wrangling
"are you sure you want to seize the goods from the human traders?" 
myk002 — Yesterday at 9:27 PM
You also have to intercept mouse triggers
Ozzatron — Yesterday at 9:27 PM
"you're gonna get ass blasted in a few seasons" 
myk002 — Yesterday at 9:27 PM
Which means you have to know the pixel layout of the screen relative to the screen edges
Robob27 — Yesterday at 9:28 PM
Is all of this information accessible currently without having to do additional memory research?
myk002 — Yesterday at 9:28 PM
When you detect a mouse click, you have to check whether it's over the button
Yes
It's all there, just needs the work
Robob27 — Yesterday at 9:28 PM
Okay sick. Thank you for the overview, gives me a lot to start with
Gonna start looking at it rn
myk002 — Yesterday at 9:30 PM
Check out plugins/lua/orders for how it does context detection for knowing when to show the orders overlay
That's the data structure you'll find all the relevant context info in
It's called game, and it's a doozy
Spend some time browsing it in  gui/gm-editor while in different game states
You can leave the editor window open, modify the game state, and then go back and look at how the values changed by going up a level in the editor and back down
Robob27 — Yesterday at 9:35 PM
So much good info tyty. Always super appreciate the willingness to help 🙂
myk002 — Yesterday at 9:36 PM
We feel the same way : ) there is so much to do for this version! Motivated people like you really help move it along
Robob27 — Yesterday at 9:36 PM
😄
myk002 — Yesterday at 9:37 PM
Now, I should say that confirm needs the context detection, but it shouldn't be making the determination itself
It should be calling Gui:getFocusString() and the Gui module should have all that logic
Robob27 — Yesterday at 9:38 PM
noted!
myk002 — Yesterday at 9:39 PM
Once you get a handle on the overall structure of confirm, you might want to look at implementing what you need in the GUI module
There is a lot of logic and code there that is mostly correct, but it needs to be translated from looking at a viewscreen to looking at data in game
You can save yourself a lot of time by converting that instead of duplicating the work in confirm
Robob27 — Yesterday at 9:40 PM
converting which sorry? i don't completely follow the last part
myk002 — Yesterday at 9:41 PM
To get DFHack to compile, I commented out large swaths of code in the GUI module
That commented out code has the logic you need
Robob27 — Yesterday at 9:41 PM
ooooooo, gotcha, okay awesome
Lethosor — Yesterday at 9:53 PM
I really wonder if DF has something built-in for this
I hope Toady at least defines the button extents somewhere that feed() and render() can get to easily
myk002 — Yesterday at 9:56 PM
If it exists, I haven't seen it anywhere
It clear that he's measuring from screen edges for panel scaling, so that's what I used for positioning the orders overlay widget
If we don't have access to "is mouse over button id X" logic, I guess what I'd do is build a mock UI using our frame system, since that can be built up hierarchically, and then just call widget:getMousePos() 
Given the small number of buttons we'd have to shadow, I think that would be comparatively low effort 
Lethosor — Yesterday at 10:07 PM
I'm just thinking he used to have layer_object_buttonst, so it's possible he has attempted to track the bounds of buttons somehow (although that class is gone entirely)
since Putnam has talked about adding some widgets, presumably they aren't widgets currently

**Comment by robob27** [comment]
WIP branch [here](https://github.com/DFHack/dfhack/compare/develop...robob27:dfhack:enable-confirm?expand=1) 

Will keep this up to date as I make progress. More experienced contributors please feel free to take this over any time. I'm trying my best here but am definitely a bit beyond my depth and will make progress much more slowly than anyone even somewhat familiar with the code 😅.

**Comment by myk002** [comment]
You can open a pull request and mark it as WIP or draft. that way we can take a look and leave comments if you have specific questions

**Comment by robob27** [comment]
Sounds good, will do!
