### ISSUE TITLE
cursor issue with Steam version

### ISSUE THREAD

**Issue by dblunk88** [DFHack/dfhack#2713]
Any time I want to use a command that needs the cursor, I get: No cursor; place cursor over tile. (ex: with changelayer). This happens in all instances (jngame gui and console)

**Comment by myk002** [comment]
Yeah, this is an annoying problem. The keyboard cursor is not nearly as accessible as it used to be. We have plans for this in #2665

**Comment by F-l-i-x** [comment]
> Any time I want to use a command that needs the cursor, I get: No cursor; place cursor over tile. (ex: with changelayer). This happens in all instances (jngame gui and console)

There is a keyboard cursor available in the steam version, but you need to activate it first under settings -> game -> keyboard cursor
It will only be visible and controllable when you go into any diggin/carving/building mode, but works well then.
![grafik](https://user-images.githubusercontent.com/64616716/215358430-5c611872-d23c-4f0a-b443-1012757ac2cf.png)
