### ISSUE TITLE
Order to make bags in orders/basic.json is instead creating cloth/leather chests in 50.x

### ISSUE THREAD

**Issue by StormCrow42** [DFHack/dfhack#2717]
I noticed that the workorders created by orders/basic.json to create cloth/leather bags is instead creating the otherwise uncreatable cloth and leather coffer/chest/box.

**Comment by myk002** [comment]
This way brought to our attention last week and is now fixed. You can get updated orders files from here to overwrite the ones in `hack/data/orders`:

https://github.com/DFHack/dfhack/tree/develop/data/orders
