### ISSUE TITLE
Workorders in orders/military.json is creating platinum weapons outside of moods

### ISSUE THREAD

**Issue by StormCrow42** [DFHack/dfhack#2718]
It's normally impossible to make a workorder to make platinum blunt weapons.  However orders/military.json includes such workorders which do work when imported, resulting in much crafting of platinum weapons which are normally unattainable outside of strange moods.

Additionally, the workorder logic for other materials assumes that such platinum objects can be made and therefore tries to avoid making silver/steel/etc blunt weapons when platinum bars are available.

**Comment by myk002** [comment]
I think this needs some clarification from Bay 12 or at least some community discussion. If the inability to normally produce platinum weapons is an unintended bug, then I think these orders can stay. If it is a gameplay design choice, then we should either take platinum out of the standard library or have an alternate `military` set that is clearly marked as non-vanilla. How's that?

**Comment by StormCrow42** [comment]
Platinum has always been listed in the DF wiki (at least as far back as 0.31) as unavailable to make weapons with outside of artifact moods.  This is not a recent development.

I wouldn’t object to an alternate file that showed how to “cheat in” platinum weapons, but I don’t think it should be a default.

**Comment by myk002** [comment]
I asked for clarification from Toady here: http://www.bay12forums.com/smf/index.php?topic=169696.msg8449781#msg8449781

**Comment by StormCrow42** [comment]
It makes sense that platinum isn't a weapon material, it's a precious metal like gold.  There are plenty of other metals and alloys that one can't make weapons out of normally.

**Comment by myk002** [comment]
The consensus on Discord is that this is intentional and we should remove platinum weapons from the orders. Could you possibly remove the references to platinum and export a file we can replace `library/military.json` with?

**Comment by StormCrow42** [comment]
[military.zip](https://github.com/DFHack/dfhack/files/10504878/military.zip)

I think this should work, I stripped all mentions of platinum out of the file *except* for the 10 platinum bar smelting.

**Comment by myk002** [comment]
Would you like to make a PR for that? That way you can get credit for the change and be officially listed as a contributor to DFHack. I don't want to steal your credit!

From the discussion in Discord, the existing `military.json` file can be renamed to `military_include_artifact_materials.json` (or similar) to indicate its non-vanilla nature. The docs should also be updated in `docs/plugins/orders.rst` to explain the difference between the two `military` orders sets a little.

**Comment by myk002** [comment]
You'd have to push to your own fork and submit a PR from there. There are some links here that could help: https://docs.dfhack.org/en/latest/docs/dev/Contributing.html

I'd be happy to take care of this, but again, I wanted to make sure you had the opportunity first.
