### ISSUE TITLE
CRASH: Right after save reliably when troops coming home

### ISSUE THREAD

**Issue by warclone** [DFHack/dfhack#2738]
Just a few seconds after the save it's crashing for me 🤷‍♂️
[gamelog.txt](https://github.com/DFHack/dfhack/files/10524407/gamelog.txt)
[errorlog.txt](https://github.com/DFHack/dfhack/files/10524408/errorlog.txt)
[stdout.txt](https://github.com/DFHack/dfhack/files/10524409/stdout.txt)
[stderr.txt](https://github.com/DFHack/dfhack/files/10524410/stderr.txt)
[SAVE.zip](https://github.com/DFHack/dfhack/files/10524411/SAVE.zip)

**Comment by lethosor** [comment]
1. What DFHack version number?
2. Does the crash still occur if you disable DFHack? Assuming Windows, you can do this by replacing SDL.dll with SDLreal.dll (but you will have to reinstall both of those DLLs from DFHack to reactivate it)
3. Could you upload stderr.log and possibly the world folder (save/regionX, not the whole save folder)? Unfortunately none of the files you have provided have anything useful.

**Comment by warclone** [comment]
I replaced the DLL and it still crashes, so not an issue here I guess?

**Comment by myk002** [comment]
yeah, if it crashes in vanilla from a fresh load, it is unlikely to be caused by DFHack
