### ISSUE TITLE
Multiple Embarks bug

### ISSUE THREAD

**Issue by nobodyinteresting** [DFHack/dfhack#2739]
Quoting from Discord:

damn. i have no idea how i did this, idk if it was a DF bug or a dfhack bug, but uh.. i just embarked twice. at the same time. and now i have all 14 dwarfs from both embarks, lol
here's what happened:

1) i embarked like normal
2) i set up my embark with prepare carefully
3) when i hit embark, it came up with a box in the middle of the screen with tons of garbled text, and the "Confirm/Abort" box in the top left like when you are choosing an embark location on the map
4) I hit Confirm in that little box
5) it brought me back to the embark carefully screen, where i embarked again
6) the error box came up again, but this time i just right clicked and tada, now im on my embarked tile with 14 dwarfs and 2x the materials lmao

(unpausing caused all trees to turn to clay, several animals and dwarves to be crushed to death, and a bunch of "newly appointed noble" popups, despite no nobles being appointed.)

---------------------------

User SeerSkye pointed out that a similar bug occurs if you open up the dfhack console (with `) while on the prepare embark screen, and hit "I'm ready!" a bunch of times. This caused all the same problems except for the screen of garbled text. I was unable to replicate that, nor did I get a screenie, sorry.

Edit: Oh, one more thing, if I try to quit back to title after causing this bug, DF crashes.

Edit 2: Sorry, basic info: Win7 64bit, DFHack 50.05-alpha2, DF 50.05 Steam.

**Comment by ab9rf** [comment]
i (and many others) have confirmed this in both alpha2 and in development head (currently bf9552094)
