### ISSUE TITLE
LuaJIT?

### ISSUE THREAD

**Issue by kazimuth** [DFHack/dfhack#274]
Random question - have you ever considered using [LuaJIT](http://luajit.org/luajit.html)? It can dramatically increase performance if you have any compute-bound lua code. Also, it's api-compatible with standard lua, has a tiny footprint, and is mit-licensed.
I don't know dfhack very well, so I'm not sure how much it would help, but it could be a nice speed bonus for a relatively simple swap-in.

**Comment by lethosor** [comment]
We're relying on some Lua 5.3 features now, so I don't think this would work. Feel free to comment/reopen if that's not the case, though.
