### ISSUE TITLE
CTD autoclothing and tailor issue

### ISSUE THREAD

**Issue by YukiGibson** [DFHack/dfhack#2750]
Hi! Thanks for your work in **DFHack**. I wish I could help but C++ is not my forte hehe.

Anyway, I have been having some issues with `autoclothing` and `tailor` commands. In comparison with #2700, mine does not crash when using the `report` flag. 

In my case I activated `tailor` and then `autoclothing` using the next params (there is a list of commands down below from the launcher.history):

```
> autoclothing cloth shoe 2
> autoclothing cloth shirt 2
> autoclothing cloth trousers 2
> autoclothing cloth hood 2
```

I got around 3 CTD on the same morning after this. All I did afterwards was after getting to Desktop, I started the game again to my last save, activate `autoclothing` again, and then get a crash around 15-30 minutes later. 

I can see an Application Error in the Event Viewer, such as:

```
Faulting application name: Dwarf Fortress.exe, version: 0.0.0.0, time stamp: 0x63b6063b
Faulting module name: autoclothing.plug.dll, version: 0.0.0.0, time stamp: 0x63cb3d94
Exception code: 0xc0000005
Fault offset: 0x00000000000064c3
Faulting process id: 0x0x1B80
Faulting application start time: 0x0x1D93337A37336E4
Faulting application path: E:\SteamLibrary\steamapps\common\Dwarf Fortress\Dwarf Fortress.exe
Faulting module path: E:\SteamLibrary\steamapps\common\Dwarf Fortress\hack\plugins\autoclothing.plug.dll
Report Id: defdaf9a-2b51-4aed-95e2-eb97e3a67dc1
Faulting package full name: 
Faulting package-relative application ID: 
```

### Files

I uploaded the save [here](https://dffd.bay12games.com/file.php?id=16409).

And checked local files if I could find the history of commands, so there is stuff like `renew-all` command over there: 
[history.txt](https://github.com/DFHack/dfhack/files/10530327/history.txt)

Thanks!

**Comment by Stealthii** [comment]
tested a similar setup on my own save, however enabling only socks with autoclothing. receiving a similar CTD during manager order processing.
