### ISSUE TITLE
Trying to use the wrong libz?

### ISSUE THREAD

**Issue by smickles** [DFHack/dfhack#276]
On fedora, in order to run vanilla DF, I have to `export LD_PRELOAD=/usr/lib/libz.so.1`. However, it seems the way dfhack's launch script is, I cannot do this. Also, even though I specified this library during build at the advanced section of ccmake, the issue persists.

The error presents itself in the exact same manner in which it does on a vanilla install. This is a popup box titled "tileset not found" and the content of "Not found: data/art/curses_640x300.png".

Switching to .bmp does not fix this, nor does using a graphics set.

Please advise.

**Comment by lethosor** [comment]
This should be easier to fix now with PRELOAD_LIB working more reliably.
