### ISSUE TITLE
Autoclothing appears to order too many items

### ISSUE THREAD

**Issue by sdegrace** [DFHack/dfhack#2761]
I first executed `autoclothing silk shirt 20` and got more orders than expected. After realizing that was 20 _per dwarf_, I reduced that to `autoclothing silk shirt 2`. However that does not seem to have fixed the issue. 

With population size 43, I see the following now:

![image](https://user-images.githubusercontent.com/62040901/215525346-a4e4e033-7a15-4d59-b38f-4922a9c881bc.png)
![image](https://user-images.githubusercontent.com/62040901/215525392-26446886-608f-478d-b27f-a4783b0c5b3f.png)

The cloth and yarn orders make sense, but the silk orders are still too high. I've tried deleting the work orders from the work order screen in game and that did not fix the issue.

**Comment by sdegrace** [comment]
[IssueUpload.zip](https://github.com/DFHack/dfhack/files/10537416/IssueUpload.zip)
Save attached

**Comment by flarejoltporeon** [comment]
I've had the same (or a similar) issue - I had wondered why I was running out of cloth and had a look at my work orders/stocks. I had one work order for 9000+ yarn trousers and 9k yarn trousers in stock, although my fort had 198 dwarves and I was asking for 3 yarn trousers per dwarf. It also only stated I had legwear for 242 dwarves, despite said 9,000 trousers. I think I'd changed from 3 to 2 either before or after this save, I don't have clear memory.

Looking through earlier saves, I'd also had a work order for 6400 yarn trousers before the 9000 one... no wonder I'm swimming in pants. 

The latest save that I had noticed it in can be found at [https://dffd.bay12games.com/file.php?id=16545](https://dffd.bay12games.com/file.php?id=16545) - It's about 30 work orders from the bottom (apologies for all the single bone-carving work orders). The save is too large to attach here unfortunately.
