### ISSUE TITLE
orders library items requiring bags, have boxes as a condition instead.

### ISSUE THREAD

**Issue by Mazz0690** [DFHack/dfhack#2765]
Orders requiring bags in the library files (e.g. mill plants), have "empty boxes" listed as a condition, instead of bags.

**Comment by myk002** [comment]
Believe it or not, that was actually correct for the previous version of DF. The orders were recently updated for the steam version, which now differentiates boxes and bags. You can get fixed orders here: 

https://github.com/DFHack/dfhack/tree/develop/data/orders

**Comment by Mazz0690** [comment]
Yes I know it was! I thought it may have been an oversight with the transfer :3 Thank you for the link. <3
