### ISSUE TITLE
is gui/create-item functional?

### ISSUE THREAD

**Issue by Morabert** [DFHack/dfhack#2769]
I can't seem to create glass, it's not clear if the command is non-functional or if there is a specific parsing necessary.

**Comment by myk002** [comment]
glass is under the "rough gem" category. it appears to be created fine for me

**Comment by Morabert** [comment]
ah, I'm actually not as bright as I look, I have not thusfar been able to get DFHack to list the contents of sub-categories, as a result I have been doing my best to simply write out the commands long-form, but truth be told, I think your reply makes it clear even to me that I am floundering with DFHack parsing literacy :P .

**Comment by myk002** [comment]
by "write out the commands" I'm thinking we're talking about different tools. `gui/create-item` gives you an in-game prompt for a type, then further prompts as necessary. At the first prompt, search for "rough" to show "rough gem", hit enter, and at the next prompt you'll see the various glass types (green glass, clear class, and crystal glass). Select the one you want, give it a quality of "None", and you're good to go.
