### ISSUE TITLE
gui/launcher does not reset log after running a command anymore

### ISSUE THREAD

**Issue by TaxiService** [DFHack/dfhack#2782]
using dfhack-win64-build-20230202-75bb67cfc

steps:
- open `gui/launcher`
- run a command, let's say `gui/gm-editor` with no valid target. This will print stuff to the log.
- now try typing in any other command, or press shift+right. The last command's log won't be cleared from the log, and no help text shows up.

this screenshot shows me after i've ran gm-editor and then pressed shift+right twice.
![Capture](https://user-images.githubusercontent.com/5853667/216416253-28f1f4b8-9290-4636-af27-b1d57e15aec0.PNG)

could this be related to the new feature that lets you click multiple help buttons from control panel?

**Comment by myk002** [comment]
This new behavior was a feature request. You can get back to the help with Ctrl-T.

Perhaps we could use the new TabBar widget I wrote for control-panel to make that more obvious here?

**Comment by myk002** [comment]
how's this?
![image](https://user-images.githubusercontent.com/977482/216427725-7d938599-f1a3-4b47-913c-be63f9fcbd5f.png)

**Comment by TaxiService** [comment]
oh my god i can't read 🤦🤦🤦🤦🤦

yeah the tabs sure makes it a lot more noticeable... :P

**Comment by TaxiService** [comment]
also i wanted to be all like "i raise you... this!!!" but the sprites don't align currently if i just move them around...

![1g6hzt6b](https://user-images.githubusercontent.com/5853667/216437265-ff86f0d0-78fc-45a4-9643-aefa32855f60.png)

if this is something you might be interested in, i'll make some more special sprites to use when connecting tabs to thin horizontal lines

**Comment by myk002** [comment]
that's a tough call. The tabs just hanging out in blank space is a little awkward, true.

just to be sure you saw this, the text on those tabs is offset from the grid. half of the letter is in the upper tile and half in the lower. when you moved the tiles around, did you account for that?

**Comment by TaxiService** [comment]
> did you account for that?
oh, no i didn't! i moved the lines downwards in multiples of 12 pixels, simulating a 8x12 grid!
