### ISSUE TITLE
Setting a seedwatch target prints the help

### ISSUE THREAD

**Issue by sarbian** [DFHack/dfhack#2791]
DFHack 50.05-alpha3
Setting a target with seedwatch prints the help. status and clear works fine.

Console:
```
[DFHack]# seedwatch all 30
seedwatch
=========

Tags: fort | auto | plants

Command: "seedwatch"
[...]
```

**Comment by myk002** [comment]
This is due to an off-by-one error in the command processing. You can set targets with a command like this:
```
seedwatch dummy POD_SWEET 40
```
will fix. thanks!
