### ISSUE TITLE
Convert confirm dialogs to "modern" windows and widgets

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#2814]
so elements are clickable and the window theme is consistent with the rest of DFHack

**Comment by myk002** [comment]
@robob27 do you have time to do this before the next release? It's not as important as the state persistence for `confirm`, though.

**Comment by robob27** [comment]
@myk002 Yeah I can try. Can you give a little guidance on what I need to do to modernize it? Am I still going to be using the same `Screen:paint*` API just using different pens kinda thing? Or like, somehow converting it to use lua widgets? Can probably figure it out with a little nudge in the right direction

**Comment by myk002** [comment]
It should be all Widgets. It's really not that bad. Just create a widget-based window like normal (you probably want a widgets.Window and just add a few widget.HotkeyLabels). You can check out overlay.cpp for how to render the widgets directly from a plugin without a parent `gui.Screen`.

**Comment by robob27** [comment]
Thanks! I'll take a look

**Comment by myk002** [comment]
have you had time to look at this at all?
