### ISSUE TITLE
automelt not working

### ISSUE THREAD

**Issue by SIX10** [DFHack/dfhack#2819]
When designating stockpiles, automelt sees none of them as having ore. Designating one doesn't fix it either.

**Comment by ElsaTheHobo** [comment]
Automelt designates items for **melting**, aka metal garbage for the Melt Item job, not **smelting**, which you do with ore with a smelt <ore> job

**Comment by myk002** [comment]
Yes, for automatic **smelting**, you'd run 

`orders import library/furnace`

For the charcoal and

`orders import library/smelting`

For the actual smelting orders.

Docs here: https://docs.dfhack.org/en/latest/docs/tools/orders.html#the-orders-library

**Comment by SIX10** [comment]
I'm stupid, thank you!
