### ISSUE TITLE
DFHack doesn't recognise new 50.06 update and crashes it on start

### ISSUE THREAD

**Issue by FriendCalledFive5** [DFHack/dfhack#2838]

**Comment by Stealthii** [comment]
DFHack intentionally doesn't load on unknown versions.

You can revert to the 50.05 release of steam supported by alpha3.1 by [opening the Steam console](steam://nav/console), and downloading the 50.05 release depot:
```
download_depot 975370 975371 5531302223525500789
```

This will likely be placed at `C:\Program Files (x86)\Steam\steamapps\content\app_975370\depot_975371` by default. Copy this over your DF installation, re-install DFHack, and postpone updates until a release is made to support 50.06.

**Comment by JezaGaia** [comment]
> You can revert to the 50.05 release of steam supported by alpha3.1 by opening the Steam console, and downloading the 50.05 release depot:

Thanks this is just what I was looking for, I forgot that you can't really block steam from updating as it'll do it automatically  when you launch.
A question tough, how do I open the steam console ?

**Comment by Stealthii** [comment]
Forgot Github doesn't show non-http links. Updated my comment.

**Comment by JezaGaia** [comment]
thank you so much, worked like a charm :)

**Comment by lethosor** [comment]
This has and always will be the case. DFHack requires information about the DF executable that can only be obtained after DF has been built, so it is impossible (without time travel) for a DFHack release from the past to support a DF release from the future.

See also: https://docs.dfhack.org/en/stable/docs/Installing.html#requirements

> DFHack releases generally only support the version of Dwarf Fortress that they are named after. For example, DFHack 0.40.24-r5 only supported DF 0.40.24. DFHack releases _never_ support newer versions of DF, because DFHack requires data about DF that is only possible to obtain after DF has been released.

**Comment by Kurru** [comment]
FYI, lethosor@ the tags and status, make it seem like DFHack will not update. Given the difficulty in using DF on Steam on a specific version of DF, having a messaging bug for supporting new versions of DF would be appreciated. Certainly, thats why I'm hear today.

**Comment by lethosor** [comment]
There is a discussion at https://github.com/DFHack/dfhack/discussions/2841 - I think that's sufficient for now. There's _always_ a period of time between DF updates and initial DFHack support for them, so I feel like creating a tracking issue that says "we'll add support for 50.xx soon" for every DF update is extra effort that could be better spent (and redundant, since that's always something we're working on).
