### ISSUE TITLE
Not a known DF version

### ISSUE THREAD

**Issue by LexiconDul** [DFHack/dfhack#2849]
Been fighting with this one repeatedly with the steam release.
Worked for a while with alpha2, stopped, so I got the newest build and it still won't run.
I'm guessing the steam auto-updater is causing the issue.
Is there just a way to disable the DF version identification?

DFHack build: 50.05-alpha3.1-0-g71deeb7a
Starting with working directory: C:\Program Files (x86)\Steam\steamapps\common\Dwarf Fortress
Identifying DF version.
Loading hack\symbols.xml ... OK
v0.50.05-steam SDL win64 (windows): PE: 0x63B6063B
v0.50.04-steam SDL win64 (windows): PE: 0x63a2a9ad
Loaded 2 DF symbol tables.
Unable to retrieve version information.
PE timestamp: 0x63e29e0c
Not a known DF version.
DFHack will now deactivate.

**Comment by ab9rf** [comment]
This is by design. DFHack only works with the specific version of DF it was built to work with. There is not yet a working build of DFHack for 50.07. Attempting to bypass or circumvent the version check will not yield fruitful results.

**Comment by Stealthii** [comment]
Also search issues (including closed) before raising them:
https://github.com/DFHack/dfhack/issues/2838#issuecomment-1421277676
