### ISSUE TITLE
autoslab creating duplicate engraved slabs

### ISSUE THREAD

**Issue by johncosker** [DFHack/dfhack#2850]
There's a ghost in my fort named Zasit Åkumurdim. The engrave job for him keeps getting queued over again, which means the string comparison to check for existing engraved slab items isn't working correctly in `autoslab`.

It just seems to be that one dwarf which makes me wonder if it has to do with the string encoding or something and it's not handling the 'Å' correctly when calling `std::string::find`

When writing the plugin I did test with dwarves with non-ASCII characters and it seemed to work so not sure yet what the exact issue is.

**Comment by johncosker** [comment]
This is why in the plugin I commented I'm not super happy about having to use string comparison for the slab text compared to something more solid like checking the historical figure id, still don't have an alternative though.

**Comment by johncosker** [comment]
For now a workaround is to place the slabs and get rid of the ghost.

**Comment by lethosor** [comment]
Can you upload the save?

**Comment by johncosker** [comment]
I added a debug log and saw that this is the issue

Checking 'marble memorial to Zasit Åkumurdim' for Zasit åkumurdim: Result false

The last name is generated from a function I stole from another plugin:

```c++
static std::string get_last_name(df::unit *unit)
{
    df::language_name name = unit->name;
    std::string ret = "";
    for (int i = 0; i < 2; i++)
    {
        if (name.words[i] >= 0)
            ret += *world->raws.language.translations[name.language]->words[name.words[i]];
    }
    return Translation::capitalize(ret);
}
```

So it looks like the capitalization isn't working for at least that letter.

**Comment by johncosker** [comment]
`Translation::capitalize` is just calling `std::toupper(input_string[0])` so I think the issue is that in this case the first letter is a unicode character it's failing...

Indeed, if you try to do this it doesn't compile

`std::cout << std::toupper('å');`
```
main.cpp:15:31: warning: multi-character character constant [-Wmultichar]
   15 |     std::cout << std::toupper('å');
      |                               ^~~
```

I think the reason I didn't see this in testing with other names with non-ascii characters is because in those cases the letter was in some other position in the name other than 0.

**Comment by johncosker** [comment]
This seems to work: https://stackoverflow.com/questions/17991431/convert-a-unicode-string-in-c-to-upper-case

```c++
#include <iostream>
#include <locale.h>

int main() {
    std::locale::global(std::locale(""));  // (*)
    std::wcout.imbue(std::locale());
    auto& f = std::use_facet<std::ctype<wchar_t>>(std::locale());

    std::wstring str = L"å";

    f.toupper(&str[0], &str[0] + str.size());
    std::wcout << str << std::endl;

    return 0;
}
```

So perhaps `Translation::capitalize needs to be updated to handle unicode better.

I'll leave this for a minute, in case anyone who has experience working with unicode strings in C++ can weigh in.

**Comment by johncosker** [comment]
Upon revisiting the code, I actually found that the `int32_t topic` field of the `df::item_slabst` structure actually contains the historical figure ID of the dwarf, at least when it's a memorial slab.

This is great news for `autoslab`, the string comparison thing has bugged me since the beginning.

I will raise a bug for the `Translation::capitalize` issue. I tried implementing the unicode fix but ran into some trouble.

**Comment by lethosor** [comment]
Per https://github.com/DFHack/dfhack/issues/2855#issuecomment-1423569814, the names are actually CP437, not Unicode. `isupper()` also cannot handle (extended, char > 255) Unicode, at least on Linux:

>        If c is neither an unsigned char value nor EOF, the behavior of these functions is undefined.

so this is a bit nontrivial to fix.

How did you end up with the discrepancy between "Åkumurdim" and "åkumurdim", anyway? My impression has been that DF almost always displays the lowercase form, so I'm not sure how you got the capitalized form.

**Comment by johncosker** [comment]
The slab engraving message contains the capitalized version of the last name, as does the units screen in game. My workaround for checking for engraved slabs was using a string comparison with the dwarf name, which uncovered the capitalization thing.

Yeah I found it definitely was not an easy fix once I started trying to fix it lol, I'm really happy I found the better solution for `autoslab` because I was starting to enter a fell mood
