### ISSUE TITLE
Family Affair / makeown compatibility

### ISSUE THREAD

**Issue by KMFrench1** [DFHack/dfhack#2863]
If I use make own on a intelligent creature, then try to use family affair to get them married family affair does not think they are a citizen. not sure if that is because they are just a visitor or if they are just not messing. Was told to file github report. so I am, :)
Using version of dfhack downloaded today, on 50.07

**Comment by lethosor** [comment]
There were multiple versions of DFHack that you could have downloaded today - if you're not on `50.07-alpha1`, could you upgrade to that and see if the issue is still present?

**Comment by KMFrench1** [comment]
It is still an issue in 50.07 alpha1

**Comment by myk002** [comment]
fixed with rewrites of both `makeown` and `gui/family-affairs`
