### ISSUE TITLE
workaround for df nickname bug

### ISSUE THREAD

**Issue by ab9rf** [DFHack/dfhack#2874]
DF is not properly persisting nicknames in a number of circumstances. Until Bay12 fixes this, we could probably write a small tool that periodically scans the unit list for units that have a nickname set in a manner that will not be persisted, and fix it so that it will be.

**Comment by plule** [comment]
https://github.com/DFHack/scripts/pull/604 is intended to do this. It updates the historical figure nickname daily, fixing most of the nickname issues (losing it in battle, during new embark, missing in legends)
