### ISSUE TITLE
`gui/mass-remove` throws nil value exception when run

### ISSUE THREAD

**Issue by libardia** [DFHack/dfhack#2880]
`gui/mass-remove` (which I understand is untested, but I was advised by a DFHack developer that I should create an issue anyway) throws the following exceptions when run:

```
> gui/mass-remove

UNTESTED WARNING: the "gui/mass-remove" script has not been validated to work well with this version of DF.
It may not work as expected, or it may corrupt your game.
Please run the command again to ignore this warning and proceed.

Output from command run from gui/launcher:
> gui/mass-remove

...\common\Dwarf Fortress//hack/scripts/gui/mass-remove.lua:313: attempt to call a nil value (method 'show')
stack traceback:
        ...\common\Dwarf Fortress//hack/scripts/gui/mass-remove.lua:313: in local 'script_code'
        ...team\steamapps\common\Dwarf Fortress\hack\lua\dfhack.lua:810: in function 'dfhack.run_script_with_env'
        (...tail calls...)
        [C]: in field 'runCommand'
        ...team\steamapps\common\Dwarf Fortress\hack\lua\dfhack.lua:853: in upvalue '_run_command'
        ...team\steamapps\common\Dwarf Fortress\hack\lua\dfhack.lua:857: in function 'dfhack.run_command_silent'
        [C]: in field 'hideGuard'
        ...pps\common\Dwarf Fortress//hack/scripts/gui/launcher.lua:886: in function <...pps\common\Dwarf Fortress//hack/scripts/gui/launcher.lua:871>
        [C]: in field 'on_submit'
        ...steamapps\common\Dwarf Fortress\hack\lua\gui\widgets.lua:722: in method 'onInput'
        E:\Steam\steamapps\common\Dwarf Fortress\hack\lua\gui.lua:584: in function <E:\Steam\steamapps\common\Dwarf Fortress\hack\lua\gui.lua:578>
        (...tail calls...)
        E:\Steam\steamapps\common\Dwarf Fortress\hack\lua\gui.lua:783: in function <E:\Steam\steamapps\common\Dwarf Fortress\hack\lua\gui.lua:772>
        [C]: in ?
```

I was trying to run this untested tool because it is really something I am very eagerly awaiting due to how tedious and error-prone removing a large amount of furniture is, and while I understand this may not be a priority, I would like to bring this to your attention.

**Comment by myk002** [comment]
Could you try overwriting the `hack/scripts/gui/mass-remove.lua` file with the contents here: https://raw.githubusercontent.com/DFHack/scripts/a18360004ac76b29b1b1ebf4e5018220fb50193f/gui/mass-remove.lua

The script needed a heavy rewrite, so some testing from a motivated user would be very welcome.

Note that "Unremove" is not supported yet because of a higher-level issue.

**Comment by libardia** [comment]
I overwrote the script, and it appears to work! There's some weirdness involving the launcher, but looking at the changes you made in that pull request, it is almost certainly related to the changes you made in the `.rst` file. Despite that weirdness it is now possible for me to use the mass-remove tool!

I'll do some more thorough testing on the other things the tool can do and report back here.

**Comment by myk002** [comment]
I'm glad that it's (mostly) working! What do you mean by "weirdness" in the launcher? Is it because the tool is still marked as "untested", hiding it from normal autocomplete? That will be cleared up once the PR is merged. Or is there something else?

I'll look into the suspend mechanics for the final build stage. There may be new variables to set in the latest DF version.

**Comment by libardia** [comment]
Yes, that's what I mean by "weirdness" -- sorry, I originally was going to talk more about it but edited down my comment too much apparently.

It still behaved like an untested script, in that it was hidden by default from auto complete and required me to run it twice to clear the warning message, but the only other strange thing I noticed was that when I wrote out its full name, suddenly it was suggested in the side panel.

For all I know, that's normal and intended behaviour for untested tools, so you can ignore my comments about the launcher lol, sorry.

**Comment by myk002** [comment]
Yeah, this is how the launcher treats "dev" commands to keep them out of the way of casual players. From the [docs](https://docs.dfhack.org/en/latest/docs/tools/gui/launcher.html#dev-mode):
```
Dev mode
By default, commands intended for developers and modders are filtered out of the autocomplete list. This includes any tools tagged with untested. You can toggle this filtering by hitting Ctrl-D at any time.
```

btw I solved the suspend issue and will merge the script in a few minutes. Thanks for bringing this up!
