### ISSUE TITLE
Autobutcher annoucements not triggering correctly.

### ISSUE THREAD

**Issue by AndrielChaoti** [DFHack/dfhack#2881]
When autobutcher sends an annoucement, it does not get propogated to the user, and instead overwrites some other annoucement. In my example it's overwriting the "Test Alert" from the tutorial:

![image](https://user-images.githubusercontent.com/3628387/218287782-2b10787c-0743-49e9-b4a0-54813db8f069.png)

You can reporduce this by creating a world and having autobutcher enabled by default, and just accepting the tutorial start provided it's available (guaranteed to happen if you have a medium or larger world)

**Comment by AndrielChaoti** [comment]
Additional note: It's probably best if autobutcher does not end up in the ALERT annoucements, as that's meant for things that need your immediate attention.

**Comment by AndrielChaoti** [comment]
I actally ended up figuring out that the tutorial expects "This is an example urgent alert![...]" at id `2` and that is what is happening here. Though the issue still stands that autobutcher is not able to send annoucements properly.

**Comment by myk002** [comment]
It's true that announcements are more intrusive than they used to be, making autobutcher more intrusive than it intended to be. So what's the fix? just output to the DFHack console instead of making an announcement? that's about in line with what other tools are doing.

**Comment by lethosor** [comment]
I don't think we can disallow all tools from making announcements. Eventually we should find a way to make them less intrusive.

For autobutcher, though, I don't think it necessarily needs to make announcements.

**Comment by AndrielChaoti** [comment]
If it ends up being possible to choose which "channel" an annoucement is printed to, that would be a lot better in regards to actually sending annoucements.

**Comment by myk002** [comment]
maybe there could be a DFHack log viewer. logs are already naturally separated by channel, it's just that relatively few tools actually use the channels and would need to be converted
