### ISSUE TITLE
seedwatch reverting target to 0 on load

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#2884]
running:
```
seedwatch all 0
seedwatch MUSHROOM_HELMET_PLUMP 30
```

then saving then loading will have the target for plump helmets set to 0 instead of 30

**Comment by ImSuperlative** [comment]
[dfhack-legacy-data.txt](https://github.com/DFHack/dfhack/files/10715849/dfhack-legacy-data.txt)
