### ISSUE TITLE
50.07-alpha1: Dwarves idling even though plenty of work.

### ISSUE THREAD

**Issue by otwkme** [DFHack/dfhack#2919]
In 50.07, twice now I've had a fort get locked up with most dwarfs either with no job or socializing in a tavern. There were plenty of assignable tasks like smoothing walls and construction. In both cases I'd 

In the first case, it included a strange mooder getting frozen. This was shortly after a werecreature cascade that got a bit out of control and I'd resorted to expelling some suspect dwarfs. I do not recall turning on any of the optional plug ins on this.

Second case is same fort restored from an earlier save (before werecreatures). I played probably 10 or so more on it from that earlier save before reinstalling DFHack and watching it be ok for several hours. I used autodump and the fix dead command to clean up trash and get some FPS back, then enabled the auto job helpers on the first screen of the gui control panel. Only one I think I hadn't enabled was autobutcher. Maybe an hour after that, I had dwarfs going idle again. Most were busy getting silly in the tavern, but there was LOTs of queued construction, mining, and smoothing that wasn't getting done. Removing DFHack restored work.

I may still have the save for the first before I had removed DF Hack, but not sure as I jumped backwards on the fort assuming it was corrupted. Second is almost definitely overwritten.

**Comment by ab9rf** [comment]
Unless you were using `autolabor`, which you don't specifically mention, this is probably a vanilla bug. We have seen multiple reports of vanilla bugs in which dwarfs refuse to work for an extended period of time, then start working again for no apparent reason. Unfortunately the circumstances leading to a "general strike" are not well-characterized, nor are there well-established means for ending one.

It's therefore unlikely that we can do anything meaningful with this report, especially since the reported behaviors are all consistent with bugs reported to be in vanilla DF.

**Comment by otwkme** [comment]
Got it... I figured it probably was , but was asked to report when discussing in reddit just in case it wasn't.

**Comment by MechanosG** [comment]
I had this happen earlier today using autolabor.  Suddenly all my dwarves socializing in the tavern except for 1.  Reloading the save did nothing.  Playing with autolabor settings did nothing.  Restarting DF fixed it though, despite using the same autolabor settings.

**Comment by ab9rf** [comment]
> Restarting DF fixed it though, despite using the same autolabor settings.

This is the part that makes me strongly suspect this is a vanilla issue. `autolabor` is stateless and idempotent; it does not retain any data from run to run (other than its explicit configuration information) and will always make the same decisions every time it's invoked in the same circumstances. Turning `autolabor` off and on again won't change its behavior. The fact that restarting DF resolved the issue really strongly points at DF, and not autolabor, as the source of this problem behavior.

**Comment by otwkme** [comment]
So I did notice this happen w/out DFHack . Reinstalling DF Hack cleared the issue this time, so must be it is a vanilla issue but whatever difference exists between DFHack and vanilla is enough to force a different calculation and get out of that state.

**Comment by myk002** [comment]
This is very likely the vanilla "general strike" bug.
