### ISSUE TITLE
Channel Safely Is Crashing on launch.

### ISSUE THREAD

**Issue by RyushoYosei** [DFHack/dfhack#2921]
Just as said, I  open the GUI for enabling things such as Auto butcher, auto farm and similar, if I click Channel Safely, Game instantly CTD's.

**Comment by myk002** [comment]
could you upload your savegame and installed mods to a cloud service (or [dffd](https://dffd.bay12games.com/)) and attach a link here so we can investigate?

**Comment by RyushoYosei** [comment]
I would but I think it was a   messed up install of DFHACK on my end, as I had re-installed it and..now it's working fine, So it might of just been an issue on my end.

**Comment by lethosor** [comment]
Are you the same person who reported this on Discord a couple days ago (nickname starting with "N")? Want to make sure we aren't losing track of this issue if it was someone else.

**Comment by RyushoYosei** [comment]
No, actually, I am not in the DFHack discord.

**Comment by lethosor** [comment]
Ok, reopening until we can track this down

**Comment by myk002** [comment]
@cppcooper FYI, though not a lot to go on here

**Comment by cppcooper** [comment]
Ya no kidding. Without some kind of crash logs.
I could try to integrate some signal handling and stacktracing like discussed on discord, but won't help unless it happens to somebody else in the future.

**Comment by RyushoYosei** [comment]
I had it happen a bit ago, but it's bizzare, It's inconsistant it seems, Though I mostly have encountered it running mods for sure, since I have been running mods, ..Every time i have noticed it I have been using like Playable animal people, but I suppose it would be best to see if I can get it to happen while using no mods.

**Comment by myk002** [comment]
reproducible crash with this save: https://drive.google.com/file/d/1_S2Yvy99IT8xC5zQW7DxVQ3cDygz_fJV/view?usp=share_link
mods: https://drive.google.com/file/d/1okCd4khCGCHLuwxb_JNs7LpRfVvWwMwj/view?usp=share_link

steps:
1) load game
2) enable channel-safely (via gui/control-panel, but it shouldn't matter how)

**Comment by myk002** [comment]
Fixed in #2945
