### ISSUE TITLE
fastdwarf: residents, not just dwarves

### ISSUE THREAD

**Issue by taygetea** [DFHack/dfhack#2922]
When Fastdwarf 1 0 is always turned on, I frequently get elven and human residents not keeping up, making it take much longer to finish jobs that noncitizens can be assigned, like building walls. Either an option to turn on fastdwarf for just the sentient races in your fort, or for only residents outright, would be very useful.

**Comment by myk002** [comment]
note to implementor: there are lots of tools that want residents included in the "citizens" count. We could possibly include them by default (or via parameter flag) in `Units::getCitizens()` and `Units::isCitizen()`

**Comment by lethosor** [comment]
Related to #664

**Comment by SIX10** [comment]
I would hope this would be an option or a separate tool. Sometimes I want my dwarfs going fast but the other races to chill.

**Comment by myk002** [comment]
Closing as dup of https://github.com/DFHack/dfhack/issues/664
