### ISSUE TITLE
deathcause reports strange cause of death

### ISSUE THREAD

**Issue by ab9rf** [DFHack/dfhack#2923]
Reported on [kitfox discord](https://discord.com/channels/329272032778780672/555404726817259580/1076008110021427251):

deathcause reports:

![image](https://user-images.githubusercontent.com/1445859/219804597-c73f6750-7beb-48c8-94e1-4d406d0a0356.png)

in game announcement:

![image](https://user-images.githubusercontent.com/1445859/219804698-1025b480-8701-4062-a6e0-7bcd025b35d8.png)

**Comment by ab9rf** [comment]
in game combat log:

![image](https://user-images.githubusercontent.com/1445859/228681371-0c7a1369-2b49-4c6b-84f8-5e75d4fe2501.png)

deathcause:

![image](https://user-images.githubusercontent.com/1445859/228681466-47fc2de4-8498-4e5d-af4f-09e6911f8c7c.png)

**Comment by quietust** [comment]
The code responsible for displaying the item name:
```
    if event.weapon then
        if event.weapon.item_type == df.item_type.WEAPON then
            str = str .. (", using a %s"):format(getItemTypeName(event.weapon.item_subtype))
        elseif event.weapon.shooter_item_type == df.item_type.WEAPON then
            str = str .. (", shot by a %s"):format(getItemTypeName(event.weapon.shooter_item_subtype))
        end
    end
```
+
```
function getItemTypeName(item_type)
    return df.global.world.raws.itemdefs.all[item_type].name
end
```
Clearly, the "getItemTypeName" function should be reading from `df.global.world.raws.itemdefs.weapons[]`, and it should probably be renamed to `getWeaponSubtypeName` in the process.
