### ISSUE TITLE
zone-remove confirm not working if unit selector is open

### ISSUE THREAD

**Issue by robob27** [DFHack/dfhack#2927]
If you open the unit selector on a Pen/Pasture civzone, the tooltip no longer shows when you mouse over the button to remove the zone. `current_hover` also does not get set, so the confirm protection doesn't work.

When we update confirm to add overlays to buttons we cannot detect with `current_hover`, we will need to include this confirm as one of them

**Comment by myk002** [comment]
Fixed in https://github.com/DFHack/scripts/commit/a6949da157953db5c6ad31a8f55bbfa1f3008020
