### ISSUE TITLE
When using `buildingplan` trying to build a track stop instead places a stone fall trap

### ISSUE THREAD

**Issue by TSM-EVO** [DFHack/dfhack#2942]
DFHack version 50.07-alpha1 (development build 50.07-alpha1-124-ge0c91877) on x86_64

Steps to reproduce:

Go to build-constructions-track stop. Place any track stop, it places a designation for a stone fall trap, and it builds a stonefall trap

**Comment by TSM-EVO** [comment]
It has something to do with the 'stair types' function

**Comment by myk002** [comment]
Thanks! it turned out the call to the is_construction() function was faulty. Fixed in PR.
