### ISSUE TITLE
Realign suspend ecosystem

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#2955]
The new "smart suspend" feature proposed for `unsuspend` puts the tool at odds with its name. I think we need to refactor the components so their functions are more obvious and discoverable.

Proposal:

- rename `autounsuspend` to `suspendmanager` (or some variation thereof) and let it be the main interface for all automated suspend-related functionality
- create `suspend` and give it the capability of suspending all construction jobs or just those that it thinks will block other construction jobs (i.e. put the new "smart suspend" feature there)
- modify `unsuspend` to not unsuspend jobs identified by `suspend` as at risk of blocking another job (by default)

this will result in the same behavior as already implemented in DFHack/scripts#627, but with a clearer naming scheme and division of responsibilities. It also fits in well with our new `forbid`/`unforbid` tool pair with similar features regarding forbidding.

renaming `autounsuspend` will require some migration steps, since it is such a widely-used and important tool. we should add a default alias for it in the internal dfhack init scripts and ensure that `enable` can interpret that alias (which it may or may not do now, and if it doesn't we'll need to modify it so it does)

**Comment by plule** [comment]
Hey @myk002, one small suggestion about the defaults:

> modify unsuspend to not unsuspend jobs identified by suspend as at risk of blocking another job (by default)

I suggest to keep the current behavior as default, this leads to a clearer overall cli:

- `suspend`/`unsuspend` are no surprise by themselves: they just suspend and unsuspend all jobs. Both are useful as one-shot calls.
- `suspend --only-blocking`/`unsuspend --skip-blocking`: Same thing but sligthly smarter. Mostly for users who don't want to enable an automatic process
- `suspendmanager`: Automated process with all the default we think are the best, so appropriate triggers, avoid blocking jobs etc. Also configurable to be able to behave like `autounsuspend`. Intended for user who don't want to micromanage job suspension at all.

**Comment by myk002** [comment]
sounds good to me! thanks!
