### ISSUE TITLE
revflood leaves revealed tiles hidden

### ISSUE THREAD

**Issue by Mizpah** [DFHack/dfhack#2962]
Issue: 

Running revflood with cursor on surface, created a game state where rooms with dwarves in are hidden.

Image below is a room with dwarves in.

![image](https://user-images.githubusercontent.com/3234840/221432065-94e4209a-22c6-45fe-8621-7d2efaaf87f8.png)

reveal all returns visibility, unreveal reverts to no visibility.

Save file attached.

[revflood.zip](https://github.com/DFHack/dfhack/files/10834548/revflood.zip)

**Comment by myk002** [comment]
Could you possibly check if the build at https://github.com/DFHack/dfhack/actions/runs/4452783909#artifacts solves the issue for you? Note that you no longer have to use the keyboard cursor to anchor the revflood source.
