### ISSUE TITLE
modtools/create-unit broken ver#50.05 alpha2

### ISSUE THREAD

**Issue by Wsynchrom** [DFHack/dfhack#2967]
# [](url)
![thingy](https://user-images.githubusercontent.com/126616290/221968689-91598bfc-1e93-463e-8e6d-a479da1844c3.PNG)

**Comment by lethosor** [comment]
This script can't work in 50.05 because of the lack of arena mode. Please upgrade to 50.07-alpha2 and let us know if the problem persists.
