### ISSUE TITLE
gui/dig: Line curve algorithm doesn't produce perfectly symmetrical cruve when mirrored

### ISSUE THREAD

**Issue by johncosker** [DFHack/dfhack#2973]
![curve1](https://user-images.githubusercontent.com/4482627/222935319-40cb9934-78f3-4dea-984d-be9992b874d3.PNG)
![curve2](https://user-images.githubusercontent.com/4482627/222935320-f66f6465-6bef-42a4-aea1-090a4c93eb5f.PNG)

Flipping shapes should produce symmetrical results, so will need to figure out how to fix this.

**Comment by johncosker** [comment]
Initial investigation is leading me to believe this is an issue with it using math.floor instead of rounding to the nearest integer, good results so far after fixing that...

**Comment by johncosker** [comment]
Okay yeah that was it, I'll include the fix in my next gui/dig feature PR.

**Comment by myk002** [comment]
Fixed in DFHack/scripts#634
