### ISSUE TITLE
Missing confirmation for deleting Burrow

### ISSUE THREAD

**Issue by zkaro** [DFHack/dfhack#2989]
There is no confirmation window for deleting a burrow if done via the "Repaint this burrow" toolbar

**Comment by ab9rf** [comment]
Is this is an issue with a DFHack component, or is it a request for a dfhack-implemented improvement on the vanilla UI?

**Comment by zkaro** [comment]
I'd call it an issue with the DFHack component "confirm" and the option "burrow-remove". 

It pops up a confirmation window on removal of burrows, and it works on one mouse UI element but not on another with the same effect. 
So it shows the confirmation window when trying to delete the burrow from the burrow window, where every burrow is listed, but not when in 'pencil mode' editing one specific burrow.

**Comment by myk002** [comment]
@robob27
