### ISSUE TITLE
Buildingplan doesn't remember item filters

### ISSUE THREAD

**Issue by ElsaTheHobo** [DFHack/dfhack#2998]
Version: https://github.com/DFHack/dfhack/actions/runs/4360248149

I'm using buildingplan to make a lot of floors, staircases, etc. I have both maple and basalt blocks available, but I've used the item filter to use only maple blocks for a section of floors and staircases. (and my global settings forbid bars, stones, logs). The floors seem to be fine, and are being made of maple as intended. with the stairs though, once the dwarves run out of maple blocks they start using basalt blocks again (or are using either? not sure)

Misc info:
i have the top of stairs to be down-only, and the bottom of stairs to be up-only
i have buildingplan set to only accept blocks, and not logs, stones, or bars
i'm using ctrl-t to make the dwarves hustle on building stairs (i have a lot of stuff in queue)

**Comment by myk002** [comment]
just to be sure, you set the filter for maple *before* designating the stairs, right?

**Comment by myk002** [comment]
can you reproduce this with the latest build? https://github.com/DFHack/dfhack/suites/11543386026/artifacts/597435502

**Comment by myk002** [comment]
closing for now. please reopen if this is still an issue with the latest build
