### ISSUE TITLE
Feature Request: Automatically set aside dwarves for military.

### ISSUE THREAD

**Issue by pyromartian** [DFHack/dfhack#3010]
A problem that I have early to mid-game is that I have trouble selecting dwarves for military service. And selecting members is tedious at this stage because it's not readily apparent which dwarves are valuable and which are expendable. Usually, I would look through each prospective dwarf and compare skill levels or I would have to open up something external like Dwarf Therapist, and comb through skills that way.
I also have to balance choosing high combat skills/traits and training low-skilled workers to spare those of high talent. 

I would propose a tool that could nickname a percentage of eligible dwarves so that they could be selected to be placed in squads at your leisure. I don't know how many changeable variables the tool can have before it has too much bloat, but it should have at minimum the ability to change the percentage of desired dwarves in service.

**Comment by pyromartian** [comment]
I am going to close this feature request because `sort.lua` plugin has addressed most of these concerns.
While not covering every scenario, it provides a practical solution for most cases.

**Comment by myk002** [comment]
that's good to hear. I've been playtesting the current sort dialog, and I'm pretty happy with it. if you do have ideas of how we can extend it to cover remaining cases, please open up a new issue.
