### ISSUE TITLE
Left click does not register on 50.07-alpha3 (works on 50.07-alpha2) with MRAU UI installed

### ISSUE THREAD

**Issue by kungyen0** [DFHack/dfhack#3013]
Left clicks are bugged after a game is loaded when [MRAU UI](https://github.com/maxarq/mrau-ui) is installed and when using DFHack 50.07-alpha3.  After the game loads, I can only click on the DFHack panel and the MRAU UI panel, but nothing else in-game. I reinstalled 50.07-alpha2 and left clicks in-game are working again. Removing MRAU UI in 50.07-alpha3 also resolves the issue.

**Comment by ab9rf** [comment]
This is a MRAU bug, not a DFHack bug. Suggest you file this as an issue on their github: https://github.com/maxarq/mrau-ui/issues

Closing as out of scope.
