### ISSUE TITLE
game freezed in  50.08 when play in wine on linux

### ISSUE THREAD

**Issue by Dawn-Xu-helloworld** [DFHack/dfhack#3032]
In 50.0x in wine the game freeze when I generate a new world or load a current game,without any errors or warnings appear.

**Comment by Dawn-Xu-helloworld** [comment]
Oh I forgot it.
My computer running Gentoo with OpenRC ,wine version 8.3

**Comment by myk002** [comment]
I've been running DF (and DFHack) successfully in Proton 7.0 (Steam's fork of wine). Does that work for you?

**Comment by Dawn-Xu-helloworld** [comment]
> > I've been running DF (and DFHack) successfully in Proton 7.0 (Steam's fork of wine). Does that work for you? I'm also on Gentoo, incidentally.
> 
> hmmm , have you tried 50.0x classic ? proton is a big package, I don't want to waste too much time on completing

50.07 classic version got freezed...

**Comment by melissaboiko** [comment]
`dfhack-50.08-r1-Windows-64bit` for me, from the github zipfile.

**Comment by melissaboiko** [comment]
did a bit more testing:

 - Fresh unpacks from `dwarf_fortress_50_08.zip` and `dfhack-50.08-r1-Windows-64bit.zip` .
 - No mods.
 - `wine64 Dwarf\ Fortress.exe`
 - Created a world with default presets
 - Hangs (at "Forming lakes...")
 - wine error message:

```
 0114:err:ole:com_get_class_object apartment not initialised
```

**Comment by lethosor** [comment]
Does it hang if you uninstall DFHack?

**Comment by melissaboiko** [comment]
yup! just rename dfhooks and vanilla works again, I'm playing it like that rn with no issues.

**Comment by Dawn-Xu-helloworld** [comment]
> Does it hang if you uninstall DFHack?

DF could work fine with no DFHack

**Comment by myk002** [comment]
is there any output in stderr.log? This one is hard to debug since DFHack doesn't actually *do* anything during worldgen. Is this at the beginning or end of the worldgen process?

**Comment by seeschloss** [comment]
Ok I realize wasn't clear, I didn't even try worldgen because it freezes when loading a game.

There is nothing in stderr.log, the last line is "Invoking: enable work-now" but that happens on the main screen. No new message while loading, and no message once it freezes.

I have to note that the music keeps playing.

**Comment by myk002** [comment]
And this is *during* the savegame loading process, not at the end?

Did you have DFHack installed when you saved the game in the first place?

If you upload your savegame and mods directory and paste the link here, I can try to reproduce the hang on my system and investigate.

**Comment by seeschloss** [comment]
It's at the very end of the loading process as far as I can tell, so maybe it's not even the loading process but just the actual play that hangs. Screen is just blank (with music playing).

The same save loads well with dfhack under Windows (in a virtual machine).

It's a save from a world generated under 0.50.8 without dfhack, I'm going to try and upload it tomorrow.

14 juin 2023 18:39:09 Myk ***@***.***>:

**Comment by seeschloss** [comment]
So I just generated a pocket world (without dfhack), started a fortress (without dfhack) and then enabled dfhack, loaded it and it froze. And I have no mods.

Here is the save: [region2.tar.gz](https://github.com/DFHack/dfhack/files/11754726/region2.tar.gz)

Tried to generate worlds without dfhack, and it froze at "running rivers" every time with a pocket world, but at "forming lakes" starting from "smaller" size.

For the sake of completeness, I just tried to generate a (pocket) world without dfhack and to start a new fortress with dfhack. It freezes at "Preparing graphics... Vanilla Music". Here is this save if you need it: 
[region3.tar.gz](https://github.com/DFHack/dfhack/files/11754736/region3.tar.gz)

**Comment by quietust** [comment]
For the record, this hang can be avoided by running `wine[64] explorer Dwarf\ Fortress.exe` or `wineconsole Dwarf\ Fortress.exe`.

**Comment by seeschloss** [comment]
It does work! Thanks for this info.

**Comment by myk002** [comment]
keeping this open so we remember to document the need for `wineconsole`
