### ISSUE TITLE
is auto-combine a possibility?

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#3033]
### Discussed in https://github.com/DFHack/dfhack/discussions/3029

<div type='discussions-op-text'>

<sup>Originally posted by **tily-lass** March 16, 2023</sup>
the "combine all" command is amazing, and a life saver... is there a way to "autocombine all", maybe once every other day or something?</div>

**Comment by myk002** [comment]
from #3029
solution would be to add `combine all` to the Maintenance list in `gui/control-panel`.
we'd just have to determine an appropriate frequency. if the command takes negligible time to run even on large forts, daily is probably fine.

**Comment by Phyktion** [comment]
If I remember correctly, there is a command to "schedule" other commands based on time.
