### ISSUE TITLE
Buildingplan - Cannot click vanilla buttons under the minimized panel

### ISSUE THREAD

**Issue by AndrielChaoti** [DFHack/dfhack#3037]
Title.

Minimize the buildingplan panel that shows up over the vanilla one, and try to change build modes from select material to use nearest, and try to click "build multiple". trying to click on anything that was originally covered by buildplan is impossible

**Comment by myk002** [comment]
Reproduced. Which is annoying since this tested cleanly not too long ago. Thanks!
