### ISSUE TITLE
Dig jobs are only performed if Prioritize Dig or Dig only labor are enabled

### ISSUE THREAD

**Issue by JayceSL** [DFHack/dfhack#3039]
https://streamable.com/g1nx52 Video where I fiddle to recreate it. You can see the miner go No Job despite there being hundreds of Dig jobs available at priortity 1. He smooths walls (default priority), harvests plants (default priority), instead of going to his Dig job. As soon as Prioritize Dig or he is set to Dig only, he starts digging. I'm fairly sure no Dig job are ever done by anyone if they don't have prioritize Dig or Dig only on. 

Using dfhack-win64-build-20230315-f191334d1

Save file zip was too large to attach, so I have uploaded it plus Mods to Google Drive: https://drive.google.com/drive/folders/1YouRzIEd9xnuFVcM418M1FnNXlGGRaEV?usp=sharing

**Comment by myk002** [comment]
for the record, we discussed this on discord, and determined that it was likely a vanilla issue, not DFHack
https://discord.com/channels/793331351645323264/807444467140788254/1086438133660405811
