### ISSUE TITLE
Adjust the "untested" tag in the docs for better clarity

### ISSUE THREAD

**Issue by blaxout1213** [DFHack/dfhack#3041]
Currently, there are some tools that are not included or built in the latest version. In the docs, these are tagged as "untested", which implies they may be available for testing.

For plugins that don't compile, testing them out isn't even an option, which muddies the language of the tag. We should consider renaming this to "unupdated" or something similar, to better convey that a plugin may not be available at all, while still conveying the original "untested" connotation.

**Comment by myk002** [comment]
other options:
- outdated
- out-of-date
- broken
- unavailable
- out-of-service

**Comment by myk002** [comment]
tasks:

- [ ] rename tag in [spreadsheet](https://docs.google.com/spreadsheets/d/1hiDlo8M_bB_1jE-5HRs2RrrA_VZ4cRu9VXaTctX_nwk/edit#gid=170388995)
- [ ] sync descriptions to Tags.rst
- [ ] sync tags to docs
- [ ] update dev-mode filter in `gui/launcher`
- [ ] update docs for `gui/launcher` dev mode
- [ ] update language in release notes template
