### ISSUE TITLE
Norton removes newest dfhack release under "WS.Reputation.1" threat identifier

### ISSUE THREAD

**Issue by darkfoxprime** [DFHack/dfhack#3043]
Just to let you know: Norton removes every DLL that came with dfhack 50.07-beta1 with the threat identifier "WS.Reputation.1" meaning it's new and "no one in the norton community is running it".

I had to add the dwarf fortress install directory to the exclude-from-scans settings in Norton.

**Comment by lethosor** [comment]
Unfortunately there isn't much we can do about this. False positives are relatively common with new software that Norton hasn't seen before - it will probably go away after some period of time.
