### ISSUE TITLE
"orders clear" not working at all

### ISSUE THREAD

**Issue by jardimdanificado** [DFHack/dfhack#3047]
i have imported library/basic and cant really clear the orders, even if i try "orders clear" it clears, but few moments later every single order from library/basic come back to the list one by one(they do not come back all at the same time), its extremely annoying. 
the library/basic orders seem to be attached to the save, as it's persistent even after imp/exp, exit/load, i've even tried delete the basic file from resources but no lucky, problem stills.

**Comment by myk002** [comment]
Could you possibly upload your savegame and mods and post a link to the files here? I'm not sure what could be making removed orders *reappear*.

**Comment by jardimdanificado** [comment]
never mind, i realized that it's the tailor command that's been loading orders to the queue, so actually wasn't a bug really and had nothing to do with the import orders/clear orders. 
thanks for the reply and sorry for the inconvenience.
