### ISSUE TITLE
More cases to prevent blocking jobs in suspendmanager

### ISSUE THREAD

**Issue by lukemaurer** [DFHack/dfhack#3049]
I needed to build a wall two levels high, so for the second level, I built a ramp and designated the second level of wall to be built. Trouble is, of course, it has to be built starting from the far side from the ramp:

![Janky suspendmanager](https://user-images.githubusercontent.com/262648/226199097-52685dff-37d8-40fc-be34-e6163a753a6c.png)

(Here I built ramps on both sides to speed things up.) Trouble is, suspendmanager saw that it had to suspend the first tile (nearest the ramp) but not that it needed to suspend _every_ tile but the last. Also, if I suspended the others manually, suspendmanager un-suspended them, so I had to turn off "prevent blocking jobs" altogether.

**Comment by myk002** [comment]
@plule

**Comment by plule** [comment]
I had some starting point today to support this, but it will be a significant change on how suspendmanager operate
