### ISSUE TITLE
assertion failed while using `unforbid all`

### ISSUE THREAD

**Issue by ab9rf** [DFHack/dfhack#3068]
![image](https://user-images.githubusercontent.com/1445859/227010363-9c64f4ba-5fbb-42bb-99a0-a64d8ead7dc7.png)

**Comment by ab9rf** [comment]
Additional information: the assertion fails because `units_getCitizens` called `lua_toboolean(L, -1)`, which then calls `index2addr(L, idx)` which then fails the assertion because the Lua state is such that a negative index of -1 is somehow invalid at that point.

This may be an issue with the implementation of `units_getCitizens` or with the Lua context at the time the function is called. I am not an expert on the innards of the Lua engine.

**Comment by myk002** [comment]
It may be that `units_getCitizens` does not properly handle the case where no parameter was sent. It perhaps should be checking whether a parameter exists before calling `lua_toboolean()` I believe at the time I thought `lua_toboolean` would just return `false` if no param were on the stack.

**Comment by ab9rf** [comment]
After researching this, I've concluded that this is a bug in Lua: the language specification provides that an invalid index will return a nil value, but but the runtime contains an assertion that fails when an invalid index is specified, which is specifically allowed by the specification. This is a case of the runtime failing to comport with its published specification, which in my book is a bug.

However, since the code works correctly when assertions are not enabled, and assertions are only enabled for debugging builds, this issue will only affect people using debugging builds: that is to say, developers. As such, I'm recommending no action.
