### ISSUE TITLE
disable ability for Lua to run compiled scripts

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#3070]
to inhibit malware distributed as 3rd party scripts

**Comment by myk002** [comment]
@ab9rf you mentioned this was a one-line change, but looking through the lua header and c files, I didn't see a clean way to turn off processing of pre-compiled scripts. there doesn't seem to be a config toggle for it.

we could do something like mess with the LUA_SIGNATURE or remove the dumping/loading functions, though.

**Comment by ab9rf** [comment]
My informant suggested that it was a one-line change to `dfhack.lua`. He did not indicate what the change was, and it's not evident to me either.

**Comment by myk002** [comment]
This is from the Lua docs: ```
load (chunk [, chunkname [, mode [, env]]])
Loads a chunk.

If chunk is a string, the chunk is this string. If chunk is a function, load calls it repeatedly to get the chunk pieces. Each call to chunk must return a string that concatenates with previous results. A return of an empty string, nil, or no value signals the end of the chunk.

If there are no syntactic errors, returns the compiled chunk as a function; otherwise, returns nil plus the error message.

If the resulting function has upvalues, the first upvalue is set to the value of env, if that parameter is given, or to the value of the global environment. Other upvalues are initialized with nil. (When you load a main chunk, the resulting function will always have exactly one upvalue, the _ENV variable (see [§2.2](https://www.lua.org/manual/5.3/manual.html#2.2)). However, when you load a binary chunk created from a function (see [string.dump](https://www.lua.org/manual/5.3/manual.html#pdf-string.dump)), the resulting function can have an arbitrary number of upvalues.) All upvalues are fresh, that is, they are not shared with any other function.

chunkname is used as the name of the chunk for error messages and debug information (see [§4.9](https://www.lua.org/manual/5.3/manual.html#4.9)). When absent, it defaults to chunk, if chunk is a string, or to "=(load)" otherwise.

The string mode controls whether the chunk can be text or binary (that is, a precompiled chunk). It may be the string "b" (only binary chunks), "t" (only text chunks), or "bt" (both binary and text). The default is "bt".

Lua does not check the consistency of binary chunks. Maliciously crafted binary chunks can crash the interpreter.
```

so setting a mode of `t` would ensure we couldn't load binary chunks.

However, in dfhack.lua, all calls to `load` and `loadfile` *already* specify `t` as the mode, so I'm still confused about what the informant was thinking here.

This does give us a lead, though, if we want to restrict loading binary chunks at the C library level. We could intercept the requested mode and force it to `t`.

**Comment by ab9rf** [comment]
My guess is that the one-line change to `dfhack.lua` my informant was alluding to is to change the calls to `load` and/or `loadfile` to specify `bt`, which would allow loading precompiled chunks. My informant was being evasive on the specifics.

The proposal to intercept the requested mode and force it to `t` seems sound to me, especially given the documentary warning of "Maliciously crafted binary chunks can crash the interpreter" which is among the things I think we are seeking to guard against.

**Comment by ab9rf** [comment]
see also https://saelo.github.io/posts/pwning-lua-through-load.html

**Comment by myk002** [comment]
I see, I thought the informant was suggesting we only had to make a one line change to *protect* ourselves, not that attackers have a one-line change to make to *break* us.

Anyway, I think I've found the code in Lua where we could disable binary mode:

```diff
diff --git a/depends/lua/src/ldo.c b/depends/lua/src/ldo.c
index 316e45c8f..65158df0b 100644
--- a/depends/lua/src/ldo.c
+++ b/depends/lua/src/ldo.c
@@ -767,14 +767,14 @@ static void f_parser (lua_State *L, void *ud) {
   LClosure *cl;
   struct SParser *p = cast(struct SParser *, ud);
   int c = zgetc(p->z);  /* read first character */
-  if (c == LUA_SIGNATURE[0]) {
-    checkmode(L, p->mode, "binary");
-    cl = luaU_undump(L, p->z, p->name);
-  }
-  else {
+  // if (c == LUA_SIGNATURE[0]) {
+  //   checkmode(L, p->mode, "binary");
+  //   cl = luaU_undump(L, p->z, p->name);
+  // }
+  // else {
     checkmode(L, p->mode, "text");
     cl = luaY_parser(L, p->z, &p->buff, &p->dyd, p->name, c);
-  }
+  // }
   lua_assert(cl->nupvalues == cl->p->sizeupvalues);
   luaF_initupvals(L, cl);
 }
```

**Comment by myk002** [comment]
howto for getting binary scripts here:
https://stackoverflow.com/questions/8936369/compile-lua-code-store-bytecode-then-load-and-execute-it
