### ISSUE TITLE
Prioritize jobs table corruption

### ISSUE THREAD

**Issue by drhead** [DFHack/dfhack#3071]
![image](https://user-images.githubusercontent.com/1313496/227076186-aa06e163-b85d-4a74-858d-a7dc66a6bb7f.png)
![image](https://user-images.githubusercontent.com/1313496/227076201-4d27b455-217e-4569-8a14-908f674bf930.png)
These show console outputs of a symptom of the problem.  Persisting after this point will result in prioritize not prioritizing most jobs (most likely the ones that turned to "nil") until you run `disable prioritize` and add back your prioritize config.  I am not sure if the issue happens in memory or if it relates to saving and loading.  I do not know how to reproduce the issue.

**Comment by myk002** [comment]
I have not been able to reproduce this. `prioritize` data appears to be persisted and loaded correctly in my tests. If this happens again, could you save your game immediately and attach it to this issue?

**Comment by drhead** [comment]
Looking further into it I think this does not happen ever in memory and only shows when loading a save after whatever triggers the bug happens.  The only thing I can think of trying that I know I do somewhat often is make a typo when adding a job to prioritize, the output does say "adding 4 jobs" even if you spelled two of the four wrong so maybe that could be it?  

I do have a save where it happened again on load: https://pixeldrain.com/l/kLSdTo1i (ignore mods2.zip).  Try `running disable prioritize`, `prioritize -a defaults`, then something including deliberately misspelled jobs like `prioritize -a Dig DigChannel CarveRamp CarveUpwardStairs CarveDownwardStairs CarveUpDownStairs`, then save and load, maybe?

**Comment by myk002** [comment]
I was not able to reproduce with those steps, unfortunately

**Comment by xominxac** [comment]
Here's the zip with the dfhack-legacy-data.dat, launcher.history, and dfhack.history files as requested.
[Prioritize Jobs Bug.zip](https://github.com/DFHack/dfhack/files/11083743/Prioritize.Jobs.Bug.zip)
Let me know if you need anything else. @myk002

**Comment by myk002** [comment]
fixed. Thank you both for your help!
