### ISSUE TITLE
Suspend manager thinks floor bars block wall when opposite is true

### ISSUE THREAD

**Issue by drewcassidy** [DFHack/dfhack#3074]
Suspend manager is suspending these floor bars, I think because it thinks they would block the adjacent walls, when in fact the walls are impossible to construct WITHOUT the floor bars 
<img width="143" alt="image" src="https://user-images.githubusercontent.com/3837797/227115460-6a603aaa-84fc-4027-92fb-8608ef016d8f.png">

Save: https://pileof.rocks/barswtf.zip
mods: 
[mods.zip](https://github.com/DFHack/dfhack/files/11047622/mods.zip)

As discussed in Discord, sounds like this is an issue with `building:isImpassableAtCreation()`

**Comment by myk002** [comment]
did this turn out to not be an issue?

**Comment by myk002** [comment]
discord discussion link: https://discord.com/channels/793331351645323264/807444467140788254/1088341251008516178

**Comment by myk002** [comment]
@plule

**Comment by plule** [comment]
List of building to take in account:
- wall
- fortification
- windows
- floodgates
- vertical bars
- wall grates
- statues
- gear assemblies? (Double check if passable)

**Comment by ab9rf** [comment]
see also https://github.com/DFHack/df-structures/issues/586
