### ISSUE TITLE
0.40.10-r1: libdfhack.so symbol lookup error on startup

### ISSUE THREAD

**Issue by Treefingers** [DFHack/dfhack#309]
When I run dfhack, I get this:

./libs/Dwarf_Fortress: symbol lookup error: ./hack/libdfhack.so: undefined symbol: _Z10lua_gettopP9lua_State

Arch Linux (32). I have lua (5.2.3-1) and lua51 (5.1.5-4) installed for things like conky, vlc, and geany; no problems with those that I can tell. Same error when I compiled dfhack myself. Same error when I tried DF/dfhack 0.34.11.

**Comment by lethosor** [comment]
DFHack should use the lua library included in the hack folder, but it sounds like it's locating your system library first for some reason - does hack/liblua.so exist?

**Comment by lethosor** [comment]
Please reopen if the issue persists.
