### ISSUE TITLE
tailor/autoclothing(?) -- ordering too many clothes due to strange circumstances

### ISSUE THREAD

**Issue by drhead** [DFHack/dfhack#3093]
Save: https://pixeldrain.com/l/kLSdTo1i (ignore mods2.zip)

Currently I have tailor enabled, and autoclothing is set to 1 silk cloak and 1 silk gloves.

This fort is for some reason producing excessive surpluses of trousers and dresses and a somewhat lesser but still alarming surplus of socks.  I have two particular residents which I know must be responsible for a large portion of the issue: 

- One (Tobul Kacothiden, militia captain vampire) is a vampire I have kept in isolation for some time with her own facilities to make new clothing.  Tailor seems to still be allocating clothing to her, understandably -- I don't really expect it to check for someone being quarantined.  It also, according to the logs, seems to be generating orders for new clothing for covering her *every day* she has worn footwear, bodywear, or legwear.

- Another (Amkash Rodohthremlu, Elephant Man Scholar risen hunter) is an elephant man implicated by the large surplus of elephant man sized clothing.  He seems to be bugged in a lot of ways since when other people would drop an item, he continues to haul it.  Before I raised him as undead he would also refuse to drop mugs, and would refuse to eat and would instead starve to the point of passing out and get food delivered to him (Putnam suspects this is due to the GRAZER tag being kept for animal men).  I suspect this could be causing larger than normal delays in acquiring new clothing and therefore generating too many orders.

Autoclothing is able to detect some of the surplus clothing, but the accounting is all wrong.  It says I have 30 legwear for dwarves, but from my count of my stockpile for trousers I have somewhere in the ballpark of 300 trousers, unworn, for various species.  It sounds like clothing is being continuously allocated whenever it isn't picked up, and that is leading to duplicate orders since the allocation of stockpiled clothing isn't cleared.

**Comment by drhead** [comment]
From further investigation with tailor in trace mode, it seems that stockpiled clothing is not looked at at all by tailor.  It will always order one clothing item for every resident with missing or worn clothing regardless of fortress inventory of clothing.

**Comment by ab9rf** [comment]
tailor specifically scans the fort's inventory, so that's not what is happening. However, it will ignore clothing that is _owned_ but not being _worn_, which means if the fort has a hoarder (and this is a possibility) tailor will keep ordering more clothes to account for the drain on the fort's usable supply created by the hoarder. 

I'm not sure that it's directly possible for tailor to accommodate for this. Hoarded clothing is unavailable to anyone other than the hoarder, and the hoarder themselves isn't creating any order need. At the same time, other units need those clothes. It's not clear to me what a good solution is here.

**Comment by drhead** [comment]
There are a number of hoarders, they are annoying, but that is not the primary issue.  The 300 trousers I mentioned are ones unowned in stockpile bins.  Yet somehow they are being ignored by tailor. This is a nearly 30 year old fort, with all that comes with that age, if that might be affecting things.
