### ISSUE TITLE
Using makeown and tailor together gives weird results

### ISSUE THREAD

**Issue by egladil** [DFHack/dfhack#3103]
If you use makeown on an animal or other creature that does not feel a need for clothes tailor will still happily produce clothes for them.

I believe this could be solved by tailor checking for the `CAN_LEARN` caste flag in addition to the current checks here:
https://github.com/DFHack/dfhack/blob/253832400883474f710291ef0b35bc4e63f8b171/plugins/tailor.cpp#L273-L277

**Comment by ElsaTheHobo** [comment]
I think checking for the EQUIPS token, or both CAN_LEARN and EQUIPS together, would probably be better, as modded intelligent creatures could be given CAN_LEARN but not EQUIPS, which would make them unable to wear clothes

**Comment by ab9rf** [comment]
I'm going to just test for EQUIPS since I think that'll cover the situation in question.
