### ISSUE TITLE
add test in confirm to protect against dangling zone pointer bug

### ISSUE THREAD

**Issue by ab9rf** [DFHack/dfhack#3116]
There is a bug in vanilla DF that, if you delete a zone to which a unit is assigned, a dangling pointer is left in the unit that points to the now-deleted zone. This can cause misoperation or crashes.

The `confirm` plugin could check for this when it intercepts zone deletion requests and either refuse to delete the zone if unit(s) are still assigned to it, or offer to clear those assignments.

**Comment by myk002** [comment]
We could intercept the vanilla zone removal and instead call our own code, which does handle this case (thanks to 20k): https://github.com/DFHack/dfhack/blob/develop/library/modules/Buildings.cpp#L1371

**Comment by myk002** [comment]
fixed in vanilla
