### ISSUE TITLE
`warn-starving` alerts for unseen hostile units

### ISSUE THREAD

**Issue by ab9rf** [DFHack/dfhack#3117]
> Unit #15783 (amphibian man ()), Amphibian Man Elite Wrestler is dehydrated!

This unit is (presumably) deep in the caverns and is not part of the fortress. I don't know why he's having a hard time (based on what `gm-editor` says, he actually went insane which I didn't know was a possibility), but `warn-starving` should not warn for such units.

I can make a save available if needed, or just bug me on Discord if you need more deets.

**Comment by myk002** [comment]
I suppose we should check for both properties -- if unseen or hostile then skip?

**Comment by myk002** [comment]
another option is `isFortControlled()`. this does not include residents. should we report on residents?
