### ISSUE TITLE
`caravan` documentation does not match tool

### ISSUE THREAD

**Issue by ab9rf** [DFHack/dfhack#3124]
the command `caravan` yields the error "caravan: Missing subcommand" but the documentation says that this is equivalent to `caravan list`

**Comment by myk002** [comment]
do you perhaps need to sync? this works for me with current HEAD

**Comment by ab9rf** [comment]
i'll check, i am a day behind

**Comment by ab9rf** [comment]
indeed, i was out of date.

closed as already-fixed
