### ISSUE TITLE
`seedwatch all` watches tree seeds

### ISSUE THREAD

**Issue by Cubittus** [DFHack/dfhack#3126]
seedwatch should only be watching plantable seeds, and not tree seeds.

![Dwarf_Fortress-2023-03-30-103438-049](https://user-images.githubusercontent.com/627213/228856019-6b770166-64e5-47d8-84f3-8fe3730a8d7f.png)

**Comment by ab9rf** [comment]
`seedwatch` should default to not watching tree seeds and should only watch a tree seed if explicitly told to do so. `seedwatch all` should not touch tree seed settings
