### ISSUE TITLE
`seedwatch <seed> 0` does not remove seeds from the watchlist

### ISSUE THREAD

**Issue by Cubittus** [DFHack/dfhack#3127]
According to the help `seedwatch PLUM 0` should remove plum pits from the watchlist.  Instead it just sets the watch target to zero and still lists PLUM.

![Dwarf_Fortress-2023-03-30-103438-049](https://user-images.githubusercontent.com/627213/228857430-42960de6-823d-453e-ba89-b81c1d77166b.png)

**Comment by ab9rf** [comment]
seeds with limit 0 are, in fact, removed from the watchlist; the report shows all seeds _in the fortress_ whether or not they are watched. seed swith a limit of 0 are not watched; seedwatch will not touch the kitchen settings for that seed

this is thus a UI/UX issue and not actually an operational problem

**Comment by ab9rf** [comment]
really the only thing i can think to do here is to display something other than "0" for a seed that is present in inventory but not on the watchlist, which might more readily convey to the player that the seed is not being watched than the 0 does currently

**Comment by ab9rf** [comment]
note also that with #4650 merged, plum pits (and other unplantable tree seeds) won't show at all in seedwatch output
