### ISSUE TITLE
buildingplan: display current filter on main buildingplan screen

### ISSUE THREAD

**Issue by ab9rf** [DFHack/dfhack#3133]
The "select flter" screen describes the current filter, it would be nice to display this on the main buildingplan screen as well

**Comment by TaxiService** [comment]
agreed, this is of utmost importance

the idea is to eventually have each entry in planneroverlay read something like this:
``` 
>1 Building material of [any material] [x]
   Available now
```

with "any material" being the currently selected filter. If it was "chert" it'd read "[chert]", and so on.

**Comment by ab9rf** [comment]
i think this is done but i can't find a relevant pr, if it is can someone please link it and close?

**Comment by myk002** [comment]
It's not quite complete. right now it indicates that there is a filter, but not specifically what it is.

**Comment by myk002** [comment]
now sufficiently implemented in https://github.com/DFHack/dfhack/pull/4219
