### ISSUE TITLE
buildingplan: wrong item list for offering places

### ISSUE THREAD

**Issue by ab9rf** [DFHack/dfhack#3134]
The list for offering places should be available offering place items, not generic materials.

![image](https://user-images.githubusercontent.com/1445859/229076111-f07acdf8-22a9-4828-8fc4-782fb08e128d.png)

![image](https://user-images.githubusercontent.com/1445859/229076164-4015e38c-ca15-40ce-ab36-afe8ee303470.png)

**Comment by ab9rf** [comment]
Same problem occurs with display furniture

**Comment by myk002** [comment]
thank you for finding this. This was due to incorrect logic applied in #3086
