### ISSUE TITLE
buildingplan error ResizingPanel overflows upwards

### ISSUE THREAD

**Issue by TaxiService** [DFHack/dfhack#3136]
if the error panel gets more than four errors, it starts shifting upwards and stays there!

[Dwarf_Fortress_0WnF9pxXBN.webm](https://user-images.githubusercontent.com/5853667/229115480-5b5f60c7-981e-4c96-be2f-c5f8abcdcb9b.webm)

to fix this you have to reload the whole suite of buildinplan scripts (or reload the map/restart the game i presume)

**Comment by TaxiService** [comment]
>you have no idea how much I struggled with this in the initial implementation.

i am starting to get the idea... 🤣 been running into issues like this all day yesterday, while trying to make the whole window be based off ResizingPanels.

like, i see there's a way to set a max height with "w", but is there not a way to set a _minimum_ height? 🤔

**Comment by TaxiService** [comment]
also yeah, while experimenting it looks like bumping up the max height to, like, 21 instead of 20 "fixes" this issue. (line 313 of planneroverlay.lua)

i could make a pr just for this 🤔

**Comment by myk002** [comment]
I'm pretty unhappy with ResizingPanels. I originally created them as a convenience when using `autoarrange_subviews` (which itself is a terrible name. why couldn't I just have called it "autolayout"?), but ResizingPanels just do not behave well in many cases.

**Comment by TaxiService** [comment]
oh boy. assigned to a bug! this is my first time so pls be gentle~

...seriously though. This bug is "fixed" in [this pr](https://github.com/DFHack/dfhack/pull/3123), but it's not a definitive fix.
If the error window got more than 5 errors, it would happen again. :\\

What i'm thinking is we should rewrite/rework the ResizingPanel class (it's called a "class", right?) so that it behaves more predictably. 🤔 
Like, we should be able to define its anchor points (and thus the directions in which the panel is allowed to expand) and its minimum/maximum height/width (so that an "empty" panel wouldn't be of height 0)

While messing around with such panels for the planneroverlay ui, i was trying to have a parent ResizingPanel change its height depending on its children, but found it very hard/impossible to control. 😣 

How could we go about addressing all this?
(also, while we're at it we could define those horizontal/vertical dividers/separators more generally)
