### ISSUE TITLE
Feature Request: Please add a way where we can clean up the bodies and weapons in arena mode

### ISSUE THREAD

**Issue by GentlemanSkelly** [DFHack/dfhack#3138]
As the title says, I would love for a feature that can clean up the bodies, body parts, and weapons in the arena mode. It's very annoying to exit out of the arena mode just to clean everything up. It's even worse when you have a bunch of mods installed that you want to test out because you have to reactivate them every time you go back into the arena mode. Having to exit out of the arena mode just to clean everything up is my number one complaint for Dwarf Fortress. I would be very thankful if this feature is implemented in DFHack.

**Comment by myk002** [comment]
@GentlemanSkelly What do you think of the design here: https://github.com/DFHack/dfhack/issues/3316#issuecomment-1550745936 ?
