### ISSUE TITLE
Refine default prioritize list

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#3145]
proposed default list:

```lua
-- take care of rottables before they rot
CustomReaction (TAN_A_HIDE)
PlaceItemInTomb
PrepareRawFish
StoreItemInBarrel
StoreItemInStockpile (Food)
StoreItemInStockpile (Body)

-- ensure medical, hygiene, and hospice tasks get done
ApplyCast
BringCrutch
CleanPatient
CleanSelf
DiagnosePatient
DressWound
GiveFood
GiveWater
ImmobilizeBreak
PlaceInTraction
RecoverWounded
SeekInfant
SetBone
Surgery
Suture

-- ensure caged units are tended to quickly
SlaughterAnimal
StoreItemInStockpile (Animals)

-- ensure noble tasks never get starved
InterrogateSubject
ManageWorkOrders
ReportCrime
TradeAtDepot

-- get tasks done quickly that might block the player from getting on to the next thing they want to do
BringItemToDepot
CustomReaction (ADAMANTINE_WAFERS)
DestroyBuilding
DumpItem
FellTree
RemoveConstruction
```

We should also add more information to the "which job types should I prioritize?" section, including describing situations where you might want to add to the default list, permanently or temporarily. Especially for quantum stockpiles, which might benefit from 

- PushTrackVehicle
- StoreItemInVehicle

especially at relatively low population counts

From conversation at https://www.reddit.com/r/dwarffortress/comments/127x7pr/comment/jeltp6z/?utm_source=share&utm_medium=web2x&context=3

**Comment by Codedependent77** [comment]
Perhaps also PlaceItemInTomb ?

**Comment by myk002** [comment]
That sounds like a good idea
