### ISSUE TITLE
Depot item list disappearing when ctrl clicking

### ISSUE THREAD

**Issue by Franzyd** [DFHack/dfhack#3155]
In some situations ctrl clicking a bin makes the list disappear, ctrl+x "fixes" it

![DFhack depot ctrl click](https://user-images.githubusercontent.com/56082757/229360457-e543aa2e-69de-4049-998d-b7d883a1d21b.gif)

**Comment by myk002** [comment]
This is in the latest DFHack 50.07-beta2 release?

**Comment by myk002** [comment]
Could you upload your savegame and mods and post a link here so I can examine your specific situation?

**Comment by Franzyd** [comment]
I think [the other save](https://drive.google.com/file/d/1fSDjOU0xv8UY5BOVbvQGfXSlElKEJLQ9/view?usp=sharing) from a week ago could also be used; no mods used
