### ISSUE TITLE
DFHack 50.07-beta2 - warn-starving warning that dead dwarf is dehydrated.

### ISSUE THREAD

**Issue by qwerbnot** [DFHack/dfhack#3158]
warn-starving gives me a warning that one of my dwarves is dehydrated even though the dwarf is already dead and buried. The issue only happens when loading the save after launching the game - it does not happen again when returning to the main menu and reloading the save.
![image](https://user-images.githubusercontent.com/43368463/229443741-e632b3e4-e4e5-4676-a826-97b571892b83.png)
![image](https://user-images.githubusercontent.com/43368463/229443777-3ed24104-c555-447b-9fec-87ff9c078fc8.png)

**Comment by myk002** [comment]
@qwerbnot Do you happen to have a save file I could download to check a proposed fix? I'm interested in why that unit is still in the active vector, and what other flags they might have set.

**Comment by qwerbnot** [comment]
The file is too big to upload directly here, so here's a download link: [https://1drv.ms/u/s!AjwzRdZKtU01g4VTJFTWbF9tebePfQ?e=MxVP0E](https://1drv.ms/u/s!AjwzRdZKtU01g4VTJFTWbF9tebePfQ?e=MxVP0E)
Also to the mods I'm using:
[https://steamcommunity.com/sharedfiles/filedetails/?id=2900381145](https://steamcommunity.com/sharedfiles/filedetails/?id=2900381145)
[https://steamcommunity.com/sharedfiles/filedetails/?id=2898549749](https://steamcommunity.com/sharedfiles/filedetails/?id=2898549749)
[https://steamcommunity.com/sharedfiles/filedetails/?id=2899720701](https://steamcommunity.com/sharedfiles/filedetails/?id=2899720701)
[https://steamcommunity.com/sharedfiles/filedetails/?id=2908779064](https://steamcommunity.com/sharedfiles/filedetails/?id=2908779064)
[https://steamcommunity.com/sharedfiles/filedetails/?id=2898589374](https://steamcommunity.com/sharedfiles/filedetails/?id=2898589374)

**Comment by myk002** [comment]
verified. Thank you!

**Comment by TaxiService** [comment]
🤔 i think i'm encountering this issue as well. Sometimes, when i load this save, I get a warn-message about a llama starving, but sometimes i don't!

I didn't investigate much about it, so the llama in question might as well be dead for all i know 🤔 All i know is that my other llamas should have no reason to be starving, none of them showed any signs of mistreatment.

https://dffd.bay12games.com/file.php?id=16563
