### ISSUE TITLE
Blueprint doesn't ignore plants

### ISSUE THREAD

**Issue by Franzyd** [DFHack/dfhack#3163]
When recording a blueprint, tiles with plants on them are considered undug, but furniture is properly recorded
Here is a room with two plants
![image](https://user-images.githubusercontent.com/56082757/229604766-fcb5d72f-ac8a-4d59-92c2-edec4a05c8bc.png)
Here is how quickfort digs it
![image](https://user-images.githubusercontent.com/56082757/229604982-0157fc7b-22f9-4090-ba01-d109d59a40d3.png)
Here is the file
[bedroom.csv](https://github.com/DFHack/dfhack/files/11141693/bedroom.csv)

**Comment by myk002** [comment]
I actually just found this **while making the trailer video for our Steam page**
It was fixed yesterday in https://github.com/DFHack/dfhack/commit/d13dfd7d496cf45a5a56e5951457efb4ed9a5e70

you can pick up a fixed build here: https://github.com/DFHack/dfhack/actions/runs/4600304671#artifacts

**Comment by myk002** [comment]
I think I found it while playing around in the fort you uploaded, actually, since I recognize that screenshot : )
