### ISSUE TITLE
gm-editor should start in read-only mode

### ISSUE THREAD

**Issue by Cubittus** [DFHack/dfhack#3171]
Perhaps it's just me, but on occasion I have accidentally clicked on a gm-editor window to give it focus and unknowingly turned by best cheesemaker into a zombie.  Boolean fields toggle state with a single click and no confirmation or warning.

To protect me from myself I'm going to modify gm-editor so that by default it won't make any changes.
I'll add a command-line flag to start in read-write mode (-dev or -edit) and a key-shortcut (Ctrl-D) to switch to it.
Hopefully have a PR up soonish.

**Comment by lethosor** [comment]
Maybe we should just disable this click behavior for boolean fields? It's relatively new compared to the keyboard toggle. Another option could be to ignore clicks if the window isn't focused. 

I'm not sure I'd like an editor defaulting to a state where edits aren't allowed.

**Comment by Cubittus** [comment]
I use it more as a data explorer than an editor 99% of the time.
With a command-line flag, an alias could be set to always run it in editing mode.
Or perhaps the other way around - default read write, and a flag to start in read-only mode?
Either way pressing Ctrl-D would toggle edit mode.
