### ISSUE TITLE
Ropes (cloth and silk) not listed in filter window when building wells.

### ISSUE THREAD

**Issue by Saint-Ajora** [DFHack/dfhack#3172]
When trying to build a well the list includes metal, clay, stone, glass, and wood options but no cloth or silk ropes. After rebooting a message saying that the well could not be built popped up and the placed ghost of the well disappears. I do not know if the materials (if any were even placed in it) vanished or not but nothing was around the well nor in the bottom of the well after the reboot.

![noropesforthewell](https://user-images.githubusercontent.com/29880249/230066570-e23dc935-899c-4178-b962-66bcf11cdde8.png)

**Comment by Saint-Ajora** [comment]
https://dffd.bay12games.com/file.php?id=16562

**Comment by myk002** [comment]
Could you possibly include an archive of your mods directory? I don't have steam on my development workstation.

**Comment by Saint-Ajora** [comment]
> Could you possibly include an archive of your mods directory? I don't have steam on my development workstation.

I have no idea how to do that. I could list them out for you if that helps.

**Comment by Saint-Ajora** [comment]
1) Seasonish Crops
2) Work Detail Icons
3) Rounded hills
4) See-Through Smoothing Designations
5) [Vanilla] Deon's missing Plant Graphics replacement
6) Interface Tweaks
7) Audible Alerts
8) Squad & Burrow Icons
9) SK GigaDwarfs Stress
10) Leather output scales with creature size
11) Reduced Z-Level Fog
12) Multi Alterations and fixes
13) Ketaros Stones Variations
14) Vanilla Two Handed Weapons
15) Workshops without floors
16) Metal plate floor
17) Additional Races: Ratfolk
18) Additional Races: Gnolls

**Comment by myk002** [comment]
An archive meaning a zip file of those mods (or just your entire `mods/` directory -- it's fine if more mods than you need get included). It will likely be small enough that you can attach the zip directly to this Issue. You won't need to upload it to dffd.

**Comment by myk002** [comment]
I was able to reproduce the issue in another world, so no need to upload mods. Thanks!

**Comment by Saint-Ajora** [comment]
Not a big deal but just wanted to be thorough, there is no option for wool ropes in wells and they don't automatically use them.

**Comment by myk002** [comment]
Can you make a wool rope? I didn't think that was possible..

**Comment by fricy** [comment]
Wool is yarn. Possibly fixed in #3251? These materials should show up in chains, wells, rollers.

**Comment by myk002** [comment]
Oh, yeah, I did add that in. It should be in the latest beta push on Steam (the "beta" branch)
