### ISSUE TITLE
buildingplan: manual material selection for roads still randomly selects materials

### ISSUE THREAD

**Issue by uecasm** [DFHack/dfhack#3174]
Build -> Constructions -> Paved Road (or bridge, probably others too).

Do not enter a filter, but do "choose from items: yes".

Select an 8x4x1 (or other) area.  See it says "9 building materials" before second click.

Choose Items window appears, but only allows selecting 1 material.

**Dorfs will use random materials for the rest.**

(Having said that, the final name and appearance does match the selected material, but you can see the random other materials in the info list when clicking on the road/bridge.)

Also, the docs say that there's supposed to be an overlay when clicking on a planned building that shows the materials that are allocated to it.  ~~I haven't seen that, although I'm not actually short of materials; it's unclear from the docs if it's intended to appear when the materials are all available but not actually delivered yet as well.~~  Ok, I see the overlay when I select unavailable materials.  Just not for available-but-not-delivered-yet.

**Comment by myk002** [comment]
I can't reproduce this with the current code. Just to check, which version of DFHack do you have installed? Run the `help` command and copy down the last line of its output.

**Comment by uecasm** [comment]
Yes, this is looking a lot better in beta2.  Apologies for the noise.
