### ISSUE TITLE
Hotkey/Keybinding for ending Civilian Alert uses the same keybinding as launching gui/dig

### ISSUE THREAD

**Issue by dimtave** [DFHack/dfhack#3186]
I just installed the Steam Beta for DFHack and was configuring my Civilian Alert, and it appears that the ctrl+d shortcut for sounding the all-clear just launches the gui/dig plugin. ctrl+w for Sound Alarm also does not appear to function. Caps lock is not on, just fyi. This may have already been reported, in which case I can delete this.

**Comment by myk002** [comment]
Do the shortcuts work for you if the window has focus? If you click somewhere else, and the window's title bar darkens, then the window has lost focus and won't interpret keystrokes. Without focus, Ctrl-D will just be interpreted by the map, which will launch `gui/design` (nee `gui/dig`).

**Comment by dimtave** [comment]
I can confirm that the window had focus during testing of these hotkeys. I also tried the hotkeys while I had the civilian alert configuration window open and closed, but both times, the dwarf fortress application window was still in focus. I also confirmed that my caps lock key was disabled, as I know that will affect other keystrokes and door fortress. Not sure how it will affect the keystrokes for DF hack.

**Comment by myk002** [comment]
When I say that the window has focus, I'm referring to the DFHack window.
Window has focus, Ctrl+w and Ctrl+d should function:
![image](https://user-images.githubusercontent.com/977482/231086397-117a603e-b7c2-4fc0-bdde-8a8f6ce5c5b2.png)

Window does not have focus. Keyboard input falls through to the lower layer:
![image](https://user-images.githubusercontent.com/977482/231086480-73de8fb4-87c9-4b6c-9269-8a3c42362cbe.png)
