### ISSUE TITLE
Prospect does not appear to be calculating Z level properly

### ISSUE THREAD

**Issue by intoempty** [DFHack/dfhack#3187]
Testing on DFHack 50.07b2, in Steam.

Prospect returns the Z level on which the material is located. However, it appears to be calculating strangely. For example, in my current fortress, the surface is at Elevation 44 in the GUI. Prospect says that various shrubs are on Z: 144..146, which if I subtract 100, gets me 44. So perhaps it's adding 100 to the Z level somehow? 

My current fort has surface at 44, and if I go down as far as possible, the Elevation in the GUI reads -112. The range of values returned from Prospect is -12 to 146; -12 is the SLADE.

So it looks like I subtract 100 if the reported Z is below 0, and _add_ 100 if it's above.

**Comment by myk002** [comment]
We might need to change the labeling. "Z-level" starts at 0 at the lowest level and goes up. "Elevation" has a linear offset from z-level, but is dependent on the region-dependent ground level. We should start listing both in tools where we currently report z-level.

**Comment by myk002** [comment]
Also, is the version you're testing 50.07-r1b2 or 50.07-beta2? They both happen to be available on Steam right now (in different release channels). Where in Steam did you see those version numbers, by the way? I was having trouble finding them on the client side.

**Comment by intoempty** [comment]
@myk002 I saw the version numbers in the console -- `help` prints `DFHack version 50.07-beta2 (release) on x86_64` at the very end. (This is from manual install, not using Steam for DFHack yet as I didn't ask for a code--figured I'd wait.)

**Comment by ab9rf** [comment]
toady switched the z level display for v50. it looks like the offset relative to what it was in v47 is always 100, but i have yet to completely confirm this
