### ISSUE TITLE
Home/End have no effect when typing in launcher

### ISSUE THREAD

**Issue by sparr** [DFHack/dfhack#3188]
When I press Home or End while typing into the launcher I would expect the cursor to move to the first or beyond the last character already typed, equivalent to ctrl+a and ctrl+e.
(Linux)

**Comment by myk002** [comment]
This is a limitation of the DF input system. The Home and End keys are simply not represented by the default keybindings, and therefore are not accessible from the UI widgets. Perhaps this will change once the SDL2 port is completed. As a stopgap, the keybindings currently assigned to "beginning of line" and "end of line" are Ctrl-A and Ctrl-E (documented [here](https://docs.dfhack.org/en/latest/docs/dev/Lua%20API.html#editfield-class))

**Comment by myk002** [comment]
Now that g_src is on GitHub, I'll see if I can submit a PR to DF that will allow home and end to get piped through.

**Comment by myk002** [comment]
reopening since this can't be fixed until 50.14 is out
