### ISSUE TITLE
Control panel shows configure button for automelt with no fort loaded

### ISSUE THREAD

**Issue by sparr** [DFHack/dfhack#3189]
Clicking the button leads to the dfhack console displaying the red message "gui/automelt: automelt requires a map to be loaded".

Either the configuration dialog should be accessible without a map/fort loaded, or the button should be disabled.

**Comment by myk002** [comment]
Ha, I was hoping nobody would notice that : P There's a comment in the code that says: ```lua
'automelt', -- TODO needs dynamic detection of configurability
```

The full solution is discussed more at https://github.com/DFHack/dfhack/issues/2213#issuecomment-1272620803 but that calls for a general system of tagging for scripts that is just too much to implement for the upcoming stable version. In the meantime, we could just write some special-case code for automelt that will be obsoleted later when we get a better system going.
