### ISSUE TITLE
Hide buildingplan panel while the tutorial is running

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#3190]
Otherwise you can't complete the tutorial

**Comment by sparr** [comment]
Specifically, the tutorial trigger for the completion of the carpenter workshop doesn't happen.

**Comment by myk002** [comment]
Perhaps we should go a step further and disable all overlays when the tutorial is running so our overlays won't confuse tutorial players. We could even display a pop-up that says what's happening and why.
