### ISSUE TITLE
Partial Search for Item Filter

### ISSUE THREAD

**Issue by Kab112** [DFHack/dfhack#3191]
As it is in the Steam version you can search "io" and get Diorite when building walls, floors etc.

**Comment by myk002** [comment]
This is a controversial choice that DFHack made long, long ago. The search boxes specifically search only substrings starting at the beginning of a word. I have never been convinced that this is the best choice, but I'm certain there will be conflicting opinions on what is "best" here.

**Comment by dimtave** [comment]
Just gonna throw this in here, I have arthritis and a crippling connective tissue disorder, and on some days, I have to play with a wrist and thumb brace on which makes it a bit more difficult to filter typing the whole material name. But, on the steam version of the game without DF hack, I can type 'ee' for steel, or 'pp' for copper, etc, and find what I'm looking for a bit easier. So if that was included in DF hack, it would certainly be a huge help.

**Comment by myk002** [comment]
It is actually not too much work to make this user-configurable. We could add a toggle to `gui/control-panel`'s Preferences tab that can change this behavior.

**Comment by myk002** [comment]
Until we get this implemented, you can fix this yourself by editing the `hack/lua/gui/widgets.lua` file. File the lines that look like this:
```lua
                    if not search_key:match('%f[^%p\x00]'..key) and
                        not search_key:match('%f[^%s\x00]'..key) then
```
and replace them with a single line that looks like this:
```lua
                    if not search_key:match(key) then
```
