### ISSUE TITLE
Loading game produces starvation warning for all past starving-then-butchered animals

### ISSUE THREAD

**Issue by sparr** [DFHack/dfhack#3193]
I was playing, got a starving warning, dismissed it, butchered the animal. Repeat. Then I save, quit, load, and dfhack produces a single starvation warning listing both already-butchered animals, which I dismissed. Two more rounds of single new animal warning, dismiss, butcher. Save, quit, load. Now I get a warning listing all four animals.

**Comment by ab9rf** [comment]
this is probably a variation on #3158, which was mitigated by dfhack/scripts#666 and thus is probably fixed in dev

**Comment by sparr** [comment]
Good call. I searched for starv but not dehydrat, not realizing they are the same plugin. I'll assume it's fixed and this is a dupe until I confirm otherwise.
