### ISSUE TITLE
quickfort order 77 failing

### ISSUE THREAD

**Issue by COBManbearpig** [DFHack/dfhack#3197]
![image](https://user-images.githubusercontent.com/130250197/230808057-c2c9dbd5-3fb5-4c6b-ab59-62bd934458d8.png)
> quickfort orders 77

...warf Fortress/hack/scripts/internal/quickfort/orders.lua:53: unhandled label: door
stack traceback:
        [C]: in function 'error'
        ...warf Fortress/hack/scripts/internal/quickfort/orders.lua:53: in upvalue 'inc_order_spec'
        ...warf Fortress/hack/scripts/internal/quickfort/orders.lua:114: in upvalue 'process_filter'
        ...warf Fortress/hack/scripts/internal/quickfort/orders.lua:185: in field 'enqueue_building_orders'
        ...Dwarf Fortress/hack/scripts/internal/quickfort/build.lua:1000: in field '?'
        ...arf Fortress/hack/scripts/internal/quickfort/command.lua:93: in global 'do_command_raw'
        ...arf Fortress/hack/scripts/internal/quickfort/command.lua:137: in upvalue 'do_apply_modifiers'
        ...arf Fortress/hack/scripts/internal/quickfort/command.lua:161: in global 'do_command_section'
        ...arf Fortress/hack/scripts/internal/quickfort/command.lua:202: in upvalue 'do_one_command'
        ...arf Fortress/hack/scripts/internal/quickfort/command.lua:228: in upvalue 'do_list_num'
        ...
        ...rary\steamapps\common\Dwarf Fortress\hack\lua\dfhack.lua:810: in function 'dfhack.run_script_with_env'
        (...tail calls...)
        [C]: in field 'runCommand'
        ...rary\steamapps\common\Dwarf Fortress\hack\lua\dfhack.lua:853: in upvalue '_run_command'
        ...rary\steamapps\common\Dwarf Fortress\hack\lua\dfhack.lua:857: in function 'dfhack.run_command_silent'
        [C]: in field 'hideGuard'
        ...apps\common\Dwarf Fortress/hack/scripts/gui/launcher.lua:886: in function <...apps\common\Dwarf Fortress/hack/scripts/gui/launcher.lua:871>
        [C]: in field 'on_submit'
        ...steamapps\common\Dwarf Fortress\hack\lua\gui\widgets.lua:722: in method 'onInput'
        ...Library\steamapps\common\Dwarf Fortress\hack\lua\gui.lua:584: in function <...Library\steamapps\common\Dwarf Fortress\hack\lua\gui.lua:578>
        (...tail calls...)
        ...Library\steamapps\common\Dwarf Fortress\hack\lua\gui.lua:797: in function <...Library\steamapps\common\Dwarf Fortress\hack\lua\gui.lua:786>
        [C]: in ?

**Comment by myk002** [comment]
All `quickfort orders` will fail until the underlying mechanism is updated for v50. For a quick(er) fix, though, I'll see if I can remove the command for now so at least if fails with "unknown command" instead of a horrible wall of error message text.
