### ISSUE TITLE
DFHack 50.07-beta2 is lacking of gui/dig.

### ISSUE THREAD

**Issue by Mayka32** [DFHack/dfhack#3201]
When i istalled 50.07-beta2 version i've got only 27 of 28 plugins of "gui" and that's qui/dig. I've downloaded and reinstalled it few times but all the same.
![image](https://user-images.githubusercontent.com/130351545/230863874-b1f9a8c3-451f-4c80-b066-ca55ed47ab5a.png)

**Comment by myk002** [comment]
`gui/dig` has been renamed to `gui/design` since it is taking on a larger role (working with constructions as well as just digging). If you run `gui/dig`, it still responds to that name, it just doesn't show up in the autocomplete.

**Comment by Mayka32** [comment]
> `gui/dig` has been renamed to `gui/design` since it is taking on a larger role (working with constructions as well as just digging). If you run `gui/dig`, it still responds to that name, it just doesn't show up in the autocomplete.

Oh, thank you very much!
