### ISSUE TITLE
Allow players to hide armok tools

### ISSUE THREAD

**Issue by Mimtos** [DFHack/dfhack#3206]
Hi I'm a dwarf fortress newbie (50 hours) and have never touched DFHack before and just wanted to input from the first few hours of my using it. I do understand that this is an advanced tool so hopefully I'm not asking too much when making the tool easier for newbies.

I really appreciate the tags system and expanding this to be user friendly would be the key point in making DFHack more accessible. A problem I'm currently having with it is the excess of commands in specified tags in a sense that I don't want some of these commands in there due to their cheat-like manner.

 For example running 'tags plants' and 'ls plants' gave me a bunch of plant related commands for my playthrough. It showed me useful features/features like autochop, autofarm, ban cooking, combine, and seedwatch. However it showed me some cheat-like commands like growcrops, createtree, and deteriorate that I would never touch but it still takes up space on my console. 
 
If there was an easy way to edit my tags list, some sort of filter, 'no cheats' mode, or a non-cheats tag section it would be great. I would like to just 'ls/tags plants' next time around where it only shows the commands that will improve my gameplay experience but not straight up cheat for me. The plants tag is a pretty small list but in some other tags there are like 10+ commands that are just cheats to edit your dwarf into essential god mode for example and it completely clutters the tags list.

Please let me know what you think or if I missed anything, thank you again for letting me access beta.

**Comment by silverwing235** [comment]
> cheat-like commands like growcrops, createtree, and deteriorate

...the third of which isn't exactly a cheat, just an FPS cleaner? [https://docs.dfhack.org/en/stable/docs/tools/deteriorate.html](url)

**Comment by Mimtos** [comment]
> ...the third of which isn't exactly a cheat, just an FPS cleaner? [https://docs.dfhack.org/en/stable/docs/tools/deteriorate.html](url) As in, Framerate per second.


Like I mentioned, plants isn't a perfect example since it's a small list of commands. But if you look at other tags, there are plenty of cheat commands which I do not want to see. The point is that I did not want to even see growcrops and createtree in the first place, they are straight up cheats. 

Also to you and DFhack deteriorate may be a FPS cleaner which I can see but to me it's almost cheat-like. That's why I was opting for other solutions like editing tags list. Maybe down the line I will start using it it but I would just like the flexibility of determining what commands I want to see or not see.

**Comment by myk002** [comment]
Ah, I've been waiting for a real player to ask for this : )

So, we've put some work into supporting what you're asking for. For anything "cheaty" (though we've avoided using that word since this is a single-player game and what one person may consider a cheat another might consider a "shaping of the game to their enjoyment", we've added the tag "armok". `gui/launcher` has code already to filter out specific tags, but it doesn't include that one.

We could add a configuration toggle to `gui/control-panel` that will let you decide whether "armok" tools are included in the default autocomplete list, or whether they are hidden within "dev mode" (Ctrl-D). How does that sound?

In the meantime, you can add this feature to your own game by editing the `hack/scripts/gui/launcher.lua` file and finding the line that looks like this:

```
local DEV_FILTER = {tag={'dev', 'unavailable'}}
```

Change that to

```
local DEV_FILTER = {tag={'dev', 'unavailable', 'armok'}}
```

and you have your very own cheat-free tool list.

**Comment by Mimtos** [comment]
That's perfect and I'm glad you pointed out the whole "cheaty" definition. I agree with you on that and that's why I was wondering if you guys had some sort of editing method.

I'm not too well versed yet in DFHack to make a decision on whether a 'dev mode' or 'config toggle' is better for your planned feature, I definitely trust you guys a lot more to make the decision. 

In general for the armok tools list, I don't think users would mind inputting to help add/delete commands from the armok list but eventually expanding into a custom tags list feature could be something to consider in the near future. Something like compile commands from all different kind of tags to make some sort of command presets. Maybe that can open up opportunities to sharing command presets with one another, if that is technologically possible of course.

**Comment by myk002** [comment]
well, I'm conflating some terminology here. Let me spec out a little more what I'm thinking:

In `gui/control-panel` there can be a setting for "Hide armok tools" with a description of "Armok tools are those that give you complete control over an aspect of the game or provide access to information that the game intentionally keeps hidden. Enable this setting if you prefer to not have these tools shown wherever commands are listed."

The effect of this setting would be to hide armok tools from:
- `ls` (unless `--dev` is passed on the commandline)
- `tags` (unless `armok` is specifically requested)
- `gui/launcher` autocomplete and related commands lists (unless dev mode is enabled with Ctrl-D)

Does that sound good?

**Comment by Mimtos** [comment]
That sounds perfect! The only thing I was worried about is how do specific commands get classified as armok or not? As you saw earlier in this thread, we had conflicting opinions on whether 'deteriorate' is cheating or not.

**Comment by myk002** [comment]
It's determined manually, by general consensus. The spreadsheet where we track all the tools and assign tags is here: https://docs.google.com/spreadsheets/d/1hiDlo8M_bB_1jE-5HRs2RrrA_VZ4cRu9VXaTctX_nwk/edit?usp=drivesdk
