### ISSUE TITLE
documentation is out of date

### ISSUE THREAD

**Issue by ab9rf** [DFHack/dfhack#3208]
> The release archives contain several folders, including a hack folder where DFHack binary and system data is stored, a dfhack-config folder where user data and configuration is stored, and a blueprints folder where [quickfort](https://docs.dfhack.org/en/latest/docs/tools/quickfort.html#quickfort) blueprints are stored.

the `blueprints` folders have been moved into `hack` but the documentation has not been updated to reflect this

also v50 no longer has a `raw` folder in the top-level so "the root DF folder, which should already include a data folder and a raw folder" is misleading and confusing

**Comment by myk002** [comment]
oof, that's on one of the summary pages, right? I may have missed that when I was updating docs about the blueprint move

**Comment by ab9rf** [comment]
On the "Installing" page

**Comment by myk002** [comment]
Ugh. I remember I held off updating this page since the native builds of DF seemed "near". Well, time to update now.

**Comment by myk002** [comment]
I should really also mention Steam somewhere on this page, since this release will coincide with Steam availability.
