### ISSUE TITLE
Search bar, search function, filterable unit/dwarf lists

### ISSUE THREAD

**Issue by yourmum21** [DFHack/dfhack#3225]
Hey, I looked for this request but even tho I'm finding this issue to be tremendous I couldn't find one posted already. How are people playing this and asking for the most random shit in Future of the Fortress instead xD?

Starting at a pop of 50+ dwarves multiple important gameplay features become a huge chore.
There are multiple and I'll list them as I come by them but these ones are the most shitty experiences, forcing you to be scrolling and searching forever:

- Assigning dwarves to a squad (you don't want skilled laborers, you want the low skilled bois you found and renamed using Dwarf Therapist) (another option would be another feature allowing you to sort for something like "peasant" or "highest skill level" (like in DT) to find expendable dwarves).
- Finding a specific dwarf in the unit list (citizen information menu -> key "u"). The vanilla sorting options are awfully insufficient, making sortable only by "name" and "profession"
- Adding a dwarf to a workshop

- This would be another issue but related to that: You should be able to jump to a unit from every screen that lists it. Important would be the labor screen, the nobles screen and the squad screen.

**Comment by myk002** [comment]
implemented in https://github.com/DFHack/dfhack/pull/3864 (and others)
