### ISSUE TITLE
add Trade Depot reachability mode for gui/pathable

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#3230]
So people can debug their trade depots

**Comment by lethosor** [comment]
Does DF keep a reachability matrix for this anywhere?

**Comment by myk002** [comment]
Not that I know of. As far as I know we'd have to do the pathing calculations ourselves. That's not completely terrible, performance-wise, since it won't have to update as the cursor moves like `gui/pathable`'s existing mode

**Comment by lethosor** [comment]
IMO this should be a separate script, then.

**Comment by myk002** [comment]
Fair enough. It might still use the `pathable` backend to render, but that's an implementation detail
