### ISSUE TITLE
Suggestion: global keybind for toggling keyboard cursor

### ISSUE THREAD

**Issue by Codedependent77** [DFHack/dfhack#3238]
Having a toggle kb cursor keybind set by default might be a good idea. I like Alt-K for keyboard, but I saw someone else recommend Alt-T for toggle.

keybinding add Alt-K "lua \"df.global.d_init.flags4.KEYBOARD_CURSOR = not df.global.d_init.flags4.KEYBOARD_CURSOR\""

(I saw this somewhere - reddit or bay12 probably - but cannot find it again to give proper attribution)

**Comment by myk002** [comment]
From testing, it isn't *quite* this simple. Yes, that will toggle the keyboard cursor, but it only shows up where you expect it to if the cursor already has a valid position. If the first thing you do is turn on the keyboard cursor and hit an arrow key, the map will zoom to the upper left corner of the map on the bottom underworld level.

There at least needs to be a little more logic to initialize the keyboard cursor to the center of the current visible screen when turning it on.

**Comment by myk002** [comment]
Ok, this does it, though it's borderline too complicated for an alias: 

alias add toggle-kbd-cursor lua "if df.global.d_init.flags4.KEYBOARD_CURSOR then df.global.d_init.flags4.KEYBOARD_CURSOR = false else local guidm = require('gui.dwarfmode') guidm.setCursorPos(guidm.Viewport.get():getCenter()) df.global.d_init.flags4.KEYBOARD_CURSOR = true end"
