### ISSUE TITLE
gui/design FreeForm Last Mark info gives the position of the cursor

### ISSUE THREAD

**Issue by Franzyd** [DFHack/dfhack#3244]
In gui/design when using the FreeForm shape the Last Mark coords give the same position as the Mouse coords which is the current position of the cursor. It should give the position of the last point that was made.
![image](https://user-images.githubusercontent.com/56082757/232326334-03e7bf8a-dd8c-4739-b698-6a4fa64e91b2.png)

**Comment by myk002** [comment]
@johncosker

**Comment by johncosker** [comment]
Fixed by #3324 and https://github.com/DFHack/scripts/pull/693
