### ISSUE TITLE
Add option for hiding terminal window by default

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#3248]
This can be something as simple as a hide option in the control panel

**Comment by fricy** [comment]
Is this live already? Because my console was gone, but there was no option to turn it on in the GUI. I had to manually edit gui/control-panel.lua to get my trusty console back.

**Comment by myk002** [comment]
It's live in the Steam "beta" branch. The scripts HEAD hasn't made it into the "50.08-beta" branch yet. We should get an updated 50.08-beta soon.

**Comment by myk002** [comment]
@fricy it's pushed now

**Comment by fricy** [comment]
Confirmed! thx for all the fixes!
