### ISSUE TITLE
Prioritize issue with dig jobs

### ISSUE THREAD

**Issue by Codedependent77** [DFHack/dfhack#3261]
With dig and smooth walls both prioritized for future jobs, I've noticed an issue with dwarves assigned dig jobs but not locked to it digging a block, getting assigned a smooth wall job, walking away ~6 steps, their assigned job changes back to a dig command near where they had been digging (not a newly revealed dig job) and they walk back and do the dig job. Rinse and repeat - a lot of back and forth.

I don't recall seeing other jobs as the assigned job when they walk away, so I'm not sure if this is just a dig/smooth walls issue or if other prioritized jobs can cause this behaviour.

**Comment by myk002** [comment]
any prioritized job can cause this behavior. it's a result of how `prioritize` interacts with DF job selection, and it's not really solvable. This is why I advocate so heavily in the docs for not prioritizing frequent jobs like digging or constructing buildings.
