### ISSUE TITLE
Always force zscreen pausing option for DF50's GM-editor

### ISSUE THREAD

**Issue by Rumrusher** [DFHack/dfhack#3265]
so given how much the new version of DF seems to destroy top viewscreen having gm-editor just letting DF be active seems like it hinders folks access to certain data and trying to just get all the different viewscreens where it does that manually seems like would require someone to be as quick with print screens as the game is with loading.
so maybe gm-editor having an arg option to force pause always might work?
like 'gui/gm-editor FP' then the rest of the command  like:

'gui/gm-editor FP scr'

**Comment by myk002** [comment]
Do we need to inhibit calls to `render()` and `input()` as well, or just to `logic()`?
