### ISSUE TITLE
GUI for autodump-destroy-here

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#3273]
perhaps merge into `gui/mass-remove`? including the "OMG Undo" button.

actually no that's a bad idea to mix "armok" functionality with "non-armok" functionality in the same tool. different UI.

**Comment by TaxiService** [comment]
would it make sense/be possible to have some sort of global "enable armok" thing modify the look/functionality of all other tools?

what i mean is: imagine if we actually did put this stuff in `gui/mass-remove`, but it would only appear in its interface if this global "armok" thing was enabled. 🤔 

..._would this make any sense?_ probably not... but i'm throwing ideas around, if anything just to then avoid going in this direction :joy:

**Comment by myk002** [comment]
I agree on fewer tools overall. The "armok" non-armok tools split is something to consider, though. we need to enforce some sort of separation between the two, and our current mechanism involves tags, which are applied at the tool level. we could start integrating "hidden" armok functionality inside of existing tools, but we need to consider our approach to doing so carefully. The easier, and potentially more user-friendly, route is to keep armok and non-armok tools strictly separate.

**Comment by myk002** [comment]
Folding in to #3316
