### ISSUE TITLE
dfhack create-item

### ISSUE THREAD

**Issue by superherojayse-maker** [DFHack/dfhack#3280]
I am asking for help regrading a mod i am making for DF, i cannot seem to find a way to bypass the Gui and create an item so that when an event happens i do not get promoted every time to choose and just have this pre-determined and sugeestions here is the code

local create = require('gui/create-item')
local modid = 'callback_mod'
local function unitcall()
dfhack.print('hi')
dfhack.create('item', {type = 0, subtype = 0, mat_type = 0, mat_index = 0, quantity = 1})
end
unitcall()

this is the most recent version of the changes i made

**Comment by myk002** [comment]
Ref discord convo: https://discord.com/channels/793331351645323264/1072680256919588914/1099166857795211406
