### ISSUE TITLE
Update GUI for `confirm`'s pop-ups

### ISSUE THREAD

**Issue by TaxiService** [DFHack/dfhack#3282]
![Dwarf_Fortress_cCjTe5EsLC](https://user-images.githubusercontent.com/5853667/233769081-83b36c03-03a1-454b-9335-92fa377ac8f6.png)

hotkeys cannot be clicked, uses an old border

**Comment by myk002** [comment]
I've got a branch in progress that will fix this. It's not simple since this window was rendered entirely from C++.

**Comment by TaxiService** [comment]
yeah i noticed 😆 i scoured any lua file seemingly related to this and found nothing
