### ISSUE TITLE
DFHack version number on title screen

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#3290]
create an overlay that displays it, down by the DF version in the lower left corner?

**Comment by lethosor** [comment]
Don't we already have this in the `title-version` plugin?

**Comment by myk002** [comment]
Do we need an entire plugin for displaying a line of static text? This is the kind of thing that overlays are supposed to make dead simple

**Comment by lethosor** [comment]
Sure. I just wanted to clarify that it was something that already existed.
