### ISSUE TITLE
update gui/create-unit

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#3301]
needs adaption to the new Arena data structures/interface

**Comment by Thazzeus** [comment]
Current create-unit issues are incorrect referencing for certain variables.

**Comment by myk002** [comment]
we might need to wait until DF supports keyboard navigation (or Putnam gives us a createUnit vmethod) before `modtools/create-unit` can function again. in the meantime, I ported the work you did in DFHack/scripts#694 to a GUI that brings up the new arena interface for actual manual interaction in DFHack/scripts#713, which I think might be sufficient to close this issue.
