### ISSUE TITLE
[RemoteFortressReader] Some materials names are encoded in CP437 instead of UTF-8

### ISSUE THREAD

**Issue by plule** [DFHack/dfhack#3304]
When retrieving the material list with RemoteFortressReader::GetMaterialList, (some) materials names  are not valid UTF-8, which makes the protobuf deserialization fail. Maybe some protobuf library will be able to continue, but unfortunately at least the rust one just fails to deserialize the entire message.

Depending on the worldgen, sometimes it will be fine, but here is one where the issue can be seen: [save](https://drive.google.com/file/d/1klKpt3K98TIixYCL1HGzC_1C6a1aceM9/view?usp=share_link). In that save, one of the material is named `Behemoth of Zikth bone` which is the CP437 encoding of `Behemoth of Zikâth bone`.

Client side, it can be worked around by commenting or replacing the `string` declaration in the proto with a `bytes` declaration, and decode it from here.

**Comment by myk002** [comment]
@RosaryMala can I assign this one to you?
