### ISSUE TITLE
Request for a way to identify which written materials on the map teach the secrets of life and death

### ISSUE THREAD

**Issue by BeerNTacos** [DFHack/dfhack#3313]
I play in worlds in which It is possible to acquire a large amount of written materials all in one go and the interface to check which books will turn a dwarf into a necromancer when they read it is hindered by the current UI.

I would love a way to mouse over a listing in the written materials menu in which a tooltip pops up to say which of the roughly 300 topics the written material is about, but that may require a lot of work so I think something like running a command to identify and then list which written materials will teach necromancy may be more feasible, with other features added on, like the specific kinds of necromancy powers that would be, picking other specific subject topics to list, or maybe listing all of the written materials and their subject topic at once.

**Comment by myk002** [comment]
Could you provide a savegame where you have some secrets in stock?

**Comment by fricy** [comment]
[There is a lua script](http://www.bay12forums.com/smf/index.php?topic=170462.0) that appers to cover this topic, but it needs some updates to the new version.

**Comment by BeerNTacos** [comment]
@fricy, that's the Library script & it's what gave me the idea in the first place. While I would love it if the creator updated it to work with v50+, the creator of the script doesn't want to work on updating it with the current version of DF until some specific changes are made. That's the reason why I'm looking to see if anyone was willing to provide at least some of the functionality that script provided.

@myk002, here's a link to a save that has several written materials concerning life and death, via slab and several codices/scrolls: https://drive.google.com/file/d/1WHQv9_Ewsq6bF6R2_9b40pYOvc8khYz5/view?usp=sharing

**Comment by myk002** [comment]
Fixed in DFHack/scripts#696
