### ISSUE TITLE
DFHack tries to use unreachable items when building constructions

### ISSUE THREAD

**Issue by Penumbra69** [DFHack/dfhack#3318]
DFHack version `50.07-beta1 (release) on x86_64`
Game Version: `Dwarf Fortress v50.07 (Steam)`
OS: `Windows 11 Pro (22621.1555)` 
CPU: `Intel i9-12900K x64`
RAM: `32GB`

## Issue: 
When attempting to build something with an object that is unreachable, the vanilla build menu doesn't list the item - but DFHack's build construction menu will, and assign a construction job that can never be completed.

## Steps To Reproduce:
I have reproduced a minimally viable test fort [here](https://drive.google.com/file/d/1SdoRRcOKK9Bm0mq6ih3-JizZ5TIfljGZ/view?usp=sharing).

There are "Willow Logs" in the brook (fallen there when cut) - and attempting to construct a floor with them in one of the open spaces will have different behaviors when using Vanilla vs DFHack.  

Vanilla: There are no "Willow Logs" available to build with.
DFHack: There are "Willow Logs" listed, but construction jobs will never complete.

## Expected Behavior:
 - Unreachable items are filtered from the available build materials
 
## Actual Behavior:
 - Unreachable items are listed and can be selected

## Workaround:
 - If I "forbid" the willow logs in the water, Vanilla and DFHack agree they can't be used.

**Comment by myk002** [comment]
I should have asked about the version you were running first. 50.07-beta1 was two releases ago, and `buildingplan` has changed a lot since then. I'll try the fort, but can you also check to make sure you can reproduce the problem on the latest release? https://github.com/DFHack/dfhack/releases

**Comment by myk002** [comment]
I reproduced the issue. Looking into it more. Thanks!

**Comment by myk002** [comment]
Fixed. Wow. **thank you** for bringing this to my attention.
