### ISSUE TITLE
Bridge not being built from raw stone

### ISSUE THREAD

**Issue by Franzyd** [DFHack/dfhack#3320]
If I select any raw stone (boulders) as building material for a bridge, the bridge will never be built no matter how many masons you have. This doesn't happen with stone blocks. I've tested the same without DFHack and it works fine.
[the save](https://drive.google.com/file/d/1j0kkQPXYQT6UW8P563itWtOg7aICqAZs/view?usp=sharing)

**Comment by myk002** [comment]
Are you referring to the bridge you already have planned in that save or to bridges that you choose specific materials for?

Looking at the save a bit, I see that you have a bridge configured to be built out of blocks of hematite. Is that the one that is not being built?

![image](https://user-images.githubusercontent.com/977482/234855469-e8939592-822e-4604-8b3b-12bf9f935e10.png)

**Comment by Franzyd** [comment]
Not that one, that one will work. Try building a bridge out of andesite for example

**Comment by myk002** [comment]
I was, actually, able to build a bridge out of an andesite boulder:
![image](https://user-images.githubusercontent.com/977482/234969565-bdebb22a-8da3-4804-a86d-2e3cea17063b.png)

it did take a while though (I'm not sure where the boulder came from - it could have been a long way away).

I used the "Choose items manually" dialog to pick the boulder. Is that how you did it?
![image](https://user-images.githubusercontent.com/977482/234969802-3fac5e53-8dab-4cf3-a845-df0e8f32cf6a.png)

**Comment by Franzyd** [comment]
> I used the "Choose items manually" dialog to pick the boulder. Is that how you did it? The filter is still set to magnetite blocks, which of course is ignored when choosing manually.

That is how I do it plus I get everyone to be masons, but still no luck after waiting a few days - keeps saying "Construction inactive.". I also tested it on my laptop where I have a fort in which building such bridge is no problem, but after downloading this save the same problem occurs.

**Comment by myk002** [comment]
This *might* be due to an issue I just fixed -- #3319

Could you try installing this build and seeing if that fixes the issue for you?
https://github.com/DFHack/dfhack/actions/runs/4823897083#artifacts

**Comment by Franzyd** [comment]
This new build did indeed work and the bridge was completed.

**Comment by myk002** [comment]
Thanks! Closing as fixed by #3319
