### ISSUE TITLE
reset-arena

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#3322]
either a new tool or extend some existing tool to cover the use case.

After an arena battle, the place is a mess. it would be useful to have a single command to clean everything up.

Essentially the equivalent of:
- `autodump destroy` for all items
- `clean all` for spatters
- maybe also `exterminate` any remaining units?

**Comment by GentlemanSkelly** [comment]
I love this idea! May I suggest something else as well? Can you add a way where we can assign everything to be dumped? It'll be very tedious if we individually click on every dead body/body parts/items and assign them to be dumped. It would be a very useful tool if we could automatically assign everything to be dumped/destroyed.

**Comment by lethosor** [comment]
Doesn't DF have the ability to mass-designate items for dumping? I'm not sure if that feature made it into v50 yet, but it definitely existed in 0.47 (`d-b-d` and select the whole map).

Anyway, dumping isn't supported in the arena, so if you find that feature is missing from DF, you should open a new ticket for it.

**Comment by lethosor** [comment]
Regarding the proposed reset-arena: it's also possible to modify the terrain (e.g. creating lava/water/obsidian, adding trees) - how much of that do we want to reset?

**Comment by lethosor** [comment]
> I haven't tried it myself, but apparently this is only a fort feature; it didn't make it into arena

Sure, but that's the point I was making in my second comment: dumping isn't supported in the arena _at all_. Never has been, and it doesn't make sense, because you also can't create zones, and there are no "citizens" that would take on dumping jobs (or jobs in general, aside from combat).

**Comment by myk002** [comment]
The approach I took in `gui/autodump` was to just treat "area select" as a separate mode. It will act on items marked for dump by default, or if you select items off the map (like you would in arena mode), it will act on those instead.

**Comment by myk002** [comment]
I think this might be adequately covered by `gui/autodump`
