### ISSUE TITLE
Way to teleport/destroy items that's not `autodump`

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#3340]
scrolls are increasingly a thing now, which can't be marked for dumping, making autodump less useful.

we could potentially extend `gui/teleport` to include items and add box select. maybe it could also have a `teleport all items marked for dumping` and it could be our GUI solution for autodump?

**Comment by fricy** [comment]
Scrolls dropped by visitors/ambushers have the trader flag set. When that flag is turned off in gm-editor dwarves will happily stockpile them in the library.

**Comment by myk002** [comment]
folding into #3316
