### ISSUE TITLE
[suggestion] Allow use of "autodump destroy" without active cursor

### ISSUE THREAD

**Issue by zacjohnston** [DFHack/dfhack#3362]
I frequently use the `autodump destroy` command to clean up unwanted items. However, I never actually use the in-game keyboard cursor or any of the related `autodump` commands that rely on the cursor. So every time I want to use `autodump destroy` after marking a bunch of items for dumping (e.g. using the Stocks screen), in order to avoid the "unsuitable state" error I have to manually:

1. Pause the game
2. Navigate to settings to enable keyboard cursor
3. Unpause the game
4. Activate the keyboard cursor (e.g. by opening the mining interface)
5. Execute `autodump destroy`
6. Repause the game
7. Navigate back to settings to disable keyboard cursor
8. Unpause the game

This all gets very tedious and frustrating since I'm not even using something that actually requires the keyboard cursor in the first place! (I understand it may actually rely on it under the hood somehow, but my suggestion is to remove that restriction)

**Comment by fricy** [comment]
Linking to #3316

**Comment by myk002** [comment]
@zacjohnston What do you think of the design here: https://github.com/DFHack/dfhack/issues/3316#issuecomment-1550745936

**Comment by zacjohnston** [comment]
@myk002 That looks great. I do get "unsuitable state" even when running from the `gui/launcher`

**Comment by myk002** [comment]
Ok, I'll look into that. `gui/autodump` will work, but I understand that a commandline is still useful in this case
