### ISSUE TITLE
investigate buildingplan not getting configured properly on new forts

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#3364]
it could be the control panel not treating the autostart settings correctly
or it could be buidlingplan retaining configuration between forts (i.e. not resetting on world unload)

**Comment by myk002** [comment]
I could not reproduce this issue by configuring buildingplan in one world, then retiring the fortress and starting a new fort in a new world. global config was initialized correctly

**Comment by fricy** [comment]
I may not understand the issue correctly, but I think settings persist if you load a world, set filter settings, (save?), then load a different fort without quitting the game.

**Comment by myk002** [comment]
Yeah, that's what I tested.  Do you have a test case that shows the problem? The issue may not actually exist. I filed this issue based on what I thought someone was saying, but I may have misunderstood the circumstances.

**Comment by fricy** [comment]
I swear I've seen that happen, but can't reproduce it either. I'll keep it in mind.
