### ISSUE TITLE
Suggestion: improvement to gui/mass-remove

### ISSUE THREAD

**Issue by fricy** [DFHack/dfhack#3369]
Edit: I'm an idiot, it already does that if all options are deselected. Maybe add that info into the description? 
Issue can be closed.

Allow differentiating between buildings/constructions already built and only in the planning phase.

Use case: I need to remove a couple of walls designated by building planner. The material filter was not correct, and they are never getting built. However there are other construction on the area that the script will want to remove unless I micromanage it.

Implementation v1:
right now the settings are: 
Construction: Leave alone/Remove

Updated: 
Leave alone/Remove planned/Remove built/Remove all

Implementation v2:
Buildings: Leave alone
Constructions: Leave alone
Suspend: Leave alone
Planned: Remove

**Comment by myk002** [comment]
Planned constructions are actually buildings, and would be removed with the buildings option. If they're getting removed even with "leave buildings alone", then that might be a bug in itself.

**Comment by fricy** [comment]
No, it's the building option. 
It just needs some tooltip or help text to make it easier to figure it out the first time.

**Comment by myk002** [comment]
Maybe change "constructions" to "built constructions"?

**Comment by fricy** [comment]
Perhaps. But that option seems to be the most straightforward. It just removes built constructions. 

The "Building" option however removes:
Furnitures
Doors
Machines
Traps
Workshops
Planned constructions
Some constructions like trackstops and bridges

I don't know which is a game limitation, and which is an oversight in coding.

I'd suggest splitting that button into multiple options if possible:

Implementation v3:
Workshops (Machines)
Furniture (Doors, Nest boxes, Hives, Traps, maybe Trackstops?)
Constructions (Bridges)
Planned buildings/constr.
Suspend

And maybe an undo button/brush to reverse a misclick. You can't uncancel planned stuff

**Comment by myk002** [comment]
> And maybe an undo button/brush to reverse a misclick. At least for stuff that's already built, because planned buildings are cancelled on the fly.

Note that this "undo" functionality exists, but is currently commented out due to an issue with v50 crashing when we cancel a DeconstructBuilding job
