### ISSUE TITLE
failed to run on steamdeck

### ISSUE THREAD

**Issue by wicast** [DFHack/dfhack#3392]
I get this error when booting dfhack:

[steam-2346660.log](https://github.com/DFHack/dfhack/files/11504133/steam-2346660.log)

**Comment by lethosor** [comment]
This looks like a DLL is missing from your DF installation. Can you try re-verifying DF from Steam?
```
 74.058:01b8:01bc:err:module:import_dll Library steam_api64.dll (which is needed by L"Z:\\home\\deck\\.local\\share\\Steam\\steamapps\\common\\Dwarf Fortress\\hack\\launchdf.exe") not found
```

**Comment by wicast** [comment]
> This looks like a DLL is missing from your DF installation. Can you try re-verifying DF from Steam?
> 
> ```
>  74.058:01b8:01bc:err:module:import_dll Library steam_api64.dll (which is needed by L"Z:\\home\\deck\\.local\\share\\Steam\\steamapps\\common\\Dwarf Fortress\\hack\\launchdf.exe") not found
> ```

i tried re-verifying, re-install and different version of proton, but still get the same result.

**Comment by myk002** [comment]
could you show the list of files that are in your `/home/deck/.local/share/Steam/steamapps/common/Dwarf Fortress/` directory?

**Comment by myk002** [comment]
I think I found the problem. I failed to include steam_api64.dll in our distribution when I did a manual upload. I'll get this fixed tomorrow on the beta Steam branch

**Comment by myk002** [comment]
Could you try updating to the beta branch now and see if this is fixed?

**Comment by wicast** [comment]
> Could you try updating to the beta branch now and see if this is fixed?

Fixed! That's great!
