### ISSUE TITLE
Superdwarf doesn't work on modded non-dwarf creatures

### ISSUE THREAD

**Issue by DragonEyeNinja** [DFHack/dfhack#3395]
I am playing with Intro's Kobold Civ and trying to use superdwarf to speed up their actions, but to no avail. It still takes the standard amount of time to complete stuff.

Fastdwarf works fine; it's superdwarf that doesn't function properly.

**Comment by myk002** [comment]
could you upload a zip of your savegame and mods? Looking at the code, it's not obvious why it isn't working. We'd need a savegame to investigate.

**Comment by DragonEyeNinja** [comment]
[Sure, here you go.](https://mega.nz/file/6B9QQYxB#p7-yXx6dzqZ4HFdNrOOw4DcR1yQzLrV7EQ4LBlsYvIk) I couldn't get a direct file upload since it was too large.

Mods are:
Better Engravings (Elaborate Design)
Pool Spawn Fix
Cooler World Names
Grey/Reduced Z-Fog
Cave Spider Syndrome Recovery
Shaped Boots
Rounded Hills
Interface Tweaks
Unisex Dwarven Beards
Intro's Kobold Civ

All of these mods have been used with vanilla dwarves instead (alongside the unisex beards mod) and superdwarf works fine for those, so I don't think any of these ones are causing the issue.

**Comment by myk002** [comment]
Could you upload a zip file of your mods folder? I need them to load the savegame.

**Comment by DragonEyeNinja** [comment]
[mods.zip](https://github.com/DFHack/dfhack/files/11523254/mods.zip)
> Could you upload a zip file of your mods folder? I need them to load the savegame.

**Comment by myk002** [comment]
I was not able to reproduce this. Running `superdwarf add` on a miner produced this speedy creature:

Uploading simplescreenrecorder-2023-06-19_15.14.30.mp4…
