### ISSUE TITLE
Compacted Animals show as Missing and are not removed by fix/dead-units fix/missing-units required?

### ISSUE THREAD

**Issue by mikeloeven** [DFHack/dfhack#3398]
Basically excess animals disposed of in a compactor are not properly registered as dead and cannot be removed from the dead units list by the fix/dead_units command separate command or flag needs to be added to clear missing entries for entities that are dead but marked as missing.

**Comment by DragonEyeNinja** [comment]
IMO I think a script that marks "Missing" creatures that got atom smashed as properly dead would be more useful.

**Comment by myk002** [comment]
I believe this is a vanilla "feature". Units aren't marked as dead until there is a witness of the corpse. If there is no corpse, there is no witness. I think eventually they are "proclaimed" dead, after a number of weeks.

**Comment by lethosor** [comment]
How long ago did you atom-smash the units in question? `fix/dead-units` deliberately won't remove units that died less than a month ago

**Comment by myk002** [comment]
Closing since this appears to be WAI
