### ISSUE TITLE
Feature Request: Generic Streaming Platform Support For Units

### ISSUE THREAD

**Issue by Dragoon209** [DFHack/dfhack#3399]
For streamers, I think it would be awesome to allow them to allow the chatrooms to interact with the unit data.  Chatters would be able to request unit data, list the squad members, names and occupations of dwarves, likes/dislikes etc.

Chatters could check on their favorite dwarves, redeem a twitch points reward to allow them to name a pet or available dwarf, and generally allow for the dynamic requests without the streamer having to stop/open units/search/zoom to unit or so on.

Potential Needs

- command to list all units of specific types (Fort members, visitors, pets, others/forgotten beasts)
- command to change the nickname and profession 
- command to request the stats of a specific unit (potentially from a streamer pre-made list, or based on the chatter's username)

Thanks for the time and awesome work!

**Comment by ab9rf** [comment]
tools like this are likely best implemented via dfhack's remote API. dfhack exposes a fairly complete remote API, using protobuf, that can be accessed using a protobuf implementation within whatever scripting languages is supported by the streaming extensions the streamer uses for chat interaction. protobuf implementations exist for virtually every remotely popular programming language

for more information, please see [the dfhack remote interface documentation](https://docs.dfhack.org/en/latest/docs/dev/Remote.html)

**Comment by myk002** [comment]
closing this since it's mostly out of scope for DFHack itself, though it's definitely a good idea for an external tool
