### ISSUE TITLE
DFhack gui launcher no longer accepting '_' character or using the caps lock

### ISSUE THREAD

**Issue by GoatsMcnuggie** [DFHack/dfhack#3400]
Using 50.08-r2cr1 is causing some new issues with the gui/launcher box, specifically use of the caps lock no longer types text capitalized (holding down shift does work) and I cannot type the underscore '_' character into it at all. This is specifically an issue with commands like exterminate, as it cannot target creatures like "ORIOLE_MAN" without the name being exact.

**Comment by GoatsMcnuggie** [comment]
> I couldn't reproduce this issue on my system: ![image](https://user-images.githubusercontent.com/977482/239575727-d736792d-d3a3-417f-94e9-d34ad85d835a.png)
> 
> if you delete/move the `prefs/interface.txt` file and restart DF, does it fix it?

That does in fact fix my issue. Sorry for report, but thank you very much for your help.

**Comment by myk002** [comment]
I'm glad it was fixed. Thanks!
