### ISSUE TITLE
Protecting assigned wheelbarrows in autodump-enabled stockpiles (logistics plugin?)

### ISSUE THREAD

**Issue by wsfsbvchr** [DFHack/dfhack#3430]
So, (in 0.47.05) I started using autodump for certain stockpiles, but occasionally the wheelbarrows assigned for those stockpiles get marked for dumping as well. It might be because of interrupted hauling jobs, after which the wheelbarrows have to be hauled back, or it might be because of something else.

Looks like the logic handling that is this: https://github.com/DFHack/dfhack/blob/develop/plugins/autodump.cpp#L56C2-L61

One way to do it would be to check the id of the item that's possibly being marked for dumping against what's listed under building.container_item_id, which seems to contain the ids of the wheelbarrows, and building.container_type can be used to determine whether the container item is actually a wheelbarrow or not.

Dunno what it should do for bins or barrels assigned for the stockpile. Dump or not dump, or empty and dump, or dump and empty? That could vary, but it's pretty clear that the wheelbarrows shouldn't be dumped.

**Comment by myk002** [comment]
I believe this is fixed in the new `logistics` plugin with the new scanning logic:
```cpp
static void scan_stockpile(color_ostream &out, df::building_stockpilest *bld,
        MeltStockProcessor &melt_stock_processor,
        TradeStockProcessor &trade_stock_processor,
        DumpStockProcessor &dump_stock_processor,
        TrainStockProcessor &train_stock_processor) {
    auto id = bld->id;
    Buildings::StockpileIterator items;
    for (items.begin(bld); !items.done(); ++items) {
        df::item *item = *items;
        scan_item(out, item, trade_stock_processor);
        if (0 == (item->flags.whole & bad_flags.whole) &&
                item->isAssignedToThisStockpile(id)) {
            TRACE(cycle,out).print("assignedToStockpile\n");
            vector<df::item *> contents;
            Items::getContainedItems(item, &contents);
            for (df::item *contained_item : contents) {
                scan_item(out, contained_item, melt_stock_processor);
                scan_item(out, contained_item, dump_stock_processor);
            }
            continue;
        }
        scan_item(out, item, melt_stock_processor);
        scan_item(out, item, dump_stock_processor);
        scan_item(out, item, train_stock_processor);
    }
}
```
note the check for `item->isAssignedToThisStockpile(id)` in the if clause
