### ISSUE TITLE
Figure out why keybindings and text entry are weird in SDL2

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#3433]
most symbols don't work, like underscore or shift-number, until their interface keys are re-bound to the keypress (which changes, for example, `RParen` to `Shift + 0`)

**Comment by lethosor** [comment]
Don't work *in DFHack viewscreens*, or don't work at all?

**Comment by myk002** [comment]
I've heard both, which is very confusing. I also don't know what's going on with the "rebind to same key" being different from the default binding symbol, and what the difference is from DF's perspective.

**Comment by lethosor** [comment]
Oh, have you not been able to reproduce this? Definitely sounds like an SDL2 oddity to me, but I'm not sure why it would be system-specific
