### ISSUE TITLE
Map annotation tiles for SDL2

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#3438]
Our "annotations" that used to just cover the upper left corner of a map tile now cover the entire tile, which is generally a bad thing. `gui/pathable` make the map unreadable with it's full-tile yellow pillbox:

![image](https://github.com/DFHack/dfhack/assets/977482/4b5ee9b6-d106-4086-989e-1bf07abbabd1)

We need a replacement map tile annotation sprite sheet. It would need all the bits and blobs we want to put on the map. Those yellow and black gems would just need to have some extra transparent space around them (but they'd stay in the upper left corner, I think?)

We'd also need markers for suspended/planned buildings. we currently use `x`, `X`, and `P`, which I don't think needs to change, but we could potentially alter the colors of the tile versions to match what we do in ASCII mode. also those letters should probably be centered in the tile

annotation gems of other colors would be nice too, for use in tools like DFHack/scripts#637 where there are many different annotations

**Comment by TaxiService** [comment]
i was messing around, seeing if just replacing our on-off.png with a larger one would do the trick...

...of course it didn't. 🤣 
![image](https://github.com/DFHack/dfhack/assets/5853667/a498579a-a710-4bb0-9ad3-45eeab09c968)

so here are two options:
- a short term solution would be to make some 8x12 sprites that are "meant to be stretched" 🤔 
[here's a webm with an example](https://github.com/DFHack/dfhack/assets/5853667/2408fa91-7f52-4a81-8bb4-26c0e3257ecf)
this really sucks, but is marginally better than covering the entire tile.

- a long term solution would be to rewrite how tiles are rendered to allow for 32x32 sprites, in addition to 8x12.
like, honestly it is kind of wild how suddenly the game is trying to stretch the textures... 🤔 worrying, even.
We need to somehow provide a sprite with the correct dimensions, and have `gui/pathable`/etc use them.
i'm scouring the repo as we speak but i'm not seeing how this could be achieved, yet... °-° maybe by editing something in Screen.cpp?

**Comment by TaxiService** [comment]
ok, that PR now points to the right branch.
In it, i've added this spritesheet exclusively for gui/pathable 
![pathable](https://github.com/DFHack/dfhack/assets/5853667/921bb91c-bd36-4cd1-8145-278c9326019c)

it has been swapped for the on-off spritesheet that it used beforehand. I didn't delete on-off for potential compatibility issues with other tools, but we can remove it later if we dont need it.

now, what i need to know is:
what should the suspend/planned sprites be like?
what do the `x`, `X` and `P` thingies mean exactly, again?
