### ISSUE TITLE
Gui/sandbox unable to spawn creatures with different caste graphics

### ISSUE THREAD

**Issue by GoatsMcnuggie** [DFHack/dfhack#3445]
In the latest sdl2 release of DFhack, gui/sandbox is unable to list/spawn any creatures that load different graphics for their caste (lions, sheep, chickens, sheep, ect). As discussed with lethosor it's an issue with [this check](https://github.com/DFHack/scripts/blob/315c7afc20651ac0fe1700d720f71796190f198e/gui/sandbox.lua#L349), as removing the line fixes the issue.

**Comment by lethosor** [comment]
Specifically it is the check for `cre.graphics` causing the issue.

As for the DFHack version number, you are using `50.08-r2-sdl2-beta1`, correct?

**Comment by GoatsMcnuggie** [comment]
> Specifically it is the check for `cre.graphics` causing the issue.
> 
> As for the DFHack version number, you are using `50.08-r2-sdl2-beta1`, correct?

yes, 50.08-r2-sdl2-beta1

**Comment by myk002** [comment]
amusingly, fixing this allows agitated wagons to be spawned. I'll just filter those out specifically : P
