### ISSUE TITLE
[Quickfort] Traffic restriction don't get applied over buildings

### ISSUE THREAD

**Issue by fricy** [DFHack/dfhack#3446]
[Test file](https://docs.google.com/spreadsheets/d/14u3HUxhu5kYXE1DEwetLWRj6HQ4Gm-vN/edit#gid=734273320)

I tried adding some traffic restrictions to my blueprints, and they get applied correctly over built/carved tracks, but get ignored if there's a building on the tile. Tested with trackstops, gears, rollers, axles.

**Comment by myk002** [comment]
I noticed this too while testing dreamfort. I'm probably doing an indeed occupancy check before altering the tile. Occupancy checks are needed for dig actions, but not for traffic designations. I'll have to check whether dump/forbid designations are improperly inhibited too.
