### ISSUE TITLE
Extend text area for title-version

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#3448]
So the long SDL2 version strings aren't truncated

**Comment by myk002** [comment]
This just means changing the width variable for the overlay widget. This can be done dynamically or statically. Just adding 15 to the `w` frame attribute will probably cover us just fine, though.

**Comment by lethosor** [comment]
I would vote for dynamic so we don't end up with a widget that's significantly wider than we need (not sure if that would happen)

**Comment by myk002** [comment]
The impact of a too-wide widget is pretty minimal. There is no border, so the unused space is simply transparent. The only negative effect is that if you want to reposition the widget, it won't be able to get as close to the right side of the screen as you might otherwise be able to make it.

That said, dynamic width is not hard. We're talking just a few lines of code here.

**Comment by myk002** [comment]
done in #3456
