### ISSUE TITLE
bring back Labor Restrictions to .50

### ISSUE THREAD

**Issue by TaxiService** [DFHack/dfhack#3449]
in .47, when viewing a workshop's profile, you could block specific job types from being queued in the selected workshop.
![Dwarf_Fortress_L0yrt3NW0I](https://github.com/DFHack/dfhack/assets/5853667/546ddf7e-053a-44ed-ac5f-35511d1cc595)

Not all workshops had this list. Some workshops (such as the _Mason's Workshop_ or the _Glass Furnace_) had this option greyed out because they could only let you queue _one_ type of job. (i guess MASON and GLASSMAKER jobs respectively)

Any workshop that had more than one possible type of job had the Labor Restrictions tab enabled, and you could individually turn the job types on or off.

The underlying structures to define these things seems to still be present in .50, but there is no UI for interacting with them. :/

The idea is to have an overlay that appears when selecting an appropriate workshop, that lets you toggle each labor just like in .47
[(here's a rough mockup)](https://github.com/DFHack/dfhack/assets/5853667/3ef4d707-fa66-4853-b381-ecbb5455294b)

i have been trying to code this thing myself, but... let's say it's not really good for my psyche. [it looked promising](https://github.com/DFHack/dfhack/assets/5853667/0ae8def8-95ed-49e6-bae4-73da3c1452e8), but i dont have the mental prowess to go on any longer.

if anyone wants to take on this project, have these lists. 
they maps a building's `.type` field with the relevant labors from its `.profile.blocked_labors` table that the overlay should display.
```lua
local workshop_labors = {
    [0]={'CARPENTER', 'TRAPPING'}, --Carpenters
    [1]={'PROCESS_PLANT', 'MAKE_CHEESE', 'MILK',
         'SHEARER', 'SPINNER', 'PAPERMAKING'}, --Farmers
    [2]={'STONECUTTER', 'STONE_CARVER',},--Masons
    [3]={'LEATHER', 'CLOTHESMAKER', 'METAL_CRAFT', 'WOOD_CRAFT',
         'STONE_CRAFT', 'BONE_CARVE', 'EXTRACT_STRAND',
         'POTTERY','WAX_WORKING', 'BOOKBINDING'}, --Craftsdwarfs
    [4]={'CUT_GEM', 'ENCRUST_GEM'}, --Jewelers
    [5]={'TRAPPER', 'FORGE_WEAPON', 'FORGE_ARMOR',
         'FORGE_FURNITURE', 'METAL_CRAFT'}, --MetalsmithsForge
    [6]={'TRAPPER', 'FORGE_WEAPON', 'FORGE_ARMOR',
         'FORGE_FURNITURE', 'METAL_CRAFT'}, --MagmaForge
    [10]={'BUTCHER', 'DISSECT_VERMIN'}, --Butchers
    [14]={'FISH', 'CLEAN_FISH', 'DISSECT_FISH'}, --Fishery
    [15]={'BREWER', 'HERBALIST'}, --Still
    [17]={'MILLER', 'PAPERMAKING'}, --Quern
    [20]={'POTASH_MAKING', 'LYE_MAKING'}, --Ashery
    [22]={'MILLER', 'PAPERMAKING'}, --Millstone
    [23]={'PRESSING', 'PAPERMAKING'}, --Custom (ScrewPress)
}

local furnace_labors = {
    [3]={'SMELT', 'POTTERY', 'GLAZING'}, --Kiln
    [6]={'SMELT', 'POTTERY', 'GLAZING'}, --MagmaKiln
}
``` 
NOTE: building `type` 23 could be both a Soapmakers or a Screwpress!!! 🤦 
The difference is in another field called `custom_type`, which is `0` for Soapmakers and `1` for Screwpress. (It's `-1` for any other building...)

In the list i've just mapped it to the ScrewPress' labors, because Soapmaker does not need the overlay to appear. :/
This is the function i had in place to determine if the overlay should appear... and it _did_ work, but idk how elegant it is.
```lua
function LaborRestrictions:is_valid_building()
    building = dfhack.gui.getSelectedBuilding()
    is_workshop = df.building_workshopst:is_instance(building)
    is_furnace = df.building_furnacest:is_instance(building)
    if is_workshop and workshop_labors[building.type] then
        if building.custom_type == -1 or -- this is true for all shops but "Custom" (23)
            building.custom_type == 1 then -- 0 is soapmakers; 1 is screwpress
            return true
        else return false end
    elseif is_furnace and furnace_labors[building.type] then
        return true
    else 
        return false 
    end
end
```

**Comment by TaxiService** [comment]
and here is my worthless code if you want
https://gist.github.com/TaxiService/10db1f1bca17c2e9ac1b95023a6142a3
at least there's a draft of an overlay-spawning code

**Comment by myk002** [comment]
I've actually been playing with exposing this functionality with `quickfort` too, so having a UI is very timely.

The code is not worthless, btw. It just needs to be a little less stateful -- as you look like you've discovered, dynamically adding the appropriate list of labors is hard. It's better to have pre-prepared widgets for each option and just choose which one is visible based on the selected workshop type.

**Comment by myk002** [comment]
I tested labor restrictions in v50, and they do still seem to work just fine.

**Comment by myk002** [comment]
I'm going through and productionizing your prototype. Thank you for the start on this!
