### ISSUE TITLE
gui/sandbox not working

### ISSUE THREAD

**Issue by Mojo-Jojo12** [DFHack/dfhack#3462]
https://mega.nz/folder/uVlRnRaI#R-tCpcMBTC3layiQKPeV-w

**Comment by myk002** [comment]
error screenshot from discord:
![image](https://github.com/DFHack/dfhack/assets/977482/69c57996-82a1-40cc-90a2-d6c5c9ce31f2)

**Comment by myk002** [comment]
I've been trying to download for 2 days now, and it seems to be stuck on 71%:

![Image](https://github.com/DFHack/dfhack/assets/977482/73b73555-1d78-461f-9705-f0b127e9f0b7)

Could you maybe upload to Google Drive?

**Comment by myk002** [comment]
that worked. thanks!

**Comment by Mojo-Jojo12** [comment]
Must've forgotten that one, sorry. Should be in the google drive now

**Comment by myk002** [comment]
I gets past the mod loading part now, but I get this error half way through:
![image](https://github.com/DFHack/dfhack/assets/977482/c953a995-2842-4532-b0aa-623f162d6972)

At this point, I'm starting to think it's a misconfigured mod that is causing this issue.

**Comment by Mojo-Jojo12** [comment]
Yeah, I tried disabling all the mods and making a new world and gui/sandbox seems to work. No idea what that error is though

**Comment by myk002** [comment]
I suspect there are just some malformed raws in one of those mods. I'll close this for now, but if it comes up again, feel free to reopen
