### ISSUE TITLE
`buildingplan` - Add "total in line" to planner infobox

### ISSUE THREAD

**Issue by DragonEyeNinja** [DFHack/dfhack#3469]
I think a number like this would help players who are planning things ahead (and need a lot of pending furniture or other constructions) to see precisely how many of a certain item/furniture they need. For instance, I just expanded by nestbox area, and would like to know how many more nestboxes I'll need to have; in order to do this, I would have to click on the last placed nestbox and see its position in line.

Doing this would be a nice little QoL to help make `buildingplan` that much more useful.
![mockup](https://github.com/DFHack/dfhack/assets/100793820/181c9ff8-31bd-4f76-8233-d01d3b28fcd4)

**Comment by myk002** [comment]
good idea, and perfectly doable. The text would probably have to go on the same line as `Will link later` since otherwise there wouldn't be room on the panel for buildings with more component items (e.g. wells).

**Comment by myk002** [comment]
note also that you can get a summary of pending buildings and their required materials by running `buildingplan` without parameters
