### ISSUE TITLE
gui/design overrides default camera navigation key

### ISSUE THREAD

**Issue by fartron** [DFHack/dfhack#3470]
the c key is used to move the camera down one z-layer but the design ui uses it to toggle 'Auto-Commit', making it impossible to navigate the camera down without a mouse wheel while using the tool

**Comment by ab9rf** [comment]
this one is a blocker for me

**Comment by johncosker** [comment]
Sorry about that, I've been on a bit of a break from development due to life stuff, should be an easy change though @myk002 I see you moved it to 'Being worked on' does that mean you or someone else is working on it?

**Comment by myk002** [comment]
Yeah, I can take this if you don't have the time for it right now
