### ISSUE TITLE
SDL2 Experimental version keyboard input bug in GUI terminal of DFhack

### ISSUE THREAD

**Issue by Jakob-Tvalfager** [DFHack/dfhack#3471]
I found a input bug in the sdl2 experimental version of DFhack. The bug appears when using the DFhack GUI terminal. 

When you use a swedish keyboard the / among all shift+number key keys and § (tilde) keys dont work. 

However, ctrl+alt+D key opens the DFhack gui terminal without much issue.

When I swap to ENG keyboard language the ` (tilde) key works but the shift+number keys dont. 

It does not seem to be a dwarf fortress native bug since the keypresses work in Dwarf fortress stockpile search and such 

Currently I am using the "show" command to open the console application window. This window seems to work fine with all kinds of text input as long as I use Windows 11's windows-terminal. 

See this page for a guide on setting windows-terminal as default on W11:
https://devblogs.microsoft.com/commandline/windows-terminal-as-your-default-command-line-experience/

I'm unsure how to do it on W10 but someone somewhere probably have a guide for it

**Comment by myk002** [comment]
I've got a PR that *should* fix this, but I haven't been able to test in other keyboard layouts or languages. Could you possibly try installing the DFHack package from this link and telling me if it solves the issue?
https://github.com/DFHack/dfhack/actions/runs/5281909743?pr=3474#artifacts
