### ISSUE TITLE
autoDFAnnouncement opens the embark message for all types

### ISSUE THREAD

**Issue by Bltgn** [DFHack/dfhack#3476]
Hi, the dfhack.gui.autoDFAnnouncement method seems to treat all types as embark announcement (the Strike the Earth! message).

I tried to simulate a job cancellation using this function:

```
function CancelReaction(reaction, unit, input_reagents, reason)
    local message = string.format(
        "%s, %s cancels %s: %s.",
        dfhack.TranslateName(dfhack.units.getVisibleName(unit)),
        dfhack.units.getProfessionName(unit),
        reaction.name,
        reason 
    )

    dfhack.gui.autoDFAnnouncement(df.announcement_type.cancel_job, unit.pos, message, COLOR_YELLOW)

    for _, v in ipairs(input_reagents or {}) do
        v.flags.PRESERVE_REAGENT = true
    end
end
```

I tried with other types, such as stuck_minerals or combat messages. It does write an entry in gamelog.txt, however.

Thanks

**Comment by Bumber64** [comment]
I think we should ask Bay12 to export this function. It's `FUN_1400574e0` in Windows Steam v50.11.

**Comment by ab9rf** [comment]
that function is `void make_announcement(const string &str,announcement_infost &info)`

**Comment by Bumber64** [comment]
Did some testing. As I suspected, it's opening the last popup, not specifically the embark one.

You can clear out the old one first using
```
do
    local mtb = df.global.world.status.mega_text
    mtb.word:resize(0)
    mtb.link:resize(0)
    mtb.current_width = -1
    mtb.max_y = 0
    mtb.environment = NULL
end
```
but this just causes an empty popup to be displayed. I need to locate the actual check being done to display it.
