### ISSUE TITLE
Not able to end the Lua terminal session

### ISSUE THREAD

**Issue by ab9rf** [DFHack/dfhack#3485]
_this has been copied from [Steam discussions](https://steamcommunity.com/app/2346660/discussions/0/5782107002614441685/)_

I used the lua command to open an interactive lua terminal session and now its not possible to close it or open other interactive tools within the terminal. Using an external OS terminal doesn't work either.

Here is the stacktrace I have after running

>  kill-lua force 

from the dfhack gui/launcher
```
 [...rary/steamapps/common/Dwarf](https://steamcommunity.com/linkfilter/?url=http://...rary/steamapps/common/Dwarf) Fortress\hack\lua\dfhack.lua:873: interrupted!
stack traceback:
        [C]: in field 'runCommand'
        [...rary/steamapps/common/Dwarf](https://steamcommunity.com/linkfilter/?url=http://...rary/steamapps/common/Dwarf) Fortress\hack\lua\dfhack.lua:873: in upvalue '_run_command'
        [...rary/steamapps/common/Dwarf](https://steamcommunity.com/linkfilter/?url=http://...rary/steamapps/common/Dwarf) Fortress\hack\lua\dfhack.lua:877: in function 'dfhack.run_command_silent'
        [C]: in field 'hideGuard'
        [...apps/common/Dwarf](https://steamcommunity.com/linkfilter/?url=http://...apps/common/Dwarf) Fortress/hack/scripts/gui/launcher.lua:763: in function [<...apps/common/Dwarf](https://steamcommunity.com/linkfilter/?url=http://%3C...apps/common/Dwarf) Fortress/hack/scripts/gui/launcher.lua:748>
        [C]: in field 'on_submit'
        ...steamapps\common\Dwarf Fortress\hack\lua\gui\widgets.lua:722: in method 'onInput'
        ...Library\steamapps\common\Dwarf Fortress\hack\lua\gui.lua:584: in function <...Library\steamapps\common\Dwarf Fortress\hack\lua\gui.lua:578>
        (...tail calls...)
        ...Library\steamapps\common\Dwarf Fortress\hack\lua\gui.lua:801: in function <...Library\steamapps\common\Dwarf Fortress\hack\lua\gui.lua:787>
        [C]: in ? 
```

Message I get when trying to run another interactive command like
> tiletypes 
while the lua terminal is still active:

 Output from command run from gui/launcher:
```
> tiletypes

tiletypes needs an interactive console to work.
Please run this command from the DFHack terminal. 
```

Is this a known issue? I'm on the latest testing build: 50.08-r4rc1. Any help would be appreciated.

**Comment by myk002** [comment]
This *sounds* like a PEBKAC (trying to run interactive commands from the non-interactive gui/launcher) , but I'm following up on the Steam discussion thread to try to get more info.

**Comment by myk002** [comment]
reporter cannot reproduce. may have been caused by an unclosed open quote, causing the input to be read as a string instead of a command.

**Comment by lethosor** [comment]
Repeating what I mentioned in the [Steam thread](https://steamcommunity.com/app/2346660/discussions/0/5782107002614441685/) just for continuity here:

> "quit" is actually handled before any parsing is delegated to Lua, so it will always work even if you're in the middle of a string literal. (This might've been deliberate, but is quite old.) https://github.com/DFHack/dfhack/blob/d77ea845dd2ed38880da54b20c15057e7916a171/library/lua/dfhack.lua#L620

+1 for the documentation improvements.
