### ISSUE TITLE
dig-now not able to dig created obsidian

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#3486]
dig designations disappear as if they are being fulfilled, but the wall is left as-is

works for layer obsidian, but not for created obsidian

reported on [discord](https://discord.com/channels/793331351645323264/793331351645323267/1120716649247559790)

**Comment by ab9rf** [comment]
layer obsidian is layerstone, but created obsidian is a different tile type (usually `LavaWall` but it can be other types if it's been smoothed, damaged, or engraved) so that's possibly what's going on here
