### ISSUE TITLE
gui/sandbox: Spawned civ members interact oddly with military leadership positions

### ISSUE THREAD

**Issue by jppessoap** [DFHack/dfhack#3490]
I have faced this issue in two different test forts in slightly different circumstances. The short version of the story is that sandbox-spawned citizens seem to become a permanent part of a squad if set to be a commander/captain, until picked as a normal soldier in another squad. There is a level to this I have no fully uncovered: there are "captain" civillians who didn't seem to interfere with my thought processes detailed below.

The game's UI fails to properly display who currently has the role, but they all obey the same station command and share equipment amongst themselves. This effectively allows for squads with more than 10 units, although only up to 10 will be armed. I did not test what happens if they go on raids.

The issue can be fixed by manually searching for the troublesome dwarves and add them into ANOTHER squad until only one captain remains. Moving any of the captains will make the game claim the spot is vacant, however, and the right dwarf must be picked to fill this vacancy.

This issue did not happen with one of the original 7 dwarves of the fort nor with human petitioners who are now citizens. They do not keep the captain title nor become ghost squad members.

**Comment by xoxomonstergirl** [comment]
Hi! I was told on the subreddit to add this here, though I'm not 100% sure it's the same issue. I've been running a modded kobold fortress which has gone great, but now I'm trying to retire it so I can play in adventure when that comes out and make a smaller fort in the same world in the meantime.

Big issue, I think, is I've been adding invaders and other nasties as fort members for extra flavor using makeown and similar techniques, which took some tweaking to get them in the military and interacting. It wasn't perfect, but I can't export now without a crash at all. I was told by myk002 to add my save here in case that helps! I would love help fixing it!

https://www.dropbox.com/scl/fi/vkujvdxnts27a57rueng8/DF-Kobold-Fortress-Save.zip?rlkey=b3scn0u69i6d3asn2ybuz1d52&dl=0

**Comment by myk002** [comment]
Thanks! Yeah, `gui/sandbox` uses `makeown` to create citizens, which is why I think these issues are linked. Could you also attach a zip of your mods directory? We'll need exactly the mods you have installed in order to load your save.

**Comment by xoxomonstergirl** [comment]
I think it should be in there!

**Comment by myk002** [comment]
Excellent - thank you!
