### ISSUE TITLE
[suspendmanager] Ramp are considered an option to build from, but they are not

### ISSUE THREAD

**Issue by plule** [DFHack/dfhack#3492]
From Weyland on discord:

![image](https://github.com/DFHack/dfhack/assets/630159/5b611ae2-a0b2-483b-9f17-614b26d178da)

In this situation, suspendmanager did not consider the walls near the ramps to be at risk, because a ramp shape is "walkable": https://github.com/DFHack/df-structures/blob/916a497000651b64272dacda3a5005650d3c0c68/df.tile-types.xml#L93

However, dwarves actually can't use ramps to construct from.

**Comment by plule** [comment]
As mention on the discord, it looks like the source issue is that RAMP_TOP is marked as walkable but should not.

Looking at the other usages, I think it is a safe change:

**burrows**
On a new digged tile, it checks if the new or old tiles are walkable to extend a burrow. A new digged tile cannot be a RAMP_TOP as far as I know, no impact.

**build-now, dig-now, deep-embark, autodump, create-unit**
All have a variation on `if (isWalkable(tt) && basic_shape != df::tiletype_shape_basic::Open)` and the basic shape of RAMP_TOP is `df::tiletype_shape_basic::Open`, so no impact. In deep-embark, the comment `downward ramps are walkable but open; units placed here would fall` even suggests that the additional check is a workaround for this issue.

The other "walkable" instances are all on block.walkable[][], or hardcoded lists.

@ab9rf Can you go ahead and make RAMP_TOP not walkable please?

**Comment by myk002** [comment]
After the attribute change, we should also clean up the usage in the scripts. We no longer have to special case ramp tops

**Comment by plule** [comment]
> After the attribute change, we should also clean up the usage in the scripts. We no longer have to special case ramp tops

I just noticed that ENDLESS_PIT is on the same situation than RAMP_TOP (walkable but the basic shape is open), so there is a possible impact here. I don't even know what ENDLESS_PIT is though, I've never reached HFS :x

**Comment by ab9rf** [comment]
it's theoretically possible to walk onto an `ENDLESS_PIT` but it will be the last thing that unit does (unless it can fly)

**Comment by myk002** [comment]
Since we're redefining walkable to mean standable, endless pit should probably get walkable=false as well

**Comment by plule** [comment]
Fixed by https://github.com/DFHack/df-structures/pull/612
