### ISSUE TITLE
Add some form of gui/Artifact List 

### ISSUE THREAD

**Issue by Draxxalon** [DFHack/dfhack#3506]
Right now the artifact list (on the world map) lets you browse the known artifacts, and create missions to go get the artifact.

Something a bit more "stockpile like" would make this a lot more usable, and possible to do this sort of 'artifact shopping'.   Filter by type, material, etc.

If this is the knowledge of what artifacts are out there, according to dwarven history, I'd expect to be able to ask the historians "Bring me a list of the artifact steel battle axes out there" - and I would expect that they'd give me a list of said axes (possibly days later, because books n such)

**Comment by myk002** [comment]
implemented in https://github.com/DFHack/dfhack/pull/3865
