### ISSUE TITLE
Duplicate units in menus referring to same creature;  possibly caused by retrieve units command?

### ISSUE THREAD

**Issue by txcrnr** [DFHack/dfhack#3512]
Link to Google drive of save file:  
https://drive.google.com/file/d/1vxbyRwRIYEpTczgI0BFSXnI4KjniyV3e/view?usp=drivesdk
  
mods used:  https://steamcommunity.com/sharedfiles/filedetails/?id=2898378637
  
 Certain squad members show up twice in all lists (regardless of being in squads or not).  Attempting to raid will crash the game during the mission, and occasionally crashes otherwise.  When sending units to another site, they become unable to be requested back as workers, but the crashing ceases.

**Comment by myk002** [comment]
Thanks! This is something I think we can check for and fix with an automated `fix` script.
