### ISSUE TITLE
[buildingplan] Sometimes picks the material from the previous building

### ISSUE THREAD

**Issue by plule** [DFHack/dfhack#3539]
It's not happening each time and I don't understand the exact sequence at the moment, but sometimes buildingplan tries to link the material from the previous building.

Here, trying to build a screwpress with cabinets:

![image](https://github.com/DFHack/dfhack/assets/630159/785f4993-b1c7-40c5-96cf-df6dfe7b05da)

and here a wall grate with a place offering:

![image](https://github.com/DFHack/dfhack/assets/630159/f0d56b2e-3443-4aa5-ba5b-0f7bd04ddf01)

**Comment by myk002** [comment]
So before you tried to build the wall grate, you built an altar? Is the problem persistent? If you try to build a wall grate again, what does it show? If you actually place the wall grate, what does it use to build the building?

**Comment by plule** [comment]
> So before you tried to build the wall grate, you built an altar?
Yes

> Is the problem persistent?
AH I'm managing to reproduce it reliably finally:

1. Designate a cabinet without building plan
2. Start placing the wall grate - it displays "cabinet"

> If you try to build a wall grate again, what does it show?
It switches back to the wall grate

> If you actually place the wall grate, what does it use to build the building?
It designates correctly with a wall grate
