### ISSUE TITLE
Suspension overlay: Distinguish between items suspended by suspendmanager from the others

### ISSUE THREAD

**Issue by plule** [DFHack/dfhack#3554]
At the moment there are 3 possibles icons for a suspended building job:
- Yellow cross: suspended by the game
- Red cross: repeatedly suspended by the game, even after unsuspension
- Clock: Not yet ready to be built, planned by buildingplan

There was discussion about adding a fourth that would mean suspended by suspendmanager, which would help read a building situation.

A suggestion was to use the blue pencil for buildingplan, and the clock for suspendmanager. However the blue pencil is not very visible at different zoom level. Maybe a white cross, since just like yellow and red it is still a suspension? I'll try variations and gather feedback

**Comment by myk002** [comment]
Right now, though, there is no such thing as a suspended building that is not suspended by suspendmanager, is there? At least not for long. If a player manually suspends a building, or if a job becomes suspended due to wildlife scaring the builder away, won't suspendmanager just unsuspend it if it can?

**Comment by plule** [comment]
What I have in mind is to have kind of a highlight to the player for these temporary hiccups, to have a graduated "call to attention". If we go for the white/yellow/red color code, this means that:
- white: most of the time it's this color, can be ignored just like the buildingplan clock
- yellow: something happened, moderate call to attention
- red: high call to attention, this likely needs an intervention

and without suspendmanager, yellow everywhere, which is ok to me.

Another benefit is for debugging based on screenshots
