### ISSUE TITLE
test for whether to suppress duplicate keyboard events causes an assertion failure

### ISSUE THREAD

**Issue by ab9rf** [DFHack/dfhack#3559]
The test for whether the "suppress duplicate keyboard events" option is enabled causes an assertion failure when SDL event processing attempts to interrogate the Lua environment for whether this flag is set:
![image](https://github.com/DFHack/dfhack/assets/1445859/33a80dcf-a2c0-4465-b9ff-2908bce40cb9)

```
>    dfhooks.dll!AssertCoreSuspend(lua_State * state) Line 86    C++
     dfhooks.dll!DFHack::Lua::PushModule(DFHack::color_ostream & out, lua_State * state, const char * module) Line 1027    C++
     dfhooks.dll!DFHack::Lua::PushModulePublic(DFHack::color_ostream & out, lua_State * state, const char * module, const char * name) Line 1047    C++
     dfhooks.dll!getSuppressDuplicateKeyboardEvents() Line 2363    C++
     dfhooks.dll!DFHack::Core::DFH_SDL_Event(SDL_Event * ev) Line 2401    C++
     dfhooks.dll!dfhooks_sdl_event(SDL_Event * event) Line 55    C++
     Dwarf Fortress.exe!00007ff734275715()    Unknown
     Dwarf Fortress.exe!00007ff734275efe()    Unknown
     Dwarf Fortress.exe!00007ff73427679b()    Unknown
     Dwarf Fortress.exe!00007ff734d435b2()    Unknown
     Dwarf Fortress.exe!00007ff734d42c7a()    Unknown
     kernel32.dll!BaseThreadInitThunk()    Unknown
     ntdll.dll!RtlUserThreadStart()    Unknown
```

The problem here is that we can't safely call Lua from the context of processing a SDL event, nor can we safely core-suspend in such a context. There is no thread-safe way (that I can see, at least) to interrogate Lua state while processing a SDL event.

The obvious solution is to store this option in the core C++ state, where the SDL event processing code can access it in a thread-safe way, and have the Lua code to manipulate it access the C++ state instead of storing it in Lua state.

**Comment by ab9rf** [comment]
i did a test build locally and can confirm that the assertion failure that was happening before no longer arises in the circumstances where it was previously arising

**Comment by myk002** [comment]
Excellent. Thank you.
