### ISSUE TITLE
Requesting an option to "collapse all" in the Fortress stocks window

### ISSUE THREAD

**Issue by IvoryTower33** [DFHack/dfhack#3561]
Requesting an option to "collapse all" in the Fortress stocks window, which  could be very helpful at least  for the time being, it'd make it  a lot more manageable I think, offering a quick overview of types of bar, stones, etc, instead of having to collapse 10 labels manually just to see what beneath.

**Comment by myk002** [comment]
this would be very similar to the trade screen overlay and should be just as easy to implement.
