### ISSUE TITLE
50.09 squad equipment duplicate assigning

### ISSUE THREAD

**Issue by donhth** [DFHack/dfhack#3568]
In my current game, I have multiple members in multiple squads being assigned the same equipment. 

For example, Urist McFly wants some shield that Urist McDoofy also wants. It was easy for me to spot when I noticed two dwarves being assigned the same named shield. Unsure if each squad is affected individually, or if it's crossing squad boundaries.

I believe I did use these squads for raiding. I'm aware of past/present issues regarding raids. Fortunately, my game has not been crashing (17 year old fortress).

My question is, would it be easy for dfhack to fix equipment assignment issues? I was hoping the 'update equipment' button would help, but it doesn't seem to. 

I have not tried disbanding/recreating the squads yet, as that would be a pita to do if this is going to keep happening. I suppose one could create a squad specifically for raiding as a workaround assuming the glitchy equipment behavior is confined to the raiding squad (I was hitting a vault, so I was sending everything I had).

**Comment by don-hwy** [comment]
That is useful to know. I'll just send em out naked then. 

So I will fiddle with my squads and hopefully resolve it. I was able to fix the named shield one by specifying a shield with a different material for one of the impacted units.  Simply removing the shield as an attempt to reset it didn't seem to work.  

In any case, thanks for the tip!

**Comment by don-hwy** [comment]
Equipping is definitely glitchy for me. I'm not convinced it's due to raids. 

I took them all out of their respective squads, let them change into their civ clothing and then re-added them. Some of their gear has been named. Urist Mcfly has a crappy named sword that was forbidden and previously placed inside an artifact stockpile -- during the time he was in civ clothing. The game is still assigning Mcfly this sword even though it is forbidden.

It's been quite a few years since I've looked at dfhack, looks like a lot of has improved. I may attempt a script to assign gear if it isn't too messy to do.

**Comment by don-hwy** [comment]
Or actually, just a periodic dup assignment checker and fixer.

The dupe assignments were happening across squad boundaries. Seems like there could be some aggressive caching going on where it is bypassing some checks.

**Comment by master-spike** [comment]
I have encountered this issue - it seems to only apply to named objects. When squad equipment is assigned, the assignments follow a priority system according to item quality and seniority of the military dwarf. However, sometimes dwarves will hold on to their "attached" named item even if that item gets assigned to someone else, leading to duplicate assignments.

**Comment by donhth** [comment]
It happens with unnamed gear too, it's just easier to spot when they're named -- unless they fixed it recently.

Workaround is to assign metal/gear that other squads don't use. So if you've got iron and copper, you can use copper for raiders and either copper weapons or weapon types reserved for the raiders so as to not infect the other squads.

**Comment by myk002** [comment]
fixed by https://github.com/DFHack/scripts/pull/912
