### ISSUE TITLE
Feature request: Show damp/warm stone while setting mining designations in classic ascii mode.

### ISSUE THREAD

**Issue by zeddy1267** [DFHack/dfhack#3585]
There is currently no visual way to see damp/warm stone while using ascii glyphs, which makes the game borderline unplayable if you're working around either of those. The only thing you can do is toggle the graphics on, which is not an option if using the free version of the game. 

damp/warm should flash exactly how they did in DF versions prior to v50, and only while making mining designations.

**Comment by myk002** [comment]
is flashing required? here's an implementation with just a constant red/blue highlight (note how the highlight shows through the vanilla UI elements; I'm not sure what can be done about that):

![warmdamp](https://github.com/DFHack/dfhack/assets/977482/448bd847-83e4-41d5-b46d-7a0926e52bc2)
![damp](https://github.com/DFHack/dfhack/assets/977482/760a252a-16c5-48d7-8b8d-26fb10f9b2b2)
