### ISSUE TITLE
Stockpile item designation tool hides game's options

### ISSUE THREAD

**Issue by TymurGubayev** [DFHack/dfhack#3588]
See screenshot:

![image](https://github.com/DFHack/dfhack/assets/348150/0d3c8bf4-478d-465e-815d-1b84f9df2878)

I think it needs to be moved down 1 tile.

**Comment by myk002** [comment]
the current position is the best I could come up with. if it is moved down one tile, it covers the "add stockpile" button that appears above the bottom bar.

for situations like this where the overlay covers vanilla UI elements, we provided the minimize button (the up arrow near the upper right corner of the overlay panel)

**Comment by don-hwy** [comment]
This has annoyed me a bit at times. Maybe a hotkey to quickly toggle minimize would help mitigate.  Could also situate the mini button more on the top right corner and make it a bit bigger, but there's so much mouse clicky as it is. Or start out minimized -- it depends how often the overlay is used. If it's just extra options that are used infrequently, starting off minimized would make more sense. 

Obviously, not a major  issue.

**Comment by TymurGubayev** [comment]
> the current position is the best I could come up with. if it is moved down one tile, it covers the "add stockpile" button that appears above the bottom bar (exit out of this stockpile custom configuration screen to see it).
> 
> for situations like this where the overlay covers vanilla UI elements, we provided the minimize button (the up arrow near the upper right corner of the overlay panel)

looks like this to me, no overlap
![image](https://github.com/DFHack/dfhack/assets/348150/1231c920-ae26-4995-8f75-a0878341b8b8)

maybe move it 1 down and to the very left?

**Comment by myk002** [comment]
@don-hwy the Hotkey is `Alt-m`

@TymurGubayev it depends on your screen size. For narrower screens, it overlaps. However, know that you can always reposition individual overlay panels with `gui/overlay` to make them work better for you.

**Comment by myk002** [comment]
If you can find a better default position, though, I'll definitely consider it. The requirements are that it has to work reasonably on both large and small screen sizes (down to the minimum DF will support). We can change the position of the minimize button. You can see it's now strategically positioned in the space between the vanilla stockpile config buttons.

**Comment by TymurGubayev** [comment]
How about above, hiding (less useful) vanilla info:

![image](https://github.com/DFHack/dfhack/assets/348150/99c5f1d0-e4a4-4c3d-8333-1db7090c559e)
![image](https://github.com/DFHack/dfhack/assets/348150/80d896fa-be28-47b7-a88f-3f84ed0731e4)

**Comment by myk002** [comment]
I'm going to close this for now since I *think* things are working as-is. The Alt-m hotkey will quickly minimize the panel, and the minimized state is persisted until you reload the game. please re-open if you feel that this is insufficient.
