### ISSUE TITLE
Hang when removing a stockpile

### ISSUE THREAD

**Issue by don-hwy** [DFHack/dfhack#3590]
Getting a hang on a clothing stockpile when I either a) attempt to remove it or b) click 'use this stockpile for trading' to toggle it off (I am on a mac so the hot key isn't working for me). 

Where do you get the dfhack version data? I believe it is rc1 for steam 50.09 df.

**Comment by don-hwy** [comment]
I tried kill-lua in dfhack's command prompt, that did nothing. typing 'ls' on there causes a freeze; however not all commands freeze. If you point me to the right direction, and if it is a lua script, I can see about troubleshooting this myself.

**Comment by don-hwy** [comment]
Workaround: I ran command 'disable logistics' 
I can now remove the stockpile without the hang. Toggling trading off still hangs with logistics disabled.

Seems like I'd want to begin by looking at do_undo in internal/quickfort/place.lua
Looks a little hairy in there... :)

**Comment by don-hwy** [comment]
Scratch that -- still freezes, just not immediately.  I'm going to assume it is dfhack since it hangs immediately when I toggle autotrade for the stockpile.

**Comment by lethosor** [comment]
> Where do you get the dfhack version data? I believe it is rc1 for steam 50.09 df.

Running `help` is one way. It should also show up in a corner of the DF title screen by default. We actually did not have a "rc1" for 50.09 - maybe you're using 50.09-r1?

> I tried kill-lua in dfhack's command prompt, that did nothing. typing 'ls' on there causes a freeze; however not all commands freeze.

kill-lua will only interrupt code written in Lua, which is not everything. A hang in C++ code (either DF or DFHack) is not possible to recover from.

> Seems like I'd want to begin by looking at do_undo in internal/quickfort/place.lua

I'm curious what makes you believe this has something to do with quickfort. Are you seeing any error messages related to it?



> Scratch that -- still freezes, just not immediately. I'm going to assume it is dfhack since it hangs immediately when I toggle autotrade for the stockpile.

Could you upload a save and provide steps to reproduce?

**Comment by don-hwy** [comment]
Yeah it's r1.

I grepped for references to autotrade and saw trading/stockpile handling in there. I've also seen some scripts make use of quickfort code.  I am not familiar with dfhack's code and was hard pressed to locate the bits handling the trading. Tried checking that since there's an immediate hang when attempting to toggle it on the stockpile overlay.

Sure, I'll upload a save file to google drive. Super easy to reproduce ( for me ).

**Comment by don-hwy** [comment]
Ok I'm assuming myk002 found it.

https://drive.google.com/file/d/1smVmfYbZn-Pl-HmQpdLJgby_Qhfkfy_d/view?usp=sharing

Z-level 37. Just under the clothier's shop. Simply attempt to delete the stockpile or toggle  trading in overlay. 

While there, if you actually need to load the save and you have a minute, there is a citizen I can't assign labors to (I've been using dwarf therapist). Don't remember if I can in DF. Pretty sure he is doing labors. It's no big deal. He's a legendary metal smith with first name Rimtar.

**Comment by myk002** [comment]
I have not found the issue yet, just marking this issue as my current task. Thank you for the savegame! I'll take a look in a few hours.

**Comment by myk002** [comment]
Thanks for the upload -- I downloaded, but you should probably remove the upload ASAP since you uploaded the entire game, not just the savegame in the `save` directory. I'll remove the link from the post.

**Comment by myk002** [comment]
Hrm, I can't seem to reproduce the issue so easily:
![logistics_no_crash](https://github.com/DFHack/dfhack/assets/977482/84294d54-8a28-4bd4-b931-e7d0ab337cd3)

Am I doing it right?

**Comment by don-hwy** [comment]
Yep. Very odd it isn't happening for you. Simply clicking on the Trading will freeze it. Just tried it again.

Yeah, my bad. Thought it'd be easier that way to make sure you had everything. Thanks.

**Comment by don-hwy** [comment]
You're welcome to teamview in if you want to arrange that.

**Comment by don-hwy** [comment]
I disabled dfhack by renaming the hack folder. I then deleted the stockpile in game. I saved it with the stockpile deleted. Re-enabled dfhack, reloaded game and it crashes. Something dfhack is doing with that stockpile. 

Maybe something not playing nicely with wine and rosetta, if you can't reproduce.

**Comment by myk002** [comment]
reupload of savegame: https://drive.google.com/file/d/1p_xJmv45bZDTrj1HEl90R0LbHmCQr1pd/view?usp=sharing

**Comment by don-hwy** [comment]
In Wine debug log, I'm seeing the below repeatedly when the game is unresponsive, I don't know if it's related to an actual problem. I posted a backtrace as well for when the game hangs. Of course, no symbols. Probably not helpful. But it is something.

06cc:fixme:msg:pack_message msg 37 (WM_QUERYDRAGICON) not supported yet
06cc:fixme:msg:pack_message msg 7f (WM_GETICON) not supported yet
06cc:fixme:msg:pack_message msg 7f (WM_GETICON) not supported yet
06cc:fixme:class:CLASS_GetClassLong offset -34 (GCLP_HICONSM) not supported on other process window 000000000002013E
06cc:fixme:class:CLASS_GetClassLong offset -14 (GCLP_HICON) not supported on other process window 000000000002013E
06cc:fixme:msg:pack_message msg 37 (WM_QUERYDRAGICON) not supported yet
06cc:fixme:msg:pack_message msg 7f (WM_GETICON) not supported yet
06c8:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_CACHE_INFORMATION
06cc:fixme:msg:pack_message msg 7f (WM_GETICON) not supported yet
06cc:fixme:class:CLASS_GetClassLong offset -34 (GCLP_HICONSM) not supported on other process window 000000000009010E
06cc:fixme:class:CLASS_GetClassLong offset -14 (GCLP_HICON) not supported on other process window 000000000009010E
06cc:fixme:msg:pack_message msg 37 (WM_QUERYDRAGICON) not supported yet
06cc:fixme:msg:pack_message msg 7f (WM_GETICON) not supported yet
06cc:fixme:msg:pack_message msg 7f (WM_GETICON) not supported yet
06cc:fixme:class:CLASS_GetClassLong offset -34 (GCLP_HICONSM) not supported on other process window 00000000003101F4
06cc:fixme:class:CLASS_GetClassLong offset -14 (GCLP_HICON) not supported on other process window 00000000003101F4
06cc:fixme:msg:pack_message msg 37 (WM_QUERYDRAGICON) not supported yet
06cc:fixme:msg:pack_message msg 7f (WM_GETICON) not supported yet
06cc:fixme:msg:pack_message msg 7f (WM_GETICON) not supported yet
06cc:fixme:class:CLASS_GetClassLong offset -34 (GCLP_HICONSM) not supported on other process window 000000000002013E
06cc:fixme:class:CLASS_GetClassLong offset -14 (GCLP_HICON) not supported on other process window 000000000002013E


Backtracing for thread 0244 in process 0230 (c:\Program Files\Dwarf Fortress\dwarf fortress.exe):
Backtrace:
=>0 0x000000007bc0e454 EntryPoint+0xffffffffffffffff() in ntdll (0x000000000031fbc9)
  1 0x0000000360e77392 EntryPoint+0x2ffff1ec1() in msvcp140 (0x000000000031fbc9)
  2 0x0000000140624bb9 in dwarf fortress (+0x624bb8) (0x000000000031fbc9)
  3 0x0000000140625700 in dwarf fortress (+0x6256ff) (0x000000000031fbc9)
  4 0x0000000140625efe in dwarf fortress (+0x625efd) (0x0000000000000007)
  5 0x000000014062679b in dwarf fortress (+0x62679a) (0x000000000031fd39)
  6 0x00000001410f35b2 in dwarf fortress (+0x10f35b1) (0x0000000000b50030)
  7 0x00000001410f2c7a in dwarf fortress (+0x10f2c79) (0x0000000000000000)
  8 0x000000007b62c679 EntryPoint+0xffffffffffffffff() in kernel32 (0x0000000000000000)
  9 0x000000007bc57dc3 EntryPoint+0xffffffffffffffff() in ntdll (0x0000000000000000)

Backtracing for thread 0240 in process 0230 (c:\Program Files\Dwarf Fortress\dwarf fortress.exe):
Backtrace:
=>0 0x00007ff8049fcfdc (0x0000000000c5f1f0)

Backtracing for thread 024c in process 0230 (c:\Program Files\Dwarf Fortress\dwarf fortress.exe):
Backtrace:
=>0 0x0000000005d1c8b4 EntryPoint+0xffffffffffffffff() in logistics.plug (0x0000000000000000)
  1 0x0000000005d19f77 EntryPoint+0xffffffffffffffff() in logistics.plug (0x0000000000d6f790)
  2 0x0000000005d1cf29 EntryPoint+0xffffffffffffffff() in logistics.plug (0x0000000004b3bf60)
  3 0x0000000002e23855 EntryPoint+0xffffffffffffffff() in dfhooks (0x0000000004b3bf60)
  4 0x0000000002cb3c9e EntryPoint+0xffffffffffffffff() in dfhooks (0x0000000000000000)
  5 0x0000000002cade99 EntryPoint+0xffffffffffffffff() in dfhooks (0x0000000000000003)
  6 0x00000001406251c4 in dwarf fortress (+0x6251c3) (0x0000000000000003)
  7 0x0000000140626349 in dwarf fortress (+0x626348) (0x0000000000000000)
  8 0x000000036b51c417 EntryPoint+0x3000ab1b0() in sdl2 (0x0000000000000000)
  9 0x000000036b5d191e EntryPoint+0x3001606b7() in sdl2 (0x0000000000000000)
  10 0x000000007b62c679 EntryPoint+0xffffffffffffffff() in kernel32 (0x0000000000000000)
  11 0x000000007bc57dc3 EntryPoint+0xffffffffffffffff() in ntdll (0x0000000000000000)

Backtracing for thread 0248 in process 0230 (c:\Program Files\Dwarf Fortress\dwarf fortress.exe):
Backtrace:
=>0 0x000000007bc0e474 EntryPoint+0xffffffffffffffff() in ntdll (0x000000000182fce0)
  1 0x000000007b06b64c EntryPoint+0x3248b() in kernelbase (0x000000000182fce0)
  2 0x000000007b06bd6e EntryPoint+0x32bad() in kernelbase (0x000000000182fe30)

Backtracing for thread 0238 in process 0230 (c:\Program Files\Dwarf Fortress\dwarf fortress.exe):
Backtrace:
=>0 0x000000007bc0d114 EntryPoint+0xffffffffffffffff() in ntdll (0x0000000000000000)
  1 0x000000007b01009f EntryPoint+0xffffffffffffffff() in kernelbase (0x0000000000000000)
  2 0x0000000002ee8b92 EntryPoint+0xffffffffffffffff() in dfhooks (0x0000000000000000)
  3 0x0000000002ee85cc EntryPoint+0xffffffffffffffff() in dfhooks (0x00000000033d83c0)
  4 0x0000000002cb48e9 EntryPoint+0xffffffffffffffff() in dfhooks (0x000000000643fd10)
  5 0x0000000002c02daf EntryPoint+0xffffffffffffffff() in dfhooks (0x0000000000000000)
  6 0x000000007b62c679 EntryPoint+0xffffffffffffffff() in kernel32 (0x0000000000000000)
  7 0x000000007bc57dc3 EntryPoint+0xffffffffffffffff() in ntdll (0x0000000000000000)

Backtracing for thread 0234 in process 0230 (c:\Program Files\Dwarf Fortress\dwarf fortress.exe):
Backtrace:
=>0 0x000000007bc0e454 EntryPoint+0xffffffffffffffff() in ntdll (0x000000000654fda9)
  1 0x0000000360e77392 EntryPoint+0x2ffff1ec1() in msvcp140 (0x000000000654fda9)
  2 0x0000000002cb6d7f EntryPoint+0xffffffffffffffff() in dfhooks (0x000000000654fda9)
  3 0x0000000002cb4552 EntryPoint+0xffffffffffffffff() in dfhooks (0x000000000654fda9)
  4 0x0000000002c02daf EntryPoint+0xffffffffffffffff() in dfhooks (0x0000000000000000)
  5 0x000000007b62c679 EntryPoint+0xffffffffffffffff() in kernel32 (0x0000000000000000)
  6 0x000000007bc57dc3 EntryPoint+0xffffffffffffffff() in ntdll (0x0000000000000000)

Backtracing for thread 0220 in process 0230 (c:\Program Files\Dwarf Fortress\dwarf fortress.exe):
Backtrace:
=>0 0x000000007bc0e494 EntryPoint+0xffffffffffffffff() in ntdll (0x000000007bc58bc0)
  1 0x000000007bc5e13a EntryPoint+0xffffffffffffffff() in ntdll (0x000000007bc58bc0)
  2 0x000000007b62c679 EntryPoint+0xffffffffffffffff() in kernel32 (0x0000000000000000)
  3 0x000000007bc57dc3 EntryPoint+0xffffffffffffffff() in ntdll (0x0000000000000000)

Backtracing for thread 02ec in process 0230 (c:\Program Files\Dwarf Fortress\dwarf fortress.exe):
Backtrace:
=>0 0x000000007bc0d4f4 EntryPoint+0xffffffffffffffff() in ntdll (0x000000000116fb80)
  1 0x000000007b058e2f EntryPoint+0x1fc6e() in kernelbase (0x000000000116fb80)
  2 0x0000000336853c9d EntryPoint+0x2ffff996c() in mmdevapi (0x000000000116fb80)
  3 0x000000007b62c679 EntryPoint+0xffffffffffffffff() in kernel32 (0x0000000000000000)
  4 0x000000007bc57dc3 EntryPoint+0xffffffffffffffff() in ntdll (0x0000000000000000)

Backtracing for thread 02c4 in process 0230 (c:\Program Files\Dwarf Fortress\dwarf fortress.exe):
Backtrace:
=>0 0x000000007bc0d074 EntryPoint+0xffffffffffffffff() in ntdll (0x0000000000000000)
  1 0x000000007b06bc0c EntryPoint+0x32a4b() in kernelbase (0x0000000000000000)
  2 0x00000001800c0e1a EntryPoint+0xfffa116d() in fmod (0x0000000000000000)
  3 0x00000001800b7aba EntryPoint+0xfff97e0d() in fmod (0x0000000000000000)
  4 0x00000001800c003b EntryPoint+0xfffa038e() in fmod (0x0000000000000000)
  5 0x000000018012f8d4 EntryPoint+0x10000fc27() in fmod (0x0000000000000000)
  6 0x000000007b62c679 EntryPoint+0xffffffffffffffff() in kernel32 (0x0000000000000000)
  7 0x000000007bc57dc3 EntryPoint+0xffffffffffffffff() in ntdll (0x0000000000000000)

Backtracing for thread 02c8 in process 0230 (c:\Program Files\Dwarf Fortress\dwarf fortress.exe):
Backtrace:
=>0 0x000000007bc0e474 EntryPoint+0xffffffffffffffff() in ntdll (0x000000000138fd70)
  1 0x000000007b06b64c EntryPoint+0x3248b() in kernelbase (0x000000000138fd70)
  2 0x000000007b06bd6e EntryPoint+0x32bad() in kernelbase (0x0000000000000000)
  3 0x00000001800c3769 EntryPoint+0xfffa3abc() in fmod (0x0000000000000000)
  4 0x00000001800b7aa1 EntryPoint+0xfff97df4() in fmod (0x0000000000000000)
  5 0x00000001800c003b EntryPoint+0xfffa038e() in fmod (0x0000000000000000)
  6 0x000000018012f8d4 EntryPoint+0x10000fc27() in fmod (0x0000000000000000)
  7 0x000000007b62c679 EntryPoint+0xffffffffffffffff() in kernel32 (0x0000000000000000)
  8 0x000000007bc57dc3 EntryPoint+0xffffffffffffffff() in ntdll (0x0000000000000000)

Backtracing for thread 02c0 in process 0230 (c:\Program Files\Dwarf Fortress\dwarf fortress.exe):
Backtrace:
=>0 0x000000007bc0d074 EntryPoint+0xffffffffffffffff() in ntdll (0x0000000000000000)
  1 0x000000007b06bc0c EntryPoint+0x32a4b() in kernelbase (0x0000000000000000)
  2 0x00000001800c0e1a EntryPoint+0xfffa116d() in fmod (0x0000000000000000)
  3 0x00000001800b7aba EntryPoint+0xfff97e0d() in fmod (0x0000000000000000)
  4 0x00000001800c003b EntryPoint+0xfffa038e() in fmod (0x0000000000000000)
  5 0x000000018012f8d4 EntryPoint+0x10000fc27() in fmod (0x0000000000000000)
  6 0x000000007b62c679 EntryPoint+0xffffffffffffffff() in kernel32 (0x0000000000000000)
  7 0x000000007bc57dc3 EntryPoint+0xffffffffffffffff() in ntdll (0x0000000000000000)

Backtracing for thread 0310 in process 0230 (c:\Program Files\Dwarf Fortress\dwarf fortress.exe):
Backtrace:
=>0 0x000000007bc5218d EntryPoint+0xffffffffffffffff() in ntdll (0x0000000000000000)
  1 0x000000007bc43bf9 EntryPoint+0xffffffffffffffff() in ntdll (0x0000000000000000)
  2 0x000000007b62c679 EntryPoint+0xffffffffffffffff() in kernel32 (0x0000000000000000)
  3 0x000000007bc57dc3 EntryPoint+0xffffffffffffffff() in ntdll (0x0000000000000000)
0x000000007bc5218d EntryPoint+0xffffffffffffffff in ntdll: ret

**Comment by don-hwy** [comment]
I removed the logistics plugin and the game doesn't crash. So that's good!

**Comment by don-hwy** [comment]
Also hangs when doing:

[DFHack]# logistics
logistics is actively monitoring stockpiles and marking items

-- 
no output

**Comment by myk002** [comment]
that might be a good avenue of research. could you run this command:
```
debugfilter set trace logistics
```
and then run the `logistics` command so it hangs? there might be too much output to capture, but I'd be interested in at least the last few lines before it hangs.

**Comment by don-hwy** [comment]
[DFHack]# debugfilter set trace logistics
Plugin      Category    Lowest printed
logistics   status      Info->Trace
logistics   cycle       Info->Trace
running logistics cycle
removing persistent key for stockpile 63
[DFHack]#

then
*CRASH*

**Comment by myk002** [comment]
does it crash at the same place when you run the `logistics` command?

**Comment by don-hwy** [comment]
[DFHack]# logistics
calling logistics lua function: 'parse_commandline'
logistics is actively monitoring stockpiles and marking items
entering logistics_getStockpileData
removing persistent key for stockpile 63
removing persistent key for stockpile 60

dfhack command prompt hung, no further output

**Comment by myk002** [comment]
did you remove stockpiles 63 and 60 before running the command?

**Comment by don-hwy** [comment]
That was with the stockpile removed.

This is the output when I simply toggle the trading on the overlay.. so it is trying to still remove the key even when the stockpile is still there.

[DFHack]# debugfilter set trace logistics
Plugin      Category    Lowest printed
logistics   status      Info->Trace
logistics   cycle       Info->Trace
entering logistics_getStockpileConfigs
entering logistics_getStockpileConfigs
entering logistics_getStockpileConfigs
entering logistics_setStockpileConfig stockpile_number=63, melt=0, trade=0, dump
=0, train=0
ensuring stockpile config stockpile_number=63
stockpile exists in watched_stockpiles
entering logistics_getStockpileConfigs
removing persistent key for stockpile 63
removing persistent key for stockpile 60
[DFHack]#

**Comment by myk002** [comment]
it actually looks like that's expected -- it removes the config if no flags are set -- and you just removed the last flag. at least for stockpile 63 -- did stockpile 60 still have a flag set?

**Comment by don-hwy** [comment]
`if (!bld || (
                !get_config_bool(c, STOCKPILE_CONFIG_MELT) &&
                !get_config_bool(c, STOCKPILE_CONFIG_TRADE) &&
            !get_config_bool(c, STOCKPILE_CONFIG_DUMP) &&
            !get_config_bool(c, STOCKPILE_CONFIG_TRAIN))) {
            remove_stockpile_config(out, stockpile_number);`

Looks like it removes the key when all the trade/melt/etc settings are off.

**Comment by don-hwy** [comment]
posted at the same time lol

**Comment by don-hwy** [comment]
Yes, stockpile 60 is marked for trading as well. I think there's only those two I marked for trading so far.

**Comment by myk002** [comment]
so it removed the key for stockpile 60 even when it wasn't supposed to..

**Comment by don-hwy** [comment]
In the overlay, trading _is highlighted_ though. That is weird.

**Comment by myk002** [comment]
is stockpile 60 out of order in the vector perhaps? how could that happen?

Just to make sure we're seeing the same things, could you possibly switch to the `testing` branch for DFHack on Steam?

**Comment by don-hwy** [comment]
I don't have steam working with wine... Maybe I can try it the same way I did with df by forcibly telling steam to download it regardless of OS compat.

**Comment by myk002** [comment]
that works -- or selecting proton as the compatibility layer
you can also just download the archive and install manually

**Comment by don-hwy** [comment]
Thanks, I was about to ask for a link.

**Comment by myk002** [comment]
are you on the DFHack discord (https://dfhack.org/discord)? it might be easier to have a conversation there

**Comment by myk002** [comment]
look at that; I got me a crash. Iterating through the `world->buildings.other.STOCKPILE` vector after a stockpile is removed causes problems. this sounds very likely to be the issue you're running into

**Comment by don-hwy** [comment]
Yeah, same issue with 50.09-r2rc2 

[DFHack]# debugfilter set trace logistics
Plugin      Category    Lowest printed
logistics   status      Info->Trace
logistics   cycle       Info->Trace
entering logistics_getStockpileConfigs
entering logistics_getStockpileConfigs
entering logistics_setStockpileConfig stockpile_number=63, melt=0, trade=0,
=0, train=0
ensuring stockpile config stockpile_number=63
stockpile exists in watched_stockpiles
entering logistics_getStockpileConfigs
removing persistent key for stockpile 63
removing persistent key for stockpile 60
[DFHack]#

I'm not on discord, but I can join it after I eat dinner.

**Comment by myk002** [comment]
cool. thanks! I might have something more concrete for you to try then too

**Comment by myk002** [comment]
I think I found the issue. Modification of container while iterating through it. Classic facepalm moment, and I should check all the other plugins to make sure they don't suffer from the same problem.

**Comment by myk002** [comment]
yup that was it. thank you profusely for helping me find this!. I checked the other plugins with similar architectures and they all avoid this problem, so this was this only bad apple.

**Comment by myk002** [comment]
when you get back, could you test the "fixed" build from here: https://github.com/DFHack/dfhack/actions/runs/5627883852#artifacts ?

**Comment by don-hwy** [comment]
:+1: 

Solved for me. I think all this translation overhead helps to weed out the nasties. It was immediate, every single time, on my end.
