### ISSUE TITLE
Notify when traders have finished unloading

### ISSUE THREAD

**Issue by DragonEyeNinja** [DFHack/dfhack#3591]
Vanilla DF alerts the player when merchants arrive and begin unloading their goods, but it never tells them _when_ the goods have been finished unloading, which tends to get out of hand in larger forts (can literally take months). This usually results in me anxiously keeping watch on the trade depot.

While the notification that the merchants will be leaving soon is usually _good enough,_ it can become a problem when your broker refuses to finish up his tasks and go trade, resulting in potential missed exports/imports for the year.

Thus, some kind of pop-up stating that merchants from xyz civilization have finished unloading their goods would be very helpful.

**Comment by don-hwy** [comment]
dfhack has a 'caravan extend' command that will keep the merchants there longer. And If they're leaving, they will turn back. I've also temporarily switched brokers when my main one is being lazy.

**Comment by myk002** [comment]
also see #3745

**Comment by myk002** [comment]
this is now provided by `gui/notify`
