### ISSUE TITLE
Feature request: Show designated stone smoothing/engraving/carving while using ascii glyphs

### ISSUE THREAD

**Issue by zeddy1267** [DFHack/dfhack#3594]
In ascii mode, there is currently no way to see stone smoothing or engraving designations (at least not any I could find, I'd be really embarrassed otherwise), which makes stone smoothing/engraving rather frustrating to work with while using ascii glyphs, especially if you're trying to cancel the designation, since there's no way to see if they exist or not. 

This also affects carving minecart tracks and fortifications. Everything in the wall orders has no visuals for ascii glyphs.

in older versions of DF, I believe carving designations were shown always, similar to mining designations. However, I believe that only showing carving designations while in the wall carving menu (and the remove orders menu) would likely be less annoying. If possible, the option to choose between always showing wall orders, or only showing them with relevant menus open would be great!

The 4 wall orders, smoothing, engraving, carving tracks, and carving fortifications should all be visually distinct.

**Comment by myk002** [comment]
Ideas for *making* them visually distinct would be welcome : )

**Comment by zeddy1267** [comment]
**_OLD DF FOOTAGE FOR REFERENCE_**
_smoothing designations_
https://github.com/DFHack/dfhack/assets/25875170/ebb325df-71ee-49e4-b1b7-6731b4e4292f

_carving designations (in order, engraving, fortification, carve tracks)_
https://github.com/DFHack/dfhack/assets/25875170/736c56bc-7601-47c4-a33b-d067ae039fac

**DESCRIPTION OF HOW OLD DF HANDLES IT**
Smoothing and engraving use the same tiles and colour for the preview, however, flashing between the designation preview and the tile tells you which it is, since you can see the designated surface underneath.

fortifications are the same, but are a different colour (red as opposed to cyan).

tracks show the preview of how they'll look once carved. This one is pretty good.

I'm not quite sure how feasible it is for DF hack to show the output tiles of a designation. For example, when carving tracks, it'd sure be nice for the preview to show what the shape of the tracks will be.

**SUGGESTIONS OF HOW IT COULD LOOK IN v50**
For stone smoothing, showing the shape of the smooth stone once smoothed would be ideal (would make it more clear how the wall would look after being smooth). However, if this isn't possible, i think simply showing a `+` for floors and an `O` for walls (the tile used when a singular wall is smoothed) would probably be best. Worst case scenario, I suppose it could still use the same tiles they did in old DF, provided they flash so the surface beneath is visible.

Unlike all other designations, smoothing stone doesn't show when the task is currently being performed. When mining, and the rest of the wall order designations, the tile will blink to indicate a dwarf is currently doing the job.  This isn't the case for smoothing, and as a bonus, it'd be a nice thing to have in DFhack too, but I have no clue if this is possible.

Below is a picture of engravings currently being carved in v50 (I's flashing, just like any designation currently being performed, which obviously doesn't show in a still image). I'm actually shocked that it shows you the engraving preview *while* they're doing it, but not while it's designated. this goes for all of the wall orders except smoothing. Due to keeping parity between the two symbols, engravings should be the same as they appear while the task is being preformed, which would make them appear the same as they did in old DF.
![image](https://github.com/DFHack/dfhack/assets/25875170/df1804d5-4015-4f13-b2eb-9c695056e2d8)


Much like engravings, fortifications should stay the same as they were in old DF, since while the task is being performed, the preview shown is the same as it used to be. However, it is orange instead of red.
![image](https://github.com/DFHack/dfhack/assets/25875170/34d3f9cf-bc29-4840-abd2-14e36ab30d2b)


For tracks? I'm not quite sure what a solution could be if it's not feasible to show the output shape of the tracks. While making track designations, the game uses `#`, so I suppose that would work if showing the preview shape of the track isn't possible. Weirdly enough, if you construct tracks as opposed to carving them, the preview for them is perfectly fine.
![image](https://github.com/DFHack/dfhack/assets/25875170/6f63c0c7-403d-4a11-8d95-b5c21d2eb298)
_Tracks currently being **CARVED** in v50_
![image](https://github.com/DFHack/dfhack/assets/25875170/771bbac2-a88a-42f4-bf4c-efb416996dc2)
_some tracks being **CONSTRUCTED** in v50_

**Comment by myk002** [comment]
implemented in https://github.com/DFHack/dfhack/pull/3761
