### ISSUE TITLE
Suspendmanager multi-level ramp issue

### ISSUE THREAD

**Issue by egocarib** [DFHack/dfhack#3600]
Example of incorrect suspendmanager handling I encountered today:

Level 1:
<img width="236" alt="Dwarf_Fortress_JEOhsduxxO" src="https://github.com/DFHack/dfhack/assets/3429497/a83eb758-4a28-4a2a-842a-014353314e30">

Level 2 (above):
<img width="187" alt="Dwarf_Fortress_TzGtWkj13l" src="https://github.com/DFHack/dfhack/assets/3429497/40d46f82-abd2-4afb-876d-4780247b3777">

These suspensions cause a central wall to be built before the outer edges and the wall can't be completed. Should have been suspended similar to the wall on the left side in order to work correctly.

After:
<img width="580" alt="Dwarf_Fortress_nm3smzAWw5" src="https://github.com/DFHack/dfhack/assets/3429497/ae2f50ff-c9c9-4143-86a0-e23358b52e7a">

**Comment by egocarib** [comment]
Ah, yes - I see what you mean about the bottom right. Maybe it would have made sense to build the two bottommost-right walls and then leave the third one suspended? Then I would've realized they couldn't access it and I could've mined out the wall to the left of that space. Not sure how easy that is to figure out though. Thanks for thinking about it, regardless.

**Comment by plule** [comment]
That would be even better yes, but possibly not easy to implement and maintain... As of now, suspendmanager never take in account diagonals, and it's already a headache sometimes.

**Comment by myk002** [comment]
@plule do recent improvements in `suspendmanager` cover these cases sufficiently?
