### ISSUE TITLE
Suspendmanager: account for unsupported walls when building near floor grates

### ISSUE THREAD

**Issue by egocarib** [DFHack/dfhack#3601]
Just had a cave-in when dwarves built one of these walls attached only to a grate floor. To be safe when building, they would've needed to wait until connecting/supporting wall was built.

![image](https://github.com/DFHack/dfhack/assets/3429497/ce78b48f-e07a-474b-bfbe-2d66079b5a06)

**Comment by myk002** [comment]
fixed in https://github.com/DFHack/scripts/pull/839
