### ISSUE TITLE
`caravan leave` should clear the "broker needed at depot" flag if all caravans are leaving

### ISSUE THREAD

**Issue by ab9rf** [DFHack/dfhack#3608]
the game normally clears this flag when the last caravan leaves, but `caravan leave` leaves it set

**Comment by myk002** [comment]
so it appears that while setting the flag on the depot is trivial, the TradeAtDepot job itself cannot be canceled via `dfhack.job.removeJob()`. `world->jobs.cancel_job(job);` appears to have no effect.

manually clicking on the `No broker needed` button successfully cancels the job, though.

**Comment by ab9rf** [comment]
lemme look into what clicking on that button does, maybe i can come up with something

**Comment by ab9rf** [comment]
found it:

```
          pbVar5->trade_flags =
               pbVar5->trade_flags & ~building_tradedepotst__SCOPE__T_trade_flags_trader_requested;
          ppjVar23 = (pbVar5->jobs)._M_start;
          iVar18 = (int)((longlong)(pbVar5->jobs)._M_finish - (longlong)ppjVar23 >> 3) + -1;
          lVar31 = (longlong)iVar18;
          if (-1 < iVar18) {
            do {
              pjVar7 = ppjVar23[lVar31];
              if ((pjVar7->job_type == TradeAtDepot) && (pjVar7 != (job *)0x0)) {
                job::_delete(pjVar7);
                ppjVar23 = (pbVar5->jobs)._M_start;
              }
              lVar31 += -1;
            } while (-1 < lVar31);
          }
          lVar21 += -1;
```
the dialog just flat out locates all `TradeAtDepot` job _in the depot's job list_ and throws them at `job::_delete`, which is the same as using `job_handlerst::cancel_job`,

**Comment by myk002** [comment]
This is the code that I currently have:
```lua
        for _,depot in ipairs(df.global.world.buildings.other.TRADE_DEPOT) do
            depot.trade_flags.trader_requested = false
            for i, job in ipairs(depot.jobs) do
                if job.job_type == df.job_type.TradeAtDepot then
                    depot.jobs:erase(i)
                    dfhack.job.removeJob(job)
                    break
                end
            end
        end
```

the job *is* successfully erased from the building job list, but `dfhack.job.removeJob()` does *not* destroy the job, and the broker is still shown as trading at the depot:

![Image](https://github.com/DFHack/dfhack/assets/977482/bdee3405-fa08-410e-870b-e320b72f3c5a)

**Comment by myk002** [comment]
I note that `dfhack.job.removeJob()` can be called on the job multiple times without any ill effects, so it calls into question the comment in the code:
```cpp
// job_handler::cancel_job calls job::~job, and then deletes job (this has
// been confirmed by disassembly).
```
since the job does not appear to be deleted

**Comment by ab9rf** [comment]
calling `cancel_job` repeatedly on the same job will reliably cause heap corruption as `job::_delete` ultimately frees its argument, after which point that pointer is invalid, so calling it a second time is guaranteed to be UB. the code has no safety check to ensure you don't do this

**Comment by myk002** [comment]
What I meant was that the job remains in the world and depot job lists after calling `cancel_job`, so running `caravan leave` multiple times will result in multiple calls to `cancel_job` for the same job (since it gets the job from the depot `jobs` vector)
