### ISSUE TITLE
Workshop-specific work orders (sometimes) disappear from "Work orders" tab of workshop when "orders-sort" maintenance feature is enabled

### ISSUE THREAD

**Issue by ngc-6853** [DFHack/dfhack#3610]
As per the title... I have the habit to setup work orders by workshops because the global list is a PITA to use, using the work orders tab of a workshop.
After enabling orders-sort, when adding a work order to a workshop, it sometimes (most of the time?) disappear immediately from the workshop tab. It doesn't always happen but I am unsure of a pattern - game paused or not, WO conditions or not.
However the work order does still exist, listed in the global work order list ("o" window).
After disabling orders-sort everything is back to normal and WO remain in the workshop WO tab.
I hope the issue is clear enough, let me know anyway :)

**Comment by myk002** [comment]
This appears to be a vanilla bug. You don't even have to use `orders sort` to get this to happen. Here's a video of just playing around with the order in the vanilla UI. You can see the effect it has on which orders show up in the workshop interface:

https://github.com/DFHack/dfhack/assets/977482/0213e794-6261-4afc-84c7-7c8c21fff395

**Comment by ngc-6853** [comment]
My bad! I don't remember if I tried to reproduce in a vanilla DF before reporting, I will make sure I do it next time!
So I guess I now have to file a bug in DF bug-tracker :upside_down_face:
