### ISSUE TITLE
Mods modules cannot be enabled on save reload

### ISSUE THREAD

**Issue by Bltgn** [DFHack/dfhack#3618]
Hello,

I created a module using [this guide](https://docs.dfhack.org/en/stable/docs/guides/modding-guide.html?highlight=--%40%20enable%20%3D%20true#your-first-script). It is located into my mod's scripts_modactive folder with its submodules in internal/<my-mod> as instructed.

It work as intended when you start a new game and load your save but if you quit to the main menu and reload your save, the module stay disabled, not even using the enable command work as seen in the console.

First load of a save fresh from DF start. Work as intended.
```
indexing mod path: data/installed_mods/succubus_dungeon (1900)/scripts_modactive
Loading script: dfhack-config/init/default.onLoad.init
Loading script: hack/init/onLoad.default.init
Loading script: dfhack-config/init/onLoad.init
Magmawell activated
Powers activated
Succubus Dungeon mod enabled
Loading script: dfhack-config/init/default.onMapLoad.init
Loading script: hack/init/onMapLoad.default.init
Loading script: dfhack-config/init/onMapLoad.init
Loading script: dfhack-config/init/onMapLoad.control-panel-new-fort.init
Loading script: dfhack-config/init/onMapLoad.control-panel-repeats.init
```

Quit to main menu (with or without saving), work as intended.
```
Succubus Dungeon mod disabled
Loading script: dfhack-config/init/default.onMapUnload.init
Loading script: hack/init/onMapUnload.default.init
Loading script: dfhack-config/init/onMapUnload.init
Loading script: dfhack-config/init/default.onUnload.init
Loading script: hack/init/onUnload.default.init
Loading script: dfhack-config/init/onUnload.init
```

Reload of the game, the module is disabled and cannot be enabled again, even by command. Note that the "disabled" message appear twice.
```
indexing mod path: data/installed_mods/succubus_dungeon (1900)/scripts_modactive
Succubus Dungeon mod disabled
Loading script: dfhack-config/init/default.onLoad.init
Loading script: hack/init/onLoad.default.init
Loading script: dfhack-config/init/onLoad.init
Succubus Dungeon mod disabled
Loading script: dfhack-config/init/default.onMapLoad.init
Loading script: hack/init/onMapLoad.default.init
Loading script: dfhack-config/init/onMapLoad.init
Loading script: dfhack-config/init/onMapLoad.control-panel-new-fort.init
Loading script: dfhack-config/init/onMapLoad.control-panel-repeats.init
[DFHack]# enable succubus-dungeon
Succubus Dungeon mod disabled
[DFHack]#
```

dfhack_flags.enable_state is false when you try the enable command. The only work around is to write the module on disk, ie. adding a space and saving, then it can be enabled again.

Here's the module : https://gist.github.com/Bltgn/107eee72e47304fcab8581bedf5b9f27

Thanks

**Comment by myk002** [comment]
There is a build with this fix up on the `testing` branch on Steam. If you switch to that branch, you'll be able to test and make sure things work now.
