### ISSUE TITLE
Build workflow failing on forks

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#3639]
e.g. in https://github.com/lethosor/dfhack/actions/runs/5774462887/job/15651432054:
```
Checking out the ref
  /usr/bin/git checkout --progress --force -B css-skip-temp-save refs/remotes/origin/css-skip-temp-save
  Error: fatal: 'refs/remotes/origin/css-skip-temp-save' is not a commit and a branch 'css-skip-temp-save' cannot be created from it
  Error: The process '/usr/bin/git' failed with exit code 128
```

I think `refs/remotes/origin/css-skip-temp-save` is the `dfhack_ref` argument coming from `build.yml`.

On develop, a similar command worked:
```
Checking out the ref
  /usr/bin/git checkout --progress --force -B develop refs/remotes/origin/develop
  Switched to a new branch 'develop'
  branch 'develop' set up to track 'origin/develop'.
```

so maybe the problem is that the repo URL is wrong?

**Comment by myk002** [comment]
I see, so this is for a branch on a fork that is *not* part of a PR. Yes, I didn't account for this case. I'll have to investigate how we can support it.

**Comment by myk002** [comment]
Could you try rerunning the workflows on your fork and verifying that this is fixed?

**Comment by lethosor** [comment]
https://github.com/lethosor/dfhack/actions/runs/5777540032/job/15657833169 worked!
