### ISSUE TITLE
Workflow and plant cloth

### ISSUE THREAD

**Issue by MIC132** [DFHack/dfhack#366]
When I try to set Range/Limit for my looms using workflow for "cloth of any plant" it shows the amount in stock as 0, no matter how much I have in stock (this causes them to work as on repeat, cause they always think there is not enough). When set to "any cloth" it shows total cloth properly.

**Comment by dorsey** [comment]
I am also having this issue in 0.40.24-r3.

**Comment by PeridexisErrant** [comment]
Closed by pull #611
