### ISSUE TITLE
Workflow vs powders

### ISSUE THREAD

**Issue by HrabiaVulpes** [DFHack/dfhack#367]
DF 0.40.13
dfhack 0.40.13-r1

Because gypsum plaster, sand, and dimple dye are for basic workflow the same thing (and are counted together) I tried to use advanced mode, but it doesn't work. After choosing 'update' nothing happens, no changes are applied. Quern or mill is still counting sand and dimple dye together, and entering advanced parameters shows that they reset.

**Comment by PeridexisErrant** [comment]
Closed by pull #611
