### ISSUE TITLE
gui/create-item creates vermin incorrectly

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#3674]
the funky way it passes race and caste information results in the incorrect variables being passed to `dfhack.items.createItem`. It may be that the `caste` variable doesn't even need to exist, and the race and caste can be passed in the mattype and matindex vars. this would fix vermin, but some testing needs to be done to make sure it doesn't break corpses, corpse pieces, and other creature-dependent items

**Comment by quietust** [comment]
The race+caste **are** supposed to be passed in the material fields, and I'm pretty sure the console `createitem` command does this and works properly.
