### ISSUE TITLE
Steam Linux version

### ISSUE THREAD

**Issue by andyhunne** [DFHack/dfhack#3682]
So, there is a Linux beta out now on Steam...

Happy to volunteer as a tester, but really have no idea how to work towards getting DFHack operating with the Linux version. Would it require a completely different DFHack release for Steam, or can the current one work with Linux as well as long as it recognises the version?

**Comment by myk002** [comment]
Good timing : ) We just released DFHack 50.09-r3rc1 with Linux support

https://www.reddit.com/r/dwarffortress/comments/15v194s/dfhack_5009r3rc1_released_on_the_steam_beta_branch/

You can see a fair history of what it took to get things working on Linux by browsing through the https://dfhack.org/discord channels, especially `#reverse-engineering`

Testing is still welcome, of course! Especially as we implement dynamic runtime symbol discovery, which might behave differently on different Linux systems.

**Comment by andyhunne** [comment]
Cheers - will give it a crack and provide whatever feedback I can if I encounter issues!

**Comment by andyhunne** [comment]
Cheers, will give it a crack and provide feedback on any issues encountered!
