### ISSUE TITLE
dfhack beta & testing branches on steam are missing symbols for df windows "beta"

### ISSUE THREAD

**Issue by ab9rf** [DFHack/dfhack#3686]
for windows clients, neither the steam `beta` nor the steam `testing` branch have the `0.50.09-06jul23` stanza that is required to match with the version of 50.09 that bay12 put on the df beta branch. i have confirmed this on both my own and my wife's computers via the steam client

these symbols are present in df-structures at `master` HEAD but apparently didn't get into dfhack `develop` prior to deploy on steam `beta` (`library/xml` apparently was not synced before deploy). i assume steam `testing` is deployed from the `linux` branch of df-structures, which also doesn't appear to have the needed `0.50.09-06jul23` stanza (and of course is not autosynced)

(as an aside, if it's possible to tell which branch the steam deploy action was told to deploy from the action run log, i can't find it. might be an idea to add some messages at the top to memorialize these parameters into the log)

i have not checked the github prerelease artifacts

i should add that both `beta` and `testing` appear to work fine with bay12's 50.09 release on windows, and so anyone on windows who runs into this issue can be directed to change to df's stable branch (as the "beta" for windows on df's beta branch appears to be not materially different from the 50.09 release)

**Comment by myk002** [comment]
fixed in https://github.com/DFHack/df-structures/pull/646
