### ISSUE TITLE
ability to delete locations

### ISSUE THREAD

**Issue by ab9rf** [DFHack/dfhack#3701]
someone mentioned on kf discord that we can no longer delete locations from a fort, which we could do in v47. this is probably just an UI oversight, and so we could probably provide a means to do this with dfhack

**Comment by myk002** [comment]
dup of #3766

**Comment by myk002** [comment]
just because the newer one had a relevant https://github.com/DFHack/dfhack/issues/3766#issuecomment-1714928447
