### ISSUE TITLE
textures become corrupted on game reload

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#3709]
to reproduce:
1. load a fort
2. quit to main menu without saving
3. load the fort again

The DFHack logo will become corrupted during the loading sequence.

![image](https://github.com/DFHack/dfhack/assets/977482/d86819c8-a388-4c04-abea-ae2e99ad059b)

@shevernitskiy

**Comment by myk002** [comment]
disregard -- this is likely due to the tests I was doing with `cancel_job`, which apparently is corrupting things.

**Comment by myk002** [comment]
it doesn't appear to be a refcount issue. increasing the refcount by 10 instead of 1 did not solve the issue.

**Comment by shevernitskiy** [comment]
> it doesn't appear to be a refcount issue. increasing the refcount by 10 instead of 1 did not solve the issue.

if it something with refcount -> surface not exist -> nullref -> crash
cached texpos (index of texture.raws vector) refering to not target texture
