### ISSUE TITLE
tubefill will NOT prevent demons from spawning

### ISSUE THREAD

**Issue by latias1290** [DFHack/dfhack#372]
Tried using reveal, tubefill, unreveal, to safely mine adamantine. But that didn't work, as apparently the game spawns demons when a certain tile in the adamantine tube is revealed, and not if HFS is revealed.

Basically, using tubefill and mining all the admantine WILL STILL cause demons to spawn when the part of the adamantine which was initially empty is mined.

Also, because HFS is not revealed, the game does not announce "You have discovered an eerie cavern.", but will only announce "Horrifying screams come from the darkness below!".

I think this requires a fix, because otherwise the whole point of tubefill is nullified.

**Comment by PeridexisErrant** [comment]
I think this issues should be closed:  it's not a bug, but a documented limitation and the plugin is working as intended.

If someone wants to improve it so this doesn't happen that would be great, but still not the point here.

**Comment by lethosor** [comment]
Agreed. I thought the documentation was reasonably clear myself, but feel free to open a pull request for any changes that could make this clearer.
