### ISSUE TITLE
Suggestion: Documentation for ban-cooking should provide clarification regarding "all" 

### ISSUE THREAD

**Issue by BeerNTacos** [DFHack/dfhack#3741]
While ban-cooking is dedicated to making sure the user does not accidentally cook items that can be used for things other than cooking, some users see the "all" selection and assumes that means all cookable items can be banned via this script.

Perhaps the language in the help can be changed to note that the script is specifically made to ban multiple use items and that using "all" means that all cookable items that have uses outside of cooking will be banned, not all items that can be cooked (like meat and leaves).

**Comment by myk002** [comment]
Ref: https://reddit.com/r/dwarffortress/s/rZm3Bs7TFd
