### ISSUE TITLE
Search and sort for display case/pedestal list

### ISSUE THREAD

**Issue by Jahell51** [DFHack/dfhack#3751]
hello everyone! There is a hard lack of sorting artifacts in the game! It would be great if the display or pedestal menu could show which artifact is where and how much it costs.

**Comment by myk002** [comment]
needs searchable list of items, default sorted by value (real value potentially obfuscated according to the skill of your broker), and filterable by item quality. widgets can be reused from the trade dialogs

**Comment by Jahell51** [comment]
I see it somehow like this.
The window for assigning artifacts to the pedestal/display.
Green check mark - assigned to the pedestal/display.
The main thing is to be able to return to the list after viewing the information about the artifact.

![Снимок экрана 2023-09-22 204854 (1)](https://github.com/DFHack/dfhack/assets/144476333/cc2ff098-2bfd-4b2b-a2e2-7eeca67ee81e)

**Comment by myk002** [comment]
It would also be useful to show the total value added by the selected items, the value of the room that the pedestal is in, and whether the new value will be enough to get the room to the desired "level" (e.g. "Grand Guildhall")

**Comment by myk002** [comment]
implemented in https://github.com/DFHack/scripts/pull/844
