### ISSUE TITLE
50.09-r3 crashes when loading my fort, doesn't crash in older versions

### ISSUE THREAD

**Issue by Modoh** [DFHack/dfhack#3756]
Getting a crash immediately when my fort finishes loading on 50.09-r3.    

I went and checked the last few versions and it looks like the problem first showed up in 50.09-r3rc3.   Still crashes in the steam testing branch as well.    -r3rc1 and -r2 both don't crash, so it seems to be something new.   It also doesn't crash without dfhack (of course, or I wouldn't be here).   

Other forts I've tried loading don't crash even in the newest version, so it seems to be something specific going on with this one.   Since it seems fort specific this is my fort (too big for a github attachment):
https://drive.google.com/file/d/1LAtYSEXWJez3Y9V3AN4pIFhKlo1VBiFa/view?usp=sharing

I saw the release notes mentioned a Linux crash but I'm on Windows 10 x64.

**Comment by myk002** [comment]
this is due to an issue with seedwatch (fixed in https://github.com/DFHack/dfhack/pull/3753)

Until the next version of DFHack comes out, the easiest way to avoid the crash is to edit `region5/dfhack-legacy-data.dat` and remove all the elements that look like this:

```json
    {
        "i" :
        [
            -1,
            30,
            -1,
            -1,
            -1,
            -1,
            -1
        ],
        "k" : "seedwatch/seed/34",
        "s" : ""
    },
```

sorry for the inconvenience!

**Comment by Modoh** [comment]
All good, thanks for looking into it.    Removing the seedwatch stuff let me load the game on the current version, just like you suggested.
