### ISSUE TITLE
[beta] [linux] Steam Overlay and game streaming do not work when started as 'DFHack' in Steam

### ISSUE THREAD

**Issue by Jajcus** [DFHack/dfhack#3768]
When I was running vanilla Dwarf Fortress I was able to use Shift-Tab to open Steam Overlay, which was useful for making notes.
After I installed DFHack and start the game via DFHack the steam overlay is not available any more.

Possibly related: game streaming from other PC does not work. I have only tried that after installing DFHack, so I am not sure if this is also a problem in unmodded Dwarf Fortress, but it might be caused by the missing steam overlay which seems to affect DFHack only.

By the way: thanks for the native Linux build! I really do appreciate that.

**Comment by Jajcus** [comment]
With the new DF beta release v50.10 I can start Dwarf Fortress using 'Dwarf Fortress' and not 'DFHack' entry in Steam again.  And when started this way both streaming and steam overlay work as expected.

The problem remains when started as 'DFHack'.

**Comment by ab9rf** [comment]
I cannot replicate this on Windows, but I'm going to guess that this is with the native linux build, which suggests that the issue is that the dfhack launcher for linux is not properly propagating whatever environmental information the Steam client uses to communicate to the game that it's running under the client when it launches DF.

**Comment by Jajcus** [comment]
yes. I think it might be the ``LD_PRELOAD`` environment variable - the ``dfhack`` script sets its without preserving previous value. I will check this…

**Comment by Jajcus** [comment]
Yes, that was that. I'll try to make a pull request.

**Comment by myk002** [comment]
There is a separate issue at hand here, and that is that we need to relaunch DF from steam when DFHack is launched from Steam. This is the pattern we use on Windows to ensure both DFHack and DF are properly attributed play time. The relaunch mechanism hasn't been written yet for Linux

**Comment by ab9rf** [comment]
i figured as much but i don't know enough about the linux environment to implement the equivalent functionality to our windows relauncher
