### ISSUE TITLE
gui/launcher - impossible to delete a written character with backspace or delete key

### ISSUE THREAD

**Issue by RightPlaceInRightTime** [DFHack/dfhack#3782]
Strange problem I've been having on beta 50.10

Deleting a character after writing it seems impossible on my machine. Pressing backspace or delete key doesn't seem to do anything, everywhere else in Dwarf Fortress the backspace key is working.

Windows 10 22H2
Ryzen 5 3600
RTX 3070
16 GB DDR4

**Comment by lethosor** [comment]
Can you upload your stderr.log file so we can see the DF and DFHack version information?

**Comment by RightPlaceInRightTime** [comment]
[stderr.log](https://github.com/DFHack/dfhack/files/12643129/stderr.log)

No problem. Here it is.

**Comment by myk002** [comment]
You're on an older version of DF. If you update to the latest DF beta, it should start working again.

**Comment by RightPlaceInRightTime** [comment]
Thank you! Didn't even notice it.
