### ISSUE TITLE
Pause game on possessed dwarf mood

### ISSUE THREAD

**Issue by unboundlopez** [DFHack/dfhack#3790]
I want the possessed dwarf to make the best stuff they can possibly make with the resources I have, but by the time I pause the game they have already picked up a crap gem, cut gem, ore, bar, rock, block etc. . If we had a few more seconds to create a stockpile by an instantaneous pause when the dwarf claims a workshop or before. Well that would give us time to create a burrow and stick the possessed dwarf to gather the materials they need which we would know through showmood command.

**Comment by ab9rf** [comment]
this can be done in vanilla by altering the `announcements.txt` file in `prefs` file, just add `P` (or `BOX`) to the line for `STRANGE_MOOD`, basically find `[STRANGE_MOOD:A_D:D_D]` and change it to `[STRANGE_MOOD:P:A_D:D_D]` (or `[STRANGE_MOOD:BOX:A_D:D_D]`)

see the [wiki article on announcements.txt](https://dwarffortresswiki.org/index.php/Announcements.txt) for more information
