### ISSUE TITLE
remotefortressreader.cpp - ambiguous function call to `lerp` when built on Visual Studio using C++20

### ISSUE THREAD

**Issue by master-spike** [DFHack/dfhack#3795]
In `plugins/remotefortressreader/remotefortressreader.cpp`

- line 133: `using namespace std;`
```

- lines 1636 to 1639:
float lerp(float a, float b, float f)
{
    return a + f * (b - a);
}
```

and while `cmath` is not explicitly included, it is included indirectly. Hence at lines 1799-1801:
```
send_unit->set_subpos_x(lerp(0, unit->path.path.x[0] - unit->pos.x, (float)(action->data.move.timer_init - action->data.move.timer) / action->data.move.timer_init));
send_unit->set_subpos_y(lerp(0, unit->path.path.y[0] - unit->pos.y, (float)(action->data.move.timer_init - action->data.move.timer) / action->data.move.timer_init));
send_unit->set_subpos_z(lerp(0, unit->path.path.z[0] - unit->pos.z, (float)(action->data.move.timer_init - action->data.move.timer) / action->data.move.timer_init));
```

The compiler cannot deduce whether to call `lerp` as defined in the source file or `std::lerp` as defined in the `cmath` header. (`std::lerp` was added to the standard in C++20)

On my machine I get the following error:
```
D:\DFHACK\DFHACK_DEVEL\dfhack\plugins\remotefortressreader\remotefortressreader.cpp(1799,187): error C2668: 'lerp': amb
iguous call to overloaded function [D:\DFHACK\DFHACK_DEVEL\dfhack\build\win64\VC2022\plugins\remotefortressreader\Remot
eFortressReader.vcxproj]
```

I am assuming that the programmer intended to use their own provided `lerp` function. To that end, the `using namespace std;` could be replaced by only using the parts of the standard library that were intended to be used in this file?

**Comment by ab9rf** [comment]
`using namespace std` violates our coding guidelines anyway, so the real solution here is to remove that code smell
