### ISSUE TITLE
dig-now channels behaving differently than manually dug ones

### ISSUE THREAD

**Issue by Az6336** [DFHack/dfhack#3808]
Normally when channeling down tiles on the surface, newly grown grass may grow in those now-exposed tiles. This doesn't occur with dug tiles on the surface using the dig-now command.

I have a sample save where the top part of the cliff was channeled manually while the right bottom corner was done with dig-now.
Immediately after finishing the top part, new grass started to grow, while on the bottom corner it wouldn't.

The minimap also shows a different color on the flooring where the terrain was dug down with dig-now, appearing with a white hue. While the manually dug tiles appear as the same color as the rest of the natural surface tiles.

Save: https://www.mediafire.com/file/3cs4dta86pe0mbu/Dig-now+test.zip/file

**Comment by MagistrumT-T** [comment]
I managed to reproduce this bug, apparently it happens because the tile channeled by dig-now do not get their outside and subterranean flag updated properly. Are there any other things digging could affect where we could encounter this? Maybe temperature?
