### ISSUE TITLE
Cleanowned without dumping

### ISSUE THREAD

**Issue by ae3qe27u** [DFHack/dfhack#3817]
Hi!

How hard would it be to have a cleanowned option that confiscates dropped items/clothing without also dumping them? I like to have two clothing stockpiles - one directly from the clothier's shop with fresh clothing, and then a second that gathers from anywhere with all the discarded stuff, and so I do want to keep the stuff that's tattered/worn. I currently work around it by going into the stock page and just un-marking the items for deletion, but if it'd be straightforward to add an option that confiscates scattered stuff without also dumping it, that would be fantastic.

**Comment by myk002** [comment]
yes, `cleanowned` could be modified to just clear the ownership and not mark the item for dumping
