### ISSUE TITLE
gui/control-panel v2

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#3830]
The current control panel has a number of challenges:

- new default-enabled tools are not enabled by default for existing players
- it's hard to figure out what is safe/recommended to enable and what isn't
- the tools are categorized by how they're implemented and not by what they do (e.g. some "fix" tools are on the Maintenance page and others are on the "fort" or "autostart" pages)

so, thoughts:

- get rid of default files in `dfhack-config/init`
- add comment lines to generated init files to indicate whether something was *explicitly* disabled
- add a `gui/control-panel --update-init-files` call to the internal dfhack.init file so new default-enabled tools can be added to the generated init files
- reorganize control panel tabs; replace fort, autostart, system, and maintenance categories with bugfix, gameplay, automation, etc. tabs. multiple checkboxes per line for fort/autostart
- don't show "always on" system tools like `buildingplan` -- their overlays can already be independently disabled

**Comment by lethosor** [comment]
I really think a proper config file would give us more stability in the long run. I was under the impression that saving config as code snippets in a `.init` file was a temporary solution to begin with. Reading a config file (even just a JSON file) would give us the ability to more gracefully handle both new options (we can implement "default" logic ourselves) and removed options (i.e. old code floating in `.init` files can break or cause unintended effects; we can define the behavior more reliably in a config parser).

**Comment by myk002** [comment]
From [discord](https://discord.com/channels/793331351645323264/807444467140788254/1170881202396340304):

so let me see if I can characterize the plan here:
1. rewrite the library of control panel commands as a single table with metadata (done)
2. rewrite the UI as per <https://github.com/DFHack/dfhack/issues/3830>, reorganizing the tabs and allowing both current and new fort state to be viewed/modified from the same list (in progress)
3. persist state in json
4. when loaded as a module, load persisted state and reconcile with in-script command library; if old init scripts exist, overwrite them with an empty file (with explanatory comment); if json state does not exist but old init scripts do, load them and migrate their contents to the json format before overwriting them.
5. hook CORE_INITIALIZED and run enabled startup commands
6. hook WORLD_LOADED and run enabled fort commands

I'll have to check to see whether CORE_INITIALIZED is fired before or after init scripts run. which should take precedence? I suspect init scripts should
