### ISSUE TITLE
add unit search/filter to burrows assignment screen

### ISSUE THREAD

**Issue by ab9rf** [DFHack/dfhack#3834]
streamer literally said "dfhack can you help us here" on that screen, so there's at least some interest

**Comment by myk002** [comment]
search is obvious, but what filters would be required on this screen?

There are buttons for assigning all/none civilians and military personnel, but I'm not sure what the use cases are for those buttons. You don't need to assign civilians to burrows when you have civalerts, and when would you ever want to assign your military to a burrow? There's already a "defend burrow" button in the squads panel.

**Comment by ab9rf** [comment]
dunno either. the obvious one would be "all children" but children notoriously ignore burrows

i don't use burrows except for civalerts, so i can't say that i know what use cases there are for filters, so maybe just search is all that is needed

**Comment by myk002** [comment]
Sorting by work detail and by profession might be useful for people who burrow units with their workshops

**Comment by myk002** [comment]
As a data point, what was the streamer attempting to do?

**Comment by ab9rf** [comment]
they had most/all of the units in a burrow for a narrative reason, but they wanted to remove one unit (out of 200) from the burrow for some reason

**Comment by myk002** [comment]
implemented in https://github.com/DFHack/dfhack/pull/3864
