### ISSUE TITLE
Cannot set logistics automelt to melt masterworks

### ISSUE THREAD

**Issue by wintrparkgrl** [DFHack/dfhack#3844]
Melt stockpiles getting filled with masterworks over time. Should have an option for what quality to melt for. If I set a stockpile to accept masterworks and put auto-melt on it, it should melt the masterworks.

**Comment by myk002** [comment]
Fixed in https://github.com/DFHack/dfhack/pull/3848

It should be out in a beta release next week or so, or you can try it now by switching to the DFHack Steam `testing` branch
