### ISSUE TITLE
remove-wear output always gives 0 items even when it works

### ISSUE THREAD

**Issue by superradish** [DFHack/dfhack#3847]
tested and confirmed on items on the ground. haven't checked if items worn are also not counted but i'm fairly sure they are not (but it still works)

**Comment by myk002** [comment]
Are you specifying the `all` parameter? I noticed that if `remove-wear` is run without the `all` parameter, it still outputs as if it checked for worn items and says 0 were updated.

**Comment by superradish** [comment]
doi. nevermind.

**Comment by myk002** [comment]
ok, I'm glad that was it -- I fixed `remove-wear` so the fact that it does nothing without the `all` parameter is clearer in https://github.com/DFHack/scripts/commit/b74a2930dfc80d21295101d1c8a3d3a5fb2eb428
