### ISSUE TITLE
Request: the ability to choose which mechanisms to use when linking levers to buildings

### ISSUE THREAD

**Issue by BeerNTacos** [DFHack/dfhack#3866]
Using DFHack It is possible to select with mechanisms are used except for when mechanisms are being linked. Choosing which mechanisms are to be used should also be an option.

**Comment by myk002** [comment]
this would involve either hooking into the "link lever to building" workflow or providing an alternate one. maybe we could provide a button to choose mechanisms on that panel that appears and shows which mechanisms will be used. Then we can swap in the chosen mechanisms. I haven't looked at the data structures to see how easy this would be to implement, though.

**Comment by myk002** [comment]
Fixed in https://github.com/DFHack/dfhack/pull/3955
