### ISSUE TITLE
`dwarfvet` may be creating jobs with ID -1

### ISSUE THREAD

**Issue by ab9rf** [DFHack/dfhack#3876]
the call to `Jobs::linkIntoWorld` relies on the C++ overload that defaults the second argument to true, but it's not clear to me that the Lua bindings are smart enough to bind the overloads appropriately, resulting in more than one animal rest job being created with a job id of -1, which ultimately causes a number of problematic issues for DF

**Comment by lethosor** [comment]
Possibly related to the issue identified in #3861
