### ISSUE TITLE
option for unforbid to ignore tattered clothes

### ISSUE THREAD

**Issue by astrokitte** [DFHack/dfhack#3967]
Essentially, I would want an option for unforbid to ignore X or XX tattered clothes. 
-prevents dwarves from wasting time hauling the clothes back to a stockpile only for autoclothing/tailor to dump it and a dwarf to have to haul it back to the garbage

**Comment by myk002** [comment]
The option is definitely a good idea, but `tailor` should not be *re-dumping* tattered clothing. In my fort I regularly run `unforbid all` to help clear out my garbage dumps, which currently includes all the tattered clothing. I've never seen the *same* item come back to the dump.

**Comment by astrokitte** [comment]
> The option is definitely a good idea, but `tailor` should not be _re-dumping_ tattered clothing. In my fort I regularly run `unforbid all` to help clear out my garbage dumps, which currently includes all the tattered clothing. I've never seen the _same_ item come back to the dump.

I actually want the tattered clothes to stay forbidden in the garbage dump.

**Comment by myk002** [comment]
understood -- I think ignoring tattered items (not just clothes) is probably a good new default behavior for `unforbid`, controllable with a new option flag. I was just noting that even with the current behavior, there *shouldn't* be an endless dump cycle. I don't know what would be causing that for you.

**Comment by astrokitte** [comment]
I think my problem was I wasn’t setting up my garbage dump correctly. The dwarves were hauling it from the dumping zone back to the refuse stockpile instead of me having my garbage zone on top of a stockpile already. 
or it’s an issue with having multiple dumping zones? I’ll need to experiment to find out exactly where I’ve gone wrong.
