### ISSUE TITLE
Burrow flood fill on surface tiles does not fill/erase the connected walkable tiles or adjacent tree trunks

### ISSUE THREAD

**Issue by xBlackTalonX** [DFHack/dfhack#3992]
Test result: The flood-fill seems to be interrupted by variations in the walkable vegetation and does not expand to tree trunks.
Expected: 
- Vegetation variations should be ignored
  - connected tiles which are walkable/pathable, should be part of the fill
- Tree trunks to be treated like walls
  - tiles adjacent to walkable tiles in the burrow, which can be interacted with and removed, should become part of the fill

**Comment by xBlackTalonX** [comment]
Test case,
Once this is fixed, a burrow created on the surface would not flood into a corner walled off by tree growth (as those tiles are not pathable). And if such burrow has autogrow enabled, cutting down the trees should should cause the burrow to expand into this area that is now pathable (unless it treats it like a cavern? hmm).

**Comment by myk002** [comment]
fixed for the tree trunks themselves. It's proving to be more difficult to include the tiles underneath the tree branches. My in-progress solution is to check the tiles above the target tile, and if there are just tree branches above it until the sky, classify it as "outside'

**Comment by myk002** [comment]
Ok, the solution here I settled on was to treat tree tiles as open space. tiles inherit the properties of the tile above the tree tiles above the current tile. This means that flood fill on the surface will go straight through tree trunks as if they weren't there.

**Comment by xBlackTalonX** [comment]
I'm just curious - if you have time to explain - what about walk-able surface tiles under tree branches makes them different and hard to apply a flood-fill to than an underground cavern/room (without trees)? I would have thought that you were looking at path-able neighbor tiles and am curious how branches above a path-able tile impact the results.

**Comment by myk002** [comment]
it's because the flood fill comparison takes both walkability group *and* inside/outside attributes into account. Outside tiles that happen to be under tree branches are considered "inside", whereas our flood fill needs them to be considered "outside"

**Comment by xBlackTalonX** [comment]
Test passed - and I like this solution to ignore trees.

Just a little worried about it making burrows to unpathable locations. I think tiles blocked by tree trunks is probably tolerable. It's those one tile gaps you're looking at in #3993 that could lead to large areas of the map being part of a burrow that it shouldn't.
