### ISSUE TITLE
Burrow fill excessively adds additional tiles to the burrow beyond down ramps (and misses minable tiles behind up ramps?)

### ISSUE THREAD

**Issue by xBlackTalonX** [DFHack/dfhack#3993]
Test results (tested on grass floor of mountain hills - no vegetation/trees),
- 2D fill reaches all adjacent walkable tiles, plus open space tiles above down ramps **(bug 1) and one additional open space tile adjacent tile to these open spaces above down ramps**
- 3D fill reaches all adjacent walkable tiles plus open space tiles above ramps **(bug 2) and MANY additional open space tiles are included beyond the down ramps** - appears to be tiles which have a floor on the underlying z-level
Expected:
- 2D fill reaches all adjacent walkable tiles, **adjacent walls(bug 3?)**, and open space tiles above down ramps (the ramps are on z-level-1 of course)
  - bug 3, adjacent walls behind ramps, like adjacent mine-able walls in an underground room, should be included? Note that burrow filling an underground room with ramps on one side does include these tiles behind the ramps in the current implementation, but that may(?) because they're adjacent to the walls of that room that also get included. The results should match even when the area isn't walled in though (hills on the surface), right? And due to burrow autogrow functionality, I believe including these walls behind ramps is the correct expected behavior.
- 3D fill reaches all adjacent walkable tiles, adjacent walls, and open space tiles above ramps

Test case: wheelbarrows can carry stone up and down ramps included in a 3D fill created burrow by dwarves assigned to that burrow

Complex test case: apply 3D/2D burrow fill to upper floor in this side view of a 2 z-levels depicting the floor and wall setup:
```
z2: floor__ |||||wall (one open space away from floor and otherwise disconnected from walls around the floors depicted - think surface tower with fortifications one open space tile away from an adjacent to hill and a ramp underneath that open space)
z1: ramp   \_____to tunnel/floor below the above walls
```
Expected: neither 3D nor 2D should include the upper walls (unless they are connected to walls surrounding the upper room? either way they're unable to be interacted with...)

**Bonus Issue** - applying a fill (2D or 3D) to open space above a ramp (i.e. a down ramp), only fills/erases that single tile
- Expected - not sure - options include:
  - a.) all adjacent walkable tiles (same as filling floor adjacent to down ramp)
  - b.) all adjacent open space tiles (same as filling open space)
  - c.) all adjacent down ramps (same as filling wall adjacent to floor or open space)
    - but how would 3D work? presumably similar to 3D filling the wall of a pit which... oh dear, that's [another bonus issue](#3994) (3D fill on the upper wall of a pit mimics 2D behavior)
  - d.) surely not both options a and b

**Comment by xBlackTalonX** [comment]
Created Bug #3994 for the "oh dear, that's another bonus issue" discovered in the original write up of this issue.

**Comment by myk002** [comment]
> and one additional open space tile adjacent tile to these open spaces above down ramps
I spent some time on this one, but while I recognize that it isn't exactly expected behavior, I don't think it's doing any harm, and it would make the algorithm convoluted to try to fix it.

> adjacent walls(bug 3?)
This is intentional, so autogrow can function. it also allows units within the burrow to interact with the walls, i.e. smoothing, engraving, or digging

I believe I got all the other issues you found here. Thank you for testing!

**Comment by xBlackTalonX** [comment]
I'll retest and highlight anything I think is important (I think my summary failed to correctly capture bug 3) as I'm probably in agreement that in practice a few things I mentioned are not important and are outweighed by complexity. Thanks for all the features and fixes! Happy to volunteer some testing.

**Comment by xBlackTalonX** [comment]
Bug 2 - Test Passed

Bug 1 & 3 - Still present (and we discussed in discord).
