### ISSUE TITLE
`forbid` uses the item ALL vector instead of IN_PLAY

### ISSUE THREAD

**Issue by ab9rf** [DFHack/dfhack#4027]
`forbid` appears to scan the `ALL` item vector for most of its operations, which is overly aggressive and could cause problems. it really should only scan, and operate on items reachable from, the `IN_PLAY` vector

**Comment by myk002** [comment]
closing as dup of https://github.com/DFHack/dfhack/issues/4025

**Comment by ab9rf** [comment]
leaving open because this is an instance of the general issue mentioned in #4025 :)

**Comment by myk002** [comment]
Fixed in https://github.com/DFHack/scripts/pull/895
