### ISSUE TITLE
[buildingplan] Make planner UI show the currently selected filter for construction/furniture material

### ISSUE THREAD

**Issue by chdoc** [DFHack/dfhack#4032]
Currently, the planner UI only shows the number of available/missing construction materials/furniture items matching the currently selected material filter, but doesn't show what this filter is. When repeatedly altering between several filters (e.g. when using different stone types for different parts of the fort or different furniture materials for nobles/commoners)

**Comment by myk002** [comment]
The issue here is spacing. I think this might depend on https://github.com/DFHack/dfhack/issues/3300 so the full filter text could show on hover.

**Comment by chdoc** [comment]
Well, I'd be fine with an abridged/incomplete material info for filters that become too long (e.g., "23 rock blocks available" when blocks of different rock types are allowed for construction"). For furniture, I imagine something like: "Statue -> 12 made from green glass available" / "Table -> 8 made from gold needed". 

I suppose the rationale is that people who use permissive filters won't be changing these filters too often. And for people like me, who repeatedly switch between single material filters, this would be good enough. Once #3300 is available, you could add a tooltip to abridged filters showing the full filter definition.
