### ISSUE TITLE
[buildingplan] add hotkey to planner UI to cycle through previously used filters

### ISSUE THREAD

**Issue by chdoc** [DFHack/dfhack#4033]
When repeatedly altering between several filters (e.g. when using different stone types for different parts of the fort or different furniture materials for nobles/commoners), it would be nice if the planner UI kept the history of recently used filters and allowed cycling through them in most-recently used order. (depends on #4032 to really be useful)

**Comment by myk002** [comment]
See https://github.com/DFHack/dfhack/issues/2883 for thoughts on this

**Comment by myk002** [comment]
See some more thoughts on Reddit: https://www.reddit.com/r/dwarffortress/comments/1bvhu48/comment/ky7vdle/?utm_source=share&utm_medium=web2x&context=3
