### ISSUE TITLE
Tailor plugin producing absurd amounts of robes

### ISSUE THREAD

**Issue by DanStus** [DFHack/dfhack#4038]
Tailor continues to create work orders for robes even when number of available robes vastly exceeds fort population
[Save for bug.](https://dffd.bay12games.com/file.php?id=16908) Fort of 150 has 1075 total robes, with tailor creating orders for more

**Comment by ab9rf** [comment]
it's allocating robes for members of the military, which isn't itself a problem

the issue is that it's ignoring the items in stock. it's detecting them during the scan, but not using them as assignable, which i don't understand
