### ISSUE TITLE
RemoteServer shutdowns after the fifth connection.

### ISSUE THREAD

**Issue by cvuchener** [DFHack/dfhack#4040]
"Too many failed accepts, shutting down RemoteServer" after connecting 5 times. Although the fifth connection is still working after that, no new connections will be accepted.

09148698c808d83d9952aff7824b3baf6f52bc3f

In "void ServerMainImpl::threadFn(std::promise<bool> promise, int port)", acceptFail counts all accept calls, not only failed ones.

Even fixing the counter, I'm not sure what is the logic here. Why completely stop the server after five errors?

**Comment by ab9rf** [comment]
see discussion in https://github.com/DFHack/dfhack/pull/3498

**Comment by cvuchener** [comment]
`SocketEwouldblock` does not look like a valid reason for shutting down the server.

**Comment by cvuchener** [comment]
Any information on how to reproduce @orrche's bug? Why isn't the socket blocking?

**Comment by lethosor** [comment]
The server previously shut down after _one_ failed `Accept()` call. The new logic is definitely buggy, though, and needs to be fixed - otherwise the remote API is very limited.

**Comment by cvuchener** [comment]
> The server previously shut down after _one_ failed `Accept()` call.

It did not shut down, it only logged the error. The only way out of the loop was an invalid listen socket.

**Comment by ab9rf** [comment]
after one failed listen call, the socket was (at least sometimes) left in a state where it would no longer accept connections, even if it was still "there"

this may be platform or situationally dependent but we need to handle such possibilities

the fix here is (I think) a one-liner, which i'm working on right now

**Comment by cvuchener** [comment]
There was some confusion with @lethosor, because I was looking at the code before the commit, instead of before the PR.

Proper error handling is not a one-liner.

    /// Extracts the first connection request on the queue of pending
    /// connections and creates a newly connected socket.  Used with
    /// CSocketType CSimpleSocket::SocketTypeTcp.  It is the responsibility of
    /// the caller to delete the returned object when finished.
    ///  @return if successful a pointer to a newly created CActiveSocket object
    ///          will be returned and the internal error condition of the CPassiveSocket
    ///          object will be CPassiveSocket::SocketSuccess.  If an error condition was encountered
    ///          the NULL will be returned and one of the following error conditions will be set:
    ///    CPassiveSocket::SocketEwouldblock, CPassiveSocket::SocketInvalidSocket,
    ///    CPassiveSocket::SocketConnectionAborted, CPassiveSocket::SocketInterrupted
    ///    CPassiveSocket::SocketProtocolError, CPassiveSocket::SocketFirewallError
    virtual CActiveSocket *Accept(void);

 - `CPassiveSocket::SocketEwouldblock`: should not happen on a blocking socket, but @orrche had it, something is wrong but I don't know what.
 - `CPassiveSocket::SocketInvalidSocket`: the listen socket is not longer valid, you can stop now, no need to retry several times.
 - `CPassiveSocket::SocketConnectionAborted`: nothing wrong here, the server should continue, ignoring the connection.
 - `CPassiveSocket::SocketInterrupted`: nothing wrong here, the server should reenter the syscall.
 - `CPassiveSocket::SocketProtocolError`: not sure for this one
 - `CPassiveSocket::SocketFirewallError`: maybe report it, but continue listening.

**Comment by ab9rf** [comment]
regardless of whether the error handling could be more robust or not, the one liner is the failure to reset `acceptFail` after a success. that's the one-line correction that should resolve the instant issue

**Comment by cvuchener** [comment]
`CPassiveSocket::SocketProtocolError` does not exists on Windows. On Linux it can be `EINVAL` or `EPROTO`.

> Linux accept() (and accept4()) passes already-pending network errors on the new socket as an error code from accept().  This behavior differs from other BSD socket implementations.  For reliable operation the application should detect the network errors defined for the protocol after accept() and treat them like EAGAIN by retrying.  In the case of TCP/IP, these are ENETDOWN,  EPROTO,  ENOPROTOOPT, EHOSTDOWN, ENONET, EHOSTUNREACH, EOPNOTSUPP, and ENETUNREACH.

`EPROTO` should be ignored.

> EINVAL Socket is not listening for connections, or addrlen is invalid (e.g., is negative).

but `EINVAL` is bug report worthy error.

I cannot find if clsocket is blocking or not by default. In doubt, calling `setBlocking` may fix orrche's error.

@ab9rf don't bother writing a bad patch. I can send a PR if you want.
