### ISSUE TITLE
`suspendmanager`: handle deadlocks due to obstruction better

### ISSUE THREAD

**Issue by ab9rf** [DFHack/dfhack#4087]
the issue:  consider this scenario:
![image](https://github.com/DFHack/dfhack/assets/1445859/2d00ba1b-c76d-4278-8976-1a26ef6640e1)
the construction in the corner needs to have the boulder cleared before it can proceed, but the game's obstruction-clearing mechanic cannot clear the boulder because none of the four available locations to clear it to are available: two are ineligible open spaces and two contain (suspended) constructions. as a result, the game will suspend the construction with "item blocking site". suspendmanager will then unsuspend the construction, leading to a cycle that generates cancellation spam

this is a deadlock. while in this scenario suspendmanager could allow one of the two adjacent constructions to proceed safely it just leads back to essentially the same scenario. allowing both to proceed would block off the unconstructed corner wall, and the game won't allow the corner wall to be built

the only way to resolve this deadlock is to remove the obstructing boulder. i don't think suspendmanager should be responsible for this; instead, what suspendmanager should do in this situation is detect the deadlock, suspend all involved constructions, notify the player of the deadlock, and wait for the player to do something about it

please note that i have no idea how to go about actually doing this, or even if it's feasible

[related discussion on discord](https://discord.com/channels/793331351645323264/1017471248567124049/1181528853177438258)

**Comment by alterae** [comment]
one related workaround (which might be useful elsewhere as well) would be to add a _player-initiated_ (not automatic) command which detects items that will cause deadlocks like this and designates them for dumping 

if you add deadlock detection warnings maybe even mention the command in them (like, "deadlock detected! you may be able to fix it by running `dump-blocking-items` to designate the item causing the deadlock for dumping" as an example)

i know i would certainly use this bc i tend to run into item-blocking-site spam a lot due to the way i build bedrooms

**Comment by chdoc** [comment]
What about the following algorithm, which does not seem to be too hard to implement:: 

1. When checking/updating the suspend status, also check if there is an item blocking the building site. 
2. Only if this is the case, check that there is a (non-diagonally) neighboring walkable space without a scheduled construction.
3. If not, emit a warning.

If we ever implement "levels of Armokness", even the lowest level might just shift the boulder over to any neighboring suspended constructions.

**Comment by plule** [comment]
I'm looking into implementing @chdoc suggestion, and dorfs can be surprisingly creative sometimes...

![dorf](https://github.com/DFHack/dfhack/assets/630159/9b0804c1-f53a-489a-8410-163f7789f618)

**Comment by myk002** [comment]
note that moving an item that is associated with a job will cancel that job. you *might* be able to modify the job to look in the new location, and maybe also have to adjust the pathing of the unit that is en route to pick it up.
