### ISSUE TITLE
`autobutcher`: Selling animals to caravan does not deduct count from autobutcher.

### ISSUE THREAD

**Issue by KevinMAmaral** [DFHack/dfhack#4095]
Example provided below with Giant Bats.
![image](https://github.com/DFHack/dfhack/assets/1851332/b0d23cb4-879c-41da-a0b4-91573d04901d)
![image](https://github.com/DFHack/dfhack/assets/1851332/d6a63a02-12aa-47b3-b534-09559b5d29aa)

Shows 1/0 male adults and 1 sent for butchering.
There exists no giant bat in the livestock list.

**Comment by myk002** [comment]
I am unable to reproduce this issue by selling a water buffalo to the caravan. After the trade, I see:
![image](https://github.com/DFHack/dfhack/assets/977482/53643c86-85a0-4c7e-b63a-32080130622a)
that is, all zeroes for the water buffalo line

**Comment by myk002** [comment]
Do you have the savegame where you were seeing this issue? I'd like to take a look at the properties of the giant bat

**Comment by KevinMAmaral** [comment]
> Do you have the savegame where you were seeing this issue? I'd like to take a look at the properties of the giant bat

The for was long-since retired. I can see about reproducing it and then provide a save file. I still play with autobutcher on.
One thing to note is that my watch interval was 1200 ticks, which would have a higher chance of a race condition if one were possible.
Another thing to note is that the Giant Bats were caught in Cages and sold in Cages. They weren't animals I purchased, embarked with, or raised.

**Comment by KevinMAmaral** [comment]
Also, the bat was likely marked for slaughter before it was sold, don't know if that affected it.

**Comment by myk002** [comment]
the specific bit I'd be looking for is if the giant bat had the `merchant` flag after being sold. If it did, then it totally should have been excluded from the counts. If it didn't I'd like to know why.

**Comment by KevinMAmaral** [comment]
Could it have been counted before it was sold and then never decremented? I'm not going to be able to attempt to replicate it until later tonight

**Comment by myk002** [comment]
All counts are "live", so it should be accurate

**Comment by myk002** [comment]
closing this for now, but please reopen if you discover a repeatable case!
