### ISSUE TITLE
autochop request

### ISSUE THREAD

**Issue by SivartMcDorf** [DFHack/dfhack#4097]
I like how autochop works for the most part, but it would be nice if we could designate tree types we want to cut down.  That way if you are in say a good/evil biome you could specify Feather/Glumprong trees only(minimizing time on surface in evil biome is important).  Or if you only want certain fruit trees you could select all the other trees.  This could be a simple toggle list for a map or burrow.  This would also aid in gathering bloodthorn and minimizing time in the caverns.

**Comment by myk002** [comment]
This is a good idea, but is already tracked in https://github.com/DFHack/dfhack/issues/986
