### ISSUE TITLE
Update embark-skills

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#4104]
as a CLI-only tool, it shouldn't be too bad to update for v50.

**Comment by Izaan17** [comment]
What is embark-skills? I want to help out. Please give me more information.

**Comment by myk002** [comment]
It's a tool that lets you adjust the skills of your starting dwarves when configuring them on the embark preparation screen.

Docs are here: https://docs.dfhack.org/en/stable/docs/tools/embark-skills.html#embark-skills
and existing code is here: https://github.com/DFHack/scripts/blob/master/embark-skills.lua

It's a short script, and fairly easy to understand. I believe the data structure that it interacts with has changed (but maybe not -- I really haven't checked).

If you'd like to try updating it, I suggest:

1. Embark carefully for a new fort and get to the screen where you can assign skills to your starting dwarves
2. Run `gui/gm-editor scr` to load the data structure for the current viewscreen
3. Play with the values in the structure to see how it changes things in the UI
4. Read the existing script and see if you can manually make the changes that you think it's trying to make
5. Update the script (if needed) with the knowledge you gained from the above steps

**Comment by LightHardt** [comment]
I have opened a pull request on this issue  https://github.com/DFHack/scripts/pull/935.
