### ISSUE TITLE
confirmation prompt enable/disable isn't being restored correctly

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#4107]
according to https://discord.com/channels/793331351645323264/807444467140788254/1189363664214577204

**Comment by lethosor** [comment]
Was there actually a bug here? I thought that was just a question. I don't believe confirm state ever persisted between DF sessions, unless that feature was added after v50.

**Comment by myk002** [comment]
the state persistence that was added for v50 was very weird for `confirm`. it was shared between the plugin and `gui/confirm`, and it just never quite worked right.
