### ISSUE TITLE
ls does not list scripts outside of hack/scripts

### ISSUE THREAD

**Issue by expwnent** [DFHack/dfhack#412]
It should do that and maybe also note when that script overrides a script in hack/scripts. The fix will involve Core.cpp if someone gets to it before I do.

**Comment by PeridexisErrant** [comment]
Just to make the implementation a little clearer:  I'd propose a new section at the end of `ls` output, for scripts in `raw/scripts` (and other searched locations).  Then any script in `hack/scripts` which is overridden could be listed in red text.  I think that would be enough information - there's not really any room for timestamps or diffs, so those could be a separate command.
