### ISSUE TITLE
Request for 1-tile tomb zone mass designation

### ISSUE THREAD

**Issue by ong-yinggao98** [DFHack/dfhack#4122]
As of now DF v50 lacks a tomb equivalent to a dorm where you can have multiple coffins in them. Manually making each coffin tile its own zone is asking for carpal tunnel and enclosing each coffin in a room to mass paint is viable, but uses a lot more space. A way to paint over an a room with multiple coffins that creates a tomb zone for each would be a helpful tool.

**Comment by myk002** [comment]
The tool for this is `burial`. You can run it from `gui/launcher`. Does it meet your needs?

**Comment by ong-yinggao98** [comment]
Ah, mb, didn't notice the change in documentation.
