### ISSUE TITLE
tailor, but for armor

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#4125]
from [reddit](https://www.reddit.com/r/dwarffortress/comments/18w6g22/comment/kfwqpls/?utm_source=share&utm_medium=web2x&context=3):

It'd be sick if we could get an armorer version of the tailor script, to automatically queue up job orders for missing uniform pieces. It's a pain when I have soldiers that don't fit normal sized armor to manually make it for them

**Comment by ab9rf** [comment]
dup of #3626
