### ISSUE TITLE
Liquid generation from source tiles doesn't persist between loads

### ISSUE THREAD

**Issue by Heneman** [DFHack/dfhack#4131]
The locations persist but the generation of liquids ceases on loading a saved game that contains added source tiles.

Steps to recreate:
* Place a source tile with any specified volume (*/7)
* Save
* Quit
* Reload last save
* `source list` shows locations remain in dfhack but they no longer produce (or drain) liquid

**Comment by myk002** [comment]
`source` clearly needs some updates.
- It doesn't persist the list on disk, so if you quit the game and restart it's just gone
- It doesn't clear the configuration on game unload, so you end up with old data in the next loaded fort (which is what you saw)
- It doesn't reinstate the liquid level modification timers on load

All this is fairly simple to fix -- the architecture can be copied from other similar tools like `emigration`

**Comment by Heneman** [comment]
I took a peek and I could take a stab at moving `main()` over to `eventloop()`, I'm guessing I can test by copying my updates to the mods folder of DF?

**Comment by myk002** [comment]
You *can* test by adding a mod directory, creating an info.txt file, etc. but there are simpler options.

It's more common for devs to have a git repo so you can later start a pull request for your changes. You'd add your git repo to your `dfhack-config/script-paths.txt` file. Here's mine:

```
~/.local/share/Steam/steamapps/common/Dwarf Fortress] $ cat dfhack-config/script-paths.txt 
# Add additional script search paths here
# Blank lines and lines that start with "#" will be ignored
# Paths preceded by "+" will be searched first
# Paths preceded by "-" will be searched after the default paths
+/home/myk/src/dfhack-scripts
```

if that's too much trouble, then you can test by overwriting the file in `hack/scripts/source.lua`.
