### ISSUE TITLE
[Request] Filter for juvenile/adults for creature filters

### ISSUE THREAD

**Issue by ong-yinggao98** [DFHack/dfhack#4143]
An additional filter for age of creatures besides the existing filters for pasture location and training level would be helpful for setting up nurseries.

One example use case would be caging up all newly hatched poults to avoid them running your FPS to the ground

**Comment by myk002** [comment]
This is doable -- a cycle hotkey that has "Juveniles and adults", "Juveniles only", and "Adults only" options would work, I think. The reason I didn't add this before is because thought it would be easy enough to search for "poult", but I can see how it would be useful if you want juveniles across many races.

**Comment by myk002** [comment]
How's this?
![image](https://github.com/DFHack/dfhack/assets/977482/ac5a694a-3372-4a6e-85fc-c3af3ebe7e24)

**Comment by ong-yinggao98** [comment]
It looks great, thank you!

> How's this? ![image](https://private-user-images.githubusercontent.com/977482/294725141-ac5a694a-3372-4a6e-85fc-c3af3ebe7e24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2MTA0NzQsIm5iZiI6MTcwNDYxMDE3NCwicGF0aCI6Ii85Nzc0ODIvMjk0NzI1MTQxLWFjNWE2OTRhLTMzNzItNGE2ZS04NWZjLWMzYWYzZWJlN2UyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwN1QwNjQ5MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOGQwYjE0NzAzYzliZmQ0ZWI1NmE2MzJhOTJjNTZkMTFmZmI2YzVkZjgyNmI2ODZmZGVlOTIxZDNiM2UxYTEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.92pE4lJKgIx2cajd9cJLREOZDKrj3S3XiuOOiBUR0Xo)
