### ISSUE TITLE
Include and update spawn.lua

### ISSUE THREAD

**Issue by expwnent** [DFHack/dfhack#415]
https://gist.github.com/Rumrusher/f4d0ba18ba6868d38221

**Comment by Devduweb** [comment]
Hello,

To mirror what I reported here:
http://www.bay12forums.com/smf/index.php?topic=139553.msg5989274#msg5989274

A spawned unit becomes hostile after saving and loading the game, setting population_id does not help. On the other hand, creating a nemesis does not crash the game anymore.

As a suggestion, perhaps we can make spawnunit a library to allow modders to better fine tune their units? Here's an example with an option to spawn several units at once, returning an array of the created units:
https://gist.github.com/Devduweb/9299841e7169445f8cce

I can provide a wrapper script for terminal call if you wish.

**Comment by PeridexisErrant** [comment]
Closed by 7b917303, and subsequent work in the develop branch?

**Comment by expwnent** [comment]
Yeah, this is obsolete.
