### ISSUE TITLE
Reproduction case for channel-safely crash

### ISSUE THREAD

**Issue by IdahoEv** [DFHack/dfhack#4157]
The attached save reliably reproduces a crash related to channel-safely, in the current steam version of the game, at least on my machine.   I will try to find another computer to test it on tomorrow and see if it happens there as well. 

### Reproduction instructions:

1. Load the attached save
2. 'enable channel-safely' in DFHack
3. unpause the game

For me, this reliably causes a crash back to the desktop within two minutes, often within a few seconds. 

### Version and System Info

DFHack 50.11-r5rc1
Dwarf Fortress (Steam) 50.11 (build 12327894)
MSI GL65 Leopard
Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz   2.59 GHz
16GB RAM
Windows 11 Home Ver: 22H2 (build 22621.3007)

### Save File Link

https://drive.google.com/file/d/1_K9vCo_-8fk1F9jLrFyBLzpcVVYj1IkM/view?usp=drive_link

**Comment by myk002** [comment]
stack trace:
```
#2  0x00007ffff797d9ed in DFHack::Job::removeJob (job=job@entry=0x7fff90cc58f0)
    at /home/myk/src/dfhack/library/modules/Job.cpp:397
#3  0x00007ffff34dab40 in cancel_job (job=0x7fff90cc58f0)
    at /home/myk/src/dfhack/plugins/channel-safely/include/inlines.h:200
```
job canceling has been problematic for a while. I'll see if we can address this. If not, we might have to remove `channel-safely` entirely for now

**Comment by cppcooper** [comment]
It was a silly design flaw. i.e. `removeJob` being called from a `manageJobStartedEvent` call stack which of course means the job list is mid iteration when a job is removed from the list.

I've made a fix. I'll be writing a better fix. Then I'll open a PR and link this.
