### ISSUE TITLE
getplants causes a hard crash

### ISSUE THREAD

**Issue by SolarizedPhoenix** [DFHack/dfhack#4171]
the getplants command is causing my game to crash. Even just running "getplants" alone, with no flags, causes a crash. So far, no other command from DFHack has caused this issue, so I'm assuming its the command itself.

Zip containing both mods and save. Using the steam release of DF.

https://cdn.discordapp.com/attachments/812655314205540352/1196020039829172264/Dwarf_Fortress.zip?ex=65b61b76&is=65a3a676&hm=ec0a481ab909d24013a0b4be38c2a0565869a8159d4eebe9010082e9981a60f2&

**Comment by myk002** [comment]
I reproduced the crash with your save. The issue is definitely caused by mod-added plants. I'm digging deeper to see what we can do to behave better in this situation
