### ISSUE TITLE
Feature Request: Pit/Pond/Pasture assignment should show distance to each creature from the zone

### ISSUE THREAD

**Issue by TheBigS** [DFHack/dfhack#4181]
**Problem Statement:**
I'm having a problem in my fort where I have a ton of cage traps that keep trapping invaders. So I made a pit for "disposing" of the creature (drop a ton of z-levels) and a stock pile for storing prisoners waiting to be dropped. I then got distracted with an engineering project and looked up and I have like 30+ creatures in the stock pile and more strewn about in cages that haven't been moved to the stock pile yet. In my caverns I also have creatures that are in a cage traps that are inaccessible (locked doors). I'd like to reclaim the materials/weapons etc. from the invaders so I want to just drop them in the pit. The problem is when I go into the Assignment dialogue I see a ton of goblins all with really hard to remember names. So I end up going to the stockpile near the pit and remembering one name at a time then finding that creature in the assignment menu and assigning it so that goblin gets dropped.

**Proposed Solution:**
It would be much simpler if I could just see a distance for each creature on the assignment screen. I could then select all of the creatures that are currently next to the pit and assign them. I feel like distance is generally useful for things like choosing which material to build something out of, so it will be similarly useful when deciding which creature to assign where.

I've never contributed to DFHack, but I am a developer. I've played around with LUA before and have C++ experience, I'm happy to attempt to add this and do a pull request if someone can point me in the right direction. In my initial search of where this feature should be added I found `plugins/lua/zone.lua` but I got bogged down in trying to figure out how to use the values in the `df-structure/df.units.xml` to get the unit positions.

**Comment by myk002** [comment]
This is an excellent choice for a first contribution! If you join the DFHack Discord server (https://dfhack.org/discord) I can help you get oriented quicker. Also feel free to start a draft PR if you'd like feedback on in-progress code.

In this case, the API you're looking for is `dfhack.units.getPosition(unit)`, documented here: https://docs.dfhack.org/en/latest/docs/dev/Lua%20API.html#units-module

You'll need to add the data to the list and implement sorting, but that's just copy-pasting the existing patterns. I'll leave it up to you for whether you want to find the distance from the center of the zone or from the closest edge : P

**Comment by myk002** [comment]
I'm sorry -- I was in need of this feature as well, so I got it implemented, forgetting that you had expressed interest. If you're still interested in contributing, there are many many other features that need attention!
