### ISSUE TITLE
Lever linking failure w/buildingplan mechanism selection -- repro case 

### ISSUE THREAD

**Issue by IdahoEv** [DFHack/dfhack#4197]
I'm occasionally seeing an issue where, when using the buildingplan mechanism selector for linking a lever, clicking the link target does not actually queue up a "link building" task for the lever.  There's no error or crash, it just closes the dialog without creating a task.  Behavior seems to be sensitive to which specific mechanism is selected.

### Reproduction steps:

1. Load the attached save
2. Enable buildingplan if it's not enabled already
3. Click the bauxite lever in the middle of the screen
4. Click "Link Lever".  It should pre-select two malachite mechanisms
5. Click the rough cobaltite bridge just north of the lever
6. **Observe the link building job in the lever task queue**
7. Cancel the task and click "Link Lever" again
8. This time, tap 'g' to change the lever's mechanism to Magma-safe.  It should select a steel mechanism
9. Click the cobaltite bridge again
10. **Observe that the link building job is NOT in the lever task queue.  Queue is empty.**

Contrast between #6 and #10 is the bug.  

### Version and System Info
DFHack 50.11-r5rc1
Dwarf Fortress (Steam) 50.11 (build 12327894)
MSI GL65 Leopard
Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz 2.59 GHz
16GB RAM
Windows 11 Home Ver: 22H2 (build 22621.3007)

### Save File Link
https://drive.google.com/file/d/1jNCruUC0GxWOD0_euGL6DaGJ1e_oI7id/view?usp=drive_link

**Comment by myk002** [comment]
discussion on Discord: https://discord.com/channels/793331351645323264/807444467140788254/1198041927153631313
