### ISSUE TITLE
Center dragging shapes in ```gui/design``` lag behind by a tile.

### ISSUE THREAD

**Issue by MagistrumT-T** [DFHack/dfhack#4202]
Center dragging shapes will display and commit to the tile the mouse was right before it entered the current tile, making it very frustrating to place anything with center dragging. Upon committing it snaps to the correct position under the mouse.

https://github.com/DFHack/dfhack/assets/136035179/4653d180-c796-4b5c-902c-933eaca114cb

**Comment by myk002** [comment]
This will get closed when we merge the PR
