### ISSUE TITLE
dig-now leaves behind ramps that it shouldn't and removes ramps that it should have left.

### ISSUE THREAD

**Issue by MagistrumT-T** [DFHack/dfhack#4213]
dig-now does not remove unusable ramps positioned diagonally from a dig designation, and removes usable diagonal ramps.

**Comment by myk002** [comment]
I think I might have been trying to mimic vanilla behavior for when an area with existing ramps is being dug out. I could have done it wrong, though. Before fixing this, it would be good to double check what the vanilla behavior is here

**Comment by MagistrumT-T** [comment]
I vividly remember vanilla dig and ramp designations leaving behind ramps back in the day? Maybe? Possibly? Anyways.

Current vanilla behavior is to remove all adjacent unusable ramps in all designation types, except for the designated ramp itself if it was a ramp designation. Looking a bit it seems our current implementation only looks at orthogonally adjacent tiles, so we probably only need to add the checks for the diagonally adjacent.
