### ISSUE TITLE
Crash when pressing hotkey at some interface

### ISSUE THREAD

**Issue by tuntematonjr** [DFHack/dfhack#4218]
Version:50.11-r5

When i press T (hotkey to open Tasks), when having Justice, Nobles or administators or Work orders interface open -> game crashes.
Tested that this does not happen, when DFHack is uninstalled.

Mods what i have.
![20240127104808_1](https://github.com/DFHack/dfhack/assets/15962001/b49bcf4e-1ebf-4fc6-8ba0-bda2b4f495c2)

**Comment by myk002** [comment]
It took a few toggles between nobles and tasks, but I was able to reproduce this. Looking into it.

**Comment by myk002** [comment]
Fix will be up on the Steam `testing` branch shortly, if you'd like to have a fixed build ASAP. Thank you for bringing this to our attention!
