### ISSUE TITLE
"No job can be found from what is selected in the UI." Spam with Trade Depot selected

### ISSUE THREAD

**Issue by Bumber64** [DFHack/dfhack#4241]
Something's spamming "No job can be found from what is selected in the UI." errors in the DFHack console when a trade depot building is selected. This comes from `Gui::getSelectedJob` with `bool quiet = false`, though I haven't checked where this is being called from.

**Comment by myk002** [comment]
I fixed an issue like this for `suspendmanager` a few days ago. Could you try subscribing to the `testing` build on Steam and seeing if it's fixed for you?

**Comment by Bumber64** [comment]
Looks like that fixed it.
