### ISSUE TITLE
Please add a tool to save/restore custom work details.

### ISSUE THREAD

**Issue by A-CuriousCat** [DFHack/dfhack#4253]
This was originally [suggested by Button](http://www.bay12forums.com/smf/index.php?topic=182380.0) in the DF suggestions forum.  I think it would be a good idea for DFHack to include an equivalent tool that can be used until if/when Button’s suggestion gets implemented.

**Comment by Jhenmhor** [comment]
it already exist you can see it in the bottom of the work orders window

**Comment by ab9rf** [comment]
the main reason we're not doing anything with work details at this time is that any changes we make to the work details screen via dfhack have no effect until and unless the player goes into the work detail screen and changes something on that screen to cause it to recompute labor assignments. at present there is no reliable way for us to trigger the game to recompute labor assignments based on work detail settings, and the function for doing so is complex enough that simulating it in our own code is impractical

it's probably too late for us to ask for something to be added to 50.12 to support this, but obviously this should go on the list of features to ask bay12 for in future DF releases

**Comment by cvuchener** [comment]
I'm implementing this feature in an external tool. It may be a good idea to use the same format. I'm currently using json like [this](https://github.com/cvuchener/df-workdetailtest/blob/a9a67419ef5920e27ba0f14c416def1fb2fc21a9/data/workdetails/Default%20Work%20Details.json). It can be a single object or an array of such object. Would this work for DFHack?

The labor update function is not that complex. I implemented it as mentioned in https://github.com/DFHack/dfhack/discussions/2901#discussioncomment-7654249 (it's noble/admin position that is too complex for me) (code has moved [there](https://github.com/cvuchener/dfhack-plugin-workdetailtest/blob/18698ffed156b88b3b6e480f46c9a16e1f3b9061/Labor.cpp#L64)).

**Comment by ab9rf** [comment]
i'm not comfortable relying on an external simulation of the assignment algorithm because i've had enough recent discussions with putnam to reasonably believe that the algorithm is likely to change in the relatively near future, which will force us to play catchup. i think we're better served by lobbying for a reliable mechanic for requesting recomputation from the game itself than jumping onto that particular treadmill

i'm not opposed to someone who wants to implement a simulation, but i'm not going to prioritize my time toward such an effort

**Comment by myk002** [comment]
My understanding about this feature request was it was for saving the definition of custom work details, not the assignment of them. I think this can be done similarly to how we're saving/restoring difficulty settings and standing orders.

**Comment by cvuchener** [comment]
Even with no one assigned, a work detail set to something different from "Everybody does this" will affect labors.
