### ISSUE TITLE
Suggestion: Reveal Layer Command

### ISSUE THREAD

**Issue by AnotherOddity** [DFHack/dfhack#4266]
A very useful ability would be to reveal just the entire current z-level, specifically because it'd allow mining of an aquifer layer unpaused without 'damp stone detected' cancellations, without spoiling the discovery of caverns or fun (unless the Z-level you are revealing is a cavern level, of course).

**Comment by myk002** [comment]
I have a different solution in progress for this. Instead of revealing the layer, you can mark the dig designations as "damp dig" and DFHack will ensure that designations will not be canceled due to dampness. Would that be an acceptable alternative?

**Comment by AnotherOddity** [comment]
That is a good alternative solution, sorry didn't see the reply until now.

Looks like it might've been added today though, which is cool!
