### ISSUE TITLE
`exportlegends` uses incorrect name for each main category (everything is `<landmasses>`)

### ISSUE THREAD

**Issue by im-coooding** [DFHack/dfhack#4283]
Every category gets exported as `<landmasses>` instead of what it's supposed to be (`<mountain_peaks>`, `<regions>`, and so forth).

`local function make_chunk(name, vector, fn)`
`    num_total = num_total + #vector`
`    return {`
`        name='landmasses',`   <--- should be `name=name,`
`        vector=vector,`
`        fn=fn,`
`    }`
`end`

It's at this line: https://github.com/DFHack/scripts/blob/e071dc2cb1375c40539c4be17ea3c5cb5a5aa496/exportlegends.lua#L85

(I'm not very familiar with git or github so please pardon my extremely janky "pull request"...)

&nbsp;

This is what causes legends browser to crash when loading legends_plus, as reported here:
robertjanetzko/LegendsBrowser2#18

**Comment by myk002** [comment]
that was my doing with a recent change. thank you for bringing this up!
