### ISSUE TITLE
Idea: Automatically queue work orders with buildingplan

### ISSUE THREAD

**Issue by brnhensley** [DFHack/dfhack#4291]
I'm not sure if this is possible, but ideally I'd like to able to use buildingplan/planning mode to queue work orders for the required object. Currently this is how the feature works:
> Buildingplan will periodically scan for appropriate items and attach them to the planned building. Once all items are attached, the construction job will be unsuspended and a dwarf will come and build the building. 

I'm suggesting when it runs this periodic scan it queues work orders for the items it cannot find. For example if you use planning mode to set 20 stone doors in the fort the next time the scan runs and you have no doors it queues an order for 20 stone doors.

For items with quality limitations, like if you use buildingplan to set 20 Masterwork doors, it could continue to queue door orders until enough masterworks have been created (queue 20 doors, get two masterwork, queue 18 more doors on next check, repeat).

This was all you'd need to do if make sure you have workshops and raw materials available and and you can go about designing your fort.

**Comment by myk002** [comment]
Ref: https://github.com/DFHack/dfhack/issues/4034
Ref: https://github.com/DFHack/dfhack/issues/2883

**Comment by myk002** [comment]
Closing as dup of #2883
