### ISSUE TITLE
Work orders not sorteable any longer.

### ISSUE THREAD

**Issue by phooenixdassmatte** [DFHack/dfhack#4306]
I just put in my 67th work order and it was 2 orders to smelt some ore, so when i pressed "sort" i would think they would end up among the other "smelt blabla" like they did before when i pressed sort but it didn't. I took away those 2 and one more so i had 64 orders and manually shuffled some orders around to "unsort" it and pressed sort again but it didn't sort.

Minor issue perhaps but i let you be the judge of that, could be more under the hood maybe.

EDIT: It's mixed with workshop orders and global orders.

**Comment by myk002** [comment]
`orders sort` sorts by order *frequency* and is otherwise a stable sort (that is, it doesn't change the relative order of items that are already sorted by frequency). The reason it doesn't sort by name is because orders may already be grouped by "theme" and that might not be alphabetical.

The primary reason for `orders sort` is so orders don't get "stuck" and never complete, which can happen if daily orders are above one-time orders in the list.

I agree that more work would be welcome here. This is a terrible, no good, rotten screen to work with, both from a player's perspective and from a data perspective. Putnam recognizes this, and is planning changes. If those changes don't happen quickly enough, DFHack could create an alternate interface, but it would need to be written from scratch. The DF data model for this screen prevents otherwise useful sorting and filtering.

**Comment by phooenixdassmatte** [comment]
> `orders sort` sorts by order _frequency_ and is otherwise a stable sort (that is, it doesn't change the relative order of items that are already sorted by frequency). The reason it doesn't sort by name is because orders may already be grouped by "theme" and that might not be alphabetical.
> 
> The primary reason for `orders sort` is so orders don't get "stuck" and never complete, which can happen if daily orders are above one-time orders in the list.
> 
> I agree that more work would be welcome here. This is a terrible, no good, rotten screen to work with, both from a player's perspective and from a data perspective. Putnam recognizes this, and is planning changes. If those changes don't happen quickly enough, DFHack could create an alternate interface, but it would need to be written from scratch. The DF data model for this screen prevents otherwise useful sorting and filtering.

Ah i see i must've misinterpreted how it sorted and what you're telling makes sense.

Yeah i've read here about plans for a better work order screen. Like someone said a way to make folders to clean it up would be nice so you can section up your industry, only that would be a great improvement. I may just not know how to, or i've been using the work order wrong but in the steam version i keep getting work orders to fail because the condition is green even if i don't actually have those items. Don't know if this is a bug or if i'm just doing something wrong. I've never had these much job-failing errors when playing on the non-steam version so i think there is something or several things not working right.


As an example that something is wrong (perhaps multiple problems, or just me, and this is a little sidetopic): I had setup 4 workshops with workshop orders to create 10 mudbricks if mudbricks < 2600, and if mudstone > 40. Stonecutting set to "everyone does this" so idle dwarves could go and make some bricks if they wanted to.

I counted the amount of bricks in a bin in the stockpile and counted to 26 in the fullest one so i assumed that was around the max a bin could store (according to the wiki they should store 12), but somehow they wouldn't fill up the bins, some have 10, some 6, some 14 etc... so they continued to massproduce mudbricks and under every workshop there were 100+ mudbricks on the floor never being hauled to a bin (i have 200+ dwarves so there is not that they don't have time, alot of loitering around).

But they didn't count towards the total when laying on the ground so they kept massproduce, and i would think that they would fill up the bins to the same amount as the one with the most bin, in every one. Doesn't work to link the workshop to output to the stockpile either. Very strange...well now i have like 3400 mudbricks x)

Anyway, i would assume that it's a smart move to wait a while before trying to mess around with it.
