### ISSUE TITLE
Traps built with build-now don't seem to trigger

### ISSUE THREAD

**Issue by Heneman** [DFHack/dfhack#4309]
!Spoilers! 

Preface: Messing around with dig-now, build-now, and [the Cheat Workshop](https://steamcommunity.com/workshop/filedetails/?id=2901299564) mod. This is more of a troubleshooting since I can't quite tell if it's a `build-now` issue or not.

I started a new embark and a dragon was a resident of the area. I immediately built some cheat workshops and adamantine mechanisms and cages. Once those were finished, I surrounded the dragon with over 100 adamantine cage traps. I started the clock and watch for months as he treated those tiles as a dance floor, never triggering the traps to spring.

AFAIK, dragon's don't have trapavoid, so I'm wondering if there's something missing in either the cheated materials or the `build-now` functionality. The materials created with the Cheat Workshop recipes don't have any Quality, I'm wondering if that's a component required for functional traps.

**Comment by myk002** [comment]
Were the traps loaded with cages?

**Comment by Heneman** [comment]
Ahhhhh they were not! There's some dwarven intervention that needs to happen similar to linking levers then it sounds like?

**Comment by Heneman** [comment]
Yep, looks like once the trap was built some dorfs had to bring the cages out to the trap, but I had them trapped in a burrow :upside_down_face:
