### ISSUE TITLE
autoclay

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#4363]
since gathering clay cannot be controlled with manager orders (IIRC)

**Comment by quietust** [comment]
The "Collect Clay" job shows up in the work order editor just fine for me, and you can even set conditions regarding "clay stones" (though it doesn't seem to populate those conditions by default).

**Comment by ab9rf** [comment]
> since gathering clay cannot be controlled with manager orders (IIRC)

i've been using manager orders to manage clay since manager orders were added to the game

the strategy described by quietust has always worked for me

**Comment by myk002** [comment]
ok, this might be player confusion then.
