### ISSUE TITLE
`fix/stuck-worship` seems to ignore monster hunters

### ISSUE THREAD

**Issue by im-coooding** [DFHack/dfhack#4367]
I've made sure the script is enabled and can see in the log that it's running periodically.

While monster hunters show up in the citizen list on the units screen in game, they don't seem to be considered actual citizens of the fort or members of the site government. Looking at the code for `dfhack.units.getCitizens` that `fix/stuck-worship` uses to get its list of units, I'm guessing this is why it doesn't work for them.

Since monster hunters also use temples and have a need to pray like regular citizens do, it would be great if the script could be made to work for them as well.

I currently have a monster hunter desperately trying and failing to pray to two of his deities, and don't really know how to help the guy.

This issue might apply to other long term residents as well, but I don't have any at the moment so can't confirm this.

**Comment by myk002** [comment]
Identifying non-citizen long-term residents is a longstanding problem that we don't have a good solution for. I'll look into this again a bit, but this is a harder problem than it has any right to be

**Comment by myk002** [comment]
ok, got it. should be fixed soon.
