### ISSUE TITLE
Classify Roosters as Egg Layers?

### ISSUE THREAD

**Issue by fatguy1121** [DFHack/dfhack#4387]
Probably not a bug, but should roosters be classified as egg layers to keep them with hens? Are there any other female/male variants that are classified separately?

**Comment by myk002** [comment]
Where are they being classified as non-egg layers? I see them both identified as egg layers in the DFHack assignment screen:
![image](https://github.com/DFHack/dfhack/assets/977482/ef1d4fa8-7f7a-4549-a3bb-9e87f2a44c16)

**Comment by fatguy1121** [comment]
Disregard, my roosters are pets. oof.
