### ISSUE TITLE
Another Addition to Notification Settings

### ISSUE THREAD

**Issue by WhompumStompum** [DFHack/dfhack#4390]
It might be cool if extremely rare or dangerous animal got its own notification in the notification window.  I know I miss a lot that show up for a while and walk away.  I am thinking of anything the players might want to see and could easily be missed.  Examples might be unicorns, cave dragons, sea monsters, yeti, and probably anything from the fanciful page.  Giant cave spiders might also make the list because of how deadly they are.  Definitely, falls under a minor nice to have, but I thought I would share since you already have the notification window.

**Comment by myk002** [comment]
This could be added as an optional (not on by default) notification type that you can turn on in `gui/notify`. It could give a short summary of the wildlife on the map
