### ISSUE TITLE
Quick switch favorites for buildingplan filters 

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#4444]
Selectable from the main panel

**Comment by myk002** [comment]
@chdoc can I assign this one to you?

**Comment by chdoc** [comment]
I'm not sure. I certainly still want this feature.

However, the first time round, I balked when trying to understand the internals of `buildingplan`. I have now spent about another half-hour, and I don't feel like I am getting any closer to understanding the "design". All I see is state everywhere and business logic closely intertwined with Lua wrapping. So I definitely do not feel comfortable touching that code.
