### ISSUE TITLE
Exclude established temples not excluding large temples 

### ISSUE THREAD

**Issue by WhompumStompum** [DFHack/dfhack#4457]
Exclude established temples not excluding large temples but including the sub groups in yellow.  This has persisted for weeks across forts and worlds.  I have many mods so not surprised if that causes issues.  Included video of issue.

[Backup.zip](https://github.com/DFHack/dfhack/files/14899054/Backup.zip)
[VIdeo of problem.zip](https://github.com/DFHack/dfhack/files/14899057/VIdeo.of.problem.zip)

Link to mods folder:
https://drive.google.com/file/d/1XnRRuRCNiTKrKduUEcyLyLNDJL7HQk5a/view?usp=sharing

**Comment by myk002** [comment]
closing since we determined the issue was due to a malformed mod (advanced agriculture)
