### ISSUE TITLE
[Bug] Autoclothing making clothing sized for wagons?

### ISSUE THREAD

**Issue by master-spike** [DFHack/dfhack#4465]
Here is an example of running the autoclothing command on my current fort (mountainhome, 1st granite early spring - no wagons *currently* on map)

![image](https://github.com/DFHack/dfhack/assets/42660765/796948cc-25d7-44d3-be1d-0006d4a42bc9)

Here is an example of a shoe that was made sized for wagons. 

![image](https://github.com/DFHack/dfhack/assets/42660765/6cdcdc56-4a8f-475d-bc53-b7f191034b65)

It cannot be done manually:

![image](https://github.com/DFHack/dfhack/assets/42660765/b1b60609-f1a5-4d84-8c5e-1e831effad99)

**Comment by master-spike** [comment]
I'll play my fort till humans arrive in summer to see if the wagons being on map counts towards the "we need clothing for X wagons" count.

**Comment by chdoc** [comment]
@myk002 is this related to #4471 and fixed by #4472
