### ISSUE TITLE
support chainloading of localization library

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#4469]
as per discussion here: https://discord.com/channels/329272032778780672/1229454017017544774

need to come up with naming convention/design for determining order of chain loaded libraries

**Comment by myk002** [comment]
Example dfhooks modification: https://discord.com/channels/329272032778780672/1229454017017544774/1229769374039150632

**Comment by Liriel-666** [comment]
please make it possible for these users that need the translation and want dfhack to use too

**Comment by myk002** [comment]
@shevernitskiy you can follow this to know when it's complete
