### ISSUE TITLE
Closing when click in invadorer_count or citizens(u) 50.11 beta

### ISSUE THREAD

**Issue by iOrdonha** [DFHack/dfhack#4477]
Closing when click in invadorer_count or citizens(u)

I've 10  intruders, undead / experiments 

It`s a dwarf fortress world i Closing when click in invader_count or citizens(u)

Map has 10  intruders, undead / experiments. 11 dwarfs.

It`s a dwarf fortress world I've generated 17/04 beforre DFhack 50.11
I`m plyaing only Fortress mode. No major mods (just some fews to transparency and so)

[crash_2024-04-18-12-59-44.txt](https://github.com/DFHack/dfhack/files/15027849/crash_2024-04-18-12-59-44.txt)
[crash_2024-04-18-13-00-58.txt](https://github.com/DFHack/dfhack/files/15027850/crash_2024-04-18-13-00-58.txt)
[errorlog.txt](https://github.com/DFHack/dfhack/files/15027851/errorlog.txt)
[gamelog.txt](https://github.com/DFHack/dfhack/files/15027852/gamelog.txt)
[stderr.log](https://github.com/DFHack/dfhack/files/15027853/stderr.log)
[stdout.log](https://github.com/DFHack/dfhack/files/15027854/stdout.log)
generated 1704 beforre DFhack 50.11
I`m plyaing only Fortress mode. No major mods (just some fews to transparency and so)

[crash_2024-04-18-12-59-44.txt](https://github.com/DFHack/dfhack/files/15027849/crash_2024-04-18-12-59-44.txt)
[crash_2024-04-18-13-00-58.txt](https://github.com/DFHack/dfhack/files/15027850/crash_2024-04-18-13-00-58.txt)
[errorlog.txt](https://github.com/DFHack/dfhack/files/15027851/errorlog.txt)
[gamelog.txt](https://github.com/DFHack/dfhack/files/15027852/gamelog.txt)
[stderr.log](https://github.com/DFHack/dfhack/files/15027853/stderr.log)
[stdout.log](https://github.com/DFHack/dfhack/files/15027854/stdout.log)

**Comment by myk002** [comment]
could I get an upload of your savegame itself along with your mods? The crash appears to be in DF code, not DFHack, but if it's crashing in response to clicking on a DFHack UI element, then there's likely something we can do to avoid the crash.

**Comment by iOrdonha** [comment]
Hello!

I was in 51-01 beta.
I'm sharing the save, the crash log, mods (Not sure, but Horses, some SKs,
Bucket, better creature text, transparency).

DF to DFHack <https://1drv.ms/f/s!Al-WM4Ee_zWsmId7-Pymyjt5Gs0nMg?e=1BNaUH>

Notes:
I started the game without DFhack. The second time playing I`ve changed
DFhack to beta and played again. But that time the crashes began so I
correlated it to DFHack (as Myk said could be DF) .
Today I'd started the game, had 3 crashes (to confirm it`s happening).
After reading the crash log, I`ve exterminated a bunch of non-dwarfs and
the problem was solved. The save game is before the extermination.











Em sex., 19 de abr. de 2024 às 01:24, Alan ***@***.***>
escreveu:

**Comment by myk002** [comment]
Thanks! I'll take a look at it

**Comment by myk002** [comment]
This appears to be an issue with one of the loaded mods. The game crashes without DFHack loaded if you manually move the viewport to show the invading human that the notification panel zooms to on click (elevation 40, north edge of map).

I'm not sure which mod it is, but there are a considerable number of mod errors shown in `errorlog.txt`. At least one mod is not loading cleanly.
