### ISSUE TITLE
doc: dfhack.maps lua module link is dead

### ISSUE THREAD

**Issue by plule** [DFHack/dfhack#4492]
On this page: https://docs.dfhack.org/en/stable/docs/api/Maps.html
The link for the lua module dfhack.maps is dead, and I can't find the doc itself at all

**Comment by vallode** [comment]
Probably should link to here: https://docs.dfhack.org/en/stable/docs/dev/Lua%20API.html#maps-module

**Comment by myk002** [comment]
It's true that this directory is a bit unloved, but the information about the game structures is still correct. I think we should just fix the link.

**Comment by vallode** [comment]
I meant I would be more in favour of moving that information out of there, so that discoverability is higher and we don't have this odd duckling of a path lying around being unloved ^^ No strong feelings though.

**Comment by myk002** [comment]
Where would it move to? We didn't really have any other place to document DF code concepts

**Comment by plule** [comment]
Agree that it's good to keep it, this information helped me more than once. As far as the location goes, no opinion on my side, I can only say that google likes this page when looking for map manipulation info, probably because it's specialized :)

Thanks for the lua link, when opening the issue I was wondering if it was actually generated
