### ISSUE TITLE
Minor Version Change for Adv-Beta

### ISSUE THREAD

**Issue by supermedman** [DFHack/dfhack#4493]
DF v51.01-beta13 Currently not recognized as valid version by adv-beta steam beta branch for DFhack

**Comment by myk002** [comment]
try restarting your steam client. it doesn't always pick up the updates to both DF and DFHack

**Comment by supermedman** [comment]
DFHack build: 50.12-r3-101-g6258162e
Starting with working directory: E:\SteamLibrary\steamapps\common\Dwarf Fortress
Binding to SDL.
Identifying DF version.
Loading hack\symbols.xml ... OK
v0.51.01-beta win64 STEAM (windows): PE: 0x6620E355
v0.51.01 win64 ITCH (windows): PE: 0x00000000
v0.51.01 win64 CLASSIC (windows): PE: 0x00000000
v0.00.00 linux64 LOCAL (linux): MD5: 00000000000000000000000000000000
v0.51.01-beta linux64 STEAM (linux): MD5: 3313eff42a9abd870b57984b5f9a5ad9
v0.51.01 linux64 ITCH (linux): MD5: 00000000000000000000000000000000
v0.51.01 linux64 CLASSIC (linux): MD5: 00000000000000000000000000000000
Loaded 7 DF symbol tables.
Unable to retrieve version information.
PE timestamp: 0x6624ba45
Not a known DF version.
DFHack will now deactivate.


Copied from stderr.txt

**Comment by myk002** [comment]
yeah, you're not updated to the latest build on DFHack's `adventure-beta` Steam branch. Try poking Steam

**Comment by supermedman** [comment]
Path to that file?

**Comment by myk002** [comment]
what you should see in stderr.log is:
```
DFHack build: 50.12-r3-139-gcfaf8a4f
[...]
v0.51.01-beta win64 STEAM (windows): PE: 0x6624BA45
v0.51.01 win64 ITCH (windows): PE: 0x00000000
v0.51.01 win64 CLASSIC (windows): PE: 0x00000000
v0.00.00 linux64 LOCAL (linux): MD5: 00000000000000000000000000000000
v0.51.01-beta linux64 STEAM (linux): MD5: 3a1d4401a25f99080f1bbb0596e143da
v0.51.01 linux64 ITCH (linux): MD5: 00000000000000000000000000000000
v0.51.01 linux64 CLASSIC (linux): MD5: 00000000000000000000000000000000
```
You can see which Steam build you have here:
![image](https://github.com/DFHack/dfhack/assets/977482/a4045c24-1ea8-4b32-8ef8-6637e7aed79d)

**Comment by supermedman** [comment]
![image](https://github.com/DFHack/dfhack/assets/56461191/e06b896d-1d6d-44e5-9e79-9881c8d73743)

**Comment by supermedman** [comment]
I switched between beta and current version to try to get it to auto pull updates

This is what it did

**Comment by supermedman** [comment]
Issue Resolved
