### ISSUE TITLE
gui/create-item fails on some types of armor

### ISSUE THREAD

**Issue by ajs** [DFHack/dfhack#4516]
Getting the error at the end of this issue when trying to create some types of item. This is consistent.

For armor, specifically, it seems to be hand-items (perhaps because they have left/right alternatives?) I can create breastplates and greaves and shields, but not gloves or gauntlets.

But doing so via `createitem` works fine. (e.g. the steel gauntlet example from the createitem help text, in-game).

```
...mon\Dwarf Fortress/hack/scripts/modtools/create-item.lua:244: failed to create item: item_type: 29, item_subtype: 0, mat_type: 0, mat_index: 8, unit: 20924
stack traceback:
        [C]: in function 'assert'
        ...mon\Dwarf Fortress/hack/scripts/modtools/create-item.lua:244: in upvalue 'createItem'
        ...mon\Dwarf Fortress/hack/scripts/modtools/create-item.lua:319: in function <...mon\Dwarf Fortress/hack/scripts/modtools/create-item.lua:285>
```

**Comment by ajs** [comment]
Note: Using latest steam beta branch. `DFHack version 51.01-beta (git: 8f0a318) on x86_64`

**Comment by myk002** [comment]
There is a fix for this in progress at https://github.com/DFHack/dfhack/pull/4488
(closing as dup of https://github.com/DFHack/dfhack/issues/2063)

we're making the bespoke fix in `createitem` available to all callers of the underlying item creation API
