### ISSUE TITLE
gui/quantum: Dwarves continue trying to place originally-assigned minecart even if you replace it manually

### ISSUE THREAD

**Issue by jontkane** [DFHack/dfhack#4529]
I set up some quantum stockpiles using gui/quantum, but the minecarts it picked were ones I had in my lava-filling stockpile. I manually reassigned them to minecarts that weren't being used for anything, and moved on. Later, when the minecarts were ready for hauling for lava purposes, dwarves mysteriously got the task "place tracked vehicle" and dragged lava-filled minecarts up to the quantum stockpiles. This behavior persisted even when I erased the station using the minecart interface. I had to destroy the track stops to allow the dwarves to safely place the lava-filled minecarts down, then wait for them to haul it away and redo the quantum stockpile.

**Comment by myk002** [comment]
it sounds like `gui/quantum` could use a "nah, I'll assign minecarts manually thx" option

**Comment by jontkane** [comment]
I actually just confirmed it's a vanilla bug, not a dfhack bug. Weird!

**Comment by myk002** [comment]
reopening since the "I'll use my own minecart" option would still be useful
