### ISSUE TITLE
"Lair" does not function correctly in Adventure mode (Df Adv beta)

### ISSUE THREAD

**Issue by GGumby** [DFHack/dfhack#4532]
Invoking lair while in adventure mode does not actually mark the map as a lair. Tested in multiple ui in adventure mode.

**Comment by myk002** [comment]
This might be a documentation error. `lair` doesn't mark the site as a monster lair, it marks the tiles within the map area as "do not scatter" as if it were a monster lair. The representation of the site on the world map won't change.
