### ISSUE TITLE
Failed to build buildingplan with GCC 14 (compiler bug?)

### ISSUE THREAD

**Issue by cvuchener** [DFHack/dfhack#4534]
Compiling 3402d1410 on linux (Fedora 40) with gcc (gcc (GCC) 14.0.1 20240411 (Red Hat 14.0.1-0)), I get:

```
dfhack/plugins/buildingplan/buildingplan.cpp: In function 'int scanAvailableItems(DFHack::color_ostream&, df::enums::building_type::building_type, int16_t, int32_t, int, bool, bool, HeatSafety*, std::vector<int>*, std::map<DFHack::MaterialInfo, int>*)':
dfhack/plugins/buildingplan/buildingplan.cpp:634:11: error: possibly dangling reference to a temporary [-Werror=dangling-reference]
  634 |     auto &job_items = get_job_items(out, key);
      |           ^~~~~~~~~
dfhack/plugins/buildingplan/buildingplan.cpp:634:36: note: the temporary was destroyed at the end of the full expression 'get_job_items((* & out), key)'
  634 |     auto &job_items = get_job_items(out, key);
      |                       ~~~~~~~~~~~~~^~~~~~~~~~
dfhack/plugins/buildingplan/buildingplan.cpp: In function 'int countAvailableItems(DFHack::color_ostream&, df::enums::building_type::building_type, int16_t, int32_t, int)':
dfhack/plugins/buildingplan/buildingplan.cpp:737:11: error: possibly dangling reference to a temporary [-Werror=dangling-reference]
  737 |     auto &job_items = get_job_items(out, key);
      |           ^~~~~~~~~
dfhack/plugins/buildingplan/buildingplan.cpp:737:36: note: the temporary was destroyed at the end of the full expression 'get_job_items((* & out), key)'
  737 |     auto &job_items = get_job_items(out, key);
      |                       ~~~~~~~~~~~~~^~~~~~~~~~
```

After a quick look at the code, it seems the reference comes from a cache, it may be a false positive. Can the author (@myk002?) confirm all is right?

**Comment by cvuchener** [comment]
[Reported to fedora bug tracker](https://bugzilla.redhat.com/show_bug.cgi?id=2277696).

**Comment by myk002** [comment]
I believe this is ok, but I'll take a closer look

**Comment by myk002** [comment]
the reference returned from `get_job_items` is valid throughout the lifetime of the loaded library. I'd say this is a false positive

**Comment by cvuchener** [comment]
To anyone having this issue, just add `-Wno-dangling-reference` to your compile flags (`CMAKE_CXX_FLAGS`).

**Comment by ab9rf** [comment]
the only way for a reference to a data element of a `unordered_map` to become invalid is if the element is erased or if the map itself is deleted. the only event that causes either of these events is plugin shutdown, so yes, this code is safe

**Comment by ab9rf** [comment]
> To anyone having this issue, just add `-Wno-dangling-reference` to your compile flags (`CMAKE_CXX_FLAGS`).

i would suggest bracketing the affected code with a `#pragma` to disable this warning for just that code block rather than disabling this warning for the entire codebase

```
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wno-dangling-reference"
....
#pragma GCC diagnostic pop
```

**Comment by cvuchener** [comment]
I got an answer from Fedora bug tracker:

> Unfortunately I don't think I can fix it.  We see it's a function returning
> a reference and taking a temporary as an argument, so we warn.  We cannot
> analyze the body of the function f in the front end.  But you can suppress
> the warning with the [[gnu::no_dangling]] attribute like this:
> 
> ```
> [[gnu::no_dangling]]
> static const std::vector<int> &f(my_key_t key)
> {
>     auto &v = cache[key];
>     return v;
> }
> ```
