### ISSUE TITLE
gui/create-item > drink no longer properly functions

### ISSUE THREAD

**Issue by LoweGotembomrek** [DFHack/dfhack#4552]
[creating drink via gui/create-item creates an empty barrel](https://youtu.be/nilXtfWMURw)

**Comment by myk002** [comment]
are there any errors printed to the external console? (`show` in windows)

**Comment by LoweGotembomrek** [comment]
I believe it did. The following printed in red

`...mon\Dwarf Fortress/hack/scripts/modtools/create-item.lua:58: Cannot invoke field (global).moveToContainer(): In bool __cdecl DFHack::Items::moveToContainer(class MapExtras::MapCache &,struct df::item *,struct df::item *): NULL pointer: container.
stack traceback:
        [C]: in field 'moveToContainer'
        ...mon\Dwarf Fortress/hack/scripts/modtools/create-item.lua:58: in function <...mon\Dwarf Fortress/hack/scripts/modtools/create-item.lua:45>
        (...tail calls...)`

![Screenshot 2024-05-03 215559](https://github.com/DFHack/dfhack/assets/168879427/a300cc79-bb11-4abe-8f42-0eacd4b8acd8)

**Comment by myk002** [comment]
thanks! that helps
