### ISSUE TITLE
suspendmanager not correctly unsuspending stairs

### ISSUE THREAD

**Issue by ihnele** [DFHack/dfhack#4580]
Since version 50.13-r2 I've been having issues with suspendmanager arbitrarily not unsuspending vertical staircases spaning several z levels. It's rather arbitrary so it might be hard to replicate.
![Dwarf_Fortress_qm0FvPh2T9](https://github.com/DFHack/dfhack/assets/15185642/5bb559d6-956c-4e97-9f8e-0858b87b3ce5)

**Comment by myk002** [comment]
@plule

**Comment by plule** [comment]
oh damn that's a big regression there thank you for the report @ihnele
