### ISSUE TITLE
dig.warmdamp reveals warm and damp tiles that should usually be hidden

### ISSUE THREAD

**Issue by dimwit105** [DFHack/dfhack#4629]
![image](https://github.com/DFHack/dfhack/assets/27827292/3a30c432-9ee1-4e66-b138-d34401418cda)

This is with dig.warmdamp disabled, the warm/damp tiles on the edge are revealed as expected, and the interior is hidden.

![image](https://github.com/DFHack/dfhack/assets/27827292/a7229394-5465-4b89-b55c-a13f3f3a2549)

Enabling dig.warmdamp reveals tiles that are usually hidden, and I can see the worlds fluidy secrets!

**Comment by myk002** [comment]
are these tiles visible from underneath?

**Comment by chdoc** [comment]
> are these tiles visible from underneath?

I'm not exactly sure what you mean by this. As far as I can tell, visibility from underneath as not a thing in general. But yes, it seems that the "spoilerd" tiles have open tiles below them - although it seems that diagonally below is enough. Here is a slightly smaller example (the blueprint tiles are right on top of each other).

lower level:
![wet0](https://github.com/DFHack/dfhack/assets/20443222/9357d63c-9314-483b-813d-f08a0b1d6144)
upper level:
![wet1](https://github.com/DFHack/dfhack/assets/20443222/2edaf62f-3008-4e01-b0e0-34d3c9c0f911)

upper level (vanilla):
![wet1-2](https://github.com/DFHack/dfhack/assets/20443222/9adab25f-09c8-40a2-9824-2477ee9ecb59)

Note: none of the tiles on the upper level are revealed (i.e. I still don't know what kind of rock it is)

**Comment by dimwit105** [comment]
In this particular example, some times were, some tiles were not. Here are 3 screen caps of the volcanic wall that I took. These are identical in position, only elevation changing. 

![image](https://github.com/DFHack/dfhack/assets/27827292/5b63c462-97b5-4deb-aed4-d55c44cf7fc3)
![image](https://github.com/DFHack/dfhack/assets/27827292/c2096bac-0753-4c59-96a0-4a548f392ab9)
![image](https://github.com/DFHack/dfhack/assets/27827292/c69aeadc-b30d-4673-809d-66a63d76d399)

**Comment by myk002** [comment]
This was an intentional change in [50.13-r2](https://docs.dfhack.org/en/latest/docs/NEWS.html#id299):
```
dig: warm/damp/aquifer status will now be shown in mining mode for tiles that your dwarves can see from the level below
```
