### ISSUE TITLE
gui/reveal: selecting "Quit without saving" from the game's escape menu crashes the game while gui/reveal is active

### ISSUE THREAD

**Issue by Scrapulous** [DFHack/dfhack#4644]
I guess I spent all my ammo in the title.

Repro steps:
1. start new embark
2. activate gui/reveal, leave it active
3. hit 'escape' to bring up the game's menu
4. choose "Quit without saving"
5. crash to desktop

**Comment by myk002** [comment]
dup of https://github.com/DFHack/dfhack/issues/4183
