### ISSUE TITLE
gui/create-item producing incorrect creature-related items

### ISSUE THREAD

**Issue by Tjudge1** [DFHack/dfhack#4689]
Any eggs or vermin produced are consistently wrong.  

These are roc eggs. Race is -1, and caste is ostensibly the creature_id. Materials for the eggs are null, and size is always 1.
 ![Screenshot 2024-06-07 215329](https://github.com/DFHack/dfhack/assets/73856869/3e58a1a2-6119-4551-8a12-7a00cffebf44)
 
 Here's what happens when you make vermin.
![Screenshot_2024-04-23_200803](https://github.com/DFHack/dfhack/assets/73856869/7336d38c-090e-47f8-a7fc-2d7b03ca01dd)

**Comment by quietust** [comment]
Same as #3674 and #4507?

**Comment by myk002** [comment]
yeah, `gui/create-item` is accumulating creature-related issues
