### ISSUE TITLE
Crash on startup: "Not a known DF version"

### ISSUE THREAD

**Issue by Camfly** [DFHack/dfhack#470]
Platform: Windows
DF version: v.0.40.23

On startup (first run), DFHack will pop up a dialogue bow stating the above, that DFHack will deactivate, and directing to stderr.log for details, quoted here:

FirstCall()
Initized HOOKS!
Identifying DF version.
Loading hack\symbols.xml ... OK
Loaded 3 DF symbol tables.

DF will then crash. Aside from DFHack's extraction, the only modifications made to DF were a tileset and colour scheme.

EDIT: I think I can safely assume that this is due to trying to run DFHack v.0.4.19 with DF v.0.4.23. Apologies for time-wasting.

EDIT 2: Screen capture here: https://www.dropbox.com/s/vt8aphm8yjnhexf/Record_02.avi

EDIT 3: I have tested a clean install of DF, as well as after the modifications before the DFHack install - both run.

**Comment by Camfly** [comment]
Screen capture of the event: https://www.dropbox.com/s/vt8aphm8yjnhexf/Record_02.avi

**Comment by lethosor** [comment]
What platform are you using? Windows?

**Comment by lethosor** [comment]
At any rate, I can't reproduce the crash in 0.40.19-r1 on OS X or Linux - DFHack does not load if it doesn't recognize the checksum, but DF loads normally. It's possible that this is Windows-specific, although I don't think it's intentional.

**Comment by Camfly** [comment]
The 0.4.23-r1 release of DFHack does work with my current install - problem over.

**Comment by lethosor** [comment]
All right, but I don't think DFHack should crash. What happens if you change the hash of the Windows version in hack/symbols.xml? For example:
```diff
    <symbol-table name='v0.40.23 SDL' os-type='windows'>
-       <binary-timestamp value='0x549b0acb'/>
+       <binary-timestamp value='0x549b0acc'/>
```

**Comment by Camfly** [comment]
Editing symbols.xml to that value causes an identical crash.
