### ISSUE TITLE
`suspend` command is broken

### ISSUE THREAD

**Issue by chdoc** [DFHack/dfhack#4717]
I just realized that there is yet another tool that was interacting with `suspendmanager`: `suspend`

From the looks of it, the variant without arguments used suspend every single construction job there is. This would be easy to implement, even in Lua, and AFAIK is not currently doable by user-facing tools. 

The `--onlyblocking` option is trickier, because it is a mode of operation that is not currently supported by `suspendmanager`. Is it really worthwhile to spend time to explicitly avoid preserving designations and the likes? 

Does anyone object to dropping the `--onlyblocking` option? The fact that nobody has noticed until now, leads me to believe that this tool doesn't have a huge user base.

**Comment by myk002** [comment]
I'm fine with making it simpler to maintain. Now that `suspendmanager` is so effective, the need for these lower level tools is much diminished
