### ISSUE TITLE
(meta) Add binaries to the old releases and better documentation to all

### ISSUE THREAD

**Issue by PeridexisErrant** [DFHack/dfhack#473]
Migrate old binary releases from Dethware to the releases page.   Having them all available through GitHub would be nice, and minimize the difficulty of finding any particular release.  With the tags already in place, it should be more tedious than difficult!

At the same time, adding the relevant NEWS or changelog to these old releases would give a better sense of history.  The formatting of this part of the releases page could be made more consistent, too.

Obviously this isn't at all urgent, but once DF updates, pulls, issues, and so on are under control it's something to consider.

**Comment by PeridexisErrant** [comment]
If someone's willing to grant me the permissions required, I'd be happy to do this myself.  Otherwise, it'll only be an hour or so to download them all from http://dethware.org/dfhack/download/ and upload them to Github as release artifacts.

**Comment by lethosor** [comment]
There are also a bunch of older releases on DFFD too, and I don't think they all have Github release notes yet. I'll take a look.

**Comment by PeridexisErrant** [comment]
There's a brief note about releases [here](https://dfhack.readthedocs.org/en/stable/docs/Core.html#miscellaneous-notes); after dealing with the binaries it might make sense to close this issue from a commit removing that note.

**Comment by lethosor** [comment]
Working on binaries when I have spare time.

**Comment by lethosor** [comment]
0.34.10-r1 is the oldest I can find release notes for (the NEWS file was introduced in 0.34.11-r2), although I'm working on binaries for some older ones now.

**Comment by lethosor** [comment]
Current status:
* 0.34.02-0.34.04 binaries are on http://dethware.org/dfhack/download/, but not tagged on GitHub: https://github.com/dfhack/dfhack/releases?after=0.34.05-r1 (so I have no idea what commit they belong to). Also, I can't find any release notes.
* 0.31.25 releases are tagged on GitHub and Dethware, but have no release notes that I can find. They could be uploaded here anyway, like 0.5 and older: https://github.com/dfhack/dfhack/releases?after=0.31.25-r4
* 0.5 releases have no release notes that I can find.

**Comment by lethosor** [comment]
I think we have gathered all documentation that we can find for this - closing, but willing to add more releases if we can identify commits and release notes (and optionally binaries) for them.
