### ISSUE TITLE
Figure out how to not crash if a civalert is active when you retire

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#4730]
And then unretire the site 

Ref: https://discord.com/channels/793331351645323264/807444467140788254/1252350146159575140
https://discord.com/channels/329272032778780672/1049402643342168114/1252349525822017536

**Comment by myk002** [comment]
Might be fixed in DF; check with Putnam

**Comment by ab9rf** [comment]
also it's come to my attention that the circumstance that led to this was caused by doing disordered inserts into df vectors that were supposed to be sorted. i suspect this is not a high priority issue, and while we should investigate it i do not think it is a high priority issue

**Comment by quietust** [comment]
From what I recall, performing a typical binary search algorithm on an unsorted list tends to result in "undefined behavior" and can potentially end up reading past the end or _before the beginning_ of the list, so crashes wouldn't be unusual at all.

**Comment by myk002** [comment]
ok, closing as unactionable
