### ISSUE TITLE
After switching between Fortress and Arena Mode via DFHack gui/sandbox the map is completely revealed

### ISSUE THREAD

**Issue by DiamondDogma** [DFHack/dfhack#4737]
https://github.com/DFHack/dfhack/assets/173388665/b72934dc-e092-4a95-bac1-03bcada1635c

**Comment by myk002** [comment]
That assume control button must be new. If I may ask, why are you clicking it?

**Comment by DiamondDogma** [comment]
> That assume control button must be new. If I may ask, what are you trying to do by clicking it? Is the "fix" for this issue to just prevent that button from being clicked?

if i click on it, i can control that unit and fight invaders like gobos or forgotten beasts etc.
Its nice to defend with one legendary dwarf or throw/split coin stacks with the Adventure Mode UI during fortress mode

**Comment by myk002** [comment]
Unfortunately, that button just isn't stable when clicked from `gui/sandbox` I'm finding it causes crashes in some cases. For now, I think we'll have to just prevent it from being clicked
