### ISSUE TITLE
gui/sandbox does not stop the sound engine

### ISSUE THREAD

**Issue by Crystalwarrior** [DFHack/dfhack#4747]
Currently, when you "assume control" in Arena mode, it stops the sound engine of the "fort view" and starts the sound engine of the "adventure view". When you go back, it restarts.

What this seems to do, in effect, is initialize and de-initialize the sound for the respective gamemode.

However, running gui/sandbox starts up the fort mode soundtrack, but does not end the adventure mode soundtrack - meaning the sound engines are stacked.

Further research should be done into how arena mode does it with assume control, this same principle may apply on open-legends music stacking as well.

**Comment by Crystalwarrior** [comment]
Yah like this happens if you run gui/sandbox the assume control paragraph was given for research how the game swaps sound engines properly

**Comment by myk002** [comment]
So to clarify the issue here, it's that when you run `gui/sandbox` from adventure mode, the dwarfmode music starts playing in addition to the current adventure mode music?
