### ISSUE TITLE
" full-heal -all_citizens -r " dont working

### ISSUE THREAD

**Issue by FeldDyWhite** [DFHack/dfhack#4748]
The command:
full-heal -all_citizens -r
aren`t revive the citizens, pls fix it <3

**Comment by myk002** [comment]
could you zip up your savegame where you're having this problem and upload it to the cloud so we can use it to test a fix? Which units, specifically, are you expecting to be revived?

**Comment by myk002** [comment]
Fixed by https://github.com/DFHack/scripts/pull/1228
