### ISSUE TITLE
`makeown` should clear `enemy.army_controller_id`

### ISSUE THREAD

**Issue by ab9rf** [DFHack/dfhack#4753]
Based on [this comment on discord](https://discord.com/channels/793331351645323264/793331351645323267/1255533944250826903), I did some code searches in 50.13 and discovered that, in at least some situations, when a unit is joined to a site its `army_controller_id` is set to -1 to indicate that it is no longer a part of an "army". `makeown` should probably do this. This appears to affect hostility determinations, based on other observations made in discord.

It may also be necessary to remove the unit and the unit's histfig from the army itself; whether this is needed requires further research.

**Comment by Crystalwarrior** [comment]
Further research should also be done on what would get the "Expel" button to appear, because it appeared for intelligent wilderness creatures I `makeown`-ed, but not the goblin snatchers.

**Comment by myk002** [comment]
Fixed by https://github.com/DFHack/scripts/pull/1321
