### ISSUE TITLE
Full-heal command dont working

### ISSUE THREAD

**Issue by FeldDyWhite** [DFHack/dfhack#4788]
The command below dont working:
```
full-heal -r --all_citizens
```

**Comment by myk002** [comment]
Do you get an error message? Which units were you expecting to be resurrected but weren't?

**Comment by FeldDyWhite** [comment]
> Do you get an error message? Which units were you expecting to be resurrected but weren't?

All dwarf unitys, when i exec the command, i receive a message saying:
"Command finished successfully"

**Comment by FeldDyWhite** [comment]
Here my discord if u want see my savegame, but all my worlds are the same problem.
feld7398

**Comment by myk002** [comment]
I found and fixed the issue. Thank you for finding this!  I'll get it pushed to our Steam `testing` branches soon

**Comment by FeldDyWhite** [comment]
I'm happy to help ;D

**Comment by myk002** [comment]
Ok, the fix has been pushed to the Steam `testing` and `adventure-beta` branches. You can pick up the fix by subscribing to one of those in your Steam client.
