### ISSUE TITLE
Replace `needs_porting/copypaste.cpp` with a Quickfort blueprints generator

### ISSUE THREAD

**Issue by PeridexisErrant** [DFHack/dfhack#479]
The original plugin was designed to copy a section of the fortress to another section.  

I believe that generating blueprints is a better way to go though; as it's less 'cheaty', allows multi-fort usage and sharing, and the blueprints can be implemented with other tools (eg digfort and fastdwarf).

The command would be something like `make-blueprint <volume> <plan_name> [dig [build [place [query]]]]` (see [QF syntax](http://www.joelpt.net/quickfort/#editing-blueprints)), and the script would output the blueprint for the corresponding phase or phases.

The dig phase would read the shape of rooms to carve out, and the blueprint could be implemented by `digfort.rb`.  The build phase would place all buildings, furniture, and constructions, and the blueprint might be implemented by the new `fortplan` plugin.  The place phase records stockpiles, and would have to be implemented by Quickfort.  The query phase records created rooms and is likewise not yet possible with DFHack.

These could be implemented in stages, and would be a giant leap for fortress construction techniques - a way to eliminate the complex and tedious process of writing a blueprint.  Instead you could just decide to record something you like!

**Comment by cdombroski** [comment]
I've made a start on this, any feedback welcome. cdombroski@8193273

**Comment by cdombroski** [comment]
[Completed dig mode](cdombroski@b627240)
Ran: blueprint 10 10 -5 test
At this location:
![screenshot 2015-01-08 12 07 12](https://cloud.githubusercontent.com/assets/244909/5666815/77f826ca-9730-11e4-8946-6e19a1cb82ee.png)
![screenshot 2015-01-08 12 08 44](https://cloud.githubusercontent.com/assets/244909/5666821/7e064934-9730-11e4-9afb-f665808cb357.png)
![screenshot 2015-01-08 12 08 48](https://cloud.githubusercontent.com/assets/244909/5666822/80abe194-9730-11e4-8238-40a29cbb2e28.png)
![screenshot 2015-01-08 12 08 51](https://cloud.githubusercontent.com/assets/244909/5666824/829ece08-9730-11e4-97e6-7b94c54e1bd8.png)
![screenshot 2015-01-08 12 08 53](https://cloud.githubusercontent.com/assets/244909/5666825/8432d7b4-9730-11e4-8b92-0175f33fa1b5.png)
and got [this output](https://gist.github.com/cdombroski/8e91cf9676e13dbf136f)

**Comment by PeridexisErrant** [comment]
Awesome!  I'm looking forward to seeing further phases.

**Comment by cdombroski** [comment]
Ran into a tricky compilation issue, but finally got buildings done: cdombroski@3489c2f
![screenshot 2015-01-13 09 25 16](https://cloud.githubusercontent.com/assets/244909/5722030/7336e5ca-9b06-11e4-84d0-3d99c67b07f6.png)
[Output](https://gist.github.com/cdombroski/9e9319f523c21d14ca4c)
I should note that build and place files might require tweaking. If variable area buildings or stockpiles are placed next to each other, quickfort can't figure out where one ends and the other begins. Also things like parts of buildings being cut off probably isn't handled vary well. There's an alternate syntax available that fixes this problem, but it would make blueprint generation more complex. I'm also not sure if digfort/buildplan support that syntax or not. It's something I'll look into once the base functionality is in place.

**Comment by cdombroski** [comment]
Stockpiles finished, same fort area and output is the same [gist as before](https://gist.github.com/cdombroski/9e9319f523c21d14ca4c). Commit is cdombroski@f315ee4

**Comment by PeridexisErrant** [comment]
http://www.joelpt.net/quickfort/#area-expansion-syntax

Explicitly specifying the size, using non-automatic expansion, should take care for that. If dfhack does the support it, that's another bug - raise an issue and just have us use the blueprints with Quickfort for now.

**Comment by cdombroski** [comment]
Do we have any other thoughts than designating rooms for query blueprints? Stockpile adjustment is possible in theory, but is probably unworkable in reality.

**Comment by PeridexisErrant** [comment]
I've never seen it used for anything more than rooms, so that should be fine - it's a rare phase anyway. 

You should add to the NEWS and readme.rst though, so everything is documented :)
