### ISSUE TITLE
`digv` and related commands don't assign priorities to designations

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#481]
This doesn't seem to cause problems, although I'm not sure what priority these designations default to.
https://github.com/DFHack/df-structures/blob/master/df.map.xml#L391 is relevant.

**Comment by txtsd** [comment]
I've been using digcircle to make my circular/cylindrical fort. The tiles designated by the command do not show a priority number, but they are prioritized above all manually designated tiles, even the ones that have highest priority (1).
It would be nice to be able to set priority in the command eg: digcircle filled 33 1 for highest priority.

**Comment by expwnent** [comment]
I'm designating this a bug even though it doesn't seem to have harmful symptoms.

**Comment by lethosor** [comment]
These designations are treated as priority 0 (i.e. higher than 1)

**Comment by PeridexisErrant** [comment]
It looks like the `digfort` script has the same problem, though it's also missing a few designation types.

**Comment by robinhoodexe** [comment]
This is the only "problem" I have with dfhack right now. It's a bit cumbersome since the designations with digv gets highest priority when you use priorities to dig manually.
