### ISSUE TITLE
Crash occurs when using gui/mass-remove on large sections of furniture

### ISSUE THREAD

**Issue by gadict** [DFHack/dfhack#4826]
https://file.io/UsgBtGwhvJYD is a link to the last two saves that were made prior to the crash being reproduced.

F4-F6 are the hotkeys for the areas where most of the furniture in the fort is located.
Steps to reproduce:
- Use gui/mass-remove to designate a large section of furniture for removal.
- Allow dwarves to pick up those tasks.
- Designate another large section for removal.

It seemed to happen more easily if I selected furniture while unpaused.

I had trouble in the smaller world getting the bug to reproduce, but I was able to force it by selecting the same area for removal multiple times. 

I have no mods installed other than DFHack and have not modified any raw files myself. 

Thanks again for the assistance!

**Comment by myk002** [comment]
discussion on Discord here: https://discord.com/channels/793331351645323264/807444515194798090/1268742053701881936

Was able to reproduce on Linux after a few attempts
