### ISSUE TITLE
Autobutcher probably needs to check for gelded animals

### ISSUE THREAD

**Issue by cdombroski** [DFHack/dfhack#484]
With the idea that autobutcher should leave a viable breeding operation, I'm not sure if gelded animals should be excluded from butchering like pets and working animals, or if they should be prioritized like homosexual animals are now.

**Comment by PeridexisErrant** [comment]
My vote would be prioritised, as are other non-breeding animals, unless they fit into one of the exclusion categories.

**Comment by expwnent** [comment]
Fixed.
