### ISSUE TITLE
Port timestream to C++

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#4841]
timestream currently takes more than 10% of DF playtime in it's current Lua form. This is singlehandedly exhausting our performance budget. We need to improve the performance of this tool, and porting to C++ is probably the best way.

Design doc and project plan: https://docs.google.com/document/d/1-yvNtI53e9TXHSfSd7B2GeWzEgN-SiYjxXI8bcSWbbA/edit

**Comment by Tjudge1** [comment]
As per your request, this is my comment.

**Comment by myk002** [comment]
Assigned. Thanks!
