### ISSUE TITLE
`fix/dry-buckets` should set the `plotinfo` flag to trigger a bucket check

### ISSUE THREAD

**Issue by ab9rf** [DFHack/dfhack#4854]
there's a flag in `plotinfo`, `eval_requester_can_check`, that is used to indicate that a bucket may now be available to satisfy "give water" jobs and forces reevaluation of such activities at the next appropriate check. `fix/dry-buckets` should set this flag whenever it creates an empty bucket

**Comment by myk002** [comment]
note to implementor: we call the flag `recheck_aid_requests`

**Comment by ab9rf** [comment]
yeah sorry i was going based on ghidra there which was imported in november 2023 and hasn't been systematically updated for all the canonicalization work we've done since
