### ISSUE TITLE
Buildings::deconstruct is not destroying jobs

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#4890]
the DF virtual destructor is responsible for this, but somehow it is not taking effect

**Comment by ab9rf** [comment]
cannot replicate in 50.13. strongly suspect this issue is specific to 51.01-beta

**Comment by quietust** [comment]
Our structure definitions are out of date - between beta20 and beta21, three building vmethods were removed.

**Comment by myk002** [comment]
Fixed in https://github.com/DFHack/df-structures/commit/5cf120bd83cc367b1d47d5f0b0ba16639d93c60e
