### ISSUE TITLE
`rejuvenate --force` needs to break mother/infant rider relationship

### ISSUE THREAD

**Issue by ab9rf** [DFHack/dfhack#4894]
when `rejuvenate --force` is used, the script changes the occupation of infants that are aged up but does not break the mother/infant "rider" relationship causing mothers to perpetually attempt to pick up their abandoned "baby" (who is now an adult)

[related discord discussion](https://discord.com/channels/793331351645323264/807444467140788254/1279376477766422528)

**Comment by ab9rf** [comment]
further update: on research, the problem may be that the aged-up babies are not being removed from the `ANY_BABY2` categorized unit subvector when they're forcibly aged up. the game periodically checks to see if, for any given unit M, there is a unit B on this vector who for who M is the unit's `Mother` but not `RiderMount` (in M's `relationship_ids` table), then if M can path to B, M will cancel whatever she is doing and initiate a `SeekInfant` job for B, regardless as to whether B is a baby or not

thus, when aging up a baby to not-baby, it's necessary to:
* clear the `RiderMount` id in the baby's `relationship_ids` table
* remove the baby from the `ANY_BABY2` unit category vector

it's probably also a good idea to set the baby's `mount_type` to `STANDARD`

**Comment by ahlove3** [comment]
Commenting to say I'm taking a look at this

**Comment by ahlove3** [comment]
Submitted a PR

**Comment by ab9rf** [comment]
we should consider centralizing age transition emulation in either a lua library or in the core
