### ISSUE TITLE
startdwarf.rb doesn't seem to function with DFHack 0.40.23-r1

### ISSUE THREAD

**Issue by Scoresby** [DFHack/dfhack#496]
No matter what number I put, I still only have 7 dwarves at embark. I read that this should be set before hitting "e" when picking a site. No luck. Also tried at title screen, no luck. The script itself seems to say it should return the error "too low" when the number is under 7, but this also doesn't happen. 

Running DF 0.40.23 on OSX 10.10.1.

**Comment by fricy** [comment]
Yeah, it's actually not a bug , but an oversight: the needed memory structure was not located for 40.23. Hopefully this will be fixed in 40.24.  
If you absolutely need this, you can embark with dfhack-40.19 and upgrade the save later.

**Comment by Scoresby** [comment]
Ah! That explains it. I was working on an experiment but it can wait until 40.24.
