### ISSUE TITLE
wont install/run

### ISSUE THREAD

**Issue by strikewyrm** [DFHack/dfhack#497]
tried installing all 3 versions and the "dfhack run" was a file instead of an application and while df ran normally no matter what i did dfhack wouldn't run

**Comment by lethosor** [comment]
- You only need to install the version of DFHack for your platform
- dfhack-run is not the executable you want to use (see the readme). On OS X and Linux, you run the dfhack script, and on Windows you launch DF normally (be sure to use the SDL version of DF).

**Comment by strikewyrm** [comment]
i have windows... so i install the "dfhack-0.40.23-r1-Windows" thing and delete the SDL file?

**Comment by lethosor** [comment]
You are decompressing the archive, right? Also, you should _overwrite_ SDL.dll with the one from the DFHack archive, instead of just deleting it (although you could delete DF's copy of SDL.dll first before copying over DFHack's).

**Comment by strikewyrm** [comment]
when i install windows there is nothing to decompress and yes on the ones that i have decompressing i do so

**Comment by lethosor** [comment]
`dfhack-0.40.23-r1-Windows.7z` is a compressed archive - if you can't open it, you might need to install [7-zip](http://www.7-zip.org/).

**Comment by strikewyrm** [comment]
....oh

urist mic stupid trundles of to follow the legendary instruction givers advice....
thanks will let u know if there are still issues

**Comment by strikewyrm** [comment]
Urist mic stupid was successful!!!
