### ISSUE TITLE
Autobutcher on embark orders butchering ignoring autostart settings for race

### ISSUE THREAD

**Issue by Birkow** [DFHack/dfhack#4986]
Reproduction steps:
1. Enable autostart for autobutcher and autostart target settings for birds 
![obraz](https://github.com/user-attachments/assets/82a402eb-e993-4822-82b1-9be5c9e4c492)
2. Embark with one of bird races selected in autostart. Select more birds than default for autobutcher, e.g 7 adult females.
3. Open gui/autobutcher just after embark, There was butchering orded using default settings, probably before autostart settings for race are loaded.
![obraz](https://github.com/user-attachments/assets/2a022cd6-8c77-41b1-b8cd-e8515e503177)

Reported on discord
https://discord.com/channels/793331351645323264/793331351645323267/1292499967692374027

**Comment by Birkow** [comment]
@myk002 It looks like removing those 2 lines would fix issue with marking animals for butchering on embark before autostart race specific config is loaded, question is if it is not needed in some other circumstances. Do you remember why autobutcher cycle is run when it's enabled? 
[e285ee31a406b4aba936615d4788e6b9f129980e  ](https://github.com/DFHack/dfhack/commit/e285ee31a406b4aba936615d4788e6b9f129980e#diff-b113c019ed1d5b04fc47fe06b90a851cdbd6d288180f94267cc0b981609c909eR110-R111)

It could probably be fixed other way too, by changing order in which autostart commands are executed.

**Comment by myk002** [comment]
the cycle runs on enable since that's what people would *usually* expect. When you enable a tool, you generally expect it to start doing something. however, in this particular case, it's not the desired behavior

**Comment by Birkow** [comment]
If I understand how autobutcher cycle is run plugin_onupdate should take care of that soon after it's enabled either way.

**Comment by myk002** [comment]
I think keeping cycle-on-enable is good in the general case, but maybe we can skip it if this is the first frame of the fort.

Another option would be to recalculate butchering for a race when configuration for that race changes. That could also lead to confusion, though. If a player has specifically marked some units for butcher, then changes the config for the race (in any way), then those units could become unmarked.

The skip-on-first-frame is simple and is probably the least bad way to solve this

**Comment by myk002** [comment]
> If I understand how autobutcher cycle is run plugin_onupdate should take care of that soon after it's enabled either way.

true, but a common case is for a player to pause, enable, then inspect the results. if there are no results, there is confusion
