### ISSUE TITLE
`fortplan` plugin should support stockpiles and query mode, like Quickfort

### ISSUE THREAD

**Issue by PeridexisErrant** [DFHack/dfhack#499]
DFHack already includes `digfort` for designations, and `fortplan` for building.  With the new `blueprint` plugin creating complete QF blueprints, it would be good to have a native way to lay out the generated blueprints in-game.

For "place" mode, all basic stockpiles need to be settable.  Custom stockpiles are not supported, IIRC.  For "query" mode, it would be good to support all options - but a majority of cases would be covered by `r+` for making a room.

**Comment by danaris** [comment]
I am working on fortplan, a plugin designed to implement all of Quickfort's basic functionality. At present, it only supports build mode, and only furniture built with items that share the furniture's name. However, I intend to expand it to support all modes, and at least all basic buildings, stockpiles, and queries. It's just going to take some time :-)

**Comment by myk002** [comment]
danaris: are you still working on this? I might start poking around in my spare time if this is still open

**Comment by danaris** [comment]
Sadly, I have not had time to devote to anything dwarfy in a few years. I would be delighted to know that some of the stuff I was poking at was being worked on by those who do.

**Comment by myk002** [comment]
I put together a project plan, though it might take me a very long time to implement it. Would you mind taking a look and leaving comments? You've spent more time thinking about this than I have, I'm sure, and I'd love to hear your thoughts on what's a good idea and what isn't. I'd especially like to find out what parts of the plan are going to be difficult/impossible so I can start thinking about alternatives!
https://docs.google.com/document/d/17EjZlGsUOJ6E8WtqkCRZi9BBKjL9L1IdHfkB3Ajqas8

**Comment by myk002** [comment]
@lethosor If you have time, I would also appreciate your input on this before I do further planning or bring it to the forums.

**Comment by lethosor** [comment]
I left a couple more general comments - I'm not that familiar with the buildings APIs myself.

**Comment by myk002** [comment]
@lethosor Thanks! That helps put some things in perspective. I see @angavrilov and @BenLubar wrote most of Buildings.cpp -- could either of you share your thoughts on the best way to apply building blueprints, especially with buildings that take multiple source components, like wells? Doc link for comment: https://docs.google.com/document/d/17EjZlGsUOJ6E8WtqkCRZi9BBKjL9L1IdHfkB3Ajqas8

**Comment by myk002** [comment]
Ok, I think the [design doc](https://docs.google.com/document/d/17EjZlGsUOJ6E8WtqkCRZi9BBKjL9L1IdHfkB3Ajqas8) is in pretty good shape now. I've also dug into the buildings API and determined that what I need to do here appears to be possible. @lethosor could you give it one more read through? Is there anyone else who I should seek approval from before I start writing any code?

**Comment by lethosor** [comment]
There's not really a formal approval process - you're welcome to start working on it whenever you like. It would probably be helpful if you could put up a pull request sooner rather than later (ideally as a draft PR if it's not done yet) since that would make it easier for people to spot any issues that could come up.
Anyway, thanks for your interest in taking this on!

**Comment by myk002** [comment]
Thanks! I opened a forum thread at http://www.bay12forums.com/smf/index.php?topic=176889.0 for public discussion and progress reports. I do expect this to take me a good bit of time to complete. I only have a few hours a week I can devote to it. We'll see how much interest it generates. I always have the hope that someone else will want to contribute too!
