### ISSUE TITLE
Add PDBs to windows distribution

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#4991]
- add `/Zi` to the compile flags
- add `/DEBUG` to the link flags

and package where?

**Comment by ab9rf** [comment]
just store the PDBs as a build artifact, they do not need to be sent to subscribers

**Comment by myk002** [comment]
It looks like ccache does not support the /Zi flag, so we might have to choose between expedient builds and Windows debug symbols.

As it stands, building with a warm cache for Windows takes about 3 minutes. Building without a cache takes about 20 minutes. That's enough of a difference to fuel a careful cost-benefit discussion.

**Comment by ab9rf** [comment]
does ccache support `/Z7`?

**Comment by myk002** [comment]
it looks like it might. I'll get you a link to the artifacts when the test build is done (and it hasn't failed yet at 50%)
