### ISSUE TITLE
"init.lua not found" message is not always suppressed

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#501]
dfhack.lua checks for a hardcoded error message, which causes this warning to appear when loading a save if the error message returned by the OS doesn't match exactly (this was reported by a user on the forums using German).

**Comment by warmist** [comment]
We did not have filesystem lib. Now that we have it chage would be easy: replace all "string.match(perr, 'No such file or directory')" and similar with filesystem.exists()
