### ISSUE TITLE
Trade Depot - Infinite 'bring everything to the depot' loop

### ISSUE THREAD

**Issue by MobiusOblidus** [DFHack/dfhack#5010]
Hi Team - playing DF v50.14 with DFHack 50.14-r1

Encountered (what I presume is) a bug last night & today where, when traders enter the map - and for the duration of their stay - my dwarves go crazy bringing everything of value in my fortress to be traded at the trade depot. I have given no instruction for them to do this, and when I go into the DFHack Trade Screen with Ctrl+T and untick every item, as soon as a dwarf removes the item it is added again and the loop continues.

I have tried deconstructing my trade depot & building a new one - the bug persists. 

Any ideas?

(Save file is too large to upload here)

**Comment by ab9rf** [comment]
make sure that you don't have stockpiles designated for autotrade

**Comment by MobiusOblidus** [comment]
> make sure that you don't have stockpiles designated for autotrade

Ach, that did it! Thank you - I wasn't even aware this was an addition until you said it was possible. Thank you!
