### ISSUE TITLE
"You have selected a narrow area" warning is always displayed when "embark-tools anywhere" is enabled

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#502]

**Comment by PeridexisErrant** [comment]
`embark-anywhere` has been replaced by `embark-tools anywhere`.  Can this issue be closed now?

**Comment by lethosor** [comment]
That's the one I was referring to, actually.

**Comment by PeridexisErrant** [comment]
Alright, better leave it open then!

**Comment by lethosor** [comment]
I believe the message now is "this is your only warning", due to some DF changes, which is more appropriate.
