### ISSUE TITLE
Non hostile getting hostile notification

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#5037]
Report:

I have a question about hostile creatures.

Down in the bottom left corner, DF hack tells me I have a hostile creature on map. This creature is visiting my fortress and is a representative of some organisation.

Why are they being flagged as hostile? And if they are hostile, why are they not attacking/being attacked?

Example save: https://www.dropbox.com/scl/fi/iany5s8su1xczlgh34pj6/autosave-2.zip?rlkey=mwombobja9280wixjkgc33q4a&st=2g3c86ni&dl=0

**Comment by NicksWorld** [comment]
The "hostile" in question is an intelligent undead, which is considered a nightcreature. `Units::isDanger` returns true for all nightcreatures, with no exceptions made in `notifications.lua`. While most nightcreatures are hostile, the wiki says that intelligent undead as visitors are as well-behaved as any other guests.

**Comment by myk002** [comment]
We fixed a similar issue in https://github.com/DFHack/dfhack/pull/4850 where we erroneously considered all undead to be hostile. I'll need to take a closer look at `isDanger` and all the code that currently calls it
