### ISSUE TITLE
Stockpile save/load doesn't work without stocksettings directory

### ISSUE THREAD

**Issue by pineapplemachine** [DFHack/dfhack#504]
This directory should be created automatically if it doesn't exist, since otherwise an error appears and the settings are not saved.

**Comment by lethosor** [comment]
Are you sure it's not the `stocksettings` directory? I'm fairly certain that the plugin creates that directory on startup.

**Comment by lethosor** [comment]
Ah, looks like it was removed in 2f4678eee548278ca30e279a02c41fc1cac13128
@ramblurr what exactly is the reason for that change?

**Comment by pineapplemachine** [comment]
The result is a successful creation of a stocksettings folder in the correct place.

**Comment by Ramblurr** [comment]
@lethosor hm, that might have been a merge mistake. I meant to move the directory creation somewhere else but never did it.

**Comment by expwnent** [comment]
Merged the fix. I'll reopen it if the problem persists.
