### ISSUE TITLE
fix/wildlife despawning caged creatures

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#5044]
reported on [Steam](https://steamcommunity.com/app/2346660/discussions/0/4634862385195150318/):

While using the fix i did notice a behaviour that may or may not be intended. When an (agitated specifically?) animal is caught in a cage trap during an ongoing siege the cage is by default marked as forbidden. Once this occurs the sidebar no longer registers the animal as wildlife, but it appears that the "Fix/Wildlife" script will still despawn them. (Leaving an empty, forbidden cage filled with smoke in it's wake).

**Comment by ab9rf** [comment]
taming an agitated animal clears the agitated state so it's probably not a good idea to poof them out of existence as they can be tamed normally

**Comment by myk002** [comment]
this behavior was totally unintended. the algorithm is expected to *skip* anything in a cage, and I'm not sure why it's affecting caged creatures at all
