### ISSUE TITLE
DFHack Time Not Showing in SteamDeck Desktop Mode

### ISSUE THREAD

**Issue by ctempleton3** [DFHack/dfhack#5047]
When you run Dwarf Fortress in desktop mode of SteamDeck it dosn't add run time to DF Hack game. Only Dwarf Fortress gets run time in steam. I am not sure what I need to provide to show this. Let me know what I need to provide and I will provide the data requested.

Just as an aside. DF Hack Works fine in Dwarf Fortress.

**Comment by myk002** [comment]
Are you running DF and DFHack under windows emulation or as a native Linux binary?

You can ensure you get the native Linux binary by setting the Compatibility to Steam Linux Runtime 1.0 (scout) for both DF and DFHack:
![image](https://github.com/user-attachments/assets/4fb7c704-5746-4e81-a7ce-ae8eb593d0ff)

When running as Linux, does it work as expected?

**Comment by ctempleton3** [comment]
When I entered the ticket, I was running under windows emulation.  Proton Experimental. When I changed the settings listed above, it gained time on both games.

**Comment by myk002** [comment]
This is expected, though I don't know where to usefully document it. When running under emulation, the DFHack stub process (which is responsible for correct functioning of cloud save for DFHack data) and the DF process (which loads the actual DFHack library) can't communicate, so the stub process exits early.
