### ISSUE TITLE
Incorrect Points Required for Skill Advancement

### ISSUE THREAD

**Issue by Halifay** [DFHack/dfhack#5098]
**Description:** The amount of points required to advance to the next level is displayed as 0 for skills at very high levels, which is often observed in combat skills. Considering the known formula for calculating the exact points needed for any level, this appears to be a bug that could be easily addressed.
![image](https://github.com/user-attachments/assets/11d0204d-feb7-4fad-ab20-1addb798d34a)

**Steps to Reproduce:**

Train a skill to a very high level (commonly observed in combat skills).

Observe the points required to advance to the next level.

**Expected Behavior:** The points required to reach the next level should be displayed accurately according to the known formula.

**Actual Behavior:** The points required to reach the next level are displayed as 0.

**Additional Information:**

Version: 51.01 adventure beta

**Comment by quietust** [comment]
The issue is that the XP threshold is being fetched from the `skill_rating` enum type defined in `library/xml/df.units.xml` rather than being calculated dynamically, so it only has meaningful values for levels up to Legendary+4 (19).
