### ISSUE TITLE
Allow Shift+Direction to traverse long lists

### ISSUE THREAD

**Issue by txtsd** [DFHack/dfhack#510]
Shift+Direction works great in Manipulator (u-l)

I find myself attempting to use it on many other screens only to be disappointed. Sure Page Up/Down is useful, but it would be very helpful to be able to scroll up/down by 8-10 units on screens where the lists are long.

Potential screens: Units (u), Jobs (j), Animals (z), Trade, Alerts (a), Reports (r).

**Comment by myk002** [comment]
shift-scrolling is now provided in DFHack lists and the vanilla DF UI
