### ISSUE TITLE
update `strangemood` with v50+ moodable skills

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#5111]
e.g. stone carving

**Comment by quietust** [comment]
Unless I'm mistaken, it already *does* support those skills - I added them back in commit 3b8da6a2eec7f49a612173feab30c22459ea964b.

**Comment by myk002** [comment]
hrm, I'll have to investigate further what the reporter was talking about (https://steamcommunity.com/app/2346660/discussions/0/604143024098812401/)

**Comment by myk002** [comment]
It might be that `strangemood --type stonecrafter` causes an error

**Comment by myk002** [comment]
it might be that "stonecarver" (and "stonecutter") is not a recognized skill on the commandline
