### ISSUE TITLE
Ensure mods can be fully self-contained in the (save) raw folder

### ISSUE THREAD

**Issue by PeridexisErrant** [DFHack/dfhack#518]
By either including mod-specific functions in the standard DFHack install, especially [Roses' scripts](), or
something like #503, allowing similar libraries to be stored in the `raw` folder.  My expertise isn't in this area, but I'd try both:  include the common stuff, and allow distributing rare modules with raws.

This was specifically prompted by my discussion with Putnam [here](https://www.reddit.com/r/dwarffortress/comments/2u0vca/fortbent_200_released_144_classpects_for_all_of/co45npx) - we both want the PyLNP's mod merge functions to become a community standard, and to work for any mod we need to be able to store all mod-specific files in the raw folder.

**Comment by expwnent** [comment]
This is already a goal but we can have it on github if you want.

**Comment by PeridexisErrant** [comment]
I'm aware that this is not a new idea, but often a clear statement in an issue tracker helps focus development.  That the PyLNP is about to open up mod distribution also adds a timeline to meet, which I think is new.

**Comment by expwnent** [comment]
To elaborate, the original goal as I phrased it is to make it possible to transfer saves  between people who have DFHack but have different mods installed and have everything still function. It's not possible for tilesets but everything else should work.

**Comment by PeridexisErrant** [comment]
Closed by bf5e491647da9a16126a8bda9c533b4e839e2f4c.
