### ISSUE TITLE
Digcircle documentation: Diameter vs radius

### ISSUE THREAD

**Issue by jvanegmond** [DFHack/dfhack#523]
digcircle takes a diameter as parameter, but the documentation is confusing on this part saying both:

- Diameter in tiles (default = 0, does nothing)
- 'digcircle filled 3' = Dig a filled circle with radius = 3.

**Comment by lethosor** [comment]
dig.cpp:299:
```
"'digcircle filled 3' = Dig a filled circle with diameter = 3.\n"
```

**Comment by jvanegmond** [comment]
Correct. Both readme.rst and readme.html are affected. digcircle definitely takes a diameter.
