### ISSUE TITLE
`getplants -c [ID]` does not clear all corresponding designations (anymore)

### ISSUE THREAD

**Issue by bseiller** [DFHack/dfhack#531]
After designating some shrubs (MUSHROOM_CUP_DIMPLE) with `getplants -s [ID]` and harvesting the reachables i tried to undesignate the rest (in the caverns which) `getplants -c [ID]`
They stayed designated for gathering, while the output said `Updated 153 plant designations`.
Undesignating some by hand and reissuing `getplants -s [ID]` flagged all of them again, using `getplants -c [ID]` after that properly cleared those that I changed manually, but again left those only manipulated by the initial getplants call unchanged - the output still claimed `Updated 153 plant designations`.
On request I can provide the save.

**Comment by warmist** [comment]
Gathering designations are no longer in designations flags. It's now a 4000 flag in designation priority block event.

**Comment by lethosor** [comment]
This should be fixed for the next release.
