### ISSUE TITLE
zone plugin causes crash when scrolling cage owner list

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#534]
(Not to be confused with the cage assignment list)
Originally reported on the [forums](http://www.bay12forums.com/smf/index.php?topic=126076.msg6015760#msg6015760)

**Comment by lethosor** [comment]
The crash was occurring [here](https://github.com/DFHack/dfhack/blob/e006eb21e82184187f948ae1b74f9fcfaa24d657/plugins/zone.cpp#L3739-L3742) - the plugin assumed that each of those four vectors had the same size, but only `ui_building_assign_units` was compared against `ui_building_assign_type` (and happened to be the only vector with the same size in this case).

**Comment by PeridexisErrant** [comment]
Would it be possible to get a build of this fix compatible with the current DFHack?
