### ISSUE TITLE
[0.40.24-r2][osx] df crashes on startup if folder path contains a space

### ISSUE THREAD

**Issue by akrieger** [DFHack/dfhack#538]
akrieger-mbp:df_osx akrieger$ pwd
/Users/akrieger/Downloads/Dir Withaspace/df_osx
akrieger-mbp:df_osx akrieger$ ./dfhack
dfhack: attempting to hook in
Loading bindings from data/init/interface.txt
Resetting textures
Could not insert hotkeys hooks!
Plugin /Users/akrieger/Downloads/Dir Withaspace/df_osx/hack/plugins/jobutils.plug.dylib has failed to initialize properly.
./dfhack: line 15:  6860 Bus error: 10           DYLD_INSERT_LIBRARIES=./hack/libdfhack.dylib ./dwarfort.exe "$@"

akrieger-mbp:df_osx akrieger$

The plugin load error is irrelevant - removing the plugin still results in the crash, with the same error about 'Could not insert hotkeys hooks!'

Vanilla df loads fine from the same directory, even the same installation.

I have not attempted to reproduce this on Windows or Linux.

**Comment by lethosor** [comment]
Odd, I can't reproduce this with 0.40.24-r2. Is there anything in stderr.log?

**Comment by lethosor** [comment]
> removing the plugin still results in the crash, with the same error about 'Could not insert hotkeys hooks!'
Er, what exactly are you removing? If you're removing `hack/plugins/hotkeys.plug.dylib` and still see that error message, something is wrong.

**Comment by akrieger** [comment]
I checked that, it was oddly nonspecific.
It might also be related to saves, somehow? I tried debugging by moving everything to a local path, but I symlinked data/save to an external location (specifically, into dropbox, where the path has a space) and for some reason that also triggered the same crash.

I also freshly installed Phoebus's tile pack, but I made sure to test with one that was vanilla, and was still getting the errors. I'll try with a fresh download - it's entirely possible I somehow managed to corrupt both my clean install and this one.

akrieger-mbp:df_osx_ascii akrieger$ cat stderr.log
dfhack: saving real SDL functions
dfhack: saved real SDL functions
dfhack: hooking successful
Identifying DF version.
Loading hack/symbols.xml ... OK
Dummy symbol table entry: start_dwarf_count
Loaded 3 DF symbol tables.
Version: v0.40.24 osx
Initializing Console.
Console is running.
Initializing Plugins.
d_init: 372

**Comment by akrieger** [comment]
I can also upload a tarball of the repro'ing thing and upload it to Dropbox if you're willing to use that.

**Comment by akrieger** [comment]
Yeah it's not happening with a freshly untar'd install, even with the directory path having a space and data/save symlinked elsewhere. Weird. Quantum rays I guess.

**Comment by lethosor** [comment]
It sounds to me like DFHack wasn't recognizing the DF version (possibly a corrupted executable?), although that wouldn't explain why plugins were being loaded in the first place and why DF crashed.

**Comment by akrieger** [comment]
https://www.dropbox.com/s/diqa3597uz20jo3/df_osx_crash_small.tar.gz?dl=0 is the crashing install. Should be fairly minimal, it actually crashes immediately when I run it regardless of the directory path now. But I md5'd the dwarfort.exe and libdfhack.dylib binaries and they matched, so maybe something else random is broken.

Hope that helps, if you're curious. I'll go ahead and close this because a clean install doesn't repro.
