### ISSUE TITLE
Autobutcher's settings export is a mess

### ISSUE THREAD

**Issue by PeridexisErrant** [DFHack/dfhack#554]
To quote the readme:

>Settings and watchlist are stored in the savegame, so that you can have
different settings for each world. If you want to copy your watchlist to
another savegame you can use the command list_export::

>* Load savegame where you made the settings.
>* Start a CMD shell and navigate to the df directory. Type the following into the shell: `dfhack-run autobutcher list_export > autobutcher.bat` (or .sh)
>*  Load the savegame where you want to copy the settings to, run the batch file (from the shell): `autobutcher.bat`

This script is very simple:  (eg)

    dfhack-run autobutcher start
    dfhack-run autobutcher autowatch
    dfhack-run autobutcher sleep 6000
    dfhack-run autobutcher target 5 1 5 1 new
    dfhack-run autobutcher target 5 1 5 1 CAT
    dfhack-run autobutcher watch CAT

Surely there's a more elegant way to do this?  Even just exporting the file directly instead of requiring the user to pop another terminal would be an improvement!

**Comment by lethosor** [comment]
> Even just exporting the file directly
What file?
At any rate, this is better than the alternative (not being able to export the data at all, as is the case with many other plugins).

**Comment by PeridexisErrant** [comment]
Running `autobutcher list_export` prints the code block above, and piping it into a `.bat` or `.sh` script allows it to re-run those commands with `dfhack-run`.  I'm currently going through the readme, so experimenting and re-documenting made this much clearer.

As a proposed change:  Instead of having to pipe output to a file, write to a file directly.  Drop the `dfhack-run` starting each line, and then to import `script autobutcher.txt` is a native DFHack command, there's no need for an external shell, and it works identically on each platform.

**Comment by lethosor** [comment]
Ah, that makes more sense. Should be fairly easy to change.

**Comment by PeridexisErrant** [comment]
I'm going to experiment with file-io when I haven't got the build environment working, but [here's the other stuff](https://github.com/PeridexisErrant/dfhack/commit/bc505952a3a6dfcba778538c20dd77639aebb40c).

If there's a DFHack console command that can pipe command output to a file, the only other change needed would be to document that appropriately.

**Comment by PeridexisErrant** [comment]
#567 will make this perfect, but basically done - it's at the same level as workflow now.
