### ISSUE TITLE
Attempting to run a function from a non-existent script causes an error

### ISSUE THREAD

**Issue by PeridexisErrant** [DFHack/dfhack#568]
While I can see that this makes sense, it also means it's impossible to attempt to call an external script which may or may not be available.  If there's a native way to check in advance whether the second script exists, I don't know it. 

This is a problem for me at the moment because I'm working on a script which stores data (descriptions of items, creatures, and materials) as a function.  If attempting to access a script, which for a mods would be in `/raw/scripts`, failed non-fatally I could include all the vanilla config in the same file.  As is, I'll need to supply a second script with the vanilla info, and allow that to be overridden by a copy in the raws.  At best this will require some inelegant workarounds, and at least a placeholder script seems essential.

**Comment by lethosor** [comment]
If you're referring to `script_environment` from bf5e491647da9a16126a8bda9c533b4e839e2f4c, wouldn't `pcall` work?

**Comment by PeridexisErrant** [comment]
I didn't know of `pcall` or `dfhack.findScript`, but the latter works perfectly by returning a bool.  Thanks.
