### ISSUE TITLE
Workflow melt-designation system

### ISSUE THREAD

**Issue by seylerius** [DFHack/dfhack#573]
This is a feature idea for Workflow: the ability to track counts of object designations, such as dump and melt. This would be accompanied by reverse constraints, allowing the user to set a constraint that resumes "Melt an object" in your smelters when meltable objects are designated. Combine this with the auto-melt stockpile for maximum win.

**Comment by PeridexisErrant** [comment]
Doesn't this already happen when you have a constraint-less repeat melt job?  Workflow should prevent it being cancelled, and then automatically resume it when reagents are available.

**Comment by seylerius** [comment]
The addition of stockflow resolved this. Hooray!
