### ISSUE TITLE
tweak: Confirmation when seizing/offering trade goods

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#577]
Currently waiting on #643

**Comment by PeridexisErrant** [comment]
Potentially also when offering goods to a caravan?

**Comment by lethosor** [comment]
:+1:

**Comment by lethosor** [comment]
I put together a separate plugin for this, which behaves similarly to the tweak and search plugins. I'm hoping to implement a few more confirmations before merging it (e.g. hauling route deletion), but the two discussed here are implemented.
