### ISSUE TITLE
lua plant_tree_info.body is one-dimensional rather than two

### ISSUE THREAD

**Issue by Qrox** [DFHack/dfhack#597]
When accessing `plant_tree_info.body[index]` in lua scripts, the return value will be a single `plant_tree_tile`, rather than an array of `plant_tree_tile` containing all the information on that z-level. This renders scripts which want to get detailed information about a tree's form invalid. This is also the case with `plant_tree_info.roots`.

**Comment by lethosor** [comment]
This is a known limitation of "2-dimensional" arrays exposed to Lua (i.e. a pointer to a pointer in C++). I'm not entirely clear on what the correct way of handling this is, but I think it's
```lua
array[x].value:_displace(y)
```

**Comment by Qrox** [comment]
Thanks for you information! I'm quite new to lua so I didn't ever have known that...

**Comment by lethosor** [comment]
Well, it's a DFHack-specific issue, not something you'd encounter with normal lua tables. It should probably be documented better.

**Comment by PeridexisErrant** [comment]
Closable with the addition of a note to the Lua API document?

**Comment by warmist** [comment]
That is not exactly correct. Some arrays are so called "flat" i.e. the array is stored as one dimensional. But it depends on case to case basis and it's largely depends on how Toady One programmed each part.

**Comment by PeridexisErrant** [comment]
Hmm.  Got a better description I can stick in, even if it's just noting that some are complicated and it's hard to tell in advance?

**Comment by warmist** [comment]
It's hard to tell. Usually you need to know why/how it came into being. E.g. there is loads of stuff that is closely packed and small. This includes tree tiles, designations, room extents etc... All of these are very fast if held in flat arrays. Big stuff (like chunks of map) do not benefit that much from being in flat array so they are not. 
Usually the element type indicates that: `stuff[][][]` is 3d array and you can access it by `stuff[x][y][z]` while `stuff[]` where you know that it might be 2d thing is usually flat array.
