### ISSUE TITLE
Is autolabor working in 0.40.24?

### ISSUE THREAD

**Issue by FredZeppelin** [DFHack/dfhack#598]
I have autolabor enabled, and mining designated for a bunch of squares, but autolabor never turns mining on for my miners. In fact, if I manually enable it, autolabor seems to turn it off...

**Comment by FredZeppelin** [comment]
Unfortunately this makes autolabor pretty much unusable at the current time for obvious reasons. :(

**Comment by PeridexisErrant** [comment]
Closed by #610
