### ISSUE TITLE
burrow auto-grow not working

### ISSUE THREAD

**Issue by TruePikachu** [DFHack/dfhack#601]
Getting back into DF, but it doesn't appear that my old method of making a safety burrow - a burrow named "Safe +" with `burrow enable auto-grow` - is working. I just watched a miner dig a square which did not result in the expansion of the burrow.

**Comment by TruePikachu** [comment]
Using a collection of out.print() statements, it appears to me that handle_dig_complete (in burrows.cpp) isn't being called. It is registered to what I'm assuming is the Lua event `onDigComplete`.

**Comment by TruePikachu** [comment]
Okay, I've diagnosed the problem to DFHack not reconising dig jobs anymore. `detect_digging` gets called, but none of the `print`s get executed (ofc when uncommented). When I figure out how to, I'll try to get Windbg to help with this.

**Comment by TruePikachu** [comment]
Every time the `if(Job::listNewlyCreated(...))` passes, I get the `job_type_class::Digging` match, but there is never a worker. The job then gets completed without being checked for a worker again.

**Comment by lethosor** [comment]
It probably has something to do with designation jobs being queued (but hidden from the job list) before assigning a worker. @BenLubar noticed something similar with plant gathering jobs.

**Comment by TruePikachu** [comment]
I was going to try coding up a fix for the plugin, but I'm probably not the best person to code something efficient and not likely to break everything.

My idea of the implementation would be to, in a vector (or a set as suggested by angavrilov on IRC) store the digging jobs that were discovered, and then (outside the `listNewlyCreated`) check said vector/set's jobs to see which ones now have a worker.

**Comment by ab9rf** [comment]
I am going to take a look at this one soon and see if I can come up with a fix.

**Comment by expwnent** [comment]
It should probably use EventManager's job created event in any case.

**Comment by lethosor** [comment]
What about the "job completed" event (assuming it works)? It looks like the "job initiated" event just checks for newly-created jobs (with IDs higher than the last ID checked), which is basically what `burrows` is doing already.

**Comment by expwnent** [comment]
Yes, that should work.

**Comment by myk002** [comment]
Fixed in https://github.com/DFHack/dfhack/pull/3948

the issue was that the code was ignoring jobs if it happened to see it before it got a worker assigned. this is most jobs, so it tended to miss a lot.
