### ISSUE TITLE
Does not compile on Debian x86_64 - protobuf not linking to pthread

### ISSUE THREAD

**Issue by Envite** [DFHack/dfhack#602]
Gives an error about threads when compiling protoc with gcc 4.9.2 on Debian amd64:

$ LANG=C make install
[ 10%] Built target lua
[ 20%] Built target protobuf
[ 24%] Built target protobuf-lite
[ 30%] Built target protoc
Linking CXX executable protoc
libprotoc.so: undefined reference to `pthread_once'
collect2: error: ld returned 1 exit status
make[2]: *** [depends/protobuf/protoc] Error 1
make[1]: *** [depends/protobuf/CMakeFiles/protoc-bin.dir/all] Error 2
make: *** [all] Error 2

$ LANG=C gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.9/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 4.9.2-10' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --with-arch-32=i586 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.9.2 (Debian 4.9.2-10)

**Comment by Envite** [comment]
I have looked at
http://code.google.com/p/open-lighting/issues/detail?id=52
but don't know how to use that in this case with cmake.

**Comment by Envite** [comment]
Finally was able to build it:
at
build/depends/protobuf/CMakeFiles/protoc-bin.dir/link.txt
I added
-lpthread
at the end of the line

**Comment by lethosor** [comment]
What's the point of "LANG=C"? A large portion of DFHack is written in C++, not C.
Also, build/depends/protobuf/CMakeFiles/protoc-bin.dir/link.txt is a generated file, which _will_ be overwritten by CMake. I'm not entirely sure what the issue is there - if libpthread wasn't available before running cmake, running it again could fix the issue, but it sounds like that's not the case.

**Comment by Envite** [comment]
LANG=C is to avoid program output in my native language. C is the standard locale.

**Comment by Envite** [comment]
* libpthread was available before running CMake.

* I edited the link.txt file after it was gnerated by CMake, but in the point of failure of make install.

**Comment by NCommander** [comment]
I won't try building DFHack in a native amd64 environment; while it IS possible, multilib has a lot of things in places -m32 won't look for it. I gave up trying to do this, and just built an Ubuntu i386 precise chroot (to get GCC 4.5) and build in that.

**Comment by lethosor** [comment]
Looks like this exact issue was reported back in 2014: http://www.bay12forums.com/smf/index.php?topic=139553.msg5434625#msg5434625

**Comment by lethosor** [comment]
Is this referring to x86_64 or something else? Travis (64-bit Ubuntu) doesn't have this issue, so you could see if https://github.com/DFHack/dfhack/blob/develop/.travis.yml helps at all.

**Comment by lethosor** [comment]
Hopefully the recent x64 support and #992 have fixed this, but feel free to reopen this issue if not.
