### ISSUE TITLE
Linux build error -- missing depends/jsonxx/CMakeLists.txt

### ISSUE THREAD

**Issue by muehlber** [DFHack/dfhack#603]
I updated my repository to a1fd1d9219883470aff60feb0ebabb79e78741d7 and tried to re-build it:

tmp/dfhack/build$ cmake .. -DCMAKE_BUILD_TYPE:string=Release -DCMAKE_INSTALL_PREFIX=/usr/local/df
-- The C compiler identification is GNU 4.7.2
-- The CXX compiler identification is GNU 4.7.2
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found ZLIB: /usr/lib/i386-linux-gnu/libz.so (found version "1.2.7") 
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found.
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
CMake Error at depends/CMakeLists.txt:7 (add_subdirectory):
  The source directory

    /tmp/dfhack/depends/jsonxx

  does not contain a CMakeLists.txt file.

-- Configuring incomplete, errors occurred!

**Comment by lethosor** [comment]
Did you update submodules (git submodule update)?

**Comment by muehlber** [comment]
Yes I did. But I didn't notice that there was a new submodule and I didn't do "git submodule init" again. Problem solved. All good.
