### ISSUE TITLE
auto stairs

### ISSUE THREAD

**Issue by soul4hdwn** [DFHack/dfhack#609]
this didn't happen in non hacked dwarf fortress, then again i haven't actually performed anything in this specific order:
 z0 : set of upstairs for intent of making a sitern.
z-1 : same thing but not aligned, as in, its a few y or x away from overlapping in z axis.
z0 : realized the silly as i was making a single up/down stair in center, and swapped to channel of only one row.
unpaused game (it was paused manually instead of the normal menu pause), dwarves dig and everything looks fine and normal. poorly made diagram:
```
<<<<< z0
<<<<<
.▼x▼.
<<<<<
<<<<<
█<█<█
<█<█<
█<<<█ culprit later on
██<██ inflow of water here

█████ z-1
█████
<▲<▲<
<<<<<
<<<<<
<<<<<
<<<<< middle tile here lines up with "cuprit" above
```
decide to poke into the brook and bring water to above setup, mind you it looked just like this.
water flows in as expected but for some reason fills up z-1 first. i find out why too late, all tiles of the z-1 rows of up stair that lined up with respective up stairs above (specially the "culprit" middle tile), became an X or an updown stairs.

checked through normal dwarf fortress bug reports and didn't find this unique behavior.
mind you it was easy to "recover" from via removing fluids and applying a wall at the trouble making spot.  it was just "fun" from the unexpectedness.

**Comment by lethosor** [comment]
I don't think this is DFHack-related unless you were using something like `tiletypes` to edit those tiles. It's more likely that you accidentally designated up/down stairs or it's a DF issue (although, like you, I haven't seen it on Mantis).
