### ISSUE TITLE
'/' character is not treated correctly in saved stockpile setting names

### ISSUE THREAD

**Issue by flarn2006** [DFHack/dfhack#621]
I tried to save a custom stockpile as `Furniture/goods/bars`, but it gave me the error "Couldn't save. Does the folder exist?"

I figured it was because it was misinterpreting the `/` character as a directory separator. This was confirmed when I attempted to give one a name beginning with `../` and found the file saved in the main Dwarf Fortress folder rather than the `stocksettings` folder.

Given that `/` can be a common character in stockpile names (as in the case I gave) I'd say this is something that ought to be fixed.

Perhaps a separate "display name" can be added to the files that can contain characters that otherwise wouldn't be valid in filenames. At the very least the error message should be changed to something less confusing, like "Invalid character detected in name."

**Comment by lethosor** [comment]
I made a few changes that hopefully address this:
* The input box now filters out invalid characters - currently, valid characters include `A`-`Z`, `a`-`z`, `0`-`9`, `_`, `-`, space, and `.`, although that can be changed.
* For stockpiles that already have names (which seems to be the issue you were having), any invalid characters are replaced with `-`
