### ISSUE TITLE
Can't search noble suggestion menu for particular dwarves

### ISSUE THREAD

**Issue by pineapplemachine** [DFHack/dfhack#622]
A liaison visited my fort and wanted suggestions for elevation to baron, but there was no way to search in the list and trying to find one out of 150 dwarves is of course horrible.

**Comment by lethosor** [comment]
Can you upload a save before this occurs? I think this is a separate screen, so reproducing it from scratch would be very difficult. (A save from another report on the DF bug tracker could also work.)

**Comment by pineapplemachine** [comment]
https://dl.dropboxusercontent.com/u/10116881/temp/suggest-nobles-screen-save.zip

Allow the liaison to meet with the mayor and the screen should appear. The mayor is a vampire and is locked in her quarters just north of the location the hotkey F3 corresponds to.
