### ISSUE TITLE
In the enhanced stock screen, allow filtering by exact matches

### ISSUE THREAD

**Issue by pineapplemachine** [DFHack/dfhack#624]
For example, it would be helpful to be able to view "granite" but not "granite coffin".

**Comment by pineapplemachine** [comment]
Filtering by item type would be helpful too, like searching for all armor or for all refuse

**Comment by lethosor** [comment]
Done in 4e45cc5 - you can now search for `^granite$` to match only "granite" (although `granite$` is usually sufficient).
