### ISSUE TITLE
hack-wish: rename to gui/create-item or something similar

### ISSUE THREAD

**Issue by Putnam3145** [DFHack/dfhack#634]
A *lot* of questions are asked about create-item that could easily be solved with hack-wish, but the utterly opaque name from when it was supposed to be a more broad script makes it very unclear as to what it's actually supposed to be. Renaming it to create-item would alleviate this issue.

**Comment by Putnam3145** [comment]
(issue instead of pull request since it seems like something that warrants discussion)

**Comment by lethosor** [comment]
:+1:

**Comment by PeridexisErrant** [comment]
Closed by #638?
