### ISSUE TITLE
[Adventure] gui.getSelectedUnit() not working.

### ISSUE THREAD

**Issue by runedog48** [DFHack/dfhack#644]
It won't work. Tried using every menu etc, didn't work, didn't work when I used both L and K with the crosshairs on my unit. Am I missing something? ( I didn't bother testing fort mode )

"No unit is selected in the UI"

**Comment by lethosor** [comment]
You have to actually press letters in the `l` menu to select a unit, since there's no cursor in that menu that can be used to select a unit if there are multiple units on a tile. The `k` menu won't work for the same reason.

**Comment by runedog48** [comment]
I think I had it working a few weeks ago, but I pressed L, then pressed A which selects myself, and then attempted to use gui\hack-wish, and it did not detect the unit

**Comment by runedog48** [comment]
https://www.dropbox.com/s/7605jgqkri9dlgb/Screenshot%202015-06-22%2017.40.35.png?dl=0

**Comment by lethosor** [comment]
It works for me on that exact screen in 5bb5d87. I don't see any related changes, but you could try replacing your version of the script with [the latest version](https://github.com/DFHack/dfhack/blob/develop/scripts/gui/create-item.lua). It's been renamed to `gui/create-item`, but that shouldn't make a difference.

Also, you should use forward slashes in command names for portability, although it won't be as much of an issue in the next release.

**Comment by runedog48** [comment]
Didn't work. I didn't mention that I'm using the DBZ mod, but I highly doubt that would affect this.

**Comment by lethosor** [comment]
What does ´lua dfhack.gui.getCurFocus´ return?

**Comment by runedog48** [comment]
Nothing.

**Comment by lethosor** [comment]
Oh, you have to print it. Try `lua print(lua dfhack.gui.getCurFocus())`.

**Comment by runedog48** [comment]
I'm assuming you meant lua print(dfhack.gui.getCurFocus()) which returned dfhack\lua

**Comment by lethosor** [comment]
Yep. If it's returning dfhack/lua, that means there's a lua (DFHack) screen on top of the current screen. Are you running any scripts like this? (It's possible that that mod includes some - check dfhack.init.)

**Comment by lethosor** [comment]
Yeah, it looks like that mod implements a screen like that. 
cc @Putnam3145

**Comment by runedog48** [comment]
That's unfortunate. Is there another way to reference my unit?

**Comment by lethosor** [comment]
Strange, it looks like [this](https://github.com/Putnam3145/SPARKING-Dwarf-Fortress-DBZ-mod/blob/e9640699c247f1934955991c5aa7743c4a51b4af/raw/scripts/dragonball/dwarf_scouter.lua#L173-L175) should make this work, assuming I'm looking at the right viewscreen. Are you using the latest version of that mod?

**Comment by lethosor** [comment]
Turns out that was added two days ago. Try replacing dwarf_scouter.lua with the most recent version ([here](https://github.com/Putnam3145/SPARKING-Dwarf-Fortress-DBZ-mod/blob/e9640699c247f1934955991c5aa7743c4a51b4af/raw/scripts/dragonball/dwarf_scouter.lua)).

**Comment by runedog48** [comment]
Thank you!
