### ISSUE TITLE
Stonesense segfault on OS X

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [DFHack/dfhack#649]
I'm getting the same segmentation-fault described later-on in #576; but I wanted to open a new Issue to record it. As soon as I invoke `stonesense` at the DFhack prompt, I get a segmentation-fault:

    [DFHack]# stonesense
    Stonesense launched
    Using allegro version 5.0.9 r1
    !! /opt/homebrew-cask/Caskroom/dwarf-fortress/0.40.24/df_osx/dfhack: line 15: 20843 Segmentation fault: 11  DYLD_INSERT_LIBRARIES=./hack/libdfhack.dylib ./dwarfort.exe "$@"

Here are the CLI-output, `stdout.log`, and `stderr.log`, from my original invocation: [f9c3c46d9ae019f6357d](https://gist.github.com/ELLIOTTCABLE/f9c3c46d9ae019f6357d)

Here's the same, as well as the OS X ‘crash report’ (basically, stack trace) from the same command, with `DFHACK_LOG_MEM_RANGES` enabled: [03471f43b7fd30c8229a](https://gist.github.com/ELLIOTTCABLE/03471f43b7fd30c8229a)

I'm running a freshly-installed ([via Homebrew](https://github.com/caskroom/homebrew-cask/blob/325b4dd13020b197ef7a858f50581504280350f6/Casks/dwarf-fortress.rb)) `v0.40.24` of DF, with DFhack from `dfhack-0.40.24-r3-OSX`.

**Comment by ELLIOTTCABLE** [comment]
Note: I tried to use the prebuilt and updated `liballegro.5.0.11` files that @lethosor suggested, downloaded from [here](https://www.mediafire.com/?nacwjdazayz9fz7), but those weren't built for my arch, and I'm not sure how to go about building them:

Output:

    Can't load plugin /opt/homebrew-cask/Caskroom/dwarf-fortress/0.40.24/df_osx/hack/plugins/stonesense.plug.dylib

`stderr.log`:

    dlopen(/opt/homebrew-cask/Caskroom/dwarf-fortress/0.40.24/df_osx/hack/plugins/stonesense.plug.dylib, 6): Library not loaded: /Volumes/MacintoshHD/brew-mavericks/lib/libfreetype.6.dylib
      Referenced from: /opt/homebrew-cask/Caskroom/dwarf-fortress/0.40.24/df_osx/./hack/libs/liballegro_ttf.5.0.dylib
      Reason: no suitable image found.  Did find:
        /usr/local/lib/libfreetype.6.dylib: mach-o, but wrong architecture
    Can't load plugin /opt/homebrew-cask/Caskroom/dwarf-fortress/0.40.24/df_osx/hack/plugins/stonesense.plug.dylib

**Comment by lethosor** [comment]
What's missing is a 32-bit version of libfreetype. Try updating the SDL_ttf library from [here](https://www.libsdl.org/projects/SDL_ttf/release-1.2.html).

**Comment by ELLIOTTCABLE** [comment]
@lethosor hm, I'm averse to manipulating /Library/Frameworks; is there a pre-built `SDL_ttf` that I can drop into `df_osx/hack/libs/` instead? Or, alternatively, a way to use a Homebrew-built SDL? (I've got `libSDL_ttf-2.0.0.dylib` in `/usr/local/Cellar/sdl_ttf/2.0.11/lib`, but I'm not too familiar with how dynamic linking works, and how to get DFhack to *use* that.)

**Comment by lethosor** [comment]
> is there a pre-built SDL_ttf that I can drop into df_osx/hack/libs/ instead?

That is exactly what I linked to (download [SDL_ttf-2.0.11.dmg](https://www.libsdl.org/projects/SDL_ttf/release/SDL_ttf-2.0.11.dmg) and drop SDL_ttf.framework into DF/libs/, or DF/hack/ - DF/hack/libs/ probably won't work, unless you modify the `dfhack` script).

**Comment by ELLIOTTCABLE** [comment]
Do I need to remove `liballegro_ttf`? It's still not working; same error:

    dlopen(/opt/homebrew-cask/Caskroom/dwarf-fortress/0.40.24/df_osx/hack/plugins/stonesense.plug.dylib, 6): Library not loaded: /Volumes/MacintoshHD/brew-mavericks/lib/libfreetype.6.dylib
      Referenced from: /opt/homebrew-cask/Caskroom/dwarf-fortress/0.40.24/df_osx/./hack/libs/liballegro_ttf.5.0.dylib
      Reason: no suitable image found.  Did find:
	/usr/local/lib/libfreetype.6.dylib: mach-o, but wrong architecture
    Can't load plugin /opt/homebrew-cask/Caskroom/dwarf-fortress/0.40.24/df_osx/hack/plugins/stonesense.plug.dylib

**Comment by lethosor** [comment]
Removing liballegro_ttf will break Stonesense. Did you update SDL_ttf? If you did, you could try adding `libs/SDL_ttf.framework/Frameworks` to DYLD_LIBRARY_PATH in the `df` and `dfhack` scripts.

**Comment by lethosor** [comment]
Actually, SDL_ttf would only fix DF's libfreetype dependency, not allegro's - is there a `libfreetype.6.dylib` in hack/libs? Try copying that to the `libs` or `hack` folders.

**Comment by ELLIOTTCABLE** [comment]
Success! (For future reference: copying `df_osx/hack/libs/libfreetype.6.dylib` to `df_osx/hack`, and then replacing `df_osx/hack/libs` with the unpacked contents of `liballegro.5.0.11` provided above.)

I can finally try Stonesense! So excited! <3
