### ISSUE TITLE
Game crashes when searching units list

### ISSUE THREAD

**Issue by Ravendarksky** [DFHack/dfhack#650]
I pressed u -> q then started typing the nickname of one of my dwarfs and the game crashed,

I presume this is a DFHack issue and not a dwarf fortress one?

http://i.imgur.com/PzQTiPv.png

**Comment by lethosor** [comment]
What did you type?

**Comment by Ravendarksky** [comment]
'Man' without the quotation marks. It crashed on third letter but none of
them showed up in the screenshot.

**Comment by lethosor** [comment]
Maybe it has something to do with the "inactive" row at the top. Did you just cancel a job on that screen with `x`?

**Comment by lethosor** [comment]
Yeah, that's it - the "Inactive" row corresponds to a null pointer in the screen's unit list, which the search plugin isn't taking into account.

**Comment by lethosor** [comment]
Fixed for the next release.

**Comment by Ravendarksky** [comment]
Thanks for fixing it =D. I take it there is no way to stop DFHack crashes from crashing out dwarf fortress? It's hard sometimes to even tell which program is causing Dwarf fortress to crash. It's frustrating to not have enough info to post bug reports!

**Comment by lethosor** [comment]
No, but you might be able to obtain stack traces to figure out where DF is crashing. I'm not sure how to do this on Windows, but OS X generates crash reports with this information by default and there's a library that can be preloaded to obtain stack traces fairly easily on Linux (and OS X). [This](http://stackoverflow.com/a/24209279/1923914) might help on Windows (`procdump -ma -i c:\dumps`), or there could be other ways to obtain information.
