### ISSUE TITLE
Not a known DF version

### ISSUE THREAD

**Issue by AkelD** [DFHack/dfhack#653]
(First time posting here, I don't know how to put labels but I guess that using [] should be it)
I downloaded the DF Lazy newb pack, but I get a "Not a known DF version" error when I launch it. My computer is a windows XP machine.
> Contents of Stderr.log:
> FirstCall()
> Initized HOOKS!
> Identifying DF version.
> Loading hack\symbols.xml ... OK
> Loaded 3 DF symbol tables.
> Not a known DF version.
> DFHack will now deactivate.

And Error.log (http://pastebin.com/nNcwS19) and symbols.xml (http://pastebin.com/e1JxPCYj)

**Comment by lethosor** [comment]
Is there anything else in stderr.log? What's the md5 of the DF executable?
(Only people able to push to this repo can add labels - there isn't a way to change that, as far as I know.)

**Comment by AkelD** [comment]
huh.
>>md5 "Dwarf Fortress.exe"
>64EFAFAA4F8D57A0FD13640FBB25B10F  Dwarf Fortress.exe
So I downloaded it again, but it gave me the same error so I tried again
>>md5 "Dwarf Fortress.exe"
9DE8E2E7F90B6E15782A2F30EFE8A31B  Dwarf Fortress.exe
I have to download DF from http://www.bay12games.com/dwarves/df_40_24_win.zip , right?

**Comment by fricy** [comment]
If you use the [Lazy Newb pack/DF Starter pack](http://lazynewbpack.com/) you shouldn't need to download DF at all, it's a standalone package containing everything you need to play. Are you trying to use an older package release with df 40.24? That'd explain your problem. (though the xml you pasted looks about right)

**Comment by AkelD** [comment]
I downloaded the lastest version, and I've already updated DF and DFhack separately.
There isn't much to exaplain really, I downloaded DFhack, got that problem, updated DFHack, and when that didn't work I asked here.

**Comment by lethosor** [comment]
Is there anything else in stderr.log?

**Comment by AkelD** [comment]
Noup, only what I posted, sorry for not answering earlier.

**Comment by lethosor** [comment]
A fresh download of df_40_24_win.zip still gives me a DF executable with an MD5 of 0fc323ab830e1d072eccc288b00fe060, so your executable is either being modified somehow or your MD5 results are incorrect (which is unlikely). Are you using any antivirus programs? Does DF start without DFHack?

Also, why did you update DFHack? Doesn't PeridexisErrant's pack come with DFHack r3?

**Comment by AkelD** [comment]
At first I had assumed than it had some old version that was causing the issue or something, so I downloaded it directly from the releases page.
And as far as I know (My task manager checks every executable on virus total) there isn't any virus on my computer, and the instalation is less than a month old.
I'll check with clamwin anyway, just in case.

**Comment by lethosor** [comment]
I mean, is it possible that any antivirus programs are modifying the executable?

**Comment by AkelD** [comment]
I am not running any active antivirus, got tired of their invasive crap years ago. The clossest thing would be Process Explorer's totalvirus checking and some clamwin scan from time to time..

**Comment by lethosor** [comment]
Is the MD5 of the zip file you downloaded 90b3dce682e0a8ab4e8d8be9a43abc55?

**Comment by AkelD** [comment]
>90b3dce682e0a8ab4e8d8be9a43abc55
Exactly the same.

**Comment by PeridexisErrant** [comment]
@lethosor - time to close this, after months with no new information?

**Comment by lethosor** [comment]
If this is still an issue, it's most likely that there's an issue with the executable on your machine, given that DFHack works normally for others. Make sure you're using DFHack 0.40.24-r3 and the Windows SDL build of DF 0.40.24 (which it sounds like you are, assuming you're using the one from the archive with the MD5 of 90b3dce682e0a8ab4e8d8be9a43abc55).
I added some more debugging information in the commit above - it should log the actual PE timestamp of the executable you're using, so you could add it to symbols.xml if you're certain you have the right executable. (There might also be a way to do this in r3.)
