### ISSUE TITLE
Woodcutter bugs, possibly related to autochop.

### ISSUE THREAD

**Issue by RogueYun** [DFHack/dfhack#656]
So I am experiencing a bug where my woodcutter dwarves go to cut down the same trees and sometimes try to cut down trees that are already cut down. Shutting off autochop, clearing the designations, and manually designating the trees to be cut down again seems to clear the issue.

**Comment by lethosor** [comment]
Are the trunks of these trees multiple tiles wide?

**Comment by RogueYun** [comment]
No, they were single tile widths if I recall correctly. It has been a long while, shall I try to duplicate the bug?

**Comment by lethosor** [comment]
It's slightly possible that this could be #741, if you're using workflow. Other than that, I haven't used autochop much, so I'm not sure what the issue is.
@Falconne: I don't know how much work you've done with autochop since 0.40.01, but do you have any ideas?

**Comment by Falconne** [comment]
I haven't done any changes since before the release of 0.40 so it's quite possible that the plugin needs some updating to work with 0.40 properly. I would have suggested multi tile trees being the problem too, as that wasn't something the plugin knew about.

**Comment by lethosor** [comment]
Yeah, it doesn't appear to have been updated since 9956b4a5ef874e8ff6e4530dadd3438609217f3f, which mostly involved organization from what I can tell (although it may have also accounted for tile type changes).

**Comment by RogueYun** [comment]
I managed to find my old save I turned up the auto chop so my guys would start cutting down trees again. Looks like workflow and auto-labor are on. A dwarf cuts down a tree, and when he is finished he walks a few steps away and comes back to the same spot with the job of "Fell Tree." This was an older version of DFHACK though...

Tested it in the new dfhack and it has the same result.

**Comment by lethosor** [comment]
Oh, it's probably not the workflow issue if it's the same dwarf. Can you upload the save somewhere?

**Comment by RogueYun** [comment]
Well, here is the old save:
https://drive.google.com/file/d/0B1-Saj70NtEXWEZwaE5VZFlTM2c/view 

Here is my whole df directory just in case that helps:
https://drive.google.com/file/d/0B1-Saj70NtEXOUQ4VUpkalQ4TzQ/view

You might have to up the number of logs in autochop, but everything else should be configured correctly.

**Comment by lethosor** [comment]
This looks like it's the issue that came up in #1030, #1014, #1018, and some others. I believe I have fixed it now, so it should be good for the next release.
