### ISSUE TITLE
Seg fault on window resize

### ISSUE THREAD

**Issue by plaguewolf** [DFHack/dfhack#657]
also posting on stonesense issues here: https://github.com/DFHack/stonesense/issues/41

arch linux, DF and DFhack built from latest source on github.

everything runs fine, i launch stonesense and i can use the mouse to scroll and select and stuff.

then i try to grab the window and resize it and boom

[DFHack]# ./dfhack: line 43: 9667 Segmentation fault (core dumped) setarch i386 -R env LD_PRELOAD="$PRELOAD_LIB" ./libs/Dwarf_Fortress "$@"

**Comment by lethosor** [comment]
I'd prefer to keep Stonesense issues on the Stonesense tracker.
