### ISSUE TITLE
Hack-Wish doesn't set the items quality.

### ISSUE THREAD

**Issue by runedog48** [DFHack/dfhack#662]
It doesn't seem to apply the quality you select. Everything you spawn has the normal quality.

**Comment by lethosor** [comment]
What items are you creating?

**Comment by runedog48** [comment]
Pretty much everything I spawn I try to give masterwork, but it doesn't show on the item that's it's masterwork. I've tried various weapons such as spears, swords, scimitars, I tested it on a trumpet, and I've tried spawning masterwork armors such as high boots and helms.

**Comment by lethosor** [comment]
This was already fixed in #605

**Comment by lethosor** [comment]
I did have a few issues with that fix, though, so I updated the script to use a more reliable method. It also supports the esc key properly, which is nice.
