### ISSUE TITLE
Add legends-mode script based on recent work by Mifki

### ISSUE THREAD

**Issue by PeridexisErrant** [DFHack/dfhack#663]
>Did you know it's possible to do

>`w=dfhack.gui.getCurViewscreen() ; w.child=df.viewscreen_legendsst:new() ; dfhack.gui.getCurViewscreen().parent=w`

>and get a fully functional Legends screen? There was couple question about how to get more info about outer world recently. The only thing you can't use ESC to close the screen, instead, use 

>`dfhack.gui.getCurViewscreen().breakdown_level=2`

>Someone needs to make a convenient script.

[Forum thread.](http://www.bay12forums.com/smf/index.php?topic=152386)

**Comment by lethosor** [comment]
> dfhack.gui.getCurViewscreen().breakdown_level=2

That's exactly what Screen:: dismiss() does.

**Comment by lethosor** [comment]
Posting this here as well: https://github.com/lethosor/dfhack-scripts/blob/master/open-legends.lua
