### ISSUE TITLE
Allow "fastdwarf 1" and teledwarf to apply to other creatures/races

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#664]
https://www.reddit.com/r/dwarffortress/comments/3ftnsa/is_there_any_particular_version_of_df_that_you/ctsinx1

**Comment by lethosor** [comment]
Yeah, the check is for "citizens", not any specific race: https://github.com/DFHack/dfhack/blob/ba629b8e0a022e8891d7177ebc58f53cc923244b/plugins/fastdwarf.cpp#L54

**Comment by myk002** [comment]
I thought the intent behind this request was to make `fastdwarf` apply to residents as well. `getCitizens` now includes residents by default.
