### ISSUE TITLE
Improve project structure; ensure documentation is clear and complete

### ISSUE THREAD

**Issue by PeridexisErrant** [DFHack/dfhack#670]
~~The `startdwarf` script is completely undocumented, as is the `hide` command.~~  *Fixed by #671*

Where there's two, there's probably more - it would be good if someone checked that each script, plugin, or command is at least mentioned in the readme to not it's existence, and preferably include some basic information.

This issue has evolved into part of a larger discussion of DFHack structure.  See the thread of comments and forum links in #667 for more information.

**Comment by lethosor** [comment]
A lot of internal commands aren't listed, so I'd like to keep this open.

**Comment by PeridexisErrant** [comment]
It occurs to me that #667, including 3rd party scripts, is going to cause some documentation headaches too.  We probably want to include a link to their documentation in the main readme, if not the full description of each script.

**Comment by PeridexisErrant** [comment]
...counting scripts shows 34 of 54 documented.  At this point, I'm thinking we might want to generate the documentation from the scripts (and make missing docs in the script a linting error).

The least-case would be to require a readme entry and current NEWS entry for any plugin or script modified by a pull request.

(I still plan to make another pull request with scripts and plugins documented, FWIW)

**Comment by PeridexisErrant** [comment]
Follow #674, all scripts in the general and fix/* directories are documented in the readme, and the existence of `devel/*` is noted.  It doesn't completely resolve the associated issue - `gui/*` scripts, plugins, and builtin commands still need to be checked.  Someone should also decide to what extent the `modtools/*` should be documented.

I'd be happy to handle the gui scripts in a separate pull request as it would involve substantial changes to the structure of the readme and I'd want some more review. Plugin documentation is similarly scattered, and could be (mostly, I'm not fluent in cpp) handled at the same time. Someone else would have to handle builtin commands.

**Comment by expwnent** [comment]
Manually checking each and every script/plugin would take a long time and it's monotonous enough that we're likely to make mistakes if we do it all at once and if we don't do it all at once it's easy to miss things. Maybe we should include a temporary "documentation confirmation todo list" file and manually check at least a handful of them every so often and cross them off as we do so it's easier to make and share progress.

The current system is basically just waiting for someone to complain about a hole in the docs then filling it, which is a bad way of doing things.

**Comment by PeridexisErrant** [comment]
Hmmm.  We may want to re-organise the Readme, since plugins and some scripts are scattered all over, and it can be hard to find what you're after.  Would functional prefixes/directories for plugins (as scripts are *meant* to use - that needs to be audited) make sense?

Either way, it should be fairly easy to write a linter script that checks every script (and plugin?) source file has a corresponding heading in the readme.

**Comment by expwnent** [comment]
Yeah, that would help.

**Comment by PeridexisErrant** [comment]
#667 has been merged - this is good, but will make documentation somewhat more complicated.  I plan to look into options for better tooling eventually, but should get to the doc-checker script a little sooner.

Policy changes I think we should consider in the short term:

1. Require all script and plugin filenames to appear in the readme (the above doc-checker)
2. Remove old alias commands and obsolete tools  (eg `digvx` - on both counts) 
3. Reorganise the readme
  * By use-case or by tool type, not the current mixture
  * To cleanly separate core functions and optional scripts or plugins

Finally, here's a idea as to where might want to end up:

* The readme file looks [more like this](https://opensource.com/business/15/6/template-starting-project-documentation), and documentation for tools is split out.
* All scripts and plugins must contain their own documentation, which is accessible through a built in help system reminiscent of man pages.  This also helps with #667.
* Use something like [Sphinx](http://sphinx-doc.org/) to generate comprehensive static documentation for tools
* As well as documenting how to contribute, some examples of how to approach different kinds of tasks.  Eg 'DFHack for beginners', 'for modders', for cheaters, adventurers, builders, historians, hackers, etc. [See this article](https://opensource.com/business/15/5/write-better-docs#types-of-docs); there are obvious differences but we probably want to cover all the major doc types in seperate places rather than the readme trying to do everything.

**Comment by warmist** [comment]
Might as well note that there is such a thing as df-structures. Most often asked thing is how everything there works (i mean the usage not updating part) and the answer usually is just try using gm-editor or lua or looking in headers. We might want to make at least a short tutorial/readme for beginners to get started.

**Comment by maxthyme** [comment]
Yeah, I didn't know how handy just looking through the df-structures files could be despite having switched gm-editor to pull up df.global instead of the no target qerror line. Naturally with appropriate "please don't change stuff in here too much without knowing what it is and what it should do" type warnings.

**Comment by CMDadabo** [comment]
I agree with pointing out the existence of df-structures, and it would be great if there was some beginning documentation explaining the overall structure of the project. Everything started to fall into place once I stumbled on dfstructures, but it's still pretty daunting to pick it all apart.

**Comment by PeridexisErrant** [comment]
#693 adds df-structures to the `Contributing.rst` doc, for pretty much this reason.  I'd love any other feedback about documentation there.

**Comment by PeridexisErrant** [comment]
OK, #697 basically sorts out the documentation for now; [see it here](http://peridexiserrant.neocities.org).  There are still three problems with the docs, each of which could probably have their own issue opened as they might be addressed by different people.

1. Many builtin commands are not documented.  The docs will need to be restructured, or a file added to fix this.  Requires someone familiar with the builtin commands and/or fluent in C++

2. We need some coherent way of categorising plugins. I would suggest splitting them into namespace-like folders as has been done to scripts, starting with the exact same set of categories - we can always add more later.

3. It would be really nice to use autodoc, where the documentation for each script or plugin is stored in the source file for that command.  This could and should be integrated with the help system, so there is a single source for information about each tool.  May also be related to `ls` output.

Random other thoughts...

* Once we have everything else stable - even if not final - adding travis checks for documentation would be nice.

* Sphinx supports cpp files natively, so someone fluent in cpp can probably do a lot with autodoc for the plugins and builtins.  That's not me though.

* The lack of autodoc support for ruby and lua [can be worked around nicely.](https://github.com/PeridexisErrant/dfhack/commit/8306fc07e776848ca602306f796c9e65bfd24dab)  I'm happy to do the grunt work after someone sets up a system and/or standard that works with `help scriptname` - it could just parse the file and spit out the lines between the given markers, for example.

* There's a lot of overlap in the functionality of some plugins and scripts; adding internal links has made this more obvious.  For example the `treefarm` plugin and `autochop` (part of `getplants`), `forceequip` and `modtools/equip-item`, or `autolabor`, `autohauler`, and `autolabor-artisans`.  I feel we should try to combine such tools where practical, turn mostly-duplicated tools into one with optional arguments, and deprecate plugins in favour of scripts where practical.  This is a big job though, and can be done separately from the documentation issues (before or after).

I would consider this issue closed after (1) and (2) above are done, and open new and better-defined issues for the remaining areas of work I've listed.

**Comment by warmist** [comment]
Don't have the time (currently) to look over if it was mentioned or not but we could use lua's flexible string definition to allow for integrated doc strings e.g. "local x=[===[" both assigns the multiline string to x and starts a docstring.

**Comment by PeridexisErrant** [comment]
Is there some more general standard for file-level docstrings in Lua?  All I've been able to find is [this](https://stackoverflow.com/questions/10902079/lua-reflection-function-parameters-and-docstrings) and [this](http://lua-users.org/wiki/DecoratorsAndDocstrings).

Here's my proposed syntax in Lua:

    __doc__ = [[
    .. _begin-doc

    .. _scripts/filename:

    filename
    ========
    Full documentation for the script, examples, ect; all wrapped
    to 72 characters to display in the terminal.  When in the terminal,
    display all lines of __doc__ after removing lines beginning ".. _"
    (link targets, or without the ":" comments used as markers), along with leading
    and trailing blank lines.  This matches the content of the built html.

    .. _end-doc
    ]]

This can then be pulled into the actual documentation file with the rst directive:

    .. include: path/to/script.lua
       :start-after: _begin-doc
       :end-before: .. _end-doc

I'm flexible on the exact markup for a multiline docstring, since I don't know what the standards are or what can be made to work with the built in help system - and it's certainly a good idea to enhance that and follow standards.  On the rst end of things, the `.. include:` directive is just pulling lines from a text file, and keeping those between the specified markers.

We could also use language-specific markers, for Lua `:start-after: __doc__ = [===[` and `:end-before: ]===]`).  This is more concise and forces exactly consistent style, at the cost of requiring a different include spec in the rst document for Ruby and Lua scripts.  I think this trade off is absolutely worth it (and easy to check or generate correct text with a Python script), but I'll leave the decision to you.

**Comment by warmist** [comment]
I'm totally for language-specific markers. Actually i would hate it if there was no and we needed to work around that (e.g. "[=[/**") 
For lua file level docstrings i think it's unnecessary to have anything more complicated than a special "one line comment mark" (e.g. "-->") and have sphinx parse it (and hopefully link to the e.g. function that follows it to extract parameters etc? like doxygen can?)
Those examples show how to implement lua docstrings that can be accessed from lua. We will not have that because usually you (at least I) prefer browsing lua_api vs opening df and typing into lua console (which might be already busy doing something i'm looking api for).

**Comment by PeridexisErrant** [comment]
I feel that we've made a lot of progress and now have a decent sense of what needs to be done.  Unless anyone objects, I'll close this and open issues for more concrete work:

- Categorise and deduplicate plugins; see above for detail.
- Ensure builtin commands are documented.
- Use Sphinx to generate docs for cpp code (core and plugins); should be fairly automatic.
- An ongoing checklist issue for specific topics that should be documented but aren't.
- Getting hosting completely sorted out.  Readthedocs.org is as simple as enabling the corresponding Github webhook, then on that site setting which branches to build (and which are the default docs).  I'd be happy to sort this out given the required permissions; I've recently done so [here](https://df-walkthrough.rtfd.org).

Additionally, I plan to make a pull request in the next few days to cover #703, documentation linting, and move docs building from cmake to a script which can be called by users with fewer dependencies (and by cmake, ofc).
