### ISSUE TITLE
Enabling "Refuse" stockpile option after searching for specific corpse causes program to crash.

### ISSUE THREAD

**Issue by Dardashti** [DFHack/dfhack#678]
I was disabling sentient/unbutcherable corpses from being stored in my butcher stockpile. I accidentally disabled Refuse in the stockpile options. Upon enabling Refuse again, the game crashed.

I'm using the Lazy Newb Pack 40_24 r15, so forgive me if this issue is specific to that mod pack rather than DFHack.

Steps To Reproduce	

1. Make a refuse stockpile. 

2. [q] [s] into stockpile options.

3. Go to Refuse -> Corpses -> and search for any creature.

4. Disable the creature's corpse from being stored in the stockpile with [Enter].

5. While the cursor is still in the rightmost column, press [d] to disable Refuse.

6. Enable Refuse with [e].

7. Crash.

**Comment by lethosor** [comment]
The crash occurs when pressing `d` for me.
