### ISSUE TITLE
An "obsidian" command, which automatically casts walls

### ISSUE THREAD

**Issue by PeridexisErrant** [DFHack/dfhack#680]
Basically a friendlier way to use the liquids plugin, which could be handy for some people.  Bonus points if it uses an in-game interface like the designation-style construction helper.

**Comment by PeridexisErrant** [comment]
Having gone through and actually documented the liquids plugin now, I don't think this is necessary.  It would still be good to deal with issue #80 at some point though.

**Comment by Estevo-Aleixo** [comment]
for those interested the documentation PE mentioned was done here https://github.com/DFHack/dfhack/commit/0307b0830ff13050164945d0a6feb06399cb7d52

**Comment by PeridexisErrant** [comment]
...which was just pulling out and formatting the help from the plugin itself.

**Comment by lethosor** [comment]
>Bonus points if it uses an in-game interface like the designation-style construction helper.

Like the gui/liquids script?
