### ISSUE TITLE
Eventful onReactionComplete changed parameters

### ISSUE THREAD

**Issue by warmist** [DFHack/dfhack#686]
This broke EVERY SCRIPT THAT USES IT!

Can i move the new parameter to the back (better for compatability) ? Or should i update the scripts (could work without new dfhack release though not likely because of packs and users not knowing what to update)?
Or we could only update plugins lua file (i.e. https://github.com/DFHack/dfhack/blob/develop/plugins/lua/eventful.lua#L49 )

Commit: e5e0d93ef1e01386b45f241931dd50ffe04e0652
Doc update: 1bff73cc7a31c8c86b975a2d27e16341cd41b8ec

Scripts that use it: https://github.com/warmist/df-mini-mods
(probably have some more in other places)

**Comment by expwnent** [comment]
I'm sorry but it happened a while ago and fixing it would re-break it.
