### ISSUE TITLE
Are the binpatches gone for good?

### ISSUE THREAD

**Issue by PeridexisErrant** [DFHack/dfhack#698]
Issue #546 and the ongoing distribution of `binpatch.exe` make this somewhat unclear.  On the other hand, the whole patches directory was removed [a while ago](https://github.com/DFHack/dfhack/commit/8a9e3d1a) and there seems to be a resolution not to bring them back - besides the fact that there are no binpatches for the 0.40 series.

I'd appreciate clarity on this.  As a proposal:

* Remaining binpatch-related code will be removed from the repo and future releases
* The issue mentioned above can be closed
* Documentation for binpatch can be deleted

They're just in a zombie limbo state at the moment, and it's time to put them out of their misery.

**Comment by warmist** [comment]
Binpatch code does not need to go: while there are no binpatches that are supported the mechanism is there. Currently there is a lack of developers with enough interest to develop said binpatches for current (and next) releases. However if anyone wants to pick it up it would be better to have the tools available (not requiring hunting through the commits) and easy to use.
I'm not sure about the stand-alone `binpatch.exe` but the `binpatch.lua` (and the supporting c++ code) should be left as is. If documentation references non-existant bitpatches (i.e. the `.dif` files) it should be removed (as it is unlikely that someone will port the them) though be warned that some tweaks loose their meaning without the binpatches (IIRC armorstand tweak needs binpatchs to work correctly).

**Comment by PeridexisErrant** [comment]
Thanks, that's really helpful.

I'll make sure the docs reflect this, including the "contributing to DFHack" guide - I may even pull all the binpatch-related docs into one file so it's really easy to pick up again, and easy to avoid if you're not after that.  Once that documentation is done, I think #546 will be closable.

I'd be inclined to ditch the standalone executable.  My understanding is that it's used to permanently patch the DF executable on disk, while `binpatch.lua` does the patches in memory?  That just sounds like an additional source of potential problems, such as the 'checksum not found' issues we already have documented.

**Comment by warmist** [comment]
You are correct. `binpatch.lua` has only drawback: you need to activate it but usually everyone makes dfhack.init and they are set.
