### ISSUE TITLE
Documentation from Comments

### ISSUE THREAD

**Issue by expwnent** [DFHack/dfhack#703]
There are a few projects out there that do this for Sphinx:

* https://pypi.python.org/pypi/sphinxcontrib-cmtinc/
* https://pypi.python.org/pypi/sphinxcontrib-autoanysrc/
* https://github.com/tlamadon/sphinx-api-any

I like the first one the best because it's the simplest. I think all we'd have to do is this:

    --example.lua
    --[[/** stuff to be extracted
    more stuff
    */]]
    lua code

The goal is that the documentation for a script should be in the script itself. This will minimize the effort it takes to document scripts.

**Comment by expwnent** [comment]
The only thing the above adds is it lets us have multiple separate comments which will all be included.

If we use @PeridexisErrant 's suggestion in #670 [here](https://github.com/DFHack/dfhack/issues/670#issuecomment-143390691) then we can include just one big comment at the top, which is fine for now.

I'd also like to make it so that we don't even have to manually change Scripts.rst with each new script. Maybe some CMake magic with configure_file would work.

**Comment by PeridexisErrant** [comment]
I'll stick to high-level comments here; see above for some detailed examples.

The first link above looks good to me too.  I do think it would be good though to integrate this with standard help functions in the terminal somehow, implying that (a) the string should probably be a variable rather than a comment, which has no impact on the rst text, and (b) it should be *strictly* wrapped to 72 or 80 characters, which obviously does.

My inclination is always to document for users, and comment for developers.  This gets hazy with autodoc and the modtools, but I'd say document anything that doesn't require editing a script and comment everything that does.  USERDOC / CONTRIBUTORDOC just sounds like it's getting overly complex and verbose to me - maybe get the user stuff up and running first, then revisit?

The easiest way to do this is probably add `scripts/**autogen.rst` to `.gitignore`, then in `docs/Scripts.rst` use a `.. include::` directive if we want a single document, or ``toctree`` with glob option if we want each page separate.  I can easily write a function to go in conf.py that generates those pages based on the contents of the script folders at build time.  This seems hacky, but it's going to be more reliable and readable than the other options.

Moving documentation to scripts also requires that we host the built documentation online so *potential* users can find and read it without having to build anything (actual users also have the offline html).  I've already mentioned that readthedocs.org is perfect for this.

**Comment by expwnent** [comment]
Yeah, we can revisit developer docs later.

I just wrote an attempt at making Sphinx auto-extract special comment headers from all lua files in all subdirectories of scripts/. It currently breaks your python script that checks that all scripts are documented and it does not correctly rerun Sphinx when lua files are changed but it's a start.

As for hosting online, see [this link.](http://expwnent.github.io/dfhack/) I'll move it to dfhack as part of the next release process.

I agree linting is good. It's tedious and error-prone to do it manually.

**Comment by expwnent** [comment]
PS: the problem with integrating it with the terminal is that if we do it that way then they can't do rst/Sphinx markup in the BEGIN_DOCS header.

**Comment by PeridexisErrant** [comment]
Breaking that linter isn't an issue; it was only ever a placeholder anyway.  I can write a better one for the new system.  I guess you could force it to re-read scripts every time by `touch`ing Scripts.rst every time conf.py is run, but that's hardly elegant.

I do think [readthedocs](https://docs.readthedocs.org/en/latest/getting_started.html#import-your-docs) has advantages - such as rebuild-on-push webhooks, **per-branch documentation**, and so on - but I've pushed it enough that I'll shut up now.  It's just that using Github Pages, docs are going to have to be updated manually and eventually someone *won't*.  See [here](https://daler.github.io/sphinxdoc-test/includeme.html) and [here](http://blog.nikhilism.com/2012/08/automatic-github-pages-generation-from.html) for the best workarounds I've found.

**Comment by expwnent** [comment]
I'll look into it.

**Comment by expwnent** [comment]
Is there any reason to require documentation in lua files to be a maximum width per line? I just tested it both in Scripts.rst and in a string included from an lua script and it worked fine even with a ridiculously long line. Unless absolutely necessary I don't want to require people to do that because it's tedious and best done by machines and if you want to go back and add or delete a sentence then it makes your paragraphs look terrible.

**Comment by PeridexisErrant** [comment]
file(GLOB SPHINX_DEPS
        ...
        "${CMAKE_CURRENT_SOURCE_DIR}/scripts/**.lua"
      )

Works, after which we don't need the `-a -E` options so partial generation still works.

`**include-all.*` should be added to the 3rdparty script submodule `.gitignore`s, so building docs doesn't pollute the submodules.  Avoid the `.rst` extension if we're including the documents into a single huge scripts file.  Keep it and use the `toctree` directive if we want a separate page of documentation for each directory of scripts.

The current function in `conf.py.in` creates many empty files, files with minimal listings, and so on.  My suggestion is that I write a slightly less general one for the native DFHack scripts, and we sort out the 3rdparty stuff after it's clear how the others work.  I think one page per directory of scripts, and one per submodule would work best.  Thoughts?

Finally - I'd prefer commits related to this stay off the develop branch until it's clear that the prototype works and will scale cleanly to the entire readme.

Re: line width.  This doesn't matter for Sphinx *at all* - until it hits an empty line, everything is wrapped into one paragraph; short long or mismatched does nothing.  IMO it helps in stupid editors/terminals/whatever, but I don't feel strongly enough to argue.  Let people do whatever they want!

**Comment by expwnent** [comment]
Just tried that in CMake again and it fails on Windows. It's equivalent to one * for me.

Is `toctree` compatible with the `include` directive the way we're using it?

`conf.py.in` can be improved but I think it's fine for now.

**Comment by PeridexisErrant** [comment]
Weird, it worked for me on windows.  I agree on leaving things alone; so long as it's working we can make it elegant later.

Yes, it's compatible.  You can see what it'll do by looking at the way the third party docs are linked from Scripts.rst - it would make the same kind of page.

**Comment by lethosor** [comment]
I mentioned this on IRC, but replacing GLOB with GLOB_RECURSE should work.

**Comment by expwnent** [comment]
I'm moving documentation from Scripts.rst to the individual scripts and I'm getting a lot of Sphinx warnings about duplicate labels between Scripts.rst and the files it includes. For example:

../../scripts/modtools/reaction-trigger-transition.lua:6: WARNING: duplicate label scripts/modtools/reaction-trigger-transition, other instance in C:\Games\DF\dfhack\docs\Scripts.rst

Any idea what might be causing that?

**Comment by PeridexisErrant** [comment]
If you haven't removed the old docs yet, it's seeing an identical title in two places.

**Comment by expwnent** [comment]
I don't think that's it. Take a look at the new sphinx branch.

**Comment by expwnent** [comment]
I looked at all three of the above links and they don't work the way we want them to. They don't just textually include the string. For some reason certain formatting isn't allowed.

Note to self: it would be easier to write my own simple C++ program to extract the comments and insert them into the right places.

**Comment by PeridexisErrant** [comment]
Following on from pull #713, I'm nearly done:  [here's the branch](https://github.com/PeridexisErrant/dfhack/compare/NEWS-cleanup...PeridexisErrant:autodoc-upgrade?expand=1).  You can see the preliminary scripts documentation [here](http://peridexiserrant.neocities.org/html/docs/Scripts.html), though obviously the remaining scripts (modtools and most of base) are substantial.

The key bit is that it finds everything under /scripts, including third party stuff, and sorts it to be included automatically in the correct page. I expect a pull with this completed to be done in a day or two, then I'll go through the third-party scripts, and finally clean up the tables of contents a bit and write a linter to confirm the docs are documented.

Then all our docs issues will be closed, and we'll be ready to release a new DFHack version :)

Note that following that pull, https://dfhack.rtfd.org will start working as soon as someone [adds the webhook](https://read-the-docs.readthedocs.org/en/latest/webhooks.html).  This supports multiple versions - ie every tag on `master` with compatible docs, plus `develop` - and I'm happy to add the DFHack team as owners (just tell me the account name on readthedocs).

**Comment by PeridexisErrant** [comment]
@lethosor - closed by #713!
