### ISSUE TITLE
autolabor can enable labors that are impossible to enable (or disable) otherwise

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#711]
E.g. alchemy (or gelding in pre-0.40.19 saves)

**Comment by expwnent** [comment]
Ideally it should have an "enable / disable cheat mode" thing like dwarf therapist does.

**Comment by lethosor** [comment]
I don't think being able to enable these labors is helpful, though - from what I understand, DF/DT/manipulator don't allow them to be enabled because they're unusable (since the dwarf civ doesn't allow them).

**Comment by expwnent** [comment]
Oh I thought you were talking about child labors and such.

**Comment by expwnent** [comment]
I guess mods could use the other labors somehow.

**Comment by lethosor** [comment]
Right, but not in existing worlds where those labors aren't permitted by the dwarf civilization.
