### ISSUE TITLE
Gui/Materials (Gui/FilteredList?) highlight arrow is off by one

### ISSUE THREAD

**Issue by DoctorVanGogh** [DFHack/dfhack#718]
Steps to reproduce:
1. Select any workshop with job (Loom with 'Collect Webs' job works fine), open material selection gui for job with <kbd>CTRL</kbd>-<kbd>a</kbd>, <kbd>m</kbd>
2. Highlight any expandable line with <kbd>up</kbd>/<kbd>down</kbd> (preferably a line where the item one line below is also expandable)

The highlighted arrow is one line below the actually highlighted item. Looks like an off by one error here.

![lists](https://cloud.githubusercontent.com/assets/324067/10858462/8108ef8e-7f55-11e5-8411-fe2b167ef936.png)

**Comment by lethosor** [comment]
For reference, gui/create-item has the same issue.

**Comment by lethosor** [comment]
Can you see if that change to widgets.lua works?

**Comment by DoctorVanGogh** [comment]
7da3c65 seems to fix this - just tried a 'weave thread' task, highlights align, *and* strange highlight in element #0 is gone.
![list-fixed](https://cloud.githubusercontent.com/assets/324067/10860885/7b5ee29e-7f70-11e5-8716-67c6a75076fe.png)

**Comment by lethosor** [comment]
All right, thanks!
