### ISSUE TITLE
built-in commands aren't included in try_autocomplete() suggestions

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#720]

**Comment by PeridexisErrant** [comment]
Related to #696?

**Comment by lethosor** [comment]
Sort of, but there isn't a good way to mention that (like on Mantis). This issue is just with the suggestions you see when typing an incomplete command, such as "di", which include commands like "diggingInvaders" but not "die".

**Comment by lethosor** [comment]
(Forgot to close with #1189)
