### ISSUE TITLE
Alternative way to organise DFHack script development

### ISSUE THREAD

**Issue by PeridexisErrant** [DFHack/dfhack#723]
For script developers, the current system is awkward enough to use that most simply don't.  Many maintain git repos for their scripts with no shared history, and more still don't use git at all.

I think it self-evident that script authors working on a fork would be better than our new submodule system, and that encouraging more people to use git for DFHack scripts would be a good thing.  I further assume that we would like to know about as much of the script development being done as possible, and prefer to have the option of adopting that work into the standard distribution.

So the proposal is actually pretty simple:

1. move the scripts directory to a new repository, and make it a submodule in it's current location
2. each author forks the repo, and works in /devel/$name/ if they're not comfortable putting stuff in the main folders
3. when ready for publication, scripts are moved to the main directories and pull-requests are made

What are the advantages for users (ie script authors)?

- it's trivial to work in a functioning environment:  just grab a DF+DFHack install, `cd hack && rm -rf scripts && git clone ...`
- the same technique makes getting new stuff easy
- all the linting and testing tools are available
- encourages collaboration, since you fork one repo not many and can fetch from other repos
- no baggage:  it doesn't include any of the scary C++/Perl/Lisp/XML/Cmake/whatever that scares people off

Advantages for DFHack core developers?

- **shared history**
- more people use git for DFHack scripts, meaning better history and more content
- the build systems and merge patterns are more sensible
- management of the scripts *could* (but need not) be handed off, and just checked when it's time to update the submodule for a release
- less duplication, as a higher proportion of the code is widely known among script authors
- +many above, eg script authors linting is a Good Thing

Thoughts?  I know this is a big step, but the DFHack project is getting big enough that it's hard to manage and this seems like a natural and helpful split to make.

**Comment by dscorbett** [comment]
If each author forks the repo, what is the purpose of working in devel/`$name`?

**Comment by PeridexisErrant** [comment]
@warmist asked in [the Bay12 thread](http://www.bay12forums.com/smf/index.php?topic=139553.msg6586916#msg6586916) (and approved of this pull in principle)

It's simply less of a change from the way people are currently working in their own repos, and would be exempt from all the linters and style-checking (eg for presence of documentation) that the standard scripts are subject to.

I would hope that most people just work in branches if they need that, but this idea is mainly targeted at people who just don't get git at all yet, and often don't use it.

**Comment by PeridexisErrant** [comment]
(oops, wrong button)

**Comment by lethosor** [comment]
For people who aren't familiar with git, I feel like the current submodule-based system would be much easier for personal scripts. I'm not opposed to moving the scripts directory to a submodule itself, but it's worth pointing out that cloning it into a DFHack installation could cause problems if CMake is pointed to the same installation. I'd prefer to make the script search path settings more user/dev-friendly - it makes it really easy to develop personal scripts in a separate folder, as well as switching between personal and DFHack versions of scripts.

**Comment by PeridexisErrant** [comment]
Most people using this probably won't even have CMake installed, so I'm not sure that's important (beyond documenting that ofc).  Otherwise useful points.

**Comment by lethosor** [comment]
I meant that your suggestion, making a clone of the scripts repo in hack/scripts, is a bad idea for core developers since CMake will overwrite things in that directory.
I actually do think this would work, though. I'd probably keep some of my work-in-progress scripts in a separate repo, but a single repo would probably be easier to deal with for core and script devs.

**Comment by PeridexisErrant** [comment]
Ah, I see what you mean.  Yes, you'd need to have one install for the core development install target and another for the script development if you wanted to do this.

**Comment by lethosor** [comment]
Having the scripts submodule in the DFHack source tree (in the current location of the scripts directory) should work too - you just wouldn't be able to combine the two approaches.

**Comment by PeridexisErrant** [comment]
#695 has a lot of relevant discussion, and proposes a new cmake target `install-scripts` without non-cmake dependencies for script authors.  it also covers several useful methods for dealing with scripts, including alternative paths.

**Comment by PeridexisErrant** [comment]
Dealing with this update is way harder than it needs to be, because it's so hard to tell what's happening when `NEWS` and `dfhack.init` are incomplete due to so much being pulled from 3rdparty repos.  Except at the same time only some things in those repos are included...

So my alternative proposal to deal with this issue is:  **Just put everything in this repo, manually add 3rdparty scripts, and release often**.  People will either start working in clones of this repo, in which case updates can be fairly coherent, or their work is added in a coherent way anyway.

Thoughts?

**Comment by lethosor** [comment]
I think the DFHack repo is large and more complicated for script authors to work with (e.g. we do all work on the develop branch, so new branches have to be based on that). It would be easier for core devs to work with, but it sounds like the exact approach we were using before the third-part script additions, which didn't seem to work as well (although the current system doesn't seem to have improved things much).

**Comment by PeridexisErrant** [comment]
Yeah, that's the logic of my main proposal - working down the list below, trying to find something that works reasonably well for everyone.

Everyone wants DFHack to do all the things they want it to do.  Core devs would additionally like it all to be in the main repo, with nice principles like good code style and less duplication.  Script authors (who aren't DFHack contributors) are just writing scripts that do the things they want, and sharing them.

The problem is this mismatch where nobody minds putting stuff in DFHack, but most people can't be bothered.  So far:

1. Hoping people submit stuff hasn't worked
2. Adding it for them (I've been doing this for a while) doesn't scale well
3. Adding submodules causes various problems
4. Making it easier to add stuff (scripts repo) will help **if** the prolific scripters take it up

So for (4), if we can get Lethosor and Roses to actively support it, enough others will probably pick it up  too (1) that a few people should be able to add in the rest (2).

**Comment by lethosor** [comment]
I'm leaning towards the single scripts submodule idea myself. I realize this hasn't seen a lot of activity, but we're mostly dealing with the new version at the moment. I'll look into this when I get a chance.

**Comment by PeridexisErrant** [comment]
No rush; getting things working again is higher priority and there's not much script development in the interim anyway.

**Comment by expwnent** [comment]
I've thought about it and I agree.

@lethosor I'm not sure I understood the problem you were talking about with overwriting files.

Plan:
- [ ] Make New Scripts Repo
- [ ] Inline all old scripts and all submodule scripts into it
- [ ] Replace scripts folder with new scripts submodule (git subtree might make more sense)
- [ ] Maybe provide a separate installer in case scripters want a convenient "install scripts" command

**Comment by lethosor** [comment]
That's what I was thinking too.
About overwriting files, my concern was that cloning the scripts repo into hack/scripts in the DF tree would cause issues if someone later tried to build and install DFHack in the same tree. Hopefully nobody will do that, but we could add a cmake sanity check of some kind to prevent it (e.g. check for hack/scripts/.git).

**Comment by lethosor** [comment]
I've started work on https://github.com/DFHack/scripts, which currently just contains scripts from this repo. I suspect combining the history of the other submodules would be more complicated, so I'll probably end up just copying over the latest versions of the scripts we care about.
(That repo currently just has a `master` branch, which might be easier for script devs to deal with, and is consistent with how df-structures, clsocket, stonesense, and other repos are set up.)

**Comment by expwnent** [comment]
Yeah, that makes sense. I'd say we can afford to lose the history.

**Comment by dscorbett** [comment]
It is not hard to keep the history, though, if you want it: http://stackoverflow.com/a/21495718.

**Comment by lethosor** [comment]
We aren't using every file from every repo, though, so we'd need to filter out the history of unused files from each repo.

**Comment by expwnent** [comment]
> We aren't using every file from every repo

That does complicate things. It means we can't just have 3rd party scripters fork the repo and just pull in whatever changes they make without complicated filtering and rebasing. I'm not sure what the right answer is.

**Comment by lethosor** [comment]
I'm thinking of just including the scripts we use in DFHack/scripts. People can fork it to work on scripts in it, or use other methods for working on scripts that aren't, so I'm not quite sure what the history issue is.
It's possible to set up additional script search paths, although there isn't a good interface for it right now (I'm just adding them through `lua` in dfhack.init, personally).

**Comment by lethosor** [comment]
I've finished the migration, I think. Looks like things are working to me.

**Comment by lethosor** [comment]
This is done!
