### ISSUE TITLE
'zone filters' lists invalid commands

### ISSUE THREAD

**Issue by DoctorVanGogh** [DFHack/dfhack#725]
`zone filters` lists (among others) `tamed` as a valid filter. 

That is incorrect: `tamed`is not a valid filter, ***`tame`*** is.

**Comment by lethosor** [comment]
Make a pull request! (You can do this by selecting the [develop](https://github.com/DoctorVanGogh/dfhack/tree/develop) branch in your fork, creating a new branch from the branch menu, and editing the file online if you like.)

**Comment by DoctorVanGogh** [comment]
No shit - was _not_ aware I could do that ;)

But since my Visual Studio decided to no longer throw a fit, I actually made a branch for this.

**Comment by PeridexisErrant** [comment]
Can be closed now :)
