### ISSUE TITLE
Replace `clsocket` with a maintained, Zlib-or-MIT-licensed alternative

### ISSUE THREAD

**Issue by PeridexisErrant** [DFHack/dfhack#728]
`clsocket` is actually pretty strange:

- Peterix got it from... somewhere offline I assume
- DFHack appears to be the only user
- it uses a variant of the BSD 3-clause license
- I can't find "CarrierLabs, LLC" online anywhere

This means that it's stable now (well, we think) but with no hope of modernisation, and makes keeping track of licenses harder than it needs to be.  It shouldn't be up to Lethosor (or any other DFHack contributor) to ensure that our sockets library supports basic error messages, or doesn't contain unused files or requests to send errors to defunct email addresses.

Given that there is in fact no shortage of socket libraries, can I suggest we replace it with something well-maintained, widely used, and available under the Zlib or MIT licenses?

**Comment by warmist** [comment]
Hmm...
Clsocket is very lightweight c++ wrapper on native sockets. If an alternative is know please say so however do keep in mind that it needs to be C++ (not C), lightweight, crossplatform. However it's (in my opinion) very low priority. Maybe one thing that is needed is move the duplicated error-string function into it.
Also i don't know much about licenses so why is BSD 3-clause license a cons?

Lastly: if it ain't broke, why fix it? :)

**Comment by lethosor** [comment]
>Maybe one thing that is needed is move the duplicated error-string function into it.

That's what I did recently, and I assume Peridexis was referring to that.

**Comment by PeridexisErrant** [comment]
It's clearly not broken, and so I agree this is very low priority.  But if there's an alternative which will require less work in future, that's probably worth taking up (eg yes, Lethosor's recent work, because why should we be maintaining a sockets library at all?).  I don't have something to hand but it's worth bearing in mind.

As for the license issue, well, it's probably nothing.  The BSD license family is one of the oldest around, and they are Free licenses.  However the extra (oldest, dropped in newer versions) clauses are stuff about advertising - and the non-standard extra clause that `The name "CarrierLabs" must not be used to endorse or promote products derived from this software` is the kind of slightly-ambiguous phrase that takedown regimes have been abused over before.

[Here's a clarified LICENSE.rst](https://github.com/PeridexisErrant/dfhack/blob/license-clarify/LICENSE.rst) (pull request coming in a few days), which I think illustrates the issue pretty well.  Practically everything is under the Zlib or MIT licenses, which are very widely known and well understood.  The BSD licenses are also pretty reasonable, but have historical baggage around advertising requirements - which led to the modern 2-clause version.  Non-standard clauses in licenses just make me nervous.  Fewer license details makes it more pleasant for concerned contributors too.

So why change?  Mitigating a very small risk, and letting future work focus on more interesting things.  Again it's a low priority, but I think worth keeping in mind if someone finds a good library and feels like putting it to use.

**Comment by lethosor** [comment]
The CarrierLabs website only went down recently (less than a year ago, IIRC). Anyway, I like clsocket because it's relatively simple (like Python's `socket` library) and the few issues we've run into have been pretty easy to fix (it's *really* well-documented, even if some of the code is a bit verbose for my liking). I don't mind if we replace it with something better as long as it offers similar functionality, but it's not always easy for us to combine frequent upstream changes with our own changes (e.g. lua and protobuf haven't been updated recently, and we've made a few fixes that might make it difficult - lua is usually easy to update, since we've primarily only changed one file and backported a few bugfixes, but I haven't looked into protobuf much).

**Comment by PeridexisErrant** [comment]
Fair enough.

The other thing that seems to have gone offline recently is Microsoft's downloads for Visual Studio 2010 - I was trying to find an official link to add to the compile instructions for Windows, and couldn't :(

**Comment by lethosor** [comment]
@thebloke found a MSVC link, which will hopefully continue to work (I added it to Compile.rst).

**Comment by PeridexisErrant** [comment]
I saw that, nice work!
