### ISSUE TITLE
Reduce duplication of tools, remove obsolete tools

### ISSUE THREAD

**Issue by PeridexisErrant** [DFHack/dfhack#735]
There are three lists:  things to remove, things to update, and tools to de-duplicate.

On the deprecation end, there's a bunch of stuff hanging around that hasn't been built or used since 0.40.01:

- [x] `dwarfexport`: disabled for some time, unused by modern tools
- [x] `mapexport`: disabled for some time, unused by modern tools
- [x] `df2mc`: hasn't been compatible with minecraft for years
- [x] `DFusion`: very old, all functions replaced save multirace embark parties
- [ ] `modtools/reaction-trigger-transition`: it's been two years, hopefully the transition is over and the script can be removed!

Some plugins are still incompatible with 40.xx, but would be great to update.  Alternatively they might be removed if it's judged not worth the bother:

- [ ] `advtools`
- [ ] `misery`
- [ ] `treefarm`

Tools with duplicated functionality, or things that could be merged: (related to #722)

- [ ] item creation: `createitem` plugin, `modtools/create-item`, `gui/create-item`.  Could drop the plugin, upgrade modtools and use it as a backend for the gui (with script_environment or similar)
- [ ] `forceequip` plugin is mostly replaced by `modtools/equip-item`
- [ ] `fastdwarf`, `teledwarf`, `superdwarf` - needs sorting out somehow.  See #664, #665.
- More to come.  Adding links between similar commands in the documentation often uncovers possibilities.

**Comment by maxthyme** [comment]
Is this also a point for doubled stuff?

Like, dfusion allows you to heal up, but it doesn't like to double-up on a unit, and full-heal is faster.

create-items duplicates a lot of gui/hack-wish, is almost the same name as modtools/create-item, and far more limited than createitem, plus the digv/digtype/etc being official now.

**Comment by PeridexisErrant** [comment]
I see deduplicating the standard library is a huge job - even more so because we probably want to have an official version of anything commonly used.  No issue for that because it's not clear what would be required to close it!

Ideally there would be "one obvious way to do it", whatever "it" is, but that's probably out of reach for the foreseeable future.  For now, I'm happy to just include everything and work on standardising can happen where it happens - because there's far more duplication of useful bits when DFHack doesn't supply a standard.

**Comment by Putnam3145** [comment]
Yeah, it's a pretty interesting problem. Does create-items do anything that createitem doesn't? For that matter, does createitem do anything that gui/create-item does?

actually why are there so many item creation scripts around

**Comment by maxthyme** [comment]
The only times I use createitem rather than gui/create-item is when I know specifically the syntax like createitem ROUGH OBSIDIAN or createitem ARMOR:ITEM_ARMOR_CLOAK SPIDER_PHANTOM:SILK or something, but if it's something I'm unsure of having the gui to search for it is super helpful.

**Comment by lethosor** [comment]
gui/create-item isn't as easy to automate, for one thing. I can't think of anything unique offered by create-items, though, aside from slightly different names for some things.

**Comment by Putnam3145** [comment]
Isn't modtools/create-item about the same now?

**Comment by lethosor** [comment]
It doesn't support creating multiple items at once, like createitem and gui/create-item, and I haven't checked to see how it handles "special" items, like gloves - ideally, all of them would behave the same way.
createitem can also create items in buildings or in containers, which I don't think the others can.

**Comment by PeridexisErrant** [comment]
It seems that this issue has expanded somewhat, so I'll edit the top post.

For item creation, it seems that the "best" thing to do would be to upgrade `modtools/create-item` to handle all the cases that `createitem` covers and remove that, then change `gui/create-item` to use the modtools script for all it's actual creation functions.

**Comment by Putnam3145** [comment]
modtools/create-item is just a convenient wrapper for item creation. Updating gui/create-item to use it seems like unnecessary abstraction, since gui/create-item is *also* a convenient wrapper for item creation. It wouldn't add any functionality.

**Comment by warmist** [comment]
About dfusion: it's mostly obsolete to the max :D. I.e. it has a system that i thought at the time was very nice (could be used as a script and as a module). However it soon got deprecated by normal stuff. Also it was mostly ported from pre-dfhack days...
Non-horribly old stuff that is there: a way to embark with custom race party and multi-race fort. The second point will be no longer relevant in next df version. The rest of stuff could be replaced by simple scripts.

**Comment by expwnent** [comment]
`modtools/create-item` can handle the same things `createitem` can, you just have to invoke it twice if you want a left/right pair. It was intended to replace the plugin. I didn't delete the plugin because I didn't create it originally. I don't know about `gui/create-item` or how it differs from `gui/hack-wish`.

**Comment by PeridexisErrant** [comment]
> I don't know about gui/create-item or how it differs from gui/hack-wish.

[gui/hack-wish is just an alias for gui/create-item](https://github.com/DFHack/dfhack/blob/master/scripts/gui/hack-wish.lua)

**Comment by PeridexisErrant** [comment]
Replaced by successor issue and pull request for clarity.
