### ISSUE TITLE
0.40.24-r4

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#737]
(This is intended to let people know that I'm making a release soon and to provide information about what's left to do. Hopefully something like this will happen for future releases as well.)
- [x] Make sure everything compiles
- [x] Make sure all submodules correspond to their latest public commits (in the repos in `.gitmodules`)
- [x] Check [travis build](https://travis-ci.org/DFHack/dfhack)
- [x] Disable dev plugins
- [x] Enable Stonesense
- [x] Update versions:
  - [x] CMakeLists.txt
  - [x] NEWS.rst
- [x] Test clean installation
  - [x] Test world generation/loading/saving
  - [x] Make sure `:lua print(dfhack.getDFHackVersion(), dfhack.getGitDescription(), dfhack.isRelease())` returns the correct values
- [x] `make package`
- [x] Tag/push release
- [x] Write release notes, save as draft
- [x] Upload binaries
- [x] Push to master
- [x] Release!

**Comment by PeridexisErrant** [comment]
https://dfhack.readthedocs.org now points to the `stable` (ie `master`-branch) docs, and users can select `latest` if they're interested in the unreleased stuff.
