### ISSUE TITLE
Set BUILD_DOC OFF by default

### ISSUE THREAD

**Issue by ragundo** [DFHack/dfhack#738]
Generating the documentation requires to install python and the Sphynx package.

If you don't have python installed, you'll not be able to build DFHack until you change the corresponding line in CMakeList.txt, because is ON by default right now.

OPTION(BUILD_DOCS "Choose whether to build the documentation (requires python and Sphinx)." OFF)

I think is too much to have C++, perl and python to compile DFHack

**Comment by lethosor** [comment]
One possibility would be to build and distribute the docs separately for people who want them offline, since the docs should be the same across platforms. (For now, I'm adding them to the Windows package.)

**Comment by PeridexisErrant** [comment]
Doesn't bother me, though I have a pretty strong preference for keeping docs in the release packages.  Even then, you can download a `.pdf` or `.epub` version from readthedocs and I can build html for the Starter Pack, so it's not a bit deal.

**Comment by lethosor** [comment]
Is it possible to get a bundle of some kind from ReadTheDocs? We could add that to releases or make it available on the download page.

**Comment by PeridexisErrant** [comment]
[RTD downloads](https://readthedocs.org/projects/dfhack/downloads): PDF, single-page html, epub.  Unfortunately they don't supply a bundle of all the html files to host elsewhere, but that should be easy to build - [instructions here](https://dfhack.readthedocs.org/en/stable/docs/Contributing.html#documentation-standards).

**Comment by lethosor** [comment]
>  In fact this should be done by CMake, thanks to the BUILD_DOC flag that started this whole thing, and included in release packages.

What do you mean? CMake doesn't build the documentation - it calls Sphinx, which won't work unless Sphinx is installed.

**Comment by PeridexisErrant** [comment]
Right, I meant that CMake calls Sphinx to build html docs in the format hosted on readthedocs, assuming you have it available installed docs. 

I can build these and post a zip if you want.

**Comment by lethosor** [comment]
I've turned this option off for now. I'm thinking of building the docs manually and posting them on the release page for r5, at least. Most users will probably prefer reading them online, so I don't know if including them in the releases is worth the extra 5 MB (after decompression).

**Comment by PeridexisErrant** [comment]
That sounds good to me.  An offline copy can easily be downloaded from readthedocs too.

**Comment by PeridexisErrant** [comment]
Issue closed, I think!

**Comment by lethosor** [comment]
Oh, I ran into another issue when uploading docs for r5 - it looks like the HTML download offered by ReadTheDocs consists of *all* of the documentation in a single index.html file (despite the documentation online being organized correctly). I had to re-enable BUILD_DOCS on my machine and package my docs/html directory, but I'd like to find a better way to do that for future releases.

**Comment by lethosor** [comment]
(I'll mark this as closed for organizational purposes, since this change happened in r5.)
