### ISSUE TITLE
Soundsense lua command fails, global msg is nil

### ISSUE THREAD

**Issue by AlexTes** [DFHack/dfhack#760]
Hope you do indeed maintain this, couldn't find any issue already revealing some general lua incompatibility.

Output:
```
[DFHack]# soundsense
...RFF~1\Dwarf Fortress 0.40.24/hack/scripts/soundsense.lua:30: attempt to call global 'msg' (a nil value)
stack traceback:
        ...RFF~1\Dwarf Fortress 0.40.24/hack/scripts/soundsense.lua:30: in function 'log_nobles'
        ...RFF~1\Dwarf Fortress 0.40.24/hack/scripts/soundsense.lua:123: in function 'event_loop'
        ...RFF~1\Dwarf Fortress 0.40.24/hack/scripts/soundsense.lua:129: in function 'f'
        ...ktop\DWARFF~1\Dwarf Fortress 0.40.24\hack\lua\dfhack.lua:554: in function <...ktop\DWARFF~1\Dwarf Fortress 0.40.24\hack\lua\dfhack.lua:495>
        (...tail calls...)
```

With:
DFHack 0.40.24-r4
Win10
using PeridexisErrant's lnp r19

**Comment by lethosor** [comment]
That script doesn't appear to be in this repo, so that's something @PeridexisErrant is distributing. I can try to figure it out, though - can you paste the script's contents somewhere?

**Comment by AlexTes** [comment]
Sure thing!
here it is: [soundsense.lua](http://lpaste.net/6057977330066784256)
Thanks for taking a look.

**Comment by PeridexisErrant** [comment]
Yep, that script is distributed in the Soundsense package.  Avoiding such problems is my motivation for #754; for now I'll backport those changes to my next pack release.

**Comment by lethosor** [comment]
Line 30 is empty. Are you sure you have the right error message (did you copy it)?

**Comment by PeridexisErrant** [comment]
That's the correct message; just a different version of the script.  I've now fixed this in my downstream - something was left out when I copy-pasted from the pull and apparently my test runs didn't hit that code.  Issue closed.

**Comment by AlexTes** [comment]
Yea, my bad. I didn't notice it wasn't actually in the hack folder until lethosor asked me to provide the source. Also just pasted source from the Linux LNP while I had this issue and msg using the Win LNP earlier today.

Sounds good PeridexisErrant, closing.

**Comment by lethosor** [comment]
Well, the message and the script can't correspond, but thanks for fixing it. I'll take a look at #754 soon.

**Comment by PeridexisErrant** [comment]
The script is basically just the event loop part from that pull, but I'd missed `msg = dfhack.gui.writeToGamelog` up the top.  Oops...
