### ISSUE TITLE
tweak idea: Display which reaction reagents are missing

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#763]
For example, it isn't easy to figure out whether barrels or plants (or both) are missing when brewing in vanilla DF:
![](http://i.imgur.com/0xp9Vxw.png)

**Comment by expwnent** [comment]
In the new DF release:

> Looking at reaction screen for redded-out reactions in workshop will indicate missing reagents now

Closing for now, but feel free to open it if there are problems with it and you are feeling ambitious or something.
