### ISSUE TITLE
errors while building

### ISSUE THREAD

**Issue by macrixen** [DFHack/dfhack#777]
i know it's not finished for 42.03 but wanted to try and bug squash a bit and can't seem to successfully build this....i have all the dependencies but vc comes up with a link error for sdl.lib and items.cpp is throwing  that produce does not take 9 arguments.

1>------ Build started: Project: git-describe, Configuration: Release Win32 ------
2>------ Build started: Project: generate_headers, Configuration: Release Win32 ------
3>------ Build started: Project: generate_proto, Configuration: Release Win32 ------
1>  Obtaining git commit information
4>------ Build started: Project: ruby-autogen-rb, Configuration: Release Win32 ------
5>------ Build started: Project: dfhack, Configuration: Release Win32 ------
5>  Items.cpp
5>..\..\..\library\modules\Items.cpp(1378): error C2660: 'df::reaction_product::produce' : function does not take 9 arguments
6>------ Build started: Project: steam-engine, Configuration: Release Win32 ------
7>------ Build started: Project: sort, Configuration: Release Win32 ------
8>------ Build started: Project: siege-engine, Configuration: Release Win32 ------
9>------ Build started: Project: showmood, Configuration: Release Win32 ------
7>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
6>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
10>------ Build started: Project: seedwatch, Configuration: Release Win32 ------
11>------ Build started: Project: search, Configuration: Release Win32 ------
12>------ Build started: Project: stepBetween, Configuration: Release Win32 ------
13>------ Build started: Project: ruby, Configuration: Release Win32 ------
12>LINK : fatal error LNK1181: cannot open input file '..\..\library\Release\SDL.lib'
10>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
11>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
14>------ Build started: Project: rprobe, Configuration: Release Win32 ------
15>------ Build started: Project: reveal, Configuration: Release Win32 ------
16>------ Build started: Project: resume, Configuration: Release Win32 ------
14>LINK : fatal error LNK1181: cannot open input file '..\..\library\Release\SDL.lib'
13>LINK : fatal error LNK1181: cannot open input file '..\..\library\Release\SDL.lib'
15>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
16>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
17>------ Build started: Project: rendermax, Configuration: Release Win32 ------
18>------ Build started: Project: renderer-msg, Configuration: Release Win32 ------
17>LINK : fatal error LNK1181: cannot open input file '..\..\library\Release\SDL.lib'
18>LINK : fatal error LNK1181: cannot open input file '..\..\library\Release\SDL.lib'
19>------ Build started: Project: rename, Configuration: Release Win32 ------
20>------ Build started: Project: regrass, Configuration: Release Win32 ------
21>------ Build started: Project: stonesense, Configuration: Release Win32 ------
22>------ Build started: Project: strangemood, Configuration: Release Win32 ------
22>  strangemood.cpp
20>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
19>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
21>LINK : fatal error LNK1181: cannot open input file '..\..\library\Release\SDL.lib'
23>------ Build started: Project: stripcaged, Configuration: Release Win32 ------
24>------ Build started: Project: tilesieve, Configuration: Release Win32 ------
23>LINK : fatal error LNK1181: cannot open input file '..\..\library\Release\SDL.lib'
24>LINK : fatal error LNK1181: cannot open input file '..\..\library\Release\SDL.lib'
25>------ Build started: Project: prospector, Configuration: Release Win32 ------
26>------ Build started: Project: probe, Configuration: Release Win32 ------
27>------ Build started: Project: power-meter, Configuration: Release Win32 ------
25>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
26>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
28>------ Build started: Project: plants, Configuration: Release Win32 ------
29>------ Build started: Project: petcapRemover, Configuration: Release Win32 ------
30>------ Build started: Project: onceExample, Configuration: Release Win32 ------
28>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
31>------ Build started: Project: notes, Configuration: Release Win32 ------
32>------ Build started: Project: nestboxes, Configuration: Release Win32 ------
31>LINK : fatal error LNK1181: cannot open input file '..\..\library\Release\SDL.lib'
33>------ Build started: Project: mousequery, Configuration: Release Win32 ------
32>LINK : fatal error LNK1181: cannot open input file '..\..\library\Release\SDL.lib'
34>------ Build started: Project: mode, Configuration: Release Win32 ------
33>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
35>------ Build started: Project: memview, Configuration: Release Win32 ------
34>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
36>------ Build started: Project: manipulator, Configuration: Release Win32 ------
37>------ Build started: Project: luasocket, Configuration: Release Win32 ------
35>LINK : fatal error LNK1181: cannot open input file '..\..\library\Release\SDL.lib'
22>..\..\..\plugins\strangemood.cpp(62): error C2039: 'STRANGE_MOODS' : is not a member of 'df::enums::caste_raw_flags'
22>..\..\..\plugins\strangemood.cpp(62): error C2065: 'STRANGE_MOODS' : undeclared identifier
22>..\..\..\plugins\strangemood.cpp(112): error C2039: 'permitted_skill' : is not a member of 'df::historical_entity::T_resources'
22>          C:\Users\Jeff\Documents\GitHub\dfhack\library\include\df/historical_entity.h(88) : see declaration of 'df::historical_entity::T_resources'
22>..\..\..\plugins\strangemood.cpp(114): error C2039: 'permitted_skill' : is not a member of 'df::historical_entity::T_resources'
22>          C:\Users\Jeff\Documents\GitHub\dfhack\library\include\df/historical_entity.h(88) : see declaration of 'df::historical_entity::T_resources'
22>..\..\..\plugins\strangemood.cpp(116): error C2039: 'permitted_skill' : is not a member of 'df::historical_entity::T_resources'
22>          C:\Users\Jeff\Documents\GitHub\dfhack\library\include\df/historical_entity.h(88) : see declaration of 'df::historical_entity::T_resources'
22>..\..\..\plugins\strangemood.cpp(736): error C2039: 'PAPERMAKING' : is not a member of 'df::enums::job_skill'
22>..\..\..\plugins\strangemood.cpp(736): error C2065: 'PAPERMAKING' : undeclared identifier
22>..\..\..\plugins\strangemood.cpp(736): error C2051: case expression not constant
22>..\..\..\plugins\strangemood.cpp(737): error C2039: 'BOOKBINDING' : is not a member of 'df::enums::job_skill'
22>..\..\..\plugins\strangemood.cpp(737): error C2065: 'BOOKBINDING' : undeclared identifier
22>..\..\..\plugins\strangemood.cpp(737): error C2051: case expression not constant
22>..\..\..\plugins\strangemood.cpp(871): error C2039: 'PAPERMAKING' : is not a member of 'df::enums::job_skill'
22>..\..\..\plugins\strangemood.cpp(871): error C2065: 'PAPERMAKING' : undeclared identifier
22>..\..\..\plugins\strangemood.cpp(871): error C2051: case expression not constant
22>..\..\..\plugins\strangemood.cpp(872): error C2039: 'BOOKBINDING' : is not a member of 'df::enums::job_skill'
22>..\..\..\plugins\strangemood.cpp(872): error C2065: 'BOOKBINDING' : undeclared identifier
22>..\..\..\plugins\strangemood.cpp(872): error C2051: case expression not constant
36>  manipulator.cpp
37>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
38>------ Build started: Project: tiletypes, Configuration: Release Win32 ------
38>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
39>------ Build started: Project: liquids, Configuration: Release Win32 ------
39>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
40>------ Build started: Project: lair, Configuration: Release Win32 ------
41>------ Build started: Project: kittens, Configuration: Release Win32 ------
40>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
41>LINK : fatal error LNK1181: cannot open input file '..\..\library\Release\SDL.lib'
42>------ Build started: Project: title-version, Configuration: Release Win32 ------
42>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
43>------ Build started: Project: jobutils, Configuration: Release Win32 ------
43>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
44>------ Build started: Project: isoworldremote, Configuration: Release Win32 ------
44>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
45>------ Build started: Project: infiniteSky, Configuration: Release Win32 ------
46>------ Build started: Project: hotkeys, Configuration: Release Win32 ------
45>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
46>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
47>------ Build started: Project: trackstop, Configuration: Release Win32 ------
47>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
48>------ Build started: Project: getplants, Configuration: Release Win32 ------
48>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
49>------ Build started: Project: stockcheck, Configuration: Release Win32 ------
49>LINK : fatal error LNK1181: cannot open input file '..\..\library\Release\SDL.lib'
50>------ Build started: Project: tubefill, Configuration: Release Win32 ------
51>------ Build started: Project: frozen, Configuration: Release Win32 ------
50>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
51>LINK : fatal error LNK1181: cannot open input file '..\..\library\Release\SDL.lib'
52>------ Build started: Project: fortplan, Configuration: Release Win32 ------
52>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
53>------ Build started: Project: forceequip, Configuration: Release Win32 ------
53>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
54>------ Build started: Project: follow, Configuration: Release Win32 ------
36>..\..\..\plugins\manipulator.cpp(173): error C2039: 'PAPERMAKER' : is not a member of 'df::enums::profession'
36>..\..\..\plugins\manipulator.cpp(173): error C2065: 'PAPERMAKER' : undeclared identifier
36>..\..\..\plugins\manipulator.cpp(173): error C2039: 'PAPERMAKING' : is not a member of 'df::enums::unit_labor'
36>..\..\..\plugins\manipulator.cpp(173): error C2065: 'PAPERMAKING' : undeclared identifier
36>..\..\..\plugins\manipulator.cpp(173): error C2039: 'PAPERMAKING' : is not a member of 'df::enums::job_skill'
36>..\..\..\plugins\manipulator.cpp(173): error C2065: 'PAPERMAKING' : undeclared identifier
36>..\..\..\plugins\manipulator.cpp(174): error C2039: 'BOOKBINDER' : is not a member of 'df::enums::profession'
36>..\..\..\plugins\manipulator.cpp(174): error C2065: 'BOOKBINDER' : undeclared identifier
36>..\..\..\plugins\manipulator.cpp(174): error C2039: 'BOOKBINDING' : is not a member of 'df::enums::unit_labor'
36>..\..\..\plugins\manipulator.cpp(174): error C2065: 'BOOKBINDING' : undeclared identifier
36>..\..\..\plugins\manipulator.cpp(174): error C2039: 'BOOKBINDING' : is not a member of 'df::enums::job_skill'
36>..\..\..\plugins\manipulator.cpp(174): error C2065: 'BOOKBINDING' : undeclared identifier
36>..\..\..\plugins\manipulator.cpp(1597): error C2039: 'UNITJOB_VIEW_UNIT' : is not a member of 'df::enums::interface_key'
36>..\..\..\plugins\manipulator.cpp(1597): error C2065: 'UNITJOB_VIEW_UNIT' : undeclared identifier
36>..\..\..\plugins\manipulator.cpp(1809): error C2039: 'UNITJOB_VIEW_UNIT' : is not a member of 'df::enums::interface_key'
36>..\..\..\plugins\manipulator.cpp(1809): error C2065: 'UNITJOB_VIEW_UNIT' : undeclared identifier
36>..\..\..\plugins\manipulator.cpp(2062): error C2039: 'UNITJOB_VIEW_UNIT' : is not a member of 'df::enums::interface_key'
36>..\..\..\plugins\manipulator.cpp(2062): error C2065: 'UNITJOB_VIEW_UNIT' : undeclared identifier
54>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
55>------ Build started: Project: flows, Configuration: Release Win32 ------
56>------ Build started: Project: fixveins, Configuration: Release Win32 ------
57>------ Build started: Project: fixpositions, Configuration: Release Win32 ------
55>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
58>------ Build started: Project: fix-unit-occupancy, Configuration: Release Win32 ------
56>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
59>------ Build started: Project: fix-armory, Configuration: Release Win32 ------
58>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
57>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
60>------ Build started: Project: filltraffic, Configuration: Release Win32 ------
61>------ Build started: Project: fastdwarf, Configuration: Release Win32 ------
59>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
62>------ Build started: Project: eventful, Configuration: Release Win32 ------
61>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
60>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
63>------ Build started: Project: eventExample, Configuration: Release Win32 ------
64>------ Build started: Project: embark-tools, Configuration: Release Win32 ------
65>------ Build started: Project: dwarfmonitor, Configuration: Release Win32 ------
64>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
62>  eventful.cpp
63>LINK : fatal error LNK1181: cannot open input file '..\..\library\Release\SDL.lib'
66>------ Build started: Project: dumpmats, Configuration: Release Win32 ------
65>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
67>------ Build started: Project: diggingInvaders, Configuration: Release Win32 ------
66>LINK : fatal error LNK1181: cannot open input file '..\..\library\Release\SDL.lib'
68>------ Build started: Project: digFlood, Configuration: Release Win32 ------
67>  assignJob.cpp
69>------ Build started: Project: dig, Configuration: Release Win32 ------
68>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
70>------ Build started: Project: dfusion, Configuration: Release Win32 ------
71>------ Build started: Project: tweak, Configuration: Release Win32 ------
71>LINK : fatal error LNK1181: cannot open input file '..\..\library\Release\SDL.lib'
72>------ Build started: Project: weather, Configuration: Release Win32 ------
62>..\..\..\plugins\eventful.cpp(342): error C2664: 'DFHack::VMethodInterposeLink<Base,Ptr>::VMethodInterposeLink<void(__thiscall product_hook::* )(df::unit *,std::vector<_Ty> *,std::vector<df::item *> *,std::vector<df::reaction_reagent *> *,std::vector<df::item *> *,int32_t,df::enums::job_skill::job_skill,df::historical_entity *,df::world_site *)>(Ptr,Ptr2,int,const char *)' : cannot convert parameter 1 from 'void (__thiscall df::reaction_product::* )(df::unit *,std::vector<_Ty> *,std::vector<df::reaction_reagent *> *,std::vector<_Ty> *,int32_t,df::enums::job_skill::job_skill,df::historical_entity *,df::world_site *)' to 'product_hook::interpose_ptr_produce '
62>          with
62>          [
62>              Base=product_hook::interpose_base,
62>              Ptr=product_hook::interpose_ptr_produce,
62>              _Ty=df::reaction_product *,
62>              Ptr2=void (__thiscall product_hook::* )(df::unit *,std::vector<df::reaction_product *> *,std::vector<df::item *> *,std::vector<df::reaction_reagent *> *,std::vector<df::item *> *,int32_t,df::enums::job_skill::job_skill,df::historical_entity *,df::world_site *)
62>          ]
62>          and
62>          [
62>              _Ty=df::item *
62>          ]
62>          Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
72>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
73>------ Build started: Project: workNow, Configuration: Release Win32 ------
73>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
74>------ Build started: Project: workflow, Configuration: Release Win32 ------
75>------ Build started: Project: stockflow, Configuration: Release Win32 ------
76>------ Build started: Project: stockpiles, Configuration: Release Win32 ------
67>..\..\..\..\plugins\diggingInvaders\assignJob.cpp(261): error C2660: 'df::reaction_product::produce' : function does not take 9 arguments
77>------ Build started: Project: deramp, Configuration: Release Win32 ------
76>LINK : fatal error LNK1181: cannot open input file '..\..\library\Release\SDL.lib'
78>------ Build started: Project: cursecheck, Configuration: Release Win32 ------
79>------ Build started: Project: createitem, Configuration: Release Win32 ------
80>------ Build started: Project: counters, Configuration: Release Win32 ------
77>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
79>  createitem.cpp
78>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
81>------ Build started: Project: confirm, Configuration: Release Win32 ------
82>------ Build started: Project: command-prompt, Configuration: Release Win32 ------
80>LINK : fatal error LNK1181: cannot open input file '..\..\library\Release\SDL.lib'
83>------ Build started: Project: color-dfhack-text, Configuration: Release Win32 ------
82>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
84>------ Build started: Project: colonies, Configuration: Release Win32 ------
85>------ Build started: Project: zone, Configuration: Release Win32 ------
83>LINK : fatal error LNK1181: cannot open input file '..\..\library\Release\SDL.lib'
84>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
85>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
86>------ Build started: Project: cleanowned, Configuration: Release Win32 ------
87>------ Build started: Project: cleaners, Configuration: Release Win32 ------
88>------ Build started: Project: cleanconst, Configuration: Release Win32 ------
86>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
87>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
89>------ Build started: Project: changevein, Configuration: Release Win32 ------
90>------ Build started: Project: changelayer, Configuration: Release Win32 ------
91>------ Build started: Project: changeitem, Configuration: Release Win32 ------
90>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
89>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
92>------ Build started: Project: catsplosion, Configuration: Release Win32 ------
91>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
93>------ Build started: Project: burrows, Configuration: Release Win32 ------
92>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
94>------ Build started: Project: buildprobe, Configuration: Release Win32 ------
95>------ Build started: Project: stocks, Configuration: Release Win32 ------
93>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
95>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
94>LINK : fatal error LNK1181: cannot open input file '..\..\library\Release\SDL.lib'
96>------ Build started: Project: buildingplan, Configuration: Release Win32 ------
97>------ Build started: Project: building-hacks, Configuration: Release Win32 ------
79>..\..\..\plugins\createitem.cpp(89): error C2660: 'df::reaction_product::produce' : function does not take 9 arguments
98>------ Build started: Project: blueprint, Configuration: Release Win32 ------
97>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
96>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
99>------ Build started: Project: autotrade, Configuration: Release Win32 ------
100>------ Build started: Project: automelt, Configuration: Release Win32 ------
98>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
101>------ Build started: Project: automaterial, Configuration: Release Win32 ------
100>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
102>------ Build started: Project: autolabor, Configuration: Release Win32 ------
99>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
103>------ Build started: Project: autohauler, Configuration: Release Win32 ------
101>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
104>------ Build started: Project: autodump, Configuration: Release Win32 ------
102>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
103>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
105>------ Build started: Project: autochop, Configuration: Release Win32 ------
106>------ Build started: Project: add-spatter, Configuration: Release Win32 ------
107>------ Build started: Project: zoom, Configuration: Release Win32 ------
104>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
106>  add-spatter.cpp
105>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
108>------ Build started: Project: RemoteFortressReader, Configuration: Release Win32 ------
107>LINK : fatal error LNK1181: cannot open input file '..\..\library\Release\SDL.lib'
109>------ Build started: Project: 3dveins, Configuration: Release Win32 ------
109>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
108>LINK : fatal error LNK1181: cannot open input file '..\library\Release\SDL.lib'
106>..\..\..\plugins\add-spatter.cpp(302): error C2664: 'DFHack::VMethodInterposeLink<Base,Ptr>::VMethodInterposeLink<void(__thiscall product_hook::* )(df::unit *,std::vector<_Ty> *,std::vector<df::item *> *,std::vector<df::reaction_reagent *> *,std::vector<df::item *> *,int32_t,df::enums::job_skill::job_skill,df::historical_entity *,df::world_site *)>(Ptr,Ptr2,int,const char *)' : cannot convert parameter 1 from 'void (__thiscall df::reaction_product::* )(df::unit *,std::vector<_Ty> *,std::vector<df::reaction_reagent *> *,std::vector<_Ty> *,int32_t,df::enums::job_skill::job_skill,df::historical_entity *,df::world_site *)' to 'product_hook::interpose_ptr_produce '
106>          with
106>          [
106>              Base=product_hook::interpose_base,
106>              Ptr=product_hook::interpose_ptr_produce,
106>              _Ty=df::reaction_product *,
106>              Ptr2=void (__thiscall product_hook::* )(df::unit *,std::vector<df::reaction_product *> *,std::vector<df::item *> *,std::vector<df::reaction_reagent *> *,std::vector<df::item *> *,int32_t,df::enums::job_skill::job_skill,df::historical_entity *,df::world_site *)
106>          ]
106>          and
106>          [
106>              _Ty=df::item *
106>          ]
106>          Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
========== Build: 4 succeeded, 105 failed, 17 up-to-date, 0 skipped ==========

**Comment by lethosor** [comment]
Did you remember to run `git submodule update`?

**Comment by macrixen** [comment]
i am such a derp... thanks.. was using gui instead of shell.. i assumed checking out got everything i needed... was wrong...  lesson learned
