### ISSUE TITLE
exportlegends.lua - timestamp of generated legends_plus.xml wrong after retiring/abandoning a fortress

### ISSUE THREAD

**Issue by Kromtec** [DFHack/dfhack#783]
Error was in [DFHack 0.40.24-r5] and is in [DFHack 0.42.04-alpha1] as well.

Only occures when starting the script after retiring or abandoning a fortress.
The day of the timestamp advances one day further for the legends_plus.xml file:
![Screenshot](http://i.imgur.com/3Sgn8GX.png)

**Comment by lethosor** [comment]
Interestingly enough, 01-01 is consistent with the other exported files.

**Comment by BenLubar** [comment]
It gives 01-16 for an adventure mode world that has been started right after worldgen and then not interacted with at all. (should be 01-15)

**Comment by fricy** [comment]
I'm seeing this with newly generated world, fresh embark. Any unintended consequences if changing [this  in exportlegends](https://github.com/DFHack/dfhack/blob/master/scripts/exportlegends.lua#L90)?

**Comment by BenLubar** [comment]
Oh, it's this:

https://github.com/DFHack/dfhack/blob/master/scripts/exportlegends.lua#L88

Remove the +1 from that line.

**Comment by PeridexisErrant** [comment]
@lethosor - fixed now, so the issue can be closed?

**Comment by lethosor** [comment]
Yeah, I think it's working now.
