### ISSUE TITLE
GetLocalFeature is commented out in include/modules/Maps.h

### ISSUE THREAD

**Issue by ragundo** [DFHack/dfhack#786]
That function is commented in the header file, but it exits in the corresponding cpp file
/library/modules/Maps.cpp.

Is it commented because it doesn't work?. In that case it should be removed.
If it's work it should be in the include file, because if not  you need to use something like
`extern bool GetLocalFeature(t_feature &feature, df::coord2d rgn_pos, int32_t index);`
in a plugin code to get access to it, which is *awkard*.

**Comment by lethosor** [comment]
Angavrilov said something about this being obsolete. Did you figure out how to use getLocalFeatureInit?

**Comment by lethosor** [comment]
Going to close this one unless getLocalInitFeature() doesn't work for some reason.
