### ISSUE TITLE
Automaterial plugin does not support Tracks & TrackStops

### ISSUE THREAD

**Issue by jobywalker** [DFHack/dfhack#790]
Automaterial does not function (and the menu options are not present for) Tracks and Track Stops.

Seen in 0.40.24-r5

**Comment by WilliamCushing** [comment]
while
  keybinding add Shift-S "job-material GRANITE"
is nice, it would be much nicer to just be able to use the search plugin in the material selection mode.  

It would also be nice to:
[(0) search in material selection]
(1) sort in material selection
(2) sort-by-dwarfbucks/value/price 
  (specifically this is useful in the trade screen itself, for dealing with dyed threads and cloths)
(3) remember the top 5 last-used and/or top 5 most-used materials
  in the current fort, some normal walls are granite, others are claystone, still others are jet;
  meanwhile, magma constructions and devices use mica and orthoclase.

**Comment by lethosor** [comment]
@WilliamCushing that should be a separate ticket.

**Comment by myk002** [comment]
this functionality is now supported by `buildingplan`
