### ISSUE TITLE
Add API reference docs, introduction for developers

### ISSUE THREAD

**Issue by PeridexisErrant** [DFHack/dfhack#794]
While recent efforts have improved documentation for users - see https://dfhack.rtfd.org - there's not much for developers.  See for example [this post](http://www.bay12forums.com/smf/index.php?topic=139553.msg6728637#msg6728637) in the Bay12 thread.

Specifically, we should provide:

 - [x] an introduction for developers, covering in general terms the utility functions available, how to interact with data structures, how to tell if a tool should be a plugin or a script (and about the example scripts/ skeleton plugin), etc.  Probably split into tips for script authors, and tips for general DFHack developers.
 - [x] detailed information on usable DFHack functions, especially those exposed to scripts (ie ensure `Lua API.rst` is complete and up-to-date; corresponding docs for Ruby and C++ ?)
 - ~~API reference for DF data structures; basically a more readable, annotated and linked form of the XML files~~  Too much text, not enough commentary.  Just reading the xml directly is easier!
 - [x] do another pass for formatting, especially where keybinding styles would be appropriate.  Use search for ctrl/alt/shift/esc etc.

I'll add a Travis test for docs building correctly too, and check that plugins are documented.

**Comment by expwnent** [comment]
It would also be nice if we could have inline docs in the comments of C++ header files. I think doxygen allows it but sphinx doesn't but I don't remember.

**Comment by PeridexisErrant** [comment]
https://breathe.readthedocs.org Looks like it's possible to use Doxygen from Sphinx, which would be nice (except when installing dependencies, but...).  I think this would be really nice for documenting the DFHack API - as in, exposed functions - but not so much for plugin docs.

It's non-trivial but reasonable to transform the structures XML into a more-or-less human-readable .rst format.  We'd certainly want to carry across any comments though, and probably annotate the xml some more.

Intro, tips, and formatting are all for wholly handwritten files.

**Comment by PeridexisErrant** [comment]
Related:  if someone merges DFHack/stonesense#43, I can finally get nice stonesense docs on the readthedocs site.
