### ISSUE TITLE
ban-cooking: add option to ban plants/fruits with certain properties

### ISSUE THREAD

**Issue by jobywalker** [DFHack/dfhack#796]
It would be helpful to be able to ban classes of plants/fruits that can be used for other purposes:

brew: ban plants/fruits that can be brewed into alcohol
mill: ban plants/fruits that can be milled to powder (flour/sugar/dye)
thread: ban plants/fruits that can be turned into thread

**Comment by BenLubar** [comment]
Fixed in d36bb20d91934db42c450bbfcd1170be32ccaa2f

**Comment by jobywalker** [comment]
Thanks!
