### ISSUE TITLE
Include offline html documentation with releases

### ISSUE THREAD

**Issue by PeridexisErrant** [DFHack/dfhack#801]
Because shipping something this complicated without a readme is disgraceful, and there's no reason not to provide it - it's really useful for anyone on a slow internet connection, and vital for anyone offline.

Total size of the built html is about 1.3MB zipped, compared to 12.1MB for the build without it, so the filesize isn't really a problem.  It's reducible a little further by deleting the `./docs/html/.buildinfo/` dir, which is no loss at all but would need to be added to the cmake recipe.

@lethosor, let me know if there's any way I can make this easier.

**Comment by milochristiansen** [comment]
+1

I was trying to do some DFHacking for First Landing and quickly realized that there was no documentation anymore. Even incomplete docs are better than no docs.

**Comment by lethosor** [comment]
The problem that came up with #738 is that building the documentation can require installing a lot of dependencies. I tried downloading documentation from ReadTheDocs at one point, but it came in a badly-organized single file, which isn't useful either.
If the rst files are readable by themselves, including them in the package would be pretty simple, though.

**Comment by PeridexisErrant** [comment]
Docs are in for 42.06-aplha2, so I'll close this for now.

It would be good if (a) this continued, and (b) `hack/docs/.doctrees/*` was left out - it's 3MB of barely-compressible intermediate representation, and of no value to users.

Closing for now regardless :)

**Comment by lethosor** [comment]
No they're not.

**Comment by lethosor** [comment]
Oh, are they in the Windows package? They're definitely not in the others.
What I gathered from #738 is that requiring everyone to install a ton of dependencies just to build documentation (particularly an issue on Windows) is problematic. It would be great if we could figure out a way to build documentation elsewhere and bundle it with releases. Unfortunately, ReadTheDocs's download isn't usable, or it wasn't last I checked.

**Comment by PeridexisErrant** [comment]
Hmm.  We could set up Travis to 'release' a zip of the built docs to a free Neocities site, if that would help?  But it would still have to be downloaded and added to the release, plus there would be serious issues with versioning.

**Comment by lethosor** [comment]
We've started asking people who build releases to enable the docs (see [here](https://github.com/DFHack/dfhack/wiki/Release-checklist)), and it looks like they're present in all of the packages for 0.43.03-r1, and at least the two I've downloaded for 0.43.03-alpha1. Unless there's an issue with them, I think this is resolved.

**Comment by PeridexisErrant** [comment]
Should the release checklist itself be part of the docs?  I thought the idea was to have everything tracked by git and available in the HTML.

**Comment by lethosor** [comment]
It's something we use internally, and it's best to just have one version of it that's always current. If it's tracked in git, then we could run into #962-type issues if people assume the one on the master branch is current. Also, sometimes I've had to update it after a release has been tagged, and pushing documentation updates that apply to a release after the release has been tagged generally isn't a good idea.

I'm not sure if it would be very useful for most people reading the docs, anyway. Maybe a link to it could work?

**Comment by PeridexisErrant** [comment]
Yep, adding a link would be good.

I'd suggest a new section in Contributing.rst, just above 'Documentation Standards', called something like "Release Process".  Ideally this would have a short description of the process, timing etc as well as a link to the release checklist.
