### ISSUE TITLE
Add method to get the size of a BitArray

### ISSUE THREAD

**Issue by ragundo** [DFHack/dfhack#802]
BitArray.h has two fieds, a pointer and a size. There's no method to get the size field.

Adding something as simple as 

`uint32_t get_size() { return size; } `

would be enough.

The reason for this PR is that DF checks that size field in order to execute different code, but trying to replicate that code in DFHack is not possible because the field is private

**Comment by lethosor** [comment]
The field isn't private - `private:` [is commented out](https://github.com/DFHack/dfhack/blob/master/library/include/BitArray.h#L167-L169). Maybe you meant `DfArray`, but that has a `size()` method.
