### ISSUE TITLE
plugin idea: autoforbid

### ISSUE THREAD

**Issue by jobywalker** [DFHack/dfhack#806]
It would be useful to have autotrade/automelt like functionality for forbidding.  The main use case for me is trying to pull wooden barrels out of circulation without manually finding & dumping them. Currently, I use a sockpile/minecart to dump the barrels in to a locked pit so they are inaccessible.  This could also be useful if you wanted to build materials for use later (magma pump stack) and wanted to keep them out of circulation.

**Comment by BenLubar** [comment]
Would [autodump](https://dfhack.readthedocs.org/en/stable/docs/Plugins.html#autodump) work for that?

**Comment by jobywalker** [comment]
Autodump would dump empty barrels which would be useful if I wanted to just get rid of all of them -- but they are useful for some buildings and early on I occasionally I'm in desperate need for food storage.

This is to have a passive strategy to remove barrels from use continually rather than a single point in time.  This could also be useful for autoforbidding valuable resources that you don't want dwarves using (i.e., Aluminum, Platinum, Giant Cave Spider Silk).

**Comment by BenLubar** [comment]
Dumping an item is the same as forbidding it, but your dwarves move it to a garbage zone.

**Comment by myk002** [comment]
this does look like it should be adequately covered by stockpile autodump. closing.
