### ISSUE TITLE
tweak.plug.dll crash

### ISSUE THREAD

**Issue by MrBobBarker** [DFHack/dfhack#811]
Was just doing basic UI stuff, it may have crashed when I was just mousing over tiles. Using 91f85831a7e3f07ab38278c93ddb17bc22e9ae80 with df-twbt 0b8b4228f99a0bb0b9b828be3166f556554d80ee which replaces mousequery.plug.dll (related?)

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	Dwarf Fortress.exe
  Application Version:	0.0.0.0
  Application Timestamp:	569bf3df
  Fault Module Name:	tweak.plug.dll
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	56aeb713
  Exception Code:	c0000005
  Exception Offset:	00004c6a
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by lethosor** [comment]
Does this occur without TwbT?

**Comment by MrBobBarker** [comment]
It's only been the single isolated crash so far, I'll continue playing without twbt to see if I can reproduce it.

**Comment by lethosor** [comment]
Any updates on whether this is caused by TwbT?

**Comment by MrBobBarker** [comment]
Let's assume it was, I have no further information to add. I haven't been able to replicate this issue.

**Comment by WilliamCushing** [comment]
I have had DF + hack + TwbT crash on me a handful of times over the last handful of releases.  It is just frequent enough that I remember to force save anytime after issuing a bunch of input...losing an hour or three of designations is painful.  

Continuing from the exception using Visual Studio allowed me to save the game and restart without losing data in all but one case (once I thought to try that; the first few crashes I didn't think to open the debugger and see if I could force myself past).  The exception was generated from code invoked through the dll for TwbT; the exception itself was in some NT dll (presumably system level code for drawing to the real device).  The one case where I couldn't manage to force the game back into a state where I could save was induced by flipping a to-be-built pump such that one of its tiles was off the left side of the map.  The other instances were induced just by moving the view around, with no obvious triggering condition.  Maybe something to do with rendering lots of stuff at once, and maybe trees were a factor.

**Comment by lethosor** [comment]
Okay, if this is a TwbT issue, it should be opened in mifki/df-twbt instead. @pronvit, any ideas?

**Comment by pronvit** [comment]
I'll play on Windows for a bit and will try to crash it. Hard to say without any info. @WilliamCushing, do you have a crashlog?

**Comment by MrBobBarker** [comment]
I accidentally closed https://github.com/mifki/df-twbt/issues/39 when I was intending close this report. But perhaps I should just leave it up to the developers to decide how to handle it. I'm okay with closing this report and officially continuing under the df-twbt project.

**Comment by WilliamCushing** [comment]
No, don't know how to play with crashlogging enabled.  Or, if that's
default, then don't know where it would be stored.
