### ISSUE TITLE
"confirm" dialogs interfere with typing note names

### ISSUE THREAD

**Issue by strburst** [DFHack/dfhack#820]
It's impossible to type a note with the letter d in it because a confirmation dialog pops up for deleting the note, even when you're trying to enter the name of the note. Nothing happens regardless of which option is selected.

![screenshot 2016-02-11 22 19 34](https://cloud.githubusercontent.com/assets/5883232/12998084/7a3379b8-d10d-11e5-92ea-952ac91a3479.png)

Of course, disabling confirm dialogs for deleting notes fixes this, but this probably wasn't intended.

Steps to reproduce:

1. Place a note and start entering its name (`N-p-n`)
1. Type the character `d`

I noticed the unrelated issue #821 while looking into this one.

**Comment by lethosor** [comment]
Fixed in f4ce45d. You can make that change to hack/lua/confirm.lua in an existing DFHack installation if you want.
