### ISSUE TITLE
"confirm" dialogs persist after disabling then reenabling them

### ISSUE THREAD

**Issue by strburst** [DFHack/dfhack#821]
A relatively minor issue that I noticed while testing #820 was that disabling a type of confirmation dialog while it's on the screen (either through the in-game dialog or the command-line), then reenabling it during the same session through the dfhack command-line causes the same dialog to pop up again.

I was expecting any dialogs that are on the screen that are disabled to be forgotten about.

**Comment by lethosor** [comment]
Yeah, this is an oddity due to how the rendering hooks function (disabling a dialog actually disables the corresponding rendering hook, but it proved to be difficult to access and disable the actual dialog). I'll take a look.

**Comment by lethosor** [comment]
Should be fixed now.
