### ISSUE TITLE
modtools/force not working

### ISSUE THREAD

**Issue by warmist** [DFHack/dfhack#828]
In one of the version ToadyOne changed the way sieges happen. Old way of forcing them no longer works. We should do something about it.

One idea i had is to try figuring out armies. Setting army position to your site position is not enough (or at least i couldn't make it happen) but maybe there is some "target site" or something there that we don't know yet.

**Comment by expwnent** [comment]
The best way would be to custom-build an army but we don't have the structs for that yet.

**Comment by warmist** [comment]
We sort of have it. I had success creating armies. Both with hist-figures
and non-hist figures (e.g. 100 random dwarves).

2016-03-02 7:16 GMT+02:00 expwnent <notifications@github.com>:

**Comment by expwnent** [comment]
In any case we seem to be missing a destination, as you said.

**Comment by lethosor** [comment]
Superseded by #1781
