### ISSUE TITLE
Get proper compiling instructions for develop versions

### ISSUE THREAD

**Issue by ragundo** [DFHack/dfhack#836]
After all the work spent in generating a pretty documentation, something as important as compiling correctly the develop version of dfhack is not mentioned anywhere.

Please add a note in 
https://dfhack.readthedocs.org/en/stable/docs/Compile.html
telling that if you want to do that, then 

git clone --recursive https://github.com/DFHack/dfhack -b develop

must be used instead of the regular one which is for stable dfhack versions.

**Comment by lethosor** [comment]
There are a lot of other ways to get the develop branch too, like "git checkout develop". I'll add a note about that, though.

**Comment by ragundo** [comment]
That is what I did but didn’t work
 /dfhack/library/Core.cpp:1556:60: error: ‘struct df::ui_sidebar_menus’ has no member named ‘command_line’         
const string & raw = df::global::ui_sidebar_menus->command_line.raw;

I needed to type also
cd /library/xml && git pull origin master
in order to get it working

**Comment by lethosor** [comment]
Oh, you also need "git submodule update", which is mentioned in Compile.rst already.

**Comment by PeridexisErrant** [comment]
Related to #801

**Comment by ragundo** [comment]
I think that is not important if this can be done by using a) or b) or c) method. I only want to be able to compile the develop version of dfhack using the docs without needing to ask in #dfhack.

Choose one method and publish it in the dfhack.readthedocs.org and everyone will be happy

**Comment by PeridexisErrant** [comment]
This has actually already been fixed by 21631b37

So far it's only on the `latest` version of the docs, corresponding with the `develop` branch - because nothing has been merged to master since 40.24

**Comment by ragundo** [comment]
Very very good.
This is what I think is an example of good documentation

**Comment by PeridexisErrant** [comment]
@lethosor - issue closed?

**Comment by PeridexisErrant** [comment]
@lethosor again - close this?
