### ISSUE TITLE
Boost Libraries

### ISSUE THREAD

**Issue by expwnent** [DFHack/dfhack#837]
As the project grows, it may become convenient to use some libraries from Boost. The advantage is that we can use well-documented and well-tested code for complicated things instead of implementing them ourselves, but the disadvantage is it would require adding more dependencies. An extra dependency wouldn't be too bad if we just added whatever libraries we use as git submodules.

For example, I already implemented something like Boost.PropertyTree in Lua in library/lua/persist-table.lua. Had I known this existed I could have saved some time.

I'm posting this issue as a request for comment from other developers. Would people hate it if I did this?

**Comment by lethosor** [comment]
It's fine with me as long as it's possible to just build the components we need, to avoid significantly increasing compile time.
I also recall some issues with GCC 4.5, although the [documentation](http://www.boost.org/doc/libs/1_60_0/libs/log/doc/html/log/installation.html) claims that Boost 1.60 is compatible with it, so those could have just been issues with a project that used Boost.

**Comment by expwnent** [comment]
Most of boost is header-only and designed to compile fast so it should be easy to only build the components we need.

**Comment by expwnent** [comment]
The more I think about it, the more I think that we should just have it as a prerequisite instead of a submodule. Fundamentally that's how we're going to use it and it doesn't make sense to download the history of every boost component we use.

**Comment by lethosor** [comment]
With that, I'm most concerned about there being less standardization across platforms, or even across machines. Most of our current prerequisites are needed in the compilation process but don't have a direct impact on the binary itself - e.g. a difference between Perl 5 and Perl 6 is highly unlikely to actually affect the behavior of DFHack, but Boost bugs could cause issues that are really hard to track down, unless we know the exact Boost version (or versions of components) used to compile every DFHack build. From what I understand, some components also require runtime libraries, which I suppose would make diagnosis easier but would run into major portability issues in some cases if those libraries are compiled separately from DFHack.
It seems that what we've usually done for these sorts of dependencies (like Lua, protobuf, jsoncpp, etc.) is bundle them as normal files in the depends/ folder. It's not great, since we have to update them manually, although that's not a huge issue for things we don't patch. It would also open up possibilities for patches, though, and it's likely that we'd need to make at least some CMakeLists.txt changes. It also allows us to ignore the history of dependencies which we aren't involved in developing.

**Comment by expwnent** [comment]
As long as we require a particular version of boost it should be fine. Most of the boost libraries are header-only.

**Comment by expwnent** [comment]
PS: uncompressed, boost is about 437 MB, and 100 MB of that is just the headers. It seems wrong at a design level to inline all that into DFHack. I could still be convinced though.

**Comment by warmist** [comment]
I think we could just include the headers we use. That way the version would be fixed and constant throughout all the possible builds

**Comment by expwnent** [comment]
So far the headers I want to use and their (many) dependencies are 10.4 MB. Still quite high.

**Comment by lethosor** [comment]
Are those dependencies external or within boost?

**Comment by expwnent** [comment]
Within boost.

**Comment by expwnent** [comment]
The other concern is copyright / licenses. Most of the boost libraries are released under the boost license and have one author each but it would be tedious and legally error-prone to manually go through and check. The boost license only requires the license to be included when the source is included and doesn't require anything for binaries so we can side-step it by requiring developers to install boost themselves. We'd include a citation as a courtesy of course but legally it's simpler.

**Comment by lethosor** [comment]
Which libraries are you looking at? Any with runtime binaries? (For those, we'd probably have to build the binaries along with DFHack.)
Also, if we do require a specific boost version, people who need a different version for something else would run into issues. I'm sure there are ways to install multiple versions of boost, but it would involve messing around with DFHack's include paths somehow, and I don't really want to force people to maintain a separate system-wide boost installation just for DFHack.

**Comment by expwnent** [comment]
Just property_tree and its recursive dependencies, which are apparently a lot. All of them are header-only. My general thought is that if we bite the bullet and require all of boost then we'll have the benefit of being able to use any part of it with no additional cost.

That's a good point about versions. Boost doesn't guarantee backward compatibility but neither do we and they do it better than we do. I wouldn't mind making sure we stay compatible with the most recent version.

![dependencies](https://cloud.githubusercontent.com/assets/47403/13722812/81c9fae8-e81f-11e5-8568-73c0870f0303.png)

**Comment by expwnent** [comment]
@quietust @angavrilov 

Any objections?

**Comment by lethosor** [comment]
I suppose another possibility would be bundling the boost headers we need in an archive somewhere and downloading/unpacking it during the build process, like we used to do for the ruby download.

**Comment by expwnent** [comment]
That would work. As long as it could cache the old files it wouldn't be too bad for compile time.

**Comment by expwnent** [comment]
Would be useful for #414.

**Comment by expwnent** [comment]
A recursive shallow clone of the boost github repo takes about twenty minutes.

**Comment by warmist** [comment]
ugh
Maybe you would like to find a lightweight replacement for property_tree? :)

E.g. std::unordered_map<string,string> ? (because you said you used only string keys and string values)

**Comment by expwnent** [comment]
I do use nested nodes / data, especially to separate out data for different plugins. At this point I'm probably going to end up implementing my own version anyway because I'm having so much trouble getting it to work. We only use it just before the game saves and just after it loads so performance is not a huge issue as long as it's reasonable, so as long as my own implementation works correctly it will be fine. We already have a json library in the dependencies so I can use that.

The problem is eventually I'd like to use more features from boost like flat_map to increase DFHack performance and threadsafe reference-counted smart pointers (and maybe flyweights) for a rewrite of EventManager I'm playing with.

**Comment by warmist** [comment]
Just remember to profile first :)

2016-03-24 1:58 GMT+02:00 expwnent <notifications@github.com>:

**Comment by warmist** [comment]
Imho it's not worth it. Usually the performance sucks because of other reasons. Also i would like to push people to the "think about what you are doing" not "reuse boost blindly" . And using boost as you saw (with the invalidating iterators) is not trivial.

**Comment by lethosor** [comment]
Is this still an issue? I know you've moved to JSON, but I'm not sure what (if anything) we might want to use from boost in the future.
