### ISSUE TITLE
Remove digFlood

### ISSUE THREAD

**Issue by expwnent** [DFHack/dfhack#850]
It's possible to do it with vanilla now.

**Comment by PeridexisErrant** [comment]
Do you mean [digFlood](https://dfhack.readthedocs.org/en/stable/docs/Plugins.html#digflood)?

**Comment by expwnent** [comment]
Yeah, that one.

**Comment by PeridexisErrant** [comment]
Related to #735; specifically `advtools`, `misery`, and `treefarm` which haven't been built since 34.11

**Comment by lethosor** [comment]
It looks to me like digFlood allows digging veins of specified types discovered in the future, which isn't possible in vanilla DF

**Comment by expwnent** [comment]
I had forgotten. I suppose people might still want it for that feature, so no need to remove it.
