### ISSUE TITLE
Add a search/filter to command list

### ISSUE THREAD

**Issue by quicksketch** [DFHack/dfhack#869]
I frequently want to do a search or filter on the list of commands in dfhack. I can usually remember that a command exists, but not its exact name. For example, when trying to remove ramps, some times I'll do `unramp`, `removeramp`, `rampremove`, etc. before I hit on `deramp`. If I'm desperate I'll open a web browser and visit http://dfhack.readthedocs.org/ (which is very nice, BTW, but inconvenient to pull up).

If this were a typical Linux command, I would use `ls | grep ramp` to filter the listing down by piping it through grep. Obviously that syntax is obtuse for non-nerds, so I'd like to see something more like `search ramp` or maybe just an extension to `ls` as `ls ramp`. Note this wouldn't map exactly to the Linux command for `ls`, which would only list files that _started_ with `ramp`, instead it would include all commands (and their help) that contained that word.

Also related/useful but a different request is tab-completion over in #696.

I love the work you've done with dfhack, thanks!

**Comment by PeridexisErrant** [comment]
Hmm.  What would you think of a script `search.lua` that opened the html docs search page, with any args to the script as search parameters?  If it used the local html, that should be really fast.

**Comment by warmist** [comment]
Imho the html idea is bad of context switches. I.e. changing where you are looking and what you are trying to understand. 
Even if it opens browser to local file - browser startup times are HUGE (and memory usage).

I think it's would be quite easy to implement **ls ramp**.

**Comment by PeridexisErrant** [comment]
Easy to implement `ls ramp` with the unixlike behaviour, sure.  It would be good to do that either way, since it does offer the less powerful but more in-flow option.

Making `search ramp` also search command help would be much harder, and you'd need to either use the docs or search all the input files for the docs (and not all are distributed!).  It's not always ideal, but it would be useful sometimes!

**Comment by expwnent** [comment]
This sounds interesting a good idea.

**Comment by lethosor** [comment]
Maybe wildcards like `ls *ramp*` could work.

**Comment by expwnent** [comment]
We'd have to distinguish between ls foldername and ls searchstring.

**Comment by lethosor** [comment]
Right now, the only non-flag argument to ls specifies a plugin name.

**Comment by quicksketch** [comment]
> We'd have to distinguish between ls foldername and ls searchstring.

I'm not sure it is necessary to distinguish between the description and the plugin name itself. There is a pretty limited number of commands, and if I'm interested in a string it'd be useful to search both all the time. I'm not sure if that's what you meant. Does `ls` deal with files/folders on disk as well? I've only ever used it to list commands.

> What would you think of a script search.lua that opened the html docs search page, with any args to the script as search parameters?

The online docs are already good enough at doing searches. If I need full help then using the online docs is not a problem for me. I'm already going to the wiki for in-depth information anyway. This request is really about finding the command I want, rather than providing help. So while something like this might be nice, it wouldn't fit the request.

**Comment by myk002** [comment]
search is now implemented for `ls` and `gui/launcher`

**Comment by quicksketch** [comment]
Awesome! Can't wait to try it out!
