### ISSUE TITLE
Make autochop estimate the number of logs you get from a tree

### ISSUE THREAD

**Issue by expwnent** [DFHack/dfhack#876]
Instead of periodically designating all trees in the selected burrows, designate enough trees to produce enough wood to get to `max_logs`, or all of them if there aren't enough.

**Comment by RogueYun** [comment]
If autochop can estimate how much wood a tree can produce, would it be possible set it to prioritize cutting the oldest trees (or the ones that are not likely to grow anymore) first?

**Comment by expwnent** [comment]
Sure.

**Comment by aljohnston112** [comment]
I could work on this one. It's a feature I was looking for.

**Comment by aljohnston112** [comment]
I was able to get the right amount of logs for a willow tree with the following code.

`
                    df::plant_tree_tile** tiles = plant->tree_info->body;
                    df::plant_tree_tile* tilesRow;
                    int trunks = 0;
                    for (int i = 0; i < plant->tree_info->body_height; i++) {
                        tilesRow = tiles[i];
                        for (int j = 0; j < plant->tree_info->dim_y*plant->tree_info->dim_x; j++) {
                            trunks += tilesRow[j].bits.trunk;
                        }
                    }
                    out << "Trunks: " << trunks << std::endl;;
`

**Comment by lethosor** [comment]
Cool! Do you have other plans or questions, and/or do you plan on putting up a PR?

If it helps, feel free to get in touch at any of [these](https://docs.dfhack.org/en/stable/docs/Support.html) places as well.

**Comment by Moth-Tolias** [comment]
if @aljohnston112 is otherwise unable to make a pr, i'd like to look into implementing this.

**Comment by ab9rf** [comment]
> if @aljohnston112 is otherwise unable to make a pr, i'd like to look into implementing this.

Go for it.
