### ISSUE TITLE
digfort/blueprint multilevel capabilities

### ISSUE THREAD

**Issue by quicksketch** [DFHack/dfhack#878]
`digfort` and friends (`blueprint`, `fortplan`) indicate from their help that they support multiple Z-levels. However, in practice they don't quite work.

When specifying multiple z-levels in blueprint, only the first layer is found. CSV rows for subsequent levels are generated, but they are all empty. e.g. I was trying to do a 3x3 spiral, but it only got the first layer: `blueprint 3 3 5 3x3-spiral dig`

```
#dig
 , ,d,#
 ,h,d,#
 , ,h,#
#<
 , , ,#
 , , ,#
 , , ,#
#<
 , , ,#
 , , ,#
 , , ,#
#<
 , , ,#
 , , ,#
 , , ,#
#<
 , , ,#
 , , ,#
 , , ,#
```

So I manually made multiple single-level csv files and combined them together to make the "correct" CSV export:

```
#dig
 , ,d,#
 ,h,d,#
 , ,h,#
#<
 , , ,#
 ,h, ,#
h,d,r,#
#<
h, , ,#
d,h, ,#
r, , ,#
#<
r,d,h,#
 ,h, ,#
 , , ,#
#<
 , ,r,#
 ,h,d,#
 , ,h,#
```

Then I attempted to import this custom file using `digfort 3x3-spiral-dig.csv`. But the resulting dig operation ended up all on one floor instead of across z-leves:
![selection_079](https://cloud.githubusercontent.com/assets/100206/13973712/f7a2df5a-f062-11e5-870d-d6a405990c8b.png)

It looks like these plugins are _almost_ there as far as z-level support, but there is a little left to adjust. Thanks for the hard work so far!

**Comment by PeridexisErrant** [comment]
Related to #499

**Comment by warmist** [comment]
Huh. At least the digfort does not have any code or documentation about multiple levels. Also it ignores everything after "#" so "#<" means nothing to it. Is this notation used somewhere?

**Comment by PeridexisErrant** [comment]
The notation is for [Quickfort-compatible blueprints](http://www.joelpt.net/quickfort/#editing-blueprints), with the caveats that DFHack does not support excel spreadsheets, and macro support is (iirc) uninplemented.

Blueprint is meant to produce these files.

**Comment by cdombroski** [comment]
IIRC, when designating rectangular prisms in DF, z-levels increase going up. In other words, the cursor specifies the bottom southwest corner if you use positive ranges.

Try placing the cursor at the bottom of the desired area, or using a negative z-range to get the desired output from the blueprint plugin.

**Comment by Amostubal** [comment]
confirmation this is still an issue in the current dfhack library. Digfort does not seem to move up/down DF z levels to dig additional areas it just continues to draw each floor south of each other.  The initial poster did fail to understand that a positive z in buildingplan would not select the layers below(that's negative) as Cdombroski commented.

**Comment by Amostubal** [comment]
additional note... blueprint does not use a different designation for up or down z it uses the same symbol in both. even though it grabs the floors in the order designated.

**Comment by cdombroski** [comment]
Blueprint uses the same symbol between floors because it always extracts the floors in the same direction (iirc, it starts at the lowest requested floor and goes up)

**Comment by Amostubal** [comment]
Yeah I figured as much.  after reviewing the code,  if you give it a -z it just flips the order and goes to the bottom and comes back to the floor your on.  which really isn't a good way to implement the code.   the help doesn't provide that kind of information on blueprint which means the player thinks the csv should be in the direction that he designates.

**Comment by myk002** [comment]
this is solved in the new quickfort script (PRs attached to #499)

**Comment by myk002** [comment]
This is fixed with `quickfort` and recent changes to `blueprint`
