### ISSUE TITLE
Not found: data/art/curses_800x600.png

### ISSUE THREAD

**Issue by cmcsun** [DFHack/dfhack#882]
CSDUJ[01:42]raina@rainadesk~/ownCloud/dwarf_fortress/df_linux$ LD_PRELOAD=/lib32/libz.so.1 ./dfhack
ERROR: ld.so: object '/lib32/libz.so.1' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/lib32/libz.so.1' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/lib32/libz.so.1' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/lib32/libz.so.1' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/lib32/libz.so.1' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/lib32/libz.so.1' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.

Dialog Box Opens with: Not found: data/art/curses_800x600.png

Any ideas?

**Comment by lethosor** [comment]
What distro are you using? Does /lib32/libz.so.1 exist?

**Comment by sv-esk** [comment]
Its /usr/lib32/libz.so.1 on ArchLinux.
Checkout [mantis post](http://www.bay12games.com/dwarves/mantisbt/view.php?id=2688#c31110) and LNP's distro_fixes.sh
Why LNP's fixes are not integrated in dfhack?

**Comment by lethosor** [comment]
The DF issue was mostly resolved by upgrading the DF build system, and given the lack of complaints we've seen since, I don't think this is something that we need to address on our end.
