### ISSUE TITLE
"tweak advmode-contained" crashes occasionally during adventure mode reactions (e.g. carving bone)

### ISSUE THREAD

**Issue by WindySkunk** [DFHack/dfhack#883]
DF version 42.06
DFHack version 42.06-alpha2-windows
OS is Windows 7

**Comment by lethosor** [comment]
Are you using TwbT?

**Comment by WindySkunk** [comment]
I am not using TwbT.

**Comment by lethosor** [comment]
Does this happen in all worlds? Are you talking about vanilla reactions or advfort?

**Comment by WindySkunk** [comment]
It happens in every world I've tried so far, and occurs for vanilla reactions. (No modifications other than DFHack).

**Comment by lethosor** [comment]
Any particular reactions?

**Comment by WindySkunk** [comment]
It doesn't seem to be any reaction in particular.

**Comment by lethosor** [comment]
I haven't really played adventure mode in 0.42.06, so how do you perform these sorts of reactions?

**Comment by WindySkunk** [comment]
In adventure mode press x to open up the reactions and interactions menu, the reactions are in the (c)reate submenu. You will have to gather small stones from the ground or kill some animals, butcher them and gather their bones to get the materials to do the reactions.

**Comment by lethosor** [comment]
I couldn't get the crash to occur with knapping (with some rocks), and I wasn't able to find wild-enough animals to get usable bones. Do you happen to have a save where it's easy to get to a crash?

**Comment by WindySkunk** [comment]
Uploaded a save (and some macros to make the crafting quicker).
http://dffd.bay12games.com/file.php?id=11896

**Comment by lethosor** [comment]
I just got a crash, but it seems to be happening in DF. Will continue investigating.

**Comment by lethosor** [comment]
Possibly related to `tweak advmode-contained`

**Comment by lethosor** [comment]
Looks like an issue with `viewscreen_layer_unit_actionst::reagent`

**Comment by lethosor** [comment]
Yeah, a couple new things in that viewscreen were throwing off the layout. Should be fixed for the next release.
