### ISSUE TITLE
Old stuff from dfusion

### ISSUE THREAD

**Issue by warmist** [DFHack/dfhack#884]
Some old stuff might be carried over. Almost nobody uses it but maybe if it was a script it would be more useful.
- [ ] reincarnate - needs to be tidied up
- [x] make-site - not sure if it's worth it because it's very small
- [ ] change adventurer - pretty sure there was other tool that did the same but with more limits (i.e. did not allow for invalid changes)

Anyone is free to do this, but this is mostly that i don't forget it.

**Comment by lethosor** [comment]
Some people complained about the change-adventurer tool being gone on the forums recently, so this would be nice to get done.

**Comment by warmist** [comment]
Make-site is useless, now that df has it.

**Comment by warmist** [comment]
Okay. I've added those two scripts into github. You can find them here: [from-dfusion branch](https://github.com/warmist/scripts/tree/from-dfusion)
However they are imho not merge ready: no documentation, it's a almost direct port (and it's ooollld code), etc...

**Comment by lethosor** [comment]
Oh, nice. I was mostly trying to categorize this issue, but thanks for doing that!
