### ISSUE TITLE
dfhack.items.moveToBuilding sets in_building flag when in mode 0

### ISSUE THREAD

**Issue by KlonZK** [DFHack/dfhack#885]
items that are contained but not installed in buildings normally dont have this flag. the items apparently behave as if they were a structural part of the building, ie, they cant be hauled/taken away. they display with a deep blue [B], as opposed to the white [B] that normal build materials have.

unsetting this flag after the operation makes the items available for jobs again. i suggest to just not set that flag in mode 0. (whatever the difference may be between the 2 modes, except for the color)

**Comment by lethosor** [comment]
What about mode 2? One of the modes is for items reserved in some way, so there may be a good reason for setting that flag.

**Comment by KlonZK** [comment]
mode 2 is the mode that actually installs items into buildings, they will then become structural part of that building (or at least, they will display that status and not be available for jobs etc).

there might be a reason to set that flag, but as far as i can see there is no practical difference between the 2 modes and there is no mode 1, and, incidentally, there is no mode that *just puts* items into buildings.

**Comment by lethosor** [comment]
There is a mode 1 (and possibly other modes as well), but it's not supported by this function for some reason.

**Comment by KlonZK** [comment]
well, anyway. from my perspective the most obvious way for this to work would be that mode 0 (or no mode) just puts stuff in a building like in a container.

**Comment by warmist** [comment]
IIRC only two modes are used by vanilla df. All others are legacy. Also i'm not sure what the intent of moveToBuilding was or maybe it was less researched...

Also i think this relates to #877

**Comment by KlonZK** [comment]
well then something must be borked, because vanilla items that are dropped in a building by jobs dont have this flag, ever. using a move to location call would instead put the items outside, on top/behind the building.

**Comment by lethosor** [comment]
@warmist: looks like you added `in_building=true` in the original version of the function (48185568e9a9370f843fb28f1ff53335639b92d6) and it's always been there. It does appear that normal items in buildings don't have `is_building` set - setting it for items in depots makes the yellow `[T]` (trade) indicator show up.
It does seem like not setting the in_building flag should work, then. Any objections?

**Comment by warmist** [comment]
We should think how new people would use it. Imho we should explicitly ask for another bool "part_of_building" or something like that and then just do in_building=part_of_building. This way it would be more clear what it does.

**Comment by lethosor** [comment]
My point is that in all of the saves I've tested, `in_building` is *always* false when `use_mode` is 0, so I think setting `in_building` when `use_mode` is 0 is incorrect.

**Comment by lethosor** [comment]
Okay, it turns out that stones in stone fall traps do have `use_mode` set to 0 and `in_building` set, so I'll add an optional argument to moveToBuilding() to account for that.

**Comment by KlonZK** [comment]
what about using no argument as default to just move stuff?

**Comment by lethosor** [comment]
I'm making `use_mode` default to 0 so you don't have to specify it, if that's what you mean.

**Comment by KlonZK** [comment]
basically. thx :)
