### ISSUE TITLE
Exploding Clay randomly, affected 2 worlds and sites. Completely burys my fort.

### ISSUE THREAD

**Issue by Starhero** [DFHack/dfhack#886]
I am gonna let the file I post speak about the issue more deeply then I will speak here. I am posting this here as another player also thought this could be a DF Hack bug as the entire map is reveals after the bug takes place.

There is a save file on DFFD that is primed to show this bug off, it shoudl trigger, unaggitated, within 7 days at least.

Please read the description of the file before downloading. I did provide as much info as I could, but would be happy to help with anymore more.

At a loss on what to do next....I haven't debugged DF like I have for other games like MC and such, so I am not sure of the tools I could use to get more info..

Fortunately, the file is public, and smarter people can do it faster then I could with better results.

Rubble is also on this, so if it is determined not to be DF, thats my next stop.

**Comment by Starhero** [comment]
So tired I almost forgot the file!

http://dffd.bay12games.com/file.php?id=11906

**Comment by lethosor** [comment]
Have you used open-legends in this save?

**Comment by sv-esk** [comment]
duplicate https://github.com/DFHack/dfhack/issues/805 - same symptomes.
Checked save - `world.world_data.region_details` and open-legends is old.
