### ISSUE TITLE
Bug for fix/build-location is fixed in DF

### ISSUE THREAD

**Issue by PeridexisErrant** [DFHack/dfhack#891]
[fix/build-location](https://dfhack.readthedocs.org/en/latest/docs/_auto/fix.html#fix-build-location) links to [bug 5991](http://www.bay12games.com/dwarves/mantisbt/view.php?id=5991), which was fixed in DF 40.05

Either the whole script should be removed, or the readme updated.

**Comment by lethosor** [comment]
> Fixes construction jobs that are stuck trying to build a wall while standing on the same exact tile

I haven't investigated, but it's possible that Toady's fix just prevents the wall tile from being assigned in the first place, and doesn't fix jobs that are already stuck or jobs that become stuck in other ways. In other words, unless DF does effectively the same thing as this script when handling jobs, I'd say keeping it around (with documentation changes) wouldn't hurt. We'd need to do some research first to find out what the situation is, though.

**Comment by myk002** [comment]
Script is gone from tree
