### ISSUE TITLE
[Suggestion] Autochop Min/Max Logs needs a rework.

### ISSUE THREAD

**Issue by RogueYun** [DFHack/dfhack#893]
Trying to adjust min/max logs by using hjHJ/klKL is a pain in the neck when your goal is to keep the screen (or a burrow) clear of trees. Often I have to adjust logs to ludicrously high numbers like 10000 when in a densely forested biome, and repeatedly smashing shift+j starts to hurt my wrists.

My suggestion is two fold:
1.) Set the option so that you can type the min/max logs in. (Similar to wheelbarrows in stockpiles and workflow).
2.) Set an option to ignore min max and just cut down any and all trees in the designated area(s).

Thanks everyone for all you do! Keep up the good work!

**Comment by lethosor** [comment]
Wouldn't a ridiculously high maximum accomplish part 2?

**Comment by RogueYun** [comment]
It would, or having a high min value would, and it would most likely be easier to code. I just made the suggestion in case it was easier on the program or programmer to designate all trees for chopping over having to calculate min/max values first.

**Comment by lethosor** [comment]
It would probably be easier to store a large value internally and display it as "unlimited". Would a large minimum or maximum be preferable?

**Comment by RogueYun** [comment]
Minimum. Iirc, trees will stop being designated if logs are above the min.

**Comment by lethosor** [comment]
Looks like it's working to me (it just designated *everything*), so it should be in the next release.
