### ISSUE TITLE
viewscreen_setupadventurest layout incorrect

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#899]
(Tracking this here to block r1)
Currently working on this at https://github.com/lethosor/df-structures/tree/0.42-viewscreen_setupadventurest

**Comment by lethosor** [comment]
It's incomplete, and deleting DFHack-created instances of the viewscreen crashes, but accessing fields doesn't crash any more in the testing I've done, so I'll merge what I have for the next release and keep this around.

**Comment by lethosor** [comment]
dfhack/df-structures@b9d515b078d7cd9a4754e79d1b7dab53bcc2f117 has fixed a large portion of this. I'll leave this open for now, but it should be usable enough for r1.

**Comment by lethosor** [comment]
More progress: https://github.com/DFHack/df-structures/commit/b9d515b078d7cd9a4754e79d1b7dab53bcc2f117 

The layout is consistent, from what I remember, although I think `df.viewscreen_setupadventurest:new():delete()` still crashes. That could simply be due to DF's destructor expecting the screen to be set up in a way that DFHack's constructor doesn't do, or expecting the world to be set up somehow, etc..

**Comment by quietust** [comment]
I've made a few fixes to that structure with 987fa45cbd1a11850f59f8599a19850f458011d9 and fb8a1292a2f87fd343d7cfb9b5ad2e2b80a71231 to align them on Windows 32-bit.

**Comment by lethosor** [comment]
Looks good to me on OS X as well, so presumably it's good on Linux too. (Forgot to reply earlier, apparently.)
