### ISSUE TITLE
Quickly placing furniture crashes the game

### ISSUE THREAD

**Issue by knorthfe** [DFHack/dfhack#905]
Tested using DF 0.42.06 and the one before it as part of LNP 0.11. I found if I quickly placed tables/chairs/doors/cabinets/chests, etc quickly in succession the game would crash. I ended up quicksaving often and placing them quite slowly. Recently tried disabling DFhack and placed items as fast as I possibly could and had zero crashes. Someone on reddit suggested that it could be a known problem with things interacting with growing trees but these were items all being placed in dwarven rooms inside the mountain.

**Comment by lethosor** [comment]
This sounds similar to a known TwbT issue. What happens if you disable TwbT temporarily?

**Comment by knorthfe** [comment]
I disabled TWBT and tried with Print Mode: 2D and Standard and couldn't reproduce the problem in either of them, but switched to TWBT and while it took a second it did crash after trying to rapidly place some furniture so it seems it is indeed a TWBT related issue. Just wanted to make sure someone knew about it, I'll play without fancy text for now.

**Comment by lethosor** [comment]
I couldn't find a report in the TwbT repo, but mifki is aware of the issue, so I'll close this one. Thanks for reporting back.
