### ISSUE TITLE
Move Sphinx build directory to inside CMake build directory

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#907]
It's generally better to have anything generated at build time inside the current CMake build folder ($CMAKE_BINARY_DIR, e.g. `build`, `build-osx`, `build-cross-linux`, `build-gcc4x`, etc.) instead of in the DFHack source tree. When multiple build directories are being used in the same DFHack clone, a build step in one writing to files in the source tree (outside of the current build folder) can cause the build process in all other build folders to re-run jobs that depend on those files unnecessarily. I'm not entirely sure if anything does depend on the generated HTML files (there shouldn't be anything, ideally, aside from the installation process), and the HTML files should be consistent regardless of the build directory, but it would be good practice nonetheless.

(I ran into a similar issue with protobuf's testHashMap.cpp being placed in the source tree, which meant that switching build directories and running `make` would re-run `cmake` every time, since testHashMap.cpp had been changed from the other build folder.)

**Comment by lethosor** [comment]
Actually, Sphinx is smart enough to not rebuild anything if the docs haven't changed since another build process built them. Not sure if this is necessary at all, then.

**Comment by expwnent** [comment]
Even if there isn't a technical reason it would be a better design just on principle. It would also let windows users easily nuke the entire build and start over if something gets horribly messed up.

**Comment by PeridexisErrant** [comment]
> Sphinx is smart enough to not rebuild anything if the docs haven't changed

Given that it's a smart build that doesn't vary by platform, I'd stick with the current system.  There's a non-trivial number of things that would have to change, from build scripts to the script-autodoc system to README.html redirects, etc.

**Comment by lethosor** [comment]
Why would README.html have to change? It's just a question of building docs in build/docs/html instead of docs/html - they'd all be in hack/docs once installed.
It's probably not a big issue, though. Might as well keep it as-is.
