### ISSUE TITLE
Compile failure on OS X

### ISSUE THREAD

**Issue by hughjonesd** [DFHack/dfhack#909]
Following the instructions in Compile.rst:

```
cmake .. -DCMAKE_BUILD_TYPE:string=Release -DCMAKE_INSTALL_PREFIX=/Applications/Macnewbie/Dwarf\ Fortress/
make install

```
Everything is fine until:
```
[ 30%] Built target clsocket
[ 30%] Generating ../../library/include/df/codegen.out.xml
[ 30%] Built target generate_headers
[ 30%] Generating ../../library/proto/Basic.pb.cc, ../../library/proto/BasicApi.pb.cc, ../../library/proto/CoreProtocol.pb.cc, ../../library/proto/Basic.pb.h, ../../library/proto/BasicApi.pb.h, ../../library/proto/CoreProtocol.pb.h
/bin/sh: line 1: 70826 Bus error: 10           ../depends/protobuf/protoc -I=/Users/david/dfhack/library/proto/ --cpp_out=dllexport_decl=DFHACK_EXPORT:/Users/david/dfhack/library/proto/ /Users/david/dfhack/library/proto/Basic.proto /Users/david/dfhack/library/proto/BasicApi.proto /Users/david/dfhack/library/proto/CoreProtocol.proto
make[2]: *** [../library/proto/Basic.pb.cc] Error 138
make[1]: *** [library/CMakeFiles/dfhack.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by lethosor** [comment]
If you're on 10.11 (or maybe 10.10), I think the easiest solution is to install XCode 6 and use xcode-select to switch to its command line tools (or tell cmake to use its assembler somehow).

**Comment by lethosor** [comment]
(Also, that's mentioned at the top of https://dfhack.readthedocs.org/en/latest/docs/Compile.html#mac-os-x )

**Comment by hughjonesd** [comment]
Apologies. I thought that as I'd installed gcc-4.5 and the other
dependencies, I didn't need XCode 6. My misreading. Your suggestion fixed
it.

David

On 26 April 2016 at 19:45, Lethosor <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> (Also, that's mentioned at the top of
> https://dfhack.readthedocs.org/en/latest/docs/Compile.html#mac-os-x )
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/DFHack/dfhack/issues/909#issuecomment-214845883>
>



-- 
Sent from Gmail Mobile
