### ISSUE TITLE
"cast" script to use dfhack commands with ingame penalties

### ISSUE THREAD

**Issue by PeridexisErrant** [DFHack/dfhack#910]
https://www.reddit.com/comments/4gasny//d2ijwo1

>>> I've pondered briefly on making a mod where a lot of the DFHack commands (reveal, transmute a tile, autodump, etc.) are enabled through some sort of mana/mystic power mechanic. So if your dwarfs are happy and praying you get power to do things like 'cast' reveal for a short period of time. Maybe this mod already exists but anyway, that's how I justify some of my DFHacking, heh.

>> Ooh, nice idea for a script!  `cast $command` runs that command, and adds some stress to your dwarves. Alternatively, maybe you could have an option which sacrifices valuable items instead...

> Oh, I like that! A mechanic which, if abused, can result in your dwarfs having mental breakdowns! Plus it could be implemented without any big changes to the game if you base it off of stress. 'Urist was irritated by witnessing a supernatural phenomenon.' I'm thinking to have it impact everyone though since it would be more... interesting.

Basically, a script which does something - possibly depending on what command it's given - then runs that command.  The idea is to add immersion or justify 'cheating' by adding a (optional) penalty to DFHack commands.

**Comment by expwnent** [comment]
It seems like this would fit together with Roses' scripts very well.

**Comment by PeridexisErrant** [comment]
Closing, as I feel issues should not be used to record feature requests.

**Comment by warmist** [comment]
I would say that issues are used to record feature request for quite a lot of projects. And been used for dfhack for some time. However they are not used as often as in other projects and are not as strict. E.g. this feature request is too vague, implementations are too numerous and there is no "right" way to do it. Some feature might be required by the "engine" (meaning c++ plugins or core or modules) but currently there is no indication of that.

**Comment by PeridexisErrant** [comment]
I haven't gone through and removed all of my feature requests, don't worry!  This one in particular though is (a) not my idea in the first place, and (b) seems less 'core' to DFHack than most things.

**Comment by expwnent** [comment]
Super late to the thread, but I'm fine with issues as feature requests. That way we can auto-close them in pull requests and inter-connect them when they're related. [We already have a lot of them.](https://github.com/DFHack/dfhack/labels/idea)
