### ISSUE TITLE
Alt+M mousequery keybinding isn't working

### ISSUE THREAD

**Issue by Gester4498** [DFHack/dfhack#916]
Dfhack version 42.06-r1

Not running anything else besides DF w/ Dfhack and basic windows programs.

As the title suggests the Alt+M keybind on the mousequery plugin doesn't work.  All the other alt keybinds in DF and Dfhack seem to work fine except this one.

**Comment by lethosor** [comment]
This one uses DF's keybinding system. Can you search for CUSTOM_ALT_M in data/init/interface.txt?

**Comment by Gester4498** [comment]
[BIND:CUSTOM_ALT_L:REPEAT_NOT]
[SYM:4:l]
[BIND:CUSTOM_ALT_M:REPEAT_NOT]
[SYM:4:m]
[BIND:CUSTOM_ALT_N:REPEAT_NOT]
[SYM:4:n]

This was in the interface.  I went into DF and unbound the key then rebound it and restarted DF and it seems to be working now.  Odd that it wasn't hooking it the first few times i tried but it's good now.  Please close.  =)

**Comment by lethosor** [comment]
Well, that looks right to me. Let us know if you can figure out what was causing it. (I believe Quickfort once caused issues, but not exactly what you were experiencing, and it sounds like you weren't using it anyway.)
