### ISSUE TITLE
Incorporate ClickableLabel

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#919]
Source: https://gist.github.com/Putnam3145/e5d4aab2228b44b51b830021da4631c2 (@Putnam3145)
Example: https://i.imgur.com/dLReqXu.gif
Need to decide if this would be better to add to Label or create a new class for.

**Comment by warmist** [comment]
I vote adding to original label. The source code even has mentions of "when this will be clickable with mouse"

**Comment by PeridexisErrant** [comment]
Ooh, nice.  Possibly related to #500 clickable menus?  There would be an awkward level of re-implementation, but given the possibilities of rearranging things *ala* the old menu improvement suggestions it could be worth it for a keen modder.

**Comment by Putnam3145** [comment]
Yeah, I don't think it would be altogether that useful for replacing the functionality of existing menus. For that, I'd use a transparent viewscreen with its onInput(keys) set to recognize certain areas (which would probably need to be set every onResize(w,h), but that's fine). It's mostly just for DFHack dialogs. I could see a lot of the gui scripts be improved by it, though.
