### ISSUE TITLE
Complilation error, need to include <math.h>

### ISSUE THREAD

**Issue by bamonroe** [DFHack/dfhack#929]
Hi, I didn't really feel like forking, patching, requesting pull request for a one liner:

I believe you're missing `#include <math.h>` in `plugins/3dveins.cpp` for the devel branch

Without it you can't use the `ceilf()` function in line `1387` of this file, causing a compilation error. I added this in to my local copy and it was able to get past the compilation error. I'm not very experienced with c/c++ so I'm not sure if this function was supposed to be declared in one of the other headers, but it seems to be from the `<math.h>` header.

Cheers,
Brian

**Comment by lethosor** [comment]
Wait, just on the develop branch? What compiler are you using?

**Comment by bamonroe** [comment]
I only tried the develop branch. Sorry I should have included my deets in the first post.

Arch Linux 64

    ~: uname -r
    4.5.1-1-ARCH
    ~: pacman -Q gcc-multilib cmake perl-xml-libxml perl-xml-libxslt dwarffortress
    gcc-multilib 6.1.1-1
    cmake 3.5.2-2
    perl-xml-libxml 2.0124-2
    perl-xml-libxslt 1.94-2
    dwarffortress 0.43.02-1

**Comment by lethosor** [comment]
Fixed in 9be9285
