### ISSUE TITLE
const method wrappers in lua

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#935]
It seems that wrapping const methods isn't currently possible (which I discovered when trying to wrap a custom method; I don't believe any vmethods can be defined as const in df-structures, so this hasn't come up before). It looks to me like making it possible would require adding 4 additional specializations of `function_wrapper` to `INSTANTIATE_WRAPPERS2`, and 2 specializations of `return_type` to `INSTANTIATE_RETURN_TYPE`, in DataFuncs.h. 

What I don't know is if the Lua API has some special way of dealing with read-only objects for const methods, so I'm holding off on this for now (*pings @angavrilov*)

Related to https://github.com/DFHack/df-structures/pull/133

**Comment by warmist** [comment]
I think the idea was to have the wrapper as simple as possible: no private, no const, no other crud that means compiles to nothing. E.g. all vmethod takes pointers instead of references, because that is what the decompiled code looks like. The original code probably had references there.

**Comment by lethosor** [comment]
A couple things:
- According to @quietust, some vmethods *should* be const but aren't marked as such currently, so they can't be used with const objects in C++ easily
- Some custom methods are already const, for good reasons, and I don't want to make them non-const to wrap them

I think my main concern was that const-ness of objects wouldn't be tracked by the Lua API and could crash, but now that I think about that, the only way for that to happen would be to call a non-const method on a read-only object, which can already happen.

Anyway, this actually only requires 1 return_type and 2 function_wrapper specializations (since non-methods can't have the `const` qualifier).

**Comment by lethosor** [comment]
Const vmethod support should go in df-structures.
