### ISSUE TITLE
df.global.ui_advmode Structures identification/research

### ISSUE THREAD

**Issue by AtomicChicken** [DFHack/dfhack#942]
**df.global.ui_advmode.anon_9**
This is initially equal to df.global.cur_year_tick_advmode and they both increase at the same rate. However, it does not seem to update when sleeping and fast-travelling, resulting in a value which differs from df.global.cur_year_tick_advmode

**df.global.ui_advmode.anon_50**
Hours of sleep. This value is updated whenever the player changes the number of hours to be slept when viewing the sleep menu.

**df.global.ui_advmode.anon_56**
Is usually set to **0**
Is set to **2** when the adventurer unit is unconscious/falling
Setting it to **0** when the adventurer is unconscious allows the player to move the adventurer, but it is immediately set to **2** again if the unit is still unconscious
Hence, it seems that this is what prevents a player from controlling the adventurer when such a status effect is in play.

**df.global.ui_advmode.anon_59 
df.global.ui_advmode.anon_60
df.global.ui_advmode.anon_61**
anon_59 is an x coordinate, anon_60 is y, anon_61 is z
These coordinates appear to be set when the adventurer becomes a projectile via jumping/falling; they are the coordinates where the flight trajectory ends (not necessarily the chosen target coordinates when jumping).

**df.global.ui_advmode.anon_15
df.global.ui_advmode.anon_16
df.global.ui_advmode.anon_17**
anon_15 appears to contain a list of x coordinates
anon_16 appears to contain a list of y coordinates
anon_17 appears to contain a list of z coordinates
(values in each list are initially set to -1000000)
Each entry is likely combined with its equivalents in the other anons, but the overall function remains unknown.

**df.global.ui_advmode.anon2
df.global.ui_advmode.anon3**
and
**df.global.ui_advmode.unk23
df.global.ui_advmode.unk24**
The above two pairs appear to be linked with the adventurer’s position on the map, though I’m not yet sure about the specifics. The values appear to be updated only when the map is reloaded, or when the adventurer enters travel mode.

**df.global.ui_advmode.menu = 30** 
The “select target” screen for interactions

The following are set when the adventurer loads the interaction target selection screen:

**df.global.ui_advmode.unk_1e8** 
Used when the interaction is a “natural ability” (otherwise, it is set to -1)
Relates to the interaction's index in the adventurer's unit.curse.own_interaction

**df.global.ui_advmode.unk_1ec**
Used for acquired interactions (otherwise set to -1)
This relates to the interaction as shown below: df.interaction.find(df.global.world.raws.effects.interactions[df.global.ui_advmode.unk_1ec])

**df.global.ui_advmode.unk_f4**
The maximum number of targets for the interaction 

**df.global.ui_advmode.unk_f8**
The maximum range of the interaction

**df.global.ui_advmode.unk_fc**
Possibly relates to the interaction target type?
For example, changing it to “4” made “disturber only” show up on the target selection screen.
“2” = adjacent only , “6” = adjacent only, disturber only
However, higher values seem to be repetitions, so I am uncertain about this.

**df.global.ui_advmode.unk_1e4
df.global.ui_advmode.unk_f0
df.global.ui_advmode.unk_200**
Unknown function, but changing their value crashes the game upon attempting to view the interaction screen. 
unk_f0 and unk_200 appear to be reset to 0 once the interaction is carried out

**df.global.ui_advmode.unk37
df.global.ui_advmode.unk38**
Contain userdata which seems to be created upon when the interaction target selection screen is loaded. Deleting the userdata in unk38 causes any available target choices to disappear. Moving the cursor causes it to reappear, with userdata being generated again. Userdata in unk37 does not seem to regenerate.

**Comment by quietust** [comment]
Are you doing research on 0.43 or on 0.42/0.40?

I ask because the anon_15/anon_16/anon_17 lists you mentioned are actually anon_24 thru anon_26 in the latest structure definitions, so all of your other "anon_*" labels are most likely wrong.

**Comment by AtomicChicken** [comment]
Ah, my mistake; I forgot to specify. All research was carried out in 0.42.06 .

**Comment by lethosor** [comment]
This should really be in https://github.com/DFHack/df-structures, by the way.

**Comment by AtomicChicken** [comment]
My bad. I'll keep that in mind next time.

**Comment by lethosor** [comment]
Moved to https://github.com/DFHack/df-structures/issues/155
