### ISSUE TITLE
crash on render fat

### ISSUE THREAD

**Issue by BenLubar** [DFHack/dfhack#943]
To reproduce:

- Construct a kitchen and a butcher shop.
- Mark the pack animals for butchering.
- Wait until fat is rendered.

This happens on Windows and Wine, but not on native Linux. The crash does not occur if DFHack is not installed or if `unload -all` is run before the world is loaded.

World where this is reproduceable 100% of the time: https://github.com/DFHack/dfhack/files/309811/region1.zip (embark in the default position)

**Comment by Buttergott** [comment]
I can confirm this. The game crashes with 100% accuracy.

**Comment by lethosor** [comment]
Quietust thinks this is probably a structure issue, maybe causing EventManager to crash.

**Comment by BenLubar** [comment]
The crash does not occur when `eventful` is unloaded.

**Comment by BenLubar** [comment]
```
Argument size mismatch: 0043e6f0 item(itemst)::addImprovementFromJob #86 - expected 44, found 52 bytes.
Argument size mismatch: 00b6c7b0 reaction_product(reaction_productst)::produce #2 - expected 36, found 44 bytes.
```

**Comment by lethosor** [comment]
eventful hooks into produce(), so that could explain it. It doesn't appear that anything uses addImprovementFromJob(), though.

**Comment by NCommander** [comment]
The latest commits should fix this. Can you test it @BenLubar?

**Comment by BenLubar** [comment]
Looks good to me

**Comment by BenLubar** [comment]
[![](http://files.explosm.net/comics/Kris/allergic.png?t=285A62)](http://explosm.net/comics/4330/)
