### ISSUE TITLE
GitHub doesn't handle docs/Contributing.rst

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#944]
Contributing.rst was moved to the docs folder in a5d1211feaa3c2416d9ed53dab5a40fd06d9acb1 (@PeridexisErrant) which broke the banner linking to it when creating a new issue/PR. There are a couple options here:
* Move it back to the root directory. I'm not sure how well this would work with Sphinx, though.
* Move it to a `.github` folder (should work, according to [this](https://help.github.com/articles/setting-guidelines-for-repository-contributors/))
* Symlink either of those paths to docs/Contributing.rst - this could cause issues if anyone tries to modify it on Windows, and I don't know for sure if GitHub will handle it.

Thoughts?

**Comment by BenLubar** [comment]
Maybe make a file in .github that just has a link to the documentation hosted on readthedocs?

**Comment by lethosor** [comment]
I think most people would be annoyed at having to jump through two links to get to guidelines and wouldn't necessarily notice changes to them.

Another option, apparently, is to put a shortened version of sorts in an issue/PR template file, which is used to populate the description of a new ticket. I would still like the banner linking to the full version, though.

**Comment by BenLubar** [comment]
If the one under .github can be a symlink, that'd probably be the best. Windows users simply get a 1-line text file with the destination of the link, and because nobody would be editing the symlink version, it shouldn't matter.

**Comment by PeridexisErrant** [comment]
Moving it back to the root dir will be fine!  The only required change is to also change the path in the 'for developers' section of `./index.rst`, so that link keeps working.  All other links should be by tag rather than file path :)

And sorry for breaking it!

**Comment by lethosor** [comment]
Closed in #945
