### ISSUE TITLE
Improve "help $scriptname"

### ISSUE THREAD

**Issue by PeridexisErrant** [DFHack/dfhack#947]
The `help` command (aliases `man`, `?`) could work much more effectively with scripts.  At the moment, it doesn't know anything about script documentation beyond the leading comment.  Using the more recent in-script documentation would be a substantial improvement.

The relevant code is at https://github.com/DFHack/dfhack/blob/master/library/Core.cpp#L256
Psudeocode diff, because I can't write C++, looks like

```
+ if is lua script and "[==== and "]====]" are tokens:
+     return text between tokens
+ if ruby script and "=begin" and "end" are tokens:
+     return text between tokens
  if find_initial_comment():
      return comment
  return "No help found"
```

It's a pretty simplistic text-extraction trick, but that's how the HTML gets built and it all seems to work there!  Simply work out which of the two token sets should be used, and print the text between them if the tokens are present.

**Comment by lethosor** [comment]
Yeah, I've been meaning to do this for a while.

**Comment by myk002** [comment]
this has been implemented for a good while now. closing
