### ISSUE TITLE
Merging documentation updates into master more frequently

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#962]
One problem I've noticed with our current branching system is that some (but not all) documentation updates aren't visible on the master branch until a new release is made. This is an issue for non-release-specific updates, like #944 - after that was fixed, it took almost a month for the change to be merged into master and take effect, during which time we were still without a banner.

I guess one possibility would be to make all updates to develop (still) and cherry-pick necessary ones onto the master branch. This may run into issues with merge conflicts, though - _someone_ made a commit to Contributing.rst on master once, and then cherry-picked it onto develop, and the merge conflict at release time needed to be manually resolved, even though I don't think there was any difference between the two versions of the file. (Also, I'm not sure if it would be possible to cherry-pick commits onto master, since we've set up Github to only allow commits that have passed CI to be pushed to master, and cherry-picked commits would have different IDs by default.)

Anyway, thoughts? It helps that most of our documentation is on ReadTheDocs now, but there are still a few things that need to stay tracked and run into this issue occasionally.

Edit: also #707, #708

**Comment by PeridexisErrant** [comment]
Why not just merge `develop` to `master` at each release?  Tags work pretty well to mark older releases...

**Comment by lethosor** [comment]
That's exactly what we've been doing, and the problem is that documentation updates, even ones that should be visible to end users, aren't visible until we merge develop into master.

**Comment by lethosor** [comment]
We've had a `docs` branch sometimes (based off master) for things like this, so I think this is resolved enough. Basically a "hotfix" from https://datasift.github.io/gitflow/IntroducingGitFlow.html
