### ISSUE TITLE
Script to duplicate work orders

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#965]
From the [forums](http://www.bay12forums.com/smf/index.php?topic=139553.msg7103591#msg7103591)

> Initially placing orders is very useful, but when you want to have pretty much the same order conditions for thread, cloth, (individual) clothes/armour pieces etc etc it can quickly become a timewasting PITA :(
> 
> I guess I'm asking for /user-defined/ order templates.. (preferably independently saved so they can be used across embarks/worlds, but the initial ability to do the above would help immensely!)

Probably not too hard, but can wait until 0.43.05 is working.

**Comment by Snafu-DF** [comment]
"Probably not too hard, but can wait until 0.43.05 is working."

Fairynuff, no rush; tks for the addition here :)

**Comment by lethosor** [comment]
See also #1098 
It doesn't have a "duplicate" feature, as far as I know, but it should be possible to add.

**Comment by BenLubar** [comment]
Instead of "duplicate", it might be easier to split "import" into "clear" and "import but don't clear".
