### ISSUE TITLE
ReadTheDocs: many scripts are missing in some versions

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#968]
This is present in the ["stable" version](http://dfhack.readthedocs.io/en/stable/docs/Scripts.html), which is concerning:

> * Basic Scripts
>   * adv-max-skills
>   * combine-drinks
>   * combine-plants
>   * embark-skills
>   * launch
>   * names
>   * open-legends
>   * prefchange
>   * troubleshoot-item
> 
> * Development Scripts
>   * devel/annc-monitor
>   * devel/click-monitor
>   * devel/modstate-monitor
> 
> * Bugfixing Scripts
> * GUI Scripts
>   * gui/extended-status
>   * gui/load-screen
>   * gui/quickcmd
>   * gui/settings-manager
> 
> * Scripts for Modders
>   * modtools/raw-lint
> 

Also present in 0.43.03-r1 and v0.43.03, but not present in "latest" or any others that I could tell. This may be related to the scripts submodule change, but that's part of master and develop now.

@PeridexisErrant advice would be much appreciated.

**Comment by PeridexisErrant** [comment]
I noticed this a few days ago, but as far as I could tell on investigation it was linked to submodule issues which have since cleared up.  Rebuilding the pages fixed it - if you have/get a readthedocs account I'd be happy to add you to the project there.

**Comment by lethosor** [comment]
Yeah, looks like it's fixed now. Thanks! I would've expected it to rebuild when we fixed the submodule issues, but at least it's working now.

[Here's my new profile](https://readthedocs.org/profiles/lethosor/), if you can add that.

**Comment by PeridexisErrant** [comment]
Done.
