### ISSUE TITLE
Make fix/dead-units less agressive

### ISSUE THREAD

**Issue by PeridexisErrant** [DFHack/dfhack#974]
by adding some additional filters to exclude dead units from deletion.

http://www.bay12forums.com/smf/index.php?topic=158907.0

**Comment by PeridexisErrant** [comment]
Looking at the diff, it's not clear this does anything.

**Comment by lethosor** [comment]
Are you comparing the version at http://www.bay12forums.com/smf/index.php?topic=158907.msg7059986#msg7059986 ?

**Comment by PeridexisErrant** [comment]
Yep.  The forums version removes the check for `dwarf_race`, but that's about it.  There's a fair bit of misleading indentation and unclear conditionals though - by the time I cleaned up it was certainly not a simple patch.
