### ISSUE TITLE
Add additional VTable support for Win64

### ISSUE THREAD

**Issue by figment** [DFHack/dfhack#984]
This should be a pull request but I cannot get my fork straightened out and I'm not sure my solution will 100% cover the issue but does fix my immediate issues.

Basically, TWBT will not load due to render vtable patching not working correctly.  This is due to different registers being used in x64 architecture which breaks the special cases in vmethod lookup so additional cases need to be added.

I will at least proposed this patch for VTableInterpose.cpp:

     library/VTableInterpose.cpp | 19 +++++++++++++++++--
     1 file changed, 17 insertions(+), 2 deletions(-)

    diff --git a/library/VTableInterpose.cpp b/library/VTableInterpose.cpp
    index c547800..27d1772 100644
    --- a/library/VTableInterpose.cpp
    +++ b/library/VTableInterpose.cpp
    @@ -124,6 +124,9 @@ bool DFHack::is_vmethod_pointer_(void *pptr)
         case 0x20FF018BU: // mov eax, [ecx]; jmp [eax]
         case 0x60FF018BU: // mov eax, [ecx]; jmp [eax+0x??]
         case 0xA0FF018BU: // mov eax, [ecx]; jmp [eax+0x????????]
    +#if _M_X64
    +    case 0XFF018B48U: // mov rax, qword ptr[rcx]; jmp qword ptr[rax]
    +#endif
             return true;
         default:
             return false;
    @@ -143,9 +146,21 @@ int DFHack::vmethod_pointer_to_idx_(void *pptr)
             return ((int8_t)pval[1])/sizeof(void*);
         case 0xA0FF018BU: // mov eax, [ecx]; jmp [eax+0x????????]
             return ((int32_t)pval[1])/sizeof(void*);
    -    default:
    -        return -1;
    +#if _M_X64
    +    case 0XFF018B48U:
    +        switch (((uint8_t *)pval)[4])
    +        {
    +        case 0x20:  // mov rax, qword ptr[rcx]; jmp qword ptr[rax]
    +            return 0;
    +        case 0x60:  // mov rax, qword ptr[rcx]; jmp qword ptr[rax+0x??]
    +            return (((uint8_t *)pval)[5]) / sizeof(void*);
    +        case 0xA0:  // mov rax, qword ptr[rcx]; jmp qword ptr[rax+0x????????]
    +            return *(int32_t*)((int8_t *)pval+5) / sizeof(void*);
    +        }
    +        break;
    +#endif
         }
    +    return -1;
     }
     
     void* DFHack::method_pointer_to_addr_(void *pptr)

Also seems like there are issues with rebase pointers on Win64

     library/include/VersionInfo.h | 4 ++--
     1 file changed, 2 insertions(+), 2 deletions(-)

    diff --git a/library/include/VersionInfo.h b/library/include/VersionInfo.h
    index b3d6c83..f6a4dc4 100644
    --- a/library/include/VersionInfo.h
    +++ b/library/include/VersionInfo.h
    @@ -53,7 +53,7 @@ namespace DFHack
             std::map <std::string, uintptr_t> Addresses;
             std::map <std::string, uintptr_t> VTables;
             uintptr_t base;
    -        uintptr_t rebase_delta;
    +        intptr_t rebase_delta;
             std::string version;
             OSType OS;
         public:
    @@ -76,7 +76,7 @@ namespace DFHack
             };
     
             uintptr_t getBase () const { return base; };
    -        int getRebaseDelta() const { return rebase_delta; }
    +        intptr_t getRebaseDelta() const { return rebase_delta; }
             void setBase (const uintptr_t _base) { base = _base; };
             void rebaseTo(const uintptr_t new_base)
             {

**Comment by lethosor** [comment]
Is there a reason for moving the "return -1" out of the switch block that I'm missing? Also, is it actually possible for rebase_delta to be negative?

Other than that, this should be fine - even if this doesn't cover all of the broken cases, fixing this one will have to be done eventually. Do you happen to know if this is MSVC-specific, or can this show up with GCC too?

**Comment by figment** [comment]
Didn't want to create 2 default case statements for each fall-through.  Technically both should return -1.  There is no difference in the generated code and there is probably a couple of ways to write this but I find this the clearest.  Also pretty sure this is MSVC specific as its in a bigger MSVC block. GCC probably handles jumps like this differently but I'm not familiar with it.

I picked intptr_t over uintptr_t as deltas generally aren't unsigned and there was quite a bit of inconsistency already there (uintptr_t vs int).  I suppose it could be negative but in practice its going to be positive in nearly all cases.  It does have to be 64-bit though for Win64.

**Comment by lethosor** [comment]
@quietust Does this look good to you?

**Comment by quietust** [comment]
The above listed patch for VTableInterpose is no longer necessary - the fix I added in 27d222966504223578684db02eb466abddc85679 accounts for it in a slightly cleaner way (by skipping the 0x48 byte, everything else just lines up).

**Comment by lethosor** [comment]
Ah, right. I'll just add the rebase_delta change, then.
