### ISSUE TITLE
Offering my help with Win64 support

### ISSUE THREAD

**Issue by TV4Fun** [DFHack/dfhack#997]
How goes 64-bit support? I'd like to help if I can, but I'd like to know what need are most pressing. @lethosor, you mentioned in the forum thread that some offsets were missing. I might be able to help with that. I have Ida with 64-bit support available.

**Comment by lethosor** [comment]
I (and Quietust) responded to this on IRC, but I don't want to close it in case someone else comes by, so I'll leave it open for now (until r1, maybe?).

**Comment by mprussak** [comment]
If you tell me how, I could also slice out some time to help, I have win64 but no enterprise level decompilers.

**Comment by lethosor** [comment]
I think Win64 globals are done, and hopefully Toady's changes to make addresses available in the next version will be useful. I'll leave this open in case you want to discuss anything else, though.

**Comment by lethosor** [comment]
Thanks for your support. I'm closing this since I don't see much need to keep it open indefinitely, but feel free to help out/report issues/etc.
