### ISSUE TITLE
Lua function "dfhack.gui.makeAnnouncement" does not work.

### ISSUE THREAD

**Issue by milochristiansen** [DFHack/dfhack#999]
Due to the way the position argument is handled this function always fails with an error. This issue also affects the other announcement functions that take a position.

**Comment by lethosor** [comment]
```lua
dfhack.gui.makeAnnouncement(df.announcement_type.CITIZEN_DEATH, {D_DISPLAY=true}, xyz2pos(1,2,3), 'test', COLOR_GREEN)
```

`xyz2pos(x,y,z)` is equivalent to `{x=x,y=y,z=z}`.

There's also a more complicated example in `plugins/lua/siege-engine.lua` or `hack/lua/plugins/siege-engine.lua`.

**Comment by milochristiansen** [comment]
I tried `{x=x,y=y,z=z}`, and it didn't work.

**Comment by lethosor** [comment]
What other arguments did you pass?

**Comment by milochristiansen** [comment]
`dfhack.gui.makeAnnouncement(df.announcement_type.CANCEL_JOB, df.announcement_flags.D_DISPLAY, unit.pos, msg, COLOR_LIGHTRED)`

When that didn't work:

`dfhack.gui.makeAnnouncement(df.announcement_type.CANCEL_JOB, df.announcement_flags.D_DISPLAY, {x = unit.pos.x, y = unit.pos.y, z = unit.pos.z}, msg, COLOR_LIGHTRED)`

The error message indicated the position was the problem.

**Comment by milochristiansen** [comment]
I also added a `new = true` in there after the first try failed (just in case), but no luck.

**Comment by lethosor** [comment]
Your `flags` argument is incorrect. df.announcement_flags is a bitfield, so you can't pass an integer. What exactly is the error you're getting, anyway? I just get
```
(interactive):1: Cannot write field (global).makeAnnouncement(): complex object.
```

I did get this, but only when I mixed up pos2xyz and xyz2pos:
```
./hack/lua/dfhack.lua:187: attempt to index a number value (local 'pos')
```
That's just a result of passing something to pos2xyz() incorrectly.

**Comment by milochristiansen** [comment]
Something like your first error, but following the stack trace took me to the line where the position is assigned. Maybe the line number was off?

**Comment by lethosor** [comment]
I'm not quite sure what you mean. I thought you were passing `unit.pos` directly into makeAnnouncement().
Anyway, does fixing the flags argument work?

**Comment by milochristiansen** [comment]
> I'm not quite sure what you mean. I thought you were passing unit.pos directly into makeAnnouncement().

I tried that first, then I tried creating my own position table, neither one worked. The first time I got the error I followed the stack trace into native code and it took me to the line where the position was assigned, so I assumed that was what was causing the problem.

I can't check to see if fixing the flags works, because I don't have DF on this computer... I can test it and get back to you on tuesday.

**Comment by lethosor** [comment]
I can't see any information in the Lua stack trace that would allow you to track down the exact line in question in the C++ code. And even if you could, the C++ function would never actually be called, because the Lua API catches invalid arguments before trying to call native code.

**Comment by milochristiansen** [comment]
Umm... What? The stack trace I got had line numbers and filenames for the Lua code, then more for native code (DFHack, not DF) that Lua had called into. A bit of looking found these files in the DFHack source distribution. I have no idea what stack traces you get, but the ones I get have all kinds of useful information. I ended up coding my own version of this function in pure Lua using the C++ version as a guide.

**Comment by lethosor** [comment]
This is what I got with your attempt (in the interactive interpreter):
```
(interactive):1: Cannot write field (global).makeAnnouncement(): complex object.
stack traceback:
	[C]: in field 'makeAnnouncement'
	(interactive):1: in main chunk
	[C]: in function 'safecall'
	./hack/lua/dfhack.lua:401: in function 'dfhack.interpreter'
	../dfhack/scripts/lua.lua:74: in local 'f'
	./hack/lua/dfhack.lua:562: in function 'dfhack.run_script_with_env'
	(...tail calls...)
```
Even if you did compile DFHack with debugging information and got Lua stack traces to show line numbers of native code, you wouldn't see anything in the makeAnnouncement() function in library/modules/Gui.cpp because it was never called.

**Comment by milochristiansen** [comment]
Well somehow I did, I have no idea how, but I did.

... Weird, but that's what happened.

Anyway, I'll have more information next tuesday.

**Comment by milochristiansen** [comment]
I was wr... I was wro... *ahem* You were right.

**Comment by lethosor** [comment]
To be fair, I had to look up that example, and I didn't even expect `{D_DISPLAY=true}` to work at first. Bitfields in Lua are friendlier than in C++, apparently.

I might see if it's possible to give better error messages for stuff like this when I get a chance.
